firebase/firebase-js-sdk

README.md
=> Update Firebase Version

package.json
Update package license for easier dist, no need for foreign reference with the license change to Apache-2.0
=> Update license reference in package.json

package.json
=> chore(publish): 4.1.0

package.json
=> chore(package.json): 4.1.2

.gitignore
=> chore(.gitignore): Add '.idea' folder for JetBrains IDEs

src/database/core/Repo.ts
https://github.com/firebase/firebase-js-sdk/blob/fd0728138d88c454f8e38a78f35d831d6365070c/src/database/js-client/core/Repo.js#L86
=> fix(database): Add missing "typeof"

src/messaging/controllers/window-controller.ts
=> fix(messaging): Add check for Fetch API support

.github/CODEOWNERS
Add CODEOWNERS file to auto assign code owners for each component
See: https://github.com/blog/2392-introducing-code-owners for an intro to what this feature is for
=> feat(*): add CODEOWNERS file to .github

package.json
=> chore(publish): 4.1.4

src/database/core/util/util.ts
ISSUES CLOSED: 106
Fixes a critical issue with database failing to decode auth tokens.
=> fix(database): fix issue with base64Decode

package.json
=> chore(publish): 4.1.5

externs/firebase-auth-externs.js, typings/app.d.ts, typings/firebase.d.ts
=> fix(externs): Added externs for 4.3.0 release.

externs/firebase-auth-externs.js
Updates Auth references with the missing OAuthCredential and OAuthProvider classes. In addition adds the missing data from ActionCodeInfo.
=> fix(externs): fix auth externs

packages/firebase/.gitignore, packages/firebase/.npmignore
Trimming some files from the firebase package.
=> Augmenting .npmignore and .gitignore

packages/firebase/app/index.d.ts, packages/firebase/index.d.ts
Fixes issue with .d.ts files in the main firebase package
=> Fix default include problem

packages/app/README.md, packages/auth/README.md, packages/database/README.md, packages/firestore/README.md, packages/messaging/README.md, packages/polyfill/README.md, packages/storage/README.md, packages/util/README.md
Several of the README files had a bad link. So I fixed that and then removed the backticks on the primary name (I think NPM will dedupe this title but I'm not 100% sure)
=> Update READMEs of all of the packages

packages/firebase/package.json
=> Add "react-native" prop to firebase/package.json

integration/shared/validator.js, packages/app/gulpfile.js, packages/app/package.json
Fixing the `firebase.SDK_VERSION` injection.
Regressed in `v4.5.1`
Fixes #225
=> @firebase/app Version Fix

tools/config.js
I wanted to make it so that you can leverage the cached credentials if available so you don't have to log in as much.
=> Leverage Cached Token from firebase-tools

integration/messaging/package.json
Refactors `integration/messaging/package.json` to retry the mocha tests 3 times in the event of failures.
=> Retry Messaging Integration Test Failures

integration/messaging/test/send-receive-msg.js
Sorry if the commit msg format is incorrect, couldn't follow the link to your commit msg guidelines; may raise an issue on that.
=> typo in comment within `sendFCMMessage` function

.travis.yml
Node version changed. Pinning back to version 8
=> Pin Node version to 8 (released as LTS)

.github/CODEOWNERS
Adding @TMSCH to the auth code owners
=> [ci skip] Adding new auth code owner

packages/firestore/src/platform_browser/webchannel_connection.ts
(and also remove inaccurate comments / logs about retrying)
=> b/67049845: Remove error logging on failed WebChannel RPCs.

packages/firestore/test/integration/util/helpers.ts
Note that I couldn't actually reproduce the 'already open in another tab' error, I think because we create a new FirebaseApp instance (with a unique app name) for every test...  But I did confirm that cleanup now runs after failed tests, whereas it didn't before.
=> b/68783609: Ensure test cleanup runs after failed tests.

.travis.yml, config/ci.config.json
This supplies a default CI config for our project so that external contributors can run tests!
=> Supply default (working) config for CI environment

packages/firestore/CHANGELOG.md
I forgot to include this in my previous PR...
=> Add Node.JS support to changelog.

ENVIRONMENTS.md
=> Remove IE9 and 10 in ENVIRONMENTS.md

README.md
Closure compiler requires java 8, update setup docs.
=> Add Java dependency

scripts/prepublish.sh
Refactor `lerna publish` to use exact versioning
FIXES: #348
=> Lerna exact

packages/auth/src/rpchandler.js, packages/auth/test/rpchandler_test.js
=> handled empty auth uri error

packages/firestore/src/remote/remote_store.ts
This change was requested as part of the new enable/disable network API.
=> Add requested log line

packages/firestore/package.json, packages/firestore/tslint.json
We have 134 outstanding errors, but at least you can lint now. :-)
=> Add an initial tslint.json and add a "yarn lint" command to use it.

packages/database-types/index.d.ts
=> Narrow ThenableReference type definition

packages/firestore/test/integration/api/server_timestamp.test.ts, packages/firestore/test/integration/util/firebase_export.ts
Port of https://github.com/firebase/firebase-ios-sdk/pull/621
=>  Fixing potential race in ServerTimestamp tests

packages/app-types/package.json, packages/app/package.json, packages/auth-types/package.json, packages/auth/package.json, packages/database-types/package.json, packages/database/package.json, packages/firestore-types/package.json, packages/firestore/package.json, packages/messaging-types/package.json, packages/messaging/package.json, packages/polyfill/package.json, packages/storage-types/package.json, packages/storage/package.json, packages/util/package.json, packages/webchannel-wrapper/package.json
Adds some missing meta to the `@firebase/*` packages.
Fixes #415
=> package.json Fixes

tools/pretest.js
Accidentally forwarded users to an internal URL
=> Removing internal URL

tools/gitHooks/license.js
Accepting '2018' in the License Header.
=> Welcoming the new year

packages/firestore/src/util/sorted_map.ts, packages/firestore/src/util/sorted_set.ts
=> Removing any from LLRBTree

packages/firestore/package.json
This should fail until https://github.com/firebase/firebase-js-sdk/pull/447 is merged.
=> Adding lint hook

integration/messaging/package.json, integration/messaging/test/static/app.js, integration/messaging/test/static/default-sw/index.html, integration/messaging/test/static/invalid-manifest/index.html, integration/messaging/test/static/valid-manifest/index.html, integration/messaging/test/static/valid-no-vapid-key/index.html, integration/messaging/test/static/valid-vapid-key/index.html, integration/messaging/test/test-default-sw.js, integration/messaging/test/test-send.js, integration/messaging/test/test-updateToken.js, integration/messaging/test/test-valid-manifest.js, integration/messaging/test/utils/retrieveFCMToken.js, integration/messaging/test/utils/timeForward.js, yarn.lock
=> Add integration tests for updateToken

packages/template-types/index.d.ts, packages/template-types/package.json, packages/template-types/test/default.test.ts, packages/template-types/tsconfig.json, packages/template/.npmignore, packages/template/README.md, packages/template/gulpfile.js, packages/template/index.node.ts, packages/template/index.ts, packages/template/karma.conf.js, packages/template/package.json, packages/template/src/index.ts, packages/template/test/index.test.ts, packages/template/tsconfig.json
For those users looking to create new packages in the SDK I figured it'd be good to have a template.
This is just some bare bones files that can be copied to create a working base for a new package.
=> Add a new package template

.github/CODEOWNERS, .github/ISSUE_TEMPLATE.md
- Updates the `ISSUE_TEMPLATE.md` to use a stackblitz example rather than a JSBin
- Updates the `CODEOWNERS` file to include @pinarx as an owner for messaging
=> .github Directory Updates

packages/util/index.ts
master isn't prettified so I'm getting spurious diffs when I try to create PRs...
=> [AUTOMATED]: Prettier Code Styling

packages/firestore/src/auth/user.ts, packages/firestore/src/local/indexeddb_mutation_queue.ts
change the internal api isUnauthenticated() to isAuthenticated() for better style naming.
yarn test
n/a
=> renaming isUnauthenticated() to isAuthenticated() for better style

packages/firebase/index.d.ts
Updating the types in firebase/index.d.ts to pull in the recent API changes.
Fixes: https://github.com/firebase/firebase-js-sdk/issues/498
=> Updating firebase/index.d.ts

config/karma.base.js, integration/messaging/package.json
We should probably do some more investigation into why this isn't working.
Sorry for the prettier changes.
=> Disabling Flaky Tests

packages/app/gulpfile.js, packages/database/gulpfile.js, packages/firestore/gulpfile.js, packages/messaging/gulpfile.js, packages/polyfill/gulpfile.js, packages/storage/gulpfile.js, packages/template/gulpfile.js, packages/util/gulpfile.js
The dev watcher task was missing the top level files.
This was an oversight, so I wanted to address it as it makes life easier.
=> Dev Script Update

scripts/release/utils/inquirer.js
Fixes an oversight introduced in #551
=> Fixes an issue with staged release version

packages/database/src/core/util/util.ts
Fixes https://github.com/firebase/firebase-admin-node/issues/230
=> Fix missing DB logs issue

packages/auth/demo/public/common.js, packages/auth/demo/public/index.html, packages/auth/demo/public/script.js, packages/auth/demo/public/web-worker.js
This helps test that Auth API works as expected in that environment.
=> Adds Auth tests to demo app for web worker environment functionality.

packages/auth/.gitignore, packages/auth/buildtools/run_demo.sh, packages/auth/demo/firebase.json, packages/auth/demo/functions/index.js, packages/auth/demo/functions/package-lock.json, packages/auth/demo/functions/package.json, packages/auth/demo/public/index.html, packages/auth/demo/public/script.js, packages/auth/demo/public/service-worker.js, packages/auth/demo/public/web-worker.js
This modifies the service worker to append the ID token in every fetch
request via a custom HTTP header.
Using Functions with Hosting, an HTTP endpoint was setup which will
parse the ID token from the header and verify it using Admin SDK and
then return a status response.
A button is added to the demo app to test this. When a user is signed
in, the user's uid is returned, otherwise an error is shown.
=> Adds tests in demo app for service worker compatibility with Firebase Auth

packages/firebase/app/index.d.ts
=> added new method declarations

packages/polyfill/src/polyfills/promise.ts
=> Fix implicit global variable

packages/messaging/src/helpers/array-buffer-to-base64.ts
Fixes: https://github.com/firebase/firebase-js-sdk/issues/503
=> Fixes getToken in SW

packages/messaging/src/models/iid-model.ts, packages/messaging/test/controller-get-token.test.ts, packages/messaging/test/iid-model-delete-token.test.ts, packages/messaging/test/iid-model-get-token.test.ts, packages/messaging/test/iid-model-update-token.test.ts, packages/messaging/test/make-fake-sw-reg.ts, packages/messaging/test/sw-controller.test.ts, packages/messaging/test/tokenDetailsModel-getToken.test.ts
I was looking through the code and wanted to make a change but after noticing the lack of types I just figured it would be worth adding that first.
After tidying up the model, I noticed the tests were failing and it essentially opened a can of worms across the tests (A couple of passing tests that were throwing asynchronously or duplicate names.
=> IID Model types

packages/messaging/src/models/iid-model.ts
Fixes some errors we are seeing in the messaging compilation.
=> Fixing "Type could be null" errors

packages/messaging/src/controllers/sw-controller.ts, packages/messaging/src/interfaces/vapid-details.ts, packages/messaging/src/models/db-interface.ts, packages/messaging/src/models/token-details-model.ts, packages/messaging/src/models/vapid-details-model.ts, packages/messaging/test/db-interface.test.ts, packages/messaging/test/deletedb.test.ts, packages/messaging/test/tokenDetailsModel-deleteToken.test.ts, packages/messaging/test/tokenDetailsModel-getToken.test.ts, packages/messaging/test/tokenDetailsModel-saveToken.test.ts, packages/messaging/test/vapid-details-model-delete.test.ts, packages/messaging/test/vapid-details-model-get.test.ts, packages/messaging/test/vapid-details-model-save.test.ts
Simplifies a lot of IndexedDb operations and removes most of the duplicated code. Also refactors tests.
=>  Refactor IndexedDb operations

packages/auth/src/iframeclient/iframewrapper.js, packages/auth/src/recaptchaverifier/recaptchaverifier.js, packages/auth/src/rpchandler.js, packages/auth/src/storage/asyncstorage.js, packages/auth/src/storage/factory.js, packages/auth/src/storage/hybridindexeddb.js, packages/auth/src/storage/indexeddb.js, packages/auth/src/storage/inmemorystorage.js, packages/auth/src/storage/localstorage.js, packages/auth/src/storage/mockstorage.js, packages/auth/src/storage/nullstorage.js, packages/auth/src/storage/sessionstorage.js, packages/auth/src/utils.js, packages/auth/test/authstorage_test.js, packages/auth/test/iframeclient/iframewrapper_test.js, packages/auth/test/recaptchaverifier/recaptchaverifier_test.js, packages/auth/test/rpchandler_test.js, packages/auth/test/storage/factory_test.js, packages/auth/test/storage/hybridindexeddb_test.js, packages/auth/test/storage/indexeddb_test.js, packages/auth/test/utils_test.js
=> Indexeddb fix

.github/CODEOWNERS
Remove @tmsch from auth code owners
=> Update Auth codeowners

config/tsconfig.base.json
es2015 includes es5 and es2015.promise
https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es2015.d.ts
=> Remove redundant lib declarations

packages/firestore/src/api/user_data_converter.ts
I made some minor tweaks while porting https://github.com/firebase/firebase-js-sdk/commit/b14678002bf6e8cc9ebd7561efbafe29315ceb8e to iOS. The big diff is because I rearranged methods but I did that in a separate commit to make reviewing easier.
=> Minor additional UserDataConverter cleanup.

README.md
This PR should be merged after #674
=> Saucelabs Badges/Attribution

packages/messaging/src/controllers/sw-controller.ts, packages/messaging/test/sw-controller.test.ts
Also reorders and refactors some tests.
=> Add a warning for notifications with too many actions

packages/auth-types/index.d.ts, packages/auth/src/auth.js, packages/auth/src/authuser.js, packages/auth/src/deprecation.js, packages/auth/src/exports_auth.js, packages/auth/test/auth_test.js, packages/auth/test/authuser_test.js
=> deprecation for I/O

packages/auth-types/index.d.ts, packages/auth/demo/public/index.html, packages/auth/demo/public/script.js, packages/auth/src/args.js, packages/auth/src/auth.js, packages/auth/src/authuser.js, packages/auth/src/error_auth.js, packages/auth/src/exports_auth.js, packages/auth/src/token.js, packages/auth/test/args_test.js, packages/auth/test/auth_test.js, packages/auth/test/authuser_test.js, packages/auth/test/testhelper.js, packages/auth/test/token_test.js
=> updateCurrentUser api

packages/auth/src/utils.js, packages/auth/test/utils_test.js
=> fix diff function to do deep comparison

packages/auth-types/index.d.ts, packages/auth/demo/public/index.html, packages/auth/demo/public/script.js, packages/auth/src/auth.js, packages/auth/src/authsettings.js, packages/auth/src/exports_auth.js, packages/auth/src/recaptchaverifier/grecaptcha.js, packages/auth/src/recaptchaverifier/grecaptchamock.js, packages/auth/src/recaptchaverifier/loader.js, packages/auth/src/recaptchaverifier/mockloader.js, packages/auth/src/recaptchaverifier/realloader.js, packages/auth/src/recaptchaverifier/recaptchaverifier.js, packages/auth/src/utils.js, packages/auth/test/auth_test.js, packages/auth/test/authsettings_test.js, packages/auth/test/recaptchaverifier/grecaptchamock_test.js, packages/auth/test/recaptchaverifier/mockloader_test.js, packages/auth/test/recaptchaverifier/realloader_test.js, packages/auth/test/recaptchaverifier/recaptchaverifier_test.js, packages/auth/test/utils_test.js
=> phone auth testing

packages/firebase/src/index.ts
Fixes some typos/wording in the `console.warn`
=> Wording Fixes

packages/firebase/index.d.ts
Fixes #705, "Add TypeScript definitions for firebase.functions()", also described here: https://stackoverflow.com/questions/49669360/using-firebase-functions-from-web-sdk-using-typescript
=> Added TypeScript definitions for firebase.functions()

packages/firebase/README.md
=> docs(firebase): gcloud -> google-cloud

packages/firebase/index.d.ts, packages/firestore-types/index.d.ts, packages/firestore/src/api/database.ts, packages/firestore/src/core/query.ts, packages/firestore/src/remote/serializer.ts, packages/firestore/test/integration/api/database.test.ts, packages/firestore/test/integration/api/query.test.ts, packages/firestore/test/integration/api/validation.test.ts, packages/firestore/test/integration/util/helpers.ts, packages/firestore/test/unit/core/query.test.ts, packages/firestore/test/unit/remote/node/serializer.test.ts
[This review is not super urgent if you're busy this week]
Port of https://github.com/firebase/firebase-ios-sdk/commit/e4384c3e809556e75907df74cd116307f397472f
=> Array Contains support (not publicly exposed yet).

packages/app-types/private.d.ts, packages/messaging-types/index.d.ts, packages/messaging/src/controllers/controller-interface.ts, packages/messaging/src/controllers/window-controller.ts, packages/util/src/subscribe.ts, packages/util/test/subscribe.test.ts
Uses `Partial` from TS to create a PartialObserver from Observer.
=> Combine Observer and PartialObserver types

packages/firebase/.gitignore, packages/firebase/tsconfig.json
=> SubImport Typings Fix

.github/CODEOWNERS
=> Update messaging CODEOWNERS

packages/firebase/index.d.ts, packages/firestore-types/index.d.ts
Fallout from https://critique.corp.google.com/#review/196568172
=> Remove part of the mergeField comment

packages/firebase/README.md
=> Update import statements in documentation

packages/firebase/app/package.json
Ensuring the CJS build gets included when needed.
=> Add pkg.browser to firebase/app

README.md
Every time there is a new release, I need to go searching for this - not sure that everyone is aware of where these are placed online, seems to make sense to have a link included here.
=> DOC: Add a link to the release notes in README.md

packages/database/src/api/DataSnapshot.ts, packages/database/src/core/snap/ChildrenNode.ts, packages/firebase/index.d.ts
This is a follow-up PR to #840
=> Propagating RTDB type changes

packages/messaging/src/models/iid-model.ts, packages/messaging/test/iid-model.test.ts
=> Use isArrayBufferEqual to compare VAPID keys

packages/firestore/src/local/indexeddb_mutation_queue.ts, packages/firestore/src/local/indexeddb_query_cache.ts, packages/firestore/src/local/indexeddb_remote_document_cache.ts, packages/firestore/src/local/simple_db.ts
Addresses a comment in https://github.com/firebase/firebase-js-sdk/pull/782 against `master`
=> Moving getStore() to SimpleDb

packages/messaging/index.ts
Messaging needs cookies to be enabled.
=> Check if cookies are enabled

packages/firestore/test/integration/api/database.test.ts
Hmmm. Looks like I never pushed my changes to respond to the PR feedback.
=> Addressing comments for https://github.com/firebase/firebase-js-sdk/pull/877

.github/CODEOWNERS
Adding a backup owner for JS SDK stuff.
=> Adding @hiranya911 to root owners

packages/firestore/test/unit/specs/limbo_spec.test.ts
This is a test that demonstrates b/72533250 if you uncomment the line after the TODO.
I'm punting on the actual bugfix at the moment because I think the best fix is a semi-large refactor.
=> Test for b/72533250.

packages/auth/src/storage/hybridindexeddb.js
Fixes issue when hybrid indexedDB fallsback to localStorage because the write/read test fails because multiple windows or instances try to write/read/delete from the same indexedDB entry. Instead of a common key __sak, we use a random one minimizing the chances of collision.
=> fix(auth): Fixes issue when hybrid indexedDB incorrectly fallsback to localStorage

packages/firestore/src/local/shared_client_state.ts
This PR adds logging for all CRUD operations in SharedClientState, similar to what we do in SimpleDb.
=> [Multi-Tab] Adding logging to SharedClientState (small)

packages/firestore/test/integration/util/events_accumulator.ts, packages/firestore/test/unit/specs/describe_spec.ts, packages/firestore/test/unit/specs/listen_spec.test.ts, packages/firestore/test/unit/specs/offline_spec.test.ts, packages/firestore/test/unit/specs/write_spec.test.ts
Port of spec changes from here: https://github.com/firebase/firebase-ios-sdk/pull/1410
=> Add support for 'no-lru' tag to spec tests

.github/ISSUE_TEMPLATE.md
I keep needing this information in issue reports.
=> Add "browser version" to issue template

packages/firebase/index.d.ts, packages/functions/index.ts
This was already implemented. Just adding it to the type definitions.
=> Add an optional parameter for region to Functions constructor.

.github/CODEOWNERS
To help increase the bus factor here, adding some folks to help w/ reviews
=> Updating list of "Top Level" reviewers

packages/firestore/src/local/local_store.ts, packages/firestore/src/local/shared_client_state.ts, packages/firestore/test/unit/specs/write_spec.test.ts
Spec tests for user changes + small bugfix.
=> [Multi-Tab] Handling user changes

packages/firestore/src/local/shared_client_state.ts, packages/firestore/test/unit/local/persistence_test_helpers.ts, packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
It's 6 pm and I haven't sent a PR to Mike yet. Fixing this.
=> [Multi-Tab] Rename WebStorage key for Multi-Tab

packages/firestore-types/index.d.ts, packages/firestore/src/api/database.ts, packages/firestore/src/core/firestore_client.ts, packages/firestore/src/local/indexeddb_persistence.ts
=> Rename synchronizeTabs to experimentalTabSynchronization

packages/firestore/CHANGELOG.md
@jshcrowthe Is this the right version?
=> Add a release note for the fix to #1548

packages/auth/src/rpchandler.js, packages/auth/test/rpchandler_test.js
catch server error RESET_PASSWORD_EXCEED_LIMIT and translate to client error TOO_MANY_ATTEMPTS_TRY_LATER
=> catch server error RESET_PASSWORD_EXCEED_LIMIT

packages/firestore/package.json, yarn.lock
Addresses https://github.com/grpc/grpc-node/issues/453 in Firestore.
Also fixes https://github.com/firebase/firebase-js-sdk/issues/1036
=> Upgrade GRPC to 1.13.1

packages/firestore/src/remote/remote_store.ts
This seems to work.
FWIW- I think I should have actually kept my stopStreams() / startStreamsIfNecessary() refactor from before rather than using enableNetwork() / disableNetwork() for applyPrimaryState, since we don't want applyPrimaryState to change the networkEnabled flag.
=> Remove canUseNetwork state.

packages/firestore/test/unit/specs/spec_builder.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
Move isPrimary assert to the spec test runner to reduce size of JSON output.
=> Move isPrimary assert to the spec test runner

packages/rxfire/package.json
Switching the `private` flag to `false` and adding a version number.
=> Prep rxfire release

packages/rxfire/package.json
Simple `package.json` changes.
=> Make RxFire public

packages/firestore/src/local/indexeddb_persistence.ts
=> Updating the indexeddb_persistence class comment

packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/test/unit/local/indexeddb_persistence.test.ts
... until we expose this publicly.
=> Use previous message for primary lease error

packages/firestore/test/unit/specs/spec_test_runner.ts
=> Spec Test: Sorting Query events

packages/firestore/src/core/sync_engine.ts, packages/firestore/test/integration/api/get_options.test.ts
Port of https://github.com/firebase/firebase-ios-sdk/pull/1413
=> Drop limbo collector

packages/firestore/src/core/sync_engine.ts, packages/firestore/src/local/shared_client_state.ts, packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
As per go/garbage-collection. This works in Chrome, Firefox and Safari.
=> Garbage Collect Mutation Batch Keys

packages/firestore/test/unit/specs/perf_spec.test.ts
I just learned that the spec builder is mutable... Small cleanup PR for the perf tests.
=> Using mutable spec runner

packages/firestore/src/local/indexeddb_persistence.ts
One more cleanup PR to delete zombied client IDs that may still linger in IndexedDb. This is "mostly" untested, since my client doesn't have an inactive clients with leftover zombie IDs.
=> Delete leftover zombied client IDs

packages/firestore/CHANGELOG.md, packages/firestore/src/platform_browser/browser_platform.ts
Adds Changelog entry for #1138
=> Add Changelog entry for ReactNative fix

packages/auth/src/storage/indexeddb.js, packages/auth/test/storage/indexeddb_test.js
Rewrites Auth indexedDB polling to avoid using infinite promise chaining.
=> Rewrites Auth indexedDB polling

packages/auth/src/error_withcredential.js, packages/auth/src/utils.js, packages/auth/test/error_test.js
We need to catch that and suppress it.
=> `navigator.serviceWorker.ready` rejects in chrome extensions.

.github/CODEOWNERS
Adding the rest of our team to Firestore OWNERS.
=> Adding Firestore team to code owners

packages/firestore-types/index.d.ts, packages/firestore/CHANGELOG.md, packages/firestore/src/api/database.ts, packages/firestore/src/core/sync_engine.ts, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/indexeddb_remote_document_cache.ts, packages/firestore/src/local/local_store.ts, packages/firestore/test/unit/local/indexeddb_persistence.test.ts, packages/firestore/test/unit/specs/spec_test_runner.ts, packages/rxfire/firestore/collection/index.ts
As per Josh: Don't merge until Friday to make sure it doesn't go out this week.
=> Expose multi-tab flag

.github/CODEOWNERS
=> add @Feiyang1 to the global code owners list

packages/functions/test/browser/callable.test.ts
check browser compatibility more reliably before running the test
=> Functions test fix

packages/testing/package.json, packages/testing/src/api/index.ts, packages/testing/test/database.test.ts
Discovered these issues when trying to set up sets in Typescript
=> Fix a few issues with the @firebase/testing package.json

packages/firebase/index.d.ts
null is not possible in the apps array, hence I'm updating the typing.
=> remove incorrect typing

packages/firebase/index.d.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/1273
=> Uncomment PersistenceSettings in all the files

packages/firestore/CHANGELOG.md
This is the web port of
https://github.com/firebase/firebase-android-sdk/pull/49
=> Backporting reviewer suggested comments from cl/214509458

yarn.lock
with yarn 1.10.0 release, a new integrity field is added to the lock file.
=> update yarn.lock with integrity field

README.md
=> update firebase version in readme example

.github/CODEOWNERS, packages/testing/src/api/index.ts
=> update storage owner

packages/firestore/src/core/sync_engine.ts, packages/firestore/src/core/target_id_generator.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/mutation_queue.ts, packages/firestore/src/local/query_cache.ts
I went thru the structural changes of the Multi-Tab PR (#1000) and noticed some areas that could use porting notes.
=> Add missing Porting Notes

packages/firebase/rollup.config.js
create component bundles in umd to support lazy loading in requireJS
=>  create component bundles in umd to support lazy loading in requireJS

packages/storage/src/implementation/location.ts
=> Add support for `_` in buckets

packages/auth/src/rpchandler.js, packages/auth/src/utils.js, packages/auth/test/rpchandler_test.js, packages/auth/test/utils_test.js
Changed email validation logic to allow international email address.
=> Changed email validation logic to allow international email address

packages/testing/src/api/index.ts
This should resolve https://github.com/firebase/firebase-js-sdk/issues/1445
=> Allow both databaseName and projectId

packages/firebase/README.md
As the title said I am adding some code syntax highlighting in the `README.md`
=> Add code syntax highlighting

.github/CODEOWNERS, packages/testing/src/api/index.ts
The PR addresses 2 issues:
1. the current CODEOWNERS setup is too rigid and it doesn't work in case like cross package changes and doesn't provide an escape hatch when owners are not available.
2. Automatic review requests are spammy for large teams.
=> use secret team as code owners to avoid review requests spam.

packages/firestore/package.json, packages/testing/package.json, yarn.lock
https://github.com/firebase/firebase-js-sdk/issues/1444
=> update grpc to 1.17.0

packages/firestore/src/local/indexeddb_mutation_queue.ts, packages/firestore/src/local/indexeddb_schema.ts, packages/firestore/src/local/memory_mutation_queue.ts, packages/firestore/test/unit/local/mutation_queue.test.ts
A straightforward port of https://github.com/firebase/firebase-ios-sdk/pull/2243.
=> Port "Stop persisting last acknowledged batch ID" from iOS

packages/firestore/CHANGELOG.md
https://github.com/firebase/firebase-android-sdk/pull/207
=> Backport changelog fixups

packages/firestore/package.json, packages/testing/package.json, yarn.lock
https://github.com/grpc/grpc-node/releases/tag/grpc%401.18.0
With Electron 4 prebuilt binaries.
=> update grpc to 1.18.0

packages/rxfire/docs/storage.md
Correct import path should be `firebase/storage`
=> Update import path

tools/gitHooks/license.js
=> update license header text

scripts/release/cli.js, scripts/release/utils/inquirer.js, scripts/release/utils/lerna.js
=> Use a different lerna command to accurately find changed packages

.github/CODEOWNERS
=> Add James Daniels to RxFire owners

packages/firestore/index.console.ts, packages/firestore/package.json, packages/firestore/tools/console.build.js
Reattempt at creating the build target for console.
The original PR: https://github.com/firebase/firebase-js-sdk/pull/374
=> Firestore Console Build

config/functions/index.js, config/karma.base.js, config/karma.saucelabs.js, config/webpack.test.js, packages/firebase/rollup-internal.config.js, scripts/emulator-testing/database-test-runner.ts, scripts/emulator-testing/emulators/database-emulator.ts, scripts/emulator-testing/emulators/emulator.ts, scripts/emulator-testing/emulators/firestore-emulator.ts, scripts/emulator-testing/firestore-test-runner.ts, scripts/release/cli.js, scripts/release/utils/banner.js, scripts/release/utils/constants.js, scripts/release/utils/git.js, scripts/release/utils/inquirer.js, scripts/release/utils/lerna.js, scripts/release/utils/npm.js, scripts/release/utils/tests.js, scripts/release/utils/workspace.js, scripts/release/utils/yarn.js, tools/config.js, tools/gitHooks/prepush.js, tools/gitHooks/prettier.js, tools/pretest.js, tools/repl.js
Somehow did not catch some minor syntax mistakes in last commit.  This fix has been tested in the actual third_party environment by pulling this branch.
=> Fix bugs in internal rollup config

packages/webchannel-wrapper/package.json, packages/webchannel-wrapper/tools/build.js, yarn.lock
* Upgraded closure-builder (necessary to be able to specify multiple defines).
* Disabled closure debug code (i.e. in particular logging) and several legacy
fallbacks that we don't need.
=> Upgrade closure-builder and optimize build size.

packages/firebase/index.d.ts
d.ts is not consistent with the reference doc. This change brings index.d.ts up to date.
=> fix(auth): add OAuthCredential in typing file.

package.json, packages/rxfire/rollup.config.js
=> include rxfire in the global build scripts

packages/rxfire/docs/firestore.md
docChanges not found in rxfire/firestore package
=> Replaced docChanges method by collectionChanges

packages/firebase/index.d.ts
Address https://github.com/firebase/firebase-js-sdk/issues/1580
=> fix (typing): replace any with concrete types

packages/webchannel-wrapper/tools/build.js
I accidentally broke this while tweaking my last change to write to a temp folder.
=> Fix webchannel-wrapper sourcemap.

config/functions/.ncurc.json, integration/browserify/.ncurc.json, integration/firebase-typings/.ncurc.json, integration/firestore/.ncurc.json, integration/messaging/.ncurc.json, integration/typescript/.ncurc.json, integration/webpack/.ncurc.json, packages/app-types/.ncurc.json, packages/app/.ncurc.json, packages/auth-types/.ncurc.json, packages/auth/.ncurc.json, packages/database-types/.ncurc.json, packages/database/.ncurc.json, packages/firebase/.ncurc.json, packages/firestore-types/.ncurc.json, packages/firestore/.ncurc.json, packages/functions-types/.ncurc.json, packages/functions/.ncurc.json, packages/logger/.ncurc.json, packages/messaging-types/.ncurc.json, packages/messaging/.ncurc.json, packages/polyfill/.ncurc.json, packages/rxfire/.ncurc.json, packages/storage-types/.ncurc.json, packages/storage/.ncurc.json, packages/template-types/.ncurc.json, packages/template/.ncurc.json, packages/testing/.ncurc.json, packages/util/.ncurc.json, packages/webchannel-wrapper/.ncurc.json
This is the last PR before we enable auto dependency updates with https://github.com/GoogleCloudPlatform/repository-gardener :)
=> add deps update configuration to all projects

packages/firebase/index.d.ts, packages/rxfire/package.json
I also included the change to make rxFire participate in the repo level test.
=> Add delete() back to index.d.ts

packages/firestore/src/api/credentials.ts
=> b/32935141: Clean up remaining TODOs in first-party-auth implementation.

packages/firebase/index.d.ts
=> Fixing a few typos.

packages/firebase/index.d.ts, scripts/docgen/generate-docs.js
Allows homepage navigation to work when viewing generated docs locally. Devsite should still be able to redirect a url with extension to the url with no extension, to fit site style.
=> Add html extension to toc on homepage

packages/polyfill/index.ts, packages/polyfill/package.json, yarn.lock
=> chore: upgrade core-js to v3

packages/database/src/core/view/QueryParams.ts
Fix lint: Two NOs make a YES 😄
=> Fix lint: Two NOs make a YES

packages/auth/gulpfile.js
I introduced a typo in #818, this PR fixes it.
=> Fix a typo in a build file of the auth package

package.json
Easy way to run prettier manually on the whole repo.
=> Add npm script to run prettier on whole repo

packages/auth-types/index.d.ts, packages/firebase/index.d.ts
Added the constructor definition on OAuthProvider in index.d.ts files.
=> Added the constructor definition on OAuthProvider

packages/auth/demo/public/script.js
replaced methods that are deprecated in v5 in demo app.
=> replaced methods that are deprecated with new ones

packages/firebase/package.json, packages/firebase/rollup.config.js
Create a "components" package.json field listing each SDK component.  Usable by rollup for building packages and by the release CLI script for creating CDN paths for each package.
=> Create package.json field for components

README.md
Add an NPM version badge and make release notes link more prominent using https://shields.io/ badges.
=> Add version and release notes badge

packages/database-types/index.d.ts, packages/database/CHANGELOG.md, packages/database/src/api/Query.ts, packages/database/src/core/view/Change.ts, packages/firebase/index.d.ts
This PR is meant to be part of the next major release.
=> Fix the type annotations in the RTDB Query.on/off/once API.

integration/shared/namespaceDefinition.json, packages/app-types/index.d.ts, packages/app/src/firebaseNamespaceCore.ts
=> Remove Promise from FirebaseNamespace

packages/installations/src/functions/delete-installation.test.ts, packages/installations/src/functions/get-token.test.ts, packages/installations/src/helpers/get-installation-entry.test.ts, packages/installations/src/helpers/idb-manager.test.ts, packages/installations/src/testing/setup.ts, packages/installations/src/util/sleep.test.ts
Fixes flaky tests. Removes some redundant code.
=> Use Sinon fake timers in tests that deal with time

packages/auth/demo/public/web-worker.js, packages/auth/src/auth.js
replaced firebase promise with native promise
=> replaced firebase promise with native promise

.travis.yml, packages/auth/buildtools/run_tests.sh
Exit with an error code if any step failed.
=> report auth test failures

packages/installations/src/functions/get-token.test.ts, packages/installations/src/helpers/get-installation-entry.test.ts, packages/installations/src/helpers/idb-manager.test.ts, packages/installations/src/helpers/idb-manager.ts
=> Remove return type generics

packages/firebase/index.d.ts
Just adding code-font formatting to some literals.
=> Fixing some formatting.

packages/firestore/src/api/database.ts, packages/firestore/src/core/query.ts, packages/firestore/test/integration/api/validation.test.ts
> If you can think of a better way to structure the array-contains, in, array-contains-any logic, please advise :)
I accepted this challenge and this is what I came up with (after fiddling around for a while).  If you're on board I can merge it into your PR...  else we can drop it or you can take it and tweak it or whatever...
I also re-arranged the test cases a tad.
=> Taking a stab at simplifying validation for array / disjunctive ops.

packages/performance/.eslintrc.json, packages/performance/index.ts, packages/performance/package.json, packages/performance/src/controllers/perf.test.ts, packages/performance/src/controllers/perf.ts, packages/performance/src/resources/network_request.ts, packages/performance/src/resources/trace.test.ts, packages/performance/src/resources/trace.ts, packages/performance/src/services/api_service.ts, packages/performance/src/services/cc_service.test.ts, packages/performance/src/services/cc_service.ts, packages/performance/src/services/iid_service.ts, packages/performance/src/services/initialization_service.test.ts, packages/performance/src/services/initialization_service.ts, packages/performance/src/services/oob_resources_service.test.ts, packages/performance/src/services/oob_resources_service.ts, packages/performance/src/services/perf_logger.ts, packages/performance/src/services/remote_config_service.test.ts, packages/performance/src/services/remote_config_service.ts, packages/performance/src/utils/attributes_utils.ts
There is a few floating promises (no error handler). @alikn, Can you check if they are harmless, or if we need to add error handlers for them?
=>  enable eslint in Performance

packages/firestore/CHANGELOG.md, packages/firestore/src/platform_browser/browser_connectivity_monitor.ts, packages/firestore/src/platform_browser/browser_platform.ts
=> Check that window is complete in BrowserConnectivityMonitor

packages/installations/src/functions/get-id.test.ts, packages/installations/src/functions/get-id.ts, packages/installations/src/functions/get-token.test.ts, packages/installations/src/functions/get-token.ts, packages/installations/src/helpers/refresh-auth-token.test.ts, packages/installations/src/helpers/refresh-auth-token.ts
Moved fetchAuthToken to helpers and renamed it to refreshAuthToken.
=> Generate a new token after getId calls if there is no valid token

packages/firebase/index.d.ts
* Change to index.d.ts file comments to show code fonts. Comments are used in generated web reference docs. Code fonts will make the generated web reference docs more readable.
=> add code fonts

packages/database/package.json, yarn.lock
This contains a minor fix (details in https://github.com/faye/faye-websocket-node/issues/73).
=> Upgrade faye-websocket from 0.11.1 to 0.11.3

packages/app/index.ts
=> Check that self.firebase is not undefined

packages/app/index.rn.ts
Made a mistake, conditional requires do not work in React Native.
=> Roll back import of newer AsyncStorage

packages/auth/src/auth.js
removed usage of deprecated APIs
=> removed usage of deprecated methods

packages/firebase/package.json, packages/installations/package.json, packages/performance/package.json
This minor version bump should be handled by the release script.
=> Revert manual version bumps

renovate.json
fixes https://github.com/firebase/firebase-js-sdk/issues/1953
=> remove whitespace

packages/rxfire/package.json
=> RxFire: Bump peerDependency of firebase to 6.x.x.

renovate.json
1. Make typescript updates in its own PR
2. Schedule the update on every Friday morning
3. Assign to @Feiyang1 and @hsubox76 by default
=> update renovate rules

packages/firestore/src/core/query.ts, packages/firestore/test/integration/api/validation.test.ts
From https://github.com/firebase/firebase-ios-sdk/pull/2670
=> Port null/NaN validation text from iOS

packages/app/src/firebaseApp.ts, packages/app/src/lite/firebaseAppLite.ts, packages/database/src/core/SyncPoint.ts, packages/database/src/core/view/EventRegistration.ts, packages/database/src/core/view/ViewProcessor.ts, packages/database/src/realtime/WebSocketConnection.ts, packages/firestore/src/api/database.ts, packages/firestore/src/local/indexeddb_mutation_queue.ts, packages/firestore/src/local/lru_garbage_collector.ts, packages/firestore/src/local/shared_client_state.ts, packages/firestore/src/platform_browser/webchannel_connection.ts, packages/firestore/src/platform_node/grpc_connection.ts, packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts, packages/firestore/test/unit/specs/limbo_spec.test.ts, packages/firestore/test/unit/specs/limit_spec.test.ts, packages/installations/src/functions/delete-installation.ts, packages/messaging/test/controller-get-token.test.ts, packages/performance/src/resources/trace.ts, packages/storage/src/implementation/blob.ts, packages/storage/src/implementation/metadata.ts, packages/util/src/errors.ts, scripts/emulator-testing/emulators/database-emulator.ts
This re-formats the Firestore sources after we updated prettier to 1.18.2.
=> Running prettier

packages/database/src/core/RepoManager.ts
Should fix #2025. @Feiyang1 / @hsubox76 Can we get this into a new release or else unpublish 6.3.2?  Thanks!
=> Add undefined check for `process` to fix browser support.

packages/firestore/test/unit/specs/limit_spec.test.ts
Adding a spec test that makes sure that we "refill" Views from cache even for the initial query snapshot.
=> Add spec test for limit query initialization

packages/firestore/test/util/equality_matcher.ts
Running `yarn prettier` on master causes this file to be changed
=> Properly format file

packages/firestore/src/core/sync_engine.ts, packages/firestore/src/local/indexeddb_mutation_queue.ts, packages/firestore/src/util/async_queue.ts, packages/firestore/test/integration/util/helpers.ts
This is the diff when I ran the linter against master.
When I get the chance, I'll look into running `yarn prettier` on the entire repo as part of Travis CI.
=> Lint against master

packages/rxfire/firestore/fromRef.ts
=> Support SnapshotListenOptions for fromRef.

scripts/docgen/content-sources/js/toc.yaml, scripts/docgen/content-sources/node/toc.yaml
Added path for new Auth docs:  ActionCodeURL and AuthError
=> added path for new auth docs

packages/firestore/test/unit/local/remote_document_cache.test.ts, packages/firestore/test/unit/local/test_remote_document_cache.ts
76% chance tests pass this time...
=> Fix test I broke.

packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/memory_persistence.ts, packages/firestore/src/local/query_data.ts, packages/firestore/src/remote/remote_store.ts, packages/firestore/test/integration/api/batch_writes.test.ts, packages/firestore/test/integration/api/database.test.ts, packages/firestore/test/unit/local/lru_garbage_collector.test.ts
Small cleanup that ports https://github.com/firebase/firebase-android-sdk/pull/687
=> Add QueryData.with() helpers

packages/firebase/externs/firebase-auth-externs.js
fixed externs by adding ActionCodeInfo.Operation definition
=> Fix externs

packages/firestore/src/platform_browser/webchannel_connection.ts
=> Remove database field from REST API request body.

packages/remote-config/package.json
Hey @Feiyang1, not sure the intent but looks like RC's main entry was wrong; referencing a non-existent file.
=> Fixing the RemoteConfig main entry

packages/firebase/index.d.ts, packages/installations-types/index.d.ts
=> Update Installations types

packages/installations/src/functions/delete-installation.ts, packages/installations/src/helpers/get-installation-entry.test.ts, packages/installations/src/helpers/get-installation-entry.ts, packages/installations/src/helpers/idb-manager.test.ts, packages/installations/src/helpers/idb-manager.ts, packages/installations/src/helpers/refresh-auth-token.ts
=> Make IdbManager only handle values of type InstallationEntry

packages/firestore/CHANGELOG.md, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/simple_db.ts
See title plus also fixes the log line that was added in the last release.
=> Make maybeGarbageCollectMultiClientState idempotent

packages/template/.npmignore, packages/template/karma.conf.js
- Remove unused `.npmignore`.
- Remove unused test requires.
=> Minor cleanup of package/template

scripts/docgen/generate-docs.js
Make script able to handle misspelled paths.
=> Add more error checking in doc gen script

packages/firestore/test/unit/specs/listen_spec.test.ts, packages/firestore/test/unit/specs/spec_builder.ts
Also fixes a bug in spec test builder.
=> Add spec test for single client

packages/firestore/src/api/user_data_converter.ts, packages/firestore/test/integration/api/validation.test.ts
Port of firebase/firebase-android-sdk#643.
=> Disallow empty document fields

packages/auth/src/autheventmanager.js, packages/auth/src/utils.js, packages/auth/test/autheventmanager_test.js, packages/auth/test/utils_test.js
Treat ionic scheme as cordova environment
=> treat ionic scheme as cordova environment

scripts/docgen/content-sources/js/toc.yaml, scripts/docgen/content-sources/node/toc.yaml
added toc for OAuthCredentialOptions
=> added toc for OAuthCredentialOptions

packages/firestore/CHANGELOG.md, packages/firestore/src/core/firestore_client.ts, packages/firestore/src/local/local_store.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
Port of https://github.com/firebase/firebase-android-sdk/pull/730
@Feiyang1 / @hsubox76: Can we bump the minor version for the release that this will be part of?
=> Enable Index-Free Queries

packages/rxfire/docs/firestore.md
I use this method already, but noticed there is no docs about it.
=> rxfire: docs update, add collectionData() method usage

packages/firebase/index.d.ts, packages/firestore-types/index.d.ts
+ Changed ordering for `TimeStamp` to have constructor first.
=> Deleting comments from index.d.ts file in packages/firestore-types

packages/component/package.json
Remove `private: true` from package.json
=> make @firebase/component public

packages/installations/src/api/create-installation-request.test.ts, packages/installations/src/api/create-installation-request.ts, packages/installations/src/api/delete-installation-request.test.ts, packages/installations/src/api/delete-installation-request.ts, packages/installations/src/api/generate-auth-token-request.test.ts, packages/installations/src/api/generate-auth-token-request.ts, packages/installations/src/functions/delete-installation.test.ts, packages/installations/src/functions/delete-installation.ts, packages/installations/src/functions/get-token.test.ts, packages/installations/src/helpers/get-installation-entry.test.ts, packages/installations/src/helpers/get-installation-entry.ts, packages/installations/src/helpers/refresh-auth-token.test.ts, packages/installations/src/helpers/refresh-auth-token.ts
For better distinction between the API functions and the SDK functions, especially deleteInstallation.
=> Append "Request" to API function names

packages/testing/src/api/index.ts
=> Implement addAuthTokenListener in testing. Fix #2417.

packages/messaging/src/controllers/base-controller.ts, packages/messaging/test/controller-delete-token.test.ts
Band-aid for #2364 until we find and fix the problem.
=> Suppress server errors in deleteToken request

packages/app-types/private.d.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/2415
=> remove unused imports

packages/firebase/index.d.ts
=> Update Messaging documentation

packages/firebase/README.md
=> Remove obsolete reference to ENVIRONMENTS.md

.github/CODEOWNERS
=> Update code owners for emulators

packages/auth-types/index.d.ts, packages/firebase/index.d.ts
Fixes https://github.com/firebase/firebaseui-web/issues/663
=> Adds missing SAMLAuthProvider constructor.

packages/firestore/index.node.ts, packages/firestore/index.ts
... just a random thing I noticed.
=> Add QueryDocumentSnapshot to the internal FirebaseNamespace

packages/performance/src/resources/trace.test.ts, packages/performance/src/services/perf_logger.test.ts
Implemented a unit test to add Page Load Trace validation.
=> Add page load unit tests with the Proto format change.

packages/installations/src/helpers/get-installation-entry.test.ts
Turns off `shouldAdvanceTime` for tests that don't need it. Also increases the `sleep` durations so they don't complete unexpectedly if a test is a bit slow.
=> Deflake getInstallationEntry tests

packages/rxfire/docs/firestore.md
=> Added docData function to rxfire documentation.

packages/firestore/.gitignore
=> Adding scripts/.js to gitignore

packages/messaging/src/controllers/window-controller.ts
fixes https://github.com/firebase/firebase-js-sdk/issues/2590
It should fix any sw update issue going forward.
=> reliably update service worker

.github/workflows/cross-browser-test.yml, .github/workflows/test-all.yml, .github/workflows/test-changed.yml
v2 has many improvements.  This should fix a possible race condition as well as more efficiently fetch only the single commit asked for.
=> Upgrade to actions/checkout@v2

scripts/emulator-testing/emulators/firestore-emulator.ts
Rolling forward the emulator version to 1.10.4, now that #2639 is in.
=> Upgrade firestore testing emulator to 1.10.4

.vscode/launch.json
For those of us who haven't hopped on the IntelliJ train yet.
+cc @wu-hui
=> Fix VS Code launch.json to look for mocha/karma in the right location

packages/auth/package.json, packages/webchannel-wrapper/package.json
It reverts 9d975e97f42f567e2b475dc059621e5d510666fd
=> revert dep update since it broke auth

packages/auth/package.json, packages/auth/test/testhelper.js, yarn.lock
Fixes failing tests that were blocking the update.
=> Updates Auth closure dependency to latest.

packages/firebase/firestore/memory/package.json
The original file was an invalid JSON, which could potentially break builds that would parse JSON files. Fixes #2810 
can discuss it …
=> Fixing dangling comma on package.json

.vscode/launch.json, packages/database/src/api/Database.ts, packages/database/src/core/Repo.ts, packages/database/src/core/Repo_transaction.ts, packages/database/src/core/SyncTree.ts, packages/database/src/core/util/ServerValues.ts, packages/database/test/servervalues.test.ts, scripts/emulator-testing/emulators/database-emulator.ts
Add back the increment operator.
=> Increment master

packages/firestore/src/util/log.ts
=> Fix logDebug log level

packages/firestore/test/unit/specs/spec_test_runner.ts, packages/firestore/test/util/helpers.ts
Attempt number three (I think).
=> Actually fix resume token debugging in spec tests

packages/firestore/test/integration/api/transactions.test.ts
=> Fix flaky transaction tests

packages-exp/auth-exp/src/api/authentication/sign_up.test.ts, packages-exp/auth-exp/src/core/user/user_impl.test.ts, packages-exp/auth-exp/test/api/helper.ts, packages-exp/auth-exp/test/mock_auth.ts
=> Consolidate mock auth object, add user object

packages-exp/auth-exp/src/api/index.ts, packages-exp/auth-exp/src/core/strategies/email.ts
Can't believe you guys let this one slip past code review 🦀
=> use queryString helper in auth-next

packages/auth/src/idp.js
This fixes the issue described here; https://github.com/firebase/firebase-js-sdk/issues/2965
=> Fix Apple popup window window

packages/firestore/src/model/object_value.ts, packages/firestore/test/unit/model/object_value_builder.test.ts
Remove a dangling static reference.
=> Remove ObjectValue.EMPTY

packages-exp/auth-exp/demo/.gitignore, packages-exp/auth-exp/demo/README.md, packages-exp/auth-exp/demo/build.sh, packages-exp/auth-exp/demo/database.rules.json, packages-exp/auth-exp/demo/firebase.json, packages-exp/auth-exp/demo/package.json, packages-exp/auth-exp/demo/public/common.js, packages-exp/auth-exp/demo/public/index.html, packages-exp/auth-exp/demo/public/manifest.json, packages-exp/auth-exp/demo/public/style.css, packages-exp/auth-exp/demo/rollup.config.js, packages-exp/auth-exp/demo/src/index.js, packages-exp/auth-exp/demo/src/logging.js, packages-exp/auth-exp/demo/src/sample-config.js, packages-exp/auth-exp/src/index.ts
Note: I just took the old demo (in `packages/auth/demo`) and modified it a bit. It has a ton of code and I don't think it's worth our time to try to modernize all of that at the moment.
=> Add a demo page to auth-exp using the new modular methods

packages-exp/auth-exp/src/core/credentials/phone.test.ts, packages-exp/auth-exp/src/core/strategies/credential.test.ts, packages-exp/auth-exp/src/core/strategies/custom_token.test.ts, packages-exp/auth-exp/src/core/strategies/phone.test.ts, packages-exp/auth-exp/src/core/user/additional_user_info.test.ts, packages-exp/auth-exp/src/core/user/additional_user_info.ts, packages-exp/auth-exp/src/core/user/user_credential_impl.test.ts, packages-exp/auth-exp/src/core/user/user_impl.test.ts, packages-exp/auth-exp/src/model/id_token.d.ts, packages-exp/auth-exp/test/id_token_response.ts
=> Fix broken build

packages/firestore/lite/test/dependencies.json, packages/firestore/lite/test/integration.test.ts, packages/firestore/lite/test/verify_dependencies.test.ts
The Lite tests are not yet run in CI. This PR updates the tests after #3189 and #3264.
=> Update Lite tests

packages-exp/auth-exp/src/api/account_management/email_and_password.ts, packages-exp/auth-exp/src/api/authentication/email_and_password.test.ts, packages-exp/auth-exp/src/api/authentication/email_and_password.ts, packages-exp/auth-exp/src/core/strategies/email.test.ts, packages-exp/auth-exp/src/core/strategies/email.ts, packages-exp/auth-exp/src/core/strategies/email_and_password.test.ts, packages-exp/auth-exp/src/core/strategies/email_and_password.ts, packages-exp/auth-exp/src/core/strategies/phone.test.ts, packages-exp/auth-exp/src/core/strategies/phone.ts, packages-exp/auth-exp/src/index.ts, packages-exp/auth-types-exp/index.d.ts
Also add a couple edge cases that I missed first pass around
=> Add verifyBeforeUpdate to auth-next

.changeset/fresh-onions-cry.md, packages/auth/package.json
Fixes https://github.com/firebase/firebase-js-sdk/issues/3397
=> add browser field to auth

packages-exp/auth-exp/karma.conf.js, packages-exp/auth-exp/package.json, packages-exp/auth-exp/test/helpers/integration/helpers.ts, packages-exp/auth-exp/test/helpers/integration/with_test_instance.ts, packages-exp/auth-exp/test/integration/smoke_test.test.ts
Based on https://github.com/firebase/firebase-js-sdk/pull/3414/files
=> Foundation for integration tests for auth-exp

yarn.lock
```
mrschmidt@mrschmidt-macbookpro firebase-js-sdk (master) $ rm -rf node_modules/
mrschmidt@mrschmidt-macbookpro firebase-js-sdk (master) $ rm yarn.lock
mrschmidt@mrschmidt-macbookpro firebase-js-sdk (master) $ yarn install
yarn install v1.22.4
```
=> Re-gen lockfile

packages-exp/performance-exp/index.ts, packages-exp/performance-exp/rollup.config.js, packages-exp/performance-exp/src/controllers/perf.test.ts, packages-exp/performance-exp/src/controllers/perf.ts, packages-exp/performance-exp/src/index.ts, packages-exp/performance-types-exp/index.d.ts
This is the first step. The changes to Traces (and other things) still need to be done in a follow-up PR.
=> Updating the FirebasePerformance Controller and index to support tree-shaking.

.github/workflows/test-changed.yml
Use official config for getting all history instead of special fetch command.
=> Update test-changed workflow checkout step

repo-scripts/size-analysis/analysis-helper.ts
setting mangle to true doesn't seem to work. Change to explicitly enable toplevel mangling
=> Enable toplevel mangling

packages-exp/auth-compat-exp/demo/public/common.js, packages-exp/auth-compat-exp/demo/public/script.js, packages-exp/auth-compat-exp/demo/public/service-worker.js, packages-exp/auth-compat-exp/demo/public/web-worker.js, packages-exp/auth-compat-exp/karma.conf.js, packages-exp/auth-exp/demo/public/common.js, packages-exp/auth-exp/demo/src/index.js, packages-exp/auth-exp/karma.conf.js, packages-exp/auth-exp/rollup.shared.js, packages-exp/auth-exp/src/core/util/assert.test.ts, packages-exp/auth-exp/src/core/util/assert.ts
See the comment and the tests for usage.
There are unrelated prettier changes
=> Add an assertTypes utility

packages/firestore/test/integration/api/query.test.ts
Adding an extra test to cover != checks on field paths.
=> add test for != document ID

scripts/docgen/content-sources/js/toc.yaml
Need to add to toc.yaml to show up in docs.
=> Add new messaging API pages to toc.yaml

scripts/docgen/theme/layouts/default.hbs
Change needed by devsite team. See CL 325842823.
=> Disable machine translation on devsite docs

packages-exp/auth-exp/src/platform_browser/strategies/popup.ts, packages-exp/auth-exp/src/platform_browser/strategies/redirect.ts
This addresses b/166287628, b/166288260
=> Add assertions for type of OAuthProvider in popup/redirect

packages-exp/auth-exp/src/core/credentials/auth_credential.ts, packages-exp/auth-exp/src/core/credentials/email.ts, packages-exp/auth-exp/src/core/credentials/oauth.ts, packages-exp/auth-exp/src/core/credentials/phone.ts
I just totally removed the `AuthCredential.fromJSON`. It's not in the new API proposal and anyway it breaks the whole modularization thing
=> Remove circular dependency issue with AuthCredential

packages/firebase/externs/firebase-firestore-externs.js, packages/messaging/src/util/errors.ts, packages/rxfire/docs/database.md, packages/rxfire/docs/firestore.md, packages/rxfire/test/firestore.test.ts
My personal linter inside of Google caught this, mainly because I make this mistake fairly often myself! :)
https://www.merriam-webster.com/dictionary/occurred
=> Fix a simple spelling error 'occured' -> 'occurred'

.changeset/witty-deers-study.md
=> Update dynamic measurement ID change to ensure firebase minor bump

scripts/release/cli.ts
=> Fix release flag logic

packages/firestore/lite/src/api/reference.ts
This is only for firestore-exp.
=> Add not-in and != to newest copy of WhereFilterOp

packages/firestore/index.console.ts, packages/firestore/tools/console.build.js
I will create another follow up PR to turn on minification. Size of standalone.js with this PR is: 360299 kB
=> Fix Firestore Console build

.changeset/config.json
Ignore perf exp pacakges in changesets
=> Ignore perf exp pacakges in changesets

packages/firestore/exp-types/index.d.ts, packages/firestore/exp/dependencies.json, packages/firestore/exp/test/shim.ts, packages/firestore/lite-types/index.d.ts, packages/firestore/lite/dependencies.json, packages/firestore/lite/src/api/reference.ts, packages/firestore/lite/test/integration.test.ts, packages/firestore/src/model/path.ts, packages/firestore/test/integration/api/validation.test.ts
Also drops CollectionReference.doc() and DocumentReference.collection() once again.
go/firestore-next-amendment-amendment
=> Add variadic arguments to collection()/doc()

packages-exp/auth-exp/src/core/auth/auth_impl.ts
=> Clear the redirect user on signout

packages-exp/auth-exp/src/core/user/account_info.ts, packages-exp/auth-exp/src/core/user/invalidation.test.ts, packages-exp/auth-exp/src/core/user/invalidation.ts, packages-exp/auth-exp/src/core/user/link_unlink.ts, packages-exp/auth-exp/src/core/user/reauthenticate.ts, packages-exp/auth-exp/src/core/user/reload.ts, packages-exp/auth-exp/src/core/user/user_impl.ts, packages-exp/auth-exp/src/mfa/mfa_user.ts
=> Add user invalidation handling

packages-exp/auth-exp/src/core/auth/auth_event_manager.test.ts, packages-exp/auth-exp/src/core/auth/auth_event_manager.ts, packages-exp/auth-exp/test/integration/flows/phone.test.ts
=> Add a cache layer to the event manager

.changeset/poor-eagles-think.md
Following up on #3825 at the request of @Feiyang1
=> Amend changeset for PR #3825

packages-exp/firebase-exp/performance/package.json, packages-exp/performance-exp/src/index.ts
- Importing installations in performance-exp/index.ts
- Fixing the location of the typings in firebase-exp/performance
=> Fixes for performance-exp

.changeset/neat-crews-rule.md, packages/firestore/lite/src/api/transaction.ts
Not sure how I managed to sneak this into the repo...
=> Fix compile error + add Changelog for #3819

.github/CODEOWNERS
scottcrossen@ is no longer on the team
=> Update codeowners for auth-exp code. Also remove scottcrossen@

.github/CODEOWNERS, scripts/exp/release.ts
1. Add exp code owners
2. exclude auth exp packages from the exp release process until we are ready to release auth
=> Add exp code owners

.changeset/dirty-rings-cry.md, .changeset/lucky-squids-explode.md
- Functions bug fix was cherrypicked into 7.22.1 and changeset file should be removed.
- Analytics minor bump needs to also minor bump firebase package.
=> Fix changesets before release

packages-exp/auth-exp/src/core/auth/auth_impl.test.ts, packages-exp/auth-exp/src/core/auth/auth_impl.ts
=> Add a toJSON() function to auth-exp

packages-exp/auth-compat-exp/src/auth.ts, packages-exp/auth-exp/src/core/auth/auth_impl.test.ts, packages-exp/auth-exp/src/core/auth/auth_impl.ts
=> Handle app deletion a little more gracefully in auth-exp and auth-compat-exp

.changeset/silver-books-reply.md
Note to self: run `yarn changeset status` before submitting one of these changeset fix PRs.
=> Fix another changeset

.changeset/config.json, packages-exp/functions-compat/package.json, scripts/check_changeset.ts
- Update functions-compat typescript dep version
- Add functions-compat to changeset ignored packages
- Fix changeset script early-exit bug
=> Update functions-compat dep version and fix changeset script error

.changeset/lemon-steaks-draw.md
I don't think changesets recognizes "internal"?
=> Fix changeset file

packages/firestore/tools/console.build.js
=> Fix import for node resolve for console build

packages/firestore/rollup.config.exp.js, packages/firestore/rollup.config.lite.js, packages/firestore/rollup.shared.js
This solves an unresolved import problem on my local machine (likely due to a corrupted cache).
=> Use distinct cache dirs for all builds

packages-exp/firebase-exp/package.json
Still having errors in the release script, manually updating the version after last publish.
=> Bump firebase-exp version

.github/ISSUE_TEMPLATE/alpha_bug_report.md, .github/ISSUE_TEMPLATE/bug_report.md
Fix the labels issue. This PR was generated through the GitHub GUI so I think it should work, I guess you can't quote labels?
=> Fix alpha issue template

.changeset/config.json, packages-exp/messaging-exp/package.json, packages-exp/messaging-exp/rollup.config.js, packages-exp/messaging-exp/rollup.config.release.js, packages-exp/messaging-types-exp/package.json
Update versions to match other packages and add to ignore list.
=> Fix messaging-exp versions and changeset

packages/firestore/package.json, repo-scripts/prune-dts/tsconfig.json
To work around a parsing issue in changeset, similar to https://github.com/atlassian/changesets/issues/196
=> fix a parsing issue in the release script

packages/firestore/src/core/bundle_impl.ts
=> Clarify error message

packages/database/rollup.config.exp.js
Remove `import '@firebase/app-types';` from the bundle
=> remove side effect imports in exp build

packages-exp/analytics-exp/rollup.config.js, packages-exp/analytics-exp/rollup.config.release.js, packages-exp/analytics-exp/src/index.ts
Forgot to import installations package.
=> Add installations import to analytics-exp

packages/auth/externs/gapi.iframes.js
=> Change comment to match g3 changes

.changeset/honest-rats-deny.md, packages/firestore/rollup.config.rn.js, packages/storage/package.json
1. Output firestore memory rn build to the right folder
2. Build storage exp in the build script
=> Fix some build issues

packages/firebase/index.d.ts
Just a quick link updated related to internal change 346201400.
Thanks!
=> Updating link to guide docs.

packages/database/src/core/CompoundWrite.ts, packages/database/src/core/WriteTree.ts, packages/database/test/compound_write.test.ts
Extract methods from `CompoundWrite`.
=> Database tree-shake step: modularize CompoundWrite

.github/CODEOWNERS
Add Chen & Ciaran as FM owners/reviewers
=> Add Chen & Ciaran as FM owners/reviewers

packages-exp/auth-exp/src/core/strategies/abstract_popup_redirect_operation.test.ts, packages-exp/auth-exp/src/core/strategies/abstract_popup_redirect_operation.ts, packages-exp/auth-exp/src/core/strategies/redirect.test.ts, packages-exp/auth-exp/src/core/strategies/redirect.ts, packages-exp/auth-exp/src/platform_browser/strategies/popup.ts, packages-exp/auth-exp/src/platform_browser/strategies/redirect.test.ts, packages-exp/auth-exp/src/platform_browser/strategies/redirect.ts, packages-exp/auth-exp/src/platform_cordova/popup_redirect/events.test.ts, packages-exp/auth-exp/src/platform_cordova/popup_redirect/events.ts, packages-exp/auth-exp/src/platform_cordova/popup_redirect/popup_redirect.test.ts, packages-exp/auth-exp/src/platform_cordova/popup_redirect/popup_redirect.ts, packages-exp/auth-exp/src/platform_cordova/popup_redirect/utils.test.ts, packages-exp/auth-exp/src/platform_cordova/popup_redirect/utils.ts
This change doesn't modify any behavior or add anything new
=> Big refactor of a bunch of redirect code that will be used by Cordova as well as Browser

.changeset/serious-fireants-hunt.md
Forgot to add a changeset to https://github.com/firebase/firebase-js-sdk/pull/4434
=> Changeset for analytics measurement ID change

packages-exp/analytics-exp/src/factory.ts, packages-exp/analytics-exp/src/helpers.test.ts, packages-exp/analytics-exp/src/helpers.ts, packages-exp/analytics-exp/src/index.test.ts, packages-exp/analytics-exp/src/initialize-analytics.test.ts, packages-exp/analytics-exp/src/initialize-analytics.ts
Apply changes already made to packages/analytics https://github.com/firebase/firebase-js-sdk/pull/4434 to analytics-exp.
=> Propagate measurement ID change to analytics-exp

packages-exp/auth-exp/index.ts, packages-exp/auth-exp/src/platform_browser/recaptcha/recaptcha_verifier.ts
=> Add assertion for the presence of `document` to the recaptcha verifier

packages-exp/auth-exp/test/integration/webdriver/util/auth_driver.ts
=> Fix last arg getting dropped in WebDriver callNoWait.

.changeset/happy-planets-lick.md, packages/rules-unit-testing/src/api/index.ts, packages/rules-unit-testing/test/database.test.ts
Fix assert fails (#4667)
Redoing this PR https://github.com/firebase/firebase-js-sdk/pull/4668/commits/a3bf56fcc57f556052ed2d86803f5c3521aa6673 since I was sloppy with git.
=> Fix assert fails (#4667)

packages-exp/auth-exp/src/core/strategies/email_link.test.ts, packages-exp/auth-exp/src/core/strategies/email_link.ts
Action code info is a required parameter.
=> [Auth] Fix sendSignInLinkToEmail signature

.changeset/healthy-beans-enjoy.md, yarn.lock
Add missing changeset for https://github.com/firebase/firebase-js-sdk/pull/4772
Fixes https://github.com/firebase/firebase-js-sdk/issues/4789
=> Add missing changeset

.changeset/five-wolves-tickle.md, packages/firestore/src/platform/node/grpc_connection.ts, packages/firestore/src/remote/rest_connection.ts
=> Don't send empty GMPID header

packages-exp/firebase-exp/package.json
Fixes https://github.com/firebase/firebase-js-sdk/issues/4830
=> remove non-existing export paths

repo-scripts/api-documenter/src/documenters/MarkdownDocumenter.ts, repo-scripts/api-documenter/src/documenters/MarkdownDocumenterHelpers.ts
Also reverting he change to add `_c` and `_i` suffixes to class and interface doc files.
=> Generate API docs for namespace members

packages-exp/messaging-exp/package.json, packages-exp/messaging-exp/sw/package.json
=> Publishing @firebase/messaging/sw to npm

packages-exp/functions-exp/src/context.ts, packages/functions/src/context.ts
https://github.com/firebase/firebase-js-sdk/issues/4909  Kudos to sudkumar
=> Function awaits messaging#getToken internally

.changeset/tender-eels-greet.md
Forgot to suggest adding changeset in PR https://github.com/firebase/firebase-js-sdk/pull/4919
=> Add changeset for previous PR

.changeset/blue-hairs-scream.md
Forgot to add my changeset to #4925. Hopefully adding it in a separate PR without reverting is ok.
=> Adding changeset to #4925

repo-scripts/api-documenter/CHANGELOG.md, repo-scripts/api-documenter/package.json
=> @firebase/api-documenter 0.1.1 release

repo-scripts/api-documenter/CHANGELOG.md, repo-scripts/api-documenter/package.json
=> publish documenter 0.1.2

packages-exp/auth-exp/src/core/auth/auth_impl.ts
fixes: https://github.com/firebase/firebase-js-sdk/issues/4937
=> fix onAuthStateChanged binding

.changeset/a-dark-knight.md
Fixes https://github.com/firebase/firebase-js-sdk/issues/4977
=> Release Webchannel Wrapper

.changeset/gentle-items-refuse.md
add changeset for https://github.com/firebase/firebase-js-sdk/pull/5008
=> changeset to publish firestore

.changeset/sharp-pans-share.md, packages/component/src/provider.test.ts, packages/component/src/provider.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/5018
=> Pass the instance to onInit callback

packages-exp/messaging-exp/src/api/getToken.ts, packages-exp/messaging-exp/src/interfaces/public-types.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/5034
=> Allows registering custom service workers

packages-exp/app-check-exp/package.json, packages-exp/app-exp/src/constants.ts
=> Remove app-check-exp from app-exp package

packages/firestore/exp/register.ts
[The fix](https://github.com/firebase/firebase-js-sdk/pull/4994) doesn't seem to fix https://github.com/firebase/firebase-js-sdk/issues/4993
=> Revert to use Xhr in Firestore

packages/firestore/test/util/test_platform.ts
=> Fix comment in spec tests

packages-exp/app-check-compat/package.json, packages-exp/app-exp/src/constants.ts, packages-exp/firebase-exp/app-check/index.ts, packages-exp/firebase-exp/app-check/package.json, packages-exp/firebase-exp/compat/app-check/index.ts, packages-exp/firebase-exp/compat/app-check/package.json, packages-exp/firebase-exp/compat/index.cdn.ts, packages-exp/firebase-exp/compat/index.ts, packages-exp/firebase-exp/compat/package.json, packages-exp/firebase-exp/package.json, yarn.lock
Create firebase/app-check and firebase/compat/app-check entry points.
=> Add App Check exp/compat to firebase-exp

packages-exp/app-check-compat/package.json
Update rollup deps to match the rest of the repo.
=> Update app-check-compat deps

packages-exp/auth-exp/src/core/util/event_id.test.ts, packages-exp/auth-exp/src/core/util/event_id.ts, packages-exp/auth-exp/src/platform_browser/messagechannel/sender.ts
=> [Auth] Break down event ID digits to a max Math.random() digit count

packages-exp/auth-exp/index.doc.ts, packages-exp/auth-exp/index.rn.ts
I'm not sure how to wire up tsc/api-report
=> [Auth] Create index.doc.ts for generating docs for all platforms

common/api-review/app-check-exp.api.md, packages-exp/app-check-compat/package.json, packages-exp/app-check-exp/src/api.ts, packages-exp/app-check-exp/src/public-types.ts, packages-exp/firebase-exp/compat/index.d.ts
- Add definitions to compat/index.d.ts.
- Add a step to generate overloads for public APIs.
=> Add app-check-compat index.d.ts types and overload types

packages-exp/firebase-exp/compat/rollup.config.release.js, packages-exp/firebase-exp/rollup.config.release.js
- Minify CDN builds (removing comments)
- Make an es5 CDN build for perf-lite
=> Update cdn builds

README.md
All other links seem to be good.
=> Fix Lerna link.

.github/workflows/health-metrics-test.yml
https://github.com/google-github-actions/setup-gcloud
=> Migrate to the new GCP action for setting up gcloud.

packages-exp/auth-exp/src/platform_browser/util/popup.test.ts, packages-exp/auth-exp/src/platform_browser/util/popup.ts
Also fix/augment the tests which, embarrassingly, were actually testing for the wrong behavior...
Fixes https://github.com/firebase/firebase-js-sdk/issues/5275
=> [Auth] Fix popup opening location

common/api-review/app.api.md, packages/app/src/api.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/5331
=> export FirebaseError

packages/messaging-compat/src/registerMessagingCompat.ts
Fix https://github.com/firebase/firebase-js-sdk/issues/5347
=> Fix Context Check in `Messaging-Compat`

packages/auth/cordova/demo/package.json, packages/auth/demo/package.json
Update the remains of v9 beta version
=> update versions to v9

packages/auth/test/integration/webdriver/util/test_runner.ts
Until we can figure out why it's often timing out
=> [Auth] Disable Firefox in webdriver tests

packages/messaging/src/api.ts, packages/messaging/src/index.sw.ts
=> Fix missing prefix in `signature` field in the public documentation

.github/CODEOWNERS
Adding self to codeowners for auth so I can help review and approve PRs
=> Add @lisajian to codeowners for auth directories

.changeset/stale-cows-leave.md
Forgot to add changeset for #5418
=> Add changeset for #5418

packages/database-compat/src/util/util.ts, packages/database-compat/src/util/validation.ts, packages/database/test/helpers/util.ts, packages/rules-unit-testing/functions/index.js
=> Add missing license headers

.github/workflows/release-log.yml, scripts/ci/log-changesets.js, scripts/ci/log-changesets.ts
Triggers on PR to `release` branch.
- Gets PR payload data through Github provided env variable.
- Check if title is 'Version Packages'.
- If so, extract release version from PR description.
- Call release tracker functions endpoint with release version and PR number.
=> Log release PR number

.changeset/brown-ladybugs-invent.md, packages/firestore-compat/package.json
Only publish dist folder to npm for @firebase/firestore-compat
=> only publish dist to npm @firebase/firestore-compat

.changeset/clean-pens-invite.md
=> Add changeset for #5512

.changeset/big-rocks-scream.md, packages/auth-compat/index.ts
=> [Auth] Add SAML provider to the compat layer

.changeset/proud-moose-taste.md
Add missing changeset for https://github.com/firebase/firebase-js-sdk/pull/5646
=> Add missing changset

packages/auth/index.rn.ts, packages/auth/src/platform_react_native/persistence/react_native.ts
Should address https://github.com/firebase/firebase-js-sdk/issues/1847 (will hold out closing that issue until we have confirmation that the fix is working)
=> [Auth] Export getReactNativePersistence function

packages/auth/src/model/public_types.ts
Related: https://github.com/firebase/firebase-js-sdk/issues/5712
=> [Auth] Update docs for UserCredential

package.json, yarn.lock
This will allow us to merge some tests that make use of the new Auth emulator features
=> Bump firebase-tools version

.changeset/curvy-cougars-turn.md
Forgot to add a changeset in https://github.com/firebase/firebase-js-sdk/pull/5771
=> Add changeset for #5771

.github/workflows/e2e-test.yml, .github/workflows/release-log.yml, scripts/ci/log-changesets.js, scripts/ci/notify-test-result.js
Send the E2E test result to the release tracker. Put the release tracker functions URL in a secret.
=> Log E2E Test Result and URL to release tracker

packages/firestore/src/local/memory_remote_document_cache.ts, packages/firestore/src/model/collections.ts, packages/firestore/src/model/document.ts, packages/firestore/test/unit/model/mutation.test.ts
Port of https://github.com/firebase/firebase-android-sdk/pull/3225
=> Use immutable Documents in MemoryRemoteDocumentCache

.github/ISSUE_TEMPLATE/bug_report.md
Add reduced capacity message for holiday weeks.
=> Add reduced capacity note to issue template

.github/ISSUE_TEMPLATE/bug_report.md
Remove message after holiday break.
=> Remove limited availability message

packages/auth/src/core/strategies/email_link.ts
Fixing to match internal cl/419910497
=> Fix example signature for signInWithEmailLink

packages/storage/src/public-types.ts
=> Update url in doc comment

.changeset/loud-pears-sort.md
Forgot to add changeset for https://github.com/firebase/firebase-js-sdk/pull/5904
=> Add changeset for #5904

packages/auth/index.rn.ts
Related to #1847. I don't know if this works.
Note this would still warn if you _don't_ pass the persistence layer yourself. But at least it shouldn't warn if you do.
Sorry for lack of detail, @hsubox76 has context on the conversation
=> Maybe fix deprecation warning

.changeset/metal-apes-double.md, integration/messaging/package.json, packages/auth-compat/package.json, packages/auth/package.json, packages/firestore/package.json, packages/functions/package.json, packages/rules-unit-testing/package.json, packages/storage/package.json, repo-scripts/changelog-generator/package.json, yarn.lock
Update node-fetch due to security issue.
See https://nvd.nist.gov/vuln/detail/CVE-2022-0235
=> Update node-fetch due to security issue

packages/firestore/src/protos/google/api/client.proto, packages/firestore/src/protos/google/api/field_behavior.proto, packages/firestore/src/protos/protos.json, packages/firestore/src/protos/update.sh
Not sure why the CI and my previous runs passed, but now my local Node tests are failing. This fixes the error for me. The new files are imported by firestore.proto
=> Fix Proto loading for Node tests

packages/firestore/src/core/query.ts, packages/firestore/src/core/target.ts, packages/firestore/src/lite-api/query.ts, packages/firestore/src/remote/serializer.ts, packages/firestore/test/unit/core/query.test.ts, packages/firestore/test/unit/model/target.test.ts, packages/firestore/test/unit/remote/serializer.helper.ts, packages/firestore/test/util/helpers.ts
Port of https://github.com/firebase/firebase-android-sdk/pull/2981
=> Change Bound.before to Bound.inclusive

.changeset/pretty-mayflies-worry.md
Changeset for https://github.com/firebase/firebase-js-sdk/pull/5762
=> Add Changeset for pull/5762

packages/firestore/src/local/indexeddb_index_manager.ts
Port of https://github.com/firebase/firebase-android-sdk/pull/3484#pullrequestreview-892779943
=> Make getNextCollectionGroupToUpdate() deterministic

packages/firestore/.idea/runConfigurations/Integration_Tests__Emulator_.xml
=> Fix Integration Test Runner on IntelliJ

.github/CODEOWNERS
Add lahirumaramba to jssdk-global-approvers comment (was added separately to the secret team).
=> Update CODEOWNERS (add lahirumaramba to team membership comment)

packages/auth/src/api/index.ts, packages/auth/src/core/credentials/email.ts, packages/auth/src/core/strategies/email_and_password.ts, packages/auth/src/core/strategies/email_link.ts, packages/auth/src/platform_browser/recaptcha/recaptcha_enterprise_verifier.ts
Make some changes to align with the latest backend changes:
1. Enforce action name
2. Check MISSSING_RECAPTCHA_TOKEN error
=> Align with backend: 

packages/firestore/src/local/indexeddb_index_manager.ts
=> Misc fixes for indexing

package.json, repo-scripts/prune-dts/package.json, yarn.lock
Updating prettier package as mentioned in [pull request 5566](https://github.com/firebase/firebase-js-sdk/pull/5566/files#) for all non-major dependencies.
=> Update prettier version.

packages/auth/package.json, yarn.lock
Updating selenium package as mentioned in [pull request 5566](https://github.com/firebase/firebase-js-sdk/pull/5566/files#) for all non-major dependencies.
=> Update selenium package.

integration/messaging/package.json, packages/auth-compat/package.json, packages/auth/package.json, yarn.lock
Updating selenium and chromedriver package as mentioned in [pull request 5566](https://github.com/firebase/firebase-js-sdk/pull/5566/files#) for all non-major dependencies.
=> Update chromedriver and selenium dependencies.

config/functions/package.json, packages/auth-compat/demo/functions/package.json, packages/auth/demo/functions/package.json, packages/rules-unit-testing/functions/package.json
Updating firebase-admin package as mentioned in [pull request 5566](https://github.com/firebase/firebase-js-sdk/pull/5566/files#) for all non-major dependencies.
=> Update firebase-admin dependencies 

repo-scripts/size-analysis/package.json, yarn.lock
Updating memfs package as mentioned in [pull request 5566](https://github.com/firebase/firebase-js-sdk/pull/5566/files#) for all non-major dependencies.
=> Update memfs dependency

config/functions/package.json, package.json, packages/auth-compat/demo/functions/package.json, packages/auth/demo/functions/package.json, packages/rules-unit-testing/functions/package.json, yarn.lock
Updating firebase-functions package as mentioned in [pull request 5566](https://github.com/firebase/firebase-js-sdk/pull/5566/files#) for all non-major dependencies.
=> Update firebase-functions dependency

.changeset/rude-games-thank.md
Forgot firebase minor and major version bumps need to be added manually if a dependent package has a minor/major bump (in this case, functions: https://github.com/firebase/firebase-js-sdk/pull/6177)
=> Add minor bump to main package

repo-scripts/api-documenter/package.json, yarn.lock
Updating resolve package as mentioned in [pull request 5566](https://github.com/firebase/firebase-js-sdk/pull/5566/files#) for all non-major dependencies.
=> Update resolve dependency

package.json, yarn.lock
Removing git-rev-sync package as it is no longer used in the codebase
=> Remove git-rev-sync dependency.

package.json, yarn.lock
Updating firebase-tools package as mentioned in [pull request 5566](https://github.com/firebase/firebase-js-sdk/pull/5566/files#) for all non-major dependencies.
=> Update firebase-tools dependency

package.json, repo-scripts/size-analysis/package.json, yarn.lock
Updating terser package as mentioned in [pull request 5566](https://github.com/firebase/firebase-js-sdk/pull/5566/files#) for all non-major dependencies.
=> Update terser package

package.json, yarn.lock
Updating semver package as mentioned in [pull request 5566](https://github.com/firebase/firebase-js-sdk/pull/5566/files#) for all non-major dependencies.
=> Update semver dependency

.changeset/light-poets-eat.md, packages/auth/src/model/public_types.ts
=> Changeset for beforeAuthStateChanged()

package.json, packages/firestore-compat/package.json, packages/firestore/package.json, yarn.lock
Updating ts-node packages as mentioned in [pull request 5566](https://github.com/firebase/firebase-js-sdk/pull/5566/files#) for all non-major dependencies.
=> Update ts-node dependencies

e2e/package.json
Updating webpack package as mentioned in [pull request 5566](https://github.com/firebase/firebase-js-sdk/pull/5566/files#) for all non-major dependencies.
=> Update webpack CLI package

repo-scripts/api-documenter/package.json, yarn.lock
Updating rushstack packages as mentioned in [pull request 5566](https://github.com/firebase/firebase-js-sdk/pull/5566/files#) for all non-major dependencies.
=> Update rushstack dependencies

package.json, yarn.lock
Updating @types/tmp package as mentioned in [pull request 5566](https://github.com/firebase/firebase-js-sdk/pull/5566/files#) for all non-major dependencies.
=> Update @types/tmp package

.changeset/khaki-fans-drop.md
Once again forgot to add minor bump to main package for minor bumps to dependents:
- Auth middleware https://github.com/firebase/firebase-js-sdk/pull/6151
- New database methods https://github.com/firebase/firebase-js-sdk/pull/6171
=> Minor bump for firebase main package

e2e/package.json
Updating firebase package as mentioned in [pull request 5566](https://github.com/firebase/firebase-js-sdk/pull/5566/files#) for all non-major dependencies.
=> Update firebase dependency

package.json, yarn.lock
Updating eslint-plugin-import as mentioned in [pull request 5566](https://github.com/firebase/firebase-js-sdk/pull/5566/files#) for all non-major dependencies.
=> Update eslint-plugin-import package

packages/database-compat/src/api/Database.ts, packages/firebase/compat/index.d.ts
Included INTERNAL properties in type definitions.
=> Updated documentation for compat to include new database APIs

package.json, packages/auth/api-extractor.json, packages/firestore-compat/package.json, packages/firestore-compat/tsconfig.json, packages/firestore/package.json, packages/firestore/tsconfig.json, repo-scripts/prune-dts/package.json, repo-scripts/prune-dts/tsconfig.json, yarn.lock
=> Update package eslint types

.github/workflows/release-staging.yml
Need to wait for merge to complete before checking out release branch!
=> Staging workflow: await merge

.changeset/sharp-rules-enjoy.md
Adding changeset for the PR https://github.com/firebase/firebase-js-sdk/pull/6350
=> Add Changeset for PR: 'Fix typo in GtagConfigParams #6350'

packages/firestore/test/integration/api/count.test.ts
Test cases are failing cause the current COUNT API is only returning dummy count 42.
=> create sample count test cases

.github/CODEOWNERS
Adding myself as owner so I can grant approval on SDK PRs.
=> Add IanWyszynski as codeowner for firebase-database

.changeset/orange-doors-swim.md, common/api-review/database.api.md, packages/database-compat/src/api/Reference.ts, packages/database-types/index.d.ts, packages/database/src/api/Reference_impl.ts, packages/firebase/compat/index.d.ts
Reverts firebase/firebase-js-sdk#6374
=> Revert "Updated type of action parameter for DataSnapshot#forEach"

.changeset/heavy-spiders-fry.md, common/api-review/firestore-lite.api.md, common/api-review/firestore.api.md, integration/firestore/firebase_export.ts, packages/firestore-compat/src/index.console.ts, packages/firestore/lite/register.ts, packages/firestore/src/api/database.ts, packages/firestore/src/core/database_info.ts, packages/firestore/src/lite-api/database.ts, packages/firestore/src/register.ts, packages/firestore/test/integration/api/database.test.ts, packages/firestore/test/integration/api/provider.test.ts, packages/firestore/test/integration/api/validation.test.ts, packages/firestore/test/integration/util/firebase_export.ts, packages/firestore/test/integration/util/helpers.ts, packages/firestore/test/lite/integration.test.ts, packages/firestore/test/util/api_helpers.ts
Reverts firebase/firebase-js-sdk#6552
=> Revert "Revert "Tomandersen/multi db"" -- and make api internal

.changeset/eleven-moons-shave.md
Amend changeset in https://github.com/firebase/firebase-js-sdk/pull/6107 to make sure main `fiirebase` package gets the same minor bump.
=> Bump main package to match firestore bump

packages/auth/src/mfa/assertions/totp.test.ts, packages/auth/src/mfa/assertions/totp.ts
The mfa/assertions/totp directory was accidentally created.
=> Move the totp assertion files into src/mfa/assertions/

packages/firebase/compat/index.d.ts
Resolving inconsistency in GithubAuthProvider example in compat docs
=> Update GithubAuthProvider compat example

packages/firestore/package.json, packages/firestore/src/core/target.ts, packages/firestore/src/protos/compile.sh, packages/firestore/src/protos/firestore_proto_api.ts, packages/firestore/src/protos/google/firestore/v1/query.proto, packages/firestore/src/protos/protos.json, packages/firestore/src/remote/serializer.ts, packages/firestore/test/integration/api/query.test.ts, packages/firestore/test/unit/local/query_engine.test.ts, packages/firestore/test/unit/remote/serializer.helper.ts
=> OR Queries public API and integration tests

common/api-review/auth.api.md, packages/auth/demo/public/index.html, packages/auth/demo/src/index.js, packages/auth/src/api/authentication/recaptcha.ts, packages/auth/src/core/auth/auth_impl.test.ts, packages/auth/src/core/auth/auth_impl.ts, packages/auth/src/core/credentials/email.test.ts, packages/auth/src/core/index.ts, packages/auth/src/core/strategies/email_and_password.test.ts, packages/auth/src/core/strategies/email_link.test.ts, packages/auth/src/model/public_types.ts
Note that our backend changes to `getRecaptchaConfig` is not ready yet. Added a TODO to e2e test the SDK changes later.
=> Update to revised public api initializeRecaptchaConfig

packages/firestore/src/core/sync_engine_impl.ts, packages/firestore/test/unit/specs/listen_spec.test.ts
=> Secondary Tab time travels with document deletes

package.json, packages/messaging-compat/package.json, packages/messaging-compat/test/fakes.ts, packages/messaging/package.json, repo-scripts/changelog-generator/package.json, yarn.lock
* Update @changesets/changelog-github
=> Update select non-major dependencies

config/functions/package.json, package.json, packages/auth-compat/demo/functions/package.json, packages/auth/demo/functions/package.json, packages/auth/package.json, packages/auth/test/integration/webdriver/util/test_server.ts, packages/rules-unit-testing/functions/package.json, packages/rules-unit-testing/functions/yarn.lock, yarn.lock
- Remove babel-plugin-transform-import-meta
- Update firebase-functions and @types/express for firebase-functions
- Update semver
=> Update select non-major dependencies 

.changeset/six-brooms-listen.md, packages/auth-compat/package.json, packages/auth/package.json
Fixes https://github.com/firebase/firebase-js-sdk/issues/6736
=> Add selenium-webdriver to devDependencies

e2e/package.json, integration/firebase/package.json, integration/messaging/package.json, package.json, packages/firestore/package.json, repo-scripts/api-documenter/package.json, repo-scripts/size-analysis/package.json, yarn.lock
- express 
- yargs
- @types/chai
- express
- json-stable-stringify
- @rushstack/ts-command-line
=> Update non-major dependencies

packages/auth/src/core/auth/auth_impl.ts, packages/auth/src/core/util/handler.ts, packages/auth/src/model/auth.ts, packages/auth/src/platform_browser/popup_redirect.test.ts, packages/auth/src/platform_browser/popup_redirect.ts
=> [Draft] Add App Check token to widget url fragment

.changeset/perfect-colts-scream.md, packages/database-compat/package.json
Fixed issue where vite with astro could not resolve the right output bundle.
=> Solve resolution issues with astrojs

.changeset/heavy-starfishes-count.md
=> Correcting the changeset's version bump type.

.changeset/heavy-starfishes-count.md
=> Downgrading version bump type from minor to patch

.changeset/sweet-rats-compete.md
Updated changeset for OR queries.
=> Updated the changeset for OR queries to be more descriptive

.changeset/lemon-lemons-wave.md
Added changeset for https://github.com/firebase/firebase-js-sdk/pull/7171
=> Changeset for fixing error message

README.md
Remove extra backtick from setting version
=> Remove extra backtick from README.md

scripts/ci/notify-test-result.js, scripts/release/utils/publish.ts
Revert publish logs (too verbose), catch E2E log request errors.
=> Catch E2E log request errors

packages/performance/src/services/api_service.ts
Fix a IndexedDB support error message in the Performance SDK.
N/A, a change to the string.
N/A
=> Fixed a error message typeo for IndexedDB in Performance.

scripts/emulator-testing/emulators/firestore-emulator.ts
=> Update testing emulator to 1.18.1

.github/workflows/test-all.yml
Brackets don't work if there aren't multiple entries.
=> Fix formatting error in "Test All Packages" workflow

.changeset/new-bananas-decide.md
Forgot to add firebase in https://github.com/firebase/firebase-js-sdk/pull/7452
=> Bump firebase to match firestore bump

.changeset/thick-lions-divide.md
Add a changeset summarizing the changes for password policy.
=> Add changeset for password policy

.changeset/fresh-frogs-heal.md, packages/webchannel-wrapper/externs/overrides.js
Followup fix of https://github.com/firebase/firebase-js-sdk/pull/7569
Fixes: https://github.com/firebase/firebase-js-sdk/issues/7581
=> Fix webchannel wrapper overrides

.github/workflows/test-changed-firestore.yml, packages/firestore/test/integration/api/query.test.ts, scripts/emulator-testing/emulators/firestore-emulator.ts
=> Fix MIEQ failure against Emulator on CI

scripts/docgen-compat/content-sources/js/toc.yaml
Add a missing entry to the compat toc.
=> Add IteratedDataSnapshot to compat toc

.changeset/ten-ads-return.md, packages/auth/index.rn.ts
PR for fixing github issue https://github.com/firebase/firebase-js-sdk/issues/7701 to provide support for Totp for react native apps.
=> Add export for totpMultifactorGenerator for react native bundle

.github/CODEOWNERS
+ @aashishpatil-g, -@jsdt,@jmwski
=> Update CODEOWNERS for rtdb

packages/firestore/test/unit/util/bundle_data.ts
=> Add tests for bundle to verify the support for empty array and map

.changeset/fifty-bees-matter.md
I mistakenly forgot to add a Changeset to [PR 7975](https://github.com/firebase/firebase-js-sdk/pull/7975). This PR adds it into `master` before this week's release.
N/A
N/A
=> Analytics ad_personalization & ad_user_data ConsentSettings changeset

packages/app/src/firebaseServerApp.ts
Add a new serverapp string for register version to track FirebaseServerApp usage.
CI.
N/A.
=> [FirebaseServerApp] add a new serverapp type for usage tracking.

.changeset/smart-turkeys-run.md
Add a missing changeset for the transitive dep update in PR #8088.
N/A
N/A.
=> Add a changset to the transitive dependency update

.changeset/cyan-pugs-buy.md, integration/messaging/package.json, package.json, packages/auth-compat/package.json, packages/auth/package.json, packages/firestore/package.json, packages/functions/package.json, packages/storage/package.json, repo-scripts/changelog-generator/package.json, yarn.lock
Update our undici dependency to 5.8.24 due to CVE-2024-30260.
Fixes #8132.
CI.
N/A.
=> Update undici dependency to 5.8.24 due to CVE-2024-30260.

.github/workflows/test-changed-firestore-integration.yml
Add fromJSON to convert env var string value to boolean.
=> Fix terraform steps in CI PR #2

e2e/package.json, package.json, yarn.lock
Minor babel dependency upgrades
=> Upgrade babel dependencies

CONTRIBUTING.md
#8276 
I reviewed the history: https://github.com/firebase/firebase-js-sdk/pull/113
@jshcrowthe
=> Remove dangling link to feature from toc

.github/workflows/test-all.yml
Remove the `.git` directory from archived build.
=> Remove git directory from archived build

.changeset/late-humans-tan.md
Fixed the format of a changeset file. I had hand edited a changeset in a previous PR and accidentally had stripped out the "release notes" section. This hadn't triggered the error in CI changset check script since the changeset wasn't yet in the main branch.
CI.
NA.
=> Fix format of a changset file.

packages/data-connect/CHANGELOG.md, packages/data-connect/src/api/DataConnect.ts, packages/data-connect/src/core/AppCheckTokenProvider.ts, packages/data-connect/src/network/fetch.ts, packages/data-connect/src/network/transport/index.ts, packages/data-connect/src/network/transport/rest.ts, packages/data-connect/src/register.ts, packages/data-connect/test/unit/dataconnect.test.ts
AppCheck support for Data Connect
=> Data Connect: Add support for appcheck

packages/vertexai/src/methods/generate-content.test.ts, packages/vertexai/src/requests/request.ts
Update text per https://docs.google.com/document/d/1Mh5kB_SozJgPFZcEGseb7aNhhS7BmFIXqurZlQObatM/edit?tab=t.2afqmaf1flcv#heading=h.aq898jn9xpo (internal link) (if docs jump around the heading is "Possible errors related to migrating")
=> Update API_NOT_ENABLED error for Vertex

packages/performance/rollup.config.js, packages/storage/rollup.config.js
These should have been part of the bigger PR, but I missed these.
=> Upgrade cjs bundles for storage and performance

.github/ISSUE_TEMPLATE/bug_report_v2.yaml
Merge after Data Connect is released.
=> Add dataconnect to issue form

common/api-review/vertexai.api.md, packages/vertexai/src/types/requests.ts
See https://github.com/firebase/firebase-ios-sdk/pull/13876#issuecomment-2407684407
=> Make SafetySettings.method optional

.github/CODEOWNERS
Make BLR team members and myself Auth owners.
=> Update CODEOWNERS for Auth

packages/auth/demo/package.json, packages/firebase/compat/rollup.config.js, packages/firebase/package.json, packages/firebase/rollup.config.js, packages/firestore-compat/package.json, packages/firestore/package.json, packages/firestore/rollup.config.js, packages/firestore/rollup.config.lite.js, packages/firestore/rollup.shared.js, yarn.lock
Fix renovate PR https://github.com/firebase/firebase-js-sdk/pull/8127 to include needed code changes as well.
=> Replace dependency rollup-plugin-terser with @rollup/plugin-terser 0.1.0

e2e/yarn.lock
Update the `yarn.lock` in e2e.
=> Update yarn.lock in e2e

packages/vertexai/test-utils/convert-mocks.ts, scripts/update_vertexai_responses.sh
Update the golden file script for the new formatting of golden files
=> fix golden files test

packages/firestore/src/lite-api/user_data_reader.ts, packages/firestore/src/util/bundle_builder_impl.ts
@MarkDuckworth took a pass at the serialization of bundled objects into a byte buffer using his Firestore innerworking knowhow.
N/A
N/A
=> Converting bundle protos to Proto3 JSON compatible format

common/api-review/vertexai.api.md, docs-devsite/vertexai.chatsession.md, docs-devsite/vertexai.generativemodel.md, packages/vertexai/src/api.ts, packages/vertexai/src/methods/chat-session.test.ts, packages/vertexai/src/methods/chat-session.ts, packages/vertexai/src/methods/chrome-adapter.ts, packages/vertexai/src/methods/generate-content.test.ts, packages/vertexai/src/methods/generate-content.ts, packages/vertexai/src/models/generative-model.test.ts, packages/vertexai/src/models/generative-model.ts
=> Define ChromeAdapter class

scripts/update_vertexai_responses.sh
Update Vertex AI mock responses to v10.
=> test(vertexai): update mock responses to v10

common/api-review/auth.api.md, docs-devsite/auth.auth.md, packages/auth/src/api/index.test.ts, packages/auth/src/api/index.ts, packages/auth/src/core/auth/auth_impl.ts, packages/auth/src/core/auth/register.ts, packages/auth/src/core/util/assert.ts, packages/auth/src/model/auth.ts, packages/auth/src/model/public_types.ts, packages/auth/test/helpers/mock_auth.ts
=> Throw Operation Not Allowed for Invalid Auth Endpoint (#9013)

.changeset/three-singers-wonder.md, common/api-review/util.api.md, packages/auth/src/core/auth/emulator.ts, packages/auth/src/platform_browser/index.ts, packages/database/src/api/Database.ts, packages/firestore/src/lite-api/database.ts, packages/functions/src/api.ts, packages/functions/src/service.ts, packages/storage/src/api.ts, packages/storage/src/service.ts, packages/util/src/emulator.ts
Cherry picks https://github.com/firebase/firebase-js-sdk/pull/8977 onto branch ending at 11.7.1 release commit.
=> Cherry pick #8977 for temporary release

docs-devsite/ai.md, packages/ai/src/types/error.ts
=> docs(ai): Fix 'occured' typo in error codes

.github/ISSUE_TEMPLATE/bug_report_v2.yaml
Update the dropdown item. I already updated the Github repo label.
=> Update issue template to rename VertexAI > AI

packages/remote-config/test/api.test.ts, packages/remote-config/test/client/realtime_handler.test.ts
This PR is a follow-up to https://github.com/firebase/firebase-js-sdk/pull/9206
This PR includes all the unit tests for the real-time Remote Config feature.
=> Realtime RC test cases
