packages/firestore/CHANGELOG.md, packages/firestore/src/util/sorted_set.ts, packages/testing/src/api/index.ts
This is a fix to https://github.com/firebase/firebase-js-sdk/issues/2620
Basically `SortedSet.unionWith` does not take the size of the two sets that it is merging into consideration.
What happens is, if there are two set: A that is empty, and B that has size of `N`. The union would take `O(N*logN)` while it could have been a no-op.
=> Add optimization to SortedSet.unionWith

packages/firestore/CHANGELOG.md, packages/firestore/src/platform_browser/webchannel_connection.ts
=> Disable use of $httpHeaders in Cordova

packages/firestore/src/api/blob.ts
Implementing Sebastian's [proposal](https://github.com/firebase/firebase-js-sdk/pull/2639/files#r381522694) for a more efficient conversion in a separate PR
=> More efficient Uint8Array conversion

packages/firestore/index.node.ts, packages/firestore/index.ts, packages/firestore/register-module.ts
This simplifies adding a new Memory-only Firestore build.
=> De-dupe module registration

packages/firestore/rollup.config.js, packages/firestore/src/util/api.ts
Removes the mangling from the Node Firestore build, which is probably not as sensitive to size. The actual fix for Node is to just add externs for `GRPC` and `grpcloader`, but at this point I am kind of wary of doing this as we have no integration tests for the mangled Node build.
I also disabled Terser's whitespace and comment removal, since this was previously not applied to NPM builds. 
Fixes https://github.com/firebase/firebase-js-sdk/issues/2655
=> De-mangle Node and CJS build

packages/firestore/src/api/blob.ts, packages/firestore/src/api/database.ts, packages/firestore/src/api/user_data_converter.ts, packages/firestore/src/model/field_value.ts, packages/firestore/src/remote/serializer.ts, packages/firestore/src/util/byte_string.ts, packages/firestore/test/unit/api/blob.test.ts, packages/firestore/test/unit/model/field_value.test.ts, packages/firestore/test/unit/remote/node/serializer.test.ts
This is a simplification that removes the api Blob types from our FieldValue API and exposed ByteString.compareTo() which I would like to use in the FieldValue rewrite.
This PR is against the feature branch since it might break canonical IDs.
=> Use ByteString in model types

packages/firestore/CHANGELOG.md, packages/firestore/src/model/field_value.ts
The implementation in `master` relies on the valueOf() semantics, which ends up comparing the Object value using JavaScript magic (but happens to match the desired outcome). Instead, we should directly compare the internal boolean value.
=> Make ordering for BooleanValues explicit

tools/gitHooks/license.js, tools/gitHooks/prepush.js, tools/gitHooks/prettier.js
Current guidance at go/copyright calls for copyright to be assigned to Google LLC, like so:
```
Copyright 2020 Google LLC
```
This change makes this the default without changing existing files. Going forward, any changed files will have their copyright line changed to match.
Note that 1ef26d56 shows what this rewrite will look like.
=> Allow for copyrights to be assigned to Google LLC

packages/firestore/src/platform_browser/webchannel_connection.ts, packages/webchannel-wrapper/externs/overrides.js, packages/webchannel-wrapper/src/index.d.ts
These will be deprecated in an upcoming google-closure-library release
Note: `backgroundChannelTest` already defaults to `true` and we don't use `testUrl`.
This replays cl/296469267 and cl/296469871.
=> Remove backgroundChannelTest and testUrl from WebChannelOptions

packages/firestore/src/api/user_data_converter.ts, packages/firestore/src/model/document.ts, packages/firestore/src/model/field_value.ts, packages/firestore/src/model/mutation.ts, packages/firestore/src/remote/serializer.ts, packages/firestore/test/unit/model/field_value.test.ts, packages/firestore/test/unit/model/mutation.test.ts
Port of https://github.com/firebase/firebase-android-sdk/pull/1150
Many more PRs to come. See https://github.com/firebase/firebase-android-sdk/pull/1217 for reference.
=> Add an ObjectValue builder

packages/firestore/src/model/field_value.ts, packages/firestore/src/model/proto_values.ts, packages/firestore/src/remote/serializer.ts, packages/firestore/src/util/misc.ts, packages/firestore/src/util/obj.ts
Port of https://github.com/firebase/firebase-android-sdk/pull/1157
Sending this to @wilhuff since it includes some gnarly type normalization that does not exist on Android (e.g. converts string numbers to numbers).
=> Adding Proto-based equality and comparison

packages/firestore/package.json, packages/firestore/rollup.config.js
This adds a mangled CJS build for Firestore and works around the fact that Terser's mangling doesn't work well with CJS by relying on the ESM build.
Size of WebApp with Firebase App + Firestore CJS before:
./bundle.js  445 KiB       0  [emitted]  [big]  main
Size of WebApp with Firebase App + Firestore CJS after:
./bundle.js  384 KiB       0  [emitted]  [big]  main
I confirmed in a simple test app that the build works in browsers (but more testing is always appreciated).
=> Add mangled CJS build

packages/firestore/test/util/values.ts
This is a port of https://github.com/firebase/firebase-android-sdk/pull/1158
=> Adding test utilities to create Value types

packages/database/src/api/Database.ts, packages/database/src/core/Repo.ts, packages/database/src/core/Repo_transaction.ts, packages/database/src/core/SyncTree.ts, packages/database/src/core/util/ServerValues.ts, packages/database/test/servervalues.test.ts
Reverts firebase/firebase-js-sdk#2500
Opening this up so https://github.com/firebase/firebase-js-sdk/pull/2499 can be merged once it is approved.
=> Revert "Revert: Add Database.Servervalue.increment(x)"

packages/storage/CHANGELOG.md, packages/storage/package.json, packages/storage/src/implementation/authwrapper.ts, packages/storage/src/implementation/request.ts, packages/storage/src/implementation/requestmaker.ts, packages/storage/test/request.test.ts
This populates the GMPID header for Storage on Web. 
See https://github.com/firebase/firebase-android-sdk/blob/e95f91e64c79206549302e9f37341534c29f58af/firebase-storage/src/main/java/com/google/firebase/storage/network/NetworkRequest.java#L53 for reference.
=> Populate GMPID header

.github/workflows/test-all.yml
Canary script is skipping release because checkout v2 doesn't have history it needs to compare.
=> Fix canary release

packages/firestore/src/core/event_manager.ts, packages/firestore/src/core/sync_engine.ts, packages/firestore/src/core/types.ts, packages/firestore/src/core/view.ts, packages/firestore/src/local/shared_client_state.ts, packages/firestore/src/remote/online_state_tracker.ts, packages/firestore/src/remote/remote_store.ts, packages/firestore/test/unit/core/event_manager.test.ts, packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
@Feiyang1 noticed in a sample app that multitab is not able to parse OnlineStates since the constants are rewritten to __PRIVATE_OnlineState:
```
@firebase/firestore: Firestore (7.9.1): SharedClientState Failed to parse online state: {"clientId":"Xnj51M6igYRWov1EHcwt","onlineState":"__PRIVATE_Unknown"}
```
This PR removes the enum usage for OnlineState, to make sure that the constant names are not mangled.
Multi-Tab uses the same concept for its other "enums": https://github.com/firebase/firebase-js-sdk/blob/bb1f4dee32dc4ee41066e176378e1b63aa1e1d14/packages/firestore/src/local/shared_client_state.ts#L209
As a guide, the size impact of this PR:
- +7 bytes versus master (before GZIP)
- -43 bytes versus master (after GZIP) WHEEE
=> Use explicit String constants for OnlineState

packages/storage/CHANGELOG.md, packages/storage/package.json, packages/storage/src/implementation/authwrapper.ts, packages/storage/src/implementation/request.ts, packages/storage/src/implementation/requestmaker.ts, packages/storage/test/request.test.ts
Reverts firebase/firebase-js-sdk#2670
We need to whitelist `x-firebase-gmpid` in the CORS preflight request.
Fixes https://github.com/firebase/firebase-js-sdk/issues/2695
=> Revert "Populate GMPID header"

.github/CODEOWNERS
Made a mistake, it was blocking ability of global approvers to approve changes made to doc files.
=> Add global approvers to doc changes in CODEOWNERS

config/tsconfig.base.json, packages/firebase/index.d.ts, packages/firestore-types/index.d.ts, packages/firestore/CHANGELOG.md, packages/firestore/externs.json, packages/firestore/src/api/timestamp.ts, packages/firestore/test/unit/api/timestamp.test.ts
Implement Timestamp.valueOf() so that Timestamp objects can be compared for relative ordering using the arithmetic comparison operators (i.e. <, <=, >, and >=).
Fixes #2632
=> Implement Timestamp.valueOf().

packages/analytics/index.test.ts, packages/analytics/index.ts, packages/analytics/src/factory.ts, packages/analytics/src/helpers.test.ts, packages/analytics/testing/get-fake-firebase-services.ts
More strongly tie promise `await`s in Analytics tests to the actual function being waited for, rather than generic ticks.  This will prevent test errors when upgrading `tslib` to a new version that handles promises more correctly.
=> Fix promises in Analytics tests

packages/firestore/src/api/user_data_converter.ts, packages/firestore/src/core/event_manager.ts, packages/firestore/src/core/query.ts, packages/firestore/src/core/sync_engine.ts, packages/firestore/src/core/target_id_generator.ts, packages/firestore/src/core/types.ts, packages/firestore/src/core/view.ts, packages/firestore/src/core/view_snapshot.ts, packages/firestore/src/local/shared_client_state.ts, packages/firestore/src/local/target_data.ts, packages/firestore/src/model/field_value.ts, packages/firestore/src/model/mutation.ts, packages/firestore/src/remote/online_state_tracker.ts, packages/firestore/src/remote/persistent_stream.ts, packages/firestore/src/remote/remote_store.ts, packages/firestore/src/remote/rpc_error.ts, packages/firestore/src/remote/watch_change.ts, packages/firestore/src/util/async_queue.ts, packages/firestore/src/util/log.ts, packages/firestore/test/unit/core/event_manager.test.ts, packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
This removes the overhead that Enums introduce in TypeScript by changing our enums to "const enums" which can be inlined: https://www.typescriptlang.org/docs/handbook/enums.html#const-enums
This also reverts some of the changes that were made to the OnlineState enum and uses the same solution.
Size before: 318393 bytes (90882 gzipped)
Size after: 315811 bytes (89863 gzipped - 1.2%)
=> Remove enum overhead

packages/firestore/src/model/field_value.ts, packages/firestore/src/model/proto_field_value.ts, packages/firestore/src/model/proto_values.ts, packages/firestore/src/protos/firestore_proto_api.d.ts, packages/firestore/src/remote/serializer.ts, packages/firestore/test/integration/api/database.test.ts, packages/firestore/test/unit/model/field_value.test.ts, packages/firestore/test/unit/model/object_value_builder.test.ts, packages/firestore/test/util/values.ts
Port of https://github.com/firebase/firebase-android-sdk/pull/1156
=> Protobuf-backed FieldValues

packages/firestore/src/local/indexeddb_schema.ts, packages/firestore/test/unit/local/indexeddb_persistence.test.ts
Port of https://github.com/firebase/firebase-android-sdk/pull/1182
=> Canonical ID Schema Migration

integration/firestore/package.json
We don't want to rebuild the whole repo when running tests. It will slow down `yarn test` at the root of the repo and CI.
=> Avoid rebuilding the repo during the global test run

packages/firestore/src/api/database.ts, packages/firestore/src/api/user_data_reader.ts, packages/firestore/src/api/user_data_writer.ts, packages/firestore/src/core/transaction.ts, packages/firestore/src/model/field_value.ts, packages/firestore/src/model/proto_field_value.ts, packages/firestore/test/unit/model/mutation.test.ts, packages/firestore/test/util/helpers.ts, packages/firestore/test/util/values.ts
This is a port of https://github.com/firebase/firebase-android-sdk/pull/1177 and also brings FieldValue.value() in line with other platforms
=> Introducing UserDataReader/UserDataWriter

.github/workflows/test-all.yml, scripts/release/cli.js, scripts/release/utils/npm.js
For best security practices, modify post-merge canary NPM publish to use wombat-dressing-room to publish.
Package-specific registry token is written to .npmrc before each publish command.
=> Set canary publish to use wombat-dressing-room proxy

packages/firebase/externs/firebase-firestore-externs.js
Minor update to firestore-externs needed to maintain compatibility for Closure users
=> Update @typedef to @type in firestore-externs

packages/auth/src/args.js, packages/auth/src/authcredential.js, packages/auth/src/multifactoruser.js, packages/auth/src/storage/localstorage.js, packages/auth/src/storage/sessionstorage.js, packages/auth/src/utils.js
Removes obsoleted closure APIs: goog.isString, goog.isNull, goog.isNumber, goog.isBoolean, etc.
=> Removes obsoleted closure APIs

packages/firebase/rollup-internal.config.js
Internal deploy guidelines require the full license to be included in generated files, we previously were using only an abbreviated format. Not sure what the origin of the abbreviated format was.
=> Add full license to generated files in internal deploy only

packages/firestore/CHANGELOG.md, packages/firestore/src/core/types.ts, packages/firestore/src/remote/serializer.ts, packages/firestore/src/util/types.ts, packages/firestore/test/integration/api/type.test.ts, packages/firestore/test/util/equality_matcher.ts
We have a couple of unit tests that verify that we treat DoubleValue -0.0 distinct from 0.0, but we were never storing -0.0 as a DoubleValue.
=> Support -0.0 in Firestore

packages/auth/src/authcredential.js
There is an internal deprecation of `forwardDeclare`. Internal deployment has already been modified by an automated change, changing our source of truth to match.
=> Fix closure line to match internal conformance requirements

packages/firestore/test/unit/specs/spec_builder.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
=> Remove base64 encoding of resume tokens in spec tests.

packages/firestore/src/api/user_data_writer.ts, packages/firestore/src/model/server_timestamps.ts
See https://github.com/firebase/firebase-js-sdk/pull/2715 for the bigger picture.
=> Add ServerTimestamp helpers

.vscode/launch.json, packages/database/src/core/Repo.ts, packages/database/test/servervalues.test.ts, scripts/emulator-testing/emulators/database-emulator.ts
Work in progress. I understand the bug fix that Mike wanted us to apply, though the result would still be pessimal (would require us to calculate resolved values always even if the there was no server values).
In trying to test the bug/fix I ran into some issues. It seems like the update command and racy sets are failing. The "handles sparse updates" test fails because the second {increment: X} is resolved as a set X. Some extra debug statements in the racy write case seem to suggest that the values are incrementing and re-decrementing with server-side results. The emulator itself seems to work, so I'm not sure what the problem is yet. Maybe the SyncTree?
=> Fix performance regression. Add tests against actual server behavior.

packages/firestore/test/unit/generate_spec_json.js
This just prints a message to console.log as each output JSON file is generated by generate_spec_json.js.  This output helps reduce impatience while waiting for the script to complete.
=> Log each file being generated by generate_spec_json.js.

package.json, renovate.json, yarn.lock
Our doc generation process assumes the location and format where typedoc outputs files to. Updating typedoc has broken the process and has introduced a lot noises in the past, so we will disable its update.
=> exclude typedoc from dep update

.github/workflows/cross-browser-test.yml, .github/workflows/test-all.yml, .github/workflows/test-changed.yml
Previously:
- "Run All Tests" ran when (1) a pull_request was closed and (2) the target branch was master. This left out some cases where we would want to run all tests, such as a direct merge to master.
- "Push/PR" ran tests on changed files, but the it runs 2 tests (1 each on the push trigger and PR trigger) that are redundant in most cases, and the "push" version may not diff correctly if the branch is stale, and may run too many tests.
Now:
- "Run All Tests" workflow is triggered on push to any branch. (Canary Deploy job only runs if the branch was master.)
- "Push/PR" renamed to "Test Modified Packages" and runs only on PR events (opened, synchronized, reopened) on any branch except master. This still may happen to run all tests if a key top level file was changed.
- "Cross Browser …
=> Update CI Triggers

packages/firestore/src/local/memory_persistence.ts, packages/firestore/test/unit/generate_spec_json.js, packages/firestore/test/unit/local/persistence_test_helpers.ts, packages/firestore/test/unit/specs/spec_test_runner.ts, packages/firestore/test/util/test_platform.ts
Our hard-coded dependency means that tree-shaking doesn't remove the unused LRU code for memory persistence. This PR removes the dependency and should also completely remove the estimated byte size accounting in the field value rewrite.
Before:
317762  firebase-firestore.js
274464  firebase-firestore.memory.js
After:
315861  firebase-firestore.js
270591  firebase-firestore.memory.js
=> Make MemoryLru tree-shakeable

packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/persistence.ts, packages/firestore/src/local/simple_db.ts, packages/firestore/test/unit/generate_spec_json.js, packages/firestore/test/unit/local/encoded_resource_path.test.ts, packages/firestore/test/unit/local/index_free_query_engine.test.ts, packages/firestore/test/unit/local/indexeddb_persistence.test.ts, packages/firestore/test/unit/local/local_store.test.ts, packages/firestore/test/unit/local/persistence_transaction.test.ts, packages/firestore/test/unit/local/remote_document_cache.test.ts, packages/firestore/test/unit/local/simple_db.test.ts, packages/firestore/test/unit/local/test_index_manager.ts, packages/firestore/test/unit/local/test_mutation_queue.ts, packages/firestore/test/unit/local/test_remote_document_cache.ts, packages/firestore/test/unit/local/test_remote_document_change_buffer.ts, packages/firestore/test/unit/local/test_target_cache.ts, packages/firestore/test/unit/specs/spec_test_runner.ts, packages/firestore/test/util/test_platform.ts
Addressing an old TODO and treating all transactions as idempotent. We no longer use non-idempotent transactions:
https://cs.corp.google.com/search/?q=%22%27readwrite%27%22+file:%5E//depot/google3/third_party/javascript/firebase/src/packages/firestore/src/+package:%5Epiper$&type=cs
https://cs.corp.google.com/search/?q=%22%27readwrite-primary%27%22+file:%5E//depot/google3/third_party/javascript/firebase/src/packages/firestore/src/+package:%5Epiper$&type=cs
https://cs.corp.google.com/search/?q=%22%27readonly%27%22+file:%5E//depot/google3/third_party/javascript/firebase/src/packages/firestore/src/+package:%5Epiper$&type=cs
vs (as an example):
https://cs.corp.google.com/search/?q=%22%27readonly-idempotent%27%22+file:%5E//depot/google3/third_party/javascript/firebase/src/packages/firestore/src/ …
=> Remove non-idempotent transactions

package.json, tools/gitHooks/prepush.js
Putting a husky hook in `scripts` in `package.json` has been deprecated for a long time and seems to have been removed entirely in a recent upgrade, causing prepush steps to not run at all. Moved `prepush` hook to the correct location.
=> Move husky hook to correct location

packages/firestore/rollup.config.js
#2608 re-introduced mangling to the Node build, which wasn't mangled before. Since it uses CJS, the output is not minified very well. This reverts this change and makes sure the next release uses the same settings as the current release.
=> Remove mangling from Node build

packages/firebase/index.d.ts
Fix https://github.com/firebase/firebase-js-sdk/issues/2780. Typescript <3.x does not recognize `unknown`.
=> Fix `onLog` type in public API to be compatible with Typescript <3.x

packages/analytics-types/index.d.ts, packages/analytics/src/constants.ts, packages/firebase/index.d.ts
Update Analytics types and method signatures to reflect GA's enhanced ecommerce options.
- Some events and params have been added.
- Some have been deprecated.
- Some existing methods have the number of suggested params expanded.
The latter should only affect IDE autocomplete. All event params are always optional and any additional arbitrary param is always allowed.
This changes the public API and will require a documentation update.
Internal bug for this feature: b/151107871
=> Update analytics ecommerce event and param types

packages/analytics/package.json, packages/app/index.ts, packages/app/package.json, packages/auth/package.json, packages/component/package.json, packages/database/package.json, packages/firebase/package.json, packages/firestore/package.json, packages/functions/package.json, packages/installations/package.json, packages/logger/package.json, packages/messaging/package.json, packages/performance/package.json, packages/remote-config/package.json, packages/rxfire/package.json, packages/storage/package.json, packages/template/package.json, packages/testing/package.json, packages/util/package.json
Today, to work on a SDK, we usually run `yarn build` at the root folder first in order to build its dependencies. This step is quite slow because it is building the entire monorepo including repos that are not dependencies of the SDK.
This PR addresses the issue by adding a new npm script `build:deps` to each SDK, which builds the SDK and its dependencies in one command.
After this change, you don't need to run `yarn build` at the root folder any more. Instead, you would directly cd into your SDK directory and run `yarn build:deps`.
Build time improvement
`yarn build` at root -  234.25s
`yarn build:deps` in `pacakges/firestore` - 124.01s
`yarn build:deps` in `pacakges/database` - 33.34s
=> Add a script to build only the SDK and its dependencies

packages/firestore/src/api/database.ts, packages/firestore/src/api/user_data_writer.ts, packages/firestore/src/core/firestore_client.ts, packages/firestore/src/core/sync_engine.ts, packages/firestore/src/local/index_free_query_engine.ts, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/lru_garbage_collector.ts, packages/firestore/src/local/memory_persistence.ts, packages/firestore/src/local/shared_client_state.ts, packages/firestore/src/local/simple_db.ts, packages/firestore/src/platform_browser/browser_connectivity_monitor.ts, packages/firestore/src/platform_browser/webchannel_connection.ts, packages/firestore/src/platform_node/grpc_connection.ts, packages/firestore/src/remote/backoff.ts, packages/firestore/src/remote/online_state_tracker.ts, packages/firestore/src/remote/persistent_stream.ts, packages/firestore/src/remote/remote_store.ts, packages/firestore/src/remote/rpc_error.ts, packages/firestore/src/remote/watch_change.ts, packages/firestore/src/util/assert.ts, packages/firestore/src/util/async_queue.ts, packages/firestore/src/util/log.ts, packages/firestore/test/unit/util/async_queue.test.ts
Small cleanup for our logging.
The main reason for going down this path is that I am trying to remove namespace imports and I don't want to refer to `error` and `debug` as free-standing functions.
=> Simplify logging

packages/firestore/src/api/database.ts
This PR fixes #2822.
It ensures `this._firestore.ensureClientConfigured().write(this._mutations);` is being executed in the same event loop as the call of `batch.commit()`.
=> Fix #2822: consistent write timing between refs and WriteBatch

packages/database/src/core/Repo.ts, packages/database/src/core/util/ServerValues.ts
Addresses #2487 by creating a new interface that lets us defer reading existing values from a SyncTree until it's actually needed and restricted to the smallest possible scope.
=> Add an interface to ServerValues that lets us read synctrees just in time

.github/workflows/health-metrics-test.yml
Health metrics tests use secrets in this repo to work properly. However, secrets are not available in workflows triggered by pull requests from forked repo, therefore the metrics tests will always fail there. Disabling it to avoid leaving a failure mark on those pull requests.
https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#using-encrypted-secrets-in-a-workflow
=> Disable health-metrics test in pull requests from forked repo.

packages/firestore/src/core/firestore_client.ts, packages/firestore/src/core/sync_engine.ts, packages/firestore/test/unit/specs/limbo_spec.test.ts, packages/firestore/test/unit/specs/spec_builder.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
This change was motivated by the following bug report: https://github.com/firebase/firebase-js-sdk/issues/2683.  In summary, the issue was that when a large number of documents went into limbo (in this case 15,000 documents) then this would cause 15,000 document listens, which would result in "resource-exhausted" errors.  The client would then back off for a bit but would try the listens again, which would again result in "resource-exhausted" errors.  And the cycle would continue.  Worst of all, the customer was being billed for all of these reads that had no beneficial effects for the clients.
In order to avoid this situation, this PR modifies the limbo resolution logic to "throttle" the limbo resolutions.  It does this by allowing at most 100 concurrent limbo resolutions.  Limbo …
=> Implement limbo resolution throttling.

packages/firestore/src/platform_browser/browser_platform.ts, packages/firestore/src/util/misc.ts
=> Fix IE11 broken by Crypto change.

packages/firestore/test/unit/generate_spec_json.js
This fixes the following error when `generate_spec_json.js` is run:
```
Error: FIRESTORE (7.11.0) INTERNAL ASSERTION FAILED: Platform not set
```
This error was introduced by https://github.com/firebase/firebase-js-sdk/commit/cae46453 a few days ago.  The easy fix is to just set the platform in main().
=> Call PlatformSupport.setPlatform() in generate_spec_json.js

packages/firestore/src/remote/serializer.ts, packages/firestore/test/unit/specs/spec_test_runner.ts, packages/firestore/test/util/helpers.ts, packages/firestore/test/util/spec_test_helpers.ts
This PR moves test-only code out of our serializer in order to reduce SDK size.
It also pretty-prints the resume token in Spec tests since all good PRs need to have at least one unrelated change... :)
=> Move test code to test helpers

packages/messaging/CHANGELOG.md
FCM starts to have CHANGELOG.md for release notes (Thanks to the JS core and DevRel folks for creating/reviewing the previous release notes).
The first entry include the release note  that is meant for the release scheduled on 2020-04-02.
The fix will address the issues in https://github.com/firebase/firebase-js-sdk/issues/2712
=> Create FCM's CHANGELOG.md with a release note.

packages/firestore/src/api/database.ts, packages/firestore/src/remote/watch_change.ts
Follow up from the customer issue in which Firestore was iterating through inactive targets multiple times in the logs. 
Additional change from prettier in database.ts that was probably not pushed up.
=> Only iterate across active targets in WatchChangeAggregator

.github/workflows/cross-browser-test.yml, config/karma.saucelabs.js, packages/analytics/index.test.ts, packages/functions/karma.conf.js, packages/functions/test/browser/callable.test.ts
Fix some failing IE tests in analytics and functions.
Also fixed error in workflow file so that cross-browser workflow will run again.
=> Fix Saucelabs tests in analytics and functions

package.json, packages/firestore/package.json, packages/firestore/test/unit/specs/describe_spec.ts, yarn.lock
Currently, the JSON generated by `generate_spec_json.js` uses `JSON.stringify()`, which generates JSON with the keys ordered by the order in which they are set in the objects.  As a result, code changes that alter the order in which the keys as added but have no other side effects cause different stringified JSON to be generated, resulting in unnecessarily-noisy diffs.
This PR changes `generate_spec_json.js` to use the third-party `json-stable-stringify` library: https://www.npmjs.com/package/json-stable-stringify.  This library produces JSON that has a stable key ordering, resulting in diffs when and only when keys are added, removed, or have their values modified.
I also implemented a custom comparator so that the generated JSON has a semblance of human readability, with the test …
=> Generate stable JSON from generate_spec_json.js

packages/firestore/CHANGELOG.md
This change to the change log was forgotten in the PR that added throttling: #2790
=> Update CHANGELOG.md to mention limbo resolution throttling

packages/firestore/src/platform/platform.ts, packages/firestore/src/platform_browser/browser_platform.ts, packages/firestore/src/platform_node/node_platform.ts, packages/firestore/src/util/misc.ts, packages/firestore/test/util/test_platform.ts
This PR temporarily reverts the feature #2764: Use a cryptographically-strong random number generator for generating document IDs.  We received several bug reports from users prompting us to revisit the implementation.  In order to unblock those users, I am temporarily reverting the feature so that it can be picked up in tomorrow's release.
The issues in question are: #2832, #2858, and #2870.
=> Revert: Use crypo RNG for auto ID generation to reduce conflicts

packages/firestore/test/unit/specs/limbo_spec.test.ts
Limbo resolution throttling is now implemented in Android, and, therefore, the spec tests for that feature should be enabled: https://github.com/firebase/firebase-android-sdk/pull/1374
=> Remove 'no-android' tags from spec tests for limbo resolution throttling

packages/database-types/index.d.ts, packages/database/CHANGELOG.md, packages/database/src/api/Database.ts, packages/database/test/servervalues.test.ts, packages/firebase/index.d.ts
As per API proposal: go/servervalue-increment-api
=> Make ServerValue.increment() public

packages/firestore/CHANGELOG.md
This is the change log entry that was forgotten in https://github.com/firebase/firebase-js-sdk/pull/2872.
=> Add CHANGELOG.md entry for reverting the usage of 'crypto'

packages/messaging/src/controllers/sw-controller.test.ts, packages/messaging/src/controllers/sw-controller.ts
A step towards fixing all cross-browser tests.  This is the only failing test for Messaging.
=> Fix Messaging test that fails in Firefox

packages/firestore/src/core/component_provider.ts, packages/firestore/src/core/firestore_client.ts, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/memory_persistence.ts, packages/firestore/src/local/persistence.ts, packages/firestore/src/util/assert.ts, packages/firestore/test/unit/local/indexeddb_persistence.test.ts, packages/firestore/test/unit/local/persistence_test_helpers.ts, packages/firestore/test/unit/specs/spec_test_runner.ts, packages/firestore/test/unit/util/async_queue.test.ts
So... obviously the component provider design broke the other PR I had in flight. In https://github.com/firebase/firebase-js-sdk/pull/2879, I rely on the ability to provide a custom persistence implementation in the SpecTest that can inject failures. With the ComponentProvider as implemented, I would have to build up all components from scratch. It would be nice if I only needed to change the persistence layer.
I pushed three versions:
- e01a7c3 is cleaner, but increases size by 580b (full build) / 973b  (memory)
- 9725015 moves some shared code to ComponentBuilder. This only helps the full build (+241b instead of 580b)
- f1d4a49 gets rid of the abstract class and has a size increase of 311b (full) / 725b (memory)
I personally prefer the last option (the diff of this PR).
=> ComponentProvider v2

packages/auth/src/authstorage.js, packages/auth/test/authstorage_test.js
Fixes ability to set Auth LOCAL persistence explicitly in a worker environment.
Fixes https://github.com/firebase/firebase-js-sdk/issues/2903
=> Worker persistence

packages/storage/src/implementation/list.ts, packages/storage/src/implementation/requests.ts, packages/storage/test/requests.test.ts
We need to use the same bucket in the list response as in the list request.
Fixes https://b.corp.google.com/issues/152053124
=> Prefix list results with correct bucket

packages/firestore/CHANGELOG.md, packages/firestore/src/core/component_provider.ts, packages/firestore/src/core/transaction_runner.ts, packages/firestore/src/local/shared_client_state.ts, packages/firestore/src/remote/backoff.ts, packages/firestore/src/util/async_queue.ts, packages/firestore/test/integration/api_internal/transaction.test.ts, packages/firestore/test/unit/specs/recovery_spec.test.ts, packages/firestore/test/unit/specs/remote_store_spec.test.ts, packages/firestore/test/unit/specs/spec_builder.ts, packages/firestore/test/unit/specs/spec_test_components.ts, packages/firestore/test/unit/specs/spec_test_runner.ts, packages/firestore/test/unit/util/async_queue.test.ts, packages/firestore/test/util/test_platform.ts
This PR allows us to recover from IndexedDB failures when a Multi-Tab operation scheduled via a WebStorage notification fails. 
To do this:
- It introduces the concept of "retryable" operations. These are directly retried on the AsyncQueue.
- All retryable operations use the same retry mechanism. It is assumed that if the first retryable operation fails, the second would fail to.
- Retries use the same exponential backoff that we use for our streams (down to the delays).
Since a operation that is schedule via a `DelayedOperation` is always run after all other operations, the PR also changes the backoff handler to use `AsyncQueue.enqueue` directly if the backoff is zero. This is not required, but not doing this breaks all tests that rely on WebStorage since `AsyncQueue.drain()` does not …
=> Retry WebStorage operations

packages-exp/auth-exp/package.json, packages-exp/auth-exp/src/api/index.test.ts, packages-exp/auth-exp/src/api/index.ts
=> Add support for API timeouts to auth-next

packages-exp/auth-exp/package.json, packages-exp/auth-exp/src/core/util/browser.test.ts, packages-exp/auth-exp/src/core/util/browser.ts, packages-exp/auth-exp/src/core/util/version.test.ts, packages-exp/auth-exp/src/core/util/version.ts
=> Add version helpers to auth-next

tools/gitHooks/license.js, tools/gitHooks/prettier.js
Some contributors have reported problems where the prettier prepush commit does not work. Sometimes the problem seems to be that the commit happens but is not pushed, and will be pushed if the user does a second push immediately after. Maybe some additional log messages will help us narrow down the problem when it happens again.
=> Add more messages to prettier prepush to help diagnose intermittent problems

packages/firestore/.eslintrc.js, packages/firestore/src/local/simple_db.ts, packages/firestore/src/platform_browser/browser_connectivity_monitor.ts, packages/firestore/src/platform_browser/browser_platform.ts, packages/firestore/src/platform_node/node_platform.ts, packages/firestore/test/integration/browser/webchannel.test.ts, packages/firestore/test/integration/util/helpers.ts, packages/firestore/test/unit/local/indexeddb_persistence.test.ts, packages/firestore/test/unit/local/persistence_promise.test.ts, packages/firestore/test/unit/local/persistence_test_helpers.ts, packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts, packages/firestore/test/util/helpers.ts, packages/firestore/test/util/test_platform.ts
This should help us find issues such as https://github.com/firebase/firebase-js-sdk/issues/2870 before they surface in ReactNative and WebWorkers.
=> Discourage use of 'window' and 'document'

common/api-review/app-exp.api.md, config/api-extractor.json, packages-exp/app-exp/api-extractor.json, packages-exp/app-exp/internal/package.json, packages-exp/app-exp/package.json, packages-exp/app-exp/rollup.config.js, packages-exp/app-exp/rollup.config.release.js, packages-exp/app-exp/src/api.test.ts, packages-exp/app-exp/src/api.ts, packages-exp/app-exp/src/index.ts, packages-exp/app-exp/src/internal.test.ts, packages-exp/app-exp/src/internal.ts, packages-exp/app-exp/src/registerCoreComponents.ts, packages-exp/app-exp/use_public_typings.js
Previously internal functions are exported in the submodule `@firebase/app-exp/internal`. This PR changes to directly export them in `@firebase/app-exp`. It removes the `internal` folder and the package.json inside it and simplifies the build configuration. It also makes it harder for developers to use our internal methods accidentally.
We generate 2 d.ts files as part of the build process.  One has only public API and is used to publish to npm, so developers won't be able to import internal methods. The other one has both public and internal APIs and is used during development, so other Firebase SDKs can import the internal methods.
=> Make @firebase/app-next have single entry point

packages/firestore/rollup.shared.js, packages/firestore/scripts/remove-asserts.ts, packages/firestore/src/util/assert.ts, packages/firestore/test/unit/specs/recovery_spec.test.ts
Goal: Reduce size of SDK by stripping error messages that should not show up in production builds. We can still trace the original error by looking at the stacktrace.
=> Strip messages for fail() and hardAssert()

packages/firestore/src/core/sync_engine.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/shared_client_state.ts, packages/firestore/test/unit/specs/recovery_spec.test.ts, packages/firestore/test/unit/specs/spec_builder.ts
This solves a problem where we were able to modify a in-memory state before the database transaction failed and also addresses issues where targets to allocate already existed or rejected targets were missing. 
I believe there are no other issues in the WebStorage callbacks.
=> Make 'handleClientStateEvent()/handleQueryTargetEvent()' idempotent

tools/gitHooks/prettier.js
Accidentally removed in https://github.com/firebase/firebase-js-sdk/pull/2909
=> Restore accidentally removed return statement.

packages/messaging/src/controllers/sw-controller.ts
Hello folks, 
Instead of comparing the href (cause the user can be in a other page), we compare the host and take the first page that has the same host
Fix: https://github.com/firebase/firebase-js-sdk/issues/390
=> feat(sw-controller): compare host instead of href for getWindowClient

packages-exp/auth-compat-exp/index.rn.ts, packages-exp/auth-compat-exp/package.json, packages-exp/auth-compat-exp/rollup.config.js
Adds react native target for dependency injection of package `react-native` (not `@react-native-community/async-storage` for consistency with old SDK) in compat layer.
Note that this build target wasn't added to auth-exp because the new package will need user specification on which package to use to setup.
=> Added react native build target

packages/firestore/test/unit/specs/spec_test_components.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
In https://github.com/firebase/firebase-js-sdk/pull/2879, I added a new spec_test_components file to not further increase the size of the spec_test_runner file. This PR removes other helper classes for the SpecTestRunner to this file. This was done using IntelliJ, I did not modify anything manually.
=> Move code to spec_test_components

packages-exp/firebase-exp/package.json, packages-exp/firebase-exp/rollup.config.js, packages-exp/firebase-exp/rollup.config.release.js, packages/firebase/rollup.config.js, yarn.lock
This hack is no longer needed as of `rollup-plugin-typescript2` version 0.26.0 and we are on 0.27.0.
`yarn build` and `yarn build:exp` succeeded after removal.
https://github.com/ezolenko/rollup-plugin-typescript2/pull/203
=> Remove objectHashIgnoreUnknownHack

packages/firestore/src/util/async_queue.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/2991
=> Check for addEventListener() before calling

.github/workflows/test-all.yml, common/api-review/app-exp.api.md, integration/browserify/package.json, integration/firebase-typings/package.json, integration/firestore/package.json, integration/typescript/package.json, integration/webpack/package.json, package.json, packages-exp/app-exp/package.json, packages/analytics/package.json, packages/app/package.json, packages/auth/package.json, packages/component/package.json, packages/database/package.json, packages/firestore/package.json, packages/functions/package.json, packages/installations/package.json, packages/logger/package.json, packages/messaging/package.json, packages/performance/package.json, packages/remote-config/package.json, packages/rxfire/package.json, packages/storage/package.json, packages/template/package.json, packages/testing/package.json, packages/util/package.json, scripts/run_changed.js, scripts/run_tests_in_ci.js
This is a followup PR for https://github.com/firebase/firebase-js-sdk/pull/2980. It further reduces clutter in the CI explorer.
Credit: https://github.com/firebase/firebase-js-sdk/pull/2954
=> Hide messages from build tools and test runners for passed packages

packages/firestore/src/api/user_data_reader.ts, packages/firestore/src/model/mutation.ts, packages/firestore/src/model/object_value.ts, packages/firestore/src/remote/serializer.ts, packages/firestore/test/integration/api/database.test.ts, packages/firestore/test/unit/remote/serializer.helper.ts, packages/firestore/test/unit/util/misc.test.ts, packages/firestore/test/util/helpers.ts
I would like to not use SortedSet in FieldMask since the Rest Wrapper API ideally does not pull in our custom Red Black Tree. FieldMasks are used in any update/set(merge:true) call.
Right now, I have a debug assert that makes sure FieldMasks only contain unique fields. This means we have to validate this as we turn user data into FieldMasks. We could also strip duplicated fields in the FieldMask constructor.
=> Drop SortedSet from FieldMask

packages/rxfire/docs/firestore.md
Closes #2572 
All changes were made in firestore.
Made the following changes in separate commits:
- Fixed format error so function parameters are now displayed.  Also fixed function name in collectionData table.
- Updated function descriptions (see questions below)
- Cleaned up examples 
Questions:
I'm not sure how good the new function descriptions are.  I still have a few questions:
- sortedChanges: says the function"emits the reduced state of individual changes".   What does that mean?
- sortedChanges: it isn't clear from the description how sortedChangesis different than collectionChanges.  I wasn't able to clarify.
Thanks!
=> Clean up rxfire API documentation

packages/firestore/CONTRIBUTING.md
At some point the command to run the Firestore emulator changed from
```
firebase serve --only firestore
```
to
```
firebase emulators:start --only firestore
```
This PR updates `CONTRIBUTING.md` to reflect this update.
=> Update command to run the Firestore emulator

packages-exp/auth-exp/src/api/authentication/token.test.ts, packages-exp/auth-exp/src/api/authentication/token.ts, packages-exp/auth-exp/src/api/index.ts, packages-exp/auth-exp/src/core/auth/auth_impl.test.ts, packages-exp/auth-exp/src/core/auth/auth_impl.ts, packages-exp/auth-exp/src/core/user/token_manager.test.ts, packages-exp/auth-exp/src/core/user/token_manager.ts, packages-exp/auth-exp/src/core/user/user_impl.test.ts, packages-exp/auth-exp/src/core/user/user_impl.ts, packages-exp/auth-exp/src/model/auth.d.ts, packages-exp/auth-exp/test/mock_auth.ts, packages-exp/auth-exp/test/mock_fetch.ts
=> Add refresh token endpoint + implementation to token manager

packages/firestore/src/local/lru_garbage_collector.ts, packages/firestore/test/unit/local/lru_garbage_collector.test.ts
Rationale is that they the LRU task will retry its run when it is invoked next.
There are no tests since the GC scheduling code is not tested right now. Let me know if you would like me to add tests.
Note that there is a behavior change: If the primary lease is lost, the GC run is rescheduled. It will however get stoped in
https://github.com/firebase/firebase-js-sdk/blob/5a60243bf264967819fc5c3897892084c5eb4d43/packages/firestore/src/core/component_provider.ts#L203
=> Ignore IndexedDB failures during garbage collection

packages/firestore/src/api/user_data_writer.ts, packages/firestore/test/integration/api/type.test.ts
Fix the regression introduced in #2784: a `GeoPoint` where at least one of the coordinates is zero doesn't marshal properly. This is because zeroes happen to be serialized as `undefined` (presumably because protos normally treat zero values and the absence of a value interchangeably) which then fails the strict input validation in `GeoPoint`.
Fixes #3006.
=> Fix `GeoPoint` field values with a zero coordinate failing input validation

packages/firestore/src/protos/firestore_proto_api.d.ts, packages/firestore/src/remote/datastore.ts
This adds a new `invokeRunQueryRpc` RPC that is used (and tested) in the Lite SDK to run queries via Rest.
This is similar to https://github.com/firebase/firebase-js-sdk/blob/96cd91dd7825f845ce860ffb98703dc48716b81b/packages/firestore/src/remote/datastore.ts#L124
Note: 
- The Query RPC needs a parent set. The types are not correct in `master`. See https://github.com/googleapis/googleapis/blob/master/google/firestore/v1/firestore.proto#L442
- RunQueryResponse returns a stream of documents followed by an empty result which just has `readTime` set. See https://github.com/googleapis/googleapis/blob/master/google/firestore/v1/firestore.proto#L477
=> Add invokeRunQueryRpc()

packages/firestore/index.console.ts, packages/firestore/src/api/blob.ts, packages/firestore/src/api/database.ts, packages/firestore/src/platform/config.ts, packages/firestore/test/integration/api/private_constructors.test.ts, packages/firestore/test/unit/api/blob.test.ts, packages/firestore/test/unit/api/field_value.test.ts, packages/firestore/test/unit/local/local_store.test.ts, packages/firestore/test/unit/model/mutation.test.ts, packages/firestore/test/unit/remote/serializer.helper.ts
The pattern in api/database.ts breaks tree-shaking since it instatiates static references to all public API types. I moved this code to platform/config.ts which is used to register the non Tree-Shakeable API
=> Remove static references to API types

packages/firestore/src/core/query.ts, packages/firestore/src/model/document.ts, packages/firestore/test/unit/model/document_set.test.ts, packages/firestore/test/util/helpers.ts
Changes for consumed API for `deleteDocument`:
=> Remove dependency on valueCompare from Document

packages/firestore/src/platform/platform.ts, packages/firestore/src/platform_browser/browser_platform.ts, packages/firestore/src/platform_node/node_platform.ts, packages/firestore/src/util/misc.ts, packages/firestore/test/util/test_platform.ts
Manually verified on IE11 and web-workers.
=> Reland "Use crypo RNG for auto ID generation to reduce conflicts (#2764)"

packages/firestore/src/remote/remote_store.ts, packages/firestore/test/unit/specs/recovery_spec.test.ts
This PR takes the network offline if we fail to talk to IndexedDB when applying a query snapshot or rejection.
Also cleans up some Promise handling in RemoteStore.
=> Take WatchStream offline when IndexedDB is unavailable

packages/firestore/src/local/local_store.ts
This is not used and hence we don't need to add recovery logic.
=> Remove unused remoteDocumentKeys()

package.json, scripts/utils.js, tools/gitHooks/license.js, tools/gitHooks/precommit.js, tools/gitHooks/prettier.js
Moved prepush scripts (prettier, license, api-report) to run on precommit. Since they now run on staged and not committed files, they only `git add` and do not create commits.  Some changes have been made to properly diff staged files against master, or staged files against unstaged files, as appropriate.
Also attempts to fetch `origin/master` before diffing to reduce anomalies caused by stale clones.
=> Move prepush scripts to precommit

packages/firestore/src/core/sync_engine.ts, packages/firestore/src/local/indexeddb_mutation_queue.ts, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/indexeddb_target_cache.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/memory_mutation_queue.ts, packages/firestore/src/local/memory_persistence.ts, packages/firestore/src/local/memory_target_cache.ts, packages/firestore/src/local/persistence.ts, packages/firestore/test/unit/local/lru_garbage_collector.test.ts, packages/firestore/test/unit/local/mutation_queue.test.ts, packages/firestore/test/unit/local/target_cache.test.ts, packages/firestore/test/unit/specs/listen_spec.test.ts
This changes `notifyLocalViewChanges` so that it has not side effects if the transaction fails. The main change is that I removed the indirection of the reference delegate to ask the LocalStore what documents are "pinned". Instead, the Local Store directly tells the reference delegate about every document that is added to a View.
Adresses #2755
=> Make notifyLocalViewChanges idempotent

packages/firestore/CHANGELOG.md, packages/firestore/src/api/field_value.ts, packages/firestore/src/api/user_data_reader.ts, packages/firestore/test/integration/api/numeric_transforms.test.ts
This reverts a behavior change in https://github.com/firebase/firebase-js-sdk/pull/3001
Before this PR, the parse contexts we used to parse ArrayTransform and Increment values was detached from the original parse context that was used to parse the update. Thus, setting the field path for the value that was being incremented did not end up modifying the context that was used to generate the Proto. The result of this was `{ updateMask: [] }`. By removing the copy, we ended up with `{ updateMask: ['sum'] }`, which ended up rewriting the value before applying the increment.
Fixes https://github.com/firebase/firebase-js-sdk/issues/3045
=> Fix regression for merge with increment

packages/firestore/test/unit/specs/recovery_spec.test.ts, packages/firestore/test/unit/specs/spec_builder.ts, packages/firestore/test/unit/specs/spec_test_components.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
Disclaimer: This is pretty ugly... feedback appreciated :)
The idea of the PR is to expand the new "failDatabase" spec test feature to allow the tests to specify which transaction action to fail. This allows individualized failures for operations that spawn multiple actions. Currently, we only test scenarios where the first transaction fails. This will allows us to test what happens if the first transaction succeeds and the second one fails.
=> Allow failing of individual transactions

packages/firestore/src/core/sync_engine.ts, packages/firestore/test/unit/specs/recovery_spec.test.ts, packages/firestore/test/unit/specs/spec_test_components.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
=> IndexedDB Recovery for Limbo documents

packages/firestore/src/core/sync_engine.ts
Goal: Don't change local state before all IndexedDB transactions succeed.
=> Transition to primary only if IndexedDB ops succeed

packages/firestore/src/core/sync_engine.ts
Follow up to https://github.com/firebase/firebase-js-sdk/pull/3049/files
=> Clean up isPrimary

packages/firestore/test/unit/specs/recovery_spec.test.ts
This runs the Memory tests with LRU persistence instead of not running them at all.
Diff without whitespace: https://github.com/firebase/firebase-js-sdk/compare/mrschmidt/gcenabled?expand=1&w=1
=> Use gcEnabled instead of durable persistence

packages/firestore/src/local/local_store.ts, packages/firestore/test/unit/specs/recovery_spec.test.ts
This adds code to ignore failures during `notifyLocalViewChanges`. This should only affect LRU GC and only mean that the documents get GCed earlier.
If we have to add recovery logic we probably need to buffer these changes and apply them via `enqueueRetryable` before running LRU GC. That's why I am hoping that we don't need to.
Disclaimer: I am not sure if this is actually correct, but I hope it is.
=> Ignore failures for notifyLocalViewChanges

packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/test/unit/local/indexeddb_persistence.test.ts
=> Ignore IndexedDB failure during lease refresh

packages/firestore/test/unit/local/indexeddb_persistence.test.ts, packages/firestore/test/unit/specs/spec_test_components.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
This is already part of https://github.com/firebase/firebase-js-sdk/pull/3038, but it looks like it broke CI for everyone so I pulled in out into a separate PR.
This broke because https://github.com/firebase/firebase-js-sdk/pull/3052 and https://github.com/firebase/firebase-js-sdk/pull/3020 were both passing CI on their own but not combined.
=> Fix Firestore build

packages-exp/firebase-exp/package.json, packages/app/package.json, packages/firebase/package.json, packages/webchannel-wrapper/package.json, scripts/run_changed.js
For a more safety, we would like `run_changed.js` (the script behind the Test Changed Packages workflow) to fail if it finds a package without a "test" or "test:ci" script (whichever command it is running).
A maintainer can put placeholder stubs for those scripts if the package does not have tests to run, but this will prevent accidentally forgetting to add a test script.
Added stubs for these scripts to packages that did not have them.
=> Ensure run_changed errors on packages without test script

packages/firestore/test/integration/api/database.test.ts
The tests for queries where the promise was rejected were disabled because there was not a known way to create a query that was accepted by the client but rejected by the server. Recently, I discovered how to make just such a query: use a collection that is a sub-collection of a document with an invalid name. I have re-enabled these tests using this strategy. Thanks for @schmidt-sebastian for bringing these tests to my attention. (Google internal ticket for this issue: b/156772969).
=> Enable tests for query rejection.

packages/firestore/src/core/firestore_client.ts
Porting from [iOS](https://github.com/firebase/firebase-ios-sdk/pull/5632).
=> Make removeSnapshotsInSyncListener run on AQ

packages/firestore/src/core/firestore_client.ts, packages/firestore/src/core/sync_engine.ts, packages/firestore/test/unit/specs/recovery_spec.test.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
=> IndexedDB recovery for handleUserChange

packages/performance/src/services/remote_config_service.test.ts, packages/performance/src/services/remote_config_service.ts, packages/performance/src/services/settings_service.ts, packages/performance/src/services/transport_service.test.ts, packages/performance/src/services/transport_service.ts
Remove the capability of sending events to clearcut from the Performance SDK. This removes the need for fetching the RC configs to decide on the dispatch destination - so that is removed in the settings service and remote config service.
=> Remove the capability of sending events to clearcut from the Performance SDK.

packages/firebase/index.d.ts, packages/firestore-types/index.d.ts, packages/firestore/CHANGELOG.md, packages/firestore/src/api/database.ts, packages/firestore/src/api/field_value.ts, packages/firestore/src/api/user_data_reader.ts, packages/firestore/src/util/input_validation.ts, packages/firestore/test/integration/api/fields.test.ts, packages/firestore/test/integration/api/validation.test.ts, packages/firestore/test/integration/util/helpers.ts, packages/firestore/test/util/helpers.ts
Port of https://github.com/googleapis/nodejs-firestore/pull/1062
=> Add ignoreUndefinedProperties

packages/firestore/test/unit/local/indexeddb_persistence.test.ts, packages/firestore/test/unit/specs/recovery_spec.test.ts, packages/firestore/test/unit/specs/spec_builder.ts, packages/firestore/test/unit/specs/spec_test_components.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
Almost all recovery spec tests only fail a single Transaction type. This PR cleans up the spec tests to make the calling code a lot prettier.
=> Clean up recovery spec tests

packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/indexeddb_schema.ts, packages/firestore/src/local/indexeddb_target_cache.ts, packages/firestore/test/unit/local/indexeddb_persistence.test.ts, packages/firestore/test/unit/specs/recovery_spec.test.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
This adds a test that verify that we can bubble up the exception from `getHighestListenSequenceNumber` to `enablePersistence()`. The client can then proceed with MemoryPersistence: https://github.com/firebase/firebase-js-sdk/blob/3de5763b76d19314db1355072b9e0d9ccea70ccc/packages/firestore/src/core/firestore_client.ts#L325
=> Add test for getHighestListenSequenceNumber() recovery

packages/firestore/lite/index.d.ts
This adds the API for the Lite SDK as approved in go/firestore-next
=> Add Firestore Lite API

packages/firestore/CHANGELOG.md, packages/firestore/src/local/index_free_query_engine.ts, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/lru_garbage_collector.ts, packages/firestore/src/remote/backoff.ts, packages/firestore/src/remote/online_state_tracker.ts, packages/firestore/src/remote/persistent_stream.ts, packages/firestore/src/util/async_queue.ts, packages/firestore/src/util/promise.ts, packages/firestore/test/integration/api_internal/idle_timeout.test.ts, packages/firestore/test/integration/remote/stream.test.ts, packages/firestore/test/unit/local/indexeddb_persistence.test.ts, packages/firestore/test/unit/specs/spec_test_runner.ts, packages/firestore/test/unit/util/async_queue.test.ts
The code to fast-forward the IndexedDB retries uses `runDelayedOperationsEarly()`, which runs not only the provided delayed operation, but all operations that were scheduled prior. This causes the OnlineStateTimer to run on page visibility events (see #2923).
Since Timer operations are likely not dependent on one another, it seems better to only run the provided operation. This also makes the API much less surprising.
Note that `op.skipDelay()` cannot be used directly in the visibility handler since we do not keep track of the DelayedOperation once it is scheduled via the backoff algorithm.
Fixes https://github.com/firebase/firebase-js-sdk/issues/2923
=> Only run the provided delayed operation early

packages/firestore/src/core/sync_engine.ts, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/local_store.ts, packages/firestore/test/unit/specs/listen_spec.test.ts, packages/firestore/test/unit/specs/recovery_spec.test.ts
This removes a `releaseQuery` call from Multi-Tab synchronization. The idea of this code path in synchronizeQueryViewsAndRaiseSnapshots is that it releases and re-allocates a query if a new primary already has a local query view but needs to make sure that it matches the data in IndexedDB before starting a Listen.
We should not need to call `releaseTarget`  here, since it overwrites the target data with potentially stale state. Instead, we just load the latest state via `allocateTarget` which has the ability to load a target from disk or from memory. I added a check to also update the in-memory data when it is stale, but I wasn't able to find any difference for this using a spec tests I hacked together (not committed).
=> Address potential IndexedDB failure in synchronizeQueryViewsAndRaiseSnapshots

packages/firestore/src/core/component_provider.ts, packages/firestore/src/core/sync_engine.ts, packages/firestore/src/core/transaction.ts, packages/firestore/src/core/transaction_runner.ts
This PR:
- Removes the need to round-trip through RemoteStore to create a Transaction.
- Removes the SortedMap dependency in Transaction to reduce code size in the Lite SDK.
=> Allow shared usage of Transaction

packages/logger/src/logger.ts
When Firestore and other users of Logger set log level on their instance only, this change allows them to use string input in addition to LogLevel enums. Firestore has a public interface that takes string input (just as the top-level `setLogLevel()` does) and needs to use this input to set logLevel on the Firestore logger instance only.
=> Make instance logLevel setter able to process string input

packages/firestore/src/api/database.ts
Non-empty string is validated right above.
=> Remove redundant input validation

packages/firestore/exp/index.d.ts, packages/firestore/exp/index.node.ts, packages/firestore/exp/src/api/foobar.ts, packages/firestore/exp/test/deps/verify_dependencies.test.ts
To the best of my knowledge this is the API that is approved for the Tree-Shakeable client as per go/firestore-next
This check in matches the Lite API here: https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore/lite/index.d.ts
=> Add Firestore Tree-Shakeable API

packages/firestore/src/api/database.ts, packages/firestore/src/api/user_data_reader.ts, packages/firestore/src/api/user_data_writer.ts, packages/firestore/test/util/helpers.ts
Introduces a common base type for all DocumentReference APIS. DocumentKeyReference exposes all state that is common between the Lite, Full and Legacy SDKs.
Updates UserDataReader and UserDataWriter to use the DocumentKeyReference.
=> Allow shared usage of UserDataReader and UserDataWriter

packages/firestore/src/core/component_provider.ts
This fixes a regression in the memory-only build that went unnoticed because we never ran the memory-only integration tests on CI (see https://github.com/firebase/firebase-js-sdk/pull/3127).
We need to throw the right error if `enablePersistence()` is used in the memory-only build. If it is used, the "durable" flag will be true in the MemoryComponentProvider, which should trigger a user-level exception and not a debugAssert.
=> Raise an error for enablePersistence() in memory-only build

packages/firestore/src/core/component_provider.ts, scripts/run_changed.js
@thebrianchen noticed that one of our integration tests that only runs as part of integration/firestore broke. It looks like this was possible because we did not run those tests as part of Firestore changes.
=> Run integration/firestore tests for Firestore code changes

.github/workflows/test-all.yml, .github/workflows/test-changed.yml
Context: I tried to check in theses changes along with my integration test changes. However, I am getting a `bad credential` response from FCM Send Service upon triggering a send request. This is a response thrown when the `server key`  is faulty or missing (local tests seems to indicated that my server key is functional). The remaining possible culprits include: 
a) Secret checked in is somehow wrong (maybe a trailing space? etc) -or-
b) Secrets must already be included in the ci runs prior than using it in a post-commit run -or-
c) Secret is somehow not included into process.Env   
This PR is created to examine the validity of hypo b). Hopeful it would resolve the issue 🍺
=> Add the FCM secret to applicable CI paths.

packages/firestore/src/local/indexeddb_mutation_queue.ts, packages/firestore/src/local/indexeddb_schema.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/memory_mutation_queue.ts, packages/firestore/src/local/mutation_queue.ts, packages/firestore/src/model/mutation_batch.ts, packages/firestore/src/remote/persistent_stream.ts, packages/firestore/src/remote/remote_store.ts, packages/firestore/test/unit/local/counting_query_engine.ts, packages/firestore/test/unit/local/local_store.test.ts, packages/firestore/test/unit/local/mutation_queue.test.ts, packages/firestore/test/unit/local/test_mutation_queue.ts
This extracts the Stream Token removal from https://github.com/firebase/firebase-js-sdk/pull/2995 into a separate PR, so it can be more easily reverted should the backend add full support for the stream tokens.
We are removing the Stream Tokens to ease IndexedDB recovery.
Proof of concept PR that implements IndexedDB recovery with Stream Tokens: https://github.com/firebase/firebase-js-sdk/pull/3131
=> Remove support for lastStreamToken

packages-exp/auth-exp/src/core/auth/auth_impl.test.ts, packages-exp/auth-exp/src/core/auth/auth_impl.ts, packages-exp/auth-exp/src/core/strategies/credential.ts, packages-exp/auth-exp/src/core/user/account_info.test.ts, packages-exp/auth-exp/src/core/user/account_info.ts, packages-exp/auth-exp/src/core/user/reload.test.ts, packages-exp/auth-exp/src/core/user/reload.ts, packages-exp/auth-exp/src/core/user/user_impl.ts, packages-exp/auth-exp/src/index.ts, packages-exp/auth-exp/src/model/auth.d.ts, packages-exp/auth-exp/src/model/user.d.ts
This change also updates the way the auth object handles notifications and persistence. This new way more closely matches the behavior of the JS sdk.
=> Add updateProfile, updateEmail, updatePassword

packages/firestore/lite/index.node.ts, packages/firestore/lite/src/api/field_value.ts, packages/firestore/lite/test/integration.test.ts, packages/firestore/src/api/field_value.ts, packages/firestore/src/api/user_data_reader.ts, packages/firestore/test/unit/api/field_value.test.ts, packages/firestore/test/util/helpers.ts
This PR adds the FieldValue methods to the Lite SDK.
It also solves a problem with the FieldValue methods in the current ("legacy") SDK. Our API promises that the FieldValue implementations returned by FieldValue.insertNameHere() methods are an instance of FieldValue. This was not the case anymore. I solved this by adding a wrapper type that wraps the FieldValue class in the Lite and Legacy SDK, which allows both SDKs to use different FieldValue types without duplicating all implementations.
This PR also prefixes the internal "toFieldTransform" method with an underscore since this is a class returned by the public API.
=> Add FieldValue methods to the Lite SDK

packages/firestore/package.json
Script `build` should only build regular packages
=> Do not build firestore lite in build because it breaks regular release build

packages/firestore/exp/index.d.ts, packages/firestore/lite/index.d.ts, packages/firestore/lite/index.node.ts
This adds setLogLevel() to the lite SDK. Note that (at least for now) we don't validate API input, so we don't need to call the wrapper. Discussion on this is still pending.
=> Add setLogLevel()

packages/firestore/lite/index.node.ts, packages/firestore/lite/src/api/reference.ts, packages/firestore/src/api/user_data_reader.ts
This adds the DocumentReference type to the Lite SDK. 
Inspired by https://github.com/firebase/firebase-js-sdk/blob/4a70e17f009ea6ab4949178b64c9bbeb68c88af5/packages/firestore/src/api/database.ts#L937
=> Add DocumentReference

packages/firestore/src/local/indexeddb_persistence.ts
We also need to ignore IndexedDB lease refresh failures for clients that don't opt into synchronizeTabs.
@thebrianchen This also removes an unused argument to `updateClientMetadataAndTryBecomePrimary`.
=> Ignore lease refresh failures for single-tab clients

packages/firestore/src/api/database.ts, packages/firestore/test/integration/api/database.test.ts
We have been checking the converter when performing equality checks in `DocumentReference`, but not for `Query` and `CollectionReference`. This PR standardizes all classes that contain converters to check for them when making equality checks.
Also, @schmidt-sebastian, wouldn't this be considered a breaking change?
=> Check for converter in Query.isEqual()

packages/firestore/lite/src/api/reference.ts, packages/firestore/lite/src/api/snapshot.ts, packages/firestore/src/api/database.ts, packages/firestore/src/api/user_data_reader.ts, packages/firestore/test/unit/api/document_change.test.ts, packages/firestore/test/util/api_helpers.ts, packages/firestore/test/util/helpers.ts
One of the comments in the Transaction PR was about a missing converter argument. This PR should make these problems go away by no longer allowing `undefined`.
I also stumbled across a test Firestore that I can use instead of `fakeFirestore`.
=> Make Converter passing explicit

packages/firestore/src/api/credentials.ts, packages/firestore/src/api/user_data_reader.ts, packages/firestore/test/integration/api/validation.test.ts
Fixes a regression introduced in #3048 which changed the context.path variable from `Path|null` to `undefined|null`.
Fixes https://github.com/firebase/firebase-js-sdk/issues/3172
=> Throw proper error for FieldValue transforms in arrays

packages/firestore/src/api/credentials.ts
When a token refresh fails because of we got a token callback while fetching the token, we could refetch the token instead of throwing an error with Code ABORTED.
This is meant to address https://github.com/firebase/firebase-js-sdk/issues/2923#issuecomment-638983250, which shows:
```
[Log] [2020-06-04T17:00:57.554Z]  @firebase/firestore: – "Firestore (7.14.5): PersistentStream" – "close with error: FirebaseError: [code=unknown]: Fetching auth token failed: getToken aborted due to token change." (vendor.js, line 179863)
[Error] [2020-06-04T17:00:57.555Z]  @firebase/firestore: – "Firestore (7.14.5): Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: FirebaseError: [code=unknown]…"
=> Refetch token if attempt was invalidated

packages/firebase/firestore/memory/package.json
When doing the following, as mentioned [here](https://firebase.google.com/support/release-notes/js#version_7130_-_march_26_2020):
```js
import * as firebase from 'firebase/app';
import 'firebase/firestore/memory';
```
You get hit with the following error message:
```
Cannot find module 'firebase/firestore/memory' from ...
```
Turns out, the following files are generate to the dist folder...
* index.esm.js
* index.node.cjs.js
...but the "main" path in the package.json is set to `dist/index.cjs.js`.
This PR fixes the main path to `index.node.cjs.js`, which fixes the import issues.
=> [Bugfix] Wrong "main" path for firestore/memory

packages/firestore/CHANGELOG.md, packages/firestore/src/api/credentials.ts
Add missing changelog for #3184
=> Add missing changelog for #3184

packages/firestore/package.json
Fixes https://github.com/firebase/firebase-js-sdk/issues/3196
Changed it to `^1.0.0`. @schmidt-sebastian Are you comfortable with the caret range? Does `grpc-js` follow semver?
=> upgrade grpc-js

packages/firestore/index.rn.memory.ts, packages/firestore/index.rn.ts, packages/firestore/memory/package.json, packages/firestore/package.json, packages/firestore/rollup.config.es2017.js, packages/firestore/src/platform_browser/browser_platform.ts, packages/firestore/src/platform_rn/rn_init.ts, packages/firestore/src/platform_rn/rn_platform.ts, yarn.lock
This builds work out of the box in RN since it relies on js-base64 for base64 encoding.
Fixes https://github.com/firebase/firebase-js-sdk/issues/2667
=> Add Firestore ReactNative build

packages-exp/auth-exp/src/core/credentials/anonymous.test.ts, packages-exp/auth-exp/src/core/credentials/anonymous.ts, packages-exp/auth-exp/src/core/credentials/email.test.ts, packages-exp/auth-exp/src/core/credentials/email.ts, packages-exp/auth-exp/src/core/credentials/index.d.ts, packages-exp/auth-exp/src/core/credentials/phone.test.ts, packages-exp/auth-exp/src/core/credentials/phone.ts, packages-exp/auth-exp/src/core/errors.ts, packages-exp/auth-exp/src/core/providers/anonymous.test.ts, packages-exp/auth-exp/src/core/providers/anonymous.ts, packages-exp/auth-exp/src/core/providers/email.test.ts, packages-exp/auth-exp/src/core/providers/email.ts, packages-exp/auth-exp/src/core/providers/phone.ts, packages-exp/auth-exp/src/core/strategies/credential.ts, packages-exp/auth-exp/src/core/strategies/email_and_password.test.ts, packages-exp/auth-exp/src/core/strategies/email_and_password.ts, packages-exp/auth-exp/src/core/strategies/email_link.test.ts, packages-exp/auth-exp/src/core/strategies/email_link.ts, packages-exp/auth-exp/src/core/strategies/phone.ts, packages-exp/auth-exp/src/core/user/reload.test.ts, packages-exp/auth-exp/src/core/user/user_credential_impl.test.ts, packages-exp/auth-exp/src/core/user/user_credential_impl.ts, packages-exp/auth-exp/src/index.ts, packages-exp/auth-exp/test/mock_auth_credential.ts, packages-exp/auth-types-exp/index.d.ts
also cleanup all our credential inheritance
=> add signInWithEmailAndPassword & signInWithEmailLink to auth-next

packages/firestore/lite/index.node.ts, packages/firestore/lite/src/api/database.ts, packages/firestore/lite/src/api/reference.ts, packages/firestore/lite/src/api/snapshot.ts, packages/firestore/lite/src/api/transaction.ts, packages/firestore/lite/src/api/write_batch.ts, packages/firestore/lite/test/helpers.ts, packages/firestore/lite/test/integration.test.ts, packages/firestore/src/api/database.ts, packages/firestore/src/core/query.ts, packages/firestore/src/util/input_validation.ts, packages/firestore/test/util/api_helpers.ts
This adds all Query filters and getQuery to the light client. As part of this, I moved a lot the internal logic from the "legacy" Query class to BaseQuery, which allows me to share most of the validation logic.
=> Add Query/getQuery

tools/gitHooks/precommit.js
I was always a bit nervous about putting a network request into a precommit hook. This will fail the fetch and continue the commit if it doesn't fetch within 10 seconds. If it fails the only cost is that the prettier and license diffs may be a bit outdated, not worth blocking a commit. But it seems useful to at least attempt to fetch first, if it doesn't take too long.
=> Add a timeout to git fetch in precommit hook

packages/firebase/src/index.rn.ts, packages/firestore/memory/package.json, packages/firestore/package.json, packages/firestore/rollup.config.es2017.js
The current build has a major issue with base64 encoding, which breaks the WriteStream and likely Query resumption on the Watch Stream. This PR removes the files that make this functionality accessible.
Fixes https://github.com/firebase/firebase-js-sdk/issues/3243
=> Disable React Native build

packages/firestore/lite/test/dependencies.json, packages/firestore/src/core/event_manager.ts, packages/firestore/src/core/query.ts, packages/firestore/src/core/sync_engine.ts, packages/firestore/src/core/target.ts, packages/firestore/src/local/indexeddb_remote_document_cache.ts, packages/firestore/src/local/indexeddb_target_cache.ts, packages/firestore/src/local/local_serializer.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/memory_persistence.ts, packages/firestore/src/local/memory_target_cache.ts, packages/firestore/src/local/remote_document_change_buffer.ts, packages/firestore/src/remote/serializer.ts, packages/firestore/src/remote/watch_change.ts, packages/firestore/src/util/obj_map.ts, packages/firestore/test/unit/core/query.test.ts, packages/firestore/test/unit/local/indexeddb_persistence.test.ts, packages/firestore/test/unit/local/target_cache.test.ts, packages/firestore/test/unit/specs/describe_spec.ts, packages/firestore/test/unit/specs/spec_builder.ts, packages/firestore/test/unit/specs/spec_test_runner.ts, packages/firestore/test/unit/util/obj_map.test.ts, packages/firestore/test/util/equality_matcher.ts
This is the first step in making Query tree-shakeable (but has not side impact on its own, since the non tree-shakeable Query relies on all functionality).
This PR:
- Makes all Target methods tree-shakeable.
- Split up Target into Target/TargetImpl, which adds a lot of code and indirection, but hides the memoizedCanonicalId from the public API
- Updated ObjectMap to use the new equals functions instead of Equatable, which allows Targets to still be stored in Objects.
- Adds the ability to use the new equals methods in our custom test equals helper.
The diff is easier to review in IntelliJ (it correlates more of the existing code). In general, this PR only contains moved code and no logic modifications.
=> Tree-shakeable Target

packages/firestore/src/core/firestore_client.ts, packages/firestore/src/core/sync_engine.ts, packages/firestore/src/remote/remote_store.ts, packages/firestore/src/remote/remote_syncer.ts, packages/firestore/test/unit/specs/recovery_spec.test.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
This changes the user change to be much more explicit:
- At first, we take RemoteStore offline
- Then SyncEngine applies the user change (with recovery)
- Only when the user change in SyncEngine succeeds do we take the network back online
Replaces https://github.com/firebase/firebase-js-sdk/pull/3192
Fixes #3179
=> Take RemoteStore offline during user change

packages/firestore/package.json
We are excluding -exp packages from being handled by changeset, so no other packages should take dependencies on them. It should not have any impact on Firestore since we have already disabled linting for them https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore/.eslintrc.js#L57.
=> remove -exp deps from firestore in preparation to enabling changeset

packages/firestore/src/util/api.ts
`makeConstructorPrivate` currently does not re-assign static members in the ESM2017 build, which essentially breaks the static methods on Blob, FieldValue and FieldPath.
=> Expose static members of public types in ESM2017 build

packages-exp/functions-types-exp/package.json
This was overlooked in https://github.com/firebase/firebase-js-sdk/pull/3051.
=> Set functions-types-exp package to private

package.json, scripts/release/utils/tests.js
Need this script for release, to avoid testing unbuilt -exp packages.
Also switch to `test:ci` because we don't need passing tests to be that verbose during release.
=> Add yarn script that runs tests on non-exp packages only

packages/firestore/src/core/component_provider.ts, packages/firestore/src/local/local_store.ts, packages/firestore/test/unit/local/local_store.test.ts
Make LocalStore an interface and have `LocalStoreImpl implements LocalStore`. Public fields in `LocalStoreImpl` then becomes file private, because `LocalStoreImpl` is not exported.
=> Make LocalStore an interface.

packages/firestore/lite/src/api/reference.ts, packages/firestore/lite/test/dependencies.json, packages/firestore/src/api/database.ts, packages/firestore/src/api/field_path.ts, packages/firestore/src/api/user_data_reader.ts, packages/firestore/src/local/encoded_resource_path.ts, packages/firestore/src/local/reference_set.ts, packages/firestore/src/model/document_key.ts, packages/firestore/src/model/object_value.ts, packages/firestore/src/model/path.ts, packages/firestore/src/remote/serializer.ts, packages/firestore/test/unit/local/encoded_resource_path.test.ts, packages/firestore/test/unit/specs/query_spec.test.ts
This changes:
- ResourcePath.EMPTY_PATH to ResourcePath.emptyPath()
- FIeldPath.EMPTYPATH to FIeldPath.emptyPath()
- FIeldPath._DOCUMENT_ID (inlined, only 1 usage)
- DocumentKey.EMPTY ((inlined, only 2 usages)
=> Remove remaining static references

packages/firestore/src/protos/firestore_proto_api.d.ts, packages/firestore/src/remote/persistent_stream.ts
We don't need to roundtrip the stream token through our Base64 serializer.
Note: This is not the fix to the RN breakage. We are adding full base64 support in https://github.com/firebase/firebase-js-sdk/pull/3251
=> Don't serialize/deserialize stream token

packages/firestore/src/util/async_queue.ts, packages/firestore/test/unit/specs/recovery_spec.test.ts, packages/firestore/test/unit/specs/spec_test_runner.ts, packages/firestore/test/unit/util/async_queue.test.ts
One of the behavior changes of `enqueueRetryable` (https://github.com/firebase/firebase-js-sdk/pull/2879) was that it only scheduled the next operation when the first operation succeeds. This means that any operation that was scheduled after the second retryable operation will run before this run:
```
enqueue(console.log(1))
enqueueRetryable(console.log(2))
enqueueRetryable(console.log(3))
enqueue(console.log(4))
-> prints 1,2,4,3 since 3 is only enqueued once 2 finishes
```
While theoretically okay, this still seems to cause some issues with the user change. This PR changes the retry behavior so that operations run in the original order if no failure occurred. 
Addresses https://github.com/firebase/firebase-js-sdk/issues/3218
=> Don't delay retryable operations

packages-exp/auth-exp/src/core/user/additional_user_info.test.ts, packages-exp/auth-exp/src/platform_browser/recaptcha/recaptcha_loader.test.ts, packages-exp/auth-exp/src/platform_browser/recaptcha/recaptcha_loader.ts, packages-exp/auth-exp/src/platform_browser/recaptcha/recaptcha_verifier.test.ts, packages-exp/auth-exp/src/platform_browser/recaptcha/recaptcha_verifier.ts
* Remove global exported consts
* Remove `get` property, replaced w/ traditional method
=> Address (some) of the tree shaking issues w/ ReCaptcha

packages/firestore/exp/index.d.ts, packages/firestore/lite/index.d.ts, packages/firestore/lite/src/api/database.ts
Add support for _FirebaseService and _removeServiceInstance
=> Integrate with app-exp

.changeset/cuddly-rivers-add.md, packages/messaging/src/core/token-management.ts
It seems we are saving the old token back to indexeddb instead of the new token. The PR fixes it.
=> Fix updateToken

.changeset/thin-ligers-fold.md, packages/firestore/src/api/database.ts
It fixes an issue where passing rxjs `Observer` to `onSnapshot` causes error `Error: Uncaught TypeError: this._next is not a function`.
For example,
```
const data$ = rxjs.Observable.create(function subscribe(observer) {
firebase.firestore().collection('test').onSnapshot(observer);
});
data$.subscribe({
next: data => handleData(data)
});
```
A similar issue is being fixed for FCM - https://github.com/firebase/firebase-js-sdk/pull/3221
=> Make onSnapshot work with rxjs observers

.changeset/nasty-pigs-invite.md, config/functions/package.json, packages/functions/src/api/service.ts, packages/functions/test/callable.test.ts, tools/config.js
Fixes https://github.com/firebase/firebase-js-sdk/issues/3289
=> clear failAfter timeout after request resolves

packages/auth/src/args.js, packages/auth/src/auth.js
goog.isFunction has been deprecated since Q2 2020.
=> Remove usages of goog.isFunction

packages/firestore/test/unit/api/document_change.test.ts, packages/firestore/test/unit/core/event_manager.test.ts, packages/firestore/test/unit/core/query.test.ts, packages/firestore/test/unit/core/view.test.ts, packages/firestore/test/unit/local/index_free_query_engine.test.ts, packages/firestore/test/unit/local/indexeddb_persistence.test.ts, packages/firestore/test/unit/local/local_store.test.ts, packages/firestore/test/unit/local/lru_garbage_collector.test.ts, packages/firestore/test/unit/local/mutation_queue.test.ts, packages/firestore/test/unit/local/remote_document_cache.test.ts, packages/firestore/test/unit/local/target_cache.test.ts, packages/firestore/test/unit/remote/serializer.helper.ts, packages/firestore/test/unit/specs/collection_spec.test.ts, packages/firestore/test/unit/specs/existence_filter_spec.test.ts, packages/firestore/test/unit/specs/limbo_spec.test.ts, packages/firestore/test/unit/specs/limit_spec.test.ts, packages/firestore/test/unit/specs/listen_spec.test.ts, packages/firestore/test/unit/specs/offline_spec.test.ts, packages/firestore/test/unit/specs/orderby_spec.test.ts, packages/firestore/test/unit/specs/perf_spec.test.ts, packages/firestore/test/unit/specs/persistence_spec.test.ts, packages/firestore/test/unit/specs/query_spec.test.ts, packages/firestore/test/unit/specs/recovery_spec.test.ts, packages/firestore/test/unit/specs/remote_store_spec.test.ts, packages/firestore/test/unit/specs/resume_token_spec.test.ts, packages/firestore/test/unit/specs/spec_test_runner.ts, packages/firestore/test/unit/specs/write_spec.test.ts, packages/firestore/test/util/helpers.ts
This is mechanical test refactor that is part of https://github.com/firebase/firebase-js-sdk/pull/3390, but extracted out to make it easier to review. It adds a test helper that hides some of the indirection that a functional Query API brings with it.
Most of this PR is renaming `query` to `query1` for local variables to avoid name clashes.
No functional changes. The new test helper is in the very last file.
=> Add query() test helper

packages/firestore/exp/index.d.ts, packages/firestore/lite/index.d.ts, packages/firestore/lite/src/api/reference.ts
As per go/firestore-next-amendment
=> Add type to DocumentReference/CollectionReference/Query

packages/rxfire/package.json
Rxfire has a dependency on firebase in both peerDependencies and devDependencies, and when changesets script sees the peerDependency version requirement (a broad range) is met, it skips updating the devDependency version. This causes problems in our release process. Temporarily removing until we can make a PR to the Changesets project that may help fix this.
=> Temporarily remove firebase devDependency from rxfire

packages/firebase/index.d.ts
Hi! Noticed that the `initializeApp()` TypeScript popups that have example code were using `applicationId` instead of `appId` so this updates them! Thanks for the awesome project!
=> docs: updating initializeApp() TypeScript @example

packages/rxfire/package.json
Messed up conflict resolution when merging https://github.com/firebase/firebase-js-sdk/pull/3381
=> Re-remove firebase devDependency from rxfire

packages/firestore/exp/index.d.ts, packages/firestore/lite/index.d.ts, packages/firestore/lite/src/api/reference.ts, packages/firestore/lite/test/integration.test.ts
This adds new methods, which are pending review in go/firestore-next-amendment.
The new collection methods allows direct access to subcollections. Instead of `collection(doc(coll, 'a'), 'b')` we now support `collection(coll, 'a/b')`. This matches the behavior of this method when call with `db` (Firestore) already.
The same change is made for `doc`.
=> Add support for collection(coll) and doc(doc)

packages/firestore/lite/src/api/database.ts, packages/firestore/src/core/component_provider.ts, packages/firestore/src/core/firestore_client.ts, packages/firestore/src/remote/datastore.ts, packages/firestore/test/integration/util/internal_helpers.ts, packages/firestore/test/unit/specs/spec_test_components.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
This is the first step in my two step plan to split up the ComponentProvider into one that provides only the components that are needed to reach from cache and into one that provides the RemoteStore and other components needed for connectivity.
=> Move Datastore to ComponentProvider

packages/firestore/src/platform/rn/base64.ts, packages/storage/karma.conf.js, packages/storage/package.json, packages/storage/src/implementation/error.ts, packages/storage/test/integration/integration.test.ts, packages/storage/test/unit/blob.test.ts, packages/storage/test/unit/reference.test.ts, packages/storage/test/unit/request.test.ts, packages/storage/test/unit/requests.test.ts, packages/storage/test/unit/service.test.ts, packages/storage/test/unit/string.test.ts, packages/storage/test/unit/task.test.ts, packages/storage/test/unit/testshared.ts, packages/storage/test/unit/xhrio.ts
This adds a barebones integration test file for Storage. Requires anonymous auth in the test project.
=> Add Storage Integration tests

packages-exp/app-exp/src/api.ts
Pretty sure this is causing the CI failure in https://github.com/firebase/firebase-js-sdk/pull/3382
=> Wait for all Promises in deleteApp()

packages/firestore/src/core/component_provider.ts, packages/firestore/src/core/firestore_client.ts, packages/firestore/src/core/sync_engine.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/memory_persistence.ts, packages/firestore/src/local/persistence.ts, packages/firestore/src/remote/datastore.ts, packages/firestore/src/util/assert.ts, packages/firestore/test/unit/local/local_store.test.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
This PR is part of my effort to create a cache-only entry point into Firestore (for `getDocFromLocalCache()`). My plan is to split up the component providers and extract one that only provides `Persistence`, `SharedClientState` and `LocalStore` . The "WIP end result" is here: https://github.com/firebase/firebase-js-sdk/pull/3425. This PR is a version of the first commit in that PR.
To avoid the combinatorial explosion of `ComponentProvider`s, this PR removes `MultiTabLocalStore` and instead makes all methods in `MultiTabLocalStore` tree-shakeable.
=> Remove MultiTabLocalStore

packages/firestore/src/core/component_provider.ts, packages/firestore/src/core/sync_engine.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/shared_client_state.ts, packages/firestore/src/local/shared_client_state_syncer.ts, packages/firestore/test/unit/local/persistence_test_helpers.ts, packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
This is similar to https://github.com/firebase/firebase-js-sdk/pull/3436 and removes the explicit MultiTabSyncEngine class. Instead, the methods are now tree-shakeable and will only be included with multi-tab IndexedDb persistence. 
Much smaller diff: https://github.com/firebase/firebase-js-sdk/pull/3442/files?w=1
This is the second commit in https://github.com/firebase/firebase-js-sdk/pull/3425. The next PR will then rewrite the component provider.
=> Remove MultiTabSyncEngine

packages/firestore/rollup.config.exp.js, packages/firestore/rollup.config.lite.js, packages/firestore/src/core/version.ts
This change is needed since the firebase-exp SDK is not meant to depend on @firebase/app
=> Use the SDK version from Firebase package.json

packages/firestore/index.console.ts
I stumbled across this today: When I removed `makeConstructorPrivate` (https://github.com/firebase/firebase-js-sdk/pull/3309), I didn't change the imports in the `index.console.ts` file. This file is not part of our build and only used in Google3, hence nothing blew up (yet).
=> Fix imports for Console builds

package.json, repo-scripts/changelog-generator/package.json
Upgrading `karma-coverage-istanbul-reporter` to `3.0.3` broke the coverage report. Revert to previous version.
=> Downgrade karma-coverage-istanbul-reporter to fix 0% coverage issue

packages/firestore/src/platform/node/grpc_connection.ts
The firestore-exp tests show this error when run under Node (not under ts-node):
CANCELLED - The operation was cancelled.
It happens after tests have finished running and is very timing dependent. It seems to have to side effects, so this PR silences this warning. See also https://grpc.github.io/grpc/core/md_doc_statuscodes.html ("The operation was cancelled, typically by the caller.")
=> Don't log Cancelled warning when stream is closed

scripts/emulator-testing/firestore-test-runner.ts
The tests with persistence run all tests twice already - once with and once without persistence. Thus, we can skip the setting test run.
=> Remove duplicate test run

.changeset/short-cars-scream.md, packages/analytics/index.ts
I approved https://github.com/firebase/firebase-js-sdk/pull/3165/files without realizing that it required a util bump because util code was changed.
I'm not sure if the bump should be minor instead because it added 3 public util methods.
Hope to cherrypick and re-release.
=> Util version bump

package.json
Change `build` to ensure app-exp builds before other packages, now that firestore needs a `d.ts` file from it.
The diff on `build:release` looks weird but I added rxfire (which was unintentionally missing) and removed `--ignore firebase-exp` because it wouldn't be included based on previous --scope params anyway. Tested to make sure this is true.
=> Fix up build scripts

packages/firestore/exp-types/index.d.ts, packages/firestore/exp/src/api/database.ts, packages/firestore/exp/test/shim.ts, packages/firestore/src/api/database.ts, packages/firestore/src/core/firestore_client.ts
Note in `exp/src/api/database.ts` and `shim.ts` the diff is based on some hacks I pushed to `wuandy/Bundles`.
=> Make loadBundle work with exp build

packages/performance-types/index.d.ts, packages/performance/src/resources/trace.test.ts, packages/performance/src/resources/trace.ts, packages/performance/src/utils/metric_utils.ts
Firebase Performance BE just allows the value of counter to be an integer. Currently the counter value could be set as a float and this would fail in processing.
=> Make sure the value that is set for a metric is an integer.

packages/firestore/exp/src/api/reference.ts, packages/firestore/src/api/database.ts, packages/firestore/src/core/firestore_client.ts
The next PR is going to have a larger diff so this one extracts the change out that I made for two methods. I moved this methods to `firestore_client.ts` to match the other methods of https://github.com/firebase/firebase-js-sdk/pull/3492.
In the follow up PR, I will then drop FirestoreClient from firestore-exp and will directly call the new methods.
=> Refactor some FirestoreClient methods

.changeset/thirty-flies-flow.md, packages/database-types/index.d.ts, packages/database/index.node.ts
The admin SDK wants to export the type of the instance of the `FirebaseDatabase` class in their namespace, but encountered an issue where Typescript thinks they are exporting the actual class from `@firebase/database-types` and compiles it to code that leads to runtime error:
```
var database_types_1 = require("@firebase/database-types");
```
Adding an interface that's implemented by `FirebaseDatabase` to work around the issue.
I tried to use `InstanceType<typeof FirebaseDatabase>` to get the type of the instance without creating a new type, but it doesn't work because the constructor is private 🤷 .
=> Add an interface Database

packages/firestore/src/protos/firestore_proto_api.d.ts, packages/firestore/src/protos/google/firestore/v1/query.proto
Also updated proto documentation to match updated documentation.
=> Add NOT_EQUAL and NOT_IN protos

packages/firestore/exp/src/api/database.ts
Found this in https://github.com/firebase/firebase-js-sdk/blob/8a8e60ada7f012b198c2c26089daff85c8270ee2/packages/firestore/src/core/firestore_client.ts#L375
=> Fix bug in terminate()

packages/firestore/exp/dependencies.json, packages/firestore/src/api/database.ts, packages/firestore/src/core/query.ts, packages/firestore/src/remote/serializer.ts
The SDK is meant to support different kind of Filters in the future, but for now only FieldFilters are supported. This is ensured via instanceof checks. These pull in the whole prototype and can be expensive in terms of code size. This PR mitigates some of that.
=> Remove FieldFilter instanceof checks

packages/firestore/exp/dependencies.json, packages/firestore/src/core/firestore_client.ts, packages/firestore/src/core/sync_engine.ts, packages/firestore/src/remote/remote_store.ts
This PR removes the hard dependency on Transaction/TransactionRunner from code that doesn't use it (for firestore-exp).
=> Remove TransactionRunner when not used

packages/firestore/src/protos/firestore_proto_api.d.ts, packages/firestore/src/protos/google/firestore/v1/query.proto
=> add IS_NOT_NULL and IS_NOT_NAN protos

.changeset/spicy-masks-sort.md, packages/analytics/index.ts, packages/analytics/src/errors.ts, packages/analytics/src/factory.ts
added browser extension check to analytics module; prevent initialization if not in a browser context.
=> Browser Extension Check for Analytics Module

.changeset/quick-drinks-cheat.md, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/simple_db.ts, packages/firestore/test/unit/local/encoded_resource_path.test.ts, packages/firestore/test/unit/local/indexeddb_persistence.test.ts, packages/firestore/test/unit/local/simple_db.test.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
This PR addresses an IndexedDb error that may occur when a transaction is first opened. The error `The database connection is closing` can be reproduced locally by invoking SimpleDb.close() and then calling `db.transaction` and this PR fixes at least this case by extending the IndexedDB retry code to include the code around `db.transaction` and by closing and re-opening the IndexedDB instance.
Fixes https://github.com/firebase/firebase-js-sdk/issues/3495
=> Re-open IndexedDB if closed

.changeset/spicy-masks-sort.md
`@firebase/firebase` --> `firebase`
=> Wrong package name in changeset file

.changeset/tidy-elephants-beam.md, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/util/async_queue.ts
I wanted to add logging for the visibility handler in AsyncQueue, which is good because it made me realize that I attached the visibility handler to the wrong object.
=> Fix bug in AsyncQueue visibility handler

.changeset/silly-moles-rush.md, packages/util/src/environment.ts
change from `'indexedDB' in window` to `'indexedDB' in self`
=> Extended Usage of `isIndexedDBAvailable` to Service Worker

.changeset/config.json, .changeset/shy-bears-heal.md, lerna.json, package.json, repo-scripts/size-analysis/.eslintrc.js, repo-scripts/size-analysis/README.md, repo-scripts/size-analysis/analysis-helper.ts, repo-scripts/size-analysis/analysis.ts, repo-scripts/size-analysis/package.json, repo-scripts/size-analysis/rollup.config.js, repo-scripts/size-analysis/test/size-analysis.test.ts, repo-scripts/size-analysis/test/test-inputs/assortedImports.ts, repo-scripts/size-analysis/test/test-inputs/bar.ts, repo-scripts/size-analysis/test/test-inputs/far.ts, repo-scripts/size-analysis/test/test-inputs/index.ts, repo-scripts/size-analysis/test/test-inputs/subsetExports.ts, repo-scripts/size-analysis/test/test-inputs/tar.ts, repo-scripts/size-analysis/test/test-inputs/tsconfig.json, repo-scripts/size-analysis/test/utils.ts, repo-scripts/size-analysis/tsconfig.json
=> Size Analysis Tool - Phase 1

packages/firestore/test/unit/local/lru_garbage_collector.test.ts
Something I noticed in a bunch of CI runs.
```
@firebase/firestore:     at http://localhost:8090/base/test/unit/bootstrap.js?26216e70590197792d0407ed7a3d00fec98dcefc:42468:89
@firebase/firestore:     at http://localhost:8090/base/test/unit/bootstrap.js?26216e70590197792d0407ed7a3d00fec98dcefc:36091:67776'
@firebase/firestore: ERROR: '[2020-08-10T21:44:55.724Z]  @firebase/firestore:', 'Firestore (7.17.2): INTERNAL UNHANDLED ERROR: ', 'TypeError: Cannot read property 'shutdown' of undefined
@firebase/firestore:     at http://localhost:8090/base/test/unit/bootstrap.js?26216e70590197792d0407ed7a3d00fec98dcefc:42471:74
@firebase/firestore:     at step (http://localhost:8090/base/test/unit/bootstrap.js?26216e70590197792d0407ed7a3d00fec98dcefc:29318:27)
@firebase/firestore:     at Object.next …
```
=> Address 'calling shutdown of undefined' warning

scripts/emulator-testing/emulators/emulator.ts
It seems we run out of disk space on GHA when downloading emulator jars for Firestore, Database and Testing SDK. This PR solves the problem by deleting the jar after the test.
=> clean up emulator after test

scripts/emulator-testing/firestore-test-runner.ts
This shuts down the tests when the parent process is killed.
=> Abort tests when test runner script is aborted

packages/rules-unit-testing/package.json
We did a release in parallel when `rules-unit-testing` was added to the repo, so some deps are outdated. The PR fixes it.
=> Update outdated deps

packages/firestore/exp/dependencies.json, packages/firestore/exp/src/api/components.ts, packages/firestore/src/core/firestore_client.ts, packages/firestore/src/core/sync_engine.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/remote/remote_store.ts, packages/firestore/test/unit/local/local_store.test.ts
This follows the precedent set in https://github.com/firebase/firebase-js-sdk/pull/3561 and tree-shakes all of LocalStore, making it possible to separate write and watch logic (once all PRs are merged). This diff is much easier to review in IntelliJ, as it does a better job detecting whitespace-only changes.
=> Tree-shake LocalStore's implementation

.changeset/silver-trainers-rhyme.md, packages/firestore/src/platform/browser/random_bytes.ts
On some IE11 the randomBytes helper crashes with "TypeError: getRandomValues is not defined". The reason is not clear, maybe something pollutes self.crypto with a bad polyfill. Nevertheless it makes sense to fall back to Math.random if crypto.getRandomValues is not available.
=> Add check if crypto.getRandomValues is available

packages/firebase/index.d.ts
Making link tweaks we discussed offline.
Thanks!
=> Fixing some links and link text.

packages/firestore/src/core/transaction.ts, packages/firestore/src/local/memory_persistence.ts, packages/firestore/src/model/document_key.ts
Since JavaScript Sets use reference equality for objects, we should not store DocumentKeys in Sets. Rather, we can use the string representation.
Fixes b/157233697
=> Replace usage of Set<DocumentKey> with Set<path>

packages/firestore/package.json
Fix `build:release` to match new `build` minus exp and lite.
=> Fix firestore build:release script

packages/analytics/index.test.ts
Cannot reproduce flaky analytics test but making a change that will hopefully make the test more stable.
Test relies on some tricky timing to test a couple of calls when FID promise has resolved but initialization promise hasn't. It was already causing some problems on IE and may be causing occasional flaky failures. Switch to just making all `expect` calls after initialization promise has resolved.
=> Try to fix flaky analytics test

packages/analytics/package.json, packages/firestore/package.json, packages/functions/package.json, packages/installations/package.json, packages/messaging/package.json, packages/performance/package.json, packages/remote-config/package.json, packages/rxfire/package.json, packages/storage/package.json, packages/template/package.json
`@firebase/app` is peerDependencies for many packages, but peerDependencies are ignored when lerna analyze dependencies. Adding it to devDependencies to solve the issue
=> take @firebase/app as devDependencies

packages/firestore/exp-types/index.d.ts, packages/firestore/exp/dependencies.json, packages/firestore/exp/index.ts, packages/firestore/exp/src/api/snapshot.ts, packages/firestore/exp/test/shim.ts, packages/firestore/lite-types/index.d.ts, packages/firestore/lite/dependencies.json, packages/firestore/lite/index.ts, packages/firestore/lite/src/api/bytes.ts, packages/firestore/lite/src/api/snapshot.ts, packages/firestore/lite/test/integration.test.ts, packages/firestore/src/api/blob.ts, packages/firestore/src/api/database.ts, packages/firestore/src/api/user_data_reader.ts, packages/firestore/src/api/user_data_writer.ts, packages/firestore/src/remote/serializer.ts, packages/firestore/test/util/helpers.ts
As part of go/firestore-next-amendment-amendment, we decided to rename Blob to Bytes to avoid name clashes with the JavaScript Blob type.
Couple notes:
- I created a new type instead of renaming the export since the error messages would have been incorrect. 
- I removed the now incorrect error messages in the new type.
- I believe all of our platforms now support byte conversion (since we have the Polyfill for ReactNative, which was required to make stream resumption work). Hence, I did not port the validation.
- The old Blob type now extends Bytes to make it easier for the serializer to use common logic.
=> Rename Blob to Bytes

.changeset/cold-impalas-drop.md, packages/firestore/exp/src/api/components.ts, packages/firestore/src/remote/remote_store.ts, packages/firestore/test/unit/specs/offline_spec.test.ts
The user change handling on Web resets the OnlineStatus to unknown even if we are offline. This breaks offline behavior for empty snapshots from cache, as we will stop raising empty snapshots.
This fixes a regression in the Web client. The Android and iOS client should have the correct behavior (see Android: https://github.com/firebase/firebase-android-sdk/blob/751684d3073329adef4cbca8865efa22c953fa5d/firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteStore.java#L319)
=> Don't switch network status to UNKNOWN during user change

.changeset/tall-mugs-shop.md, packages/messaging/src/controllers/sw-controller.test.ts, packages/messaging/src/controllers/sw-controller.ts
FM should not open non-origin links.  
for more context: go/fcm-security-issue
=> Stop redirecting to non-origin sites

packages/firebase/externs/firebase-firestore-externs.js
Adjust the Firestore Externs to use properly use `@typedef` instead of `@type`
---
The proper way to define what is effectively a "type alias" in Closure is to use `@typedef`.  On the other hand, the `@type` annotation would typically be used to define the type for a current object or a property on a class/interface.
I've confirmed in a very elaborate closure environment that this properly compiles ;)
tag @hsubox76
=> Firestore Externs: @type -> @typedef

packages/firebase/externs/firebase-client-auth-externs.js, packages/firebase/externs/firebase-firestore-externs.js
Adds an `@override` annotation on the RecaptchaVerifier.Verify in AuthClient externs
--
This is needed because this interface implements the `firebase.auth.ApplicationVerifier` type.
This resolves a Closure compiler warning message
tag @hsubox76
=> Add '@override' annotation to RecaptchaVerifier.Verify method in AuthClient externs.

packages/firebase/rollup.config.js
Externals should include tslib and use `startsWith` pattern.
=> Fix externals for packages/firebase builds

.github/workflows/health-metrics-test.yml, scripts/size_report/report_binary_size.ts
1. run the regular size report and modular export size report in parallel
2. fix an issue where the regular size report exit before the report is created
=> run size reports in parallel in CI

.changeset/config.json
Was causing errors in changeset validation when running release.
=> Add installations-exp packages to changeset ignore

package.json
`app-compat` build fails in this flow, blocking release.
=> Exclude -compat from build:release

.changeset/polite-readers-wait.md, packages/database/index.node.ts, packages/database/src/api/Database.ts, packages/database/src/core/PersistentConnection.ts, packages/database/src/core/RepoInfo.ts, packages/database/src/core/RepoManager.ts, packages/database/src/core/util/libs/parser.ts, packages/database/src/realtime/WebSocketConnection.ts, packages/rules-unit-testing/test/database.test.ts
The `NODE_ADMIN` global means that the RTDB Admin and Client SDKs cannot coexist, whichever is initialized first will control the behavior.
This is a problem for testing, where clients want to use the Admin SDK to do privileged actions but then test the behavior of the Client SDK with low privileges.
N/A
=> Remove usage of the NODE_ADMIN global in RTDB

repo-scripts/size-analysis/test/size-analysis.test.ts
Test is consistently exceeding timeout of 60s. Extending `before` timeout to 120s.
=> Increase timeout for flaky test

packages/firestore/exp-types/index.d.ts, packages/firestore/exp/src/api/database.ts
This adds "experimentalForceOwningTab" to the experimental SDK. Exposed as "forceOwnership" - comments welcome.
=> Add forceOwnership to firestore-exp

.changeset/tame-donuts-relate.md, packages/firestore/exp/src/api/transaction.ts, packages/firestore/lite/src/api/field_value.ts, packages/firestore/src/api/database.ts, packages/firestore/test/integration/api/validation.test.ts
=> Call toFirestore() only once

packages/firestore/exp/src/api/transaction.ts, packages/firestore/lite/src/api/field_value.ts, packages/firestore/src/core/query.ts, packages/firestore/test/integration/api/query.test.ts, packages/firestore/test/integration/util/helpers.ts, packages/firestore/test/unit/remote/serializer.helper.ts
Porting over from [Android](https://github.com/firebase/firebase-android-sdk/pull/1947).
Making integration tests run against prod since protos are now public. Tests are currently failing b/c the client proxy has not been fully released yet, but they should be passing by EOW.
=> Fix NotInFilter matches

.changeset/shiny-forks-pull.md, packages/firebase/index.d.ts, packages/firestore-types/index.d.ts, packages/firestore/exp-types/index.d.ts, packages/firestore/lite-types/index.d.ts, packages/firestore/src/api/database.ts, packages/firestore/src/core/query.ts, packages/firestore/test/integration/api/database.test.ts, packages/firestore/test/integration/api/query.test.ts, packages/firestore/test/integration/api/validation.test.ts, packages/firestore/test/integration/util/helpers.ts, packages/firestore/test/unit/core/query.test.ts
In addition to making the operators public, this PR also adds NOT_IN to the `isInequality()` check and updates some validation error messages.
=> Make != and NOT_IN publicly available

scripts/release/cli.ts
This allows continuing the release from a checkpoint in our internal script, even after changeset has made its changes.
=> Allow ignoring unstaged changes during release

packages/firestore/exp/src/api/reference.ts, packages/firestore/exp/src/api/snapshot.ts, packages/firestore/lite/src/api/reference.ts
The converter property is currently not part of our public API, and as such it should be prefixed with an underscore
This is firestore-exp/lite only.
=> Hide converter from Public API

packages-exp/performance-exp/index.ts, packages-exp/performance-exp/package.json, packages-exp/performance-exp/rollup.config.js, packages-exp/performance-exp/src/controllers/perf.test.ts, packages-exp/performance-exp/src/controllers/perf.ts, packages-exp/performance-exp/src/index.ts, packages-exp/performance-exp/src/resources/trace.ts, packages-exp/performance-exp/src/services/iid_service.test.ts, packages-exp/performance-exp/src/services/initialization_service.test.ts, packages-exp/performance-exp/src/services/perf_logger.test.ts, packages-exp/performance-exp/src/services/remote_config_service.test.ts, packages-exp/performance-exp/src/services/settings_service.ts, packages-exp/performance-types-exp/index.d.ts
Also moving the index.ts under src/
=> Updating the dependencies on Firebase products to use the exp packages

packages-exp/functions-exp/package.json, packages-exp/functions-exp/src/config.ts, packages-exp/functions-exp/src/index.node.ts, packages-exp/functions-exp/src/index.ts, packages-exp/functions-exp/src/service.ts, packages-exp/functions-exp/test/utils.ts, packages/functions/index.node.ts, packages/functions/index.ts, packages/functions/package.json, packages/functions/src/api/service.ts, packages/functions/src/config.ts, packages/functions/test/utils.ts, yarn.lock
The `isomorphic-fetch` dependency has not been updated in years and depends on an older version of `node-fetch` which has now been discovered to have security issues. Removing isomorphic-fetch and consuming node-fetch directly.
I tried another approach that involved passing the node-fetch implementation directly into the functions service, but it involved passing through many layers, and since it is passed into the Service constructor, the `createTestService` test util function needs to detect the environment and pass the correct fetch implementation as well which seems like a lot of places. This seems like the simplest approach and only touches the `index.node.ts` file.
Fixes https://github.com/firebase/firebase-js-sdk/issues/3768
=> Remove isomorphic-fetch dependency

.changeset/honest-doors-poke.md, packages/firebase/rollup.config.js
Fixes https://github.com/firebase/firebase-js-sdk/issues/414
=> Fixes an unicode encoding issue in firebase-auth.js

.changeset/moody-jobs-deliver.md, packages/firestore/src/util/types.ts
It should not matter whether we check for "value === 0.0" or "value === -0.0" since JS treats them equal. This change should silence a lint error that is blocking one of our customers.
Fixes https://github.com/firebase/firebase-js-sdk/issues/3814
=> Address negative zero lint validation

.changeset/mean-queens-roll.md, packages/firestore/src/core/sync_engine.ts, packages/firestore/test/unit/specs/spec_builder.ts, packages/firestore/test/unit/specs/spec_test_runner.ts, packages/firestore/test/unit/specs/write_spec.test.ts
A user noticed that `waitForPendingWrites` doesn't work in secondary tabs. This is a one line fix + spec tests.
Fixes https://github.com/firebase/firebase-js-sdk/issues/3816
=> Support waitForPendingWrites in secondary tabs

packages/firebase/externs/firebase-app-internal-externs.js
FirebaseComponent doesn't seem to be defined and for the purposes of app-internal-externs, it probably doesn't need to be. Also got an error on Blaze build for not naming the param. This change mirrors a change I already made in the third_party repo. (internal link: cl/332960756)
=> Fix app externs type

packages/firestore/test/unit/generate_spec_json.js
This drops the old Platform specification in favor of the default (which is Node)
=> Fix generate_spec_json script

packages/firestore/test/unit/specs/limbo_spec.test.ts
Limbo resolution throttling is now implemented in iOS, and, therefore, the spec tests for that feature should be enabled: https://github.com/firebase/firebase-ios-sdk/pull/5310
=> Remove 'no-ios' tags from spec tests for limbo resolution throttling

.changeset/poor-eagles-think.md, packages-exp/functions-exp/src/api.ts, packages-exp/functions-exp/src/config.ts, packages-exp/functions-exp/src/service.test.ts, packages-exp/functions-exp/src/service.ts, packages-exp/functions-types-exp/index.d.ts, packages/functions/index.ts, packages/functions/src/api/service.ts, packages/functions/src/config.ts, packages/functions/test/service.test.ts, packages/functions/test/utils.ts
[Googlers: see API review here](https://docs.google.com/document/d/1cSIcGCW2QR1OLHX4RDCVNhpBUolnG6tfNpJBR2pn1aM/edit#)
* Added new unit tests
* API reviewed
=> Add custom domain support to callable functions

packages-exp/auth-exp/src/platform_browser/popup_redirect.test.ts, packages-exp/auth-exp/src/platform_browser/popup_redirect.ts
=> Handle null auth events from the iframe

packages-exp/auth-exp/src/model/popup_redirect.ts, packages-exp/auth-exp/src/platform_browser/iframe/gapi.iframes.ts, packages-exp/auth-exp/src/platform_browser/popup_redirect.test.ts, packages-exp/auth-exp/src/platform_browser/popup_redirect.ts, packages-exp/auth-exp/src/platform_browser/strategies/popup.test.ts, packages-exp/auth-exp/src/platform_browser/strategies/popup.ts, packages-exp/auth-exp/test/helpers/mock_popup_redirect_resolver.ts
=> Add web storage support check to popup actions

packages/firestore/exp/dependencies.json, packages/firestore/lite/src/api/transaction.ts, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/indexeddb_remote_document_cache.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/memory_persistence.ts, packages/firestore/src/local/memory_remote_document_cache.ts, packages/firestore/test/unit/local/remote_document_cache.test.ts, packages/firestore/test/unit/local/test_remote_document_cache.ts
This PR removes a static inheritance that WebPack cannot tree-shake. 
Before, our RemoteDocumentCaches would look like this:
```
class XYZRemoteDocumentCache {
static class XYZRemoteDocumentChangeBuffer extends RemoteDocumentChangeBuffer {...}
}
```
This patterns breaks code optimization in Webpack (as per @Feiyang1's research), but it does allow us to access "private" members within the enclosing class while also extending from another class. To address the Webpack issue while keeping some of the encapsulation, I:
- Extracted the XYZRemoteDocumentChangeBuffers into top-level classes.
- Changed XYZRemoteDocumentCaches to XYZRemoteDocumentCacheImpls
- Made XYZRemoteDocumentCacheImpls methods public, so they can be used by the newly extracted types
The rest of the repo still refers to the …
=> Remove cyclic references in RemoteDocumentCache

.changeset/fifty-snakes-shout.md, packages-exp/performance-exp/src/services/perf_logger.test.ts, packages-exp/performance-exp/src/services/perf_logger.ts, packages/performance/src/services/perf_logger.test.ts, packages/performance/src/services/perf_logger.ts
Developer reported that `custom trace` right after initializing perf object was not able to be recorded. That is because initialization didn't finish, thus was not able to flip the bit of `SettingsService.loggingEnabled` from false to true. Therefore custom trace was discarded.
Check `SettingsService.loggingEnabled` after initialization finishes, thus avoid dropping events before reading RemoteConfig value.
Internal tracking bug: b/169126072
=> Fix custom trace event dispatch before initialization for Performance Monitoring

.changeset/dirty-rings-cry.md, packages-exp/functions-exp/src/index.ts, packages/functions/index.ts
Fix a bug caused by PR https://github.com/firebase/firebase-js-sdk/pull/3782 to replace isomorphic-fetch dependency in functions. Bug occurs in Chrome extensions and possibly other environments. When passing `fetch` function as an argument it loses `window` context. Binding `self` so that it will work in service workers as well.
See https://stackoverflow.com/questions/44720448/fetch-typeerror-failed-to-execute-fetch-on-window-illegal-invocation for a similar issue.
Fixes https://github.com/firebase/firebase-js-sdk/issues/3849
=> Functions: Bind passed fetch function

packages-exp/auth-exp/src/core/auth/auth_impl.test.ts, packages-exp/auth-exp/src/core/auth/auth_impl.ts, packages-exp/auth-exp/src/core/user/user_impl.ts
* State change listeners before initialization completes now fire after initialization is done
* Deserializing user objects now does not care if the a value is null or undefined
b/169870894  
b/169870246
=> Fix a couple of parity issues for auth-exp

.changeset/modern-parents-worry.md, packages-exp/performance-exp/src/resources/trace.test.ts, packages-exp/performance-exp/src/resources/trace.ts, packages-exp/performance-exp/src/utils/errors.ts, packages/performance/src/resources/trace.test.ts, packages/performance/src/resources/trace.ts, packages/performance/src/utils/errors.ts
It is common for developer to provide 0 or invalid value for `startTime` and `duration` when calling `record(startTime, duration, options)` to create custom trace. This doesn't create error on the client side, but will be filtered silently during backend processing. Add basic validation to check developer input of both variables on the client side.
=> Throw exception when Performance custom trace API is provided with non-positive startTime or duration

.changeset/chilled-ways-promise.md, packages/rules-unit-testing/src/api/index.ts, packages/rules-unit-testing/test/database.test.ts
This is a non-breaking change to improve the typing for `options.auth` in `initializeTestApp`.  Note that this removes the `uid` property of the token which should never have been there in the first place (`sub` is the canonical `uid` field).
Related issues: 
- https://github.com/firebase/quickstart-testing/issues/2
- https://github.com/firebase/firebase-tools/issues/2405
- http://b/153398707 (internal)
Improved existing unit tests
N/A
=> Improve typing for options.auth

.changeset/config.json
Ran into the following error with #3898. When I removed `auth-compat-exp`, it complained about adding back `auth-compat`. I then added `auth-compat` back, which resulted the changeset working.
```
🦋  error { ValidationError: Some errors occurred when validating the changesets config:
🦋  error The package "@firebase/auth-compat-exp" is specified in the `ignore` option but it is not found in the project. You may have misspelled the package name.
🦋  error     at parse (/Users/chenbrian/dev/firebase-js-sdk/node_modules/@changesets/config/dist/config.cjs.dev.js:173:11)
🦋  error     at Object.read (/Users/chenbrian/dev/firebase-js-sdk/node_modules/@changesets/config/dist/config.cjs.dev.js:64:10)
🦋  error   name: 'ValidationError',
🦋  error   _error:
🦋  error    Error
🦋  error        at new …
```
=> Modify auth-exp related packages in changeset ignore

.changeset/silent-brooms-search.md, packages/rules-unit-testing/src/api/index.ts, packages/rules-unit-testing/test/database.test.ts
See https://github.com/firebase/firebase-js-sdk/pull/3876#issuecomment-706241099
* New unit tests
* Reverting a bug
=> Fix custom claims

.changeset/long-hornets-scream.md, packages/firestore/src/util/async_queue.ts
We currently do follow the global order of AsyncQueue operations when we insert items into the retryable queue. This seems to allow operations that inserted into the retryable queue to skip ahead of items that are inserted into the regular queue. This PR ties the insertion of new items to the retryable queue to the order in which all items are enqueue.
I still am not able to reproduce the original failure in a unit test (tried various delays, various order of operations, scheduling operations while other operations are running), but this code change addresses the consistent Integration tests failures in a follow-up PR.
=> Fix out-of-order execution for enqueueRetryable

packages-exp/auth-compat-exp/src/auth.ts, packages-exp/auth-exp/src/api/index.test.ts, packages-exp/auth-exp/src/core/auth/auth_impl.test.ts, packages-exp/auth-exp/src/core/auth/auth_impl.ts, packages-exp/auth-exp/src/core/util/emulator.test.ts, packages-exp/auth-exp/src/core/util/emulator.ts, packages-exp/auth-exp/src/model/auth.ts, packages-exp/auth-types-exp/index.d.ts
=> Make the emulator API match for auth-exp

.changeset/ninety-kings-agree.md, packages/rules-unit-testing/src/api/index.ts, packages/rules-unit-testing/test/database.test.ts
Fixes #3920
Previous to this change we would delete the `uid` property from the object before copying it, which is destructive if the user is re-using the object.
* Added unit test.
* None
=> Preserve user input in initializeTestApp

scripts/release/prerelease.ts
prevent accidentally releasing prereleases to firebase@latest
=> forbid prereleasing to npm tag @latest

.changeset/early-elephants-learn.md, packages/auth/src/auth.js
=> Add a sanity check for useEmulator URL.

.changeset/silver-books-reply.md, packages-exp/functions-exp/src/api.ts, packages-exp/functions-exp/src/service.test.ts, packages-exp/functions-exp/src/service.ts, packages-exp/functions-exp/test/utils.ts, packages/firebase/index.d.ts, packages/functions-types/index.d.ts, packages/functions/src/api/service.ts, packages/functions/test/service.test.ts
This PR is part of a group: #3904 #3906 #3909
Android implementation:
https://github.com/firebase/firebase-android-sdk/pull/1802
This follows Proposal 2 at:
http://go/firebase-emulator-connection-api
* Added new unit tests
* Approved, see above
=> Implement useEmulator for Functions

packages/firestore/exp/src/api/components.ts
This is meant to make https://github.com/firebase/firebase-js-sdk/pull/390 smaller.
These function were not `async` before, but as of https://github.com/firebase/firebase-js-sdk/pull/3701 they can be. This is because now every function is executed on the `AsyncQueue` and we call `verifyNotTerminated()` before, which throws a JavaScript exception before we enqueue the new `async` functions.
=> Using async functions in Component initialization

common/api-review/auth-exp.api.md, packages-exp/auth-exp/src/core/auth/auth_impl.test.ts, packages-exp/auth-exp/src/core/auth/auth_impl.ts, packages-exp/auth-exp/src/core/auth/firebase_internal.test.ts, packages-exp/auth-exp/src/core/strategies/anonymous.test.ts, packages-exp/auth-exp/src/core/strategies/anonymous.ts, packages-exp/auth-exp/src/core/strategies/credential.ts, packages-exp/auth-exp/src/core/strategies/custom_token.ts, packages-exp/auth-exp/src/core/strategies/email_and_password.ts, packages-exp/auth-exp/src/core/user/account_info.test.ts, packages-exp/auth-exp/src/core/user/invalidation.test.ts, packages-exp/auth-exp/src/core/user/link_unlink.test.ts, packages-exp/auth-exp/src/core/user/token_manager.test.ts, packages-exp/auth-exp/src/core/user/token_manager.ts, packages-exp/auth-exp/src/core/user/user_credential_impl.test.ts, packages-exp/auth-exp/src/core/user/user_impl.test.ts, packages-exp/auth-exp/src/core/user/user_impl.ts, packages-exp/auth-exp/src/mfa/mfa_resolver.ts, packages-exp/auth-exp/src/model/auth.ts, packages-exp/auth-exp/src/model/user.ts, packages-exp/auth-exp/src/platform_browser/strategies/redirect.test.ts
This PR creates a differentiation between the public `updateCurrentUser()` and the internal `_updateCurrentUser()`. The latter does not make a copy because it is called by the SDK itself when the SDK signs someone in or updates something.
b/170886559,
b/170854629
=> Copy the auth user on updateCurrentUser(), also assert the app name matches

.changeset/strange-rabbits-wait.md, packages/firebase/index.d.ts, packages/firestore-types/index.d.ts, packages/firestore/exp/src/api/snapshot.ts, packages/firestore/lite/src/api/snapshot.ts, packages/firestore/src/api/database.ts, packages/firestore/src/api/user_data_writer.ts, packages/firestore/test/integration/api/fields.test.ts, packages/firestore/test/unit/remote/serializer.helper.ts, packages/firestore/test/util/helpers.ts
Fixes #3879.
Merging with next breaking change window.
Will add changeset once the `.changesset/config.json` is updated.
=> Remove `timestampsInSnapshots` from FirestoreSettings

lerna.json
Remove deprecated field. Anyway, currenly project uses learna v3.22.1, not 3.10.x
=> `lerna` field is deprecated since v3

.changeset/bright-ducks-jump.md, packages/database-types/index.d.ts, packages/database/src/api/Database.ts, packages/database/src/api/Reference.ts, packages/database/src/core/Repo.ts, packages/database/src/core/RepoManager.ts, packages/database/test/database.test.ts, packages/firebase/index.d.ts
This PR is part of a group: #3904 #3906 #3909
In order for `useEmulator()` to work the `Repo` has to be changed or replaced.  In Android this was easier because the database instance lazily creates the `Repo` (via `ensureRepo()`) but in JS the `Repo` creates the database instance.
In this change I move the `repo_` and `root_` fields to have getters/setters so that we can track their usage and allow `useEmulator()` to replace the `Repo` only if no database operations have been performed yet.
Android implementation:
https://github.com/firebase/firebase-android-sdk/pull/1802
This follows Proposal 2 at:
http://go/firebase-emulator-connection-api
* Added new unit tests
* Approved, see above
=> Implement useEmulator for Database

packages/firebase/index.d.ts, packages/storage-types/index.d.ts, packages/storage/src/implementation/error.ts, packages/storage/src/implementation/request.ts, packages/storage/src/implementation/requests.ts
Separated out from storage modularization PR: https://github.com/firebase/firebase-js-sdk/pull/3499
Should fix https://github.com/firebase/firebase-js-sdk/issues/1515
=> Fix storage-types

.changeset/tame-knives-change.md, packages/database-types/index.d.ts, packages/firebase/index.d.ts
`push()` should return a `ThenableReference`
=> Fix a typing error in database-types

packages-exp/firebase-exp/compat/index.ts, packages/firebase/README.md, packages/firebase/src/index.ts, packages/rxfire/README.md, packages/rxfire/docs/storage.md
For https://github.com/firebase/firebase-js-sdk/pull/3932
=> update import syntax in readmes and messages

.changeset/tiny-hounds-rest.md
Since storage is not GA, we should only bump minor.
=> lower storage bump to minor

yarn.lock
Update yarn.lock. Release adds a minor bump to `database` and `database-types` which is beyond what firebase-admin's dependency specifies, causing it to bring in older versions of `@firebase/database` and its firebase deps.
Details: firebase-admin depends on database ^0.6.10 and this release bumps database to 0.7.0. Minor bumps aren't allowed by ^ if the major version is 0.
=> Update yarn.lock for release

common/api-review/functions-exp.api.md, packages-exp/auth-exp/src/core/auth/firebase_internal.ts, packages-exp/auth-exp/src/core/auth/register.ts
- Implement the interface from `@firebase/auth-interop-types`
- rename the internal component to `auth-internal`, so consumers don't need to change their existing code for exp. (It's also easier for the typings).
FYI, @schmidt-sebastian
=> Make AuthInternal implement the interface

scripts/emulator-testing/emulators/database-emulator.ts, scripts/emulator-testing/emulators/emulator.ts, scripts/emulator-testing/emulators/firestore-emulator.ts
When running unit tests locally the emulator is downloaded every time.  This is 30-60MB depending on the service and on my slow home WiFi this makes test startup much slower than it needs to be.
Here are the database unit tests, run twice.
First run:
```
$ yarn test:emulator
yarn run v1.22.4
$ ts-node --compiler-options='{"module":"commonjs"}' ../../scripts/emulator-testing/database-test-runner.ts
Created temporary directory at [/var/folders/xl/6lkrzp7j07581mw8_4dlt3b000643s/T/tmp-88560-ch7akdXEY5Iy].
Downloading emulator from [https://storage.googleapis.com/firebase-preview-drop/emulator/firebase-database-emulator-v4.4.1.jar] ...
Saved emulator binary file to [/var/folders/xl/6lkrzp7j07581mw8_4dlt3b000643s/T/tmp-88560-ch7akdXEY5Iy/firebase-database-emulator-v4.4.1.jar].
Changed emulator …
```
=> Cache emulator between runs

CHANGELOG.md
I noticed that the developer experience (especially for people not already familiar with lerna or how this repo is structured) to be able to see at least a hint about where the changelogs are.
Personally, when I see a `CHANGELOG.md` file (as is convention) that's the first place I look, and I'll bet I'm not alone on that.
Please feel completely free to change what I wrote to whatever you think is best.  The main idea here is just to have _something_ there that will quickly point people in the right direction.
=> adds a root changelog

.changeset/giant-pants-relax.md, .github/workflows/check-changeset.yml, scripts/check_changeset.ts
Initially set BLOCKING_FAILURE var to false, and also log the value to help diagnose any future issues.
=> Fix to avoid false failures on changeset checker

.changeset/my-random-name.md
Changeset for https://github.com/firebase/firebase-js-sdk/pull/3974
=> Add changeset for Firestore

.github/workflows/test-all.yml, .github/workflows/test-changed-auth.yml, .github/workflows/test-changed-fcm-integration.yml, .github/workflows/test-changed-firestore-integration.yml, .github/workflows/test-changed-firestore.yml, .github/workflows/test-changed-misc.yml, .github/workflows/test-changed.yml, .github/workflows/test-firebase-integration.yml
auth-exp tests were causing memory to run out in CI (but not locally) as part of `test-changed.yml`. It's possible it could happen in the future to other large test suites like Firestore so might as well consistently bump for all test workflows.
=> Bump Node memory limit for all test CI

packages/firestore/package.json, scripts/ci-test/build_changed.ts
Add app-compat to app-exp prebuild hack
=> Add app-compat hack

.github/workflows/test-changed-firestore-integration.yml, .github/workflows/test-changed-firestore.yml, packages/firestore/exp/src/api/database.ts, packages/firestore/exp/test/shim.ts, packages/firestore/index.console.ts, packages/firestore/index.memory.ts, packages/firestore/index.node.memory.ts, packages/firestore/index.node.ts, packages/firestore/index.rn.memory.ts, packages/firestore/index.rn.ts, packages/firestore/index.ts, packages/firestore/lite/src/api/components.ts, packages/firestore/lite/src/api/database.ts, packages/firestore/lite/src/api/reference.ts, packages/firestore/package.json, packages/firestore/src/api/database.ts, packages/firestore/src/api/user_data_reader.ts, packages/firestore/src/core/database_info.ts, packages/firestore/test/integration/api/database.test.ts, packages/firestore/test/integration/api/type.test.ts, packages/firestore/test/integration/api/validation.test.ts, packages/firestore/test/integration/api_internal/database.test.ts, packages/firestore/test/integration/util/firebase_export.ts, packages/firestore/test/integration/util/internal_helpers.ts, packages/firestore/test/unit/api/database.test.ts, packages/firestore/test/util/api_helpers.ts, scripts/ci-test/build_changed.ts
This PR replaces the Firestore class from the main SDK with a Compat class that delegates most simple calls to firestore-exp (e.g. `enableNetwork`, `waitForPendingWrites`) and drops the no longer needed `FirestoreCompat` interface. The OR doesn't yet replace WriteBatch, `runTransaction`, DocumentReference or CollectionReference and instead uses the legacy implementations. 
Hidden in these changes is also unwrapping code that recognizes the [FieldValue Compat](https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore/src/compat/field_value.ts#L29) types and unwraps them so that they are recognized by the UserDataConverter. 
There are also a couple of test updates in this PR. Most are due to the unfortunate fact that we are losing test coverage for firestore-exp's …
=> Compat Layer for Firestore

packages-exp/auth-exp/src/platform_browser/persistence/indexed_db.test.ts, packages-exp/auth-exp/src/platform_browser/persistence/indexed_db.ts
Similar to https://github.com/firebase/firebase-js-sdk/blob/a10c18f8996fc35942779f5fea5690ae5d102bb0/packages/firestore/src/local/simple_db.ts
=> Add retry logic around logic IndexedDB connections.

packages/firestore/lite/src/api/field_path.ts, packages/firestore/src/api/database.ts, packages/firestore/src/api/field_path.ts, packages/firestore/src/api/user_data_reader.ts, packages/firestore/test/integration/util/firebase_export.ts, packages/firestore/test/util/helpers.ts
This PR removes the FieldPath class in the legacy class in favor of a Compat class that delegates to firestore-exp. It changes all callsites to accept either the Compat class or the firestore-exp FieldPath.
=> Compat class for FieldPath

.changeset/gentle-gifts-sort.md, packages/auth/src/storage/indexeddb.js, packages/auth/test/storage/indexeddb_test.js
There appears to be an issue with webkit where it periodically closes the connections such as when the tab is backgrounded (https://bugs.webkit.org/show_bug.cgi?id=197050).  We can't repro, but Firestore did something similar and have stopped getting error reports.
Closes #1926
=> [auth] Retry IndexedDB errors a fixed number of times

packages-exp/remote-config-compat/package.json
remote-config-compat was just merged and some external dep versions got out of sync with the rest of the repo.
=> Update remote-config-compat deps

.changeset/curvy-planets-sneeze.md, packages/firestore/src/api/database.ts, packages/firestore/test/integration/api/query.test.ts
8.0.2 contains a bug in DocumentChange.newIndex, which returns the oldIndex.
Fixes https://github.com/firebase/firebase-js-sdk/issues/4071
Fixes https://github.com/firebase/firebase-js-sdk/issues/4079
=> Fix DocumentChange.newIndex

packages-exp/auth-exp/src/core/auth/auth_impl.ts, packages-exp/auth-exp/src/platform_browser/auth.test.ts, packages-exp/auth-exp/src/platform_browser/iframe/iframe.ts
`getRedirectResult()` was hanging previously if `config.authDomain` wasn't set. This PR makes `getRedirectResult()` error if `config.authDomain` isn't available, and also skips the eager redirect path entirely if authDomain isn't available at initialization
=> Fix issue with auto-redirect signin in auth-exp

scripts/size_report/report_binary_size.ts, scripts/size_report/report_modular_export_binary_size.ts
It will make the workflow fail instead of passing, so we know if something went wrong.
=> return non zero code on error in size analysis workflow

repo-scripts/size-analysis/bundle/rollup.ts
The old packages were deprecated and replaced by the new ones. https://github.com/firebase/firebase-js-sdk/pull/3930
=> Fix the size analysis tool to use new packages 

scripts/size_report/report_binary_size.ts
A packages might be split into multiple files in order to share code between entry points. The shared code is extracted to a shared file that all entry points import.
As a result, an entry point file may not include all code and we need to make a bundle to get the actual size of the entry point.
=> bundle the package in order to get the size for an entry point

.changeset/early-dots-peel.md, packages/rules-unit-testing/src/api/index.ts, packages/rules-unit-testing/test/database.test.ts
```assertFails``` does not recognise the permission denied error from database ```once('value')```
example
```
const app = firebase.initializeTestApp({
databaseName,
auth: { uid: 'alice' },
})
app
.database()
.ref('secrets/bob/id')
.once('value')
.then((snapshot) => {
console.log('read succeeded')
})
.catch((err) => {
console.log('read failed')
// current implementation of isPermissionDenied 
// https://github.com/firebase/firebase-js-sdk/blob/d934f74d6750dc31cca480e126757d53935cefcd/packages/rules-unit-testing/src/api/index.ts#L457
const isPermissionDenied =
(err && err.message && err.message.indexOf('PERMISSION_DENIED') >= 0) ||
(err && err.code === 'permission-denied')
console.log(`isPermissionDenied ${isPermissionDenied}`)
console.log(JSON.stringify({ message: err.message, ...err }, …
```
=> Fix assertFails not recognising database permission denied error

packages/firestore/src/core/bundle.ts, packages/firestore/src/local/bundle_cache.ts, packages/firestore/src/local/indexeddb_bundle_cache.ts, packages/firestore/src/local/local_serializer.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/memory_bundle_cache.ts, packages/firestore/test/unit/local/local_store.test.ts, packages/firestore/test/unit/local/test_bundle_cache.ts, packages/firestore/test/util/helpers.ts
The namespace imports don't work well with APIExtractor, which we want to use to generate API docs
=> Don't use namespace imports

packages/firestore/exp/src/api/reference.ts, packages/firestore/src/core/firestore_client.ts
This replaces a bunch of duplicate logic in firestore-exp with the FirestoreClient functions
=> FirestoreClient cleanup

.changeset/calm-shrimps-press.md, packages/firestore/src/api/database.ts, packages/firestore/test/integration/api/type.test.ts, packages/firestore/test/util/equality_matcher.ts
This fixes a bug where the Firestore Classic SDK leaks the firestore-exp types in QuerySnapshots. We need to use the Firestore Classic's UserDataWriter (similar to what we already do in `DoucmentSnapshot.get()`).
Fixes https://github.com/firebase/firebase-js-sdk/issues/4125, https://github.com/firebase/firebase-js-sdk/issues/4134
=> Return Firestore-Compat types from QuerySnapshot.docs

.changeset/afraid-socks-shop.md, packages/firestore/src/model/path.ts, packages/firestore/src/remote/rpc_error.ts, packages/firestore/test/unit/model/path.test.ts
JavaScript's `replace()` by default only replaces the first occurrence of a string, which breaks our field path escaping.
=> Properly escape field paths

packages/firebase/index.d.ts, scripts/docgen/content-sources/js/toc.yaml, scripts/docgen/generate-docs.js
Some `@link` tags were incorrectly formatted or the generated html file had the wrong case, leading to broken links in generated docs.
Sort of hard to avoid in Node docs, because comments sometimes reference some pages that only exist in (client) JS docs. Decided to remove the markup and leave the words as plain text in this case.
Also added 2 missing TOC entries from Storage.
=> Fix docs formatting issues.

packages-exp/auth-compat-exp/package.json, packages-exp/remote-config-exp/package.json, scripts/exp/release.ts
Remove line blocking auth-exp release. Change 2 `prepare` scripts to call `build:release`.
=> Fixes to allow auth and remote config exp releases

.changeset/rich-birds-wink.md, packages/firestore/exp/src/api/reference.ts, packages/firestore/exp/src/api/snapshot.ts, packages/firestore/lite/src/api/reference.ts, packages/firestore/lite/src/api/snapshot.ts, packages/firestore/lite/src/api/write_batch.ts, packages/firestore/src/api/user_data_reader.ts, packages/firestore/src/core/transaction.ts, packages/firestore/src/local/local_serializer.ts, packages/firestore/src/model/mutation.ts, packages/firestore/src/remote/serializer.ts, packages/firestore/test/integration/api/query.test.ts, packages/firestore/test/unit/local/local_serializer.test.ts, packages/firestore/test/unit/local/local_store.test.ts, packages/firestore/test/unit/model/mutation.test.ts, packages/firestore/test/unit/remote/serializer.helper.ts, packages/firestore/test/unit/specs/spec_builder.ts, packages/firestore/test/util/helpers.ts
=> Replace usage of transform with updateTransforms

.github/workflows/prerelease-manual-deploy.yml, packages/firebase/firestore/bundle/index.ts, packages/firebase/firestore/bundle/package.json, packages/firebase/firestore/index.cdn.ts, packages/firebase/firestore/memory/bundle/index.ts, packages/firebase/firestore/memory/bundle/package.json, packages/firebase/firestore/memory/index.cdn.ts, packages/firebase/firestore/memory/index.ts, packages/firebase/firestore/package.json, packages/firebase/rollup.config.js, packages/firebase/src/index.cdn.ts, packages/firebase/src/index.node.ts, packages/firebase/src/index.rn.ts, packages/firebase/src/index.ts, packages/firestore/rollup.config.node.js
* Add missing `firebase/firestore/bundle` and `firebase/firestore/memory/bundle`.
* Add bundle to firebase complete build
* Add missing firestore.proto for Firestore memory build for Node.
=> A few fixes for Firestore bundle sdk builds

packages/database/src/realtime/BrowserPollConnection.ts, packages/database/src/realtime/Constants.ts, packages/database/src/realtime/WebSocketConnection.ts
Updates the console detection to use new URLs (*.corp.google.com and console.firebase.google.com). This will ensure that we append the "r=f" URL param.
=> Update Console domains for RTDB SDK

.changeset/snake-ten-some.md, packages-exp/performance-exp/src/services/transport_service.test.ts, packages-exp/performance-exp/src/services/transport_service.ts, packages/performance/src/services/transport_service.test.ts, packages/performance/src/services/transport_service.ts
Backend starts rejecting logRequest with more than 1000 events in batch. In order for client event to be accepted and avoid any unintentional flood, put a cap for each logRequest dispatch to be 1000, extra events will stay in queue until next dispatch.
=> Control the maximum amount of events in single logRequest to be 1000 in Performance Monitoring

.github/workflows/test-all.yml
Was causing error in CI:
```
Run echo "::set-env name=FIREBASE_CI_TEST_START_TIME::$(date +%s)"
Error: Unable to process command '::set-env name=FIREBASE_CI_TEST_START_TIME::1607107014' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> Update disabled setenv command

scripts/docgen/content-sources/node/toc.yaml
I overlooked this in the review.
=> Fix Node toc.yaml typo

common/api-review/auth-exp.api.md, packages-exp/auth-exp/index.node.ts, packages-exp/auth-exp/index.rn.ts, packages-exp/auth-exp/index.ts, packages-exp/auth-exp/index.webworker.ts, packages-exp/auth-exp/src/core/auth/initialize.ts, packages-exp/auth-exp/src/core/index.ts, packages-exp/auth-exp/src/core/providers/oauth.test.ts, packages-exp/auth-exp/src/core/providers/oauth.ts, packages-exp/auth-types-exp/index.d.ts
Specifically, this PR:
* Fixes the return type of `setPersistence` to be the correct value (`Promise<void>`) in the typings package
* Adds `OAuthProvider.credentialFromResult()` and `OAuthProvider.credentialFromError()`
=> Fix some incorrect typings / missing pieces in the new auth SDK

packages/firestore/src/core/bundle_impl.ts, packages/firestore/src/core/component_provider.ts, packages/firestore/src/core/firestore_client.ts, packages/firestore/src/core/sync_engine.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/local_store_impl.ts, packages/firestore/src/remote/remote_store.ts, packages/firestore/test/unit/local/local_store.test.ts
This addresses an outstanding cleanup from the firestore-exp work. In the later stages of the development, we decided to use consistent prefixes for all free-standing functions so that they we can continue to use the method names from other platforms. This first PR addresses LocalStore.
A class that already follows this pattern is FirestoreClient.
=> Prefix all LocalStore functions with localStore

packages-exp/remote-config-exp/src/index.ts, packages-exp/remote-config-exp/src/register.ts
If this import is not in the same file that uses the code (that has the `getProvider()` call), this import gets tree-shaken out during the rollup build and installations fails to register. (The error won't happen if there's another library, like performance, bringing in installations.)
=> Fix remote-config-exp installations import

.changeset/large-books-call.md, packages/auth/src/authuser.js, packages/auth/src/idtoken.js, packages/auth/src/token.js, packages/auth/test/auth_test.js, packages/auth/test/authuser_test.js, packages/auth/test/idtoken_test.js, packages/auth/test/storageusermanager_test.js, packages/auth/test/testhelper.js, packages/auth/test/token_test.js
See cl/343354267, cl/347495710.
=> [Auth] Update auth token logic to rely on device clock time instead of server time

.github/ISSUE_TEMPLATE/alpha_bug_report.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml
This PR makes a few changes to issue templates:
1. Adds a separate issue template for Alpha bugs. It has a slightly different preamble and also auto-applies the `alpha` label.
1. Adds a new "choice" screen to direct people to the right template and also offer a link to Support.
Hard to preview in a PR but here's how the iOS SDK chooser looks:
=> Issue template for alpha

.github/ISSUE_TEMPLATE/bug_report.md
Adding a note about reduced capacity during the holiday. Also adding some line breaks makes the commented-out text format better in the Github editor.
=> Add reduced capacity note to issue template

scripts/check_changeset.ts
Changesets seems to have been updated so `changeset status` errors if there is no changeset. The regular changeset bot already has a message about this so it's redundant for the changeset checker to surface this message. Also it shouldn't count as a failed Github check.
=> Do not block if no changesets present

.changeset/slimy-mugs-type.md, packages/firestore/src/api/database.ts, packages/firestore/test/integration/api/type.test.ts
We need to use the "classic" UserDataWriter in the old Transaction API, as only the classic UserDataWriter returns the old API types. This is the same fix as https://github.com/firebase/firebase-js-sdk/pull/4136 (and the last!)
Fixes https://github.com/firebase/firebase-js-sdk/issues/4226
=> Return Firestore Classic types from Transaction API

.changeset/dirty-hotels-cheat.md, packages/database/src/core/RepoInfo.ts, packages/database/test/database.test.ts
Fixes #3681
Added new unit test
None
=> Fix multiple database instances when using emulator

.changeset/metal-paws-joke.md, packages/firestore/src/lite/query.ts, packages/firestore/test/integration/api/validation.test.ts
=> Update outdated error message to include '!='

packages/storage/compat/task.ts
`UploadTaskCompat` was using a static _snapshot generated in the constructor but it won't update the state. The original `UploadTask` has a `snapshot()` getter that actually inserts the current state whenever it is called, so I'm changing the compat version to call its delegate's getter to get one with an updated state, and then wrap it in a Compat snapshot.
Fixes https://github.com/firebase/firebase-js-sdk/issues/4158 I think.
=> Fix storage compat task bug

packages/firestore/src/model/mutation.ts, packages/firestore/src/model/server_timestamps.ts, packages/firestore/src/model/transform_operation.ts, packages/firestore/test/integration/api/server_timestamp.test.ts
After porting update transforms to [Android](https://github.com/firebase/firebase-android-sdk/pull/2262), I found some changes that needed to be ported back. I also replaced usages of TransformMutation.
=> Backport Android updateTransform changes

packages/firestore/src/core/bundle.ts, packages/firestore/src/local/bundle_cache.ts, packages/firestore/src/local/indexeddb_bundle_cache.ts, packages/firestore/src/local/local_serializer.ts, packages/firestore/src/local/memory_bundle_cache.ts, packages/firestore/test/unit/local/bundle_cache.test.ts, packages/firestore/test/unit/local/test_bundle_cache.ts
Rename to match API names in the BundleCache.
=> Rename Bundle metadata type to BundleMetadata

.changeset/clever-kangaroos-hug.md, packages/database/src/api/Database.ts, packages/database/test/database.test.ts
The unit test `refFromURL returns an emulated ref with useEmulator` fails for me locally. I think that we don't want to enforce the host check when the database URL is emulated.
Note that this test probably passes on CI since `localhost` gets used as the default host.
=> Fix refFromUrl when used with emulator

.changeset/wet-badgers-nail.md, packages/auth/src/auth.js, packages/auth/src/defines.js, packages/auth/src/exports_auth.js, packages/auth/test/auth_test.js, packages/firebase/externs/firebase-auth-externs.js
Also add the relevant bits to the externs in the firebase package, so that other Closure libraries can consume the new features.
=> Expose emulator config for the Auth SDK

packages/firebase/index.d.ts
I think this got overlooked in an update to database-types (https://github.com/firebase/firebase-js-sdk/blob/master/packages/database-types/index.d.ts#L88)
See https://github.com/firebase/firebase-js-sdk/issues/4250.
=> Update mismatch in main index.d.ts

common/api-review/analytics-exp.api.md, packages-exp/analytics-exp/src/api.ts, packages-exp/analytics-exp/src/factory.ts, packages-exp/analytics-exp/src/index.test.ts, packages-exp/analytics-exp/testing/integration-tests/integration.ts
(This PR was originally "add initializeAnalytics()")
Remove `analytics` prefix from `settings()` method.
=> Remove analytics prefix from settings()

scripts/size_report/size_report_helper.ts
The metrics backend for size analysis is revamped. We should be able to see some UI improvements ([a demo report](https://github.com/yifanyang/javascript/pull/3#issuecomment-760919595)) in the size analysis report.
The new implementation returns 200 (OK) instead of 202 (ACCEPTED). Therefor the script should also treat 200 as success.
=> Adjust to new size analysis implementation.

.changeset/neat-yaks-kneel.md, integration/firestore/firebase_export.ts, integration/firestore/firebase_export_memory.ts, packages/firestore/src/api/database.ts, packages/firestore/test/integration/api/database.test.ts, packages/firestore/test/integration/util/firebase_export.ts
`FirestoreDataConverter.fromFirestore()` was being invoked with an instance of `QueryDocumentSnapshot` from the experimental SDK; however, it was expected to be invoked with an instance of `QueryDocumentSnapshot` from the Classic SDK. This worked okay, except that the object was lacking attributes like `ref`, which are only provided by the Classic SDK.
The root cause is that the `FirestoreDataConverter` provided by the user was registered directly with the `QueryDocumentSnapshot` from the experimental SDK, and therefore was invoked with types from the experimental SDK. The fix is to instead register a "wrapper" data converter with the `QueryDocumentSnapshot` that calls the underlying data converter with the equivalent objects from the Classic SDK.
There was, however, a side effect of this …
=> Fix FirestoreDataConverter.fromFirestore() being called with QueryDocumentSnapshot from exp

.changeset/hip-turtles-travel.md, packages/database/src/core/Repo.ts, packages/database/test/query.test.ts
https://b.corp.google.com/issues/177263312
=> RTDB get shouldn't send requests for listened-to data

.github/workflows/test-changed.yml, packages/database/rollup.config.exp.js
I will create a separate PR directly into master to add RTDB to the exp release process.
=> Minor build fixes

packages-exp/firebase-exp/package.json, packages-exp/firebase-exp/storage/index.ts, packages-exp/firebase-exp/storage/package.json, packages/storage/package.json, scripts/exp/prepare-firestore-for-exp-release.ts, scripts/exp/prepare-storage-for-exp-release.ts, scripts/exp/release.ts
Set up scripts to publish storage-exp, similar to Firestore's.
I have a question:
I set up the script based on Firestore's pattern. Based on this, the `typings` field in `packages-exp/firebase-exp/storage/package.json` points to "dist/storage/index.d.ts". If I look at that generated file, it contains one line `export * from '@firebase/storage';`. The same thing happens in Firestore, with `firestore` instead of `storage` of course. Is that right? I get a little confused about the firebase-exp entry points.
=> Create storage-exp packaging scripts

packages/firebase/index.d.ts
Updated functions param in firebase/index.d.ts so documentation matches code changed in https://github.com/firebase/firebase-js-sdk/pull/3825
I think the second change in this file is just a `prettier` update.
=> Update functions docs

packages-exp/firebase-exp/package.json, scripts/exp/release.ts
- Add `analytics-exp` and `database` deps to `firebase-exp`.
- Fix a name collision bug in exp release script.
=> Add exp deps and fix script bug

packages-exp/analytics-exp/src/helpers.ts, scripts/exp/release.ts
Fix analytics-types-exp import.
Missed some fixes in commitAndPush.
=> Fix analytics-types-exp import and fix exp release script

packages-exp/analytics-exp/src/index.ts
Add `type` to exclude from being included in js bundle.
=> Fix analytics type export

packages/firestore/src/api/database.ts
The console build doesn't have FirebaseApp and fails the delete if this.app is accessed.
=> Fix instance deletion in the Console build

packages/storage/exp/package.json, scripts/exp/prepare-storage-for-exp-release.ts
- Ensure storage-exp typings pointing to public typings.
- Storage prep script modifies storage-types/package.json as well, to package `exp/index.d.ts`
=> Package storage-types/exp

packages-exp/analytics-exp/src/index.ts
Separate type import and export statements. Transformer is causing some trouble with `export type`.
=> Fix analytics-exp type exports

scripts/exp/prepare-storage-for-exp-release.ts, scripts/exp/release.ts
Ensure exp version of storage-types is properly packaged with other exp packages.
Tested with --dry-run release.
=> Add storage-types to exp release script

common/api-review/functions-exp.api.md, packages-exp/functions-exp/src/api.ts
Export public types. Reviewed functions-types and seems like they all should be public.
=> Export public types from functions-exp

.changeset/silent-cars-burn.md, packages/firestore/src/api/user_data_reader.ts, packages/firestore/test/integration/api/fields.test.ts
Previously any field in the document would be propagated into the
FieldMask regardless of whether or not it had an undefined value, which
led to the client acting as if the user had passed FieldValue.delete(),
which wasn't intended.
Fixes googleapis/nodejs-firestore#1392 for the JS SDK.
=> handle ignoreUndefinedProperties in set(merge: true)

packages/firestore/exp/index.ts, packages/firestore/export.ts, packages/firestore/index.bundle.ts, packages/firestore/src/api/database.ts, packages/firestore/src/exp/bundle.ts
=> Fixes for Bundles@exp

.changeset/fluffy-carrots-jam.md, packages/auth/gulpfile.js, packages/auth/protractor_spec.js, packages/auth/src/idtoken.js, packages/auth/test/idtoken_test.js
Fix #4174.
Changes to the SDK is already reviewed internally so feel free to rubber stamp. I fixed the tests while I'm at it (port conflict with Emulator UI).
=> Decode UTF-8 in ID Token. Fix #4174.

packages/firestore/test/unit/generate_spec_json.sh, packages/firestore/test/unit/specs/bundle_spec.test.ts
Also fix generate_spec_json.sh
=> Remove no-android from Bundle tests

common/api-review/auth-exp.api.md, packages-exp/auth-exp/index.ts, packages-exp/auth-types-exp/index.d.ts
Export public types from auth-exp main package entry point.
=> Export public types from auth-exp

packages/database/test/query.test.ts
Before this test was trying to shallow-compare the promise object to `{foo: 'bar'}`.
=> Fix bug in rtdb query get test

.changeset/wet-windows-itch.md, packages/database/src/api/Query.ts, packages/database/src/core/view/QueryParams.ts, packages/database/test/query.test.ts
We should not be passing a fallback key to startAfter if we're querying on a key index. The indexValue is the key in this case.
=> Fix startAfter/endBefore for orderByKeys queries

packages-exp/auth-exp/src/api/authentication/idp.ts, packages-exp/auth-exp/src/api/index.test.ts, packages-exp/auth-exp/src/api/index.ts, packages-exp/auth-exp/src/core/strategies/idp.test.ts, packages-exp/auth-exp/src/core/strategies/idp.ts
We weren't passing through one of the required flags in the request that allows the `Provider.credentialFromError()` flow to work.
Fixes https://github.com/firebase/firebase-js-sdk/issues/4389
=> Fix issue with IDP sign in error handling

repo-scripts/size-analysis/analysis-helper.ts
Size analysis CI bugs started happening after we changed auth-exp to export const enum types from the main package.
I hope this is the most correct way to find and filter out const enums.
Also added 'tslib' as an external - otherwise rollup will do it anyway but give you a lot of warnings.
=> Fix size analysis script issues

packages-exp/auth-exp/api-extractor.json, packages-exp/auth-exp/package.json, packages-exp/auth-exp/src/core/action_code_url.ts, packages-exp/auth-exp/src/core/credentials/oauth.ts, packages-exp/auth-exp/src/core/credentials/phone.ts, packages-exp/auth-exp/src/core/strategies/credential.ts, packages-exp/auth-exp/src/core/strategies/idp.ts, packages-exp/auth-exp/src/core/user/account_info.ts, packages-exp/auth-exp/src/core/user/additional_user_info.ts, packages-exp/auth-exp/src/core/user/id_token_result.ts, packages-exp/auth-exp/src/core/user/link_unlink.ts, packages-exp/auth-exp/src/core/user/token_manager.ts, packages-exp/auth-exp/src/core/util/resolver.ts, packages-exp/auth-exp/src/model/application_verifier.ts, packages-exp/auth-exp/src/model/auth.ts, packages-exp/auth-exp/src/model/id_token.ts, packages-exp/auth-exp/src/model/popup_redirect.ts, packages-exp/auth-exp/src/model/user.ts, packages-exp/auth-exp/src/platform_browser/messagechannel/receiver.ts, packages-exp/auth-exp/src/platform_browser/messagechannel/sender.ts, packages-exp/auth-exp/src/platform_browser/persistence/indexed_db.ts, packages-exp/auth-exp/src/platform_browser/popup_redirect.ts, packages-exp/auth-exp/src/platform_browser/strategies/phone.ts, packages-exp/auth-exp/src/platform_browser/strategies/popup.ts, packages-exp/auth-exp/src/platform_browser/strategies/redirect.ts
1. Create a rollup d.ts file that only contains public types. Fixes https://github.com/firebase/firebase-js-sdk/issues/4392
2. Remove unnecessary `@internal` annotations. `@internal` is only needed to hide members of public API, e.g. to hide internal methods of a public class. If something is not part of the API, there is no need to annotate it.
=> Expose only public types from Auth exp

common/api-review/storage.api.md, packages/storage/exp/index.ts
Add jsdoc description and change name from `url` to `bucketUrl` to make it more clear. (FYI the param name in the original API is `url`).
Fixes https://github.com/firebase/firebase-js-sdk/issues/4407
=> Fill out storage bucket url param

scripts/check_changeset.ts
Blocking flag should only be set if `firebase` bump is mismatched or missing.
=> Fix changeset checker logic

.changeset/eight-bananas-nail.md, packages/firestore/src/core/sync_engine_impl.ts, packages/firestore/test/unit/specs/limbo_spec.test.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
Fix a bug where enqueued limbo resolutions are left in the queue even after all targets that care about their resolutions are stopped. This erroneous behavior was found in and reported against the Android SDK (https://github.com/firebase/firebase-android-sdk/issues/2311) but also applies to the Web and iOS SDKs. This fix will be ported to those other SDKs. This bug was introduced when limbo resolution throttling was implemented almost a year ago (https://github.com/firebase/firebase-js-sdk/pull/2790).
=> Dequeue limbo resolutions when their respective queries are stopped

packages-exp/analytics-exp/package.json
This should fix the canary release workflow. All the other exp packages are set to private.
=> Add private field to analytics-exp

packages-exp/auth-exp/src/core/auth/firebase_internal.test.ts, packages-exp/auth-exp/src/core/auth/firebase_internal.ts, packages-exp/auth-exp/src/core/errors.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/4425
"Fixes" is a loose sense. There's not a good fix for this. The error will at least make it clear what the remedy is.
=> Throw an error when the Auth (exp) internal instance is used by another SDK before Auth initialization

.changeset/young-cups-drum.md, packages/database-types/index.d.ts, packages/firebase/index.d.ts
Add missing public types for startAfter/endBefore.
=> Add startAfter() and endBefore() to database types

packages-exp/app-exp/src/api.test.ts, packages-exp/app-exp/src/constants.ts
Incorrect paths causing `registerVersion` to not find the correct platform logging string and trying to register library using its raw name, which has illegal characters.
Console warnings look like:
```
[2021-02-09T18:37:57.903Z]  @firebase/app: Unable to register library "@firebase/installations-exp" with version "0.0.900": library name "@firebase/installations-exp" contains illegal characters (whitespace or "/")
defaultLogHandler @ logger.ts:115
logger.ts:115 [2021-02-09T18:37:57.906Z]  @firebase/app: Unable to register library "@firebase/performance-exp" with version "0.0.900": library name "@firebase/performance-exp" contains illegal characters (whitespace or "/")
defaultLogHandler @ logger.ts:115
logger.ts:115 [2021-02-09T18:37:57.907Z]  @firebase/app: Unable to register library …
```
=> Fix version name lookup for exp packages

packages/analytics/index.test.ts, packages/analytics/src/factory.ts, packages/analytics/src/helpers.test.ts, packages/analytics/src/helpers.ts, packages/analytics/src/initialize-ids.test.ts, packages/analytics/src/initialize-ids.ts
Confirmed with gtag team that including measurementId in initial script tag request does not trigger a page_view event. page_view is in fact triggered on first config call. Tested this out as well.
We now wait for measurementID to be fetched from the dynamic config endpoint, then insert the script tag.  All events sent with firebase.analytics() are still queued until after all initialization requests complete, so the delay shouldn't cause any problems?
This should prevent 2 downloads of gtag reported by users here: https://github.com/firebase/firebase-js-sdk/issues/2628 which causes a cluttered and confusing log when using the Google Analytics Debugger chrome extension.
I'm still not sure if the double download causes any functionality issues (I don't think so) but it seems to make it …
=> Send Analytics measurement ID with script tag request

packages/firestore/src/exp/database.ts, packages/firestore/src/lite/database.ts, packages/firestore/src/util/error.ts, packages/firestore/test/lite/integration.test.ts
Throw if `initializeFirestore()` is called after a Firestore instance has already been created for the app.
=> throw if initializeFirestore is called more than once

packages-exp/auth-exp/src/platform_cordova/plugins.ts, packages-exp/auth-exp/src/platform_cordova/popup_redirect/events.test.ts, packages-exp/auth-exp/src/platform_cordova/popup_redirect/events.ts, packages-exp/auth-exp/src/platform_cordova/popup_redirect/popup_redirect.test.ts, packages-exp/auth-exp/src/platform_cordova/popup_redirect/popup_redirect.ts, packages-exp/auth-exp/src/platform_cordova/popup_redirect/utils.test.ts, packages-exp/auth-exp/src/platform_cordova/popup_redirect/utils.ts
This change also reshuffles the Cordova code structure a bit
=> Add an app activity listener to more-or-less complete the redirect sign in flow.

packages/app/src/firebaseApp.ts, packages/app/src/lite/firebaseAppLite.ts, packages/app/tsconfig.json
This shaves off a little bit of size. It was meant to fix #4207, but is no longer needed for it. It sill saves some bytes though.
=> Remove downlevelIteration from firebaseApp

.changeset/itchy-grapes-drum.md, packages-exp/auth-compat-exp/src/auth.ts, packages-exp/auth-exp/src/api/index.test.ts, packages-exp/auth-exp/src/core/auth/auth_impl.ts, packages-exp/auth-exp/src/core/auth/emulator.test.ts, packages-exp/auth-exp/src/core/auth/emulator.ts, packages-exp/auth-exp/src/core/util/emulator.test.ts, packages-exp/auth-exp/src/core/util/emulator.ts, packages-exp/auth-exp/src/model/auth.ts, packages-exp/auth-types-exp/index.d.ts, packages/auth-types/index.d.ts
This PR implements the approved `auth.emulatorConfig` API in `auth-exp`, in parity with existing `auth` SDK.
Somehow `auth.emulatorConfig` and also `useEmulator` were never added to the existing `auth-types`. This PR also fixes that (and replaces #4354).
=> Implement and type auth.emulatorConfig.

packages-exp/auth-exp/index.cordova.ts, packages-exp/auth-exp/src/model/popup_redirect.ts, packages-exp/auth-exp/src/platform_browser/strategies/redirect.ts, packages-exp/auth-exp/src/platform_cordova/popup_redirect/popup_redirect.ts, packages-exp/auth-exp/src/platform_cordova/strategies/redirect.ts
Cordova can use the `platform_browser` redirect entry points entirely, we just need to add new functions that have a different return type (`Promise<void>` instead of `Promise<never>`)
=> Add remaining bits to support Cordova redirect sign in

packages/database/src/api/Query.ts, packages/database/src/core/ReadonlyRestClient.ts, packages/database/src/core/view/QueryParams.ts, packages/database/src/core/view/View.ts
I kept simple getters and `copy()` within the class. Other methods are changed to functions.
=> Refactor QueryParams

common/api-review/storage.api.md, packages/storage/exp/index.ts, packages/storage/exp/public-types.ts, packages/storage/package.json, packages/storage/src/metadata.ts, packages/storage/src/reference.ts, packages/storage/test/integration/integration.exp.test.ts, scripts/exp/prepare-storage-for-exp-release.ts, scripts/exp/release.ts
Remove exp types for storage as part of the effort to remove all -types packages from the exp SDK.
=> Remove storage-types/exp

common/api-review/functions-exp.api.md, packages-exp/functions-exp/src/api.ts, packages-exp/functions-exp/src/callable.test.ts, packages-exp/functions-exp/src/public-types.ts, packages-exp/functions-exp/src/service.ts
Add `RequestData` and `ResponseData` generics to `httpsCallable`. `RequestData` is the arg provided to the callable function (only one allowed). The callable function returns a promise with a `data` field, and `RequestData` describes whatever is in that data field.
Used the generics in a couple of `httpsCallable` tests as a check to make sure the typing works, and left them out of some tests to make sure it also works if they are omitted.
=> Add generics to httpsCallable

common/api-review/database.api.md, packages/database/src/core/RepoInfo.ts, packages/database/src/realtime/BrowserPollConnection.ts, packages/database/src/realtime/Connection.ts, packages/database/src/realtime/WebSocketConnection.ts, packages/database/test/repoinfo.test.ts
It seems like most of the methods should stay on the class, I only extracted `connectionURL` and its helper method `needsQueryParam` but let me know if that's incorrect.
=> Tree-shake RepoInfo

packages-exp/auth-exp/src/core/auth/initialize.test.ts, packages-exp/auth-exp/src/model/popup_redirect.ts, packages-exp/auth-exp/src/platform_browser/popup_redirect.test.ts, packages-exp/auth-exp/src/platform_browser/popup_redirect.ts, packages-exp/auth-exp/src/platform_browser/strategies/popup.ts, packages-exp/auth-exp/src/platform_cordova/popup_redirect/popup_redirect.ts, packages-exp/auth-exp/test/helpers/mock_popup_redirect_resolver.ts
Popups should open as quickly as possible after being triggered by a user action. This change moves the origin validation stage to _after_ the popup is opened, to prevent latency between user action and the popup. See this discussion: https://github.com/firebase/firebase-js-sdk/discussions/4432
=> Movie client-side popup origin validation to _after_ popup is opened

packages-exp/auth-exp/src/core/providers/oauth.test.ts, packages-exp/auth-exp/src/core/providers/oauth.ts, packages-exp/auth-exp/src/core/user/additional_user_info.ts, packages-exp/auth-exp/src/core/user/user_credential_impl.ts, packages-exp/auth-exp/src/model/id_token.ts
The OIDC stuff was pretty much there already, but the type for several things internally needed to be changed from strictly `ProviderId` to `ProviderId | string` as OIDC provider IDs are arbitrary strings
=> Fix the OAuth credential logic, and add support for OIDC

packages-exp/auth-exp/index.cordova.ts, packages-exp/auth-exp/index.node.ts, packages-exp/auth-exp/index.rn.ts
Fixes https://github.com/firebase/firebase-js-sdk/discussions/4510
=> fix getAuth for non browser entry points

.changeset/config.json, common/api-review/analytics-exp.api.md, packages-exp/analytics-compat/.eslintrc.js, packages-exp/analytics-compat/karma.conf.js, packages-exp/analytics-compat/package.json, packages-exp/analytics-compat/rollup.config.js, packages-exp/analytics-compat/rollup.config.release.js, packages-exp/analytics-compat/rollup.shared.js, packages-exp/analytics-compat/src/constants.ts, packages-exp/analytics-compat/src/index.ts, packages-exp/analytics-compat/src/service.test.ts, packages-exp/analytics-compat/src/service.ts, packages-exp/analytics-compat/tsconfig.json, packages-exp/app-exp/src/constants.ts, packages-exp/functions-compat/src/register.ts, packages/analytics-types/index.d.ts, packages/analytics/src/factory.ts, packages/firebase/index.d.ts
Create analytics-compat package wrapping analytics-exp. Did not add to `firebase` package - doesn't seem like most compat packages have been added to it yet.
=> Implement analytics-compat package

packages/database/index.node.ts, packages/database/index.ts, packages/database/src/api/Database.ts, packages/database/src/api/internal.ts, packages/database/src/api/test_access.ts, packages/database/src/core/RepoManager.ts, packages/database/src/exp/Database.ts
Removes the RepManager, which was only used as a singleton. It is replaced with two const variables. All functions are moved to be tree-shakeable (interrupt() and resume() were removed since they are not used).
=> Remove RepoManager

packages/database/src/core/Repo.ts, packages/database/src/core/SparseSnapshotTree.ts, packages/database/test/sparsesnapshottree.test.ts
Changed from class to interface, replaced the constructor with `newSparseSnapshotTree`?
Two methods are only used in the unit tests (`find` and `forEachChild`), but now that they've been extracted they shouldn't make it into the bundle, so they probably don't need to be moved into the test file.
=> Tree-shake SparseSnapshotTree

.changeset/little-suns-train.md, packages/firebase/index.d.ts
`eventParams` should be an optional argument.
=> Fix analytics logEvent public signatures

packages-exp/auth-compat-exp/src/auth.test.ts, packages-exp/auth-compat-exp/src/auth.ts, packages-exp/auth-compat-exp/src/persistence.ts, packages-exp/auth-compat-exp/src/user.ts, packages-exp/auth-exp/internal/index.ts
This change does a couple things:
* Saves redirect storage in reauth and link methods as well
* Fixes a bug where redirect would fail if called immediately after library load (i.e. `firebase.auth().signInWithRedirect()` where `firebase.auth()` is the first call to `auth()`)
=> Fix up the redirect persistence storage in Auth Compat

common/api-review/firestore-exp.api.md, packages/firestore/src/model/mutation.ts, packages/firestore/src/remote/serializer.ts, packages/firestore/test/unit/local/local_store.test.ts, packages/firestore/test/unit/model/mutation.test.ts, packages/firestore/test/util/helpers.ts
Port of https://github.com/firebase/firebase-android-sdk/pull/2428
=> Make TransformResult non-nullable

packages-exp/auth-exp/src/core/action_code_url.ts, packages-exp/auth-exp/src/core/auth/emulator.ts, packages-exp/auth-exp/src/core/util/handler.ts, packages-exp/auth-exp/src/platform_react_native/persistence/react_native.ts, packages/util/src/query.ts
I've tried to keep the regex short and to the point, but let's see.
Once this is merged, there should be no `new URL` or `new URLSearchParams` floating in `auth-exp`.
=> Modify URL parsing for React Native compat.

packages-exp/auth-compat-exp/src/platform.ts, packages-exp/auth-compat-exp/src/popup_redirect.test.ts, packages-exp/auth-compat-exp/src/popup_redirect.ts, packages-exp/auth-exp/src/core/auth/auth_impl.ts, packages-exp/auth-exp/src/core/auth/initialize.test.ts, packages-exp/auth-exp/src/core/strategies/redirect.test.ts, packages-exp/auth-exp/src/core/strategies/redirect.ts, packages-exp/auth-exp/src/core/util/browser.ts, packages-exp/auth-exp/src/core/util/instantiator.ts, packages-exp/auth-exp/src/model/popup_redirect.ts, packages-exp/auth-exp/src/platform_browser/auth.test.ts, packages-exp/auth-exp/src/platform_browser/popup_redirect.ts, packages-exp/auth-exp/src/platform_browser/strategies/redirect.test.ts, packages-exp/auth-exp/src/platform_browser/strategies/redirect.ts, packages-exp/auth-exp/src/platform_cordova/popup_redirect/popup_redirect.ts, packages-exp/auth-exp/test/helpers/mock_popup_redirect_resolver.ts, packages-exp/auth-exp/test/helpers/redirect_persistence.ts
This change prevents checking for redirects unless a key is set in storage. This brings the new SDK closer in line with the old SDK.
This change also similarly adds a new field to the resolver called `_shouldInitProactively`. This field is true for specific environments where opening the iframe is costly or can break the popup flow (i.e. Safari).
=> [Auth] set key in storage before redirect, check this key before checking for redirect events

packages-exp/auth-exp/src/api/authentication/idp.test.ts, packages-exp/auth-exp/src/api/authentication/idp.ts, packages-exp/auth-exp/src/core/credentials/oauth.test.ts, packages-exp/auth-exp/src/core/credentials/oauth.ts, packages-exp/auth-exp/src/core/strategies/idp.ts
We had typed it as `string|null` where it should actually be omitted if it's not set.
=> Fix postBody parameter for Auth sign in

packages-exp/auth-exp/karma.conf.js, packages-exp/auth-exp/scripts/run-node-tests.js, packages-exp/auth-exp/scripts/run-node-tests.ts, packages-exp/auth-exp/test/helpers/integration/helpers.ts, packages-exp/auth-exp/test/integration/flows/custom.local.test.ts
This change also introduces a standard of marking a test as `.local.test.ts` if it can only be run against the emulator.
=> Add custom auth integration tests (against emulator only)

packages-exp/auth-exp/karma.conf.js, packages-exp/auth-exp/scripts/run-node-tests.js, packages-exp/auth-exp/scripts/run-node-tests.ts, packages-exp/auth-exp/test/helpers/integration/emulator_rest_helpers.ts, packages-exp/auth-exp/test/helpers/integration/helpers.ts, packages-exp/auth-exp/test/integration/flows/custom.local.test.ts, packages-exp/auth-exp/test/integration/flows/phone.test.ts
This change introduces a new mechanism for detecting emulation and then pulling the OTP from the emulator API
=> Update the phone tests to work with the emulator

packages-exp/auth-exp/test/helpers/integration/emulator_rest_helpers.ts, packages-exp/auth-exp/test/helpers/integration/helpers.ts, packages-exp/auth-exp/test/integration/flows/custom.local.test.ts, packages-exp/auth-exp/test/integration/flows/oob.local.test.ts
These tests are purely local; emulator required.
=> [Auth] Add a bunch of integration tests for the various OOB Code flows

LICENSE
=> Add protobuf license needed for internal use.

packages-exp/auth-exp/scripts/run-node-tests.js, packages-exp/auth-exp/scripts/run-node-tests.ts, packages-exp/auth-exp/test/integration/webdriver/redirect.test.ts, packages-exp/auth-exp/test/integration/webdriver/static/index.js, packages-exp/auth-exp/test/integration/webdriver/util/auth_driver.ts, packages-exp/auth-exp/test/integration/webdriver/util/idp_page.ts, packages-exp/auth-exp/test/integration/webdriver/util/js_load_condition.ts
There are still a lot more tests to write, but this is a proof of concept
=> Add some redirect webdriver tests

.changeset/lemon-laws-brush.md, packages/firebase/index.d.ts, packages/firestore-types/index.d.ts, packages/firestore/src/api/database.ts, packages/firestore/src/lite/reference.ts, packages/firestore/test/integration/api/database.test.ts, packages/firestore/test/lite/integration.test.ts
Porting from [node](https://github.com/googleapis/nodejs-firestore/pull/1394).
=> Add default converter option in withConverter()

packages-exp/auth-exp/test/integration/webdriver/anonymous.test.ts, packages-exp/auth-exp/test/integration/webdriver/redirect.test.ts, packages-exp/auth-exp/test/integration/webdriver/static/anonymous.js, packages-exp/auth-exp/test/integration/webdriver/static/core.js, packages-exp/auth-exp/test/integration/webdriver/static/index.js, packages-exp/auth-exp/test/integration/webdriver/static/redirect.js, packages-exp/auth-exp/test/integration/webdriver/util/auth_driver.ts, packages-exp/auth-exp/test/integration/webdriver/util/functions.ts, packages-exp/auth-exp/test/integration/webdriver/util/idp_page.ts
This change adds webdriver tests for redirect flows including error states as well as happy states. This change also reconfigures the static files directory so that test functions aren't all in one giant file.
This brings our total webdriver integration tests to 20
=> Add more redirect tests so that almost all the main use cases are covered

.changeset/giant-eggs-nail.md
It was changed in https://github.com/firebase/firebase-js-sdk/pull/4543 without a changeset
=> add the missing changeset for @firebase/util

packages/firebase/externs/firebase-externs.js
An internal change was requested (see cl/356656077), this makes it permanent and prevents that change from being overwritten next time the firebase library is imported to google3.
=> Add externs annotation to firebase-externs

packages/database/exp/index.ts, packages/database/src/exp/DataSnapshot.ts, packages/database/src/exp/Database.ts, packages/database/src/exp/Query.ts, packages/database/src/exp/Reference.ts, packages/database/src/exp/ServerValue.ts, packages/database/src/exp/Transaction.ts, packages/database/test/exp/integration.test.ts
This adds API stubs (see go/rtdb-next)
=> Add database@exp API

.changeset/clever-apricots-look.md, packages-exp/analytics-compat/src/index.ts, packages-exp/auth-exp/src/core/auth/initialize.ts, packages-exp/auth-exp/src/core/auth/register.ts, packages-exp/functions-exp/src/config.ts, packages-exp/performance-exp/src/index.ts, packages-exp/remote-config-compat/src/index.ts, packages-exp/remote-config-exp/src/register.ts, packages/component/index.ts, packages/component/src/provider.test.ts, packages/component/src/provider.ts, packages/component/src/types.ts, packages/database/exp/index.ts, packages/database/index.node.ts, packages/database/index.ts, packages/firestore/exp/register.ts, packages/firestore/lite/register.ts, packages/firestore/src/exp/database.ts, packages/firestore/src/lite/database.ts, packages/functions/src/config.ts, packages/remote-config/index.ts, packages/storage/compat/index.ts, packages/storage/exp/index.ts
Currently component factory doesn't take an options parameter. This leads to a 2 steps initialization pattern in `initializeAuth()`, `initializeFirestore()`, `initializePerformance()` and `initializeAnalytics()`:
Step 1: The component framework creates a service instance using default options
Step 2: Set user supplied options on the service instance returned from Step 1.
This PR removes the need of the second step by allowing you to pass an options to the component framework 
using the new `Provider.initialize()` method.
2 steps initialization is also problematic for certain use cases. See this [doc](https://docs.google.com/document/d/1wv2yxkMhp01Sp6uaQgyzUIWGIP4TV80j8ggJi8TatFM/edit?resourcekey=0-qQljqbBcfnxMdyOjrjovyw#heading=h.141ziqg4ofg6) for more details.
**Component factory can …
=> Add `Provider.initialize()`

packages/database/src/core/SyncPoint.ts, packages/database/src/core/view/CompleteChildSource.ts, packages/database/src/core/view/View.ts, packages/database/src/core/view/ViewCache.ts, packages/database/src/core/view/ViewProcessor.ts
=> Tree-shake ViewCache

packages/auth/src/autheventmanager.js, packages/auth/src/cacherequest.js, packages/auth/src/rpchandler.js, packages/auth/test/proactiverefresh_test.js
To reflect internal change.
Internal link: cl/361474162
=> Change goog.now() to Date.now()

packages-exp/auth-compat-exp/.eslintrc.js, packages-exp/auth-compat-exp/index.node.ts, packages-exp/auth-compat-exp/index.ts, packages-exp/auth-compat-exp/karma.conf.js, packages-exp/auth-compat-exp/package.json, packages-exp/auth-compat-exp/scripts/run_node_tests.ts, packages-exp/auth-compat-exp/src/auth.ts, packages-exp/auth-compat-exp/test/helpers/helpers.ts, packages-exp/auth-compat-exp/test/integration/flows/anonymous.test.ts, packages-exp/auth-exp/internal/index.ts, packages-exp/auth-exp/test/helpers/integration/emulator_rest_helpers.ts
As a proof of concept, this PR also ports of the anonymous tests from the modular package.
I've update the typings for the compat package to fully match the Closure SDK as well
=> [Auth] Add integration test framework to compatibility layer.

packages/firestore/compat/config.ts, packages/firestore/exp/index.ts, packages/firestore/src/api/blob.ts, packages/firestore/src/api/database.ts, packages/firestore/src/api/field_path.ts, packages/firestore/src/api/field_value.ts, packages/firestore/src/exp/reference_impl.ts, packages/firestore/src/lite/compat.ts, packages/firestore/src/lite/query.ts, packages/firestore/src/lite/reference.ts, packages/firestore/src/lite/reference_impl.ts, packages/firestore/src/lite/snapshot.ts, packages/firestore/src/lite/transaction.ts, packages/firestore/src/lite/user_data_reader.ts, packages/firestore/src/lite/write_batch.ts
Changes:
- export compat FieldValue and FieldPath from firestore-compat
- export `Compat` from exp, so `instanceof` works correctly across packages
- This is a stopgap solution till we implement the interop proposal for all packages.
=> Export the compat implementation for FieldPath and FieldValue

packages-exp/auth-compat-exp/package.json, packages-exp/auth-compat-exp/scripts/run_node_tests.ts, packages-exp/auth-compat-exp/src/auth.ts, packages-exp/auth-compat-exp/src/popup_redirect.ts, packages-exp/auth-compat-exp/src/user_credential.ts, packages-exp/auth-compat-exp/src/wrap.ts, packages-exp/auth-compat-exp/test/integration/webdriver/static/anonymous.js, packages-exp/auth-compat-exp/test/integration/webdriver/static/core.js, packages-exp/auth-compat-exp/test/integration/webdriver/static/email.js, packages-exp/auth-compat-exp/test/integration/webdriver/static/index.html, packages-exp/auth-compat-exp/test/integration/webdriver/static/index.js, packages-exp/auth-compat-exp/test/integration/webdriver/static/persistence.js, packages-exp/auth-compat-exp/test/integration/webdriver/static/popup.js, packages-exp/auth-compat-exp/test/integration/webdriver/static/redirect.js, packages-exp/auth-compat-exp/test/integration/webdriver/static/rollup.config.js, packages-exp/auth-exp/internal/index.ts, packages-exp/auth-exp/src/mfa/mfa_resolver.ts, packages-exp/auth-exp/test/integration/webdriver/persistence.test.ts, packages-exp/auth-exp/test/integration/webdriver/util/auth_driver.ts
The compat layer uses the existing webdriver tests here; we swap out the JS source served to the browser to use the compat layer (keeping the same function names)
=> [Auth] Update compat layer credential interception; add webdriver tests

packages/database/src/api/DataSnapshot.ts, packages/database/src/api/Query.ts, packages/database/src/api/Reference.ts, packages/database/src/core/Repo.ts, packages/database/src/core/view/Event.ts, packages/database/src/core/view/EventRegistration.ts, packages/database/src/exp/DataSnapshot.ts, packages/database/src/exp/Reference.ts, packages/database/test/datasnapshot.test.ts
This PR creates the Compat class for DataSnapshot, and also adds the `@exp` class at the same time (mostly by moving code). 
There are a bunch of seemingly unrelated changes, but most of them are meant to remove internal references to the old legacy DataSnapshot from `/core`.
The next step would be to do this same change for Reference, since I only converted the code paths that I needed for the conversion.
One extra thing: The current SDK accepts numbers and string in some places for child keys, but this is not documented. I dropped accepting numbers for now.
=> Compat and @exp class for DataSnapshot

integration/messaging/test/test-receive-background.js, integration/messaging/test/test-receive-foreground.js, integration/messaging/test/test-token-delete.js, integration/messaging/test/test-token-update.js, integration/messaging/test/test-useDefaultServiceWorker.js, integration/messaging/test/test-useValidManifest.js, integration/messaging/test/utils/checkMessageReceived.js, integration/messaging/test/utils/checkSendResponse.js
Context: 
- The FM integration test (IT) is flaky.
- In a workflow, when the IT fails, the workflow normally reports the failure after 50minutes (among 10 minutes are FM IT tests).
- It's too slow to see it fails and rerun. 
Goal:
- Make the test flow fail more quickly if it fails. 
- Reduce testing time. 
This PR:
- Refactors the test suites: separate foreground and background receive checks. 
- Make background receive check run last so if the faster test fail, the entire IT fails more quickly.
- From [reports](https://github.com/firebase/firebase-js-sdk/runs/2185633365?check_suite_focus=true) `get and delete token` fails most often for unknown reason, make this test run first for the same reason above. 
- Reduce retries from 3 to 2. Retries doesn't seem to help with the majority …
=> Reduce FM Integration Test Impact & Run Time

packages-exp/auth-compat-exp/demo/rollup.config.js, packages-exp/auth-exp/src/core/auth/auth_impl.test.ts, packages-exp/auth-exp/src/core/auth/auth_impl.ts, packages-exp/auth-exp/src/core/user/user_impl.test.ts, packages-exp/auth-exp/src/core/user/user_impl.ts, packages-exp/auth-exp/src/model/user.ts
The Closure SDK makes sure the user belongs to the project by checking the API key on the user and the auth object. We don't store the API key on the user in the new SDK so we were checking this using the app name. But it's a perfectly valid use case to pass users between apps on the same project, so this check was wrong.
This PR also removes an unused rollup plugin that was breaking the compat demo build.
=> [Auth] Fix an issue with the UI interop

integration/compat-typings/package.json, packages-exp/auth-compat-exp/package.json, yarn.lock
Point to `firebase-exp` using the project location for now because `firebase-exp` doesn't exist on npm and its version is not automatically bumped in dependencies as part of the exp release. Things will work again once it becomes `firebase`.
=> fix dependencies

packages-exp/auth-exp/src/core/auth/register.ts
This is to prevent potential collisions with app name in the persistence layer (as `:` is used as the separator). In practice this will only ever apply when using fake API key / app against the emulator as no actual API key has `:`.
=> [Auth] Restrict the ':' character in API key

packages-exp/auth-exp/src/platform_browser/auth.test.ts, packages-exp/auth-exp/src/platform_browser/persistence/indexed_db.test.ts, packages-exp/auth-exp/src/platform_browser/persistence/indexed_db.ts, packages-exp/auth-exp/src/platform_browser/persistence/local_storage.ts
=> Fix indexDB putObject concurrency issue and cache.

.changeset/thick-ties-hang.md, packages/rules-unit-testing/package.json
Bug fix: Make @firebase/rules-unit-testing depend on @firebase/component directly so that @firebase/rules-unit-testing works correctly with Yarn Plug'n'Play (https://yarnpkg.com/advanced/rulebook#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies).
Closes #4716.
=> Make rules-unit-testing depend on @firebase/component directly

packages/database/exp/index.ts, packages/database/src/api/Database.ts, packages/database/src/api/Reference.ts, packages/database/src/exp/Database.ts, packages/database/src/exp/Reference_impl.ts, packages/database/src/exp/Transaction.ts, packages/database/test/helpers/util.ts, packages/database/test/query.test.ts, packages/database/test/transaction.test.ts
One breaking change: The `onComplete` callback of a transaction is no longer invoked synchronously when transactions are aborted. I think this is such a subtle change that it won't break our users - they would have to rely on the timing of a write that takes place outside of the `runTransaction` function and the transaction callback.
OnDisconnect is still missing and is next.
=> Compat class for Reference

.github/workflows/lint.yml
External contributors making PRs don't trigger the push trigger, but lint check is required for merge. I suggest running lint on both triggers and setting the PR version as the required check for merge.
=> Add pull_request trigger to lint workflow

packages-exp/analytics-exp/src/api.ts, packages-exp/auth-exp/index.ts, packages-exp/functions-exp/src/api.ts, packages-exp/installations-exp/src/api/get-installations.ts, packages-exp/messaging-exp/src/api.ts, packages-exp/performance-exp/src/index.ts, packages-exp/remote-config-exp/src/api.ts, packages/database/src/exp/Database.ts, packages/firestore/src/exp/database.ts, packages/firestore/src/lite/database.ts, packages/storage/exp/api.ts
Make `app` optional in `getFoo()` functions.
Implements the [proposal](https://docs.google.com/document/d/1iNBpkCKfPCTxKmVOctobCe-ljMzAVxQ8ViOl5gj0xug/edit?ts=605a5961)
=> Support default app in the modular SDK

packages-exp/app-exp/src/constants.ts, packages-exp/auth-compat-exp/index.ts, packages-exp/auth-exp/src/core/auth/register.ts, packages/database/exp/index.node.ts, packages/database/exp/index.ts, packages/database/exp/package.json, packages/database/exp/register.ts, packages/database/rollup.config.exp.js, packages/firestore/compat/index.node.ts, packages/firestore/compat/index.rn.ts, packages/firestore/compat/index.ts, packages/firestore/exp/api.ts, packages/firestore/exp/index.node.ts, packages/firestore/exp/index.rn.ts, packages/firestore/exp/package.json, packages/firestore/exp/register.ts, packages/firestore/rollup.config.exp.js, packages/storage/compat/index.ts, packages/storage/compat/package.json, packages/storage/exp/index.ts, packages/storage/exp/package.json, scripts/exp/release.ts
Update files as needed for platform logging to work with exp packages.
Part of this requires keeping track of the versions of firestore, storage, and database exp in their respective /exp/package.json files. These files aren't used in publishing the release so we need to add something to the release script to make sure they stay updated the same way as any other subpackage once we move out of alpha.
=> Fix platform logging for exp packages

common/api-review/analytics-exp.api.md, common/api-review/functions-exp.api.md, packages-exp/analytics-exp/src/public-types.ts, packages-exp/functions-exp/src/public-types.ts
I decided not to document every property of analytics param types like Item, I'm sure Analytics users can find those in the general Google Analytics docs, and that documentation will be better maintained.
=> Fill documentation gaps in analytics and functions exp

packages-exp/firebase-exp/compat/index.d.ts, packages/firebase/index.d.ts
Added to firebase/index.d.ts but forgot to add to firebase-exp/index.d.ts. Also the signature was wrong.
=> Add storage.useEmulator to exp global typings

common/api-review/firestore-exp.api.md, common/api-review/firestore-lite.api.md, packages/firestore/src/exp/reference_impl.ts, packages/firestore/src/exp/settings.ts, packages/firestore/src/lite/database.ts, packages/firestore/src/lite/field_value.ts, packages/firestore/src/lite/geo_point.ts, packages/firestore/src/lite/reference.ts, packages/firestore/src/lite/settings.ts, packages/firestore/src/lite/timestamp.ts, packages/firestore/src/util/error.ts, repo-scripts/prune-dts/prune-dts.ts, repo-scripts/prune-dts/tests/firestore.output.d.ts, repo-scripts/prune-dts/tests/propagates-comments.input.d.ts, repo-scripts/prune-dts/tests/propagates-comments.output.d.ts
Add missing comments for Firestore's Public API and modify the API generation script to pull JSDoc comments from a hidden superclass to the new location.
=> Add missing Firestore comments

.changeset/rich-olives-tease.md, packages/firestore/src/lite/timestamp.ts, packages/firestore/test/unit/api/timestamp.test.ts
Porting over from [node](https://github.com/googleapis/nodejs-firestore/pull/1464).
=> remove floating point rounding error in Timestamp.fromMillis()

packages-exp/auth-exp/src/platform_cordova/plugins.ts, packages-exp/auth-exp/src/platform_cordova/popup_redirect/popup_redirect.test.ts, packages-exp/auth-exp/src/platform_cordova/popup_redirect/popup_redirect.ts
=> Fix handleOpenURL spelling.

.changeset/few-stingrays-divide.md
The changeset was missed in https://github.com/firebase/firebase-js-sdk/pull/4753
=> Add missing changeset for changes in database-types

packages-exp/app-exp/src/constants.ts
Firestore-exp/database-exp platform logging name keys should point at their root package.json because that's where their `registerVersion` calls get the name/version from. Add database-compat name key.
=> Fix database and firestore exp platform logging

.changeset/hip-dingos-judge.md, packages/database/rollup.config.js
Addresses https://github.com/firebase/firebase-js-sdk/issues/4776
=> fix RTDB build

.changeset/friendly-cooks-tan.md, packages/storage/src/implementation/error.ts
Modify fix from https://github.com/firebase/firebase-js-sdk/pull/4760 so message property is populated.
=> Fix FirebaseStorageError message recursion bug

packages-exp/auth-exp/src/core/user/token_manager.ts, packages-exp/auth-exp/src/model/auth.ts, packages-exp/auth-exp/src/model/popup_redirect.ts, packages-exp/auth-exp/src/model/user.ts, packages-exp/auth-exp/src/platform_browser/recaptcha/recaptcha_loader.ts
Address an issue found in bug bash
=> exclude internal types from appearing in the Auth public typings

packages-exp/messaging-compat/src/messaging-compat.ts
Sticky situation for providing legacy `isSupported`  method with the modular SDK construct. Please let me know if there is a better way to just include and export the legacy API code in the `messaging-compat`. The rational for doing so is as followed: 
- Modular `isSupported` became async. It's not compatible w/ the legacy sync version. 
- Modular SDK has two entry points `window` and `sw`, but export `isWindowSupported` and `isSwSupported` as `isSupported` depends on the context. Not sure if there is a way to import `isWindowSupported` and `isSwSupported` separately from `@firebase/messaging-exp` to `messaging-compat`.
=> Add `isSupported` for `messaging-compat`

.changeset/sweet-monkeys-warn.md, packages/database/src/core/PersistentConnection.ts, packages/database/src/exp/Database.ts
We need to invoke repoManagerApplyEmulatorSettings with db._repoInternal as db._repo starts the WebSocket connection if it hasn't yet been started and applies the production host.
Also random unrelated cleanup.
Fixes https://github.com/firebase/firebase-js-sdk/issues/4811
=> Fix db.useEmulator

packages/firestore/src/api/database.ts, packages/firestore/src/exp/database.ts, packages/firestore/src/exp/reference_impl.ts, packages/firestore/src/exp/snapshot.ts, packages/firestore/src/exp/transaction.ts, packages/firestore/src/lite/database.ts, packages/firestore/src/lite/query.ts, packages/firestore/src/lite/reference.ts, packages/firestore/src/lite/reference_impl.ts, packages/firestore/src/lite/transaction.ts, packages/firestore/src/lite/write_batch.ts
Fixes: https://github.com/firebase/firebase-js-sdk/issues/4812
The current API does not retain the type of CollectionReference<T> and Query<T> since T is not referenced within these classes.
We also want to expose a type property on FirebaseFirestore. This is similar to the type property of FirebaseDatabase@exp  and helps TypeScript tell apart instances of Firestore, FirestorLite and RTDB.
=> Make Converter explicit

.changeset/fluffy-oranges-cross.md, packages/database/src/exp/Reference_impl.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/4818
This simplifies the code in ChildEventRegistration. The class is meant to support multiple callbacks, but only one cancel callback. This broke in our refactor. Luckily, the class is never used for more than callback, so I was able to simplify the code and also fix the bug (which was due to the fact that the cancel callback was never registered under 'cancel').
=> Fix cancelCallback for child_added events

packages/app-check/src/debug.ts, packages/app-check/src/internal-api.test.ts, packages/database/src/realtime/WebSocketConnection.ts, packages/util/src/environment.ts
Add ability for App Check to use debug token in Node by using `globalThis`.
In `app-check/src/util.ts`, `self` is also used in `self.grecaptcha` and I left that alone because Node can't use `grecaptcha` anyway.
See question about headers.
=> Add Node debug token support

common/api-review/database.api.md, packages/database/index.ts, packages/database/src/api/Database.ts, packages/database/src/api/Reference.ts, packages/database/src/api/onDisconnect.ts, packages/database/src/core/util/util.ts, repo-scripts/prune-dts/extract-public-api.ts, repo-scripts/prune-dts/prune-dts.ts
Admin SDK couldn't upgrade to the latest version because our typings are broken. They reference typings from `@firebase/app-exp`. This ugly workaround fixes it.
These changes are internal, so no public types are affected.
=> fix broken typings for the non modular RTDB package

.changeset/loud-bears-rule.md, packages/app-check/package.json, packages/app-check/src/client.test.ts, packages/app-check/src/client.ts, packages/app-check/src/factory.ts, packages/app-check/src/index.ts, packages/app-check/src/internal-api.test.ts, packages/app-check/src/internal-api.ts, packages/app-check/test/util.ts, packages/app/src/constants.ts
AppCheck is ready for beta, enable platform logging.
=> Enable platform logging for AppCheck

packages/app-check-types/index.d.ts, packages/app-check/src/api.test.ts, packages/app-check/src/api.ts, packages/app-check/src/client.test.ts, packages/app-check/src/client.ts, packages/app-check/src/factory.ts, packages/app-check/src/indexeddb.ts, packages/app-check/src/internal-api.test.ts, packages/app-check/src/internal-api.ts, packages/app-check/src/state.ts, packages/app-check/src/storage.test.ts, packages/app-check/src/storage.ts, packages/app-check/test/util.ts
- Implement global opt-out. API proposal is here: https://docs.google.com/document/d/17RZDbKMRtgHoRGcyAR_KIAHPStr2aFnJmFsffO50pRI/edit?hl=en&forcehl=1#
- Implement auto-refresh timing. Formula is `issuedAtTime + (50% * TTL) + 5 minutes` from here: https://docs.google.com/document/d/1fi4xUsARCs3Uc8c46KvNiIf2rQeWnjxvODW-h0coSmo/edit?resourcekey=0-IK3tvAt8BxEmzoOHbbRfcg&disco=AAAAIUhr8kE
The second required an additional `AppCheckTokenInternal` type to be created that extends `AppCheckToken` with a `issuedAtTimeMillis` field, which is needed to calculate the auto refresh time. This info can also be extracted from the token, but I am following Android's example of adding this data to an internal token type using the local client's clock to avoid clock skew (the issued-at-time in the token is …
=> Implement App Check auto refresh timing and opt out flag

.changeset/curly-lamps-rescue.md, packages/firebase/index.d.ts
Adds correct typing for new argument introduced in #4792.
=> Fix database.useEmulator typing.

.changeset/many-turtles-try.md, packages/database/src/api/Reference.ts, packages/database/src/exp/Reference_impl.ts, packages/database/test/helpers/EventAccumulator.ts, packages/database/test/query.test.ts
The way `once()` was implemented led to some level of recursion if the user updated the value inside the `once` callback. This update would get executed synchronously, which could trigger new invocations of the `once()` callback before it was unregistered.  
Repo: https://jsbin.com/xofinop/4/edit?html,js,console
=> Database once() should only fire once

packages/database/src/core/PersistentConnection.ts
This delays the first connection attempt until we have information to send to the backend, which allows users to create DatabaseReferences before calling getAuth().
=> Establish connection only when needed

packages/database/src/core/AppCheckTokenProvider.ts, packages/database/src/core/AuthTokenProvider.ts, packages/database/src/core/PersistentConnection.ts
This changes the RTDB SDK to allow getAuth() to be called after getDatabase(). Unlike Firestore, it does not go back into blocking mode if Auth is initialized after startup. This would require us to rewrite the entire networking layer to be asynchronous and I suspect that this simple change is enough to cover most use cases.
The simple fix here works because the initial connection attempt in the networking layer is asynchronous. Only was `this.connected` is set to true do we flip to a synchronous behavior and send all requests immediately.
=> Support getAuth() after getDatabase()

.changeset/fair-garlics-smoke.md, packages-exp/app-compat/src/firebaseApp.ts, packages-exp/app-compat/test/firebaseAppCompat.test.ts, packages/app-check/src/index.ts, packages/app/src/firebaseApp.ts, packages/app/test/clientLogger.test.ts, packages/app/test/firebaseApp.test.ts, packages/app/test/platformLogger.test.ts
Make AppCheck initialization explicit, so users not intending to use app-check won't get errors in storage, functions, etc. Modify _getService to initialize component if it hasn't been.
=> Make App Check initialization explicit

.changeset/silent-planets-raise.md, packages/rules-unit-testing/src/api/index.ts
Fix related to #4863.
Public API change only changes to the almost certainly expected behavior :)
=> Fix useEmulators argument validation

packages-exp/app-compat/src/lite/firebaseNamespaceLite.ts, packages-exp/firebase-exp/compat/rollup.config.release.js, packages-exp/remote-config-exp/rollup.config.release.js, scripts/exp/prepare-util.ts
firebase-compat.js, firebase-remote-config.js, firebase-performance-standalone-compat.js are broken currently. The PR fixes them.
=> fix compat cdn builds

scripts/release/utils/yarn.ts
Set stdio on `build:release` step so we can see build errors in the terminal.
=> Show build output during release script

common/api-review/messaging-exp.api.md, packages-exp/messaging-compat/src/messaging-compat.ts, packages-exp/messaging-compat/src/registerMessagingCompat.ts, packages-exp/messaging-compat/test/messaging-compat.test.ts, packages-exp/messaging-exp/src/api.ts, packages-exp/messaging-exp/src/helpers/register.ts, packages-exp/messaging-exp/src/index.sw.ts, packages-exp/messaging-exp/src/index.ts
`messaging-compat` is a compatibility layer that bridges the v8 and v9(modular) JS API. It's created through wrapping the v9 SDK to recreate the v8 API surface. The objective is to allow developer to gradually migrate to v9 without having to migrate the entire codebase. 
Now the v9 SDK registers its listeners (`onPush`, `onSubChange`, `onMessage`) in `getMessagingInWindow` and `getMessagaingInSw` which is not called in the `messaging-compat`. Without these listeners, the compat SDK can only `getToken` and not get callbacks in `onMessage` and `onBackgroundMessage` 
- PR moves the  listeners registration to factory methods.    
- PR also removes unused variables in `messaging-compat`.
- PR registers 2 components since they will both be called in `messaging-compat` as `messaging-exp` and …
=> Migrates Listeners Registration from `getMessaging` to Messaging's Factory Methods 🏭

.github/CODEOWNERS
It doesn't seem like the techwriters alias is working for triggering a suggested reviewer or assignee, change to individual account for now (@egilmorez) and see if it works better.
=> Change techwriter alias to individual account

package.json, packages/firestore/package.json, repo-scripts/prune-dts/package.json, repo-scripts/size-analysis/bundle/webpack.ts, repo-scripts/size-analysis/package.json, yarn.lock
Updates minimum GRPC version to 1.3.
Fixes https://github.com/firebase/firebase-js-sdk/issues/4851
=> Update grpc-js to 1.3

packages/firestore/src/exp/snapshot.ts, packages/firestore/src/lite/snapshot.ts, packages/firestore/src/lite/user_data_writer.ts, packages/firestore/src/local/local_store_impl.ts, packages/firestore/src/local/memory_persistence.ts, packages/firestore/src/model/document.ts, packages/firestore/src/model/object_value.ts, packages/firestore/src/model/values.ts, packages/firestore/src/remote/serializer.ts, packages/firestore/src/util/obj.ts, packages/firestore/test/unit/model/document.test.ts, packages/firestore/test/unit/model/object_value.test.ts, packages/firestore/test/unit/remote/serializer.helper.ts, packages/firestore/test/unit/specs/bundle_spec.test.ts, packages/firestore/test/unit/specs/spec_builder.ts, packages/firestore/test/util/spec_test_helpers.ts
This is one of those "port of port" PRs. When I implemented iOS (https://github.com/firebase/firebase-ios-sdk/pull/8124) it became apparent that we do not need overlays anymore to implement mutable ObjectValues. There are only needed on Android, since Protobuf manipulations on Android are fairly expensive. On iOS and Web, we can directly edit the Protobuf object and can use a simpler version of ObjectValue.
=> Simplify ObjectValue

.changeset/twenty-scissors-exist.md, packages/firebase/app/index.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/4235
`firebase.SDK_VERSION` may not be up to date because the value is set at compile time in `@firebase/app`, which is not necessarily published with every release. This change updates `firebase.SDK_VERSION` to the latest version of `firebase` package.
Note that the solution will NOT work if you import scoped packages.
You should import using the umbrella package:
```
import firebase from 'firebase/app';
firebase.SDK_VERSION; // the latest version
// DON'T do it if you want the latest SDK VERSION
// import firebase from '@firebase/app';
// firebase.SDK_VERSION; // might be a stale version
```
To fix the issue for the scoped package, we will need to publish `@firebase/app` with every release to make sure SDK_VERSION is up to date. …
=> update SDK_VERSION to the latest value in `firebase/app`

.changeset/brown-snails-pull.md, packages-exp/functions-exp/src/serializer.test.ts, packages-exp/functions-exp/src/serializer.ts, packages/functions/src/serializer.ts, packages/functions/test/serializer.test.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/683
Also see https://github.com/firebase/firebase-js-sdk/pull/4450
Currently httpsCallable functions serialize any `Date` objects passed to them to an empty object (`{}`). In the absence of a comprehensive Date type shared across all the SDK client platforms plus the functions backend, which may or may not happen, we should at least convert it to an ISO string.
We are not automatically deserializing ISO strings because the developer may intentionally be passing that string down from the cloud function.
=> Convert Date to ISO string in functions

.github/workflows/release.yml, scripts/add_changeset.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/4235. 
This is a complete fix by publishing `@firebase/app` in every release. It's a better solution than https://github.com/firebase/firebase-js-sdk/pull/4283 because it also works if people use scoped packages directly.
=> Always release @firebase/app

packages/firebase/index.d.ts, packages/util/src/emulator.ts
Very minor edits to recently added doc strings.
Thanks!
=> Making some minor style/grammar edits.

packages-exp/auth-exp/src/core/strategies/anonymous.ts, packages-exp/auth-exp/test/integration/webdriver/anonymous.test.ts
=> [Auth] Make anonymous sign in wait for auth to finish initializing

packages-exp/messaging-compat/package.json, packages-exp/messaging-exp/api-extractor.json, packages-exp/messaging-exp/package.json
We need rollup typings to generate overloads for interop in messaging-compat.
=> create rollup typings for messaging

packages-exp/auth-exp/src/api/authentication/mfa.test.ts, packages-exp/auth-exp/src/api/authentication/sms.test.ts, packages-exp/auth-exp/src/core/errors.ts, packages/auth/src/error_auth.js
Fixes https://github.com/firebase/firebase-js-sdk/issues/4692
=> [Auth] Fix typo in invalid SMS code error message

packages-exp/messaging-exp/src/messaging-service.ts
`deleteService()` wasn't populated with a value so when `_delete()` tries to call it, there's an error. I think this pattern was copied from functions-exp where the constructor assigns a value to `deleteService()`. But it never gets assigned here, so just inlining the Promise.resolve().
=> Fix messaging delete bug

packages/firestore/src/api/credentials.ts
=> Block on Auth synchronously

common/api-review/analytics-exp.api.md, packages-exp/analytics-exp/src/api.ts, packages-exp/analytics-exp/src/errors.ts, packages-exp/analytics-exp/src/factory.ts, packages-exp/analytics-exp/src/index.test.ts, packages-exp/analytics-exp/src/index.ts, packages-exp/analytics-exp/src/initialize-analytics.test.ts, packages-exp/analytics-exp/src/initialize-analytics.ts, packages-exp/analytics-exp/src/public-types.ts, packages-exp/analytics-exp/testing/integration-tests/integration.ts
Create an `initializeAnalytics()` method that can only be called once, which can take an `AnalyticsOptions` object with an initial config. Allows users to set useful custom gtag config parameters such as `send_page_view` on initialization of analytics.
Updated some documentation comments.
Design doc (internal link):
go/firebase-analytics-initial-config
=> Add `initializeAnalytics()` to analytics-exp

.changeset/dry-spiders-destroy.md, packages/auth/buildtools/generate_test_files.sh, packages/auth/src/authuser.js, packages/auth/test/authuser_test.js
This is a mirror of cl/376945582. 
Fixes https://github.com/firebase/firebase-js-sdk/issues/4879
=> [Auth] Update user to plumb through emulator config

common/api-review/auth-exp.api.md, packages-exp/auth-compat-exp/src/user.ts, packages-exp/auth-exp/index.node.ts, packages-exp/auth-exp/index.ts, packages-exp/auth-exp/src/core/action_code_url.ts, packages-exp/auth-exp/src/core/user/link_unlink.ts, packages-exp/auth-exp/src/model/enum_maps.ts, packages-exp/auth-exp/src/model/public_types.ts
This PR removes public `const enum`s (which are inaccessible to JS anyway) and moves any (public) reference to those types to simply `string`. Instead, we export maps that can be used to reference acceptable values (but these are not used internally to aid tree shaking)
Fixes https://github.com/firebase/firebase-js-sdk/issues/5012
=> Remove all public const enums; export maps instead (with typings to strings)

packages-exp/auth-exp/index.cordova.ts, packages-exp/auth-exp/index.node.ts, packages-exp/auth-exp/index.rn.ts, packages-exp/auth-exp/index.webworker.ts
`getAuth()` is implemented separately in each auth entry point file. https://github.com/firebase/firebase-js-sdk/pull/4702 added a default app param value in only the browser `index.ts` entry point. Adding to the other entry points for consistency.
Fixes https://github.com/firebase/firebase-js-sdk/issues/4949
=> Add getAuth() default arg to all entry points

packages-exp/auth-exp/cordova/demo/.gitignore, packages-exp/auth-exp/cordova/demo/README.md, packages-exp/auth-exp/cordova/demo/package.json, packages-exp/auth-exp/cordova/demo/rollup.config.js, packages-exp/auth-exp/cordova/demo/sample-config.xml, packages-exp/auth-exp/cordova/demo/src/index.js, packages-exp/auth-exp/cordova/demo/src/logging.js, packages-exp/auth-exp/cordova/demo/src/sample-config.js, packages-exp/auth-exp/cordova/demo/www/index.html, packages-exp/auth-exp/cordova/demo/www/style.css
This app is based on the main demo app JS, with the bits removed that we don't support in Cordova.
=> [Auth] Add Cordova demo app

.changeset/sixty-masks-wash.md, packages/auth/src/exports_auth.js, packages/component/src/provider.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/4932
Since Firestore doesn't call `authProvider.get()` to work with asynchronously loaded Auth anymore (changed to use `authProvider.onInit()` in v9 which is shared with v8), `auth-interal` needs to be proactively initialized after Auth has been initialized.
Note that it only affects v8, `auth-internal` is already initialized proactively in v9.
=> auto-init auth-internal after initializing auth

packages/firestore/src/core/transaction_runner.ts, packages/firestore/test/integration/api_internal/transaction.test.ts, packages/firestore/test/integration/util/internal_helpers.ts
Porting from [Android](https://github.com/firebase/firebase-android-sdk/pull/2764)
=> Standardize transaction retries to attempts

.changeset/config.json, packages-exp/app-check-compat/.eslintrc.js, packages-exp/app-check-compat/README.md, packages-exp/app-check-compat/karma.conf.js, packages-exp/app-check-compat/package.json, packages-exp/app-check-compat/rollup.config.js, packages-exp/app-check-compat/rollup.config.release.js, packages-exp/app-check-compat/rollup.shared.js, packages-exp/app-check-compat/src/index.ts, packages-exp/app-check-compat/src/service.test.ts, packages-exp/app-check-compat/src/service.ts, packages-exp/app-check-compat/tsconfig.json
Add app-check-compat layer. This is based on the ch-appcheckexp-update branch because it needs the 2P token methods added to exp first.
@egilmorez You can ignore this one, you were automatically added because there was a change to the `.changeset` directory, but it was just the config file, not a changelog note.
=> Add app-check-compat

.changeset/config.json, common/api-review/app-check-exp.api.md, packages-exp/app-check-compat/.eslintrc.js, packages-exp/app-check-compat/README.md, packages-exp/app-check-compat/karma.conf.js, packages-exp/app-check-compat/package.json, packages-exp/app-check-compat/rollup.config.js, packages-exp/app-check-compat/rollup.config.release.js, packages-exp/app-check-compat/rollup.shared.js, packages-exp/app-check-compat/src/index.ts, packages-exp/app-check-compat/src/service.test.ts, packages-exp/app-check-compat/src/service.ts, packages-exp/app-check-compat/tsconfig.json, packages-exp/app-check-exp/src/api.test.ts, packages-exp/app-check-exp/src/api.ts, packages-exp/app-check-exp/src/factory.ts, packages-exp/app-check-exp/src/index.ts, packages-exp/app-check-exp/src/internal-api.test.ts, packages-exp/app-check-exp/src/internal-api.ts, packages-exp/app-check-exp/src/public-types.ts, packages-exp/app-check-exp/src/state.ts, packages-exp/app-check-exp/src/types.ts, packages-exp/app-check-exp/test/util.ts, packages-exp/app-check-exp/tsconfig.json
Porting 3P token APIs that were added to v8 (non-modular) API in https://github.com/firebase/firebase-js-sdk/pull/5033
Also added some test reliability improvements.
=> Port 3P token API to app-check-exp

.changeset/gold-turtles-tell.md, packages/app-check-types/index.d.ts, packages/app-check/src/api.ts, packages/app-check/src/factory.ts, packages/app-check/src/internal-api.test.ts, packages/app-check/src/internal-api.ts, packages/app-check/src/state.ts, packages/app-check/tsconfig.json
Fix a problem discovered while updating the exp version: https://github.com/firebase/firebase-js-sdk/pull/5069
App Check should treat listeners added by 3P vs 2P calls differently. 3P listeners should always call the supplied error handler if there's a token error. 2P listeners should return the token with the error field attached to the token.
Porting it here to the v8 version.
=> Update appcheck to distinguish between 3P/2P listeners

packages-exp/auth-compat-exp/index.ts, packages-exp/auth-compat-exp/rollup.config.shared.js, packages/database/rollup.config.compat.js, packages/firestore/rollup.config.browser.compat.js, packages/firestore/rollup.config.node.compat.js, packages/firestore/rollup.config.rn.compat.js, packages/storage/rollup.config.compat.js, scripts/exp/ts-transform-import-path.js
For some reason, our build doesn't remove the `-exp` in `auth-exp` correctly, so auth-compat is broken in 9.0.0-beta.5. 
We should use `ActionCodeOperation` as an implementation anyway since it has been changed from const enum to an object map.
=> Fix auth compat import

packages-exp/app-check-compat/package.json, packages-exp/app-check-compat/src/errors.ts, packages-exp/app-check-compat/src/index.ts, packages-exp/app-check-compat/src/service.test.ts, packages-exp/app-check-compat/src/service.ts
Try to fix app-check-compat's activate() incorrectly throwing an error that app check has already been initialized. This happens because app-check-compat's factory initializes app-check-exp, which means when the compat activate() calls exp's initializeAppCheck() it is too late, it has already been initialized.
This approach avoids initializing app-check-exp until activate() is called. This means the AppCheck compat service's _delegate is going to be empty at initialization. That should be fine because all the other app check compat methods can throw an error asking the user to call activate() first. I think app check compat should have its own error anyway. If they hit the error in the called exp function, it asks you to "call initializeAppCheck() first" which doesn't exist in compat.
=> Fix app-check-compat initialization

packages-exp/app-check-exp/src/index.ts
AppCheck shouldn't be able to be instantiated by consumers by using `Provider.get()` or `Provider.getImmediate()`. Rather it should become available when it's explicitly initialized by developers by calling `initializeAppCheck()` and passing it an AppCheckProvider.
=> change the instantiation mode to explicit for appcheck

packages-exp/auth-exp/test/integration/flows/anonymous.test.ts, packages-exp/auth-exp/test/integration/flows/custom.local.test.ts, packages-exp/auth-exp/test/integration/flows/email.test.ts, packages-exp/auth-exp/test/integration/flows/idp.local.test.ts, packages-exp/auth-exp/test/integration/flows/oob.local.test.ts, packages-exp/auth-exp/test/integration/flows/phone.test.ts, packages-exp/auth-exp/test/integration/webdriver/popup.test.ts, packages-exp/auth-exp/test/integration/webdriver/redirect.test.ts
It appears in the updated version of eslint we need to disable-next-line on the `import` keyword now (for tests)
=> [Auth] Fix eslint issues in tests

packages-exp/auth-exp/src/api/project_config/get_project_config.ts, packages-exp/auth-exp/src/platform_cordova/popup_redirect/popup_redirect.test.ts, packages-exp/auth-exp/src/platform_cordova/popup_redirect/popup_redirect.ts, packages-exp/auth-exp/src/platform_cordova/popup_redirect/utils.test.ts, packages-exp/auth-exp/src/platform_cordova/popup_redirect/utils.ts
=> [Auth] Implement origin validation for fast erroring-out in Cordova popup redirect resolver

.changeset/silent-seals-approve.md, packages/database/src/realtime/WebSocketConnection.ts
`this.nodeAdmin` does not always appear to be set when it should be, which is breaking the admin SDK for users with appcheck enforced. This should be more robust, since we always send whatever credentials the client has.
* At this time we cannot accept changes that affect the public API.  If you'd like to help …
=> Always send our auth token on Node, and always send an appcheck token if we have one.

scripts/exp/remove-exp.js
Access a path only if it exists.
=> Fix a bug in remove-exp.js

packages-exp/app-check-exp/src/index.ts, packages-exp/auth-exp/src/core/auth/emulator.ts, packages-exp/auth-exp/src/core/credentials/auth_credential.ts, packages-exp/auth-exp/src/core/credentials/email.ts, packages-exp/auth-exp/src/core/providers/email.ts, packages-exp/auth-exp/src/core/providers/facebook.ts, packages-exp/auth-exp/src/core/providers/github.ts, packages-exp/auth-exp/src/core/providers/google.ts, packages-exp/auth-exp/src/core/providers/twitter.ts, packages-exp/auth-exp/src/core/strategies/email.ts, packages-exp/auth-exp/src/model/public_types.ts, packages-exp/auth-exp/src/platform_browser/providers/phone.ts
- Add package description for AppCheck
- Update links in Auth comments. It's not possible to link to a property of a variable, so we just link to the variable.
- Remove unnecessary package specifiers in links
=> Update comments for v9 reference docs

.changeset/fair-cycles-rescue.md, .github/workflows/check-changeset.yml, scripts/check_changeset.ts
There is a bug in the latest changesets: https://github.com/atlassian/changesets/issues/517
Instead of letting it implicitly try to use `master`, use `--since` option to specify base SHA, obtained from Github Actions' env variables. Keep `master/HEAD` as a fallback option in case this script is run locally.
=> Fix changeset checker

common/api-review/auth-exp.api.md, packages-exp/auth-exp/src/core/providers/email.ts, packages-exp/auth-exp/src/core/providers/facebook.ts, packages-exp/auth-exp/src/core/providers/github.ts, packages-exp/auth-exp/src/core/providers/google.ts, packages-exp/auth-exp/src/core/providers/twitter.ts, packages-exp/auth-exp/src/model/id_token.ts, packages-exp/auth-exp/src/platform_browser/providers/phone.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/5118
=> [Auth] Fix broken public typings `d.ts` file

packages-exp/app-check-exp/src/client.test.ts, packages-exp/app-check-exp/src/factory.ts, packages-exp/app-check-exp/src/internal-api.test.ts, packages-exp/app-check-exp/src/internal-api.ts, packages/app-check/src/internal-api.test.ts, packages/app-check/src/internal-api.ts
Ported from v8: https://github.com/firebase/firebase-js-sdk/pull/5055
Also includes some of the test reliability fixes in 5055 that I missed porting over in an earlier PR.
=> Add debug token caching to app-check-exp

.github/workflows/label-doc-changes.yml
Actions made using the default `GITHUB_TOKEN` can't trigger additional workflow, so we switch to use the Firebase OSS bot's token.
see https://docs.github.com/en/actions/reference/events-that-trigger-workflows
=> Use oss bot github token to label PRs

packages-exp/auth-exp/src/platform_browser/load_js.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/5141
Now the promise will reject with an error instead of the result of `onerror`.
=> [Auth] Fix promise rejection for failing when loading JS

.changeset/wet-pets-travel.md, packages/database/src/realtime/Connection.ts, packages/database/src/realtime/WebSocketConnection.ts
This fixed two more problems with using admin credentials on node with appcheck enforced:
1. We now pass the auth token to the transport constructor, and
2. We set the header value to `Bearer: <token>`
us make Firebase …
=> Fix more issues related to admin auth and appcheck.

packages-exp/auth-compat-exp/package.json, packages-exp/auth-compat-exp/src/phone_auth_provider.ts, packages-exp/auth-compat-exp/test/integration/webdriver/static/index.js
Also fix those integration tests which had broken, fix a bug that the integration tests would have caught :P
=> [Auth] Add compat integration tests to CI

.changeset/nasty-hats-hope.md, common/api-review/analytics-exp.api.md, packages-exp/analytics-exp/src/api.ts, packages-exp/analytics-exp/src/public-types.ts, packages/analytics-types/index.d.ts, packages/firebase/index.d.ts
Add `firebase_screen` and `firebase_screen_class` to `EventParams` type and put them in the `logEvent('screen_view', ...)` overload. This should only affect autocomplete and type checking. Adding this to the "guides" in the docs site is also in progress.
This change is for both exp and non-modular.
API proposal: go/firebase-js-screen-view
=> Add firebase-specific screen_view params to Analytics

.changeset/nine-needles-compare.md, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/util/async_queue.ts, packages/firestore/src/util/async_queue_impl.ts, packages/firestore/test/unit/util/async_queue.test.ts
This PR changes our IndexedDB shutdown to skip all remaining work items on Safari 14. It is believed that writing to IndexedDB during unload can trigger a bug on Safari that prevents IndexedDB from loading during the next page load.
Fixes https://github.com/firebase/firebase-js-sdk/issues/4076
=> Skip IndexedDB cleanup on Safari 14

.changeset/curly-shrimps-wait.md
This was caught by the changeset checker in the PR https://github.com/firebase/firebase-js-sdk/pull/5149 but I think it got lost in the noise of the warnings about firebase-compat-typings-test that I think we can't get rid of until v9 is GA.
=> Fix changeset formatting

packages-exp/firebase-exp/analytics/package.json, packages-exp/firebase-exp/app-check/package.json, packages-exp/firebase-exp/app/package.json, packages-exp/firebase-exp/auth/cordova/package.json, packages-exp/firebase-exp/auth/package.json, packages-exp/firebase-exp/auth/react-native/package.json, packages-exp/firebase-exp/compat/analytics/package.json, packages-exp/firebase-exp/compat/app-check/package.json, packages-exp/firebase-exp/compat/app/package.json, packages-exp/firebase-exp/compat/auth/package.json, packages-exp/firebase-exp/compat/database/package.json, packages-exp/firebase-exp/compat/firestore/package.json, packages-exp/firebase-exp/compat/functions/package.json, packages-exp/firebase-exp/compat/messaging/package.json, packages-exp/firebase-exp/compat/package.json, packages-exp/firebase-exp/compat/performance/package.json, packages-exp/firebase-exp/compat/remote-config/package.json, packages-exp/firebase-exp/compat/storage/package.json, packages-exp/firebase-exp/database/package.json, packages-exp/firebase-exp/firestore/lite/package.json, packages-exp/firebase-exp/firestore/package.json, packages-exp/firebase-exp/functions/package.json, packages-exp/firebase-exp/messaging/package.json, packages-exp/firebase-exp/messaging/sw/package.json, packages-exp/firebase-exp/package.json, packages-exp/firebase-exp/performance/package.json, packages-exp/firebase-exp/remote-config/package.json, packages-exp/firebase-exp/storage/package.json
Addresses https://github.com/firebase/firebase-js-sdk/issues/5140
=> add esm entry points for node

common/api-review/auth-exp.api.md, common/api-review/database.api.md, common/api-review/functions-exp.api.md, common/api-review/storage.api.md, packages-exp/auth-compat-exp/src/auth.ts, packages-exp/auth-exp/src/core/auth/emulator.test.ts, packages-exp/auth-exp/src/core/auth/emulator.ts, packages-exp/auth-exp/src/core/errors.ts, packages-exp/auth-exp/src/core/index.ts, packages-exp/auth-exp/test/helpers/integration/helpers.ts, packages-exp/auth-exp/test/integration/webdriver/static/index.js, packages-exp/functions-compat/src/service.test.ts, packages-exp/functions-compat/src/service.ts, packages-exp/functions-exp/src/api.ts, packages-exp/functions-exp/src/service.test.ts, packages-exp/functions-exp/src/service.ts, packages-exp/functions-exp/test/utils.ts, packages/database/exp/api.ts, packages/database/src/api/Database.ts, packages/database/src/exp/Database.ts, packages/firestore/exp/api.ts, packages/firestore/lite/index.ts, packages/firestore/src/api/database.ts, packages/firestore/src/exp/database.ts, packages/firestore/src/lite/database.ts, packages/storage/compat/service.ts, packages/storage/exp/index.ts, packages/storage/src/service.ts, packages/storage/test/unit/service.compat.test.ts, packages/storage/test/unit/service.exp.test.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/4930
=> Rename all v9 modular useEmulator functions to connectEmulator

.changeset/short-lies-sing.md, packages/app-types/package.json
Hey everyone, 
i ran into an issue with the `app-types` module where the typescript compilation of a module that defined `firebase-admin` as a dependency failed with the following error:
```
.yarn/cache/@firebase-app-types-npm-0.6.2-936c84268d-243af1c06f.zip/node_modules/@firebase/app-types/index.d.ts:17:57 - error TS2307: Cannot find module '@firebase/logger' or its corresponding type declarations.
``` 
The project uses yarn2 with a 'strict' PnP mode. 
I have created a small codesandbox that demonstrates this issue: https://codesandbox.io/s/gallant-satoshi-fycm1 
Run `yarn compile` to see the issue in action. 
Looking forward to your review!
=> Add @firebase/logger as dependency to app-types

packages/database/src/exp/Database.ts, packages/storage/compat/service.ts, packages/storage/src/service.ts, packages/storage/test/unit/service.compat.test.ts
`_delete()` should be idempotent - it should just be a noop if the service has already been deleted. This prevents errors trying to delete an already deleted service.
Also firestore-compat and database-compat can't have their INTERNAL.delete() method removed easily because it's in a class shared by v8, exp, and compat. But storage-compat has it in a compat-only file, where it's not needed, so removed it.
=> Make _delete() idempotent

renovate.json
The old config stopped working for unknown reasons, and renovate is sending individual PRs for every dependency.
=> fix renovate config to group non major updates

.changeset/wise-forks-poke.md, packages-exp/analytics-exp/src/api.ts, packages-exp/analytics-exp/src/public-types.ts, packages-exp/firebase-exp/compat/index.d.ts, packages/analytics-interop-types/index.d.ts, packages/analytics-types/index.d.ts, packages/firebase/index.d.ts
Fixed some link formatting in comments, addressing https://github.com/firebase/firebase-js-sdk/issues/5116.
While doing that, discovered some of the links were for UA and not for GA4, meaning some of the event/config params were incorrect. Corrected them.
The link for screenviews (https://firebase.google.com/docs/analytics/screenviews) doesn't have the JS snippet yet, it can't be submitted until the typing changes in this PR have been released. It should be a short lag time though.
=> Fix links and update event typings

packages/database/src/core/view/EventRegistration.ts, packages/database/test/exp/integration.test.ts, packages/database/test/transaction.test.ts
This fixes a bug in listener unregistration, which exists in both the user facing `unsubscribe` API as well as runTransaction() (since it uses listeners internally).
When we unregister a listener, we go through all existing listeners to find the one that matches. We do this by comparing the callbacks for equality.
In v8, we wrap all listeners, and hence, we have to unwrap the listener to get back to the original user function before checking for equality. Our listener looks as such:
```
const listener = () => { userCallback(); /*...*/ )
listener.userCallback = userCallback;
```
In v9, we have:
```
const listener = userCallback(); 
```
Unfortunately, the comparison function considered all v9 listeners the same since it either compared `listener` (which only matches for the exact listener) …
=> Fix transaction interference in v9

common/api-review/analytics-exp.api.md, packages-exp/firebase-exp/compat/index.d.ts, packages-exp/firebase-exp/compat/index.node.ts, packages/firebase/index.d.ts, packages/firebase/src/index.node.ts
We support Node in Storage for both v9 and v8 now (https://github.com/firebase/firebase-js-sdk/pull/5149 and https://github.com/firebase/firebase-js-sdk/pull/4985) so it should be included in Node docs (remove `@webonly` tags) and in the Node all-in-one bundle.
=> Add storage to Node bundle and Node docs

packages/firestore/exp/register.ts
Reverts firebase/firebase-js-sdk#5046. Fetch streams should now work (see https://github.com/firebase/firebase-js-sdk/issues/5074#issuecomment-889532005)
Addresses https://github.com/firebase/firebase-js-sdk/issues/5074
=> Revert "Revert to use Xhr in Firestore"

.changeset/great-tigers-doubt.md, packages/app-check-types/index.d.ts, packages/app-check/src/api.test.ts, packages/app-check/src/api.ts, packages/app-check/src/factory.ts, packages/app-check/src/index.ts, packages/app-check/src/internal-api.test.ts, packages/app-check/src/internal-api.ts, packages/app-check/src/providers.ts, packages/app-check/src/recaptcha.test.ts, packages/app-check/src/state.ts, packages/app-check/src/util.ts, packages/app-check/test/util.ts, packages/firebase/index.d.ts
Create provider classes that users can use in `activate()`. To avoid breaking changes, `activate` still takes a string site key or our previous custom provider pattern, which is any object with a `getToken` property.
I also changed `addTokenListener` to check for existing tokens in both memory and storage because otherwise it will only check storage if `getToken()` is called, which only happens if the refresher starts, which only happens if automatic token refresh is enabled. I don't think fetching a token from local storage should be gated on that.
Note: API changes should also be propagated to v9 compat after this.
Edit: For docs review - only need to review `packages/firebase/index.d.ts`
=> Change appcheck activate() to use provider pattern

packages/rules-unit-testing/src/api/index.ts, packages/rules-unit-testing/test/database.test.ts
Fixes Issue 4 of #5086
https://github.com/firebase/firebase-js-sdk/issues/5086
This PR makes assertFails work properly with the storage emulator. 
Most storage permission errors throw errors with the message "(storage/unauthorized)", but assertFails only checks for the string "permission denied". This means that assertFails won't work properly for most storage unit tests. 
This fix is a small one that just adds another check if the message contains the string "unauthorized". A better fix would be to ensure that all firebase products throw consistent error message codes when permission is denied, but this solution will at least fix this bug in the unit testing library for storage for the time being.
* Added unit test to packages/rules-unit-testing/test/database.test.ts called …
=> fix: assertFails for storage read/write requests (#5086)

.changeset/gorgeous-balloons-confess.md, packages/storage/rollup.config.js
This adds back a browser CJS build, once removed by #5149 but still needed by Emulator UI. No changes to exports and package.json.
=> Add back browser CJS build as ./dist/index.browser.cjs.js.

packages-exp/auth-compat-exp/src/auth.test.ts, packages-exp/auth-compat-exp/src/auth.ts, packages-exp/auth-exp/index.ts, packages-exp/auth-exp/src/core/persistence/index.ts, packages-exp/auth-exp/src/core/persistence/persistence_user_manager.test.ts, packages-exp/auth-exp/src/core/persistence/persistence_user_manager.ts, packages-exp/auth-exp/src/platform_browser/auth.test.ts, packages-exp/auth-exp/src/platform_browser/persistence/indexed_db.ts, packages-exp/auth-exp/src/platform_browser/persistence/local_storage.ts, packages-exp/auth-exp/test/integration/webdriver/persistence.test.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/5171
`browserSession` persistence is now added to the escalation path of `getAuth()` to match v8. We also now only "upgrade" the persistence if the persistence deems itself "upgradeable" (which only applies to `indexedDB` and `localStorage`)
=> [Auth] Fix persistence issue when manually setting/using session storage

.changeset/four-taxis-fry.md, packages/app-check-types/index.d.ts, packages/app-check/src/factory.ts, packages/firebase/index.d.ts
Incorrect typing of `activate()` params in `packages/firebase/index.d.ts` is causing users to get Typescript errors when using string or provider arguments.
Fixes https://github.com/firebase/firebase-js-sdk/issues/5258
=> Fix AppCheck typings error

packages/firebase/index.d.ts, scripts/docgen/content-sources/node/toc.yaml
Did not get everything in the last attempt. This should correctly lead to a Storage section being created in the Node reference docs.
=> Correctly add Storage to Node documentation

packages/firebase/index.d.ts
Deprecated method doc should start with "Use ...".
This will fix: b/170682742
=> Fix deprecation documentation

packages-exp/performance-exp/src/index.test.ts, packages-exp/performance-exp/src/index.ts, packages-exp/performance-exp/src/utils/errors.ts, tools/gitHooks/prettier.js
Making all product initialize() functions idempotent.
See https://github.com/firebase/firebase-js-sdk/pull/5272
=> Make initializePerformance() idempotent

packages/firestore/src/exp/database.ts
Making all product initialize() functions idempotent.
See #5272
I don't see any existing tests for `initializeFirestore()` or `getFirestore()` and I'm a little unsure of how to set up a new test in this structure.
=> Make initializeFirestore() idempotent

packages-exp/auth-exp/src/core/auth/initialize.test.ts, packages-exp/auth-exp/src/core/auth/initialize.ts, packages-exp/auth-exp/src/core/errors.ts
Making all product initialize() functions idempotent.
See https://github.com/firebase/firebase-js-sdk/pull/5272
=> Make initializeAuth() idempotent

packages-exp/auth-exp/index.ts
Fixes https://github.com/firebase/firebase-js-sdk/discussions/5254
=> update getAuth comment to make clear that it's idempotent

scripts/docgen/content-sources/js/toc.yaml, scripts/docgen/content-sources/node/toc.yaml
Recent changes added some top level doc pages which were not added to the toc.yaml files, so they won't appear in the reference docs.
=> Update toc.yaml files for v8 doc generation

packages-exp/app-check-exp/src/api.ts, packages-exp/app-check-exp/src/internal-api.test.ts, packages-exp/app-check-exp/src/internal-api.ts, packages-exp/app-check-exp/src/state.ts
Copy part of the v8 app check PR https://github.com/firebase/firebase-js-sdk/pull/4902 that involves checking for token in storage during initialization. (The rest of 4902 was already in v9.)
=> Add cached token changes to v9 appcheck

packages-exp/auth-exp/src/core/auth/auth_impl.ts, packages-exp/auth-exp/src/platform_browser/auth.test.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/5304
We were holding on to any redirect error and throwing it after initialization completed. Unfortunately since init is totally async, there was no way this was actionable for developers. The error can instead be gotten by calling `getRedirectResult()`, while initialization simply swallows any errors in the redirect flow. This matches v8 behavior.
=> [Auth] Remove background error throwing in initialization

.changeset/big-lobsters-tell.md, packages/storage/src/service.ts, packages/storage/test/unit/service.exp.test.ts
Based on the only reference to ".." in the Android repo (a test), it seems we do not try to parse ".." as a parent shortcut on the client side and just pass it directly to the server. (https://github.com/firebase/firebase-android-sdk/blob/d7017614307c4497f5b91da3c59b6de2102a17b7/firebase-storage/src/test/java/com/google/firebase/storage/PathingTest.java#L162)
So we will just remove the error and the test for it, and server errors should enable developers to debug if they pass an invalid path.
Fixes https://github.com/firebase/firebase-js-sdk/issues/5180
=> Storage: Do not throw for path containing ".."

packages-exp/firebase-exp/messaging/sw/index.ts
Ensures that `isSupported()` function exported by `@firebase/messaging/sw` (https://github.com/firebase/firebase-js-sdk/pull/4665) is available from `firebase/messaging/sw`.
Fixes https://github.com/firebase/firebase-js-sdk/issues/5309
=> Add isSupported() to firebase/messaging/sw exports

packages-exp/functions-exp/package.json, packages-exp/functions-exp/src/callable.test.ts, packages-exp/functions-exp/src/config.ts, packages-exp/functions-exp/src/context.ts, packages-exp/functions-exp/src/service.ts, packages-exp/functions-exp/test/utils.ts
Modify functions service to use the new interop component `messaging-internal`.
=> Change functions to use messaging interop component

packages/firestore-compat/src/index.console.ts, packages/firestore/lite/register.ts, packages/firestore/src/api/credentials.ts, packages/firestore/src/api/database.ts, packages/firestore/src/core/firestore_client.ts, packages/firestore/src/lite-api/database.ts, packages/firestore/src/register.ts, packages/firestore/test/integration/util/internal_helpers.ts, packages/firestore/test/util/api_helpers.ts
This PR changes Firestore to block the AsyncQueue even if Auth is only available after startup. The queue is blocked from the moment that auth is detected until the SDK receives a user.
=> Always block on Auth

common/api-review/auth.api.md, packages/auth/api-extractor.json, scripts/exp/docgen.ts
Hack to ensure auth uses `index.doc.d.ts` for doc gen only - and not during the actual build.
=> Set up auth to use a separate d.ts file for docgen

packages/rules-unit-testing/src/impl/discovery.ts, packages/rules-unit-testing/src/impl/rules.ts, packages/rules-unit-testing/src/impl/test_environment.ts, packages/rules-unit-testing/src/impl/url.ts, packages/rules-unit-testing/src/initialize.ts, packages/rules-unit-testing/src/util.ts, packages/rules-unit-testing/test/impl/discovery.test.ts, packages/rules-unit-testing/test/impl/rules.test.ts, packages/rules-unit-testing/test/test_utils.ts, packages/rules-unit-testing/test/util.test.ts, yarn.lock
This completes all rules unit testing v2 features.
=> Implement rest of RUTv2 features.

packages/messaging/src/api.ts, packages/messaging/src/helpers/register.ts
Ensure messaging env checks are only called when the user explicitly initializes messaging. If messaging is initialized by an internal API (Functions specifically) in an unsupported environment, it will leave ugly warnings that aren't catchable because the check is async and leaves a hanging promise. Since the user did not call messaging, the user can't do anything about it, and the warning is not helpful.
Also in Node 16, it actually exits and blocks further execution.
=> Move Messaging env checks to public methods

repo-scripts/api-documenter/src/documenters/MarkdownDocumenter.ts, repo-scripts/api-documenter/src/toc.ts
Changes:
1. show table of functions first in the overview pages
2. generate toc items only for entry points
=> Update reference doc generation

.changeset/eleven-swans-drive.md, .changeset/late-bobcats-swim.md, packages/analytics-compat/src/service.test.ts, packages/app-check-compat/src/service.test.ts, packages/app-compat/src/index.lite.ts, packages/app-compat/src/index.ts, packages/firestore/package.json, packages/functions-compat/src/callable.test.ts, packages/functions-compat/src/index.node.ts, packages/functions-compat/src/service.test.ts
Fixes https://github.com/angular/angularfire/issues/2903
- Fix cjs build of app-compat, so it works with mjs import in Nodejs/bundlers
- Expose firestore/lite in Nodejs by defining the exports field
=> Fix nodejs builds

.changeset/twelve-items-wonder.md, packages/firestore/src/platform/node_lite/connection.ts, packages/storage/src/platform/node/connection.ts
Storage and FirestoreLite were importing node-fetch as a namespace, rather than pulling the default fetch function and using that.
```ts
// import * as nodeFetch from 'node-fetch';
Object [Module] {
default: [Getter],
Headers: [Getter],
Request: [Getter],
Response: [Getter],
FetchError: [Getter]
}
```
```ts
// import nodeFetch from 'node-fetch';
[Function: fetch] {
isRedirect: [Function (anonymous)],
Promise: [Function: ZoneAwarePromise] {
toString: [Function (anonymous)],
resolve: [Function (anonymous)],
reject: [Function (anonymous)],
race: [Function (anonymous)],
all: [Function (anonymous)],
allSettled: [Function (anonymous)],
allWithCallback: [Function (anonymous)],
__zone_symbol__uncaughtPromiseErrors: []
}
}
```
This was leading to timeouts in Storage node and uncaught exceptions in …
=> Fix the import of node-fetch polyfill

.changeset/dirty-balloons-unite.md, packages/auth/package.json
Fixes https://github.com/firebase/firebase-js-sdk/issues/5392
`repo-scripts/prune-dts/prune-dts.ts` removes inherited constructors, which makes the typings of classes incorrect.
This is a temporary fix, and will expose some internal types to developers. We should fix the `prune-dts.ts` to handle constructors correctly.
@schmidt-sebastian fyi
=> use raw api-report rollup d.ts

.changeset/slimy-jobs-wave.md, packages/app-compat/api-extractor.json, packages/app-compat/package.json, packages/app-compat/src/firebaseApp.ts, packages/app-compat/src/public-types.ts
fixes https://github.com/firebase/firebase-js-sdk/issues/5382
=> Remove private types in app-compat

packages/auth/src/core/strategies/custom_token.test.ts, packages/auth/src/core/strategies/custom_token.ts, packages/auth/src/core/user/reload.test.ts, packages/auth/src/core/user/reload.ts, packages/auth/test/helpers/integration/emulator_rest_helpers.ts, packages/auth/test/integration/flows/custom.local.test.ts
Added integration tests for passthrough, namely,
- for the initial call to signInWithCustomToken
- for a force refresh with a customTokenProvider
Noticed a couple bugs in the process and addressed it here too:
- `user.uid` is not set until a call to `_reloadWithoutSaving()`. The previous logic in `_reloadWithoutSaving()` did not correctly set the `uid` and is now updated to parse the access token for the `sub` claim
- The REST API for [`signInWithCustomToken`](https://cloud.google.com/identity-platform/docs/reference/rest/v1/accounts/signInWithCustomToken) does not include the `localId` in the response, so the assertion in `setCustomTokenProvider()` was also updated to parse the id token 
`xit` is used in place of `it` since passthrough emulator changes have not been merged into main, but …
=> Add integration tests, fix reload and setCustomTokenProvider

packages/auth-compat/demo/public/script.js, packages/auth/cordova/demo/src/index.js, packages/auth/cordova/demo/www/index.html, packages/auth/demo/public/index.html, packages/auth/demo/src/index.js
Added form for setting / clearing customTokenProvider. For simplicity, the provider set simply returns the custom token that is passed in.
Corresponding internal bug: b/192699639
=> Add custom token provider form to auth demo page

packages/firestore/src/local/local_documents_view.ts, packages/firestore/src/local/local_store_impl.ts, packages/firestore/src/model/mutation.ts, packages/firestore/src/model/mutation_batch.ts, packages/firestore/test/unit/model/mutation.test.ts
The mutation file never followed the functional style naming convention we came up with during the firestore-exp migration. This PR changes the function names to follow the className+methodName pattern.
=> Apply functional-style naming pattern to mutation.ts

packages/firestore/package.json, packages/firestore/rollup.config.debug.js
Adding a new build configuration to both simplify and speed up browser-based testing.
=> Add yarn build:debug

packages/auth/src/api/index.test.ts, packages/auth/src/api/index.ts, packages/auth/src/core/errors.ts, packages/auth/src/core/util/assert.test.ts, packages/auth/src/core/util/assert.ts, packages/auth/src/platform_browser/strategies/popup.ts, packages/auth/src/platform_browser/strategies/redirect.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/5420
We now provide better messaging in cases where auth is imported from multiple entry points, leading to mismatched types. Also small update for https://github.com/firebase/firebase-js-sdk/pull/5423; we now incorporate the message onto the error itself (as it should have been originally, thanks @lisajian for pointing that out)
=> [Auth] Add custom error factory for custom messages; add special handling for instanceof checks

.changeset/small-scissors-try.md, packages/firestore/src/lite-api/reference.ts, packages/firestore/test/lite/integration.test.ts
=> Fix the implementation of `collection()` with multiple path segments.

packages/app-compat/package.json
This must have been overlooked somehow when cleaning out the scripts/exp directory and all references to it.
=> Fix path typo in npm script

packages/functions/src/context.ts
See https://github.com/FirebaseExtended/flutterfire/issues/6794
This is a change being made across Android, iOS, and Web.
=> Don't send dummy App Check token to functions endpoint

.changeset/slimy-penguins-itch.md, packages/auth/src/api/authentication/idp.ts, packages/auth/src/api/authentication/mfa.ts, packages/auth/src/api/authentication/sms.ts, packages/auth/src/core/errors.ts, packages/auth/src/core/util/version.ts, packages/auth/src/model/auth.ts, packages/auth/src/model/enums.ts, packages/auth/src/model/id_token.ts, packages/auth/src/model/popup_redirect.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/5451
Mark some internal types as `@internal` to prevent `const enum`s from accidentally showing up in the public typing file.
=> Remove Auth internal types from the public typings

.changeset/tender-pumpkins-love.md, common/api-review/storage.api.md, packages/storage/src/api.ts, packages/storage/src/implementation/metadata.ts, packages/storage/src/implementation/requests.ts, packages/storage/src/implementation/url.ts, packages/storage/src/service.ts, packages/storage/test/unit/location.test.ts, packages/storage/test/unit/requests.test.ts, packages/storage/test/unit/service.test.ts
I tried to avoid adding another property to the service in the initial emulator PR by having some logic in `makeUrl` to deal with the fact that `host` could contain a protocol or not. Unfortunately `Location.refFromUrl` doesn't use `makeUrl` and this caused a bug where there were duplicate protocol strings in the regex. Trying to keep "host" in a consistent format now to avoid future mistakes, separating "protocol" into a separate field.
Fixes https://github.com/firebase/firebase-tools/issues/3715
=> Add protocol as a separate property for FirebaseStorage service

.changeset/spicy-moose-approve.md, packages/firestore/rollup.shared.js
Mangled terser code is causing some problems seen in Create React App apps. This is a temporary fix that will avoid mangling the specific variable in question. Long term fix is to see if terser will provide an option to mangle properties without mangling anything else (currently not available), and/or find out what downstream build tool is causing this bug and get them to fix it.
Details:
The `initializeFirestore()` function, when mangled by terser, has two variables with the same name in different scopes (one is an import, one is a `const` in an `if` block). This seems to confuse one of the tools in the Create React App production default build pipeline (Babel?). The code is converted to ES5, which makes the `const` a `var`, which puts both variables sharing a name into the same scope. …
=> Temporary hack to fix terser output

.github/workflows/release.yml
This works in tandem with a change to the internal `release-cli` script (that branch is currently named `custombranch`).
The change to that script is, if publishing from `master`, the release branch is named `release`. If publishing from any other branch, the release branch is named `[branch name]-releasebranch`. I was going to make the suffix `-release` but I did a search and it's not uncommon to end dev branches with `-release` if we're working on the release process. So trying to make something more unique.
=> Allow publishing from any branch

.changeset/bump-sdk-version.md, scripts/ci/add_changeset.ts
`@firebase/app` should be published on every release. The script to automatically do this was failing because `yarn changesets status` couldn't find the `master` branch locally, because actions/checkout doesn't check it out locally. After reproducing locally, it does seem to be able to access `origin/master`, so changed it to that.
=> Fix workflow that automatically publishes @firebase/app

.changeset/neat-pants-wonder.md, common/api-review/auth.api.md, packages/auth/src/platform_browser/mfa/assertions/phone.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/5480
We were missing the static `FACTOR_ID` field that is [present in v8](https://firebase.google.com/docs/reference/js/v8/firebase.auth.PhoneMultiFactorGenerator#static-factor_id)
=> [Auth] Add phone factor ID to the PhoneMultiFactorGenerator object

.changeset/fast-brooms-tie.md, packages/rules-unit-testing/src/public_types/index.ts
Fixes a typescript issue found in https://github.com/firebase/firebase-js-sdk/discussions/4715#discussioncomment-1284818
=> Fix RUTv2 compat instances not working with modular.

.changeset/fast-brooms-tie.md, .changeset/little-foxes-own.md, packages/rules-unit-testing/src/impl/test_environment.ts, packages/rules-unit-testing/src/public_types/index.ts
See changeset and comment for context.
=> Fix RUTv2 not setting RTDB namespace by default.

.github/workflows/release.yml, scripts/ci/add_changeset.ts
I did it wrong. --since does not do what I expected. We need to explicitly pull master and use the regular `yarn changeset status` command.
https://github.com/atlassian/changesets/issues/517
=> Fix app release again

.changeset/curly-elephants-cover.md, packages/auth/src/core/user/user_impl.test.ts, packages/auth/src/core/user/user_impl.ts, packages/auth/src/platform_browser/persistence/local_storage.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/5430
Also clean up the typescript in the local_persistence file
=> [Auth] Fix bug in Auth where emailVerified wasn't set in the user constructor

.gitignore, scripts/docgen-compat/content-sources/js/toc.yaml, scripts/docgen-compat/content-sources/node/toc.yaml, scripts/docgen-compat/generate-docs.js
Small path fixes and add 2 pages to the TOC that were missing. These additions were before the v9 release but we had not updated the TOC. Will also update and re-run the g3 script after this is checked in.
=> Clean up compat docgen

.changeset/blue-rice-ring.md, common/api-review/remote-config.api.md, packages/firebase/compat/index.d.ts, packages/remote-config-compat/src/index.ts, packages/remote-config-compat/src/remoteConfig.ts, packages/remote-config/src/api2.ts, packages/remote-config/src/errors.ts, packages/remote-config/src/register.ts, packages/remote-config/src/storage/storage.ts
Issue 2393 fix for Remote-Config module.
Added `isSupported` method where users can call to check if indexedDB is supported before initializing the module. 
Fixes https://github.com/firebase/firebase-js-sdk/issues/5502
=> Add environment check to Remote-Config Module

.changeset/swift-shirts-appear.md, packages/auth/src/platform_node/index.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/5475
In node, all persistence types now map to inMemory instead of the not-available error
=> [Auth] Make the persistences default to inMemory for node

.changeset/angry-moons-change.md, .changeset/lazy-bulldogs-tickle.md, .changeset/ninety-lions-report.md, .changeset/sixty-flowers-melt.md, packages/firestore/src/local/simple_db.ts, packages/firestore/test/integration/util/helpers.ts, packages/messaging-compat/src/messaging-compat.ts, packages/messaging/src/api/isSupported.ts, packages/performance/src/services/api_service.ts, packages/util/src/environment.ts
`isSupported()` had bugs in messaging, performance, and analytics.
* in messaging, isSupported was not checking for the existence of window or indexedDB before validating that indexedDB is openable
* in performance and analytics, navigator was not being checked for correctly `!navigator` should be `typeof navigator !== 'undefined` since it's a global. This led to runtime failures.
* further I dry'd up performance and messaging to use the same `areCookiesEnabled` test
Further, the indexedDb check was not working correctly in AppCheck due to checking for it on `self` (which isn't available in all environments). I addressed this and dry'd up our `typeof indexedDb` checks to all use `isIndexedDBAvailable()`.
=> isSupported fixes

repo-scripts/prune-dts/tsconfig.eslint.json, repo-scripts/prune-dts/tsconfig.json
Relaxing the pattern to match all d.ts files to allow them to be trimmed. The original pattern was too specific and didn't match the typings file `public.d.ts` in `@firebase/database`, so it was not trimmed.
=> trim all d.ts files in dist folder

packages/app-check/src/api.test.ts, packages/app-check/src/api.ts, packages/app-check/src/debug.ts, packages/app-check/src/index.ts, packages/app-check/src/state.ts, packages/app-check/src/storage.ts
Initialize debug mode for App Check (i.e., reading the global var) in the first call to `initializeAppCheck()` instead of when the app-check component is registered. This makes it easier for developers to set the variable in code.
Additionally, it logs a `console.warn` on subsequent calls to initializeAppCheck notifying the user they are still in debug mode, and logging the token (if they don't reload/quit before that token promise resolves). This may help HMR users who lose the initial token message.
=> Initialize App Check debug mode in initializeAppCheck

.changeset/heavy-books-mate.md, .changeset/wet-queens-tell.md, config/webpack.test.js, packages/firestore/src/util/input_validation.ts, packages/logger/package.json, packages/logger/rollup.config.js, packages/util/package.json, packages/util/rollup.config.js, packages/webchannel-wrapper/package.json
Esm2017 is the default build for v9 libraries. Changing util libraries to use esm2017 by default.
=> use esm2017 builds by default

.changeset/swift-items-prove.md, packages/auth/src/api/authentication/email_and_password.ts, packages/auth/src/core/strategies/action_code_settings.ts, packages/auth/src/core/strategies/email.test.ts, packages/auth/src/core/strategies/email_and_password.test.ts, packages/auth/src/core/strategies/email_link.test.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/5541
We were sending `iosBundleId` instead of `iOSBundleId`, which was causing incorrect behavior.
=> [Auth] Fix incorrectly-cased parameter in OOB request

.github/workflows/check-changeset.yml, .github/workflows/release.yml, scripts/ci/check_changeset.ts
The option doesn't do what I thought it did, it should be calling the normal `changeset status` command. It just needs to explicitly pull master first so that the command doesn't fail.
`--no-rebase` avoids the warning message of not specifying a default merge strategy while selecting what would have been the default anyway.
=> Fix changeset checker to stop using since option

repo-scripts/changelog-generator/index.ts
Github has been warning about deprecation of the `access_token` query param and asking users to use the `Authorization` header instead.
=> Use Authorization header instead of access_token for Github call

.changeset/tame-owls-deny.md, packages/auth-compat/src/user_credential.ts
Hopefully to address b/198623196
=> [Auth] Switch compat UserCredential function to use promise chaining instead of async/await

packages/webchannel-wrapper/gulpfile.js
The new `ALLOW_ORIGIN_TRIAL_FEATURES` option was added to Closure in [this commit](https://github.com/google/closure-library/commit/23314e6077b4b7fb25bd9600a66480529e0ead1f).
Having this flag will save ~1.74 KB in the webchannel wrapper JS bundle compared with not having it (with the next Closure release).
=> Disable Origin Trial code in WebChannel to reduce JS bundle size.

packages/app-check/src/types.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/5569
The two public facing providers (Custom and RecaptchaV3) implement an internal interface `AppCheckProvider` but they hide some of their public methods, causing them to be inconsistent with the internal interface.
If I tag `AppCheckProvider` `@internal`, the "implements AppCheckProvider" is still there on the two public types and there's an error because it can't find it.
I don't want to get rid of the "implements" because it is a helpful check in the internal code.
=> Fix App Check typings

.changeset/itchy-snails-give.md, common/api-review/auth.api.md, packages/auth/src/core/credentials/oauth.test.ts, packages/auth/src/core/credentials/oauth.ts, packages/auth/src/core/providers/oauth.test.ts, packages/auth/src/core/providers/oauth.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/5553
The field wasn't being carried through to the final object properly. This change also makes the `nonce` field in the OAuthCredential object fully private---it is not documented or exposed in any of the other SDKs
=> [Auth] Fix OAuth credential issue with nonce fields

.changeset/curvy-roses-press.md
https://github.com/firebase/firebase-js-sdk/pull/5570 was merged without a changeset.
=> Add changeset for #5570

.changeset/wild-vans-camp.md, packages/app-check-compat/src/index.ts, packages/app-check-compat/src/service.test.ts, packages/app-check-compat/src/service.ts, packages/firebase/compat/index.d.ts
Not sure how this was overlooked but the special provider classes were not exported on the firebase.appcheck object and `activate` was not set up to process them.
=> Fix app-check-compat providers

.changeset/twelve-scissors-wink.md, packages/auth/src/core/user/user_impl.test.ts, packages/auth/src/core/user/user_impl.ts
There was a bug in the `user._clone()` method where the tenantId wasn't getting carried over to the new object.
=> [Auth] Fix tenantId field when setting user via updateCurrentUser

.changeset/curvy-peaches-deliver.md, packages/storage/src/implementation/connection.ts, packages/storage/src/implementation/request.ts, packages/storage/src/platform/node/connection.ts, packages/storage/test/browser/connection.test.ts, packages/storage/test/unit/connection.test.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/5372
We should not throw from `connection.send` to enable retries.
=> Do not throw from connection.send in Node.js

.changeset/thirty-rats-worry.md, packages/auth/src/core/auth/auth_impl.ts, packages/auth/src/platform_browser/auth.test.ts, packages/auth/test/integration/webdriver/persistence.test.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/5685
=> [Auth] Fix double-onAuthStateChanged call bug

.changeset/ten-impalas-wink.md, common/api-review/app-check.api.md, packages/app-check-compat/src/index.ts, packages/app-check-compat/src/service.ts, packages/app-check/src/api.test.ts, packages/app-check/src/api.ts, packages/app-check/src/client.test.ts, packages/app-check/src/client.ts, packages/app-check/src/constants.ts, packages/app-check/src/internal-api.test.ts, packages/app-check/src/providers.ts, packages/app-check/src/public-types.ts, packages/app-check/src/recaptcha.test.ts, packages/app-check/src/recaptcha.ts, packages/app-check/src/util.ts, packages/app-check/test/util.ts, packages/firebase/compat/index.d.ts
Add `ReCaptchaEnterpriseProvider` and associated methods to `app-check` and `app-check-compat`.
E2E tests were successful.
We want to coordinate the release with iOS/Android, do not merge until the coordinated date (TBD).
=> Implement ReCaptchaEnterprise for App Check

.changeset/dry-toes-hammer.md, .changeset/short-mice-itch.md, common/api-review/firestore-lite.api.md, common/api-review/firestore.api.md, packages/firestore/src/lite-api/reference.ts, packages/firestore/test/lite/integration.test.ts
Fixes #5661. Thanks @gustavohenke for proactively bringing up the fix!
This change allows developers to pass an object of type `T` into `WithFieldValue<T>`.
=> Allow type T in WithFieldValue<T>

packages/firestore/test/lite/integration.test.ts
Converters should allow `setDoc()` to be called with primitive types, as long as the provided converter converts the primitive to an object that matches `DocumentData`.
=> Add regression tests to support primitive values in converters

.changeset/witty-kids-buy.md, packages/auth/src/platform_browser/iframe/iframe.test.ts, packages/auth/src/platform_browser/iframe/iframe.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/5631
This is a follow-up to https://github.com/firebase/firebase-js-sdk/pull/5633/files. There was still an issue with lighthouse until we add tabindex=-1 to the iframe as well
=> [Auth] Add tabindex=-1 to iframe to fix issue with aria-hidden

.changeset/cool-toys-marry.md, packages/functions/src/service.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/5692
=> clear pending timeout after promise.race

.changeset/tame-beans-study.md, packages/storage/src/implementation/backoff.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/5628
=> clear the global timeout once an operation is done in the Storage SDK

.changeset/lovely-bobcats-punch.md, packages/firestore/src/local/indexeddb_persistence.ts
This PR changes our IndexedDB shutdown to skip all remaining work items on Safari 15. It is believed that writing to IndexedDB during unload can trigger a bug on Safari that prevents IndexedDB from loading during the next page load.
Fixes https://github.com/firebase/firebase-js-sdk/issues/5716 (Which is just extending https://github.com/firebase/firebase-js-sdk/issues/4076)
=> Skip IndexedDB cleanup on Safari 15

packages/auth/demo/README.md, packages/auth/demo/package.json, packages/auth/demo/src/index.js
As the title implies^^, a quick addition to run against the Auth Emulator
`yarn run demo:emulator`
N/A
=> Added instructions for running auth demo against emulator

.github/workflows/health-metrics-presubmit.yml, .github/workflows/health-metrics-pull-request.yml, .github/workflows/health-metrics-release.yml
Add a GitHub Actions workflow file for submitting the tags information (name, commit sha1) to the SDK metric service.
The action is open sourced at https://github.com/FirebaseExtended/github-actions/tree/master/health-metrics/release-diffing.
The bundle definitions are to be added in #5706.
=> Add GHA workflow for submitting tags to metric service.
