.changeset/quick-experts-shave.md, packages/firestore/rollup.config.js
Generate polyfill for Nodejs only.
Partially fixes https://github.com/firebase/firebase-js-sdk/issues/5687 (or rather just hide the problem that Jest will load Nodejs bundles as if it is testing in browser)
=> better meta url polyfill

.changeset/famous-houses-retire.md, packages/storage/src/reference.ts, scripts/build/create-overloads.ts
Add NodeJS.ReadableStream to excluded builtin types in the compat overloads script. Maybe there's a more robust way to address this, or can look into it later.
Also fix some type errors in storage.
=> Exclude NodeJS.ReadableStream from compat overloads

packages/firestore/rollup.config.js, packages/firestore/test/unit/specs/describe_spec.ts
This fixes the endless saga of 
```
[!] (plugin rpt2) Error: ENOENT: no such file or directory, open '/Users/mrschmidt/GitHub/firebase/firebase-js-sdk/packages/firestore/node_modules/.cache/rollup-plugin-typescript2/rpt2_7887a05285f2ead33e6e00d96643596dbe46f0d0/code/cache_/1e43392417c9b6c95b07e7f45d8c498c15e959c1'
```
for me. We don't need to clean the cache since each build has its own directory.
=> Fix caching errors during Firestore build

.changeset/red-actors-care.md, packages/auth/src/core/auth/auth_impl.ts, packages/auth/src/platform_browser/auth.test.ts, packages/auth/src/platform_browser/iframe/gapi.test.ts, packages/auth/src/platform_browser/iframe/gapi.ts, packages/auth/src/platform_browser/popup_redirect.test.ts, packages/auth/src/platform_browser/popup_redirect.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/5720
In proactive initialization for the popup/redirect resolver, Auth initialization should not fail if there's a network error (i.e. in the case of offline-mode).
=> [Auth] Fix halted initialization when proactive popup resolver init fails

packages/auth/demo/src/index.js
* Add TODO for unused custom parameters
* Uncommented logic for sign in with SAML providers
Corresponding internal bug: b/192387796
Verified that OIDC/SAML happy cases work against head of Auth Emulator mainline. Followed instructions for running against emulator ([here](https://github.com/firebase/firebase-js-sdk/tree/master/packages/auth/demo#running-against-auth-emulator)). See videos of sign in flows:
* [go/firebase-jssdk-5776-oidc](http://go/firebase-jssdk-5776-oidc) - signs in with OIDC provider
* [go/firebase-jssdk-5776-saml](http://go/firebase-jssdk-5776-saml) - signs in with SAML provider
N/A
=> Verify OIDC/SAML sign in against Auth Emulator

packages/util/test/object.test.ts
Remove accidental `describe.only` in packages/util tests.
=> Remove describe.only

packages/firebase/compat/index.d.ts
Should fix the CI errors on passthrough feature branch (e.g. https://github.com/firebase/firebase-js-sdk/runs/4411661246?check_suite_focus=true). Didn't auto-gen the index.d.ts and instead added it manually.
Corresponding internal bug: b/192699639
Changes are in accordance with: go/custom-auth-passthrough-sdk#heading=h.t4hz4i7fojar
=> Fix build error for missing functions on compat Auth

packages/firestore/rollup.config.js, packages/firestore/src/platform/node/grpc_connection.ts
Hardcode the grpc-js version used for logging. This isn't ideal, as getting the version at runtime provides the most accurate version for metrics and debugging, but working around problems with import.meta.url in ESM Node builds while ensuring CJS Node builds still work is causing a lot of problems. Make a TODO to change back to getting runtime version when there is a better way to support it across CJS and ESM Node builds.
See issues:
https://github.com/firebase/firebase-js-sdk/issues/5752
https://github.com/firebase/firebase-js-sdk/issues/5687
And PR:
https://github.com/firebase/firebase-js-sdk/pull/5532
=> Hardcode grpc-js version

packages/auth-compat/test/integration/flows/custom.test.ts, packages/auth/test/integration/flows/custom.local.test.ts
Copied over integration passthrough integration tests (from https://github.com/firebase/firebase-js-sdk/pull/5361) over to compat layer. Additional changes include:
* Adding TODO's to enable tests once passthrough launches
* Remove unneeded timeout from all integ tests
Corresponding internal bug: b/192699639
To test `auth-compat/`:
* Built emulator suite locally `npm run build` from `firebase-tools/`
* Change `xit` to `it`
* From `packages/auth-compat/` ran `node /Users/lisajian/dev/firebase-tools/lib/bin/firebase emulators:exec --project demo-emulatedproject --only auth "yarn run-s test:browser:integration test:node:integration test:webdriver"` (was having a little trouble with `yarn test:integration` b/c it wasn't picking up my local emulator build)
To test `auth/`:
* Same first two …
=> Add passthrough compat integration tests

.changeset/cuddly-birds-stare.md, packages/auth-compat/src/auth.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/5791
=> [Auth] Fix persistence selection in compatibility layer in worker scripts

.github/CODEOWNERS
Remove @Feiyang1 and @hiranya911 from CODEOWNERS file. They are not removed from the comment under `@firebase/jssdk-global-approvers` because that's just a comment listing who is in that team, whose actual membership is managed elsewhere in Github.
We can delay removing them from that team for now, and they'll still be able to approve requests if needed as part of the team, but won't get notifications for every PR. Will file a separate internal bug when the time comes to remove them from the jssdk-global-approvers team if needed.
=> Remove departing team members from codeowners

packages/firestore/src/lite-api/reference_impl.ts, packages/firestore/src/lite-api/transaction.ts, packages/firestore/src/lite-api/write_batch.ts
Addresses firebase/firebase-js-sdk#5818
=> docs: add @throws API comment for CRUD methods

packages/firestore/src/lite-api/reference.ts
Addresses firebase/firebase-admin-node#987
=> docs: improve documentation for merge behavior

packages/firestore/src/index/directional_index_byte_encoder.ts, packages/firestore/src/index/firestore_index_value_writer.ts, packages/firestore/src/index/index_byte_encoder.ts, packages/firestore/src/index/ordered_code_writer.ts, packages/firestore/src/model/values.ts
This ports:
https://github.com/firebase/firebase-android-sdk/blob/master/firebase-firestore/src/main/java/com/google/firebase/firestore/index/DirectionalIndexByteEncoder.java
https://github.com/firebase/firebase-android-sdk/blob/master/firebase-firestore/src/main/java/com/google/firebase/firestore/index/FirestoreIndexValueWriter.java
https://github.com/firebase/firebase-android-sdk/blob/master/firebase-firestore/src/main/java/com/google/firebase/firestore/index/IndexByteEncoder.java
=> Port IndexValueWriter

.changeset/big-otters-reply.md, common/api-review/firestore-lite.api.md, common/api-review/firestore.api.md, common/api-review/storage.api.md, packages/firestore/src/util/error.ts, packages/storage/src/implementation/error.ts, packages/util/src/errors.ts, repo-scripts/prune-dts/.run/AllTests.run.xml, repo-scripts/prune-dts/extract-public-api.ts, repo-scripts/prune-dts/prune-dts.ts, repo-scripts/prune-dts/tests/error.input.d.ts, repo-scripts/prune-dts/tests/error.output.d.ts
This changes FirestoreError to extend FirebaseError and updates the "Prune DTS" script to not remove this change again.
As part of this, I added a new test to "Prune DTS" and added a test runner for IntelliJ/WebStorm.
Fixes https://github.com/firebase/firebase-js-sdk/issues/5754
=> Change FirestoreError to extend FirebaseError

packages/auth/src/core/strategies/custom_token.test.ts, packages/auth/src/core/strategies/custom_token.ts
As the title implies - USER_MISMATCH is a more descriptive error code than INTERNAL_ERROR. This will also be reflected in iOS and Android.
Corresponding internal bug: b/192699639
* `yarn test:browser:unit` passes
=> Update mismatching UID error code to USER_MISMATCH

packages/util/package.json, packages/util/src/errors.ts
This fixes https://github.com/firebase/firebase-js-sdk/blob/b835b4cbabc4b7b180ae38b908c49205ce31a422/packages/firestore/src/local/simple_db.ts#L532
=> Fix Firestore compile

packages/firestore/rollup.config.js
Hack to fix for Vercel while not re-breaking for Jest.
=> Add jest exception

packages/firestore-compat/.idea/runConfigurations/Integration_Tests__Emulator_.xml, packages/firestore-compat/babel-register.js, packages/firestore-compat/babel.config.json, packages/firestore-compat/karma.conf.js, packages/firestore-compat/package.json, packages/firestore-compat/test/array_transforms.test.ts, packages/firestore-compat/test/batch_writes.test.ts, packages/firestore-compat/test/bootstrap.ts, packages/firestore-compat/test/bundle.test.ts, packages/firestore-compat/test/cursor.test.ts, packages/firestore-compat/test/database.test.ts, packages/firestore-compat/test/fields.test.ts, packages/firestore-compat/test/get_options.test.ts, packages/firestore-compat/test/numeric_transforms.test.ts, packages/firestore-compat/test/query.test.ts, packages/firestore-compat/test/server_timestamp.test.ts, packages/firestore-compat/test/smoke.test.ts, packages/firestore-compat/test/transactions.test.ts, packages/firestore-compat/test/type.test.ts, packages/firestore-compat/test/util/equality_matcher.ts, packages/firestore-compat/test/util/events_accumulator.ts, packages/firestore-compat/test/util/firebase_export.ts, packages/firestore-compat/test/util/helpers.ts, packages/firestore-compat/test/util/promise.ts, packages/firestore-compat/test/util/settings.ts, packages/firestore-compat/test/validation.test.ts
This adds explicit integration tests for Firestore Compat, as I am rewriting the existing integration tests to use the v9 API. Most of the files are just copied. Exceptions are noted.
=> Add explicit tests for Compat

.github/ISSUE_TEMPLATE/bug_report.md, packages/firestore/rollup.config.js
This changes the manual replacement code to produce the exact output I got in 9.2:
```
url.fileURLToPath((typeof document === 'undefined' ? new (require('url').URL)('file:' + __filename).href : (document.currentScript && document.currentScript.src || new URL('index.node.cjs.js', document.baseURI).href)));
```
Fixes https://github.com/firebase/firebase-js-sdk/issues/5823
=> Fix Vercel build

.changeset/unlucky-bottles-wait.md, packages/messaging/src/helpers/externalizePayload.test.ts, packages/messaging/src/helpers/externalizePayload.ts, packages/messaging/src/helpers/logToFirelog.ts, packages/messaging/src/interfaces/internal-message-payload.ts, packages/messaging/src/listeners/sw-listeners.test.ts
Message Id  is passed down to the SDK as camel case as opposed to snake case.
The previous implementation resulted `mid=null` for all messages.
=> Fix message id parsing

.changeset/selfish-pots-fetch.md, packages/firestore/rollup.config.js, packages/firestore/rollup.config.lite.js, packages/firestore/src/platform/node/load_protos.ts, packages/firestore/src/protos/google/api/annotations.proto, packages/firestore/src/protos/google/api/http.proto, packages/firestore/src/protos/google/firestore/v1/common.proto, packages/firestore/src/protos/google/firestore/v1/document.proto, packages/firestore/src/protos/google/firestore/v1/firestore.proto, packages/firestore/src/protos/google/firestore/v1/query.proto, packages/firestore/src/protos/google/firestore/v1/write.proto, packages/firestore/src/protos/google/rpc/status.proto, packages/firestore/src/protos/google/type/latlng.proto, packages/firestore/src/protos/protos.json, packages/firestore/src/protos/update.sh
This changes the Firestore SDK to load protos from JSON, which gets bundled directly into the source file. This should fix a bunch of problems with JS environments that use Node sources + Bundlers.
=> Load Protos from JSON

.changeset/slow-bobcats-clap.md, packages/messaging/package.json, packages/messaging/rollup.config.js, packages/messaging/sw/package.json
Although the messaging SW shouldn't technically have a Node version as SW's don't run in Node, some SSR applications generate pages in Node to be later loaded in the browser, and these builds break when they can't find a CJS version. This can also be fixed by adding an ESM Node version, but that can't currently be done until we update the `idb` dependency (see https://github.com/firebase/firebase-js-sdk/issues/5839). Adding a CJS build for now.
See https://github.com/firebase/firebase-js-sdk/issues/5854
=> Add CJS build for messaging/sw

.changeset/moody-ways-learn.md, packages/auth/src/api/index.test.ts, packages/auth/src/api/index.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/5874
The error being thrown when the network timed out was not the correct one to use.
=> [Auth] Fix error code thrown when the network errors out

scripts/ci/log-changesets.js, scripts/ci/notify-test-result.js
Error in script that logs E2E test status to the release tracker.
Added proper error handling to all `req.write` calls in CI scripts (all related to logging release status info to the release tracker functions backend).
=> Fix CI release tracker script errors

.changeset/happy-tools-wonder.md, packages/messaging-compat/package.json, packages/messaging/package.json
This change will direct all Node consumers of messaging, messaging-compat, and messaging/sw to the respective CJS bundles, regardless of whether they are using `require` or `import`. We cannot currently provide ESM Node bundles for messaging until we are able to upgrade our `idb` dependency, so we need to point all Node applications to the CJS bundles.
Once we are unblocked on upgrading `idb` (which entails officially dropping IE support, PR https://github.com/firebase/firebase-js-sdk/pull/5857), we can create Node ESM bundles for messaging and separate the `exports.node` entry point into `exports.node.require` (cjs) and `exports.node.import` (mjs) entry points.
See issue https://github.com/firebase/firebase-js-sdk/issues/5839.
=> Set Messaging to use only CJS bundles if Node

packages/auth/package.json
Seems like it needs the exact file path in "exports". See the `firebase/messaging/sw` path for the same pattern:
https://github.com/firebase/firebase-js-sdk/blob/c5d8f6595e1344612dd84732d366912bd416d503/packages/messaging/package.json#L19
That one is split into 3 because it has a Node version.
Fixes https://github.com/firebase/firebase-js-sdk/issues/5878
=> Add cordova and rn export paths to auth

.changeset/gold-geckos-carry.md, packages/auth-compat/src/auth.test.ts, packages/auth-compat/src/persistence.ts, packages/auth-compat/src/platform.ts
Issue: https://github.com/firebase/firebase-js-sdk/issues/5913
This also appears in database, so I won't be closing out the issue with this PR
=> [Auth] Fix errors when cookies are disabled in Chrome (compat layer)

.changeset/yellow-suns-clean.md, packages/auth/index.rn.ts
Changeset for https://github.com/firebase/firebase-js-sdk/pull/5739
=> Add changeset for PR #5739

.changeset/happy-badgers-leave.md, packages/firestore/src/core/firestore_client.ts, packages/firestore/src/remote/remote_store.ts
=> Re-establish streams when App Check token expires.

.changeset/curvy-brooms-clean.md, packages/auth/src/core/user/user_impl.test.ts, packages/auth/src/core/user/user_impl.ts, packages/auth/src/model/user.ts
Fixes https://github.com/firebase/firebaseui-web/issues/917.
I also updated all the fields on `UserImpl` to not have a default constructor, so in future we'll get type errors if one of the fields isn't properly initialized by the parameters. (We also ran into this issue with tenantId).
=> [Auth] Add missing initializer for providerData to UserImpl

packages/performance/src/resources/trace.test.ts, packages/performance/src/resources/trace.ts
Fix for Fireperf counter value might be null
=> Fix for Fireperf counter value might be null

packages/auth/src/api/authentication/email_and_password.test.ts, packages/auth/src/api/authentication/email_and_password.ts, packages/auth/src/api/authentication/sign_up.test.ts, packages/auth/src/api/authentication/sign_up.ts, packages/auth/src/api/index.ts
This PR updates the 4 email auth apis (sign in, sign up, password reset, email link sign in) to support recaptcha enterprise.
Base apis and types update
- Backend API updates - https://github.com/firebase/firebase-js-sdk/pull/5942
- Public API and internal support types
- New backend error types
Core logic
- Implement getRecaptchaConfig API
- Implement recaptcha enterprise verifier
- Wire recaptcha enterprise verifier to email auth flows
=> Update backend apis

packages/firestore/src/core/sync_engine_impl.ts, packages/firestore/src/local/indexeddb_lru_delegate_impl.ts, packages/firestore/src/local/memory_persistence.ts
... why does this not break the build!? No one knows.
=> Fix compilation for MemoryRemoteDocumentCache

scripts/ci/notify-test-result.js
=> Fix e2e notify script again

packages/auth/index.doc.ts, packages/auth/src/model/public_types.ts
Add `getReactNativePersistence` to the special index file we use only for generating docs (which includes methods from environments that shouldn't go together in one bundle).
Also add `@public` tag to MultiFactorPhoneInfo, this just gets rid of a warning as the api-extractor seems to default to public anyway.
=> Add getReactNativePersistence to docs

.changeset/tame-apes-tie.md, packages/messaging-compat/src/messaging-compat.ts, packages/messaging/src/api/isSupported.ts
Wrap `validateIndexedDBOpenable()` in a try/catch. Add a comment to the equivalent function in messaging-compat to remind us of why we can't add this check there.
Fixes https://github.com/firebase/firebase-js-sdk/issues/5868
=> Fix isWindowSupported() check

packages/firestore/src/local/indexeddb_schema.ts, packages/firestore/src/local/indexeddb_schema_converter.ts, packages/firestore/test/unit/local/indexeddb_persistence.test.ts
Port of https://github.com/firebase/firebase-ios-sdk/pull/9268
=> Add Index Schema

packages/firestore/src/local/index_manager.ts, packages/firestore/src/local/indexeddb_index_manager.ts, packages/firestore/src/local/memory_index_manager.ts
This PR ports the new APIs for IndexManager.
=> Port IndexManager APIs

packages/auth/src/model/public_types.ts, packages/auth/src/platform_react_native/persistence/react_native.ts
Errors caught in review when generating new docs pages. See internal cl/425742150
api-documenter doesn't allow referencing members of an enum, causing there to just be a blank space in the documentation text where `{@link FactorId.PHONE}` should be, so I moved the `.PHONE` out of the link.
=> Fix documentation

packages/firestore/src/api/snapshot.ts
Clarifying that this is a method, not a property (as it was in v8)
Thanks!
=> Revise comment for exists()

packages/auth/src/platform_browser/auth_window.ts, packages/auth/src/platform_browser/recaptcha/recaptcha.test.ts, packages/auth/src/platform_browser/recaptcha/recaptcha.ts, packages/auth/src/platform_browser/recaptcha/recaptcha_enterprise_verifier.test.ts, packages/auth/src/platform_browser/recaptcha/recaptcha_enterprise_verifier.ts, packages/auth/src/platform_browser/recaptcha/recaptcha_loader.ts, packages/auth/src/platform_browser/recaptcha/recaptcha_mock.ts
This PR implements the new recaptcha enterprise verifier.
Not that it resolves the conflicts with existing recaptcha v2 and recaptcha v3 & enterprise from App check.
Base apis and types update
- https://github.com/firebase/firebase-js-sdk/pull/5942
- https://github.com/firebase/firebase-js-sdk/pull/5943
- New backend error types
Core logic
- Implement getRecaptchaConfig API
- This PR - https://github.com/firebase/firebase-js-sdk/pull/5964
- Wire recaptcha enterprise verifier to email auth flows
=> Add recaptcha enterprise verifier

.changeset/green-parents-compare.md, packages/firestore/src/local/simple_db.ts
See https://docs.google.com/presentation/d/e/2PACX-1vRFevPoyBj-ntqpFmD_lRVFcBi7f1Q4fBHWR04UvLniOu_98gfgDPFo7FOv8S27ZBrqgSKexVbz5YE4/pub?start=false&loop=false&delayms=3000&slide=id.g440afe71f7_0_44
=> Use transaction.commit() if available

packages/firestore-compat/tools/console.build.js
This change updates the console.build.js script that is used internally at Google to build the Firestore SDK.
Use of `eval` is removed and instead the code is exported using the global `window`.
=> Update console.build.js to set a value on window

packages/firestore/src/local/indexeddb_remote_document_cache.ts, packages/firestore/src/local/local_documents_view.ts, packages/firestore/src/local/memory_remote_document_cache.ts, packages/firestore/src/local/remote_document_cache.ts, packages/firestore/test/unit/local/counting_query_engine.ts, packages/firestore/test/unit/local/local_store.test.ts, packages/firestore/test/unit/local/remote_document_cache.test.ts, packages/firestore/test/unit/local/test_remote_document_cache.ts
Port of https://github.com/firebase/firebase-android-sdk/pull/3201, which also includes the rationale behind this change.
=> Use RemoteDocumentCache.getAll()

.changeset/late-tables-juggle.md, packages/firestore/src/local/simple_db.ts
getAll() is roughly 20% faster than iterate in my local tests with both Safari/Chrome. We should use getAll() for all large read operations.
=> Use getAll() when available

.github/workflows/test-changed.yml, scripts/ci-test/testConfig.ts
firestore-compat belongs with firestore, auth-compat belongs with auth in the separated test configs for the "test-changed" script. Made sure to exclude them from the "core" config as well.
=> Group firestore-compat and auth-compat properly in test config

packages/firestore/src/index/index_byte_encoder.ts, packages/firestore/src/index/index_entry.ts, packages/firestore/src/local/indexeddb_index_manager.ts, packages/firestore/src/local/indexeddb_schema.ts, packages/firestore/src/local/indexeddb_schema_converter.ts, packages/firestore/src/model/document_key.ts, packages/firestore/src/util/sorted_set.ts, packages/firestore/test/unit/local/index_manager.test.ts, packages/firestore/test/unit/util/sorted_set.test.ts
This ports the `updateEntries` code from Android.
=> IndexeddbIndexManager.updateEntries()

packages/firestore/src/platform/node/grpc_connection.ts, packages/firestore/src/platform/node/load_protos.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/5983
=> Use package import for GRPC

packages/firestore/test/unit/local/document_overlay_cache.test.ts
This test was ported from https://github.com/firebase/firebase-ios-sdk/commit/cf04e6740bd371738cd62bed71498838a259e3db, part of https://github.com/firebase/firebase-ios-sdk/pull/9345.
=> document_overlay_cache.test.ts: added a test for updating a document's overlay

packages/firestore/src/core/target.ts, packages/firestore/src/index/index_entry.ts, packages/firestore/src/local/index_manager.ts, packages/firestore/src/local/indexeddb_index_manager.ts, packages/firestore/src/local/memory_index_manager.ts, packages/firestore/src/local/simple_db.ts, packages/firestore/src/model/field_index.ts, packages/firestore/src/model/type_order.ts, packages/firestore/src/model/values.ts, packages/firestore/src/platform/node/base64.ts, packages/firestore/src/util/byte_string.ts, packages/firestore/test/unit/api/bytes.test.ts, packages/firestore/test/unit/local/index_manager.test.ts, packages/firestore/test/unit/local/simple_db.test.ts, packages/firestore/test/unit/local/test_index_manager.ts
This adds all index evaluation logic to the Web SDK and ports all tests from Android. The query logic is mostly the same as Android, with the exception of notIn/notEquals queries which are executed by doing scans across split ranges.
Example:
```
Query q = coll.where("a", ">", 2).where("a", "!=", 3);
Android: SELECT * FROM (SELECT * FROM coll WHERE a > 2) WHERE a != 3
Web: Scan [a>2, a<3] && [a>3, ∞]
```
=> Implement Index Scanning

packages/firestore/src/util/sorted_map.ts, packages/firestore/test/unit/util/sorted_map.test.ts
I happen to be the first person to use `getReverseIterator()` which has a bug.
=> Fix SortedMap's reverse iterator (without start key).

packages/messaging/src/listeners/sw-listeners.ts
To resolve [issue](https://github.com/firebase/firebase-js-sdk/issues/5516)
=> Add `await` to `onBackgroundMessage` callback

packages/firestore/src/local/indexeddb_bundle_cache.ts, packages/firestore/src/local/indexeddb_document_overlay_cache.ts, packages/firestore/src/local/indexeddb_index_manager.ts, packages/firestore/src/local/indexeddb_lru_delegate_impl.ts, packages/firestore/src/local/indexeddb_mutation_batch_impl.ts, packages/firestore/src/local/indexeddb_mutation_queue.ts, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/indexeddb_remote_document_cache.ts, packages/firestore/src/local/indexeddb_schema.ts, packages/firestore/src/local/indexeddb_schema_converter.ts, packages/firestore/src/local/indexeddb_sentinels.ts, packages/firestore/src/local/indexeddb_target_cache.ts, packages/firestore/src/local/local_serializer.ts, packages/firestore/test/unit/local/indexeddb_persistence.test.ts, packages/firestore/test/unit/local/local_serializer.test.ts, packages/firestore/test/unit/local/persistence_transaction.test.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
We use classes for IndexedDB, but really our entries are just plain JSON. This PR changes the code to treat them as JSON, which reduces the overhead of JS classes. This PR is merely meant to reduce SDK size, as we are adding a lot of bytes for indexing.
=> Use interfaces for IndexedDB

.changeset/sweet-pumas-dance.md, packages/app/src/heartbeatService.test.ts, packages/app/src/heartbeatService.ts, packages/app/src/indexeddb.ts, packages/app/src/types.ts
Persist date of last sent heartbeat header, to prevent adding any more entries for that date. This is done by adding a `lastSentHeartbeatDate` to the heartbeat object stored in IndexedDB (and retained in app memory as `this._heartbeatsCache`).
=> Add a last sent date to heartbeat storage

.changeset/proud-otters-tap.md, packages/installations/src/api/get-id.test.ts, packages/installations/src/api/get-id.ts, packages/installations/src/api/get-token.test.ts, packages/installations/src/api/get-token.ts, packages/installations/src/api/on-id-change.ts, packages/installations/src/functions/config.ts, packages/installations/src/functions/create-installation-request.test.ts, packages/installations/src/functions/create-installation-request.ts, packages/installations/src/functions/generate-auth-token-request.test.ts, packages/installations/src/functions/generate-auth-token-request.ts, packages/installations/src/helpers/get-installation-entry.test.ts, packages/installations/src/helpers/get-installation-entry.ts, packages/installations/src/interfaces/installation-impl.ts, packages/installations/src/testing/fake-generators.ts
Replace sending v1 platform logging header with sending new heartbeats header.
Additionally:
- Sending the header to the "createInstallation" endpoint, which happens when an installations ID is registered. Previously it was only being sent to the "authTokens:generate" endpoint, which only happens on the auth token refresh, starting 7 days after registration.
- Adding app ID param to the body sent to the authTokens:generate endpoint.
=> Installations heartbeat implementation

.changeset/polite-donkeys-divide.md, .changeset/pretty-mayflies-worry.md, packages/app-check/src/client.test.ts, packages/app-check/src/client.ts, packages/app-check/src/factory.ts, packages/app-check/src/index.ts, packages/app-check/src/internal-api.ts, packages/app-check/src/providers.ts, packages/app-check/test/util.ts
Replace sending v1 platform logging header with sending new heartbeats header.
Will point at master and add changeset after heartbeat controller PR is merged: https://github.com/firebase/firebase-js-sdk/pull/5723
=> App Check heartbeat implementation

.changeset/neat-olives-punch.md, packages/auth-compat/src/auth.test.ts, packages/auth-compat/src/popup_redirect.test.ts, packages/auth-compat/test/helpers/helpers.ts, packages/auth/demo/src/index.js, packages/auth/src/api/index.ts, packages/auth/src/core/auth/auth_impl.test.ts, packages/auth/src/core/auth/auth_impl.ts, packages/auth/src/core/auth/register.ts, packages/auth/src/platform_browser/auth.test.ts, packages/auth/test/helpers/mock_auth.ts
Implemented in new PR to make it easier since there were a lot of underlying changes to Auth between now and https://github.com/firebase/firebase-js-sdk/pull/5782
Will wait for Rosalyn to merge
=> [Auth] heartbeat implementation

.changeset/seven-dolphins-breathe.md, packages/firestore/externs.json, packages/firestore/src/core/snapshot_version.ts, packages/firestore/src/local/indexeddb_mutation_batch_impl.ts, packages/firestore/src/local/indexeddb_remote_document_cache.ts, packages/firestore/src/local/indexeddb_schema.ts, packages/firestore/src/local/indexeddb_schema_converter.ts, packages/firestore/src/local/indexeddb_schema_legacy.ts, packages/firestore/src/local/indexeddb_sentinels.ts, packages/firestore/src/local/local_documents_view.ts, packages/firestore/src/local/local_serializer.ts, packages/firestore/src/local/memory_remote_document_cache.ts, packages/firestore/src/local/query_engine.ts, packages/firestore/src/local/remote_document_cache.ts, packages/firestore/src/model/field_index.ts, packages/firestore/src/model/path.ts, packages/firestore/test/unit/local/counting_query_engine.ts, packages/firestore/test/unit/local/indexeddb_persistence.test.ts, packages/firestore/test/unit/local/query_engine.test.ts, packages/firestore/test/unit/local/remote_document_cache.test.ts, packages/firestore/test/unit/local/test_remote_document_cache.ts
This changes the schema of the Remote Document Cache to rewrite the primary keys. The keys are now:
[ [prefix path ], collection group, read time, document ]
This allows for efficient scanning of indexed and non-indexed queries using `getAll()`. The PR also adds `getDocumentsFromCollectionGroup`, which means that all functionality required by Indexing is now available.
TODO:
- Benchmark the migration
- Re-write multi tab to use the collectionGroup+ReadTime index
=> RemoteDocumentCache APIs for Indexing

packages/firestore/src/core/bundle.ts, packages/firestore/src/core/bundle_impl.ts, packages/firestore/src/core/component_provider.ts, packages/firestore/src/core/query.ts, packages/firestore/src/core/sync_engine_impl.ts, packages/firestore/src/local/indexeddb_remote_document_cache.ts, packages/firestore/src/local/indexeddb_schema_converter.ts, packages/firestore/src/local/indexeddb_sentinels.ts, packages/firestore/src/local/local_store_impl.ts, packages/firestore/src/local/shared_client_state.ts, packages/firestore/src/local/shared_client_state_schema.ts, packages/firestore/src/local/shared_client_state_syncer.ts, packages/firestore/test/unit/core/query.test.ts, packages/firestore/test/unit/local/indexeddb_persistence.test.ts, packages/firestore/test/unit/local/local_store.test.ts, packages/firestore/test/unit/local/remote_document_cache.test.ts, packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
This drops one index created by https://github.com/firebase/firebase-js-sdk/pull/5988 and changes the multi-tab synchronization to use the collection group read time index. This works pretty well for normal query execution, but needs some adjusting to bundle loading as we don't know the collection groups of the bundles. As such, this PR adds functionality to the bundle loader to persist the names of the affected collection groups in LocalStoragel
=> Use collectionGroupReadTimeIndex for multi-tab synchronization

.changeset/fluffy-tools-thank.md, packages/app-check-compat/package.json
This was overlooked when app-check-compat was created.
=> Add app-check-types as a dependency for app-check-compat

packages/firestore/src/core/target.ts, packages/firestore/src/local/index_manager.ts, packages/firestore/src/local/indexeddb_index_manager.ts, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/indexeddb_schema.ts, packages/firestore/src/local/indexeddb_sentinels.ts, packages/firestore/src/local/memory_index_manager.ts, packages/firestore/src/model/field_index.ts, packages/firestore/test/unit/local/index_manager.test.ts, packages/firestore/test/unit/local/test_index_manager.ts, packages/firestore/test/unit/model/target.test.ts
This adds code to order all query results by document key, which is needed to return the correct result for limit queries.
Port of https://github.com/firebase/firebase-android-sdk/pull/3499
=> Support descending queries

.changeset/eighty-coats-hide.md, packages/database-compat/src/api/Reference.ts, packages/database-types/index.d.ts, packages/firebase/compat/index.d.ts
Fixes #6071. I've also update the return type for the `onComplete` handler that the methods also accept.
I've copied the comments for the `TransactionResult` interface from the corresponding `@firebase/database` package:
https://github.com/firebase/firebase-js-sdk/blob/14ccbadd034e1a702f7d91e70ec14856d445764f/packages/database/src/api/Transaction.ts#L42-L49
=> Updated typings for database methods

.github/workflows/health-metrics-pull-request.yml, .github/workflows/health-metrics-release.yml, .github/workflows/release.yml
Warnings to be fixed:
- https://github.com/firebase/firebase-js-sdk/actions/runs/2042542635
- https://github.com/firebase/firebase-js-sdk/actions/runs/2025417132
=> Resolve warnings on GitHub Actions

packages/database/src/api/Database.ts
Fixes #5789 
This PR adds type checks for `process.env` to avoid `TypeError` when `process.env` is undefined although `process` is defined.
=> fix: Add type check for `process.env`

.changeset/hungry-owls-hide.md, packages/util/src/indexeddb.ts
While the mode parameter is optional, the wrapper method will pass `undefined` into the native method if it is not passed into the wrapper. IE11 interprets this as a mode instead of ignoring it and throws an InvalidAccessError.
Specifying `readonly` as the default (which is the default if the parameter is omitted) prevents IE11 from crashing during initialization.
This PR fixes #6121.
=> Specify readonly as the default indexeddb transaction mode

.changeset/nasty-hairs-knock.md, packages/firestore/src/local/indexeddb_remote_document_cache.ts, packages/firestore/src/local/simple_db.ts, packages/firestore/test/unit/local/remote_document_cache.test.ts, packages/firestore/test/unit/local/simple_db.test.ts, packages/firestore/test/unit/local/test_remote_document_cache.ts
This changes the ordering we user for multi-key lookups to match that of IndexedDB.
Fixes https://github.com/firebase/firebase-js-sdk/issues/6110
=> Fix the ordering of the index-based lookup in getAll(keys)

common/api-review/auth.api.md, packages/auth/src/core/auth/auth_impl.test.ts, packages/auth/src/core/auth/auth_impl.ts, packages/auth/src/core/errors.ts, packages/auth/src/model/public_types.ts
Create `beforeAuthStateChanged()` method per internal design doc [go/firebase-auth-middleware](https://goto.google.com/firebase-auth-middleware).
TODO in a separate PR: implement `onAbort()`.
=> Auth middleware (beforeAuthStateChanged)

packages/firestore/src/core/target.ts, packages/firestore/src/local/index_manager.ts, packages/firestore/src/local/indexeddb_index_manager.ts, packages/firestore/src/local/memory_index_manager.ts, packages/firestore/test/unit/local/index_manager.test.ts, packages/firestore/test/unit/local/test_index_manager.ts
Port of https://github.com/firebase/firebase-android-sdk/pull/3583. The Query engine part of the PR is not ported as we do not yet have the Query Engine changes that require this change.
=> Support plumbing for partial index execution

.changeset/new-gorillas-film.md, packages/app-check/src/client.test.ts, packages/app-check/src/client.ts, packages/app-check/src/constants.ts, packages/app-check/src/internal-api.test.ts
For both reCAPTCHA v3 and reCAPTCHA Enterprise:
1. Updated URL to exchange for an App Check token
2. Updated the response JSON object containing the FAC token
=> Update App Check to v1 from v1beta

packages/firestore/src/core/query.ts, packages/firestore/src/core/view.ts, packages/firestore/src/lite-api/query.ts, packages/firestore/src/lite-api/reference_impl.ts, packages/firestore/src/local/index_manager.ts, packages/firestore/src/local/indexeddb_index_manager.ts, packages/firestore/src/local/indexeddb_schema.ts, packages/firestore/src/local/local_documents_view.ts, packages/firestore/src/local/local_store_impl.ts, packages/firestore/src/local/memory_index_manager.ts, packages/firestore/src/local/query_engine.ts, packages/firestore/src/model/collections.ts, packages/firestore/src/util/misc.ts, packages/firestore/test/unit/core/query.test.ts, packages/firestore/test/unit/local/counting_query_engine.ts, packages/firestore/test/unit/local/index_manager.test.ts, packages/firestore/test/unit/local/query_engine.test.ts, packages/firestore/test/unit/specs/spec_builder.ts
This ports the query engine changes for indexed query execution from Android.
=> Port QueryEngine

packages/firestore/src/core/query.ts, packages/firestore/test/integration/api/query.test.ts
Fix: https://github.com/firebase/firebase-js-sdk/issues/6134
=> Fix a bug with limitToLast and cursors

.changeset/new-bugs-think.md
Amend https://github.com/firebase/firebase-js-sdk/pull/6162 to change version bumps to minor since we're adding a new method and changing the API. My bad for not noticing this when PR was approved.
=> Change functions bump to minor

packages/auth-compat/src/popup_redirect.test.ts, packages/auth-compat/src/popup_redirect.ts, packages/auth/internal/index.ts, packages/auth/src/core/auth/auth_impl.ts, packages/auth/src/core/auth/initialize.test.ts, packages/auth/src/core/strategies/redirect.ts, packages/auth/src/model/popup_redirect.ts, packages/auth/src/platform_browser/auth.test.ts, packages/auth/src/platform_browser/popup_redirect.ts, packages/auth/src/platform_cordova/popup_redirect/popup_redirect.ts, packages/auth/test/helpers/mock_popup_redirect_resolver.ts, packages/auth/test/integration/webdriver/persistence.test.ts, packages/auth/test/integration/webdriver/popup.test.ts, packages/auth/test/integration/webdriver/redirect.test.ts
This change fixes the middleware behavior around redirect. It also ensures that the `auth/login-blocked` error is only thrown when calling `getRedirectResult()` after the library is initialized
=> [Auth] Fix redirect middleware

scripts/docgen-compat/content-sources/js/toc.yaml, scripts/docgen-compat/content-sources/node/toc.yaml
Overlooked adding new items to compat docs toc.yaml:
- Add `ReCaptchaEnterpriseProvider` to JS compat docs.
- Add `TransactionResult` to JS and Node compat docs.
=> Add missing entries to compat toc

package.json, repo-scripts/api-documenter/package.json, yarn.lock
Updating types for js-yaml as mentioned in [pull request 5566](https://github.com/firebase/firebase-js-sdk/pull/5566/files#) for all non-major dependencies.
=> Update types for js-yaml

.github/workflows/merge-release-branch.yml
Manually triggerable workflow that merges release into master. Won't be able to test it until after next release.
=> Add a workflow to merge release into master

common/api-review/auth.api.md, packages/auth/src/core/index.ts
Adding the fn export for middleware #6178
=> Add beforeAuthStateChanged fn export

packages/auth/src/core/index.ts, packages/auth/src/model/public_types.ts
Update some comment text for reference docs.
=> Make some doc comment changes

common/api-review/auth.api.md, packages/auth/src/core/auth/auth_impl.ts, packages/auth/src/core/auth/middleware.test.ts, packages/auth/src/core/auth/middleware.ts, packages/auth/src/core/index.ts, packages/auth/src/model/public_types.ts, packages/auth/test/integration/flows/middleware_test_generator.ts
I've refactored the middleware code to its own class since it got sufficiently complicated with the `onAbort()` callbacks.
=> [Auth] Add onAbort and refactor middleware

e2e/karma.conf.js, e2e/sample-apps/modular.js, e2e/webpack.config.js
I think the E2E tests were failing (https://github.com/firebase/firebase-js-sdk/actions/runs/2278640484) because karma-typescript was trying to grab the cjs module for idb and karma-typescript config doesn't allow specifying module fields preferences. This fixes it locally, will see how it runs on CI after merged.
=> Fix e2e tests

.github/workflows/merge-release-branch.yml
Oops, should be `workflow_dispatch` to allow triggering from Github UI.
=> Update merge release branch workflow trigger

.github/workflows/merge-release-branch.yml
- github-script v6 needs REST APIs to be called with `github.rest` instead of `github`.
- Add an input field so we can put the version into the merge commit message (https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/)
=> Fix API call, add commit message

packages/firestore/src/local/indexeddb_schema_converter.ts, packages/firestore/src/local/local_documents_view.ts, packages/firestore/src/local/local_store_impl.ts, packages/firestore/src/local/overlayed_document.ts, packages/firestore/src/model/mutation.ts, packages/firestore/src/model/mutation_batch.ts, packages/firestore/test/unit/local/local_store.test.ts
See:
https://github.com/firebase/firebase-android-sdk/pull/3623
https://github.com/firebase/firebase-android-sdk/pull/3691
=> Backport overlay bug fixes (Android PR 3691 3623)

packages/auth/src/core/index.ts, packages/auth/src/model/public_types.ts
`error` and `completed` callbacks in `onAuthStateChanged()` and `onIdTokenChanged()` have always been no-op, even since before v9. Changing the docs to reflect this and to mark them as deprecated in preparation for removing them in a future major bump.
- We can't use the actual `@deprecated` tag on a single param, only on an entire function or interface, so I just put the word "Deprecated" in the comment. That means we won't get the big red box that devsite puts on deprecated items: https://firebase.google.com/docs/reference/js/analytics.item I don't think there's a way around it, I don't think devsite can put that box around params either, considering the way params are formatted.
- `packages/auth/src/core/index.ts` is the actual source of truth for the docgen, so copied some comment …
=> Mark Auth error callbacks as deprecated

.changeset/polite-fireants-mate.md, packages/auth-compat/src/platform.ts
No change to current codebase is just addition to make the SDK work as expected in capacitor app, like in Cordova app
=> fix: Auth env detection for capacitor

.github/workflows/e2e-test.yml, .github/workflows/release-staging.yml
Moving as many release tasks as possible out of local script and into Github Actions.
Try creating a workflow for staging first. If all works well, make one for production in a future PR.
- Merge master into release
- Check out release branch
- yarn install
- Add changeset for @firebase/app to ensure that package is always published (this keeps the SDK_VERSION variable current)
- Create release PR (the "Version Changes" PR - use changesets Github action to automatically do this)
- Publish to NPM using wombat-dressing-room tokens
- Launch E2E tests workflow (changed e2e-test.yml workflow to use a `repository_dispatch` trigger to make it easier to call from here)
- Log staging info to Firebase release tracker (call a cloud function) - we should probably add some kind of auth check before …
=> Create staging release workflow

.gitattributes
Use https://git-scm.com/docs/gitattributes to normalize line endings for markdown files checked into git. We had issues in the past where files with different line endings would be checked in and the diff would show the entire file as changed. This will use the line endings specified for all markdown files checked in.
=> Normalize line endings for markdown files checked into git

.github/workflows/release-staging.yml, scripts/release/cli.ts, scripts/release/release.ts
In order to run the release script in CI, it needs to skip the interactive prompts. Added a `skipPrompts` flag to the command to allow this.
Also the package.json isn't updated until after this script has run, so moved the step that gets the release version from the package.json to after the release script step.
=> Update release script with skipPrompts option

.changeset/late-toys-film.md, packages/auth/src/api/authentication/idp.test.ts, packages/auth/src/api/index.ts
=> Propagate customData in FirebaseError when the user is disabled. 

.github/workflows/release-prod.yml, scripts/release/utils/publish.ts, scripts/release/utils/tmp.ts
This is the production version of the staging release workflow, added in:
https://github.com/firebase/firebase-js-sdk/pull/6279
https://github.com/firebase/firebase-js-sdk/pull/6291
https://github.com/firebase/firebase-js-sdk/pull/6294
https://github.com/firebase/firebase-js-sdk/pull/6296
It differs from the staging workflow in that
- it does not create a changeset PR
- it calls the release script with the `--Production` flag which:
- writes tags to the Github repository afterwards
- does not bump versions manually since the correct versions should already be merged to the release branch
- it does not run E2E tests
- when done, it notifies the logProduction endpoint on the release tracker instead of logStaging
I've also modified `publishToCI()` so that it checks if a version has already …
=> Create production release workflow

scripts/release/release.ts, scripts/release/utils/publish.ts
- If production release, pass all packages to publishToCI(), which will sort out which needs to be published.
- Fix logic in publishToCI() to detect this.
Was able to test run successfully with some modifications (used --dryRun flag, skipped release tracker step)
=> Prod workflow: Fix logic for detecting published packages

scripts/release/release.ts, scripts/release/utils/publish.ts
When not using changeset to publish, we need to add the git tags manually.
=> Publish workflow: Add git tags during publish

repo-scripts/api-documenter/src/toc.ts, toc/toc.yaml
Revert part of https://github.com/firebase/firebase-js-sdk/pull/5333 so that we go back to generating TOC sub-items for each product.
=> Restore v9 TOC menu sub-items

packages/functions/src/callable.test.ts, packages/remote-config/src/api.ts, packages/storage/src/platform/node/connection.ts, packages/storage/src/task.ts, packages/storage/test/browser/blob.test.ts, packages/storage/test/integration/integration.test.ts, packages/storage/test/node/stream.test.ts, packages/storage/test/unit/testshared.ts
Updating error handling in select packages to account for a future TypeScript package upgrade. For more information, see the below blog comment about TypeScript v4.4 errors.
"""
In JavaScript, any type of value can be thrown with throw and caught in a catch clause. Because of this, TypeScript historically typed catch clause variables as any, and would not allow any other type annotation:
Once TypeScript added the unknown type, it became clear that unknown was a better choice than any in catch clause variables for users who want the highest degree of correctness and type-safety, since it narrows better and forces us to test against arbitrary values. Eventually TypeScript 4.0 allowed users to specify an explicit type annotation of unknown (or any) on each catch clause variable so that we …
=> Update error handling for TS v4.4 unknown variables

.changeset/sour-hornets-care.md, packages/messaging/src/helpers/externalizePayload.test.ts, packages/messaging/src/helpers/externalizePayload.ts
b/232072111
Should resolve https://github.com/firebase/firebase-js-sdk/issues/6207 & https://github.com/firebase/firebase-js-sdk/issues/5824
=> Fill Currently Missing`FcmOptions.link`

packages/analytics/src/index.ts, packages/auth/src/core/auth/middleware.ts, packages/auth/test/integration/flows/phone.test.ts, packages/firestore-compat/src/api/database.ts, packages/firestore/src/core/event_manager.ts, packages/messaging/src/helpers/registerDefaultSw.ts, repo-scripts/api-documenter/src/plugin/PluginLoader.ts, scripts/ci/check_changeset.ts
Updating error handling in select packages to account for a future TypeScript package upgrade. For more information, see the below blog comment about TypeScript v4.4 errors.
"""
In JavaScript, any type of value can be thrown with throw and caught in a catch clause. Because of this, TypeScript historically typed catch clause variables as any, and would not allow any other type annotation:
Once TypeScript added the unknown type, it became clear that unknown was a better choice than any in catch clause variables for users who want the highest degree of correctness and type-safety, since it narrows better and forces us to test against arbitrary values. Eventually TypeScript 4.0 allowed users to specify an explicit type annotation of unknown (or any) on each catch clause variable so that we …
=> Update error handling for TS v4.4 unknown vars

.changeset/mean-seals-poke.md, packages/storage/rollup.config.js
The Storage Node ESM bundle was incorrectly building from entry point `index.ts` instead of `index.node.ts`
Ran a build and the `index.node.esm.js` compiled bundle no longer contains "getStream() is only supported by NodeJS builds" error string.
Fixes https://github.com/firebase/firebase-js-sdk/issues/6343.
=> Fix Node ESM bundle to build from Node entry point.

.github/workflows/release-log.yml, .github/workflows/release-pr.yml, .github/workflows/release-staging.yml
Separated out the part of the staging release workflow that uses changesets/action to generate the "Version Changes" PR because that action is dependent on github context to get the branch and SHA which is basically set when the workflow begins and can't be changed. The main staging workflow unfortunately makes some changes to the release branch before calling changesets/action, so it doesn't work there.
Basically, on step 2 of the Staging Release workflow ("Merge master into release"), the work will split into 2 branches running in parallel. One branch is the staging workflow continuing to its next steps (NPM publish mainly), and the second branch is the "Release PR" workflow beginning, triggered by the merge.
=> Split staging release script into 2 parts

.github/workflows/release-staging.yml
Running this script in the actual release branch causes some issues in that it will use whatever version of this script is currently in the release branch, which might not be the most current. Use workflow inputs instead to get the "to" and "from" branches for this release.
=> Use workflow inputs for release branch

.github/workflows/e2e-test.yml, scripts/ci/notify-test-result.js
E2E tests are running fine but there's an issue with the REST call to the release tracker to log the result.
The E2E workflow was recently changed from a `workflow_dispatch` trigger to a `repository_dispatch` trigger. This changes how it receives input from the calling REST request, so the old github env variables no longer work. The correct variable is now passed in to the Node script through env variables to the "Tests succeeded" and "Tests failed" steps.
=> Fix E2E reporting to release tracker

common/api-review/analytics.api.md, packages/analytics/src/public-types.ts
Fix Typo in GtagConfigParams https://github.com/firebase/firebase-js-sdk/issues/6349
=> Fix typo in GtagConfigParams

.changeset/nervous-starfishes-crash.md, packages/rules-unit-testing/package.json, packages/rules-unit-testing/rollup.config.js
Rules-unit-testing only had a CJS build for Node. This causes it to load the CJS build of Firestore, while the user may load methods from an Node ESM build of Firestore, if their project uses ES modules. This causes there to be two copies of Firestore instances that don't match.
Tested on repro: https://github.com/MarkDuckworth/firebase-js-sdk-issues-6080 and it fixes the issue.
Fixes https://github.com/firebase/firebase-js-sdk/issues/6080
=> Add a Node ESM build to RUT

packages/analytics/src/get-config.ts, packages/messaging/src/internals/requests.ts, repo-scripts/size-analysis/analyze-all-bundles.ts, repo-scripts/size-analysis/test/size-analysis.test.ts
Update codebase to conform to later typescript versions. TS version > 4.4 gave TS errors for the lack of return type and not using arrow functions as a callback. TS version 4.4  requires updating catch variables as unknown. See additional information below.
"""
In JavaScript, any type of value can be thrown with throw and caught in a catch clause. Because of this, TypeScript historically typed catch clause variables as any, and would not allow any other type annotation:
Once TypeScript added the unknown type, it became clear that unknown was a better choice than any in catch clause variables for users who want the highest degree of correctness and type-safety, since it narrows better and forces us to test against arbitrary values. Eventually TypeScript 4.0 allowed users to specify an …
=> Update typing for new TS versions

.changeset/tiny-donuts-draw.md, common/api-review/functions.api.md, packages/functions-compat/src/callable.test.ts, packages/functions/src/callable.test.ts, packages/functions/src/error.ts, packages/functions/src/index.ts, packages/functions/src/public-types.ts
Add a public `FunctionsErrorCode` type that is prefixed with "functions/" to match the exact strings found in `FunctionsError.Code`.
This uses template literal types [which were introduced in Typescript 4.1](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html). This should be ok for most users I hope? 4.1 was released in Nov 2020.
Fixes https://github.com/firebase/firebase-js-sdk/issues/6281
=> Add public FunctionsErrorCode type

.changeset/witty-windows-unite.md, packages/auth/src/core/util/browser.test.ts, packages/auth/src/core/util/browser.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/6331
This is important for Cordova
=> [Auth] Update user agent detection to better detect iPad

.github/workflows/health-metrics-pull-request.yml, .github/workflows/release-prod.yml, .github/workflows/test-all.yml
There is another workflow [1] that listens to tag push events.
However, this workflow is not being triggered by new tags
currently, due to the fact that tag push commands
(`git push <tag-name>`) initiated by GitHub Actions bot do not
trigger other workflows [2].
Switching to a personal GitHub account (in our case the
`google-oss-bot`) should fix the problem.
[1] https://github.com/firebase/firebase-js-sdk/blob/master/.github/workflows/health-metrics-release.yml
[2] https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
=> Upload release tags on behalf of google-oss-bot.

.github/workflows/release-pr.yml
Prevent "Create Release PR" workflow from running on push to release, if the push came from the release operator merging the "Version Packages" PR into the release branch in preparation for the production release.
=> Block release PR flow if release merge

packages/rules-unit-testing/src/util.ts
Update the reference doc for assertSucceed and align it to the public doc.
per:  https://firebase.google.com/docs/rules/unit-tests#rut-v2-common-methods
> The function asserts that the supplied Promise wrapping an emulator operation will be resolved with no Security Rules violations.
Proposed fix for #6306
=> Update the assertSucceed reference doc to the public doc

.changeset/silly-panthers-mix.md, common/api-review/analytics.api.md, packages/analytics/src/api.test.ts, packages/analytics/src/api.ts, packages/analytics/src/factory.ts, packages/analytics/src/functions.test.ts, packages/analytics/src/functions.ts, packages/analytics/src/initialize-analytics.test.ts, packages/analytics/src/initialize-analytics.ts
Add function to set data that will be set on every event logged from the SDK, including automatic one.
=> Add function setDefaultEventParameters() to set data that will be logged on every analytics SDK event 

.changeset/late-ducks-invite.md, packages/firebase/compat/installations/index.ts, packages/firebase/compat/installations/package.json, packages/firebase/compat/package.json, packages/firebase/installations/index.ts, packages/firebase/installations/package.json, packages/firebase/package.json
These were not added in v9 because were under the impression that installations should not be a publicly exposed API but guide docs seem to indicate otherwise: https://firebase.google.com/docs/projects/manage-installations
This allows:
- importing `firebase/installations` and `firebase/compat/installations` - previously users could import `@firebase/installations` and `@firebase/installations-compat` directly, but they were not available on the `firebase` entry point (no `@`)
- usage of firebase-installations.js and firebase-installations-compat.js from the gstatic CDN
=> Add installations CDN build and "firebase" entry point

.changeset/smooth-readers-cough.md, packages/auth/src/platform_browser/recaptcha/recaptcha_loader.ts
Auth's `ReCaptchaLoaderImpl.load()` method checks for if the ReCAPTCHA script tag has already been loaded by itself or another library, and does not load it again if so. It does this by checking for the global object `window.grecaptcha`. Unfortunately, this object will exist if the ReCAPTCHA Enterprise version of the script has been loaded (which may be done by App Check if the user is using ReCAPTCHA Enterprise with App Check), BUT it will only contain the `enterprise` property, which is a nested version of the regular ReCAPTCHA object.
This change has the `load()` method check instead for the existence of `window.grecaptcha.render`. If it is not found, it will go ahead and load the non-Enterprise script tag, which seems to be able to co-exist with Enterprise and just adds the …
=> Check for non-Enterprise recaptcha object

.changeset/stale-pianos-buy.md, packages/database/src/realtime/WebSocketConnection.ts
We were redeclaring `options`, which means we weren't setting them correctly.
=> Fix options for RTDB on node

.changeset/shiny-bats-reflect.md, .changeset/silly-panthers-mix.md
Forgot to add `firebase` to minor version bumps for Analytics. We need to manually add it because changesets won't automatically do a minor bump for the main package when dependent packages get a minor bump.
=> Forgot to add firebase version bumps for analytics

.changeset/cyan-sheep-battle.md, packages/app-check/src/internal-api.test.ts, packages/app-check/src/providers.ts
Switch check for FirebaseError code to use includes https://github.com/firebase/firebase-js-sdk/issues/6373
=> Fix throttling for App Check to prevent unnecessary requests to backend 

packages/database/src/api/Reference_impl.ts
Updated documentation to reflect recommended way of removing listeners.
=> Updated docstring for off

.changeset/popular-bugs-draw.md, config/functions/package.json, package.json, packages/auth-compat/demo/functions/package.json, packages/auth/demo/functions/package.json, packages/rules-unit-testing/functions/package.json, yarn.lock
`firebase-functions` needs to be bumped to 3.22.0 to be compatible with `firebase-admin` version 11.0.0. Also might as well bump our testing functions to use Node 16 while we are at it.
=> Update firebase-functions version

.changeset/kind-pots-admire.md, common/api-review/database.api.md, packages/database-compat/src/api/Reference.ts, packages/database-types/index.d.ts, packages/database/src/api/Reference_impl.ts, packages/firebase/compat/index.d.ts
=> Updated type of action parameter for DataSnapshot#forEach

packages/auth/src/platform_browser/recaptcha/recaptcha_verifier.ts
Remove note about auto-populating auth if it's not present
=> Update recaptchaVerifier docs

packages/app/src/public-types.ts
This change corrects a misspelling of Firebase in a documentation comment. Issue #6393
=> Correct Firebase spelling for issue #6393

.github/workflows/release-prod.yml
Last TODO in the new release process: allow the release-prod.yml workflow to take a custom release branch name. This should only be needed in very rare cases but we need to add this functionality for the migration to officially be complete.
=> Allow selecting a custom release branch

.github/workflows/check-changeset.yml, .github/workflows/health-metrics-pull-request.yml
Skip running this workflow on the "Version Packages" release PR. It always leaves a confusing comment that no changesets were found because this PR removes all changesets, as it should, for the release.
=> Do not run check-changeset on release PR

packages/auth/api-extractor.json, scripts/docgen-compat/generate-docs.js, scripts/docgen-compat/theme/layouts/default.hbs
Changed v8 docgen script so that depending on if "node" or "js" is specified as the script is called, the script will modify theme/layouts/default.hbs to point to the correct _project.yaml.
Sample of the generated files:
First 7 lines of firebase.app.App.html for js/v8:
```
<!DOCTYPE html>
<html devsite class="default no-js">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="hide_page_heading" value="true" />
<meta name="project_path" value="/docs/reference/js/v8/_project.yaml" />
```
First 7 lines of firebase.app.App.html for node:
```
<!DOCTYPE html>
<html devsite class="default no-js">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="hide_page_heading" value="true" />
<meta name="project_path" …
```
=> Generate v8 docs with correct project paths

.changeset/calm-pugs-leave.md, packages/app/src/errors.ts, packages/app/src/indexeddb.test.ts, packages/app/src/indexeddb.ts
IndexedDB is used in firebase/app for platform logging purposes. If there are any issues reading and writing to IDB, they should not throw and crash the rest of the app. Changed all caught failures to warn instead of throw.
Also renaming the error codes because they can be misleading and make it looks like the errors are related to Firebase Storage, the product.
Addresses "Error 1" listed in https://github.com/firebase/firebase-js-sdk/issues/6456
=> Warn instead of throw for idb errors in core app

scripts/docgen/docgen.ts
TOC paths should not have "v9" in them.
=> Fix TOC path for v9 docs

packages/firestore/src/api/credentials.ts
=> Allow FirstPartyAuth to specify a token factory func.

.changeset/lovely-apricots-begin.md, e2e/package.json, e2e/yarn.lock, packages/firebase/compat/index.cdn.ts, packages/firebase/package.json, yarn.lock
We previously provided a `@firebase/polyfill` library for polyfills needed to get the SDK working in older browsers. We stopped providing this upon the v9 release, as official policy on v9 release was to ask users to provide their own polyfills if they need them. It's still included as a dependency in `packages/firebase/package.json` and it's imported in the compat CDN builds. I'm not sure if that was intentional, but since we don't maintain the package any more (it's been deleted from the repo) and can't update it, I don't think we should depend on it.
Removed import in compat CDN and dependency from firebase/package.json. Also updated the version of `firebase` in `e2e/` even though it doesn't matter (it's reinstalled every time the e2e workflow runs), just so `@firebase/polyfill` gets …
=> Remove all references to `@firebase/polyfill` from repo

.changeset/happy-eels-confess.md, packages/auth/src/core/auth/auth_impl.test.ts, packages/auth/src/core/auth/auth_impl.ts
We noticed the logic in the proactive refresh code was not quite correct (it wasn't turning on for newly-signed-in users). Turns out we also never tested this. D'oh! I've added some tests and walked through the code with Maneesh and I think this puts us in a better spot.
=> Fix proactive refresh logic, add some tests

.github/workflows/test-changed-auth.yml, packages/auth/src/api/errors.ts, scripts/run_tests_in_ci.js
Update Auth Firefox cross browser action to only run on changed auth files. In the previous iteration, we ran the unit tests irrespective of changed auth files which is incongruent with the purpose of the github action
=> Update Auth Firefox cross browser action to only run on changed auth files

.github/workflows/test-changed-auth.yml, .github/workflows/test-changed-firestore.yml, packages/firestore/karma.conf.js, packages/firestore/package.json, packages/firestore/test/unit/util/bundle.test.ts, scripts/run_tests_in_ci.js
Add browser unit tests for firefox in firestore
Update build command for firefox in auth
=> Add browser unit tests for firefox in firestore

.changeset/good-bears-obey.md, packages/database/src/core/util/util.ts, packages/database/test/deno.test.ts, scripts/emulator-testing/emulators/database-emulator.ts
Fixes the issue where the database hangs when all actions are completed and `setTimeout` fails to terminate via `unref` #5783
Deno has the experimental `Deno.unrefTimer` as an alternative to Node.JS's `timer.unref` in the unstable API version of Deno. With the `--unstable` argument, you can use `unrefTimer` in the same way as `unref`
=> Included experimental support for Deno

.github/workflows/deploy-config.yml, scripts/ci-test/deploy-if-needed.ts
Infrequently, someone may change one of the project config files in the `config/` directory (database rules, firestore rules, or cloud functions) which needs to be pushed to the backend.
`yarn test:setup` can be used to push any changes to the test project the developer is using during development, but the CI tests run specifically against the jscore-sandbox project, and the same rules/functions need to be pushed to that project for CI tests to pass.
This detects if any of those files have changed and tries to deploy them efficiently to the backend using the `only` option (so if only firestore rules have changed, it only deploys firestore rules). If `firebase.json` changes, that is considered to require deploying everything.
This needs to complete before any tests run, but since the …
=> Have CI deploy rules/functions to test project as needed

.changeset/smart-plants-sparkle.md, packages/firestore/src/core/transaction.ts, packages/firestore/test/integration/api/transactions.test.ts, packages/firestore/test/lite/integration.test.ts
Note: This fix needs to be ported to android and ios.
Fixes #5871
=> Firestore: Fix FAILED_PRECONDITION when writing to a deleted document in a transaction

packages/auth/src/api/account_management/mfa.test.ts, packages/auth/src/api/account_management/mfa.ts, packages/auth/src/api/authentication/mfa.test.ts, packages/auth/src/api/authentication/mfa.ts, packages/auth/src/api/index.ts, packages/auth/src/mfa/mfa_resolver.test.ts, packages/auth/src/platform_browser/mfa/assertions/phone.test.ts, packages/auth/src/platform_browser/strategies/phone.test.ts
We will have other MFA providers than phone in the near future.
=> Fix MFA endpoint names to be mfa provider-agnostic.

packages/auth/karma.conf.js, packages/auth/src/core/util/version.test.ts, packages/auth/src/platform_browser/persistence/session_storage.test.ts, packages/auth/src/platform_cordova/popup_redirect/events.test.ts
These currently show up in the diff when running `yarn format`. Sending a separate PR so they are not showing up as unrelated changes in other PRs.
=> Fix formatting for auth files.

common/api-review/auth.api.md, packages/auth/src/mfa/assertions/totp.ts, packages/auth/src/model/enum_maps.ts, packages/auth/src/model/public_types.ts, packages/auth/src/platform_browser/mfa/assertions/totp.ts
Added basic structure for implementing TOTP MFA
=> Add public methods to support TOTP as a multi-factor provider.

packages/firestore/src/protos/google/firestore/v1/query.proto, packages/firestore/src/protos/protos.json
change int32 to int64 for up_to
=> change int32 to int64

packages/firestore/src/core/firestore_client.ts, packages/firestore/test/integration/api/aggregation.test.ts
=> check client offline state and test

.changeset/spotty-pillows-applaud.md, common/api-review/auth.api.md, packages/auth/src/model/public_types.ts
This change updates the type of the custom claim field in the `ParsedToken` interface to be `any`. This more accurately reflects that a JWT may contain any valid JSON object.
While using the `unknown` type would have been more type-safe (and use of `any` is generally frowned-upon), it unfortunately makes this change backwards-incompatible.
Fixes https://github.com/firebase/firebase-js-sdk/issues/6553
=> Update type of ParsedToken to include unknown

.changeset/curly-mirrors-occur.md, packages/auth/src/mfa/mfa_session.ts, packages/auth/src/mfa/mfa_user.test.ts, packages/auth/src/mfa/mfa_user.ts, packages/auth/src/platform_browser/mfa/assertions/phone.test.ts
This is needed for TOTP support where the function to generate TOTP Secret (by invoking startEnrollment API) needs the Auth reference, but rather than pass in a parameter, we can derive it from the multiFactorSession that is already passed in as a param. This simplifies the TOTP enrollment API for the developer, by requiring one less parameter.
The usage for auth can be seen in this WIP change - https://github.com/firebase/firebase-js-sdk/compare/mfa-totp...mfa-totp-prameshj#diff-e9ae122839df9e758f95dd35db60444dd51b73a319b02a9ef36b747dc9889fbaR81
* If this has been discussed in an issue, make sure to link to the …
=> Include a reference to AuthInternal in MultiFactorSessionImpl.

.changeset/selfish-worms-glow.md, packages/app-check/src/indexeddb.ts, packages/app-check/src/internal-api.test.ts, packages/app-check/src/internal-api.ts, packages/app-check/src/storage.ts, packages/app-check/src/types.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/6373
Found 2 causes of the problems:
1) `getToken()` needs to return an error result (a dummy token with an `error` property) whenever there is an error. It was assuming that if there was an error there would be no token. This is not always the case. If the token is about to expire, the proactive refresh attempt may run into an error at the exchange endpoint. Then there will be an existing valid token, but also en error.
2) When `getToken()` makes a request to the exchange endpoint, it stores the promise in `state.exchangeTokenPromise` and doesn't make another request if the promise is in flight, instead, any calls during that period await the existing promise. Once the promise is resolved, it clears `state.exchangeTokenPromise`, …
=> Fix App Check timer issues

.changeset/nine-cherries-swim.md, packages/firestore/src/local/local_store_impl.ts, packages/firestore/test/unit/specs/listen_spec.test.ts
Fix: https://github.com/firebase/firebase-js-sdk/issues/6511
=> Fix document change leads to time travel across multiple tabs

common/api-review/firestore-lite.api.md, common/api-review/firestore.api.md, packages/firestore/lite/index.ts, packages/firestore/src/api.ts, packages/firestore/src/api/aggregate.ts, packages/firestore/src/lite-api/aggregate.ts, packages/firestore/src/lite-api/aggregate_types.ts
The wording is copied from https://github.com/firebase/firebase-android-sdk/pull/4143
=> Firestore: Re-write API docs for COUNT API

common/api-review/firestore.api.md, packages/firestore/src/api/database.ts, packages/firestore/src/lite-api/database.ts, repo-scripts/prune-dts/extract-public-api.ts
Update prune-dts (only used by Firestore I think) to allow beta APIs to get through (this seems to be the default behavior when using api-documenter). I think this is because api-documenter uses the *.api.json files and prune-dts filters out beta APIs before they even get into the json, whereas api-extractor puts everything in the json, and only filters what it puts into the public *.d.ts file.
Also an overload was recently added to `getFirestore()` which causes `{@link getFirestore}` to no longer work, leaving only a blank space in its place in reference docs. Fixed this by specifying the overload.
Also regenerated the firestore.api.md file after these changes.
=> Update prune-dts to allow beta APIs

scripts/docgen/docgen.ts
Add a leading slash to keep the toc contents consistent with what's already on devsite.
=> Add leading slash to toc path

packages/auth/demo/README.md
Updated build step for auth package in the readme file
=> Demo-app readme fix

packages/firestore-compat/src/index.console.ts
=> Adding Count to be accessible to the console.

README.md, packages/storage/.gitignore
Updated README to include CORS setup information to run Storage tests.
=> Updated readme instructions for storage

.changeset/cool-seas-confess.md, packages/database/src/api/Reference_impl.ts
=> fix documentation typo

packages/firestore/test/integration/api_internal/aggregation.test.ts, packages/firestore/test/lite/integration.test.ts
Enable the integration tests for COUNT that were added in https://github.com/firebase/firebase-js-sdk/pull/6597 now that the RunAggregationQuery RPC has been fully rolled out.
=> Enable COUNT integration tests, now that backend support has rolled out

common/api-review/auth.api.md, packages/auth/demo/package.json, packages/auth/demo/public/index.html, packages/auth/demo/public/style.css, packages/auth/demo/src/index.js, packages/auth/index.ts, packages/auth/src/mfa/assertions/totp.ts
Exported TOTP objects and updated the demo app to support TOTP MFA enrollment.
Modified the demo app package.json to pick up auth changes from HEAD.
=> Mfa totp demoapp

common/api-review/storage.api.md, packages/storage/src/implementation/backoff.ts, packages/storage/src/implementation/constants.ts, packages/storage/src/implementation/error.ts, packages/storage/src/implementation/request.ts, packages/storage/src/implementation/requests.ts, packages/storage/src/implementation/string.ts, packages/storage/src/implementation/utils.ts, packages/storage/src/service.ts, packages/storage/src/task.ts, packages/storage/test/unit/requests.test.ts, packages/storage/test/unit/task.test.ts, packages/storage/test/unit/testshared.ts, packages/storage/test/unit/utils.test.ts
When upload requests respond with a 503, there is a situation where the bytes were uploaded, yet finalize did not occur. This can result in an incorrect offset being sent to the server. We should make a request that checks the status of the upload, and updating our offset based on that.
This PR implements that, along with a backoff feature, exponentially increasing the time between different requests being issued.
=> Implemented exponential backoff with query

scripts/docgen/docgen.ts
Removes the 3 packages from the v9 docs index page that shouldn't have a public link (they're already removed from the TOC and the generated md files are also removed)
This is the page: https://firebase.google.com/docs/reference/js
=> Remove excluded packages from doc index.md

.changeset/metal-goats-unite.md, packages/firestore-compat/src/index.console.ts, packages/firestore/src/platform/browser/webchannel_connection.ts, packages/webchannel-wrapper/src/index.d.ts, packages/webchannel-wrapper/src/index.js
There are two notable changes in this PR:
1. Add a call to `XhrIo.setWithCredentials(true)` when invoking the `RunAggregationQuery` RPC.
2. Add a hook in firestore-compat to call `getCountFromServer()` in the `INTERNAL` object.
The `XhrIo.setWithCredentials(true)` change is required so that the Firestore Console's authentication cookie will be included in the HTTP request headers. Without it, the requests fail with HTTP 401 errors. This problem is unique to the Firestore Console because they use 1st-party authentication. This change should have no effect on any other users. Moreover, the "Listen" and "Write" streams have been invoking `XhrIo.setWithCredentials(true)` indirectly since the dawn of time by specifying `supportsCrossDomainXhr: true` in the `WebChannelOptions`: …
=> Make COUNT queries available to the Firestore Console

.changeset/strong-squids-dress.md, packages/util/src/defaults.ts
Fix bugs introduced in https://github.com/firebase/firebase-js-sdk/pull/6526:
1) Remove `__FIREBASE_DEFAULTS_PATH__` option to point to a JSON file path for modular autoinit defaults. This causes webpack warnings about dynamic `require()`s although the code is only meant to take that path in a Node environment. (See https://github.com/firebase/firebase-js-sdk/issues/6660). If we can figure out a way around this, we can add the functionality back.
2) Fix the `process` check to be more robust and handle environments that have `process` but do not have `process.env`. This incorporates the fix in PR https://github.com/firebase/firebase-js-sdk/pull/6663
Fixes https://github.com/firebase/firebase-js-sdk/issues/6660
Fixes https://github.com/firebase/firebase-js-sdk/issues/6662
=> Remove json path and fix process check

packages/auth/src/platform_browser/strategies/redirect.ts, packages/firebase/compat/index.d.ts
In v8, getRedirectResult returned a UserCredential with a null user if no redirect operation was called. In v9, it now returns null. Change docs to reflect this change
https://github.com/firebase/firebase-js-sdk/issues/6616
=> Update doc string to reflect V9 changes

.changeset/slow-forks-tease.md, packages/analytics/src/helpers.test.ts, packages/analytics/src/helpers.ts, packages/analytics/src/index.test.ts, packages/analytics/src/initialize-analytics.test.ts, packages/analytics/src/initialize-analytics.ts, packages/analytics/testing/gtag-script-util.ts
Update findGtagScriptOnPage to take optional data layer name when finding existing scripts
https://github.com/firebase/firebase-js-sdk/issues/6565
=> Update to allow for multiple instance of gtag with different datalayer names

.changeset/shy-dragons-fly.md, common/api-review/util.api.md, packages/database/src/api/Database.ts, packages/firestore/src/api/database.ts, packages/firestore/src/lite-api/database.ts, packages/functions/src/api.ts, packages/storage/src/api.ts, packages/util/src/defaults.ts, packages/util/test/defaults.test.ts
Fixes IPv6 addresses not parsed correctly in #6526. See tests added
=> Handle IPv6 addresses in emulator autoinit.

.changeset/moody-icons-repeat.md, common/api-review/analytics.api.md, packages/analytics/src/api.ts, packages/analytics/src/functions.test.ts
Allow users to pass in `null` value to public `setUserId` per internal implementations 
https://github.com/firebase/firebase-js-sdk/issues/6592
=> Update public api signature for setUserId to reflect internal functions

package.json, packages/firestore-compat/babel.config.json, packages/firestore/babel.config.json, yarn.lock
Removing dependency as we no longer use `import.meta.url` in the codebase https://github.com/firebase/firebase-js-sdk/search?q=%22import.meta.url%22&type=code. 
The need for the dependency was removed by PR https://github.com/firebase/firebase-js-sdk/pull/5883
=> Remove dependency babel-plugin-transform-import-meta

.changeset/great-houses-trade.md, packages/storage/src/task.ts, packages/storage/test/unit/task.test.ts, packages/storage/test/unit/testshared.ts
Made sure that timers are cleaned up when in the middle of exponential backoff.
=> [Storage] Cleared timeouts upon pause/resume of uploads

.changeset/grumpy-suits-pump.md, packages/util/src/defaults.ts, packages/util/test/defaults.test.ts
Due to various frameworks and environments, we have been encountering a lot of special cases not accounted for in `getDefaults()` (such as `process` existing but `process.env` not existing in Nuxt 3, or `document` existing but `document.cookie` throwing in Angular Universal).
Adding an overall try/catch block to `getDefaults()` so that if it runs into any errors we haven't thought of, it won't block execution of the rest of Firebase. It will log a console.info so we can find out about these cases and account for them.
Also added a separate catch specifically for the Angular Universal case. Yes, this would be caught by the overall try/catch already, but I'd like to put in the specific cases as we find them so we know the specifics of the various environments we're dealing with, as this …
=> Catch getDefaults() errors and do not throw

.github/workflows/release-tweet.yml, scripts/ci/poll_release_notes.js
This is manually triggered for now. You have to enter the version number. It will poll devsite 10 times every 15 minutes until it finds the release notes have been published, and then should send the tweet. I haven't put the secrets into the repo yet, I'd like to test everything else works up to that step before doing so. This PR needs to be merged to test it though.
=> Add a workflow to send release tweet

common/api-review/auth.api.md, packages/auth/demo/public/index.html, packages/auth/demo/src/index.js, packages/auth/src/api/authentication/mfa.ts, packages/auth/src/mfa/assertions/totp.ts
Support sign-in with MFA TOTP.
Builds on top of the changes in https://github.com/firebase/firebase-js-sdk/pull/6629
=> sign-in flow for totp

.gitignore, README.md, scripts/docgen-compat/content-sources/js/HOME.md, scripts/docgen-compat/content-sources/node/HOME.md
We have stopped publishing Bower versions of Firebase. Removing mentions of it from the repo.
=> Remove mentions of Bower from repo and docs

.changeset/popular-beans-wonder.md, repo-scripts/api-documenter/src/cli/MarkdownAction.ts, repo-scripts/api-documenter/src/documenters/MarkdownDocumenter.ts, scripts/docgen/docgen.ts
Attempting to clean up pages with large groups of functions such as https://firebase.google.com/docs/reference/js/auth by grouping them by first param.
Will gate this behind a flag, `--sort-functions` so that the change will not be forced on other consumers of our api-documenter fork (functions and admin teams).
=> Add a flag allowing api-documenter to sort functions by first param

packages/auth/src/mfa/assertions/totp.test.ts
This PR contains code implementation for adding unit test cases for sigin-flow
=> Unit test cases for sign-in flow

repo-scripts/api-documenter/package.json, repo-scripts/api-documenter/src/documenters/MarkdownDocumenter.ts, repo-scripts/api-documenter/src/toc.ts
API documenter's API doesn't seem to let you add arbitrary HTML or formatting so added bold using its API. Can't seem to do much more than that for now.
Also remove "section: []" from toc. Apparently devsite doesn't like it? But it used to?
=> Use API to bold

.changeset/chilled-forks-accept.md, packages/storage/src/implementation/type.ts, packages/storage/test/unit/task.test.ts
Removed use of native Node 18 blobs.
=> [Storage] Removed use of native Node 18 blobs

.changeset/lovely-swans-shake.md, common/api-review/messaging-sw.api.md, common/api-review/messaging.api.md, packages/messaging/src/helpers/externalizePayload.test.ts, packages/messaging/src/helpers/externalizePayload.ts, packages/messaging/src/interfaces/internal-message-payload.ts, packages/messaging/src/interfaces/public-types.ts
Fixes for b/241885017.
Would patch https://github.com/firebase/firebase-js-sdk/issues/6466
=> Expose 'icon' field from the Firebase Messaging SDK

.changeset/dirty-eggs-deliver.md, packages/performance/src/utils/attribute_utils.test.ts, packages/performance/src/utils/attributes_utils.ts
https://github.com/firebase/firebase-js-sdk/issues/6657 Cannot read property 'controller' of undefined
=> Account for a `navigator` that has a key of `serviceWorker` but an undefined value

.changeset/young-knives-shake.md, packages/firestore/src/core/transaction_runner.ts, packages/firestore/test/integration/api/transactions.test.ts
Transaction.get(ref) followed by transaction.set(ref, {...}) is causing the transaction to fail with error 'Document already exists' if the document was created by another app between the get and set.
'already-exists' is considered to be a permanent error for transactions, therefore will not be retried.
https://github.com/firebase/firebase-js-sdk/blob/f86f7de090ae7f61b795d0dbbe9b3765590e0286/packages/firestore/src/core/transaction_runner.ts#L115
Fix Issue: https://github.com/firebase/firebase-js-sdk/issues/6659
=> Fix transaction.set() failure without retry on "already-exists" error

.changeset/lovely-swans-shake.md, common/api-review/messaging-sw.api.md, common/api-review/messaging.api.md, packages/messaging-types/index.d.ts, packages/messaging/src/helpers/externalizePayload.test.ts, packages/messaging/src/helpers/externalizePayload.ts, packages/messaging/src/interfaces/internal-message-payload.ts, packages/messaging/src/interfaces/public-types.ts
This follows https://github.com/firebase/firebase-js-sdk/pull/6722 to supplement 'icon' also to the '/messaging-types'  dir.
ref: b/241885017
=> Add 'icon' to '/messaging-types' 

repo-scripts/changelog-generator/index.ts
In this pr, fixed a typo in a variable name. It is a really very small change that does not affect any functionality or process.
=> Typo on changelog-generator

.changeset/long-shirts-explode.md, packages/storage/src/implementation/error.ts, packages/storage/src/implementation/string.ts, packages/storage/src/platform/browser/base64.ts, packages/storage/test/browser/string.browser.test.ts
When users of Expo and other similar environments don't support `atob` or `btoa`, polyfills are required, but the SDK doesn't provide this information to the user. 
This PR checks whether `atob` is available and throws an error if it is not.
=> Updated base64 error to be more descriptive

.changeset/shiny-berries-carry.md
Add missing package that should have been included in https://github.com/firebase/firebase-js-sdk/pull/6728
=> Add missing package to changeset

scripts/ci/check_changeset.ts
This path seems to have not been updated when the script was moved inside a subdirectory in https://github.com/firebase/firebase-js-sdk/pull/5390
=> Update parent path for check_changeset script

common/api-review/firestore-lite.api.md, common/api-review/firestore.api.md, packages/firestore/src/lite-api/query.ts
Tagging all new OR Query API members as internal until server support. This keeps the OR Query members out of public documentation, but does not keep changes to pre-existing API members out of public docs. For example, changes to `limit(...)` documentation and return types will still be in docs.
=> Tagging all new OR Query API members as internal until server support

packages/auth/package.json, packages/auth/test/helpers/api/helper.ts, packages/auth/test/helpers/integration/helpers.ts, packages/auth/test/integration/flows/totp.test.ts, packages/auth/totp-generator.d.ts
=>  integration tests for totp

.github/workflows/test-changed-auth.yml, .github/workflows/test-changed-firestore.yml, .github/workflows/test-changed.yml, packages/firestore/src/index/directional_index_byte_encoder.ts
Github's latest image for ubuntu is ubuntu-22.04 which seems to come with a version of Firefox that causes the karma launcher to hang and eventually give up when trying to launch Firefox. Other users have reported the Firefox bin isn't there at all, which is not exactly the same issue, but could be related. Locking it to ubuntu-20.04 until we can figure out why (hopefully it isn't that current and future versions of Firefox don't work with karma-firefox-launcher).
=> Fix Firefox CI issue

packages/firestore/src/protos/firestore_proto_api.ts, packages/firestore/src/remote/existence_filter.ts, packages/firestore/src/remote/serializer.ts, packages/firestore/test/unit/specs/existence_filter_spec.test.ts, packages/firestore/test/unit/specs/limbo_spec.test.ts, packages/firestore/test/unit/specs/limit_spec.test.ts, packages/firestore/test/unit/specs/spec_builder.ts, packages/firestore/test/unit/specs/spec_test_runner.ts, packages/firestore/test/util/helpers.ts, packages/firestore/test/util/spec_test_helpers.ts
Note: The logic for using bloom filter and skipping full re-query is not implemented yet.
=> Add bloom filter to existence filter and watchFilters spec builder

.changeset/three-glasses-judge.md, packages/util/src/environment.ts
Related issue:
https://github.com/firebase/firebase-js-sdk/issues/6801
=> 6801 catch insecure indexedDB access

packages/auth/test/helpers/integration/helpers.ts, packages/auth/test/integration/flows/totp.test.ts, yarn.lock
Used timestamp to get future totp codes using totp-generator
=> Totp integration test fix

packages/auth/demo/public/index.html, packages/auth/demo/src/index.js
Adding functionality for setting tenant in demo app in order to test TOTP MFA at tenant level
=> Add set tenant method to demo app

packages/auth/demo/README.md
Updated the readme with screenshots and troubleshooting steps.
@sam-gc @renkelvin
=> Update demo app README with troubleshooting steps

.changeset/wild-frogs-play.md, packages/firestore/src/api/reference_impl.ts
Fix documentation for getDocsFromCache. Specifically this updates the line stating that the function will throw if documents are not cached, and instead states that the function will return an empty result set if documents are not cached. Fixes #6851
=> Fix documentation for getDocsFromCache.

.changeset/nervous-ads-pretend.md, packages/database/src/api/Database.ts, packages/database/test/exp/integration.test.ts
=> Fixed issue where we call connectDatabaseToEmulator twice

.changeset/wild-geckos-fetch.md, packages/util/src/defaults.ts
Scramble "process.env" in a comment because some compiler or combination of build tools seems to choke on it.
Fixes https://github.com/firebase/firebase-js-sdk/issues/6838
=> Format comment containing process.env

.changeset/silly-suns-drop.md, .changeset/young-hornets-rescue.md, common/api-review/util.api.md, packages/util/index.node.ts, packages/util/index.ts, packages/util/src/defaults.ts, packages/util/src/environment.ts, packages/util/src/global.ts, packages/util/test/defaults.test.ts, packages/util/test/environments.test.ts
To adapt to the changing javascript landscape, we will allow users to specify their environment as Node or Browser to override Firebase's runtime environment detection and force the SDK to act as if it were in the respective environment.
=> Add Env Override Global Variable `forceEnvironment`

common/api-review/auth.api.md, packages/auth/demo/public/index.html, packages/auth/demo/public/style.css, packages/auth/demo/src/index.js, packages/auth/src/mfa/assertions/totp.ts
Also changed the demo app to display this field as a countdown.
cc @bhparijat @sam-gc
=> Expose enrollmentCompletionDeadline field in TotpSecret.

packages/auth/src/platform_browser/strategies/redirect.ts
=> Reference the signInWithRedirect best practices in docs

.changeset/tricky-ravens-stare.md, packages/auth/demo/src/index.js, packages/auth/src/platform_browser/strategies/redirect.test.ts, packages/auth/src/platform_browser/strategies/redirect.ts, packages/auth/test/helpers/mock_auth.ts
Await on the initialization promise to ensure that the processing of a pending redirect result (as part of auth init) is done before triggering a new redirect.
Fixes https://github.com/firebase/firebase-js-sdk/issues/6827
=> Await on the auth initialization promise in signIn/link/reauthenticateWithRedirect

.changeset/pretty-carrots-kneel.md, packages/database/src/realtime/BrowserPollConnection.ts
Replacing innerHTML call with textContent. This is considered to be best practice and the safest option
=> Remove innerHTML call and replace with textContent

.github/workflows/merge-release-branch.yml, .github/workflows/release-prod.yml, .github/workflows/release-staging.yml, scripts/ci/check_changeset.ts, scripts/ci/detect-doc-changes.ts
The `set-output` command for Github Actions has been deprecated and should be replaced with writing to `$GITHUB_OUTPUT` as described here: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
This will get rid of warnings in Github workflow logs.
=> Replace deprecated set-output commands

.changeset/heavy-mirrors-drum.md, packages/auth-interop-types/package.json
`auth-interop-types` doesn't have any dependencies or imports and it's likely the `peerDependencies` only appears in its package.json because of a copy-paste mistake when the package was created.
Likely causing warnings as described in `firebase-admin`: https://github.com/firebase/firebase-admin-node/issues/973
=> Remove peer deps from auth-interop-types

.changeset/chilled-boats-report.md, packages/auth/demo/public/index.html, packages/auth/demo/src/index.js, packages/auth/src/core/strategies/credential.ts, packages/auth/src/mfa/mfa_user.test.ts, packages/auth/src/mfa/mfa_user.ts
This can be thrown if the MFA option that was most recently enrolled into, was unenrolled. The user will be logged out to prove the posession of the other second factor. This error can be handled by reauthenticating the user.
This change also updates the demo app to store the lastUser in case mfa unenroll logs out the user. From here, the lastUser can be reauthenticated.
=> Expose TOKEN_EXPIRED error upon mfa unenroll.

packages/auth/src/platform_browser/strategies/redirect.ts
Need to use `@link` tag for links in comments, not markdown. Markdown will get escaped by api-documenter and not work in devsite.
=> Fix link format in auth doc comment

packages/auth/demo/src/index.js
=> clear TOTP QR code display in the demo app once enrollment is complete.

.changeset/brave-ducks-relax.md, packages/auth-compat/src/auth.test.ts, packages/auth-compat/src/popup_redirect.test.ts, packages/auth-compat/test/helpers/helpers.ts, packages/auth/src/api/index.ts, packages/auth/src/core/auth/auth_impl.test.ts, packages/auth/src/core/auth/auth_impl.ts, packages/auth/src/core/auth/register.ts, packages/auth/src/core/util/handler.ts, packages/auth/src/core/util/log.ts, packages/auth/src/model/auth.ts, packages/auth/src/platform_browser/auth.test.ts, packages/auth/src/platform_browser/popup_redirect.test.ts, packages/auth/src/platform_browser/popup_redirect.ts, packages/auth/test/helpers/mock_auth.ts
Includes App Check token in Auth header requests to backend, if present. Passes App Check token to widget via the URL fragment
As part of [go/auth-app-check-sdk](http://go/auth-app-check-sdk)
Internal bug link: [b/265453815](http://b/265453815)
`yarn test` passes in `packages/auth` and `packages/auth-compat`
N/A
=> Add App Check token to Auth requests

.changeset/stupid-otters-speak.md, packages/auth-compat/package.json, packages/auth/package.json, packages/database-compat/package.json, packages/database/package.json, packages/firebase/package.json, packages/firestore-compat/package.json, packages/firestore/package.json, packages/functions-compat/package.json, packages/functions/package.json, packages/rules-unit-testing/package.json, packages/storage/package.json, packages/template/package.json, packages/util/package.json
Move `exports.defaults` field to the last field.
Fixes https://github.com/firebase/firebase-js-sdk/issues/7005.
This bug was introduced by https://github.com/firebase/firebase-js-sdk/pull/6981.
PR based on https://github.com/firebase/firebase-js-sdk/pull/7006
Edit: tested locally with a Next.js project
=> Fix exports fields

.github/workflows/e2e-test.yml, e2e/.gitignore, e2e/package.json, e2e/webpack.config.js
Add steps in E2E smoke test just to see if the app will build with a pretty standard webpack config. This would have caught https://github.com/firebase/firebase-js-sdk/issues/7005 . The E2E unit tests are run with karma-typescript and don't use webpack at all so they didn't catch this.
=> Add builds to E2E workflow

packages/firestore/test/unit/specs/spec_test_runner.ts
When comparing document changes for correctness in spec tests, the lists of changes in the actual and expected results were assumed to be ordered the same; however, they are not necessarily ordered in the same manner. Since order doesn't actually matter, this PR fixes potential future problems with sort order mismatches by sorting both of them using the same comparator.
Credit for this PR goes to @milaGGL from https://github.com/firebase/firebase-js-sdk/pull/6897. I'm merely merging a small component of that PR into the master branch to reduce the diff when her PR ultimately gets merged.
=> spec_test_runner.ts: sort document changes before comparing for correctness

packages/firebase/tsconfig.json
Ensure `firebase` main package builds ignore all dist files even in subdirectories. This was causing very slow builds in `rollup-plugin-typescript2` (30-50s per small index file). This didn't seem to be a problem in the past (perhaps a change to rpt2 or typescript introduced this), and it's not a problem for `@rollup/plugin-typescript` which doesn't even seem to need the `exclude` to know to ignore `dist/` files.
This reduces build times per file from roughly 30s to about 3s.
=> One neat trick to fix slow builds

packages/auth/src/api/authentication/mfa.ts, packages/auth/src/mfa/assertions/totp.test.ts, packages/auth/src/mfa/mfa_info.ts
=> remove startMfaSignIn step for TOTP, since it requires only one step.

.changeset/soft-nails-give.md, packages/firestore/src/util/byte_stream.ts
Fixes: https://github.com/firebase/firebase-js-sdk/issues/5838
Was introduced by: https://github.com/firebase/firebase-js-sdk/pull/4098
=> Fix unimplemented error when loading bundles

packages/firestore-compat/src/index.console.ts
This is necessary for errors where an index needs to be created and the user needs the creation link
=> Surface the error for COUNT queries

.changeset/fluffy-seas-behave.md, packages/auth/src/core/user/user_impl.test.ts, packages/auth/src/core/user/user_impl.ts
* Issue being fixed by this PR: https://github.com/firebase/firebase-js-sdk/issues/7057
When calling `updateCurrentUser` the code clones the UserImpl class but incorrectly clones the UserMetadata resulting in `undefined` values. 
Line of code calling `_clone`: https://github.com/firebase/firebase-js-sdk/blob/bea604ea33c529e755cc3fcdc0a2ea75d04b9f19/packages/auth/src/core/auth/auth_impl.ts#L343
`_clone` function: https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth/src/core/user/user_impl.ts#L142. 
The spread operator only passes keys on the UserImpl class and will not pass the Metadata properties belonging to `UserMetadata`.  This causes https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth/src/core/user/user_impl.ts#L142 to fail.
This is missed in the …
=> Explicitly set createdAt and lastLoginAt when cloning UserImpl

packages/auth/demo/README.md, packages/auth/demo/package.json
Update the README with steps to use the staging endpoint.
=> Point the demo app to use local auth SDK changes by default.

.github/workflows/check-changeset.yml, .github/workflows/check-docs.yml
PRs to feature branches (and release branch) don't need changeset checker run. Should only run the changeset check on PRs targeting master.
=> Avoid changeset check on PRs to non-master branches

packages/firestore/test/unit/specs/existence_filter_spec.test.ts, packages/firestore/test/unit/specs/limbo_spec.test.ts, packages/firestore/test/unit/specs/limit_spec.test.ts, packages/firestore/test/unit/specs/recovery_spec.test.ts, packages/firestore/test/unit/specs/spec_builder.ts, packages/firestore/test/unit/specs/spec_test_components.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
Validate targetPurpose in spec test ValidateActiveTargets function.
=> Validate target purpose in spec tests

.changeset/sixty-buckets-repeat.md, packages/auth/src/api/index.test.ts, packages/auth/src/api/index.ts
Fix https://github.com/firebase/firebase-js-sdk/issues/7118. 
https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth/src/api/index.ts#L184 throws INTERNAL_ERROR when there is a network error. However, https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth/src/core/auth/auth_impl.ts#L309-L316 treats any error other than NETWORK_REQUEST_FAILED as token is invalid and signs user out which is not an expected behavior. Hence, we're changing it back to using NETWORK_REQUEST_FAILED.
=> Change _fail to use NETWORK_REQUEST_FAILED

.changeset/friendly-ads-yell.md, packages/firestore/src/platform/browser/base64.ts
In https://github.com/firebase/firebase-js-sdk/issues/7115 the customer shows that the "browser" logic for decoding a base64 string was being invoked from a react-native app. In react-native, the `DOMException` class does not exist, which results in the following error:
```
ReferenceError: Property 'DOMException' doesn't exist
```
This usage of `DOMException` was added by https://github.com/firebase/firebase-js-sdk/pull/7019.
Although a react-native app _should_ be using a different implementation of base64 decoding, we may as well be safe here so that the error message produced from a react-native app is more meaningful, something like `Uncaught ReferenceError: atob() is not defined`.
=> firestore: verify DOMException exists before using it in when base64 decoding

.changeset/plenty-radios-look.md, packages/firestore/src/api/credentials.ts
Gapi.auth is going to be deprecated on March 31, and it is used for first party authentication in firestore.
Issue: https://github.com/firebase/firebase-js-sdk/issues/7012
=> remove gapi.auth fall back option for getAuthToken()

.changeset/brown-beers-tease.md
I overlooked this in the review for https://github.com/firebase/firebase-js-sdk/pull/7015
Minor/major bumps to individual products require an explicit minor/major bump to "firebase".
=> Add "firebase" changeset

packages/firestore/test/integration/api/query.test.ts, packages/firestore/test/integration/util/helpers.ts
This PR was ported to the Android SDK in https://github.com/firebase/firebase-android-sdk/pull/4799 and to the iOS SDK in https://github.com/firebase/firebase-ios-sdk/pull/10974.
=> Firestore: query.test.ts: add a test that resumes a query with existence filter

packages/firebase/compat/rollup.config.js, packages/firestore/rollup.shared.js
There is a bug where Closure has trouble handling scope in a switch statement. The mangler reuses a name in the switch statement body that was previously declared outside the switch scope and used inside the switch condition. If we don't mangle the outer variable, there can't be a name collision.
=> Unmangle a switch variable for Closure

.github/workflows/test-changed-auth.yml, packages/auth/src/api/authentication/email_link.ts
Auth CI tests are failing on all recent PRs due to new version of Chrome. 
Pinning Chrome version 110.0.5481.177-1 for "Test Auth on Chrome and Node If Changed test" where the tests passed previously to avoid this.
Tests pass locally on mac (in some setups) and fail different tests in linux + 111 chrome version. Sending this PR to unblock auth PRs for the upcoming release.
We will retry to use the latest, once Chrome releases stable version 112 (April 4 ETA).
=> [Auth] Pin Chrome version 110.0.5481.177-1 for "Test Auth on Chrome and Node If Changed test"

scripts/docgen/docgen.ts
Docgen modifies some files (usually packages/auth/api-extractor.json, but other files for TOC generation) before running `yarn build` and `yarn api-report` steps. If the process fails or is aborted during those steps, those files will remain modified, and any future runs will only restore them back to that modified state.
This PR uses a try/finally to make sure the files are always restored no matter what. Yes, you can have a try/finally without a catch: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#description
Tested it in the cases of a `yarn api-report` failure and success and the files are restored properly in both cases.
=> Ensure docgen script restores original files even if build fails

scripts/run_tests_in_ci.js
Auth compat and Firestore compat also need exclusions to stick to browser tests.
=> Ensure firefox tests exclude unnecessary tests

docs-devsite/auth.md, packages/auth/src/core/index.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/2985
@sam-gc @kevinthecheung
=> Update onIdTokenChanged docs about token expiration.

packages/auth/src/api/authentication/email_and_password.test.ts, packages/auth/src/api/errors.ts, packages/auth/src/core/errors.ts
PR to fix error code for missing password. Added a unit test case as well.
Performed manual testing with the demo app.
=> fixing error code for missing password

docs-devsite/firestore_.firestoresettings.md, docs-devsite/firestore_.md, docs-devsite/firestore_.persistentmultipletabmanager.md, docs-devsite/firestore_.persistentsingletabmanagersettings.md, packages/auth/api-extractor.json, packages/firestore/src/api/cache_config.ts, packages/firestore/src/api/settings.ts
Necessary for internal cl/520368128 presubmit
=> Update firestore docs for typos

.changeset/soft-zoos-listen.md, common/api-review/auth.api.md, docs-devsite/auth.totpmultifactorgenerator.md, packages/auth/src/mfa/assertions/totp.ts
The const enum is internal and not exported with public types, causing an error since it's referenced.
I believe other publicly exported auth classes avoid this by following the pattern here: https://github.com/firebase/firebase-js-sdk/blob/1d5646ed68ccc59dde27983bfe2575db5ecb528d/packages/auth/src/platform_browser/providers/phone.ts#L55
So I've done the same for `TotpMultiFactorGenerator`.
Fixes https://github.com/firebase/firebase-js-sdk/issues/7174
=> Fix ToTP typings issue

.github/CODEOWNERS
We should make a docs team alias at some point but for now, adding the 3 tech writers who cover all our product SDKs.
=> Add kevinthecheung to CODEOWNERS

packages/auth/demo/README.md
Added a command in readme to install packages after removing npm modules.
=> added missing command to install packages

.github/workflows/test-changed-auth.yml
Chrome stable version 112 was released. 
Revert [github.com/firebase/firebase-js-sdk/pull/7157](https://github.com/firebase/firebase-js-sdk/pull/7157) to unpin and install the latest Chrome version for "Test Auth on Chrome and Node If Changed test."
Make sure the tests pass with the latest Chrome version.
=> Install latest chrome version for "Test Auth on Chrome and Node If Changed" test 

.github/workflows/e2e-test.yml, e2e/karma.conf.js
Use `noEmitOnError` TS config flag to ensure karma E2E tests fail if TS has a compile error.
Also getting a warning about actions/setup-node@v2 being deprecated - we should update this in all workflows.
Otherwise TS failures like the one in this E2E job are non-blocking and the workflow is considered passing https://github.com/firebase/firebase-js-sdk/actions/runs/4550223341
=> Ensure e2e tests fail on TS errors

.github/workflows/update-api-reports.yml, common/api-review/auth.api.md
Fix a bug in the "Update API reports" workflow as seen in runs like https://github.com/firebase/firebase-js-sdk/pull/7205#issue-1657951238 as a result of upgrading EndBug/add-and-commit to v9.
=> Fix "Update API reports" workflow

.github/workflows/test-changed-auth.yml, packages/auth/src/api/authentication/email_link.ts
This reverts https://github.com/firebase/firebase-js-sdk/pull/7197 which unpinned the chrome version in "Test Auth on Chrome and Node If Changed".
The test still fails on version 111. Tests passed in the above PR because there were no code changes to auth.
Chrome version 112 has not become stable yet, so `sudo apt-get install google-chrome-stable` still installs version 111.
=> Revert "Install latest chrome version for "Test Auth on Chrome and Node If Changed" test"

.changeset/brave-ducks-relax.md, packages/auth-compat/src/auth.test.ts, packages/auth-compat/src/popup_redirect.test.ts, packages/auth-compat/test/helpers/helpers.ts, packages/auth/src/api/index.ts, packages/auth/src/core/auth/auth_impl.test.ts, packages/auth/src/core/auth/auth_impl.ts, packages/auth/src/core/auth/register.ts, packages/auth/src/core/util/handler.ts, packages/auth/src/core/util/log.ts, packages/auth/src/model/auth.ts, packages/auth/src/platform_browser/auth.test.ts, packages/auth/src/platform_browser/popup_redirect.test.ts, packages/auth/src/platform_browser/popup_redirect.ts, packages/auth/test/helpers/mock_auth.ts
As the title implies
Internal tracking bug: [b/265453815](http://b/265453815)
Unit tests pass and manually tested endpoints as part of [go/gcip-app-check-bug-bash](http://goto.google.com/gcip-app-check-bug-bash)
N/A
=> Added Firebase App Check support to Firebase Auth.

.changeset/shaggy-zebras-leave.md, packages/app-check/src/api.test.ts, packages/app-check/src/internal-api.test.ts, packages/app-check/src/providers.test.ts, packages/app-check/src/providers.ts, packages/app-check/src/recaptcha.test.ts, packages/app-check/src/recaptcha.ts, packages/app-check/src/state.ts, packages/app-check/test/util.ts
We were catching local errors in recaptcha by `catch`ing the result of `grecaptcha.execute`. It turns out that not all recaptcha errors result in `recaptcha.execute` throwing. Errors can also be caught in `error-callback` params passed to `grecaptcha.render`. See https://developers.google.com/recaptcha/docs/invisible for parameters accepted by `grecaptcha.render`.
These callbacks will set a boolean variable in our AppCheck state object, which will be checked in provider.getToken() methods for the two reCAPTCHA providers, and provider.getToken() will throw with a RECAPTCHA_ERROR if false. This will prevent the main `getToken()` in internal-api.ts from going on to call the exchange endpoint, since we already know we don't have a usable reCAPTCHA token to send. This will then prevent a 503 …
=> Catch all recaptcha errors

.changeset/three-months-lie.md, packages/firestore/src/core/firestore_client.ts, packages/firestore/test/integration/api/aggregation.test.ts
Fixes #7198.
A proper long-term solution for multi-tab should be implemented.
=> Allow aggregations to work with multi-tab.

.github/workflows/release-staging.yml
This should diff against the last published version, which we create a git tag for on every prod publish, in the format `firebase@[version number]`. We can use `npm info` to get the number and then git diff against that tag.
=> Fix doc change detection logic

.changeset/dry-cats-lick.md, packages/auth/src/platform_browser/strategies/popup.ts, packages/auth/test/integration/webdriver/popup.test.ts
In some cases (Fiefox or mobile or if opener is an iframe), the popup is closed by the oauth helper code right after sign in has completed at the IDP. The IDP response still needs to be processed by the SDK + signInWithIdp API call needs to be invoked. This can take upto 7s, if there is a blocking function configured. Increase the poller timeout to 8s, so it does not reject the sign in with popup-closed-by-user error.
Fixes - https://github.com/firebase/firebase-js-sdk/issues/7049, https://github.com/firebase/firebase-js-sdk/issues/7093
@sam-gc @renkelvin
=> Wait for upto 8s for IDP sign in to finish, after popup is closed.

packages/analytics/src/helpers.test.ts
Check if trusted types exists in the browser before running tests that stub the API stubbing
For example, Firefox still has not implemented the API, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/trusted-types#browser_compatibility
=> Prevent Trusted Types tests to run when the API does not exist

packages/firestore/test/lite/integration.test.ts
Fix some Firestore integration tests to use uniquely-generated collection names rather than hardcoding the collection names. This ensures that concurrently-executing tests will not interfere with each other.
There have recently been a few flakes, such as in the `supports partials with merge` test that could be explained by concurrently-executing tests both manipulating the same collection. By uniquely generating the collection ID this possibility is eliminated.
=> Firestore: use unique collection names in integration tests

packages/firestore/test/unit/api/database.test.ts
Add Firestore unit tests for coercing experimentalForceLongPolling and experimentalAutoDetectLongPolling to boolean
=> Firestore: database.test.ts: add tests for coercing long polling settings to boolean

README.md
Update the readme to reflect currently required tool versions (node, yarn and jdk) and `gsutil` auth steps.
N/A. Notes stem from setting up the SDK to build on macOS for the first time.
N/A
=> README Updates to steps and required tool versions

common/api-review/auth.api.md, common/api-review/storage.api.md, docs-devsite/auth.actioncodeinfo.md, docs-devsite/auth.multifactorassertion.md, docs-devsite/auth.multifactorerror.md, docs-devsite/auth.multifactorinfo.md, docs-devsite/auth.usercredential.md, docs-devsite/storage.md, packages/auth/src/core/strategies/redirect.test.ts, packages/auth/src/model/public_types.ts, packages/messaging/src/internals/idb-manager.test.ts, packages/messaging/src/internals/token-manager.test.ts, packages/messaging/src/listeners/sw-listeners.test.ts, packages/storage/src/implementation/string.ts, packages/storage/src/implementation/taskenums.ts, scripts/format/prettier.ts
We recently bumped the `prettier` dependency (https://github.com/firebase/firebase-js-sdk/pull/7232) which included a change to `typeof` expressions (puts parens around them): https://github.com/prettier/prettier/blob/main/CHANGELOG.md#add-parentheses-for-tstypequery-to-improve-readability-14042-by-onishi-kohei
Running it on the whole repo and also running docgen on the newly changed files so that these changes don't just pop up randomly in everyone's PRs going forward.
=> Rerun prettier/docs after prettier dependency update

packages/auth/src/model/public_types.ts
=> Clarify the usage of const enums and enum maps in auth.

.github/workflows/test-all.yml, .github/workflows/test-changed-auth.yml
Add Chrome pinning to `test-all.yml`, as was done for the auth-only tests in https://github.com/firebase/firebase-js-sdk/pull/7157. Although this is not a required check, it runs on all PRs and causes noise.
Auth team is working to determine the root cause and see if the tests can be fixed or skipped.
=> Pin Chrome version for test-all.yml

docs-devsite/auth.auth.md, packages/auth/src/model/public_types.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/158
cc @sam-gc @renkelvin
=> Document that signout will not revoke the id token.

.changeset/funny-ways-carry.md, packages/app/src/api.test.ts, packages/app/src/api.ts, packages/app/src/errors.ts, packages/app/src/internal.test.ts
See https://github.com/firebase/firebase-js-sdk/issues/7262
The `if` block added for modular autoinit is intercepting errors that users should be getting for calling `getApp()` before `initializeApp()`.  This change uses `getDefaultAppConfig()` as an additional condition. If it returns undefined, this isn't a modular autoinit situation and the user will get the correct `NO_APP` error.
Also updated the error message with the correct modular name for `initializeApp()`.
Also stubbed `logger.debug` on a test that had a verbose debug log that was cluttering test output.
=> Fix `getApp()` error message for non-autoinit situations

.vscode/settings.json
This should fix incorrect `import/no-extraneous-dependencies` eslint errors that only happen in the VSCode UI because it has trouble resolving dependencies in a monorepo.
More on the setting here: https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint#settings-options
=> Fix eslint vscode settings

.changeset/sixty-dolls-report.md, packages/app/src/indexeddb.ts
These indexeddb read/write functions are supposed to never throw, as they are part of platform logging, which should never impact user functionality. There is a try/catch to prevent this, but unfortunately the last statement in each try block was returning a promise directly instead of using `await`, which prevents `try` from catching errors in that statement. Converted them to await statements. They should be properly caught by `try/catch` now.
Fixes https://github.com/firebase/firebase-js-sdk/issues/6871
=> Catch more heartbeat read/write errors

docs-devsite/auth.md, docs-devsite/auth.user.md, packages/auth/src/core/action_code_url.test.ts, packages/auth/src/core/user/id_token_result.ts, packages/auth/src/model/public_types.ts
=> spellcheck identify

.changeset/small-chairs-explain.md, packages/auth/src/core/auth/initialize.test.ts, packages/auth/src/core/auth/register.ts
Used demo app to test changes. The authdomain was set to localhost:8080 and I saw the redirect hitting URL 
https://localhost:8080/__/auth/handler?apiKey=<API_KEY>&appName=%5BDEFAULT%5D&authType=signInViaRedirect&redirectUrl=http%3A%2F%2Flocalhost%3A5000%2F&v=9.8.1&providerId=google.com&scopes=profile
Fixes: https://github.com/firebase/firebase-js-sdk/issues/7233
=> Allow port numbers in authdomain

.changeset/witty-wasps-play.md
This changeset was created by https://github.com/firebase/firebase-js-sdk/pull/7176, but its wording neglected to update `idleHttpRequestTimeoutSeconds` to `experimentalLongPollingOptions.timeoutSeconds`. This commit fixes the wording to specify the correct property.
=> Fix changeset wording for `experimentalLongPollingOptions.timeoutSeconds`

packages/firestore/test/unit/specs/existence_filter_spec.test.ts, packages/firestore/test/unit/specs/limbo_spec.test.ts, packages/firestore/test/unit/specs/listen_spec.test.ts
Remove the no-android tag from bloom filter spec tests, now that the feature has been merged into the android sdk in https://github.com/firebase/firebase-android-sdk/pull/4982.
The spec test changes from this PR were ported to the iOS SDK in https://github.com/firebase/firebase-ios-sdk/pull/11245. Porting to the Android SDK is not needed since these changes were included in https://github.com/firebase/firebase-android-sdk/pull/4982.
=> Firestore: Remove the no-android tag from bloom filter spec tests

.github/workflows/release-staging.yml
Do the docs check in one step, and use the correct output variable (should be `$GITHUB_OUTPUT` and not `GITHUB_STATE`). The "log to release tracker" step relies on this being output from the step with the id `docs-check`, and not a later step. Also if this fails with an exit code it makes it look like the whole job failed which is bad UX, so removed that and just checked string length of output.
=> Do docs check in one step

.github/ISSUE_TEMPLATE/bug_report_v2.yaml
We will use those labels to help configure which hotlist the GitHub Issue mirroring bot puts each issue.
Also used by other firebase teams https://github.com/search?q=org%3Afirebase%20%22new%2C%20type%3A%20question%22&type=code
=> Add label for GitHub Issue hotlist mirroring

.github/workflows/canary-deploy.yml, .github/workflows/check-changeset.yml, .github/workflows/check-docs.yml, .github/workflows/check-pkg-paths.yml, .github/workflows/deploy-config.yml, .github/workflows/e2e-test.yml, .github/workflows/format.yml, .github/workflows/health-metrics-pull-request.yml, .github/workflows/lint.yml, .github/workflows/prerelease-manual-deploy.yml, .github/workflows/release-log.yml, .github/workflows/release-pr.yml, .github/workflows/release-prod.yml, .github/workflows/release-staging.yml, .github/workflows/release-tweet.yml, .github/workflows/update-api-reports.yml
E2E tests are failing because they use `firebase-tools` which has been recently updated. The latest version requires Node 16.13.0 or greater. We should probably update it across all workflows. We should not update it to 18 because our unit tests do not work in Node 18 due to needing to upgrade webpack.
=> Update Node version to 16 in workflows

scripts/release/utils/publish.ts
Try to ensure any errors in the spawn process that runs the npm publish command are sent to the console and not swallowed. May help debug problem publishing in staging:
https://github.com/firebase/firebase-js-sdk/actions/runs/4953536908/jobs/8861115245
=> Try to log publish errors

.changeset/quiet-cycles-complain.md
In https://github.com/firebase/firebase-js-sdk/pull/7176 the new Firestore setting `experimentalLongPollingOptions.timeoutSeconds` was implemented; however, that PR forgot to mark `@firestore/webchannel-wrapper` as needing a new release and, therefore, the upgraded google-closure-library dependency was not picked up in the v9.22.0 release. As a result, setting `experimentalLongPollingOptions.timeoutSeconds` in that version has no effect. This PR bumps the version of webchannel-wrapper so it will get released with the upgraded google-closure-library dependency that implements the long polling timeout feature.
Fixes: #6987
=> Firestore: Bump the version of webchannel-wrapper so that it gets released

scripts/release/utils/publish.ts
Restore https://github.com/firebase/firebase-js-sdk/pull/7295
It leaves very long logs so we need to get rid of it later or add an option, but we need this to better debug what's going wrong with the NPM publish.
=> Log publish details again

.github/workflows/release-staging.yml, scripts/release/utils/publish.ts
- Add a workflow option to set NPM publish `--verbose` option.
- Only print publish logs if a publish task failed
=> More logging for npm publish

.changeset/quiet-drinks-cross.md, .github/workflows/release-staging.yml, scripts/release/utils/publish.ts
Trying a few more things to fix or diagnose staging problems.
- bump memory limit in case memory is the issue (we do this on builds)
- ensure it always spits out all logs if the "verbose" option is enabled
=> More logging and increase memory limit

packages/auth/src/mfa/assertions/totp.test.ts, packages/auth/src/mfa/assertions/totp.ts, packages/auth/src/mfa/mfa_session.ts, packages/auth/src/mfa/mfa_user.test.ts, packages/auth/src/mfa/mfa_user.ts, packages/auth/src/platform_browser/mfa/assertions/phone.test.ts
Cleanup TOTP code to include Firebase User reference in MultiFactorSession. 
- Changed a field in MultiFactorSession from AuthInternal to UserInternal
- fixed corresponding tests and functions to match the type change.
Ran the code in demo app and was able to complete TOTP enrollment.
=> Cleanup TOTP code to include Firebase User reference in MultiFactorSession.

packages/auth/test/helpers/integration/helpers.ts, packages/auth/test/integration/flows/totp.test.ts
Reorganized the mfa totp integration tests such that the user that is enrolled for mfa will always be unenrolled at the end of each test. 
Ran TOTP MFA integration tests against the backend locally. Intentionally added "expect(2).to.equal(200)" in each test. 
Also tried adding the false statement into the beforeEach block that enrolls users before the test. 
Used curl command to check the status of the user's MFA enrollment. 
Successfully verified that the user is unenrolled from MFA at the end despite different test failures.
=> reorganized mfa totp integration tests

.github/ISSUE_TEMPLATE/bug_report_v2.yaml
An upate to transition the `type: question` label to simply `question`. This saves space on the Issue list page where many labels might be applied a single issue.
Pushed the `new` label to be second so that it sticks out more.
N/A
N/A
=> Update to the labels applied to new issues

packages/auth/test/helpers/integration/helpers.ts, packages/auth/test/integration/flows/totp.test.ts
Fixing variable name in test from fakePassword to password
=> Fixing interdependency in mfa totp integration tests ax

packages/firestore/test/unit/specs/existence_filter_spec.test.ts, packages/firestore/test/unit/specs/limbo_spec.test.ts, packages/firestore/test/unit/specs/listen_spec.test.ts
Remove the no-ios tag from bloom filter spec tests, now that the feature has been merged into the ios sdk in https://github.com/firebase/firebase-ios-sdk/pull/11457.
The spec test changes from this PR were ported to the Android SDK in https://github.com/firebase/firebase-android-sdk/pull/5088. Porting to the iOS SDK is not needed since these changes were included in https://github.com/firebase/firebase-ios-sdk/pull/11457.
=> Firestore: Remove the no-ios tag from bloom filter spec tests

scripts/ci/log-changesets.js
Seen some errors on the log for this job although it seems to complete fine. Try to catch the error (it says it's unhandled) and not stringify `data` until after the console.log line has read its properties.
=> Fix console log and error handling

packages/app/package.json, packages/app/rollup.config.js, packages/firebase/rollup.config.js, packages/firestore/package.json, packages/firestore/rollup.config.js, packages/firestore/rollup.shared.js, yarn.lock
These changes include: 
- Exporting the firestore and app typescript typings in a consumable way in google3 (without imports)
- Keep the class and function names in the minified firestore file (at runtime, consuming the obfuscated names proves very challenging)
=> Firestore Modular V9 Changes for Console

.changeset/sour-glasses-count.md, packages/firestore/rollup.config.js, packages/firestore/rollup.config.lite.js
Some of the bundles produced by Firestore's rollup pipeline generated source maps that incorrectly linked into yet another minified, mangled JavaScript file, instead of back into the original source code. This rendered the source maps useless because there was no way to get back to the original source code.
The root problem was that the rollup pipeline is done in a two step process. Step 1 produces a minified, mangled bundle and step 2 takes that minified, mangled bundle and produces other minified, mangled bundles. Surprisingly, _some_ of the source maps did indeed map back to the original source code (i.e. `index.esm5.js.map` and `index.node.cjs.js`) but others referenced the intermediate minified, mangled bundle (i.e. `index.esm2017.js`, `index.cjs.js`, `index.node.mjs`, and …
=> Firestore: fix source maps that incorrectly referenced back into the bundle itself

packages/auth/src/api/index.ts, packages/auth/src/api/password_policy/get_password_policy.test.ts, packages/auth/src/api/password_policy/get_password_policy.ts
Add an endpoint for fetching the password policy in auth, as this will be used to implement password validation against project/tenant policies.
=> Add password policy endpoint in auth (#1)

.github/workflows/test-all.yml
Lerna commands need to be run with yarn to use the locally installed version instead of the globally installed version on the Github VM (a much higher version).
=> Fix lerna commands in test-all.yml

packages/firestore/test/integration/api/aggregation.test.ts, packages/firestore/test/integration/api/array_transforms.test.ts, packages/firestore/test/integration/api/batch_writes.test.ts, packages/firestore/test/integration/api/bundle.test.ts, packages/firestore/test/integration/api/cursor.test.ts, packages/firestore/test/integration/api/database.test.ts, packages/firestore/test/integration/api/fields.test.ts, packages/firestore/test/integration/api/get_options.test.ts, packages/firestore/test/integration/api/index_configuration.test.ts, packages/firestore/test/integration/api/numeric_transforms.test.ts, packages/firestore/test/integration/api/query.test.ts, packages/firestore/test/integration/api/server_timestamp.test.ts, packages/firestore/test/integration/api/smoke.test.ts, packages/firestore/test/integration/api/transactions.test.ts, packages/firestore/test/integration/api/type.test.ts, packages/firestore/test/integration/api/validation.test.ts, packages/firestore/test/integration/api_internal/database.test.ts, packages/firestore/test/integration/api_internal/idle_timeout.test.ts, packages/firestore/test/integration/api_internal/transaction.test.ts
The Firestore integration tests are parameterized by the persistence type being used. All of the tests accept a `persistence` argument of type `boolean`. The tests unnecessarily explicitly specify the type `boolean` for this argument; however, the type can be omitted and deduced by the TypeScript compiler, leading to less code.
The immediate motivation of this change is to prepare for changing the type from `boolean` to some new type. By removing the explicit specification of `boolean`, a future change, https://github.com/firebase/firebase-js-sdk/pull/7404, will be able to change the type without actually affecting most of the test code that accepts the `persistence` argument. This will lead to a more targeted diff for that PR.
Note to reviewers: This small change reduced some of the line …
=> Firestore: remove explicit type from `persistence` argument in integration tests

.changeset/old-badgers-mate.md, common/api-review/auth.api.md, docs-devsite/auth.recaptchaverifier.md, packages/auth-compat/src/recaptcha_verifier.ts, packages/auth/demo/src/index.js, packages/auth/src/platform_browser/providers/phone.test.ts, packages/auth/src/platform_browser/recaptcha/recaptcha_verifier.test.ts, packages/auth/src/platform_browser/recaptcha/recaptcha_verifier.ts, packages/auth/src/platform_browser/strategies/phone.test.ts, packages/auth/test/integration/flows/phone.test.ts
Reorder RecaptchaVerifier params so auth is the first param (b/273333245)
=> Reorder RecaptchaVerifier params so auth is the first param

.changeset/two-bags-jog.md, docs-devsite/auth.md, packages/auth/index.doc.ts, packages/auth/index.rn.ts, packages/auth/package.json, yarn.lock
DO NOT MERGE until 6/20. This is a breaking change and must be released with a major version. It is expected to release with the next major version of the SDK in June 2023.
See internal doc: https://docs.google.com/document/d/1ZA1u7gfyIZjNpFY_v8DVBpBvDZAbxASl826OvjiTLvg/edit?resourcekey=0-AfgkOJV0qHh5waZvdLxucg#heading=h.9g9y2z36z0g9
getAuth() has been using`AsyncStorage` from the React Native core package, which was deprecated for a while and has now been removed. Users are expected to get `AsyncStorage` from the community package (`@react-native-async-storage/async-storage`) now. We have tried to bridge the gap for a while by using the core AsyncStorage as the default and allowing users to import the community AsyncStorage using `initializeAuth()`, but the core AsyncStorage no longer …
=> Use ReactNativeAsyncStorage from community package.

packages/firestore/test/integration/browser/indexeddb.test.ts, packages/firestore/test/integration/util/helpers.ts
The tests `'fails with code unimplemented'` and `'falls back without requiring a wait for the promise'` tests in `indexeddb.test.ts` were broken by https://github.com/firebase/firebase-js-sdk/pull/7404, which changed the way that "persistence" was tracked in the integration tests. These test failures were not noticed because they don't get executed by CI. This PR fixes the tests by providing a means to _not_ explicitly specify a `localCache` in `FirestoreSettings` and instead use the implicit default, which is required by these tests.
=> Firestore: Fix 'where indexeddb is not available' tests that were broken by persistence changes

packages/firestore/src/remote/watch_change.ts, packages/firestore/src/util/testing_hooks.ts, packages/firestore/test/integration/api/query.test.ts, packages/firestore/test/integration/util/testing_hooks_util.ts
Modify the test `'bloom filter should correctly encode special unicode characters'` in `query.test.ts`, that was added by the recent PR https://github.com/firebase/firebase-js-sdk/pull/7412, to directly check the bloom filter for containing the document paths with complex Unicode characters. Previously, it was indirectly checking this via the other properties of the existence filter. As a result, the "retry" logic was removed, since it doesn't matter if there is a false positive.
To add the ability to directly interrogate the bloom filter, the testing hooks needed to be augments to expose the "mightContain" method of `BloomFilter`.
=> Update test 'bloom filter should correctly encode special unicode characters' in query.test.ts

.changeset/empty-boats-dream.md, packages/firestore-types/index.d.ts
Update `index.d.ts` from the `firestore-types` package for the `FirestoreDataConverter` breaking API changes from https://github.com/firebase/firebase-js-sdk/pull/7310.
This fixes ~29 build errors that anyone using the `firestore-compat` library would get, that look like this:
```
node_modules/@firebase/firestore-compat/dist/src/index.d.ts:54:80 - error TS2707: Generic type 'CollectionReference<T>' requires between 0 and 1 type arguments.
54     function addDoc<AppModelType, DbModelType extends DocumentData>(reference: types.CollectionReference<AppModelType, DbModelType>, data: WithFieldValue<AppModelType>): Promise<DocumentReference<AppModelType, DbModelType>>;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I tested this change by creating a new npm project and running `npm …
=> Firestore: update firestore-types with breaking API changes for FirestoreDataConverter

.github/workflows/test-all.yml
Background:
We have required "test-changed" workflows that run on subsets of packages if they detect a file in that package has changed. We also had a non-required "test-all" workflow that runs all tests regardless of what changed. That workflow was extremely flaky so we recently split it into separate jobs to see if we could reduce flakiness: https://github.com/firebase/firebase-js-sdk/pull/7353
In that workflow we still kept firestore and firebase-firestore-integration-test tests grouped together, which may actually be causing a lot of the flakiness. Splitting them again into two separate jobs here.
=> Make firestore-integration its own job in "test all"

common/api-review/auth.api.md, packages/auth/src/core/auth/auth_impl.test.ts, packages/auth/src/core/auth/auth_impl.ts, packages/auth/src/core/strategies/email_and_password.test.ts, packages/auth/src/core/strategies/email_and_password.ts, packages/auth/src/model/auth.ts
Update AuthImpl to use the internal `PasswordPolicyImpl` for performing password validation. Also, update test cases to include fields used in the policy internally.
=> Update Auth to use PasswordPolicyImpl for validation

common/api-review/auth.api.md, docs-devsite/auth.passwordpolicy.md, packages/auth/src/core/auth/auth_impl.test.ts, packages/auth/src/core/auth/auth_impl.ts, packages/auth/src/core/auth/password_policy_impl.test.ts, packages/auth/src/core/auth/password_policy_impl.ts, packages/auth/src/core/strategies/email_and_password.test.ts, packages/auth/src/model/public_types.ts
Implement the `validatePassword` function in both `Auth` and `PasswordPolicyImpl`. Also, fix `PasswordPolicy.allowedNonAlphanumericCharacters` to be of type `string` instead of `string[]` to match the API proposal.
See [this PR](https://github.com/firebase/firebase-js-sdk/pull/7424) for previous discussion on this implementation.
=> Implement validatePassword endpoint and fix PasswordPolicy type to match API proposal

packages/auth/src/core/strategies/email_and_password.test.ts, packages/auth/src/core/strategies/email_and_password.ts
Update the cached password policy when the sign-in flow (signInWithEmailAndPassword) receives a `PASSWORD_DOES_NOT_MEET_REQUIREMENTS` error.
=> Update password policy in sign-in flow

packages/auth/src/core/auth/password_policy_impl.test.ts, packages/auth/src/core/auth/password_policy_impl.ts
Fix validatePasswordCharacterOptions to include the character options statuses even when an empty string is inputted.
=> Include the character option statuses even when an empty string is inputted to validatePassword

.changeset/eighty-roses-appear.md, packages/firestore/src/remote/rest_connection.ts, packages/firestore/test/unit/remote/rest_connection.test.ts, scripts/emulator-testing/emulators/firestore-emulator.ts
Fix named databases calls to backend with REST connection that experience error:
> Missing routing header. Please fill in the request header with format x-goog-request-params:project_id=mrenshaw-multi-db&database_id=my-database
=> Add `x-goog-request-params` to request header.

packages/firestore/test/integration/api/query.test.ts
The Firestore emulator does not (as of July 14, 2023) send an existence filter when a query is resumed by clients. As a result the client fails to delete documents that were deleted since the query was last run. The emulator will soon be fixed to send the existence filter (Googlers see b/270731363).
There are two bloom filter integration tests, the first of which tried to do as much as it could when running against the emulator and completing successfully if it got that far. That test, though, didn't really validate anything and by it passing it incorrectly implied that the bloom filter logic was validated. This test is now completely skipped when running against the Firestore emulator, which also makes the test simpler and easier to maintain.
These two bloom filter integration tests also …
=> Firestore: Disable bloom filter integration tests when using Firestore emulator

.changeset/odd-bats-hug.md, packages/auth/package.json, yarn.lock
Fixes https://github.com/firebase/firebase-js-sdk/issues/7448
This gives React Native users more flexibility over the exact version of `@react-native-async-storage/async-storage` to be used in their project.
=> Unpin version for React Native async storage dependency

packages/auth/demo/public/index.html, packages/auth/demo/public/style.css, packages/auth/demo/src/index.js
Update the auth demo to include a section for password validation. As a password is typed in, the status of requirements will be displayed and updated based on what is required by the policy.
See a quick demo at https://drive.google.com/file/d/1WlAkDJrZCS5qiMYSrNLk-LDWjquFPxTA/view?usp=sharing
=> Update auth demo to include password validation

packages/firestore/src/remote/watch_change.ts, packages/firestore/src/util/testing_hooks.ts, packages/firestore/test/integration/api/query.test.ts, packages/firestore/test/integration/util/testing_hooks_util.ts
In https://github.com/firebase/firebase-android-sdk/pull/5145, the internal bloom filter logic and the testing hooks were improved. This PR ports the relevant changes. There are no net behavior changes, only code cleanup and some minor refactoring.
Some minor changes made in this PR were ported to Android in https://github.com/firebase/firebase-android-sdk/pull/5177.
=> Firestore: Misc bloom filter cleanup ported from Android

common/api-review/auth.api.md, docs-devsite/auth.passwordpolicy.md, packages/auth/src/api/password_policy/get_password_policy.ts, packages/auth/src/core/auth/auth_impl.test.ts, packages/auth/src/core/auth/password_policy_impl.test.ts, packages/auth/src/core/auth/password_policy_impl.ts, packages/auth/src/core/strategies/email_and_password.test.ts, packages/auth/src/model/public_types.ts
Add the enforcementState and forceUpgradeOnSignin fields to the PasswordPolicy public type. These fields are not used internally for validation, but the developer can use them to determine if the password will be rejected during sign-in, sign up, or reset password flows.
=> Add enforcementState and forceUpgradeOnSignin to PasswordPolicy type

packages/auth/src/api/password_policy/get_password_policy.ts, packages/auth/src/core/auth/password_policy_impl.test.ts, packages/auth/src/core/auth/password_policy_impl.ts
The non-alphanumeric characters could be undefined when returned from the backend, even though they are not marked as optional. In this case, the SDK will store and return an empty string as part of the policy.
=> Fix bug when non-alphanumeric characters is undefined

packages/firestore/test/integration/api/query.test.ts
Use a different Firestore instance instead of a `WriteBatch` to avoid affecting the local cache in `query.test.ts`.
I had originally thought that `WriteBatch` sidestepped the local cache, just like a transaction did; however, that turned out to be incorrect and using a `WriteBatch` nullified the test cases that were modified to use it. This is a follow-up to https://github.com/firebase/firebase-js-sdk/pull/7415.
This PR was ported to the Android SDK in https://github.com/firebase/firebase-android-sdk/pull/5184.
=> Firestore: query.test.ts: use a different Firestore instance instead of a WriteBatch

.github/workflows/canary-deploy.yml, .github/workflows/e2e-test.yml
E2E tests are running on staging release and have already caught some key bugs, but staging is pretty late in the process to fix bugs. Because E2E runs on published NPM versions to test that the NPM publish/install process works, it can't be run on CI checks on PRs. The next best thing is to run it on canary builds, which are published every time a PR is merged to master.
I added an additional event type ("canary-tests") accepted by the e2e workflow so that in the future it can maybe handle notifications differently depending on if it's the staging tests or canary tests, but that's a TODO. For now all the notifications go to the "Firebase JS Core SDK Team" chat, which pretty much only consists of automated notifications.
=> Run E2E tests on canary releases

.github/workflows/test-all.yml
The test-all workflow builds in one job and runs tests in subsequent jobs, and it uses the upload-artifact and download-artifact GitHub Actions to deliver the build results between the build and test jobs.
The retention period for storing these artifacts was configured for 2 days. Unfortunately this made it difficult to debug failures or re-run flaky tests that failed over the weekend.
This change updates the retention to two weeks, which should be more than enough time.
Note that artifacts might not actually last two weeks. If we exceed our storage limits then the older artifacts will be automatically deleted to create more space for the newer workflow runs.
CI tests only, as this change affects only a single CI Workflow.
[CI Execution](https://github.com/firebase/firebase-js-sdk/actions/ …
=> increase GHA artifact retention from 2 to 14 days

packages/auth/src/core/auth/auth_impl.test.ts, packages/auth/src/core/auth/password_policy_impl.test.ts, packages/auth/src/core/auth/password_policy_impl.ts
The backend will enforce a minimum password length of 6 even if no minimum password length is configured. I created a backend bug for this, but we will also default to using this value in the SDK if no minimum length is set.
=> Use a default minimum password length of 6

packages/firestore/test/unit/local/query_engine.test.ts
The unit tests in `query_engine.test.ts` are parameterized on a `configureCsi` boolean variable. Some tests are if an `if (configureCsi)` block, some are in an `if (!configureCsi)` block, and others are in neither, and run for both values of `configureCsi`. However, the entire test suite was inside the `if (!configureCsi)` block, nesting the checks for `if (configureCsi)` which would unconditionally evaluate to false, causing those tests to never be run. This was likely a coding accident due to the subtle indenting difference.
This PR fixes this by putting the `if (configureCsi)`, `if (!configureCsi)`, and the other block at the same nesting level so that the appropriate tests are run for the appropriate values of `configureCsi`.
Note to reviewers: Turn off whitespace when looking at the …
=> Firestore: query_engine.test.ts: fix logic that checks `configureCsi`

packages/firestore/src/api.ts, packages/firestore/src/lite-api/settings.ts
Expose PrivateSettings interface as an internal type for the Firestore console. It was exported in the previous version of the non-modular firestore SDK we used in console.
=> Export internal interface PrivateSettings for console

packages/auth/src/core/strategies/email_and_password.test.ts, packages/auth/src/core/strategies/email_and_password.ts
Fix the handling of recaching the password policy in the sign up flow to not conflict with the handling of other errors (like MISSING_RECAPTCHA_TOKEN).
The missing token error doesn't occur in the password reset flow (only occurs and is handled when getting the OOB code), so I have only included test cases for sign up and sign-in.
=> Fix password policy recaching in sign up

packages/firestore/test/util/equality_matcher.ts
This PR fixes a bug in Firestore's unit/integration testing framework where a "deep equals" assertion check would _omit_ the custom failure message, when it should have _included_ the custom failure message.
For example, consider the following "expect" checks:
```ts
expect({foo: 42}, 'custom message').to.deep.equal({bar: 42});
expect({foo: 42}).to.deep.equal({bar: 42}, 'custom message');
```
Both of these checks will unconditionally fail because `{foo: 42}` does not "deep equal" `{bar: 42}`. Also, both the checks specify a custom failure message to be incorporated into the failure message, albeit in different ways.
The problem is that the custom message is _not_ included in the ultimate failure message:
```
AssertionError: expected { foo: 42 } to roughly deeply equal { bar: 42 }
```
With …
=> Firestore: equality_matcher.ts: fix missing custom assertion failure message in deep equals

.changeset/quiet-gorillas-smoke.md, packages/firestore/src/core/query.ts, packages/firestore/src/lite-api/query.ts, packages/firestore/src/remote/datastore.ts, packages/firestore/test/unit/core/query.test.ts
=> Fix: Aggregate query order-by normalization

common/api-review/auth.api.md, docs-devsite/auth.md, packages/auth/demo/src/index.js, packages/auth/src/api/authentication/token.test.ts, packages/auth/src/api/authentication/token.ts, packages/auth/src/api/index.ts, packages/auth/src/core/auth/auth_impl.ts, packages/auth/src/core/index.ts, packages/auth/src/core/user/token_manager.test.ts, packages/auth/src/model/auth.ts
Implement revokeAccessToken public api. 
Note:
-Did not add tests to [auth_impl.test.ts](https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth/src/core/auth/auth_impl.test.ts) because backend doesn’t return anything for revokeToken api and we cannot verify if apple oauth access token is revoked in auth_impl.test.ts. Please let me know if I’m wrong or there are ways to test `auth_impl#revokeAccessToken`.
-Tested with demo app and was able to revoke apple oauth access token. However, wasn't able to test in multi-tenancy environment because firebase test project doesn't support multi-tenancy and I don't have a personal project that has Apply sign in provider set up.
TODO: Write integration tests if we can retrieve the apple oauth access token in the testing environment.
=> Implement revokeAccessToken public api

packages/firestore/test/integration/api/database.test.ts, packages/firestore/test/integration/api/numeric_transforms.test.ts, packages/firestore/test/integration/api/query.test.ts
=> Fix and skip flaky Firestore tests

config/webpack.test.js, integration/firebase/test/namespace.test.ts, integration/firestore/package.json, package.json, packages/auth-compat/test/helpers/helpers.ts, packages/auth/package.json, packages/auth/test/helpers/integration/helpers.ts, patches/karma-webpack+5.0.0.patch, repo-scripts/size-analysis/package.json, yarn.lock
See internal doc ([go/update-webpack-to-v5-firebase-js-sdk](https://goto.google.com/update-webpack-to-v5-firebase-js-sdk)) for issues upgrading so far. This is needed to allow us to upgrade to Node 18+.
Continues https://github.com/firebase/firebase-js-sdk/pull/7374
=> Upgrade webpack to v5

.changeset/mean-candles-approve.md, packages/auth/src/core/auth/auth_impl.ts
This will fix the issue reported in #7383.
I have implemented a change that only requires a small adjustment in the code. 
This patch has resolved the issue in the reproduction project that I reported (https://github.com/omochi/firebase-auth-js-cancel-bug).
=> [Auth] Fix auth event uncancellable bug

config/webpack.test.js, integration/firestore/package.json, yarn.lock
1. Update webpack-stream to a version compatible with webpack 5
2. Supply defaults in webpack.EnvironmentPlugin for RTDB_EMULATOR_PORT and RTDB_EMULATOR_NAMESPACE variables. If there's no defaults, webpack will error if they aren't defined in the shell environment. The only place they are used is in RTDB emulator tests, and the check for whether to use them is basically `!!RTDB_EMULATOR_PORT`: https://github.com/firebase/firebase-js-sdk/blob/master/packages/database/test/helpers/util.ts#L39 So setting them both to false if they are undefined in the shell environment should be a good default that results in the same behavior as before.
=> Fix webpack env variable settings

.changeset/nervous-cups-relax.md, packages/firestore/src/platform/browser/webchannel_connection.ts, packages/webchannel-wrapper/src/index.d.ts
Fixes: https://github.com/firebase/firebase-js-sdk/issues/6118
=> Fix how we enable fetch streams.

.changeset/eleven-lamps-give.md, packages/auth/index.rn.ts, packages/auth/package.json, yarn.lock
See https://github.com/firebase/firebase-js-sdk/issues/7522
In 10.0.0 we added `@react-native-async-storage/async-storage` as a dependency to make things more convenient for React Native users, enabling us to automatically include it as a persistence method for auth. Unfortunately this causes a number of warnings and unexpected issues for non-React Native users. We cannot give the React Native bundle a separate set of dependencies without making a separate NPM package for it. The best compromise is to set the dependency list in a way that works for the majority of users, and document how React Native users can provide an AsyncStorage import to enable auth state persistence.
So this involves 2 steps:
1) Move the dependency to an optional `peerDependency`, using `peerDependenciesMeta` to …
=> Remove dependency on @react-native-async-storage/async-storage

.github/workflows/test-all.yml, .github/workflows/test-changed-auth.yml, packages/auth/test/integration/webdriver/redirect.test.ts
We currently [pin Chrome v110](https://github.com/firebase/firebase-js-sdk/blob/master/.github/workflows/test-changed-auth.yml#L17-L23) on CI as tests in https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth/test/integration/webdriver/redirect.test.ts became flaky on version 111.
This change fixes these flaky tests and pins Chrome v114. 
**Why do we pin v114 but not install the latest Chrome version?**
https://chromedriver.chromium.org/downloads only goes up to version 114, so ChromeDriver installation will fail with higher versions: `"No such object: chromedriver/LATEST_RELEASE_115.0.5790"`. According to that website, starting with version 115 [these JSON endpoints](https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints) should be used to determine …
=> Fix flaky auth webdriver tests

packages/firestore/test/unit/local/local_store.test.ts, packages/firestore/test/unit/local/local_store_indexeddb.test.ts
In #7542 and #7587 I added local store unit tests for client-side index auto-creation logic into `local_store.test.ts`, which contains the generic unit tests that apply to both "memory" local store and "indexeddb" local store. But since client-side indexing is purely a feature of indexeddb local store, I should have put the tests into `local_store_indexeddb.test.ts`. This PR moves the tests into the correct file. This has the added benefit that uses a more modern and more readable "await" style testing rather than the promise chaining used in the generic tests.
=> Firestore: Move local store index auto-creation unit tests into the proper file

packages/firestore/src/local/query_engine.ts
In `query_engine.ts` the `DEFAULT_RELATIVE_INDEX_READ_COST_PER_DOCUMENT` value was hardcoded as `2`, which was just copied from the Android SDK. Some experimentation has been done and we found that this value should not be hardcoded universally, but should be adjusted based on the browser/OS on which the code is running. More experiment data is needed, so changing the hardcoded value to `8` is the lowest-common-denominator of the experiment data captured so far. A later PR will refine this value.
=> Firestore: Set DEFAULT_RELATIVE_INDEX_READ_COST_PER_DOCUMENT to 8 in query_engine.ts

packages/firestore/test/integration/api/persistent_cache_index_manager.test.ts, packages/firestore/test/unit/local/local_store_indexeddb.test.ts, packages/firestore/test/unit/model/target_index_matcher.test.ts
Port testing improvements for persistent cache auto indexing from the Android SDK: https://github.com/firebase/firebase-android-sdk/pull/5213
=> Firestore: Increase test coverage for persistent cache indexing

scripts/docgen-compat/generate-docs.js
Forgot to remove some variables and references when removing the Node portion of this script. Probably would have caught it if it was in TypeScript.
=> Fix compat doc gen

.github/workflows/test-all.yml
Fixed a misaligned indentation on line #107 of `test-all.yaml` that cause a workflow execution failure in GitHub Action CI.
Includes an update to all of the `test-all.yml` chrome installation steps to use the `npx` install method.  
There's a Failure in `(Firestore) Node.js and Browser (Chrome) Tests`, but this existed even before the npx update (when installing Chrome via `apt-get`). [See this previous run](https://github.com/firebase/firebase-js-sdk/actions/runs/6254022106/job/17001301255). Since the Firestore issue still remains, the has been disabled (will skip) for now.
Also fixed the a problem setting the max heap size for node. Previous attempts echoed the value to the GITHUB_ENV variable on the command line, but this was producing errors. Changed it to use the worfklow `env:` …
=> Fix to test-all .github workflow yaml file.

.github/workflows/test-changed-firestore-integration.yml, .gitignore, common/api-review/firestore.api.md, integration/firestore/gulpfile.js, packages/firestore/src/api.ts, packages/firestore/src/util/misc.ts, packages/firestore/test/integration/api/README.md, packages/firestore/test/integration/api/composite_index_query.test.ts, packages/firestore/test/integration/util/composite_index_test_helper.ts, packages/firestore/test/integration/util/helpers.ts
=> Fix composite index testing build bug

.changeset/lucky-dragons-juggle.md, packages/auth/src/core/credentials/email.ts, packages/auth/src/core/strategies/email_and_password.ts, packages/auth/src/core/strategies/email_link.ts, packages/auth/src/platform_browser/recaptcha/recaptcha_enterprise_verifier.test.ts, packages/auth/src/platform_browser/recaptcha/recaptcha_enterprise_verifier.ts
All flows manually verified in the demo app. Gonna add the unit tests in a separate PR.
=> Create handleRecaptchaFlow helper method

docs-devsite/app-check.md, packages/app-check/src/api.ts
=> Fix typo in JSDoc

.github/workflows/test-changed-firestore-integration.yml
In firestore integration workflow, Terraform fails due to "index already exists" error. We can safely ignore this.
=> Add message to Firestore workflow terraform failure

.changeset/real-ants-notice.md, packages/firestore/src/platform/browser/webchannel_connection.ts
Rolling back the use of useFetchStreams, which has lead to hanging queries.
Writing additional automated tests for this is non-trivial. This change has been tested locally using `yarn link` against a reproduction project. This change can be pushed alone, or it can wait for automated tests to be written.
This is the original change we're rolling back: https://github.com/firebase/firebase-js-sdk/pull/7569/files#diff-a0dc4840c5dc14c6bd4f1a172930675ddde606430fbc23bc613aca0cbd6d031d
=> Rolling back the use of useFetchStreams, which has lead to hanging queries.

.changeset/strong-coins-repeat.md, packages/firestore-compat/src/api/database.ts, packages/firestore-compat/test/database.test.ts
This is to resolve issue: https://github.com/firebase/firebase-js-sdk/issues/7719
A converter can return undefined, so we should not fail when data is undefined in compat library.
=> Support converter that returns undefined.

.changeset/tiny-items-grin.md, packages/auth/src/api/account_management/email_and_password.test.ts, packages/auth/src/api/account_management/email_and_password.ts, packages/auth/src/api/authentication/sign_up.ts, packages/auth/src/core/credentials/email.test.ts, packages/auth/src/core/credentials/email.ts
The /signUp API supports linking when Email Enumeration Protection is enabled as well as disabled. /setAccountInfo does not work when Email Enumeration Protection is enabled.
Verified with the test app that anonymous user upgrade works.
=> Update the linkWithCredential API to call the signUp endpoint

.changeset/eight-planets-sleep.md, common/api-review/auth.api.md, docs-devsite/auth.md, packages/auth/demo/src/index.js, packages/auth/src/api/authentication/token.test.ts, packages/auth/src/api/authentication/token.ts, packages/auth/src/api/index.ts, packages/auth/src/core/auth/auth_impl.ts, packages/auth/src/core/index.ts, packages/auth/src/core/user/token_manager.test.ts, packages/auth/src/model/auth.ts
Currently only supports Apple OAuth Access token revocation.
=> Implement token revocation public api

.changeset/chilly-emus-sit.md, packages/app/src/heartbeatService.ts
There seems to be a potential scenario in the heartbeat service running in the Opera browser (#7736) that the heartbeatCache exists but it's an empty object. The code implementation encounters errors in these cases as it assumes the heartbeatCache has a heartbeats array. This change better detects these empty object cases and treats them in a similar way as if there's nothing in the heartbeatCache. 
CI
None.
=> [Heartbeat Service] Guard against empty heartbeat caches.

integration/messaging/package.json, integration/messaging/test/utils/sendMessage.js, packages/rules-unit-testing/package.json, packages/rules-unit-testing/src/impl/rules.ts, packages/rules-unit-testing/src/impl/test_environment.ts, packages/rules-unit-testing/src/util.ts, packages/rules-unit-testing/test/util.test.ts, packages/storage/src/implementation/type.ts, scripts/emulator-testing/emulators/emulator.ts
Some of our build/test targets from ddb-upgrade-node-fetch still require a migration from node-fetch to undici. These remaining changes aren't straightforward so I'm creating a sub branch to iron out the required changes.
Local / CI
N/A
=> Update remaining test targets to use undici

.github/workflows/e2e-test.yml, .github/workflows/health-metrics-pull-request.yml, .github/workflows/release-staging.yml, .github/workflows/test-all.yml, .github/workflows/test-changed-auth.yml, .github/workflows/test-changed-fcm-integration.yml, .github/workflows/test-changed-firestore-integration.yml, .github/workflows/test-changed-firestore.yml, .github/workflows/test-changed-misc.yml, .github/workflows/test-changed.yml, .github/workflows/test-firebase-integration.yml
TLDR; This change migrates the configuration of NODE_OPTIONS from shell commands within individual jobs, to GitHub Workflow `env:` directives which apply to all jobs on the runner.
Our workflows attempted to configure the NODE_OPTIONS environment variable by executing the following shell command:
```
echo "NODE_OPTIONS=--max_old_space_size=4096" >> $GITHUB_ENV
```
This was once supported by GitHub Actions, but no more. Attempts at env config in this way produces [errors in our workflows](https://github.com/firebase/firebase-js-sdk/actions/runs/6869300208/job/18681776630#step:5:5) and the configuration fails to stick. In the worst case, this could be part of test flakiness, but at the least it's producing needless [error messages in the Annotation section our Workflow …
=> Fix GitHub Action Worfklow env configuration of node 'max_old_space_size'.

packages/auth/src/api/account_management/mfa.test.ts, packages/auth/src/api/account_management/mfa.ts, packages/auth/src/api/authentication/mfa.test.ts, packages/auth/src/api/authentication/mfa.ts, packages/auth/src/api/authentication/sms.test.ts, packages/auth/src/api/authentication/sms.ts, packages/auth/src/api/index.ts, packages/auth/src/platform_browser/recaptcha/recaptcha.test.ts, packages/auth/src/platform_browser/recaptcha/recaptcha.ts, packages/auth/src/platform_browser/recaptcha/recaptcha_enterprise_verifier.test.ts, packages/auth/src/platform_browser/recaptcha/recaptcha_enterprise_verifier.ts
This is the pre-req for reCAPTCHA Enterprise and phone auth integration support.
- Add Phone provider and action names
- Add reCAPTCHA Enterprise fields to phone API requests
- Update injectRecaptchaFields to inject recaptcha enterprise fields into phone API requests
Tested the following flows with the demo app:
- Phone Auth
- SMS MFA
- Email auth with reCAPTCHA Enterprise
=> Update injectRecaptchaFields to inject recaptcha enterprise fields into phone API requests

.changeset/olive-dogs-play.md, packages/firestore/src/core/firestore_client.ts, packages/firestore/src/core/sync_engine_impl.ts, packages/firestore/src/core/view.ts, packages/firestore/test/unit/core/view.test.ts, packages/firestore/test/unit/local/query_engine.test.ts, packages/firestore/test/unit/specs/limbo_spec.test.ts, packages/firestore/test/unit/specs/limit_spec.test.ts
While resuming a query and there is an existence filter mismatch detected, SDK updated the limbo docs without waiting for a full re-query result. 
Ported to android in https://github.com/firebase/firebase-android-sdk/pull/5506 and ios in https://github.com/firebase/firebase-ios-sdk/pull/12044.
=> Fix docs unnecessarily undergo limbo resolution while resuming query bug

packages/auth/test/integration/webdriver/compat/firebaseui.test.ts, packages/auth/test/integration/webdriver/redirect.test.ts
* Webdriver redirect tests started to fail on CI.
* This PR disables the failing tests to unblock other PRs.
* We will investigate, fix, and enable the tests again.
=> Disable all webdriver redirect tests

.changeset/shiny-houses-stare.md, packages/app-check/src/proactive-refresh.ts
Install catch handlers for promises in the Derferred object used by in AppCheck. There were some cases where the promise was cancelled and this bubbled up error messages to our clients' applications despite this being expected behavior.
This change is to alleviate the logging reported in issue #7805.
CI.
N/A
=> [App Check] Install catch handler for promise in Deferred.

.changeset/wet-moons-wave.md, packages/database/package.json
An import of `@firebase/app-check-interop-types` was added to the standalone entry points (consumed by admin-node) in https://github.com/firebase/firebase-js-sdk/pull/7258
This dep wasn't getting installed when consumed by the admin-node package because admin-node only installs `@firebase/database-compat` and not the umbrella `firebase` package.
In this PR the dep is being added in `@firebase/database` but will be installed transitively as `database-compat` depends on `database`. This is already working for `auth-interop-types`. We just need to add `app-check-interop-types` in the same place.
=> Add app-check-interop-types dependency to database

.changeset/cold-carpets-sing.md, packages/firestore/src/core/component_provider.ts, packages/firestore/src/platform/node/grpc_connection.ts, packages/firestore/src/remote/connection.ts, packages/firestore/src/remote/datastore.ts, packages/firestore/src/remote/rest_connection.ts, packages/firestore/test/unit/remote/datastore.test.ts, packages/firestore/test/unit/specs/spec_test_components.ts
Fix leak of grpc-js resources on terminate.
Fixes https://github.com/firebase/firebase-js-sdk/issues/7747
=> Fix: Leak of grpc resources on terminate.

.github/workflows/deploy-config.yml, .github/workflows/e2e-test.yml, config/functions/package.json
Updates to our E2E tests in CI (`E2E Smoke Tests` and `Deploy Project Config`) to use Node v18. Additionally, pin the firebase-tools version to 12.9.1. While we plan to upgrade the firebase-tools version in the future, we're chosing to pin to a version for the long term to prevent suddent CI test failures.
[Executed a E2E test in CI](https://github.com/firebase/firebase-js-sdk/actions/runs/7187075863).
N/A.
=> Fix E2E runtime - pin Firebase Tools, node 18 runtime

.changeset/yellow-houses-happen.md, packages/firestore/src/lite-api/user_data_reader.ts, packages/firestore/test/lite/integration.test.ts
fix [7706](https://github.com/firebase/firebase-js-sdk/issues/7706)
Change the `isEqual` from identity equality check to comparing properties.
=> Update isEqual for arrayUnion, arrayRemove, and increment 

packages/firestore/test/unit/core/filter.test.ts
Improve a Firestore unit test by comparing Query objects rather than comparing Target objects.
=> Use canonifyQuery rather than canonifyTarget in unit test.

repo-scripts/size-analysis/bundle-definitions/firestore.json
Add a new size report for Firestore: "Read Write w Persistence". This is a bundle size for an app that calls getDoc, setDoc, and enables IndexedDb persistence.
=> Add size report for Firestore read & write w/ persistence

.github/workflows/e2e-test.yml, config/firebase.json
Previously we ran into an issue where we couldn't use the latest firebase-tools CLI version (v13+) due to an error attempting to deploy the E2E cloud function.
The error was due to a new requirement of the CLI that `firebase.json` requires a `functions` configuration. This change adds that configuration and pins the firebase CLI version to 13.
Forced [a CI execution](https://github.com/firebase/firebase-js-sdk/actions/runs/7241120102) on push.
N/A
=> [E2E CI] Update firebase-tools to v13.0.2

package.json, yarn.lock
The Firetore build process logged errors when importing undici complaining about a lack of definition of `Blob`. This change updates the @types/node version from `12.20.50` to `16.18.68` which fixes the issue.
Local builds.
CI.
N/A.
=> Upgrade @types/node dev dependency to v16.18.68

packages/firestore/src/local/index_backfiller.ts
Fix spelling typos in `index_backfiller.ts` log messages: "IndexBackiller" -> "IndexBackfiller"
=> Firestore: index_backfiller.ts: fix spelling typos in log messages

packages/firestore/src/core/firestore_client.ts
This is a minor implementation detail change in Firestore where a method was unnecessarily declared as `async` and was change to a simple property access. This has little (if any) performance improvement but makes the code a bit clearer for future readers. No functionality was changed.
=> Firestore: firestore_client.ts: async getConfiguration() -> get configuration()

packages/firestore/src/core/component_provider.ts
This PR makes a few tiny code improvements to the `terminate()` functions in `component_provider.ts`:
1. Simplify some `if` blocks checking for and object being null with more concise null chaining (i.e. the `?.` operator).
2. Remove `await` from function calls that simply return `void`, which make the `await` superfluous and potentially confusing.
3. Explicitly call `indexBackfillerScheduler?.stop()`, just like how `gcScheduler?.stop()` is called. This doesn't really affect anything because the scheduled job is cancelled by virtue of the AsyncQueue being shut down, but it's probably best not to rely on that implementation detail of the scheduler.
=> Firestore: component_provider.ts: cleanup terminate() functions

packages/firestore/src/local/indexeddb_index_manager.ts, packages/firestore/src/local/local_serializer.ts, packages/firestore/test/unit/local/local_serializer.test.ts
This PR makes a tiny change to an internal function named `toDbIndexState()`. Formerly, this function had a `User` argument, of which only the `uid` property was used. If the given user was unauthenticated, then the empty string was used instead. This, however, is an implementation detail of the single call site which uses an empty string as the "uid" of an unauthenticated user.
To avoid this implementation detail bleeding into the `toDbIndexState()` function, this PR changes the argument from a `User` to simply a `string`, whose value is the "uid" to use. The caller, then is responsible for mapping the unauthenticated user to the correct string, keeping that implementation detail in one place.
This PR does not actually change any functionality, but merely cleans up the code a bit.
=> Firestore: local_serializer.ts: change toDbIndexState() argument from user:User to uid:string

.changeset/good-seals-promise.md, packages/app/src/indexeddb.ts
This is part of the platform logging code and errors should not block any Firebase functionality.
Sometimes in Safari (and other Safari-based browsers), db.createObjectStore() triggers a "the database is not running a version change transaction" error which is not supposed to happen inside the onupgradeneeded event handler (abstracted to `upgrade` in the `idb` wrapper). Would guess this is an error in Safari or `idb`. We will just catch and warn for now to avoid spamming monitoring logs or crashing the app.
Fixes https://github.com/firebase/firebase-js-sdk/issues/7829
=> Catch possible Safari error

.github/workflows/test-changed-firestore.yml, packages/firestore/test/integration/api/query.test.ts
Skip the tests against Firestore nightly as a PR presubmit check, it is activated when the workflow is manually triggered still.
=> Disable nightly run with PR

repo-scripts/size-analysis/bundle-definitions/firestore.json
Add two new size reports for Firestore: "CSI Auto Indexing Enable" and "CSI Auto Indexing Disable and Delete". These calculate how much client-side indexing contributes to the bundle size. These numbers will help prioritize the work to make the client-side indexing code tree-shakeable (https://github.com/firebase/firebase-js-sdk/pull/7902).
=> Add size report for Firestore client-side indexing

packages/firestore/test/unit/local/local_store_indexeddb.test.ts
Fix some spurious test failures that get reported if some of the "before" actions of a test fail. Specifically, calling
```
persistence.shutdown()
```
would throw a
```
Uncaught TypeError: Cannot read properties of undefined
```
error if the "before" step that initialized the `persistence` variable failed before setting it.
Although this isn't a problem, it adds noise to a test failure that may already be difficult enough to debug.
The fix is simple: just _conditionally_ call the method only if the object is defined; that is, change it to
```
persistence?.shutdown()
```
=> Firestore: local_store_indexeddb.test.ts: fix spurious errors on test cleanup

.changeset/witty-comics-rule.md, packages/firestore/src/local/query_engine.ts
A previous PR, https://github.com/firebase/firebase-js-sdk/pull/7608, hardcoded the value of `DEFAULT_RELATIVE_INDEX_READ_COST_PER_DOCUMENT` to 8. At the time, this was the "worst case" value, but penalized many platform/browser combinations that would experience performance benefits from a lower value.
Since then, an experiment was performed to calculate a more reasonable value. These optimal values were:
1. 8 for Safari
2. 6 for Android
3. 4 for everything else (e.g. desktop browsers)
This PR changes the hardcoded value of 8 to one of the values above, depending on the runtime environment.
=> Firestore: Choose DEFAULT_RELATIVE_INDEX_READ_COST_PER_DOCUMENT value based on the browser, rather than hardcoding 8

packages/firestore/src/local/query_engine.ts
Move the client-side indexing code in the `QueryEngine` class into its own, separate class. A later PR will further modify the `QueryEngine` class to allow that new class, named `QueryEngineFieldIndexPlugin`, to be "installed" independently into an instance of `QueryEngine` so that it can be tree-shaken away if not used.
The diff of this PR is more complicated than the changes really are. The main changes are:
1. Move the `performQueryUsingIndex()` and `createCacheIndexes()` method of the `QueryEngine` class into the new class `QueryEngineFieldIndexPlugin`.
2. Move some private methods of `QueryEngine` to top-level functions so that they can be shared by both `QueryEngine` and `QueryEngineFieldIndexPlugin`, namely `applyQuery()`, `needsRefill()`, and `appendRemainingResults()`.
3. Add a …
=> query_engine.ts: move CSI code into its own class

.github/workflows/check-changeset.yml, scripts/ci/check_changeset.ts
Here is an example of this change causing the workflow to correctly report the results:
From https://github.com/firebase/firebase-js-sdk/actions/runs/7586489122/job/20664769245
From https://github.com/firebase/firebase-js-sdk/actions/runs/7587195474/job/20666981441
=> Fix errors in reporting errors in the "Check changeset vs changed files" workflow

.changeset/purple-cooks-explode.md, packages/util/src/environment.ts
In https://github.com/firebase/firebase-js-sdk/pull/7929 some logic was added to Firestore to check for the browser being Safari. This new check for `isSafari()` unexpectedly threw an exception in React Native. This PR fixes the exception by explicitly checking for an object not being `undefined` before using it.
Fixes https://github.com/firebase/firebase-js-sdk/issues/7962
=> Fix isSafari() throwing on React Native (fixes #7962)

.changeset/cyan-apes-listen.md, packages/database/src/api/Reference_impl.ts, packages/database/test/queryconstraint.test.ts
Fixes #7835. Originally, we set the type of `type` to be a string, but that didn't actually set the value of the property (`s/:/=`)
=> Fixed issue where queryConstraint.type was undefined

docs-devsite/auth.googleauthprovider.md, docs-devsite/auth.md, packages/auth/src/core/providers/google.ts
Fixed a duplicate 'an' string in documentation for the `GoogleAuthProvider` class.
=> docs: Fix 3 typos

.changeset/few-drinks-kiss.md, packages/app/src/indexeddb.ts
The `idb` library we use has a `done` promise on all transactions, which can throw unhandled rejections. It must be included in all try/catch blocks in order to avoid an unhandled rejection.
This is part of the platform logging functionality, which should never throw or block user app functionality. This change ensures it will be caught along with all other transaction errors and converted to a `console.warn`.
=> Catch transaction.done errors

packages/app/src/api.test.ts, packages/app/src/api.ts, packages/app/src/firebaseServerApp.test.ts, packages/app/src/firebaseServerApp.ts
Mangle the name of the app based on the hash of the parameters passed in.
In addition, return the same app when the same parameters are used.
Added more unit tests.
CI.
N/A.
=> [ServerApp] Mangle the FirebaseServerApp name

docs-devsite/analytics.gtagconfigparams.md, docs-devsite/analytics.md, packages/analytics-types/index.d.ts, packages/analytics/src/api.ts, packages/analytics/src/public-types.ts, packages/firebase/compat/index.d.ts
Old page-view page is gone. New page is https://developers.google.com/analytics/devguides/collection/ga4/views
=> update page-view links in analytics docs

packages/app/src/api.test.ts, packages/app/src/api.ts, packages/app/src/firebaseServerApp.ts
Update the `FirebaseServerApp` creation to return the same object if an existing object exists with the same configuration. However, the `deleteOnDeref` field is ignored when detecting duplicate apps, since that object reference could vary across multiple SSR rendering passes.
The hope is that a `FirebaseServerApp` instance awaiting deletion from a the `deleteOnDeref` feature maybe be reused if another SSR pass occurs in rapid succession, there by speeding up the SSR code.
Updated tests to ensure that `FirebaseServerApps` are being deleted properly.
Added new tests to track reference counting.
N/A.
=> [ServerApp] RefCount FirebaseServerApps

docs-devsite/auth.auth.md, docs-devsite/auth.md, docs-devsite/auth.user.md, packages/auth/src/core/auth/auth_impl.ts, packages/auth/src/core/index.ts, packages/auth/src/core/strategies/anonymous.ts, packages/auth/src/core/strategies/credential.ts, packages/auth/src/core/strategies/custom_token.ts, packages/auth/src/core/strategies/email_and_password.ts, packages/auth/src/core/strategies/email_link.ts, packages/auth/src/core/user/account_info.ts, packages/auth/src/core/user/reauthenticate.ts, packages/auth/src/core/user/user_impl.ts, packages/auth/src/model/public_types.ts, packages/auth/src/platform_browser/strategies/phone.ts, packages/auth/src/platform_browser/strategies/popup.ts, packages/auth/src/platform_browser/strategies/redirect.ts, packages/auth/test/integration/flows/firebaseserverapp.test.ts
Updates FirebaseServerApp implementation in Auth to prevent operations that would change the currently logged in user. The user should be that of the authIdToken provided to FirebaseServerApp only.
Note: some of the method implementations currently reside in browser-only files. I added safe guards to these methods even though FirebaseServerApp is not supported in browser enviornments.  These guards protect us in case the methods are later adapted to other environments and/or migrated to other files that are not browser-only. The changes to the browser implementations produce little overhead, so I thought that safety first was the correct call here.
New tests added.
N/A
=> [SeverApp] Restrict certain auth operations

.github/workflows/test-all.yml, .github/workflows/test-changed-auth.yml, integration/messaging/package.json, packages/auth/package.json, yarn.lock
We're having some CI issues on npm install for auth tests. Seems to be related to a new url for downloading chrome.
https://github.com/puppeteer/puppeteer/pull/11923
I bumped the `chromedriver` NPM package to version 116.0.0 because I think it needs to be above 115 in order to use this env variable (see https://github.com/giggio/node-chromedriver?tab=readme-ov-file#for-versions--115) but starting with 117.0.0 it requires Node 18+ which we're not ready to convert our workflows to.
=> Fix chromedriver issue 2

.changeset/thirty-otters-hug.md, packages/auth/src/platform_browser/index.ts
The `_authTokenSyncURL` property coming from the __FIREBASE_DEFAULTS__ autoinit (for frameworks tooling) should only point to the same domain and be a relative path. Do not set the cookie if this is not a relative path (such as if it is a full url), as this could be a possible vulnerability.
See b/327386166
=> Enforce authTokenSyncURL being a path and not a url.

.changeset/selfish-donkeys-cheer.md, packages/firebase/package.json
We are upgrading all our Github workflows from Node 16 and Node 20, and noticed this broke E2E tests that install from NPM.
It seems sometime between Node 16 and Node 18 there may have been a bump in NPM version, and this NPM change has a difference in the way it handles glob patterns in the `files` field `package.json`. Previously we used the pattern `"**/dist/"` and it included any file in any `dist` folder under `packages/firebase`, but after the bump to Node 20 (and consequent NPM version bump) it only included `package.json` files, no js or ts files, basically removing the entry points to all modular versions of products.
When changed to `"**/dist/**/*"`, it seems to work as it previously did.
If not fixed, this will break all releases.
=> Fix glob pattern to work with Node 20 and its NPM version

.changeset/bright-avocados-attack.md, packages/auth/src/platform_browser/index.ts
Additional fix to https://github.com/firebase/firebase-js-sdk/pull/8056 to prevent the string beginning with a double slash.
=> Prevent using authTokenSyncURL if the string begins with a double slash

.github/workflows/test-all.yml, scripts/ci/check_changeset.ts
A Firestore CI test configuration was previously disabled in our GitHub action Workflows due to a 100% failure rate. While revisiting this issue months later, it seems that the test now passes. This might be related to our Node v20 CI upgrade.
As a bonus, fixed a comment typo in the check changeset script.
CI
N/A
=> Enable previously failing `(Firestore) Node.js and Browser (Chrome) Tests`

packages/auth/src/core/auth/auth_impl.ts, packages/auth/src/core/auth/initialize.ts
It turns out the FirebaseServerApp implementation in #8005 was not blocking auth initialization, so when testing end-to-end we were seeing race conditions with auth state. In this PR I address by awaiting the user fetch and moving the implementation into `AuthImpl#initializeCurrentUser` for cleanliness.
Mind taking a look @renkelvin?
=> Fix for authStateReady for FirebaseServerApp

.changeset/green-mugs-protect.md, packages/auth/src/platform_browser/index.ts
* Don't allow insecure context, unless localhost
* Protect against escaping hacks by instantiating a new URL instance
b/327386166
FYI @hsubox76
Q, should we guard against isSecureContext not being available? [Can I use isSecureContext?](https://caniuse.com/mdn-api_issecurecontext)
=> More complex check for authTokenSyncUrl

e2e/yarn.lock, packages/auth-compat/demo/functions/yarn.lock, packages/auth-compat/demo/yarn.lock, packages/auth/demo/functions/yarn.lock, packages/rules-unit-testing/functions/yarn.lock, yarn.lock
The CI won't test the Dependabot prs since they're made from a source external to the repository.
This PR attempts to incorporate all of the yarn.lock file changes into a single PR.
Includes changes from the following dependabot created PRs:
- #8078
- #8077
- #8075
- #8074
- #8073
- #8072
- #8071 
- #8070
- #8069
CI.
N/A.
=> Dependabot transitive dependency rollup

e2e/yarn.lock
Dependabot recommends an update to a transitive dependency in our E2E tests. #8093.
I'm updating the dependency manually since our CI doesn't execute changes originating from a different repo.
CI.
N/A.
=> Dependabot weback-dev-middleware transitive dep upgrade

packages/vertexai/src/types/enums.ts, packages/vertexai/src/types/requests.ts, packages/vertexai/src/types/responses.ts
After doing an audit, added a number of Vertex types that were missing in the JS SDK.
See https://docs.google.com/document/d/1E-Kw5NC5iwtAA4_D9O7eNM4DpT8OZjwY8YwKUrDSNSI/edit?resourcekey=0-agpRR_nc-s3n4cCy4tBkOQ&tab=t.0 (internal)
=> Add additional Vertex types

.changeset/cyan-rats-itch.md, packages/messaging/src/internals/token-manager.test.ts, packages/messaging/src/internals/token-manager.ts
Revised token update logic to keep existing tokens during update failures, preventing unnecessary deletions for transient issues.
context: b/329447928
=> Don't delete on update failure

packages/auth/demo/package.json
Upgrade the sample app build file so that the latest published Firebase libs are for auth sample app.
=> Use the latest published version for auth sample app

.github/workflows/test-changed-firestore-integration.yml
Conditionally run terraform CI steps only if secrets are available
=> Conditionally run terraform CI steps only if secrets are available

.github/workflows/health-metrics-pull-request.yml
PRs created by Dependabot do not have privledges to run our non-critical Health Check CI workflows. Currently these workflows error-out on all Dependabot changes. It would be a better developer experience if these steps were simply skipped, so it doesn't look like we're merging a PR with errors.
CI in the feature branch.
Also CI in a Dependabot branch.
N/A
=> Update health-metrics-pull-request to skip execution on Dependabot PRs

.github/workflows/deploy-config.yml
One more Workflow to skip when dependabot makes a PR: the deploy config workflow. This workflow will still work if we push code to the branch ourselves. 
CI.
N/A.
=> Disable Deploy Config workflow on dependabot PRs.

.changeset/sharp-lizards-sit.md, packages/firestore/src/local/query_engine.ts, packages/firestore/src/local/simple_db.ts, packages/firestore/test/unit/local/simple_db.test.ts
https://github.com/firebase/firebase-js-sdk/pull/7929 accidentally pulled in the IndexedDB persistence code even in Firestore applications that did _not_ used IndexedDB, unnecessarily increasing the code size by 6.5 kB starting in v10.7.2. This PR fixes this code size increase by moving the `getAndroidVersion()` function from a static member of the `SimpleDB` class to a free function to avoid pulling in all of the IndexedDB code.
=> Firestore: simple_db.ts: move getAndroidVersion() to a free function

docs-devsite/auth.md, docs-devsite/auth.recaptchaparameters.md, packages/auth/src/core/strategies/email.ts, packages/auth/src/core/strategies/email_and_password.ts, packages/auth/src/core/user/account_info.ts, packages/auth/src/model/public_types.ts
This change updates links in code documentation that are in Markdown format to be in the expected JSDoc link format, so that they can be correctly parsed by the api-documenter.
=> Change Markdown links in code docs to JSDoc links

README.md
As of April 19th, 2024, the CI is using Node 20.12.0 for testing. Node <18 no longer works with some devDependencies that were recently updated, namely chromedriver 116.0.1 -> 119.0.1 in messaging and auth.
=> Update recommended Node version for development

CONTRIBUTING.md
- Fixed 'adn' to 'and'
- Remove extra right parenthesis in markdown link that caused the link not to be formatted, and the closing parenthensis to be missing
=> Fix typo and link formatting in contribution guide

packages/vertexai/src/requests/request.test.ts, packages/vertexai/src/requests/request.ts
All headers need a version number or they won't show up. Adding a version to the `gl-js/` client header.
=> Fix client headers

.changeset/real-ravens-prove.md, packages/auth/rollup.config.js
The Firebase Auth webextension bundle was previously being shipped as a CommonJS package rather than a ES module, because it did not have a module package file indicating that it was an ES module.
Fixes #8115 
**Aside:** The web-extension entry point does not have a Node bundle, and browser bundles don't normally require a `package.json` file with `{ "type": "module" }`, but certain browser testing frameworks use Node, and need working ES module resolution.
=> Emit a module package file into esm2017 auth webextension bundle

packages/vertexai/src/models/generative-model.test.ts, packages/vertexai/src/models/generative-model.ts, packages/vertexai/src/requests/request-helpers.test.ts, packages/vertexai/src/requests/request-helpers.ts, packages/vertexai/src/types/requests.ts
Change so that `systemInstruction` param can be passed in to the model or to methods as a string, as well as a Part or Content.
Parallel GoogleAI PR: https://github.com/google-gemini/generative-ai-js/pull/113
=> Allow text-only systemInstruction

LICENSE
Tslib is bundled into our code in some of the CDN packages and it has a BSD-0-Clause license. Import into google3 requires this license be reflected in the top-level LICENSE file.
=> Add tslib bsd-0 license

packages/vertexai/src/api.ts, packages/vertexai/src/index.ts, packages/vertexai/src/public-types.ts, packages/vertexai/src/requests/stream-reader.test.ts, packages/vertexai/src/service.test.ts, packages/vertexai/src/service.ts
Revert the location part of https://github.com/firebase/firebase-js-sdk/pull/8124 and allow user to set location again.
Also get rid of some TS errors on SafetyRatings in tests.
=> [VertexAI] Allow user to set location

packages/vertexai/src/index.ts, packages/vertexai/src/models/generative-model.ts, packages/vertexai/src/requests/request.test.ts, packages/vertexai/src/requests/request.ts, packages/vertexai/src/service.test.ts, packages/vertexai/src/service.ts, packages/vertexai/src/types/internal.ts
Integrating VertexAI with Auth, so that when Firebase Auth is available and signed in, we append an `Authorization: Firebase <authToken>` header to requests.
This is needed in order to support GCS URI `FileData` support.
=> Integrate VertexAI with Auth

packages/vertexai/src/requests/request-helpers.test.ts, packages/vertexai/src/types/content.ts
This chain of branches is getting a bit messy- I'm just putting this PR out so it can be reviewed :)
This PR follows #8216, and uses Firebase Authorization tokens to allow users to pass URLs in `generateContent` to GS resources that are secured by Firebase Security Rules.
This currently works against the production backend. I live tested in a React application configured with Firebase auth, storage, and vertexai.
Live tested using the following:
```javascript
const firebaseConfig = { /* OMITTED */ };
const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const vertex = getVertexAI(app);
const model = getGenerativeModel(vertex, { model: 'gemini-1.5-pro-preview-0409'});
const storage = getStorage(app)
async function run() {
await signInWithEmailAndPassword(auth, …
```
=> Add support for GCS FileData in inference

packages/vertexai/src/requests/request-helpers.test.ts
Missed a failing test on: https://github.com/firebase/firebase-js-sdk/pull/8216
=> [VertexAI] fix test

packages/vertexai/src/requests/response-helpers.test.ts, packages/vertexai/src/requests/response-helpers.ts
`response.text()` only works when the first `Part` in the candidate has text, and fails if it's mixed in with `FunctionCallPart`s. Modified to look for text on any `Part` and added some tests.
We also need to port this fix to GoogleAI.
Internal reference: b/338296397
=> Make text() accessor handle mixed-parts responses

docs-devsite/index.md, docs-devsite/vertexai-preview.md, docs-devsite/vertexai-preview.vertexaioptions.md, packages/vertexai/src/api.ts, packages/vertexai/src/index.ts, packages/vertexai/src/public-types.ts
Fix docs based on comments in cl/631623581 (internal)
=> Fix doc comments

.changeset/tiny-pots-sit.md
Bump all packages by a patch.
Staging release selectively publishes only packages that had their versions bumped, and their direct dependencies (not transitive dependencies), which means on npm installs there are 2 versions of `@firebase/app` which causes component registration to be very buggy. This will roll into the existing "Version Packages" staging PR, so everything that's bumped minor there will stay minor, and any other package will be bumped by a patch from this changeset.
The long term solution is to fix the staging release check to publish all the packages that would need to be published, for this release, I just want to make sure we have a staging release to test with ASAP, and also be 100% sure we don't have a problem in prod.
=> Bump all packages

README.md
I noticed some small mistakes in the README.md, this PR fixes them.
=> Fix minor mistakes in the root README

.github/workflows/release-prod.yml
Adds a job to the production release workflow to create a GitHub release.
I tested this on a minimal version (no build or npm publish) of the workflow on a fork. It adds and pushes tags the same way that the `scripts/release/release.ts` script does.
Test workflow: https://github.com/dlarocque/firebase-js-sdk/blob/master/.github/workflows/test-release.yml
Resulting release: https://github.com/dlarocque/firebase-js-sdk/releases/tag/firebase%405.5.5
This job assumes that the version packages PR was already merged.
=> Add job to create a GitHub release

.changeset/empty-windows-push.md, packages/vertexai/package.json
Vertex typings point to the entry point index.d.ts instead of the rolled-up typings file created by api-extractor. This causes errors in some build tools.
May be the cause of: https://github.com/angular/angularfire/issues/3532
Similar fix as https://github.com/firebase/firebase-js-sdk/pull/8251 (those are for auth/web-extension and auth/cordova)
Was able to repro in a TS project and this change fixed it.
=> Change Vertex typings path to point to rolled up d.ts file

scripts/docgen/docgen.ts
- Put cleanup for both docs and toc generation into a cleanup function that's run on process exit and SIGINT (ctrl-C) to ensure auth files especially are returned to their original state no matter what.
- Clean top level `temp/` json dir before every run.
The cleanup process used to run in a "finally" block which is fine for catching errors caused by the specific code but doesn't account for a SIGINT or some other unexpected interruption.
I think I put enough checks in the cleanup code to make sure the steps don't error but I also wrapped it in a try/catch just in case with a warning to watch out for changed files.
=> More robust clean up after unexpected docgen process exits.

.github/workflows/test-all.yml, .github/workflows/test-changed-auth.yml
- Removes  `push` trigger for `test-changed-auth` which was added in error when debugging that workflow in #7872.
- Changes `test-all` worklfow to run only on pull requests. This workflow was previously triggered on branch pushes.
CI execution.
None.
=> [CI] Reduce executions by removing `on: push` for two workflows

CONTRIBUTING.md
#8276 
I verified that Google+ is gone: https://plus.google.com redirects to https://workspaceupdates.googleblog.com/2023/04/new-community-features-for-google-chat-and-an-update-currents%20.html
I verified that Twitter is gone: https://twitter.com redirects to https://x.com
=> Update social media platforms

.github/workflows/check-docs.yml, CONTRIBUTING.md, docs-devsite/_toc.yaml, package.json, scripts/docgen/docgen.ts
Since we are now checking in the `toc/toc.yaml` file, we should have a check to ensure this file was updated, just as we do for `docs-devsite`.
=> Add docgen all script and update documentation

docs-devsite/_toc.yaml
These entries were introduced when the `toc.yaml` was first added to the repository here: https://github.com/firebase/firebase-js-sdk/pull/8257
The uploaded file was generated in the [vertexaierror branch](https://github.com/firebase/firebase-js-sdk/tree/dlarocque/vertexaierror) (not merged). Since it wasn't tracked by Git, we weren't able to notice that there were new entries. This shouldn't happen again now that we have the checks in place.
**Note**: The changes being removed here haven't been uploaded to devsite, so the change is only on GitHub
=> Remove VertexAIError related entries from TOC

.changeset/orange-rings-own.md, packages/webchannel-wrapper/package.json
Fixes a typo in the webchannel-wrapper's package.json that affected ems5 exports.
=> fix: Fix a typo in the webchannel-wrapper's package.json.

.changeset/flat-scissors-suffer.md, packages/firestore/src/core/sync_engine_impl.ts, packages/firestore/test/unit/specs/listen_spec.test.ts
Fix https://github.com/firebase/firebase-js-sdk/issues/8314.
The previous fix  https://github.com/firebase/firebase-js-sdk/pull/8247 introduced out-of-sync metadata issue for multi-tab users.  When viewSnapshot is not defined, that means there is no change, so it should not be seen as "not-current".
=> Fix multi-tab snapshot listener metadata sync issue

.changeset/chilly-moons-play.md, .changeset/fifty-mayflies-hug.md, packages/app/src/api.ts, packages/util/src/environment.ts
Update browser detection logic:
Detect either window or web worker (WorkerGlobalScope).
Fixes #8299 #8284
=> fix: browser detection

.changeset/clever-dryers-double.md, packages/app/src/firebaseServerApp.ts
The code had already guarded use of the `FinalizationRegstiry` during the initialization of `FirebaseServerApp` in `initializeServerApp` if the `releaseOnDeref` configuration parameter was defined. This gating was to provide functionality in older node versions.  However, there was other code that would errantly attempt to allocate a `FinalizationRegstiry` in `FirebaseServerAppImpl` regardless of the existence of `releaseOnDeref` field, and this caused issues in some edge environments.
This change fixes that issue.
I had tested this previously using Node v14.14.0, which is the release version previous to the [reported addition](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry#browser_compatibility) of the FinalizationRegistry, and our …
=> FirebaseServerAppImpl: guard use of FinalizationRegistry based on its availability.

docs-devsite/vertexai-preview.errordetails.md, packages/vertexai/src/types/error.ts
This PR fixes two typos that were introduced in #8240.
=> Fix typos in VertexAI errors docs

packages/app/src/constants.ts
Replaced `fire-connect` with `fire-data-connect` to match other package names.
=> Updated Heartbeat Name for Data Connect

.github/workflows/health-metrics-pull-request.yml, .github/workflows/health-metrics-release.yml
https://github.com/google-github-actions/setup-gcloud v0 is no longer maintained.
```
Run google-github-actions/setup-gcloud@v0
Error: The v0 series of google-github-actions/setup-gcloud is no longer maintained. It will not receive updates, improvements, or security patches. Please upgrade to the latest supported versions: 
```
=> Upgrade setup-gcloud to v2

.changeset/chilly-plums-burn.md, packages/rules-unit-testing/functions/yarn.lock
This change is automatically done when running `yarn test` in the repo. We should probably check it into the repo?
The version of `google-cloud/firestore` in the `rules-unit-testing/functions/yarn.lock` was listed as '6.6.0', when it was actually pulling '6.8.0'. This change upgrades the listed version to be the real version.
=> Upgrade firebase-admin and google/cloud-firestore in rules-unit-testing yarn lock

.github/workflows/check-vertexai-responses.yml, packages/vertexai/package.json, scripts/update_vertexai_responses.sh
This adds a new script that clones the latest minor version within a hard-coded major version of the mock responses.
It also adds a CI job that leaves a comment on the PR if the script is cloning an outdated major version.
=> VertexAI: add support for mock responses versioning system

packages/auth/test/helpers/integration/helpers.ts, packages/auth/test/integration/flows/totp.test.ts
There are a couple lines that are violating an eslint rule. In other cases where this rule is violated, we add a similar exception.
This was causing `npm run lint` to fail in auth.
=> Disable extraneous import errors on violating lines in auth tests

packages/firestore/src/remote/persistent_stream.ts
This prepares for InitilaizeStream handshake by moving the logic to AbstractStream that distinguishes first response subsequent stream responses. The Listen stream will make use of this in future PRs.
=> Refactor stream

.changeset/spicy-dragons-pay.md, packages/app-compat/src/index.ts, packages/util/src/environment.ts
Properly handle the case in app-compat checks where `window` exists but `self` does not. (This apparently occurs in Ionic Stencil's Jest preset.)
This is a safer check as `isBrowser()` now checks for the existence of `window`, so if it passes, the second condition shouldn't error.
Fixes https://github.com/firebase/firebase-js-sdk/issues/8365
=> Handle app-compat environment check where self does not exist

packages/data-connect/CHANGELOG.md, packages/data-connect/src/network/fetch.ts, packages/data-connect/test/emulatorSeeder.ts, packages/data-connect/test/post.gql, packages/data-connect/test/queries.test.ts, packages/data-connect/test/unit/dataconnect.test.ts, packages/data-connect/test/unit/fetch.test.ts, packages/data-connect/test/unit/queries.test.ts
When the server responds with an error, the response includes irrelevant information to the user in addition to the message itself. Instead of reporting this redundant information, we throw an error with just the nested message object.
=> Better JSON messages

.changeset/tender-apes-clap.md, packages/analytics/package.json, packages/analytics/src/helpers.test.ts, packages/analytics/src/helpers.ts, packages/app-check/package.json, packages/app-check/src/recaptcha.test.ts, packages/app-check/src/recaptcha.ts, packages/auth/package.json, packages/auth/src/platform_browser/index.ts, packages/auth/src/platform_browser/load_js.test.ts, packages/auth/tsconfig.json, packages/database-compat/tsconfig.json, packages/database/package.json, packages/database/src/realtime/BrowserPollConnection.ts, packages/database/tsconfig.json, packages/messaging/package.json, packages/messaging/src/helpers/registerDefaultSw.ts, yarn.lock
This reverts commit f58d48cd42c9f09eab4d8b2a606af360528917f8.
An issue in App Check revealed that [safevalues](https://github.com/google/safevalues) is not compatible with es5, since [template tag functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates) are required, and those are not supported in es5. Our bundler tries to compensate for this by replacing template tag functions with `tslib.__makeTemplateObject`, but safevalues does not assert that those are valid template string literals, and throws an error.
This can be fixed by upgrading all of our browser cjs bundles from es5 to es6, but we don't want to make that breaking change at this time, so we must revert our usage of safevalues until we're ready to drop es5 support.
For …
=> Revert introduction of safevalues

.changeset/README.md, .changeset/config.json, .github/workflows/canary-deploy.yml, .github/workflows/check-changeset.yml, .github/workflows/merge-release-branch.yml, .github/workflows/release-pr.yml, .github/workflows/release-staging.yml, CONTRIBUTING.md, README.md, packages/auth/README.md, packages/firebase/README.md, packages/remote-config/src/remote_config.ts, scripts/ci-test/deploy-if-needed.ts, scripts/ci-test/tasks.ts, scripts/ci/add_changeset.ts, scripts/ci/check_changeset.ts, scripts/format/format.ts, scripts/utils.ts
This is to match the coordinated effort across all Firebase platform SDKs. The change has already been made in the Apple and Android repos.
=> Rename usages of "master" branch to "main"

packages/firestore/src/local/globals_cache.ts, packages/firestore/src/local/indexeddb_globals_cache.ts, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/indexeddb_schema.ts, packages/firestore/src/local/indexeddb_schema_converter.ts, packages/firestore/src/local/indexeddb_sentinels.ts, packages/firestore/src/local/memory_globals_cache.ts, packages/firestore/src/local/memory_persistence.ts, packages/firestore/src/local/persistence.ts, packages/firestore/test/unit/local/globals_cache.test.ts, packages/firestore/test/unit/local/indexeddb_persistence.test.ts, packages/firestore/test/unit/local/test_globals_cache.ts
=> Implement SessionToken Persistence

packages/firestore/src/core/component_provider.ts, packages/firestore/src/core/event_manager.ts, packages/firestore/test/integration/api/batch_writes.test.ts, packages/firestore/test/integration/api/database.test.ts
In preparation for clearing cache on named database reuse, listeners need to abort when FirestoreClient is terminated.
=> Abort Firestore listeners on terminate.

.github/workflows/test-all.yml
Instead of having an additional step to delete the `.git` directory before archiving it, we can directly exclude it from the archived build with `--exclude`.
Firestore is already doing this here: https://github.com/firebase/firebase-js-sdk/blob/main/.github/workflows/test-changed-firestore.yml#L71
=> Exclude `.git` from archived build, instead of deleting it

.github/workflows/canary-deploy.yml, .github/workflows/check-changeset.yml, .github/workflows/check-docs.yml, .github/workflows/check-pkg-paths.yml, .github/workflows/deploy-config.yml, .github/workflows/e2e-test.yml, .github/workflows/format.yml, .github/workflows/merge-release-branch.yml, .github/workflows/prerelease-manual-deploy.yml, .github/workflows/release-log.yml, .github/workflows/release-pr.yml, .github/workflows/release-prod.yml, .github/workflows/release-staging.yml, .github/workflows/release-tweet.yml, .github/workflows/test-changed-auth.yml, .github/workflows/test-changed-fcm-integration.yml, .github/workflows/test-changed-firestore-integration.yml, .github/workflows/test-changed-firestore.yml, .github/workflows/test-changed-misc.yml, .github/workflows/test-changed.yml, .github/workflows/test-firebase-integration.yml, .github/workflows/update-api-reports.yml
The `actions/checkout` was being pulled from `@master` which is still at v2, since their default branch has changed from master to main in 2020.
Previous default branch, at v2: https://github.com/actions/checkout/tree/master
New default branch, at v4: https://github.com/actions/checkout/tree/main
The v2 -> v3 bump was to drop support for Node runtimes < 16: https://github.com/actions/checkout/compare/v2.4.2...v3.0.2#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R17-R18
The v3 -> v4 bump was to drop support for Node runtimes < 20: https://github.com/actions/checkout/compare/v4.0.0...v4.1.0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R15-R17
Since we're already using Node >= 20, we can upgrade all the way to v4.
=> Upgrade actions from master to v4

common/api-review/auth.api.md, docs-devsite/auth.md, docs-devsite/auth.phoneauthprovider.md, packages/auth/src/api/index.ts, packages/auth/src/platform_browser/providers/phone.test.ts, packages/auth/src/platform_browser/providers/phone.ts, packages/auth/src/platform_browser/strategies/phone.test.ts, packages/auth/src/platform_browser/strategies/phone.ts
* Currently, public phone auth related functions require a reCAPTCHA v2 verifier because that’s the only attestation provider we’re supporting. Since we're adding reCAPTCHA Enterprise support and the reCAPTCHA Enterprise ENFORCE flow doesn't require a reCAPTCHA v2 token, we will make `ApplicationVerifier` parameter optional.
* If ApplicationVerifier is not available in OFF mode or AUDIT fallback flow, we will throw an `auth/argument-error`. 
Tested the Phone Auth, SMS MFA Enroll, and SMS MFA Sign-In flows with the demo app when ApplicationVerifier is not set
* Enforce mode: Expect sendVerificationCode to be called with a reCAPTCHA Enterprise token
* Audit mode:
* First, expect sendVerificationCode to be called with a reCAPTCHA Enterprise token
* If the reCAPTHCA Enterprise token flow …
=> Make ApplicationVerifier params optional in Phone Auth APIs

.changeset/mighty-shirts-pump.md, packages/auth/src/platform_browser/persistence/local_storage.ts
This PR removes a localStorage synchronization fix introduced in 2016 to address an issue in Safari 9 (*Important:* [b/28330893](http://b/28330893)). The fix, while necessary at the time, is now causing several Auth tests to fail in Safari. After removing this fix, all tests pass.
The Safari tests are failing because they assume that a storage event without a change to the underlying storage will not trigger callbacks that we attach. With this fix, if we dispatch a storage event without a change to the underlying storage, a manual synchronization will take place, which will then cause the callbacks to be called.
See: [`local_storage.test.ts`](https://github.com/firebase/firebase-js-sdk/blob/main/packages/auth/src/platform_browser/persistence/local_storage.test.ts#L168-#L179).
**Testing**: …
=> Remove LocalStorage synchronization on storage events in Safari

.github/workflows/check-changeset.yml
It looks like a sloppy copy-paste on my part from when this was originally created 4 years ago. https://github.com/firebase/firebase-js-sdk/pull/3554/files#r468200983
=> Fix typo errors in check-changeset workflow

.changeset/slow-emus-vanish.md, packages/app-compat/src/index.ts
Updated how app-compat checks the global scope. The `getGlobal()` checks the existence of `self`, `window`, and also `global`.
Fixes #8409
=> fix error when initializing firebase on service worker

packages/vertexai/src/methods/generate-content.test.ts, packages/vertexai/src/requests/stream-reader.test.ts, scripts/update_vertexai_responses.sh
The set of mock responses were updated to reduce some more duplication: https://github.com/FirebaseExtended/vertexai-sdk-test-data/pull/12
This updates the test code to use the updated version.
=> VertexAI: use updated set of mock responses

.changeset/itchy-boxes-try.md, common/api-review/storage.api.md, docs-devsite/storage.md, packages/storage/src/api.browser.ts, packages/storage/src/api.node.ts, packages/storage/src/implementation/connection.ts, packages/storage/src/platform/browser/connection.ts, packages/storage/src/platform/connection.ts, packages/storage/src/platform/node/connection.ts, packages/storage/src/reference.ts, packages/storage/test/node/stream.test.ts
In the past, we used `node-fetch`, which used the `NodeJS.ReadableStream` interface for streaming requests. When we moved to `undici` (https://github.com/firebase/firebase-js-sdk/pull/7705), we began using the Web `ReadableStream` interface under the hood, but did not update our usage of the interface, so users began seeing errors when using `getStream` (https://github.com/firebase/firebase-js-sdk/issues/8303).
To fix this issue, we need to migrate from the Node to the Web `ReadableStream` interface.
This will help us in the future when we migrate to native Node `fetch`, since that also uses the Web `ReadableStream` interface.
Fixes #8303
=> Migrate from the Node to the Web ReadableStream

.changeset/large-games-dress.md, packages/app/src/heartbeatService.test.ts, packages/app/src/heartbeatService.ts
Heartbeat code should never throw and interfere with developer app operation. This PR wraps the two main heartbeat methods, `triggerHeartbeat()` and `getHeartbeatsHeader()` in try/catch blocks that hopefully catch unexpected errors in uncommon environments and logs a `console.warn()` instead.
I've been told in previous issues that thrown errors cause a lot of noise in Sentry logs (plus interrupting the app) while a `console.warn()` does not clog up Sentry logs, so I think this is a good compromise to avoid swallowing any fixable errors that we might want to know about.
Fixes https://github.com/firebase/firebase-js-sdk/issues/8407
=> Wrap all heartbeats methods in try/catch

.changeset/perfect-weeks-care.md, packages/app/src/heartbeatService.ts
Following the discussion in issue #8436, I’ve removed an unnecessary console.log statement that appears to have been inadvertently included in a recent commit
=> fix: remove unnecessary console.log statement

.changeset/dull-nails-kneel.md, packages/functions/src/service.test.ts, packages/functions/src/service.ts
=> Allow a custom path in Firebase functions custom domain

.github/ISSUE_TEMPLATE/bug_report_v2.yaml
Our Bug report template required that the user input a browser version. This isn't applicable in cases where the bug occurs in a non-browser environment (e.g. Node, React Native).
Users usually only select one product. We should make it more clear that they can select multiple if they're relevant.
=> Update Bug Report Template

packages/vertexai/src/requests/stream-reader.test.ts, scripts/update_vertexai_responses.sh
Ugrades vertex mock responses from v2 to v3. 
Related: https://github.com/FirebaseExtended/vertexai-sdk-test-data/pull/15
=> Upgrade vertex responses to v3

docs-devsite/index.md, docs-devsite/vertexai-preview.md, docs-devsite/vertexai-preview.vertexai.md, docs-devsite/vertexai-preview.vertexaierror.md, docs-devsite/vertexai-preview.vertexaioptions.md, packages/vertexai/src/errors.ts, packages/vertexai/src/index.ts, packages/vertexai/src/public-types.ts
Replace 'Vertex AI For Firebase' usage with 'Vertex AI in Firebase'.
=> Replace 'Vertex AI For Firebase' usage with 'Vertex AI in Firebase'

docs-devsite/app-check.md, packages/app-check/src/api.ts
`getToken()` docs text inaccurately said that it returns null if no token is available. Fixed text to describe behavior accurately.
=> Fix AppCheck getToken docs text

packages/auth/src/platform_browser/strategies/phone.ts
**Issue** 
Currently, we show the challenge and fetch reCAPTCHA v2 token when reCAPTCHA Enterprise token is empty (token fetch fails) before making the phone auth request.
In Enforce mode, we fetch rcv2 token when rCE token is empty. This is incorrect behavior, we shouldn't fetch rcv2 token in Enforce mode. Fetching rcv2 means we will show the rcv2 challenge, which would make confuse developers as to why we show rcv2 challenge when they're in Enforce mode. 
We expect to throw MISSING_RECAPTCHA_TOKEN instead without fetching rcv2 token. This PR fixes that.
**Testing**
- CI
- Manual testing
=> Only fetch reCAPTCHA v2 token when FAKE_TOKEN

.changeset/warm-oranges-itch.md, packages/firestore/src/core/sync_engine_impl.ts, packages/firestore/src/local/shared_client_state.ts, packages/firestore/test/unit/specs/listen_source_spec.test.ts
Issue: when creating a snapshot listener, it's `QueryTargetState` is simply set to "not-current" if it is listening to cache only. This is going to create out-of-sync metadata in persistence multi-tabs:
scenario: 
1. Create a snapshot listener in primary client, listen to server
2. It raised a snapshot from server, which is up-to-date (fromCache=false),  and store it into cache
3. Listen to same query with source==cache in secondary tab
4. Since the cached result is up-to-date, and the cache listener in the secondary tab is sharing the date with the server listener in the primary tab, the raised snapshot should be `current` as well (fromCache=false)
=> Fix metadata sync issue for cache listeners in multi-tab

packages/auth/src/platform_browser/providers/phone.test.ts, packages/auth/src/platform_browser/strategies/phone.test.ts, packages/auth/src/platform_browser/strategies/phone.ts
**Issue**
At the beginning of phone auth flow, we initialize the reCAPTCHA Enterprise config in order to check the enablement state. However, if rCE is not enabled for any provider (phone, email), `GetRecaptchaConfig` response will not contain a `recaptchaKey`, and [this error](https://github.com/firebase/firebase-js-sdk/blob/629919ea760e35b7d880a099edf7f42b5bcbae4b/packages/auth/src/platform_browser/recaptcha/recaptcha.ts#L91) will eventually be thrown. Therefore, phone auth flows are broken when rCE is not enabled.
This PR ignores the above error when failing to initialize rCE config and proceeds to use reCAPTCHA v2 verification.
**Test**
- CI/unit test
- Manual testing
=> Proceed to reCAPTCHA v2 if unable to get phone enablement state

.changeset/four-pillows-fetch.md, packages/messaging/src/helpers/logToFirelog.test.ts, packages/messaging/src/helpers/logToFirelog.ts
Here’s a refined version of your GitHub PR description:
Context: The logging endpoint has been updated in accordance with [go/firelog](https://github.com/firebase/firebase-js-sdk/compare/link). We observed that BigQuery logging is missing entries for WebPush (see [b/350475783](https://github.com/firebase/firebase-js-sdk/compare/link) for reference). This PR addresses the issue by updating both the endpoint and the payload to ensure proper logging of WebPush entries.
=> Update endpoint to Clearlog

packages/auth/README.md, packages/auth/karma.conf.js, packages/auth/test/integration/flows/recaptcha_enterprise.test.ts
Add integration tests for reCAPTCHA Enterprise. These test run against real backend. The following rCE config is configured for the CI project:
```
"phoneEnforcementState": "ENFORCE",
"useSmsBotScore": true,
"useSmsTollFraudProtection": true
```
=> Add integration tests for rCE ENFORCE

packages/firebase/rollup.config.js
The rollup-typescript-plugin does not transpile JS files using the TS compiler by default. This means that external dependencies that provide JS bundles will not be transpiled to the target ES version specified in the TypeScript config used by the plugin. 
In other words, if one of our dependencies has a bundle that uses newer JS features that aren't supported in all browsers, it will be included in our bundle without being translated into an older JS version that we promise our bundles are compatible with.
This resulted in one of our dependencies (https://github.com/jakearchibald/idb) being included in the CDN bundles without being transpiled to ES5 (the target ES version). Since this dependencies bundle uses ES2018 syntax (object spread operator `{ ...x }`), this upgraded our CDN …
=> Rollup JS files with rollup-typescript-plugin

packages/analytics/testing/get-fake-firebase-services.ts
Analytics test logs had a lot of spam with warnings that the app is already deleted. This actually didn't come from a call to deleteApp() but a reference to `app.name` (which is actually a getter function) in a heartbeatService method. This is because some of the analytics tests use a full FirebaseApp initialized with initializeApp instead of a stub, which causes heartbeatService to also be initialized and start running its lifecycle methods.
The solution is to replace the heartbeatService component in the app used for testing, a fix which was already done in AppCheck, probably for the same problem https://github.com/firebase/firebase-js-sdk/blob/main/packages/app-check/test/util.ts#L70 Analytics tests don't need to test the heartbeatService so it makes sense to stub it out.
=> Fix analytics test warnings

renovate.json
We don't want to upgrade idb, since it targets `esnext`, which could introduce a burden to use latest node/browsers for our users (or transpile).
We should also remove the dependencies we don't have anymore.
=> Tell renovate to ignore idb and remove unused dependencies

packages/vertexai/src/models/generative-model.test.ts
We introduced some type errors in the test files after modifying types in #8514
=> Fix TypeScript Compiler Errors in Vertex Tests

.changeset/tender-tips-hammer.md, common/api-review/functions.api.md, docs-devsite/functions.functionserror.md, docs-devsite/functions.md, packages/functions/src/api.ts, packages/functions/src/callable.test.ts, packages/functions/src/error.ts, packages/functions/src/public-types.ts
We should export the `FunctionsError` class to users, so that they can perform instanceof checks.
Tested using:
```js
import { FirebaseError, initializeApp } from "firebase/app";
import { FunctionsError, getFunctions, httpsCallable } from "firebase/functions";
const firebaseConfig = {
/* ... */
};
const app = initializeApp(firebaseConfig);
const functions = getFunctions(app);
(async () => {
try {
const addMessage = httpsCallable(functions, 'addMessage'); // Function does not exist
await addMessage({ text: 'hello' });
} catch (err) {
console.log(err instanceof FirebaseError); // true
console.log(err instanceof FunctionsError); // true
throw err;
}
})();
```
Also added an `expect(error).to.be.instanceOf(FunctionsError)` to all error checks in the tests.
Fixes #8511
=> Make the `FunctionsError` class publicly exported

.github/workflows/test-all.yml, scripts/emulator-testing/emulators/emulator.ts
We need to close the writer after the download is complete, otherwise we get an `ETXTBSY` when trying to read a file that is busy.
=> Close emulator file after download is complete

.changeset/little-cows-tie.md
The package has been renamed with the latest Vertex merges - change to avoid breaking changesets tool.
=> rename vertexai package reference in a changeset

docs-devsite/vertexai.safetysetting.md
Should have regenerated docs based on https://github.com/firebase/firebase-js-sdk/pull/8567 but it was missed due to holding off on all Vertex docs changes for the big PR.
=> Missed one doc change from a PR

packages/data-connect/package.json, packages/data-connect/rollup.config.js
Follow up from #8509- this will be merged into v11 once we've rebased on top of the data connect changes.
=> Remove data-connect es5 bundles

packages/vertexai/src/methods/generate-content.ts, packages/vertexai/src/requests/response-helpers.ts, packages/vertexai/src/requests/stream-reader.ts
Fixes #8566 
The backend omits the `index` for the first candidate, since 0 is a default value, and protos omit defaults. This causes tests to fail against the v4 mock responses, and aggregated responses will be malformed, since instead of `response.candidate[0] = ...` it ends up being `response.candidate[undefined] = ...`.
=> Overwrite undefined candidate index

packages/vertexai/src/requests/response-helpers.ts, packages/vertexai/src/requests/stream-reader.ts, scripts/update_vertexai_responses.sh
Upgrades the mock responses from v3 to v5.
This also includes a fix for an issue where where the first candidate's index is undefined, causing undefined to be used as the key when aggregating candidates.
=> Upgrade Vertex Mock Responses to V5

.changeset/rare-radios-leave.md, .changeset/shy-bikes-explain.md, common/api-review/auth.api.md, docs-devsite/auth.md, docs-devsite/auth.phoneauthprovider.md, packages/auth/README.md, packages/auth/karma.conf.js, packages/auth/src/api/account_management/mfa.test.ts, packages/auth/src/api/account_management/mfa.ts, packages/auth/src/api/authentication/mfa.test.ts, packages/auth/src/api/authentication/mfa.ts, packages/auth/src/api/authentication/sms.test.ts, packages/auth/src/api/authentication/sms.ts, packages/auth/src/api/index.ts, packages/auth/src/core/credentials/email.test.ts, packages/auth/src/core/credentials/email.ts, packages/auth/src/core/strategies/email_and_password.test.ts, packages/auth/src/core/strategies/email_and_password.ts, packages/auth/src/core/strategies/email_link.test.ts, packages/auth/src/core/strategies/email_link.ts, packages/auth/src/platform_browser/providers/phone.test.ts, packages/auth/src/platform_browser/providers/phone.ts, packages/auth/src/platform_browser/recaptcha/recaptcha.test.ts, packages/auth/src/platform_browser/recaptcha/recaptcha.ts, packages/auth/src/platform_browser/recaptcha/recaptcha_enterprise_verifier.test.ts, packages/auth/src/platform_browser/recaptcha/recaptcha_enterprise_verifier.ts, packages/auth/src/platform_browser/strategies/phone.test.ts, packages/auth/src/platform_browser/strategies/phone.ts, packages/auth/test/integration/flows/recaptcha_enterprise.test.ts
Currently, Firebase Auth Web SDK is relying on reCAPTCHA v2 to verify that the phone number verification request comes from one of the app's allowed domains to mitigate SMS abuse.
A downside of reCAPTCHA v2 is that end-users are required to solve a challenge. Therefore, we would like to give end-users a better user experience by integrating [reCAPTCHA Enterprise](https://cloud.google.com/recaptcha/docs/overview) with our phone auth flow. reCAPTCHA Enterprise is completely invisible to the user, so the phone auth flow will become seamless without user interaction.
* CI
* Manual testing with test app
=> Add reCAPTCHA Enterprise support for Phone Auth

yarn.lock
We're seeing this message when running browser tests:
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
```
Upgrading to make it go away :)
=> Upgrade caniuse

.changeset/afraid-terms-kick.md
See https://github.com/firebase/firebase-js-sdk/issues/8583
In order to mark the Node `engines` requirement change with a major bump, we need to do two steps:
1. Release a new version of the Firebase JS SDK with the dependency `database-compat` bumped by a major version to 2.0.0, which contains the Node `engines` requirement of 18.0.0 to enable current web SDK users to not be disrupted by the next step
2. Release a version of just `@firebase/database-compat` within the 1.x.x version range which reverts the `engines` field change (has no engines field, as it did before 11.0.0), enabling any repos with a semver `^1.x.x` dependency on `@firebase/database-compat` to avoid receiving the `engines` field bump.
=> Major bump for database-compat for Node engines change.

.changeset/six-toys-chew.md, packages/vertexai/src/requests/request.ts
If we use a multi-line template string for the error message, the indentation will be preserved. We should instead add multiple single-line template strings.
=> Remove indentation in Vertex AI API Not Enabled Error

.changeset/nervous-timers-call.md, docs-devsite/vertexai.requestoptions.md, packages/vertexai/src/types/requests.ts
This is the new default base url
=> Update default base url in comment

.changeset/tall-peas-tell.md, packages/vertexai/src/logger.ts, packages/vertexai/src/methods/chat-session.test.ts, packages/vertexai/src/methods/chat-session.ts, packages/vertexai/src/requests/request.test.ts, packages/vertexai/src/requests/request.ts, packages/vertexai/src/requests/response-helpers.ts
App Check's `getToken()` should never throw, but in case of an error getting a valid App Check token, it fills in the "token" field with a standard dummy token, and adds an "error" field. The backend needs to receive these dummy tokens in the header so the developer can track failed requests. Right now we just don't send them. This change sends the dummy token, and logs a warning if an error is found.
I also realized I forgot to include the standard `logger` API in VertexAI so I added it. This is a wrapper around `console` used across all products that adds a product name prefix and also enables the global `setLogLevel()` to apply to any console messages called through this wrapper.
=> Use logger class and send App Check dummy token in header

packages/auth/karma.conf.js, packages/auth/test/integration/flows/hosting_link.test.ts
Added the following tests -
1. Allows user to sign in with default firebase hosting link 
2. Allows user to sign in to a tenant with default firebase hosting link
3. Allows user to sign in with custom firebase hosting link
4. Allows user to sign in to a tenant with custom firebase hosting link
5. Sign in with invalid firebase hosting link throws exception
=> FDL Deprecation & Hosting link Integration Test

e2e/package.json, e2e/yarn.lock
Fixes the `@types/node` errors in e2e tests here: https://github.com/firebase/firebase-js-sdk/actions/runs/11518441707/job/32075789147
The old webpack dependencies were using `@types/node` version 16, which is now incompatible with our SDK.
I had to delete and rewrite `yarn.lock` locally for it to pick up the correct versions. I'm not sure if there's a better way to do this that doesn't generate such a large diff.
=> Upgrade webpack dependencies in e2e tests

.changeset/tame-paws-nail.md, scripts/build/create-overloads.ts
Fixes issue in the e2e tests where there are `declare` statements inside of `declare` blocks: https://github.com/firebase/firebase-js-sdk/actions/runs/11518441707/job/32075789147
In #8561, this script was modified, and all modifiers were accidentally added to all function declarations. This means that the `export` and `declare` modifiers were brought over, which is what caused the issue.
=> Remove modifiers from compat overloads

.github/workflows/canary-deploy.yml, .github/workflows/check-changeset.yml, .github/workflows/check-docs.yml, .github/workflows/check-pkg-paths.yml, .github/workflows/deploy-config.yml, .github/workflows/e2e-test.yml, .github/workflows/format.yml, .github/workflows/health-metrics-pull-request.yml, .github/workflows/lint.yml, .github/workflows/prerelease-manual-deploy.yml, .github/workflows/release-log.yml, .github/workflows/release-pr.yml, .github/workflows/release-prod.yml, .github/workflows/release-staging.yml, .github/workflows/release-tweet.yml, .github/workflows/test-all.yml, .github/workflows/test-changed-auth.yml, .github/workflows/test-changed-fcm-integration.yml, .github/workflows/test-changed-firestore-integration.yml, .github/workflows/test-changed-firestore.yml, .github/workflows/test-changed-misc.yml, .github/workflows/test-changed.yml, .github/workflows/test-firebase-integration.yml, .github/workflows/update-api-reports.yml
Node 22 enters LTS on October 29th, 2024, so we should upgrade CI to run on Node 22.
Would there be any benefits to using `22.x` instead of `22.10.0`? I specified an exact version in case it helps with reproducibility.
=> Upgrade workflows Node version from `20.x` to `22.10.0`

repo-scripts/prune-dts/prune-dts.ts
In #8561, I replaced this function with `convertPropertiesForEnclosingDeclaration`, but it seems that I forgot to remove this (: 
There are no references to this
=> Remove unused `convertPropertiesForEnclosingClass`

scripts/run_tests_in_ci.js
Having the `stdout` and `stderr` in a single string makes it easier to read when analyzing test failures. Currently if there's a test failure, we output stdout and stderr separately so we can't tell which errors were logged during which test.
For example, in https://github.com/firebase/firebase-js-sdk/actions/runs/10776099172/job/29882046607, there are tons of `FIREBASE FATAL ERROR`'s logged, but I can't tell which tests are logging these errors, or if they're even what's causing the tests to fail.
=> Consolidate CI test output into a single string

.changeset/four-baboons-behave.md, packages/vertexai/src/constants.ts, packages/vertexai/src/requests/request.ts
We set a timeout to abort a request after 180s by default, but we don't cancel this timeout after the request completes. We should cancel this timeout after the request completes to prevent Node scripts from hanging.
I inlined everything in `buildFetchOptions` and removed that function. Let me know if I should revert this and initialize the `AbortController` in there- but I think the timeout-related code still has to be inlined so that we can get the `timeoutId`.
I tested this in a Node script using the default timeout and a custom timeout, and they both work as expected. If the timeout is triggered before the request completes, an `AbortError` is thrown. If the request completes before the timeout is triggered, the timeout is cancelled, and the Node script is able to exit.
Fixes …
=> Clear fetch abort timeout

.github/workflows/test-changed-auth.yml, .github/workflows/test-changed-firestore.yml, .github/workflows/test-changed.yml, config/karma.base.js
We locked the ubuntu image for Firefox tests 2 years ago: https://github.com/firebase/firebase-js-sdk/pull/6833 because the new image was having issues. Hopefully that's been fixed by now, trying ubuntu-latest.
Conclusion: Firefox installed with apt-get seems to cause issues on Ubuntu 22.04, perhaps because of some conflict with Ubuntu 22.04's own pre-installed Snap version of Firefox. This can be solved either by removing the Firefox install altogether or by installing with puppeteer instead, which seems to not cause a conflict. Although removing the install and relying on the image's pre-installed Firefox works fine, and Github seems to update their Ubuntu regularly so it always has the latest version of Firefox, I prefer to use puppeteer for explicit control over the version. Maybe we …
=> Use ubuntu-latest for Firefox CI tests

docs-devsite/_toc.yaml, repo-scripts/api-documenter/src/toc.ts
TAP YAML linter now requires there to be no array indentation, so we need to change how we generate our TOC. Fortunately we can do this by just changing a config in `js-yaml`.
=> Disable TOC array indentation

packages/firestore/src/local/memory_remote_document_cache.ts, packages/firestore/src/model/path.ts, packages/firestore/test/integration/api/database.test.ts
Document ID supports strings and well as long integers in the format of "id" . When sorting documents by document ID, it should be sorted in the following order:
1. Long (numeric order)
2. String (lexicographic order)
=> Fix: sort document reference by long type id

common/api-review/firestore-lite.api.md, common/api-review/firestore.api.md, packages/firestore/src/lite-api/expressions.ts, packages/firestore/test/integration/api/pipeline.test.ts
- Bytes instead of Uint8Array
- Record<string, any> instead of Map<string, any>
- Remove support for constant of `undefined`
- Remove support for constant of proto values
=> Fixes for Constant.of(...)

.github/workflows/e2e-test.yml, scripts/release/poll-npm-publish.js
Recently npm propagation after publish has been taking longer (there is some delay after a successful publish on the command line before that version is actually available to install). Adding polling using `npm view` to check every 60 seconds for 15 minutes and ensure the version is available for install before running the E2E firebase install. Hopefully that's enough.
=> Set e2e test workflow to poll npm to check the version is available

.github/workflows/check-vertexai-responses.yml
I think it should be safe to pin these third party Github actions to versions instead of commit hashes. Pinning it to a commit hash results in a lot of renovate PRs every time there's a new commit to that action.
=> Use versions instead of commits in vertexai responses actions scripts

.github/workflows/test-changed-firestore.yml, config/karma.base.js
There were a pair of `download-artifact` GitHub actions that were still set to `v3` instead of `v4`. The `v3` actions were unable to find the build archive in the test-changed-firestore workflow. This PR upgrades those to `v4` actions.
For an example of this failure, [check this CI run](https://github.com/firebase/firebase-js-sdk/actions/runs/12774755988/workflow?pr=8651).
CI.
N/A.
=> Upgrade two more `download-artifact` v3 actions to v4  in Firestore workflow

renovate.json
We need to stay on karma-webpack 5.0.0 - 5.0.1 has a ton of changes, one of which breaks us.
TLDR, karma-webpack 5.0.0 has one breaking bug for us that we get around by using patch-package. This bug was fixed in 5.0.1, but 5.0.1 also contained many other changes, one of which introduces a new bug for us. We must stay on 5.0.0 for now and continue using patch-package.
=> Have renovate ignore karma-webpack

.github/workflows/test-all.yml
Update our CI's logged `CHROME_VALIDATED_VERSION` to the currently tested version. We haven't updated it in a while.
Keeping this up to date should reduce support burden later.
CI
N/A
=> Workflow CI: Update CHROME_VALIDATED_VERSION for Auth tests

package.json, yarn.lock
The auto generated PR #8606 attempts to patch the `yarn.lock` file for a dependency associated with CVE-2024-37168 that was pulled in by the Google Cloud CLI.
Instead of only patching the yarn.lock file to update the transitive culprit `@grpc/grpc-js@~1.9.0`, let's just update the dependency that we use - the Firebase CLI tools.
Local build, CI.
This is a dev dependency update.
NA
=> Manual fix(deps): update dependency firebase-tools

.changeset/yellow-rice-kneel.md, packages/app/src/heartbeatService.test.ts, packages/app/src/heartbeatService.ts
Currently, we discard heartbeats once they are 30 days old. This PR changes this behaviour to only discard the earliest heartbeat once a limit of 30 heartbeats in IndexedDB has been reached.
=> Discard earliest heartbeat once there are 30 heartbeats

.changeset/chilled-clocks-remember.md, packages/database/src/core/PersistentConnection.ts
Fix for https://github.com/firebase/firebase-js-sdk/issues/8718
=> Fix negative offset of reconnect delay (#8718)

packages/auth/test/integration/flows/recaptcha_enterprise.test.ts
['throws error if recaptcha token is invalid'](https://github.com/firebase/firebase-js-sdk/blob/main/packages/auth/test/integration/flows/recaptcha_enterprise.test.ts#L106) sometimes fails with `auth/too-many-requests`. Skip the test for now to unblock the other PRs and the release.
We will consider increasing the quota for this API.
=> Skip flaky auth recaptcha test

packages/firestore/src/util/misc.ts
use platform based `newTextEncoder` creation instead of calling `TextEncoder` directly.
=> Fix: fix the "TextEncoder undefined" issue

common/api-review/firestore-lite.api.md, packages/firestore/src/lite-api/database.ts, packages/firestore/src/lite-api/settings.ts, packages/firestore/test/integration/api/validation.test.ts, packages/firestore/test/integration/util/settings.ts, packages/firestore/test/unit/api/database.test.ts
Update `connectFirestoreEmulator` to support its invocation more than once. If the Firestore instance is already in use, and `connectFirestoreEmulator` is invoked with the same configuration, then the invocation will now succeed instead of assert.
The implementation takes the Data Connect implementation as inspiration. Data Connect stores the parameters passed to `connectDataConnectEmulator` on the instance of Data Connect itself, so that they can be quickly checked to see if subsequent invocations match. This PR implements a similar storage and compare process with the optional `emulatorOptions` parameter (host and port are already stored).
This PR unlocks support for SSR frameworks which render the page numerous times with the same instances of Firestore. Before this PR customers were …
=> Emulator Idempotency: Firestore

.changeset/forty-bags-arrive.md, packages/database-compat/test/database.test.ts, packages/database/src/api/Database.ts, packages/database/src/core/RepoInfo.ts, packages/database/test/exp/integration.test.ts, packages/database/test/helpers/util.ts
Update the `connectDatabaseEmulator` function to support its invocation more than once. If the Database instance is already in use, and `connectDatabaseEmulator` is invoked with the same configuration, then the invocation will now succeed instead of assert.
This unlocks support for web frameworks which may render the page numerous times with the same instances of RTDB. Before this PR customers needed to add extra code to guard against calling `connectDatabaseEmulator` in their SSR logic. Now we do that guarding logic on their behalf which should simplify our customer's apps.
Fixes #6824.
CI, new tests added to integration tests.
N/A
=> Emulator Idempotency: Database

.changeset/lemon-candles-vanish.md, packages/auth/src/core/auth/emulator.test.ts, packages/auth/src/core/auth/emulator.ts
Update the `connectAuthEmulator` function to support its invocation more than once. If the Auth instance is already in use, and `connectAuthEmulator` is invoked with the same configuration, then the invocation will now succeed instead of assert.
This unlocks support for web frameworks which may render the page numerous times with the same instances of auth. Before this PR customers needed to add extra code to guard against calling `connectAuthEmulator` in their SSR logic. Now we do that guarding logic on their behalf which should simplify our customer's apps.
Fixes #6824.
CI, new tests added to `packages/auth/src/core/auth/emulator.test.ts`.
N/A
=> Emulator Idempotency: Auth

packages/vertexai/api-extractor.json
`publicTrimmedFilePath` trims all APIs with the `@beta` release tag. To allow beta/preview APIs to be published, we need to publish the `betaTrimmedFilePath`. This will be used for labelling Imagen APIs as public preview in #8683. Since we don't label any APIs as `@beta` or `@alpha` yet, there is no change to the typings (I confirmed that the diff is empty).
See: https://api-extractor.com/pages/setup/configure_rollup/
=> Publish VertexAI API's tagged with `@beta`

.changeset/seven-oranges-care.md, packages/vertexai/src/requests/stream-reader.test.ts, packages/vertexai/src/requests/stream-reader.ts, packages/vertexai/test-utils/mock-response.ts, scripts/update_vertexai_responses.sh
Fixes #8714 
When streaming responses, remove all empty text parts, since if we send these to the backend we'll get an error.
If a response contained only empty text parts, an error will be thrown in `validateChatHistory` for the candidate having no parts in it's content.
=> Filter empty text parts when streaming

.changeset/stale-llamas-hide.md, packages/vertexai/package.json, packages/vertexai/rollup.config.js, packages/vertexai/src/index.node.ts
Create a new Node entrypoint `index.node.ts` where we can make Node-specific modifications to the bundles. This will be required for upcoming features where Node and Web bundles use different libraries.
[go/firebase-js-sdk-vertex-node-bundle](http://goto.google.com/firebase-js-sdk-vertex-node-bundle) (internal)
=> Create VertexAI Node CJS and ESM bundles

.changeset/tough-kiwis-smile.md, packages/app-check/src/internal-api.test.ts, packages/app-check/src/internal-api.ts
The internal `getToken()` method should never throw - it's used by other product SDKs (auth, etc.) and it's up to those product SDKs to handle errors, which are attached to the token as a string property. We have a try/catch around the exchange logic for the normal token, which returns a dummy token and the error string when an error is caught, but we didn't have this same try/catch around the logic where we try to exchange the debug token. Added it.
=> Catch errors in debug token exchange logic

packages/vertexai/test-utils/mock-response.ts
If we call `getMockResponse` with a filename that doesn't exist, we'll get some confusing error like not being able to read a property from undefined. It'd be better if we just threw an error if the mock response file doesn't exist.
=> Throw error if mock response file not found

e2e/sample-apps/modular.js, e2e/tests/modular.test.ts
Add post-npm publish smoke tests for VertexAI and DataConnect. Also added the same cases to the sample apps.
=> Add Vertex and DataConnect E2E smoke tests

.changeset/silver-jeans-sell.md, common/api-review/database.api.md, docs-devsite/database.thenablereference.md, packages/database-types/index.d.ts, packages/database/src/api/Reference.ts, packages/database/src/api/Reference_impl.ts, packages/firebase/compat/index.d.ts
When using `push` to add data a `ThenableReference` is returned, this reference can never have an undefined `key` (or `parent`) because it's never going to be the root reference.
=> Added non-null properties to database.ThenableReference

.github/workflows/check-changeset.yml
This fixes an issue where a step fails with a 403 for no write permissions: https://github.com/firebase/firebase-js-sdk/actions/runs/13706506246/job/38332961549
=> Give `check-changeset` job write permissions on pull requests

.changeset/fluffy-otters-whisper.md, packages/app-check/src/api.ts, packages/app-check/src/errors.ts, packages/app-check/src/internal-api.test.ts, packages/app-check/src/internal-api.ts, packages/app-check/src/providers.ts
The two main changes here are
- throw "internalError" (background: https://github.com/firebase/firebase-js-sdk/pull/6617) in the public-facing `getToken()` method. Errors here should not block 2P calls to App Check (internal calls from Auth, Firestore, etc)
- Distinguish between an initial network error that causes throttling, and an error thrown by attempting to make a call while a throttle is in effect
I've also decided to stop logging getToken errors with `console.error` - these should all be thrown by the public `getToken()` now, and the internal products calling getToken internally (Auth, Firestore, etc.) have access to the error message in a property of AppCheckTokenResult which they can log in the format they choose.
Fixes #8822
=> Surface all App Check errors in public getToken() method

.github/workflows/release-pr.yml
Our staging release workflow failed to create a Version Packages PR. Grant the PR creation workflow `pull-request` `write` permissions.
N/A.
N/A.
=> [Workflows] Give Create PR workflow pull-request write perms

.github/workflows/release-pr.yml
Our staging release workflow failed to merge branch. Grant the PR creation workflow `content` `write` permissions to fix this.
N/A.
N/A.
=> [Workflows] Grant Create PR workflow content write perms

.changeset/tricky-geese-shout.md, common/api-review/vertexai.api.md, docs-devsite/vertexai.groundingattribution.md, docs-devsite/vertexai.groundingmetadata.md, packages/vertexai/src/types/responses.ts
`GroundingAttribution` is deprecated and will never be defined. We should label this as deprecated so users don't use it. In the next major release, we should remove this.
=> Deprecate `GroundingAttribution`

.github/workflows/test-all.yml
Use lerna --stream and skip run_tests_in_ci script to ensure we are not missing any logs from failed tests.
This causes really long logs but we don't lose the error. So far on this PR, I tried 2 runs and it errored in 2 different places, which is more info than we were getting before.
=> Stream full logs of test-all firestore job

packages/firestore/src/core/pipeline-util.ts
Port improved whereConditionsFromCursor from Android
=> Port improved whereConditionsFromCursor from Android

.changeset/slow-students-fry.md, packages/firestore/src/local/simple_db.ts
If using IndexedDB persistence with Firestore and a user clicks the "Clear Site Data" button in a web browser, the IndexedDB database is closed (as expected); however, it is re-opened as soon as it is needed again, under the assumption that the database contents haven't changed. This incorrect assumption can lead to writing inconsistent data into the database, causing all sorts of problems.
One notable problem is that if a snapshot listener receives an "update" after "Clear Site Data" was clicked, then it will write the updated document contents into the database as if the rest of the information (e.g. the target) is also in the database. This is an inconsistent database state. If, then, the web page is reloaded, it will misinterpret the data in the database and produce document snapshots …
=> firestore: fix `undefined` document snapshot data after "clear site data"

packages/firestore/karma.conf.js, packages/firestore/test/unit/util/bundle.test.ts
Firestore's Karma config overwrites the `browsers` that are set in the base karma config:https://github.com/firebase/firebase-js-sdk/blob/main/packages/firestore/karma.conf.js#L24
`getTestBrowsers(argv)` only uses the `BROWSERS` environment variable if it's running the unit tests: https://github.com/firebase/firebase-js-sdk/blob/main/packages/firestore/karma.conf.js#L81
We want the `BROWSERS` environment to always define the browser to use- regardless of whether we're running unit tests.
=> Use base browsers variable in Firestore karma config

e2e/package.json, integration/messaging/package.json, package.json, packages/auth-compat/package.json, packages/auth/package.json, packages/firestore/package.json, repo-scripts/changelog-generator/package.json, repo-scripts/size-analysis/package.json, yarn.lock
Update some deps from https://github.com/firebase/firebase-js-sdk/pull/5566 Focused on simple ones that are unlikely to affect the build (mostly used for tests).
- @types/json-stable-stringify (Removing entirely, as the new version says it is only a stub that is no longer needed because `json-stable-stringify` brings its own types, and in fact adding the `@types` package now causes errors.)
- chai
- express
- playwright
- selenium-webdriver
- webpack
=> [chore] Update some dependencies

.changeset/gentle-rocks-repeat.md, packages/firestore/externs.json, packages/firestore/src/local/simple_db.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/6465
Call the "indexedDb" on `self/window/global` based on availability.
=> Fix 'window is not defined' error when calling `clearIndexedDbPersistence`

.changeset/hungry-snails-drive.md, common/api-review/data-connect.api.md, packages/data-connect/src/api/index.ts, packages/data-connect/src/core/error.ts
`DataConnectOperationError` extends `DataConnectError`, both of which have tags `@hideconstructor`. This means that in public builds, our output marks the constructors as `private`. However, this causes an error to be thrown: `cannot extend private constructor`, because `DataConnectOperationError` extends `DataConnectError`, which has a private constructor. The reason why this wasn't caught during integration tests is because to integration tests, the constructors aren't private, but for public builds (that are used by external devs), the constructors *are* private. So the only way we could've caught this would've been to use the published version (or packaged version) of the SDK.
TL;DR: Fix error where if we exported `DataConnectError`, then when using the types, the user would get a …
=> Fix Data Connect Types

.changeset/cyan-frogs-relate.md, packages/firestore/src/core/filter.ts, packages/firestore/test/integration/api/query.test.ts, packages/firestore/test/unit/core/query.test.ts
ported from https://github.com/firebase/firebase-ios-sdk/pull/14704
=> fix: remove `null` value inclusion from `!=` and `not-in` filter results

packages/vertexai/test-utils/convert-mocks.ts
This directory was renamed to `googleai` in https://github.com/FirebaseExtended/vertexai-sdk-test-data/pull/33.
=> test(vertexai): update developerapi mock response dir to googleai

packages/vertexai/src/types/index.ts, packages/vertexai/src/types/language-model.ts
Add LanguageModel types.
Based off: https://github.com/webmachinelearning/prompt-api?tab=readme-ov-file#full-api-surface-in-web-idl.
=> Vaihi add langmodel types.

.changeset/great-cheetahs-invite.md, packages/auth/src/core/action_code_url.test.ts, packages/auth/src/core/action_code_url.ts
It was observed that the parameter used for language code in the backend is `lang` and not `languageCode`, due to which `ActionCode.languageCode` will always be null. This is to fix the query parameter, so that the languageCode is populated correctly after parsing.
Issue was originally reported for ios-sdk at https://github.com/firebase/firebase-ios-sdk/issues/14664
Updated unit tests.
=> Fix languageCode parameter in action_code_url

common/api-review/vertexai.api.md, docs-devsite/vertexai.md, docs-devsite/vertexai.modelparams.md, docs-devsite/vertexai.requestoptions.md, packages/vertexai/src/api.test.ts, packages/vertexai/src/api.ts
Adding smoke test for new hybrid params + Fix some naming.
=> Adding smoke test for new hybrid params

common/api-review/vertexai.api.md, docs-devsite/vertexai.md, packages/vertexai/src/api.test.ts, packages/vertexai/src/types/enums.ts, packages/vertexai/src/types/requests.ts
Moving to string type for the inference mode
=> Moving to string type for the inference mode

packages/vertexai/src/methods/chrome-adapter.test.ts, packages/vertexai/src/methods/chrome-adapter.ts, packages/vertexai/src/methods/count-tokens.test.ts, packages/vertexai/src/methods/count-tokens.ts, packages/vertexai/src/models/generative-model.ts
=> Adding count token impl

packages/vertexai/src/types/language-model.ts
`LanguageModel.availability()` returns `Availability` in TS, but a string in JS, causing the comparison to fail. Since we define the TS types for `LanguageModel` (for now, at least), we can define string values for the `Availability` enum, which enables the comparison to work as expected.
=> VinF Hybrid Inference: Define Availability values

packages/vertexai/src/methods/chrome-adapter.test.ts, packages/vertexai/src/methods/chrome-adapter.ts
Adding image inference support.
=> Add image inference support

e2e/sample-apps/modular.js, packages/vertexai/src/methods/chrome-adapter.test.ts, packages/vertexai/src/methods/chrome-adapter.ts
Problem: we're currently falling back to Cloud even if the mode is only_on_device.
Proposal:
1. isAvailable should return true unconditionally if mode is only_on_device
2. createSession should throw if the model is unavailable
Also: remove stale tests for systemInstruction; I added a backlog item for figuring out if we want to honor systemInstruction passed in the request vs onDeviceParams.
=> VinF Hybrid Inference: throw if only_on_device and model is unavailable

packages/vertexai/src/methods/chrome-adapter.test.ts, packages/vertexai/src/methods/chrome-adapter.ts
We can't differentiate roles until Chrome supports the [LanguageModelMessage type](https://github.com/webmachinelearning/prompt-api?tab=readme-ov-file#full-api-surface-in-web-idl).
Multi-turn requests [differentiate turns by role](https://github.com/firebase/firebase-js-sdk/blob/dd0c4b10d21bd783b856b24e8594b5b030fc4a56/packages/vertexai/src/methods/chat-session.ts#L110-L115), so without roles, we can't support multi-turn.
We can't throw to indicate a lack of support, like we can with countToken, because ChromeAdapter integrates below 
ChatSession.
Bug: b/413402604
This change indicates a lack of support for multi-turn requests by updating the request validator to fail if a request contains non-"user" roles. We can relax this once LanguageModelMessage is released.
=> VinF Hybrid Inference: disable multi-turn support

packages/vertexai/src/methods/chat-session-helpers.ts
Add missing closing single quote to error message.
Is a changeset necessary here?
=> fix(vertexai): add missing quote to chat role error message

packages/vertexai/src/methods/chrome-adapter.test.ts, packages/vertexai/src/methods/chrome-adapter.ts
We [stopped setting image as a default input type](https://github.com/firebase/firebase-js-sdk/pull/8974) due to some confusion about the minimum support we require. We've since clarified that we're targeting v138+, which will default to multi-modal.
This change restores the logic to set image as an expected input type by default. (Text is implicitly supported.)
This change also guards against unsupported mime types, since this is a much more convenient experience than handling exceptions.
=> VinF Hybrid Inference: set image (and text) as default input type

packages/vertexai/src/googleai-mappers.test.ts, scripts/update_vertexai_responses.sh
The test files have been updated to include `json` extension versions of the tests files. The old, `txt` extension files are deprecated and will be deleted eventually.
=> [vertexai] Use json of unary-success-citations

e2e/sample-apps/modular.js, packages/vertexai/src/methods/chrome-adapter.ts
We had some feedback today that logging would be helpful. https://github.com/firebase/firebase-js-sdk/pull/8991 addresses the code that feedback pertained to, but the SDK has some relatively complex conditional logic and logging would help clarify what the SDK is doing.
=> VinF Hybrid Inference: log debug messages in conditional logic

.changeset/lemon-tomatoes-breathe.md, packages/auth/src/core/auth/emulator.test.ts, packages/auth/src/core/auth/emulator.ts
Fix an emulator issue where if no auth port is specified, then `null` is passed into the `pingServer` URL.
=> Fix Auth Port for Firebase Studio

.changeset/afraid-baboons-develop.md, docs-devsite/app.firebaseappsettings.md, packages/app-check/src/api.test.ts, packages/app-check/src/api.ts, packages/app-compat/test/firebaseAppCompat.test.ts, packages/app/src/api.test.ts, packages/app/src/api.ts, packages/app/src/firebaseApp.test.ts, packages/app/src/firebaseServerApp.ts, packages/app/src/public-types.ts
This change should default `automaticDataCollectionEnabled` to true (it previously defaulted to false).
This value is only consumed by App Check and Vertex.
App Check has been modified so that it retains the previous behavior (that automatic token refresh is off by default and will be turned on if `isTokenRefreshEnabled` is explicitly set to true). The only unexpected behavior may be that setting `isTokenRefreshEnabled` will do nothing if `automaticDataCollectionEnabled` is set to false. This is unlikely to happen as users rarely touch `automaticDataCollectionEnabled` and this PR defaults it to true. I have added a logged warning just in case, but this is expected to be an edge case.
This affects Vertex in that it allows sending data for AI monitoring by default.
=> Change automaticDataCollectionEnabled to default to true.

.changeset/blue-spies-visit.md, docs-devsite/app.firebaseappsettings.md, packages/app-check/src/api.test.ts, packages/app-check/src/api.ts, packages/app-compat/test/firebaseAppCompat.test.ts, packages/app/src/api.test.ts, packages/app/src/api.ts, packages/app/src/firebaseApp.test.ts, packages/app/src/firebaseServerApp.ts, packages/app/src/public-types.ts
Reverting #8999. The backend isn't ready to accept the Vertex header that would be sent by defaulting this var to true. It should be ready by the I/O release next week.
=> Roll back #8999

.changeset/fast-mangos-chew.md, packages/vertexai/src/models/generative-model.test.ts, packages/vertexai/src/models/generative-model.ts
DO NOT MERGE.
`startChat` wasn't passing `GenerativeModel`'s `BaseParams` to `ChatSession`. 
So, if a model had a `generationConfig`, it would never be passed to `ChatSession`.
This is how the other SDKs behave.
=> fix(vertexai): pass `GenerativeModel`'s `BaseParams` to `ChatSession`

.vscode/launch.json
- Added debug launch config for `AI Unit Tests (node)`
- Formatted the file (VSCode's JSON auto-formatter)
- Removed `"protocol": "inspector"`. I believe this is no longer supported since VSCode gives a warning `Property protocol is not allowed`.
=> Clean up vscode launch file and add vertexai debug config

.changeset/ninety-ways-dress.md, docs-devsite/app.firebaseappsettings.md, packages/app-check/src/api.test.ts, packages/app-check/src/api.ts, packages/app-compat/test/firebaseAppCompat.test.ts, packages/app/src/api.test.ts, packages/app/src/api.ts, packages/app/src/firebaseApp.test.ts, packages/app/src/firebaseServerApp.ts, packages/app/src/public-types.ts
#8999 was rolled back in #9007 because the backend was not ready. This should be merged again when it is confirmed the backend will be able to accept the header.
=> Restore #8999

packages/ai/src/methods/chrome-adapter.test.ts, packages/ai/src/methods/chrome-adapter.ts
I was using the e2e test and noticed it was throwing an exception from `countToken`.
We intentionally throw from `countToken` in the hybrid case, but it was surprising to see that error in the non-hybrid case. 
Turns out, `mode` is undefined in the non-hybrid case, but we weren't guarding for that.
Explicitly guard against an undefined `mode`
=> AI Hybrid Inference: guard against undefined mode

e2e/package.json, e2e/sample-apps/modular.js, e2e/tests/modular.test.ts, e2e/yarn.lock
Currently uses VertexAIBackend because the GoogleAIBackend isn't public yet.
=> Update e2e tests to reflect AI package and new API

.changeset/large-windows-mate.md, packages/auth/src/core/auth/emulator.ts, packages/data-connect/src/api/DataConnect.ts, packages/database/src/api/Database.ts, packages/firestore/src/lite-api/database.ts, packages/functions/src/service.ts, packages/storage/src/service.ts
Only show emulator banner when:
* Calling `connect*Emulator`
* On Firebase Studio
=> Updated to only show banner when calling connect*Emulator

.changeset/spotty-ghosts-kneel.md, packages/firestore/src/platform/browser/webchannel_connection.ts
CI logs showed that some WebChannel connections were being left open after tests. This change implements the `terminate()` method on the `WebChannelConnection` class to ensure that any open WebChannelConnections are closed when the SDK terminates.
=> Close webchannel instances on terminate

config/karma.base.js
Reorder reporters in karma config to prevent log message duplication. Currently in CI actions that run Karma, all SDK logging is rendered twice ([example](https://github.com/firebase/firebase-js-sdk/actions/runs/15026164402/job/42227656801?pr=9039#step:7:509)). This fixes the issue.
See also: https://github.com/karma-runner/karma/issues/2342#issuecomment-1304180955
=> ci: Reorder reporters to prevent log message duplication

common/api-review/ai.api.md, packages/ai/src/methods/chrome-adapter.test.ts, packages/ai/src/methods/chrome-adapter.ts, packages/ai/src/types/language-model.ts
NOTE: this is a placeholder until support is added
Chrome will add support for the official `LanguageModelMessage[]` input type, so this change updates the hybrid SDK to normalize to that type rather than `LanguageModelMessageContent[]`.
=> AI Hybrid Inference: migrate to LanguageModelMessage

config/karma.base.js, packages/util/test/errors.test.ts, scripts/run_tests_in_ci.js
The main purpose was to fix a Firefox CI test error on one of the util tests - a recent version of Firefox causes the error class to no longer be stored in `error.stack` and our test that checks for the "FirebaseError" string on a purposefully thrown error now fails. There's no recognizable string in the stack anymore (just code locations), so I just changed it to just check for its existence.
In the course of trying to diagnose this I followed a false trail thinking it might be because Node tests were running during Firefox and Webkit tests. That wasn't the cause but they shouldn't be running during those jobs, it's pointless. Node tests already run during the main Chrome test job. I changed it so that all packages running a cross-browser test use:
1. "test:browser" if available
2. …
=> ci: Fix Firefox error and streamline cross-browser tests

.changeset/wicked-scissors-yell.md, packages/auth/src/api/authentication/token.test.ts, packages/auth/src/api/authentication/token.ts
Fixes issue where the Firebase Studio cookie wasn't passed in when requesting a new cookie from the emulator.
=> Fixed issue where requestSts wasn't including the Studio cookie in it

.changeset/old-candles-confess.md, common/api-review/ai.api.md, docs-devsite/ai.counttokensresponse.md, packages/ai/src/types/responses.ts
Add deprecation tag to `totalBillableCharacters`. This field is no longer populated when using models greater than `gemini-1.5-*`, since the newer models count tokens, not characters. Developers should use `totalTokens` instead.
=> fix(ai): Add deprecation tag to `totalBillableCharacters`

packages/ai/integration/chat.test.ts, packages/ai/integration/constants.ts, packages/ai/integration/generate-content.test.ts
Added `gemini-2.5-flash` to our integration tests now that it's publicly available.
The token counts differ slightly between `2.0-flash` and `2.5-flash` so I introduced conditionals when checking token counts.
=> test(ai): Add `gemini-2.5-flash` to integration tests

.changeset/brown-pens-confess.md, common/api-review/util.api.md, packages/storage/src/platform/browser/connection.ts, packages/storage/test/browser/connection.test.ts, packages/util/src/url.ts
Fixed CORS issue when using Storage with Firebase Studio
=> Fixed issue where storage wasn't passing cookies when using firebase Studio

packages/auth/src/core/providers/saml.test.ts
* Increase unit test coverage for saml.ts to 100%
* 100% code coverage & branch coverage - https://screenshot.googleplex.com/BDvvZcHSWdb3FkK
* Unit test passing locally.
=> Increase unit test coverage for saml.ts to 100%

packages/firestore/src/util/misc.ts
This PR enhances the documentation for the `compareUtf8Strings()` method by adding a concrete example. This example illustrates the nuances of comparing Unicode strings, particularly how characters represented by surrogate pairs in UTF-16 can compare differently than the lexicographical comparison of their UTF-8 encoding.
This PR is in response to review comment https://github.com/firebase/firebase-android-sdk/pull/7098#pullrequestreview-2994517806 and is a port of https://github.com/firebase/firebase-android-sdk/pull/7113
=> docs(firestore): add an example to the detailed comment in compareUtf8Strings()

.github/workflows/test-all.yml, packages/auth/demo/public/index.html, packages/auth/demo/src/index.js, packages/auth/demo/yarn.lock, packages/auth/src/core/auth/auth_impl.test.ts, packages/auth/src/core/auth/auth_impl.ts
* Implement signOut for BYO-CIAM firebaseToken
* Added Unit test
* Demo App testing - https://screenshot.googleplex.com/4Hk7FZ7LycJ6Y86
=> Implement signOut for BYO-CIAM firebaseToken

.changeset/hungry-icons-dream.md, packages/firestore/src/core/firestore_client.ts, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/persistence.ts, packages/firestore/src/local/simple_db.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
This appears to resolve the timeout issues in firestore-compat tests.
=> Revert "firestore: minor refactor of listener registration of "versionchange" indexedb events (#9087)

docs-devsite/ai.groundingmetadata.md, docs-devsite/ai.md, docs-devsite/app.md, packages/ai/src/types/imagen/requests.ts, packages/ai/src/types/responses.ts, packages/app/src/api.ts, packages/firestore/src/local/indexeddb_persistence.ts
Backport for typos found and fixed while preparing reference docs for devsite in g3.
* double "the"
* misspelled "environment"
* Use of "smart quotes" (double-quote character that is different for the opening and closing quote)
The g3 change only flagged the ai.groundingmetadata.md file but I searched the repo to find any other instances of those special characters and fixed the other ones I found (in a Firestore file).
=> docs: fix doc typos found by g3 presubmit

docs-devsite/ai.chromeadapter.md, docs-devsite/ai.requestoptions.md, packages/ai/src/methods/chrome-adapter.ts, packages/ai/src/types/chrome-adapter.ts, packages/ai/src/types/requests.ts
Backfill documentation fixes per cl/791925900 (internal).
- remove `<p>` tags - these are not generally necessary and cause markdown inside them to not work
- add a link to console to the RequestOptions description
- use `@remarks` to separate extra details of a method from the summary that should go in the table of contents at the top
=> Backfill fixes for hybrid docs

packages/telemetry/.eslintrc.js, packages/telemetry/CHANGELOG.md, packages/telemetry/README.md, packages/telemetry/index.node.ts, packages/telemetry/index.ts, packages/telemetry/karma.conf.js, packages/telemetry/package.json, packages/telemetry/rollup.config.js, packages/telemetry/src/index.test.ts, packages/telemetry/src/index.ts, packages/telemetry/src/types/index.ts, packages/telemetry/tsconfig.json
Create new Telemetry package by copying template package, with minimal changes
yarn --cwd packages/telemetry test
N/A
=> Add new Telemetry package

packages/telemetry/index.node.ts, packages/telemetry/package.json, packages/telemetry/rollup.config.js, packages/telemetry/src/api.ts, packages/telemetry/src/constants.ts, packages/telemetry/src/index.node.ts, packages/telemetry/src/public-types.ts, packages/telemetry/src/service.ts
Copied some boilerplate code to initialize telemetry package
No new unit tests yet. Built, ran existing tests, linked to a test app.
N/A
=> Basic scaffolding to init telemetry package

.changeset/stupid-files-reflect.md, common/api-review/ai.api.md, docs-devsite/ai.md, packages/ai/src/index.ts
Bug introduced by https://github.com/firebase/firebase-js-sdk/pull/9201
Accidentally exported `factory` causing it to also export `AIService` and expose some references to internal-only typings, which breaks a strict typescript compile.
Fixes https://github.com/firebase/firebase-js-sdk/issues/9231
=> fix(ai): remove accidental factory export

.changeset/young-timers-jump.md, packages/analytics-interop-types/index.d.ts, packages/analytics/src/index.ts, packages/messaging/src/testing/fakes/firebase-dependencies.ts
This allows other Firebase product packages to call the Analytics method `setUserProperties()` internally in the same way they can currently call `logEvent()`. This will be needed for an upcoming Remote Config feature.
Tested this by temporarily adding some code to messaging (the only other product SDK that currently depends on the internal analytics instance) so that it calls `setUserProperties()` (then removing it after the test). This succeeded.
Edit: No changeset for messaging because it's only a test change.
=> Expose setUserProperties from internal analytics instance

packages/auth/src/core/auth/auth_impl.test.ts, packages/auth/src/core/auth/auth_impl.ts
Update refresh token buffer from 30 seconds to 60 seconds.
* Unit test added
=> Update refresh token buffer from 30 seconds to 60 seconds

packages/auth/demo/public/index.html, packages/auth/demo/src/index.js
Demo app improvements.
Deployed the demo app - https://manandarji-testproject-2.web.app/
=> Demo app improvements.
