firebase/firebase-js-sdk

.travis.yml, README.md, README.public.md, package.json, yarn.lock
=> feat(travis-ci): add .travis.yml [triage-skip]

gulp/tasks/test.integration.js, src/app/firebase_app.ts, tests-integration/bundlers/browser/lazy-app.test.js, tests/app/unit/firebase_app.test.ts, tsconfig.test.json
Fixes #14 
Live demo available here:
http://jsbin.com/zozuqeh/edit?js,console
=> Allow for lazy registration of app components

src/app/firebase_app.ts, tests/app/unit/firebase_app.test.ts
FirebaseApp's contract with the components is that the instanceIdentifier will be `undefined` in the
default case (not the string `[DEFAULT]`). This was not tested by any existing tests and was broken in the async refactor. This fixes that issue and adds a test.
=> fix(app): fix issue with default instanceIdentifier [triage-skip]

.travis.yml
With the release of Node.js 8.0, our travis builds are failing.
Pinning Travis to version 6 of Node.
=> fix(travis.yml): pin Node.js version to 6 [triage-skip]

gulp/tasks/build.js, package.json, yarn.lock
This refactors our build process a bit to generate the sourcemaps slightly differently for the main compiled assets (mapping them all the way back to the `.ts` source).
In addition I have refactored the main firebase.js file to properly reference the sourcemaps of the 5 concatenated binaries.
=> fix(sourcemaps): fix sourcemap generation for browser code [triage-skip]

src/app/firebase_app.ts, tests/app/unit/firebase_app.test.ts
FirebaseAppImpl should not extend prototype.INTERNAL as this will apply to
all Firebase app instances.
To reproduce, do the following:
var app1 = firebase.initializeApp(config);
var app2 = firebase.initializeApp(config, 'app2');
console.log(app1.INTERNAL === app2.internal);
The above incorrectly resolves to true.
This means that if I sign in with app1.auth() and then call app1.INTERNAL.getToken(),
it will resolve with null as it is getting app2.INTERNAL.getToken.
The last initialized instance will basically overwrite all existing ones.
This is currently breaking all FirebaseUI-web single page applications
using Firebase real-time database with JS version >= 4.1.0:
https://github.com/firebase/firebaseui-web/issues/47#issuecomment-306648715
This should also be breaking any application using …
=> fix(app): fix issue with FirebaseApp extending INTERNAL

gulp/tasks/build.js
Creates a custom `webpackJsonpFirebase` function for webpack chunk output.
ISSUES CLOSED: #42
=> fix(core): utilize "webpackJsonpFirebase" for Webpack JSONP output func

src/storage/implementation/observer.ts, tests/storage/browser/task_test.ts
See issue #40
Test added.
None.
=> fix(storage): allow missing some methods in UploadTask observer

src/app/firebase_app.ts, tests/app/unit/firebase_app.test.ts
Fix for issue #69 
This implements the option 1 approach mentioned in the linked issue.
Note: Once the `ts-database/add-new-impl` branch has been merged into `master`, the `contains` function definition should be replaced with an import from [`src/utils/obj.ts`](https://github.com/firebase/firebase-js-sdk/blob/7efa1b0d40d8e20bf85042cb12c650333d540880/src/utils/obj.ts#L3-L5)
Added 2 tests
None.
=> fix(app): Allow Object.prototype member names as app names

externs/firebase-app-externs.js, externs/firebase-app-internal-externs.js, externs/firebase-auth-externs.js, externs/firebase-messaging-externs.js, externs/firebase-storage-externs.js, typings/app.d.ts, typings/firebase.d.ts
=> Typings: Add Observer interface and improve typings for Auth, Storage, and Messaging

src/database/core/util/EventEmitter.ts
This was throwing a TypeError every time my online state changed, if there were no listeners on `.info/connected`
=> Prevent using uninitialized array in EventEmitter

externs/firebase-externs.js
Removes the window.atob function extern provided by the browser natively.
=> fix(externs): fix window var provided extern

src/database/api/Reference.ts, src/database/api/TransactionResult.ts, tests/database/transaction.test.ts
To address https://stackoverflow.com/questions/43151022/cloud-functions-for-firebase-onwrite-timeout, this adds a toJSON method() in TransactionResult.
This also addresses Google-internal bug https://b.corp.google.com/issues/62262817 and allows transaction objects to be returned from GCF.
=> fix(database): Adding toJSON() method to TransactionResult

src/app.ts, src/utils/shims.ts
These two functions are part of ES2015 and are not present in IE11. In the migration we removed
closure compiler which was injecting these by default
=> fix(ie11): add Array.prototype.find/findIndex polyfills

package.json
=> chore(publish): 4.2.0

CONTRIBUTING.md
Update the CONTRIBUTING.md to better communicate community expectations.
=> Contributing updates [triage-skip]

typings/app.d.ts, typings/firebase.d.ts
Do we really want to return undefined in these methods? I think we just want them to be void right?
Fixes: https://stackoverflow.com/questions/45386915/wrong-function-definition-in-typescript
=> Remove the need to return undefined in typings

src/database.ts, src/database/core/Repo.ts, src/database/core/RepoManager.ts, tests/database/database.test.ts
This enables database to leverage multi instance feature enabling multiple database instances per app.
=> feat(database): enable database multi-resource support

externs/firebase-auth-externs.js
Fixes issue with Auth interfaces not being instantiated.
=> fix(externs): fix auth externs

.cz-config.js, integration/browserify/karma.conf.js, integration/browserify/namespace.test.js, integration/browserify/runner.sh, integration/messaging/download-browsers.js, integration/messaging/runner.sh, integration/messaging/test/send-receive-msg.js, integration/messaging/test/static/manual-test-server.js, integration/messaging/test/static/shared-files/app.js, integration/messaging/test/static/shared-files/firebase-messaging-sw.js, integration/messaging/test/static/test-server.js, integration/quickstart/karma.conf.js, integration/quickstart/runner.sh, integration/quickstart/src/database.test.ts, integration/quickstart/src/storage.test.ts, integration/quickstart/wdio.conf.js, integration/serviceWorker/karma.conf.js, integration/serviceWorker/runner.sh, integration/serviceWorker/webpack.config.js, integration/shared/validator.js, integration/typescript/karma.conf.js, integration/typescript/runner.sh, integration/typescript/src/namespace.test.ts, integration/typescript/src/typings.d.ts, integration/webpack/karma.conf.js, integration/webpack/namespace.test.js, integration/webpack/runner.sh, integration/webpack/webpack.config.js, src/utils/shims.ts
This fixes all known conformance issues.
=> Add licenses to files that are missing them

src/firestore/api/database.ts, tests/firestore/integration/api/validation.test.ts
This is for Google-internal bug b/67419579
=> Rejecting 'null' and 'undefined' as arguments for CollectionReference.doc()

packages/firestore/src/api/database.ts
This should work fine, but there seems to be an issue with our minification process where usages of _databaseId get minified but the actual property does not, causing runtime errors. :-(
I've opened https://github.com/firebase/firebase-js-sdk/issues/194 and https://github.com/firebase/firebase-js-sdk/issues/195 to track the underlying causes.
=> Avoid "private" getter _databaseId, since it breaks the minified build.

.prettierignore, packages/firebase/gulpfile.js, packages/firebase/package.json, packages/firebase/webpack.config.js, yarn.lock
Fixes an issue where `firebase-firestore.js` could not be loaded alongside `firebase.js`
=> Fix for issue where firestore could not be loaded alongside firebase.js

packages/firestore/package.json, packages/firestore/src/api/database.ts, packages/firestore/src/core/firestore_client.ts, packages/firestore/src/remote/remote_store.ts, packages/firestore/test/integration/api/database.test.ts, packages/firestore/test/integration/api/query.test.ts
This is the JS port of https://github.com/firebase/firebase-ios-sdk/pull/347
=> Adding goOnline/goOffline to the Web SDK

packages/firestore/src/api/database.ts, packages/firestore/test/integration/api/database.test.ts, packages/firestore/test/integration/api/query.test.ts
@jshcrowthe I thought this would fix the issue with the integration tests, but there are still some failing for a different reason.  I'm not sure what's going on, and unfortunately I have to run.  I can't take a look until later tonight.  If this is blocking you, feel free to disable the minified integration tests for the moment. I'll figure it out tonight or tomorrow. :-/
=> Expose enable/DisableNetwork() via INTERNAL so it can be used in tests (but don't add to our .d.ts at least for now).

packages/firebase/index.node.js
These packages do not exist in version `4.5.0` of the JS SDK.
=> Removing storage/messaging from node build (included by accident)

packages/firestore/test/integration/bootstrap.ts, packages/firestore/test/unit/bootstrap.ts
I'm about to send a subsequent PR that reenables our serializer tests (under a /node/ directory).
=> Exclude node tests in the browser.

packages/firebase/index.js
I just was looking at our package and noticed that we are duplicating this require statement unnecessarily.
It is also included here:
https://github.com/firebase/firebase-js-sdk/blob/master/packages/firebase/app/index.js#L17
=> Removing Duplicate Require

.travis.yml
We are getting some issues where tests will fail on push but not on PR.
This disables the branch whitelist to ensure we are running push build tests in Travis as well.
=> Disabling travis branch restriction

integration/firestore/package.json
This will just help to prevent from accidentally publishing this as an npm package.
=> Refactor firestore int tests to be a private package

packages/database/index.node.ts
Creating a standalone entrypoint for the `firebase-admin-node` package to better consolidate the codebases.
=> Adding an entrypoint for firebase-admin-node

packages/firebase/app/index.d.ts, packages/firebase/index.d.ts, packages/firestore/src/api/database.ts, packages/firestore/src/typings/firestore.d.ts, packages/firestore/test/integration/api/database.test.ts, packages/firestore/test/integration/api/type.test.ts, packages/firestore/test/util/equality_matcher.ts
This is a port of the tests for the fix I made for Android (and implementing isEqual).  Note that the isEqual() API was previously discussed (when it was added for RTDB).  See internal issue b/62143881 for more details.
=> Add isEqual() and port DocumentReference array test.

.gitignore, packages/firestore/src/api/user_data_converter.ts, packages/firestore/test/integration/api/validation.test.ts
With this change indirectly nested arrays are allowed. We still disallow
directly nested arrays.
Fixes internal bug b/66253451.
Port of firebase/firebase-ios-sdk#377
=> Fix validation of nested arrays to allow indirect nesting

packages/database/test/transaction.test.ts
The test "Transaction without local events (2)" is inherently racey (we're trying to do 4 sets on one connection before the other connection retries the transaction 25 times). And when it fails, it could cause the rest of the tests to fail by not calling restoreHash().  So I've disabled the test and made the restoreHash handling a bit more robust so similar cascading failures can't happen in the future.
=> Try to address flaky database transaction tests.

packages/firebase/webpack.config.js
There was a minification error causing some odd issues with auth state persistence.
Fixes #230
=> Fixing named prop "_lat"

.vscode/launch.json, config/karma.base.js, packages/firestore/CONTRIBUTING.md, packages/firestore/README.md, packages/firestore/karma.conf.js, packages/firestore/test/integration/util/helpers.ts
See new packages/firestore CONTRIBUTING.md doc for new abilities.
Changes:
* Add --local flag to run against a localhost Firestore server.
* Add --unit and --integration flags to limit to unit or integration tests.
* Make --grep work with karma / mocha to limit the tests that run.
* Change default karma port to 8089 to avoid conflicting with localhost
Firestore server on 8080 (and other common web servers that default
to 8080).
=> Dev-X improvements for running Firestore tests.

packages/firestore/test/integration/api/database.test.ts, packages/firestore/test/integration/api/query.test.ts, packages/firestore/test/integration/api/smoke.test.ts, packages/firestore/test/integration/api/transactions.test.ts, packages/firestore/test/integration/api/type.test.ts, packages/firestore/test/integration/api/validation.test.ts
For context: I had a failure this morning that I think may have been caused by this
=> Avoid using hardcoded document paths which could cause conflicts when tests are running concurrently (e.g. on Travis).

packages/firestore/src/api/database.ts, packages/firestore/src/api/user_data_converter.ts, packages/firestore/test/integration/api/database.test.ts, packages/firestore/test/integration/api/validation.test.ts
This adds support for deleting fields with merges.
This is a port of cr/172802651.
=> Allowing field deletes with merge-enabled sets

packages/firestore/package.json, packages/firestore/test/unit/generate_spec_json.js, packages/firestore/test/unit/generate_spec_json.sh
* The tsconfig path was broken after the recent repo refactor.
* We were accidentally leaving a .ts in the destination json file names.
* I made it so the destination directory doesn't need to exist in advance.
=> Fix generate_spec_json script.

packages/firebase/app/index.d.ts, packages/firebase/index.d.ts
@tstirrat noticed this was missing.
=> Firestore typings fix: Add firestore() to firebase.app.App.

packages/firestore/test/integration/remote/remote.test.ts, packages/firestore/test/integration/remote/stream.test.ts, packages/firestore/test/integration/util/helpers.ts
This is a port of https://github.com/firebase/firebase-ios-sdk/pull/391
=> Creating Stream Tests for the Web Client

packages/database/index.node.ts, packages/database/index.ts, packages/database/package.json
The Admin SDK is trying to consume the `@firebase/database` package as a standalone. This fixes some of the typings to better support that.
=> Fixing Typings for RTDB

integration/browserify/package.json, integration/firestore/package.json, integration/messaging/package.json, integration/typescript/package.json, integration/webpack/package.json, package.json, packages/app/package.json, packages/database/package.json, packages/firestore/package.json, packages/messaging/package.json, packages/polyfill/package.json, packages/storage/package.json, packages/util/package.json, yarn.lock
Figured I'd close the previous PR as it had some unnecessary commit noise. This should be a little cleaner.
=> Update Package Dependencies

integration/messaging/package.json
To promote a stable CI env, we are temporarily disabling these tests while @gauntface investigates the root cause of their flakiness.
=> Temporarily disable flakey messaging tests (@gauntface to investigate)

integration/firestore/package.json
Adds a script to the integration/firestore package in the workspace to allow for debugging the int tests.
=> Add a debug script to integration/firestore

integration/firestore/package.json
Due to some flakeyness issues we are disabling these tests until the server environment here, stabilizes.
=> (Temporary) Disable Firestore Int Tests

packages/firestore/test/integration/api/database.test.ts
This test had two problems:
1. After reading the document a second time (as `doc`) it was validating fromCache on the old version (`snapshot`).
2. It wasn't returning the Promise, causing the failure to happen asynchronously and not be noticed by mocha.
This in turn seems to have (sometimes?) caused errors about offline persistence being enabled in a different tab.  I fixed the test and implemented it with more chaining instead of nesting. :-)
=> Fix broken firestore test.

packages/firestore/src/util/async_queue.ts, packages/firestore/test/unit/util/async_queue.test.ts
The bug reported in b/68058918 did not actually exist, but I've added testing for it (1) and made a minor improvement (2).
1. Adds testing to ensure that the original error is preserved and propagated in
the face of multiple failures in the queue (this already worked).
2. Adds an asynchronous exception on queue failures so that they can be caught by
crash reporting libraries (otherwise, only subsequent failures with
"AsyncQueue is already failed: ..." would be caught).
=> b/68058918: Async Queue error handling testing / improvement.

packages/firestore/src/remote/persistent_stream.ts, packages/firestore/test/unit/specs/listen_spec.test.ts, packages/firestore/test/unit/specs/spec_builder.ts, packages/firestore/test/unit/specs/spec_test_runner.ts, packages/firestore/test/unit/specs/write_spec.test.ts, packages/firestore/test/util/equality_matcher.ts
This PR makes sure that we sent an empty write request before the write steam closes. Most of the changes in this PR are geared towards making this testable via the Spec tests (which includes adding support for enable/disableNetwork and request counting).
=> Sending an empty write request before tearing down the WriteStream.

packages/firestore/test/integration/api/batch_writes.test.ts, packages/firestore/test/integration/api/cursor.test.ts, packages/firestore/test/integration/api/database.test.ts, packages/firestore/test/integration/api/fields.test.ts, packages/firestore/test/integration/api/query.test.ts, packages/firestore/test/integration/api/server_timestamp.test.ts, packages/firestore/test/integration/api/smoke.test.ts, packages/firestore/test/integration/api/transactions.test.ts, packages/firestore/test/integration/api/type.test.ts, packages/firestore/test/integration/api/validation.test.ts, packages/firestore/test/integration/browser/indexeddb.test.ts, packages/firestore/test/integration/remote/remote.test.ts, packages/firestore/test/integration/remote/stream.test.ts, packages/firestore/test/unit/local/eager_garbage_collector.test.ts, packages/firestore/test/unit/local/encoded_resource_path.test.ts, packages/firestore/test/unit/local/local_store.test.ts, packages/firestore/test/unit/local/mutation_queue.test.ts, packages/firestore/test/unit/local/query_cache.test.ts, packages/firestore/test/unit/local/reference_set.test.ts, packages/firestore/test/unit/local/remote_document_cache.test.ts, packages/firestore/test/unit/local/remote_document_change_buffer.test.ts, packages/firestore/test/unit/local/simple_db.test.ts, packages/firestore/test/unit/specs/describe_spec.ts, packages/firestore/test/util/helpers.ts
A few tests got re-indented by the code formatter. You can just look at the first commit to exclude those if you want.
=> Remove no-longer-necessary asyncIt wrappers.

packages/webchannel-wrapper/package.json, yarn.lock
Josh, this should fix https://github.com/firebase/firebase-js-sdk/issues/183. Thoughts about including it in this week's release?
Also, I don't really understand why extra stuff in yarn.lock changed. Let me know if you think it's problematic.
=> Upgrade closure-builder to fix #183.

packages/firestore/test/unit/specs/spec_test_runner.ts
Fixes #309
Previously, the type SpecWatchFilter in spec_test_runner was specified as a tuple, but it was later used with `push` and is actually an array with a first element that is guaranteed to be present, and of type TargetId[].
In Typescript 2.7, tuples will be fixed-length and this usage will fail.  This changes the definition of SpecWatchFilter to an interface that extends Array<TargetId[] | string> and whose required '0' property is a TargetId[].
=> Firestore: in tests, fix SpecWatchFilter type to work on upcoming Typescript 2.7

packages/firestore/CHANGELOG.md, packages/firestore/src/platform_browser/webchannel_connection.ts
I verified that our Authorization header is sent via the the '$httpHeaders' URL parameter now, the OPTIONS network round-trip no longer occurs, and our authentication token is still correctly respected by the backend.
=> b/68251551: Send headers via URL Param to avoid CORS preflight round-trip.

packages/webchannel-wrapper/tools/build.js
=> extended build config webchannel-wrapper to support web worker 

packages/firestore/src/remote/remote_store.ts
Firestore log offline warning
To avoid surprise by adding a warning. Right now, when offline, empty result is returned with no log nor error, see https://groups.google.com/forum/#!topic/google-cloud-firestore-discuss/puFl9HVU57I/discussion
Tests pass. No new test required.
API review approved by all platform owners.
=> Firestore log offline warning

packages/firestore/CHANGELOG.md, packages/firestore/src/core/firestore_client.ts, packages/firestore/src/core/sync_engine.ts, packages/firestore/src/core/types.ts, packages/firestore/src/core/view.ts, packages/firestore/src/remote/remote_store.ts, packages/firestore/test/integration/api/query.test.ts, packages/firestore/test/unit/specs/listen_spec.test.ts, packages/firestore/test/unit/specs/offline_spec.test.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
* Plumbs OnlineState changes through to views.
* View sets this.current to false on OnlineState.Failed, triggering
isFromCache=true events. this.current will automatically be returned to true
once the listen is reestablished and we get a new CURRENT message.
* Updated tests (and added new ones) to verify behavior.
=> b/68276665: Raise isFromCache=true events when offline

packages/firestore/src/remote/remote_store.ts
Make offline warning an `error` instead of `debug`. JS client SDK does not have `warning`. To make warning default behavior, we actually want `error` here instead of `debug`.
=> Make offline warning an `error` instead of `debug`.

packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/platform_node/grpc_connection.ts, packages/util/test/base64.test.ts
While log.debug() statements take a tag parameter, log.error()
statements do not. (Note that they still work even with a tag parameter
since log.error() takes in a va_list.)
=> Remove 'tags' from log.error() statements.

packages/firestore/CHANGELOG.md, packages/firestore/src/remote/remote_store.ts
Cherry-pick https://github.com/firebase/firebase-js-sdk/commit/2fa51d3b45705e9f27f500ab4def078905cbed4e (as the original change https://github.com/firebase/firebase-js-sdk/commit/72536c468d2375794a3b18c20fd032d6f0adf178 is already in master) and update changelog based on the two log messages we've added.
=> Add changelog entry for new warning log messages.

packages/firestore/src/core/event_manager.ts, packages/firestore/src/core/firestore_client.ts, packages/firestore/test/unit/core/event_manager.test.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
FYI- I've gone with applyOnlineStateChange on iOS / Web (to be consistent with applyRemoteEvent, etc.) but handleOnlineStateChange on Android (to be consistent with handleListenEvent, etc.).  I'm not sure why the platforms diverged in naming but I don't want to try to clean it up in this PR.
=> Rename EventManager.onOnlineStateChanged => applyOnlineStateChange

packages/app-types/package.json
Fixes an issue introduced with the type refactor (i.e. #334)
=> Ensure app-types package includes private.d.ts

packages/app-types/index.d.ts, packages/app-types/private.d.ts, packages/app/test/firebaseApp.test.ts, packages/auth/src/storage/indexeddb.js, packages/auth/test/autheventmanager_test.js, packages/database/src/core/RepoManager.ts
I noticed that the word "initialize" is misspelled in multiple places across the product and documentation, and wanted to fix that.
=> Replace all instances of 'intialize' with 'initialize'.

packages/firebase/externs/firebase-app-externs.js, packages/firebase/externs/firebase-app-internal-externs.js, packages/firebase/externs/firebase-auth-externs.js, packages/firebase/externs/firebase-client-auth-externs.js, packages/firebase/externs/firebase-database-externs.js, packages/firebase/externs/firebase-database-internal-externs.js, packages/firebase/externs/firebase-error-externs.js, packages/firebase/externs/firebase-externs.js, packages/firebase/externs/firebase-messaging-externs.js, packages/firebase/externs/firebase-storage-externs.js
Adding some `@license` annotations to ensure the externs are properly handled by Closure Compiler.
=> Add @license annotation to externs

packages/firebase/index.d.ts
This module declaration solved some issues for some google users. Should be benign to end-users.
=> Add a "declare module" statement to index.d.ts

packages/firestore/test/integration/api/batch_writes.test.ts, packages/firestore/test/integration/api/database.test.ts
This should fix my Travis run: https://travis-ci.org/firebase/firebase-js-sdk/builds/327950507?utm_source=github_status&utm_medium=notification
Note that is seems that the backend still returns the old error message from time to time.
=> Accepting new backend error message for missing docs

packages/firestore/src/local/persistence_promise.ts, packages/firestore/src/util/promise.ts, packages/firestore/test/integration/api/batch_writes.test.ts, packages/firestore/test/integration/api/database.test.ts, packages/firestore/test/unit/local/persistence_promise.test.ts
This PR:
- Disables lint warnings for the type of the next Promise in the Promise chain
- Restricts the error-type to adhere to `Error`
=> Removing some of the 'any' usage in our Promise implementation

packages/firestore/src/local/indexeddb_schema.ts, packages/firestore/src/remote/serializer.ts, packages/firestore/src/util/sorted_map.ts, packages/firestore/test/integration/bootstrap.ts, packages/firestore/test/unit/bootstrap.ts
This silences the remaining uses of `any` (and fixes a lint error I just introduced!)
- In serializer, we are deliberately using the wrong type, but unless we fix the generated typings, this is here to stay.
- We could fix the `any` use in both bootstrap.js files, but this would require a type dependency on `webpack-env`. To me, adding a new dependency just to address this warning isn't quite justified, especially since this affects only the setup code for our tests.
=> Removing last lint errors

integration/firestore/gulpfile.js, packages/firestore/src/api/database.ts, packages/firestore/test/integration/api/README.md, packages/firestore/test/integration/api/batch_writes.test.ts, packages/firestore/test/integration/api/cursor.test.ts, packages/firestore/test/integration/api/database.test.ts, packages/firestore/test/integration/api/fields.test.ts, packages/firestore/test/integration/api/query.test.ts, packages/firestore/test/integration/api/server_timestamp.test.ts, packages/firestore/test/integration/api/smoke.test.ts, packages/firestore/test/integration/api/transactions.test.ts, packages/firestore/test/integration/api/type.test.ts, packages/firestore/test/integration/api_internal/idle_timeout.test.ts, packages/firestore/test/integration/api_internal/idle_timeout.ts, packages/firestore/test/integration/browser/webchannel.test.ts, packages/firestore/test/integration/remote/remote.test.ts, packages/firestore/test/integration/remote/stream.test.ts, packages/firestore/test/integration/util/events_accumulator.ts, packages/firestore/test/integration/util/helpers.ts, packages/firestore/test/integration/util/internal_helpers.ts, packages/firestore/test/util/helpers.ts, packages/firestore/test/util/promise.ts
This lets us run these tests (via firebase-js-sdk/integration/firestore/)
against the minified build without risk of accidentally mixing in non-minified
classes (leading to tests misbehaving or skipping testing the minified code
that we were intending to test).
Fixes b/71721842 and b/66946692.
Changes include:
* Split integration/api into api/ and api_internal/
* Move Idle Timeout tests (that drain the async queue) to api_internal/ and
remove semi-public db.INTERNAL.drainAsyncQueue() method.
* Remove src/ dependencies from integration/api tests:
* Split integration/util/helpers.ts into helpers.ts (with no src/
dependencies) and internal_helpers.ts (with src/ dependencies).
* Create test/util/promise.ts with Deferred<> implementation to avoid depending
on src/util/promise.ts.
* Move …
=> Refactor integration/api/ tests to have no src/ dependencies.

packages/database/src/core/util/libs/parser.ts, packages/database/src/core/util/validation.ts, packages/database/test/database.test.ts
This change was discussed in #116.
=> Allow localhost database URL

packages/database/src/core/util/libs/parser.ts, packages/database/test/database.test.ts
The builds on top of: https://github.com/firebase/firebase-js-sdk/pull/426 (@rynobax)
#426 added support for `localhost:<port>`, and this PR allows `localhost` without the `<port>`.
=> Allowing localhost URL with port

packages/util/index.ts
Closure compiler does not support ES6 Wildcard export.
By declaring each and every export, can Closure Compiler do its magic.
See: #369 For more details
=> fix: Closure Compiler ES6 Wildcard import not supported

packages/firestore/src/core/view.ts, packages/firestore/test/unit/specs/offline_spec.test.ts
Context: I made a previous change to raise isFromCache=true events when the client goes offline. As part of this change I added an assert for "OnlineState should not affect limbo documents", which it turns out was not valid because:
* When we go offline, we set the view to non-current and call View.applyChanges().
* View.applyChanges() calls applyTargetChange() even though there's no target change and it recalculates limbo documents.
* When the view is not current, we consider no documents to be in limbo.
* Therefore all limbo documents are removed and so applyChanges() ends up returning unexpected LimboDocumentChanges.
Fix: I've modified the View logic so that we don't recalculate limbo documents (and generate LimboDocumentChanges) when the View is not current, so now my assert holds and …
=> Fix b/72502745: OnlineState changes cause limbo document crash.

packages/auth/src/cordovahandler.js, packages/auth/src/universallinksubscriber.js, packages/auth/test/autheventmanager_test.js, packages/auth/test/cordovahandler_test.js, packages/auth/test/universallinksubscriber_test.js
Fixes broken universallinks.subscribe in Android when multiple listeners are set.
=> fix(auth): Cordova OAuth fix for Android with multiple App instances

packages/firestore/src/model/document_set.ts, packages/firestore/src/util/sorted_map.ts, packages/firestore/test/unit/model/document_set.test.ts, packages/firestore/test/unit/util/sorted_map.test.ts
This is dead code.
I think it was probably useful in the RTDB because of the way it
notified of changes, but we give changes with indexes in Firestore so I
think we don't need it.
This parallels https://github.com/firebase/firebase-ios-sdk/pull/735
=> Remove SortedMap.getPredecessorKey

.yarnrc, scripts/release/cli.js, scripts/release/utils/git.js
Fixes some issues/deficiencies in the release CLI
1. Fixes an issue where `--follow-tags` wasn't functioning as expected
1. Added some flags to skip various parts of the build process
=> Release CLI Fixes

packages/firestore/src/remote/persistent_stream.ts, packages/firestore/src/util/async_queue.ts, packages/firestore/src/util/promise.ts
* Introduces a DelayedOperation helper class in AsyncQueue to encapsulate
delayed op logic.
* Adds cancellation support which I want to use in
https://github.com/firebase/firebase-js-sdk/pull/412
* Remove delayedOperationsCount in favor of keeping delayedOperations populated
correctly at all times.
* Fixes a preexisting issue in AsyncQueue.schedule() where the returned promise
would always be resolved with undefined, instead of the result of your op.
Also remove an AnyDuringMigration usage.
=> Refactor AsyncQueue's "delayed scheduling" support and add cancellation.

packages/firestore/package.json, packages/firestore/src/api/credentials.ts, packages/firestore/src/api/database.ts, packages/firestore/src/api/user_data_converter.ts, packages/firestore/src/core/event_manager.ts, packages/firestore/src/core/firestore_client.ts, packages/firestore/src/local/indexeddb_mutation_queue.ts, packages/firestore/src/local/indexeddb_query_cache.ts, packages/firestore/src/local/memory_query_cache.ts, packages/firestore/src/local/memory_remote_document_cache.ts, packages/firestore/src/local/reference_set.ts, packages/firestore/src/model/document_set.ts, packages/firestore/src/model/field_value.ts, packages/firestore/src/platform/config.ts, packages/firestore/src/platform_node/grpc_connection.ts, packages/firestore/src/remote/datastore.ts, packages/firestore/src/remote/persistent_stream.ts, packages/firestore/src/remote/remote_store.ts, packages/firestore/src/remote/stream_bridge.ts, packages/firestore/src/util/async_queue.ts, packages/firestore/src/util/sorted_map.ts, packages/firestore/test/integration/api/type.test.ts, packages/firestore/test/integration/util/internal_helpers.ts, packages/firestore/test/unit/model/mutation.test.ts, packages/firestore/test/unit/specs/spec_test_runner.ts, packages/firestore/test/util/equality_matcher.ts, packages/firestore/test/util/helpers.ts, packages/firestore/tslint.json
This PR adds type checking to tslint and enables "no-unused-vars".
I also added a new auto-fix option to the default scripts (`yarn lint:fix`), which is responsible for some of the changes in here.
Tests are all passing locally for me and `yarn prepare` works in the repo root as well as in packages/firestore
=> Adding no-unused-vars to TSLint

packages/firestore/src/core/firestore_client.ts, packages/firestore/src/remote/backoff.ts, packages/firestore/src/remote/datastore.ts, packages/firestore/src/remote/persistent_stream.ts, packages/firestore/src/util/async_queue.ts, packages/firestore/test/integration/api_internal/idle_timeout.test.ts, packages/firestore/test/integration/remote/stream.test.ts, packages/firestore/test/integration/util/internal_helpers.ts, packages/firestore/test/unit/specs/spec_test_runner.ts, packages/firestore/test/unit/util/async_queue.test.ts
Core changes:
* Moves ExponentialBackoff to the AsyncQueue (matches iOS / Android).
* Adds a TimerId enum for identifying delayed operations on the queue and uses it to identify our existing backoff and idle timers.
* Added AsyncQueue.hasDelayedOperation(id) and .runDelayedOperationsEarly(id) which can be used from tests to check for the presence of an operation and to schedule them to run early.
* Idle tests now use these mechanisms.
* Spec tests now use this rather than setting initalBackoffDelay to 1ms.
* Reworked mechanism by which DelayedOperation objects get removed from AsyncQueue's delayedOperations list to make sure it happens synchronously.
Cleanup:
* Renamed schedule() to enqueue() and scheduleWithDelay() to enqueueAfterDelay().
* Reorders AsyncQueue.enqueueAfterDelay() …
=> Improve usage and testing of delayed operations.

packages/database/src/core/RepoInfo.ts, packages/database/src/core/util/libs/parser.ts, packages/database/test/database.test.ts
This PR adds support for the `?ns=` query param. This will be used for testing against non-production endpoints.
=> Support ns queryparam

packages/database/src/core/util/libs/parser.ts
=> Fix query string parsing

packages/database/index.node.ts
Refactor the `initStandalone` function to optionally patch the firebase version.
Also sets the `NODE_ADMIN` constant to `true`
=> Version Patch for Firebase Admin

packages/messaging/src/models/clean-v1-undefined.ts, packages/messaging/src/models/db-interface.ts, packages/messaging/src/models/token-details-model.ts, packages/messaging/src/models/vapid-details-model.ts, packages/messaging/test/controller-delete-token.test.ts, packages/messaging/test/tokenDetailsModel-deleteToken.test.ts, packages/messaging/test/tokenDetailsModel-getToken.test.ts, packages/messaging/test/tokenDetailsModel-saveToken.test.ts, packages/messaging/test/vapid-details-model-delete.test.ts, packages/messaging/test/vapid-details-model-get.test.ts, packages/messaging/test/vapid-details-model-save.test.ts
A few bugs have been highlighted from 4.9x => 4.10.0:
- There was a bug in <= 4.9.X builds of the messaging SDK that meant the SDK was using an IDB name of 'undefined'. My hunch is something went wonky in closure -> typescript.
- If the name wasn't `undefined` the changes in 4.10 should have been fine, but because there is now a difference IDB name, the SDK is creating a new token, meaning end users can get two notifications - one for the old token and one for the new token.
This PR will bump the version of the IDB database in the next release, and clean up any old IDB instances if they exist in the version upgrade step.
=> Messaging - IDB Cleanup

packages/messaging-types/index.d.ts
@pinarx pointed out that the types file was out of sync with the API surface.
@jshcrowthe we can do away with the types files if we get the "typescript-y-ness" of the source inline and up-to-date right, or is there something I'm missing? I.e. move away from closure and opt for typescript typing
=> Updating API surface

scripts/release/utils/npm.js
As part of publishing scoped packages, we have to pass set the default access of our scoped packages. If we don't do this, the `npm publish` command will fail to publish new packages.
=> NPM Publish Access

packages/logger/package.json
This will ensure the `@firebase/logger` package is picked up for the next release.
=> Remove the "private" flag from the @firebase/logger package

packages/database-types/index.d.ts, packages/database/src/api/Database.ts, packages/database/test/database.test.ts
This implements go/firebase-ref-from-ref:
// Before:
// The developer must know of the little-used refFromUrl and must also know that a 
// ref's toString is the full URL of the ref
let ref2 = admin.database().refFromURL(ref1.toString());
// After:
// more intuitive
let ref2 = admin.database().ref(ref1);
=> Database API: Ref from Ref

packages/messaging/package.json
tentatively fixes #546 
I'm not sure that making grpc an optional dependency is the best way to fix this, but I figured I'd create this PR as a starting point.
=> Remove unnecessary lcov-result-merger dep from @firebase/messaging

scripts/release/utils/banner.js, scripts/release/utils/inquirer.js
There were some issues w/ the release process that needed to be addressed. Specifically:
- The banner text was displayed incorrectly
- The release CLI wasn't able to publish new packages properly
=> Release Fixes

packages/firestore/src/platform_browser/webchannel_connection.ts
I verified that the client still works against prod and that the ?database=... paremeter was included in every WebChannel network request.
NOTE that prior to this change we were including the "google-cloud-resource-prefix" header on non-streaming RPC requests, but with this change we will not include the header or use the "database" url parameter.
See b/72663769 for more info.
=> Remove "google-cloud-resource-prefix" header in favor of "database" url parameter in WebChannel requests.

packages/firebase/index.d.ts
Pulls [firebase/index.d.ts](https://github.com/firebase/firebase-js-sdk/blob/master/packages/firebase/index.d.ts#L464) into alignment with [@firebase/messaging-types/index.d.ts](https://github.com/firebase/firebase-js-sdk/blob/master/packages/messaging-types/index.d.ts#L37) by adding `usePublicVapidKey` definition.
=> Fixes #562, Adds usePublicVapidKey to firebase/index.d.ts

packages/firestore/CHANGELOG.md, packages/firestore/src/remote/persistent_stream.ts
Sorry, I meant to remove this assert when responding to your CR feedback yesterday, but apparently failed.
=> Remove assert I accidentally left in (I meant to remove it when I re-added the defensive check above).

packages/firebase/index.d.ts
Related to issue #573.
Added the TypeScript definition for the `createUserAndRetrieveDataWithEmailAndPassword` function in Auth interface.
=> Add missing function in Auth interface

packages/auth/demo/public/script.js, packages/auth/demo/public/web-worker.js, packages/auth/package.json, packages/auth/src/rpchandler.js, packages/auth/src/utils.js, packages/auth/test/rpchandler_test.js, packages/auth/test/utils_test.js, yarn.lock
Fixes vague errors thrown in older browsers such as IE10/11 and iOS mobile Safari related to worker support.
Most of these are attributed to lack of support for fetch related APIs even when web workers are still supported.
In that case we throw an operation not supported in environment error on operations that require http requests.
Also adds missing dependency on firebase-functions required for demo app.
=> Fetch API missing support handling

packages/firebase/index.d.ts, packages/messaging/src/controllers/controller-interface.ts
cc @gauntface
Should be a no-op in terms of functionality:
1) Use async/await in the ControllerInterface.
2) Merge the retrieval of pushSubscription and publicVapidKey, so we don't call getPushSubscription and getPublicVapidKey multiple times in the flow.
=> Unify pushSubscription/publicVapidKey retrievals

packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/memory_persistence.ts, packages/firestore/src/local/persistence.ts, packages/firestore/test/unit/specs/persistence_spec.test.ts, packages/firestore/test/unit/specs/spec_builder.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
This will be used by SharedClientState to retrieve the list of active clients during its startup. Using this list, the SharedClientState can then read all relevant rows in LocalStorage.
=>  Adding getActiveClients()

packages/firestore/CHANGELOG.md, packages/firestore/src/remote/online_state_tracker.ts, packages/firestore/test/unit/specs/offline_spec.test.ts
OnlineStateTracker was reverting to OnlineState Unknown on every stream attempt
rather than remaining Offline once the offline heuristic had been met (i.e. 2
stream failures or 10 seconds). This means that get() requests made while
offline could be delayed up to 10 seconds each time (or until the next backoff
attempt failed).
=> Fix issue that could cause offline get()s to wait up to 10 seconds.

packages/webchannel-wrapper/package.json, yarn.lock
This updates the `closure-builder` dependency in the `@firebase/webchannel-wrapper` package. This should help to address some of the perf issues we've been seeing.
=> Updates the @firebase/webchannel-wrapper Version

packages/firestore/src/local/shared_client_delegate.ts, packages/firestore/src/local/shared_client_state.ts, packages/firestore/src/local/shared_client_state_syncer.ts, packages/firestore/src/remote/remote_syncer.ts, packages/firestore/src/util/misc.ts, packages/firestore/test/unit/local/persistence_test_helpers.ts, packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
This PR allows pending mutation batches to be persisted in LocalStorage. In order to keep things focussed, this only adds the serialization and deserialization in SharedClientState. The next PR will add the calls from LocalStorage that invoke SharedClientState, and in a further follow up I will add the wiring between SyncEngine and SharedClientState.
This PR also paves the way for SyncEngine to gain two pieces of functionality:
- Apply pending batches by Batch ID to all Local Views 
- Apply successful mutations by Batch ID
Note: The changes in `fromLocalStorageEntry` are formatting only  as I wrapped the logic in a `if (value !== null)` block.
=> Persisting mutation batch state in LocalStorage

packages/firebase/app/index.d.ts, packages/messaging/src/controllers/controller-interface.ts, packages/messaging/test/controller-get-token.test.ts
Check if pushSubscription details have changed before returning an existing token.
This should enable us to deal with permission changes where new push subscriptions are generated but we're returning old token: https://stackoverflow.com/questions/49393052/chrome-firebase-cloud-message-notregistered
cc: @gauntface
=> PushSubscription validation

packages/messaging/src/models/errors.ts
Fixes #114
If a developer calls userServiceWorker() twice an error is thrown but the message isn't obvious as to what the cause it. This makes it a little easier to reason with.
=> Tweaks message for useServiceWorker error

packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/indexeddb_schema.ts, packages/firestore/src/local/memory_persistence.ts, packages/firestore/src/local/persistence.ts, packages/firestore/src/local/shared_client_state.ts, packages/firestore/src/local/shared_client_state_syncer.ts, packages/firestore/test/unit/local/persistence_test_helpers.ts, packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
This renames ClientKey to ClientId.
```
mrschmidt@mrschmidt-macbookpro3 src (multitab-clientidrename) $ grep -r -i "clientkey" .
mrschmidt@mrschmidt-macbookpro3 src (multitab-clientidrename) $ 
```
=>  Renaming ClientKey to ClientId

packages/firebase/index.d.ts
Removes the following unneeded block:
```typescript
declare module `firebase` {}
```
This file is referenced from the package.json and is automatically assigned to the `firebase` name.
Fixes #474
=> Fix Issue 474

packages/firestore/src/api/field_value.ts, packages/firestore/src/api/user_data_converter.ts, packages/firestore/test/integration/api/validation.test.ts
This technically includes a small breaking change. Before we would allow you to do:
`doc.set({a: [0, FieldValue.delete(), 2] }, {merge: true})`
Which ended up equivalent to:
`doc.set({a: [0, null, 2] }, {merge: true})`
But with my change it will now result in an error:
`FieldValue.delete() is not currently supported inside arrays.`
Let me know if you think that's an issue. I can rework it but I don't think the existing behavior was particularly useful or intentional.
=> Small cleanup to FieldValue sentinel code to make it easier to add more sentinels in the future.

packages/firestore/src/core/firestore_client.ts, packages/firestore/src/core/sync_engine.ts, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/memory_persistence.ts, packages/firestore/src/local/shared_client_state.ts, packages/firestore/src/local/shared_client_state_syncer.ts, packages/firestore/test/unit/local/local_store.test.ts, packages/firestore/test/unit/local/persistence_test_helpers.ts, packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
This PR adds the SharedClientState to FirestoreClient and plumbs it through to LocalStore (where it is currently only used to add new mutation batches to WebStorage). (Spec-)Tests for this will come in the next PR when I start reading these mutations back.
There are two changes in here to make sure the existing tests still work:
- The first part of `handleUserChange` is implemented in the memory-only SharedClientState implementation. This is needed since the Memory Persistence re-uses mutation batch IDs after a user change, which `LocalClientState` doesn't handle.
- IndexedDbPersistence cancels the client metadata refresh, since the LocalStore tests re-use the AysncQueue and fail when multiple clients metadata refreshes are active at the same time.
=>  Plumbing through SharedStorageState

packages/firebase/app/index.d.ts, packages/storage-types/index.d.ts
Removing 'any' from some of the Storage APIs. I copied this from the Storage externs definition in Google3.
=> Fixing Storage Types

packages/firestore/test/integration/api/validation.test.ts, packages/polyfill/src/polyfills/promise.ts
This add mocha-like .skip and .only functions to validationIt. I am not sure if this can be done without the 'any' keyword, as validationIt is now both a function and an object.
As always, this also contains unrelated prettier changes :)
=> Adding .skip and .only for validation tests

packages/messaging/src/controllers/controller-interface.ts, packages/polyfill/src/polyfills/promise.ts
Basically when the permissions are revoked and restored, do not unsubscribe from the PushSubscription, as we're using a brand new one.
Just remove the token from DB and from FCM server DB.
=>  Fix a bug that was introduced in PR: #591

integration/messaging/test/static/app.js, packages/messaging/index.ts, packages/messaging/package.json, packages/messaging/src/controllers/controller-interface.ts, packages/messaging/src/controllers/sw-controller.ts, packages/messaging/src/controllers/window-controller.ts, packages/messaging/src/models/db-interface.ts, packages/messaging/src/models/default-sw.ts, packages/messaging/src/models/errors.ts, packages/messaging/src/models/fcm-details.ts, packages/messaging/src/models/iid-model.ts, packages/messaging/src/models/notification-permission.ts, packages/messaging/src/models/token-details-model.ts, packages/messaging/src/models/vapid-details-model.ts, packages/messaging/src/models/worker-page-message.ts, packages/messaging/test/controller-delete-token.test.ts, packages/messaging/test/tokenDetailsModel-deleteToken.test.ts, packages/messaging/test/tokenDetailsModel-getToken.test.ts, packages/messaging/test/tokenDetailsModel-saveToken.test.ts, packages/messaging/tsconfig.json
This doesn't really "fix" anything, but explicit "any"s are still better than implicit "any"s. I'll fix the types properly after this.
Adds TypeScript compilation as part of tests, which means tests & CI will now fail if you don't make the compiler happy.
I also removed "use strict"s, which are emitted automatically by --alwaysStrict, which is part of --strict.
FYI: --noImplicitAny, which is part of --strict, is still off. This is because it's set to false explicitly in the base TSConfig. I'm working on fixing the types so I can enable that as well.
=> Add --strict flag to TSConfig and fix errors

packages/app-types/index.d.ts, packages/app/src/firebaseApp.ts, packages/app/test/firebaseApp.test.ts
This PR changes `initializeApp` to support an options object as the second argument. It propagates the `name` and `automaticDataCollectionEnabled` flags to the `FirebaseAppImpl`.
=> automaticDataCollectionEnabled Flag

packages/storage-types/index.d.ts
Fix for Storage types described in #620.
=> Specify types of observer and next function for UploadTask.on

packages/database-types/index.d.ts, packages/firebase/app/index.d.ts
Reverts firebase/firebase-js-sdk#613
Since our next major release is around the corner, reverting this change from master.
=> Revert "Removing .path from Database Typings"

packages/database-types/index.d.ts, packages/firebase/app/index.d.ts
This is the "Removing .path from Database Typings" PR (https://github.com/firebase/firebase-js-sdk/pull/613) against the v5-master branch.
=> v5 Change: Removing .path from Database Typings

packages/firebase/app/index.d.ts, packages/firebase/index.d.ts, packages/storage-types/index.d.ts
In the future, Storage backend changes will make it infeasible to automatically provide these properties. These properties will eventually be removed, but it will still be possible to generate download URLs with the Reference.getDownloadURL method.
The `@deprecated` property will show up in TSLint. I'll also update our [documentation](https://firebase.google.com/docs/) before the next release.
=> Deprecate downloadURL property in Storage metadata types.

.travis.yml
Install stage was mistakenly set to be skipped by PR #674.
This is to fix build failure: https://travis-ci.org/firebase/firebase-js-sdk/builds/365852699.
=> Fix deployment procedures.

packages/auth-types/index.d.ts, packages/auth/demo/public/index.html, packages/auth/demo/public/script.js, packages/auth/src/authuser.js, packages/auth/src/exports_auth.js, packages/auth/src/idtoken.js, packages/auth/src/idtokenresult.js, packages/auth/test/authuser_test.js, packages/auth/test/idtoken_test.js, packages/auth/test/idtokenresult_test.js, packages/auth/test/testhelper.js, packages/firebase/index.d.ts, packages/firestore/src/api/user_data_converter.ts
=> expose custom claims

.travis.yml
Most of our builds are pull request builds or feature branch builds, which are not for the purpose of release. Skipping the deployment stage in build process shorten these builds by a few minutes.
=> Skip deployment for non-release build.

packages/firestore/rollup.config.js
With the build refactor the vast majority of imports worked seamlessly. However Firestore's import of the `util` lib here (which translates to a `require('util')` was not properly externally referenced resulting in errors.
This correctly marks the lib as external for the Node.js build.
=> Firestore Node.js External Fix

packages/app/package.json, packages/auth/package.json, packages/database/package.json, packages/firestore/package.json, packages/functions/package.json, packages/logger/package.json, packages/messaging/package.json, packages/polyfill/package.json, packages/storage/package.json, packages/template/package.json, packages/testing/package.json, packages/util/package.json, packages/webchannel-wrapper/package.json
We are accidentally including some of the coverage and cache directories in our NPM builds.
This scopes it to only the built artifacts in the `dist` directory of each component.
_NOTE: I removed some of the entries from `auth/package.json` because they are included by default (per https://docs.npmjs.com/files/package.json#files)_
=> Add pkg.files entry to each package.json

packages/firestore/src/core/sync_engine.ts, packages/firestore/test/unit/specs/write_spec.test.ts
This PR adds the missing elements to reject mutations for multi-client writes.
=> Adding multi-client support for rejected mutations

packages/messaging/src/controllers/sw-controller.ts, packages/messaging/test/sw-controller.test.ts
According to https://firebase.google.com/docs/cloud-messaging/js/receive, a message should always be sent to the window client if it is in focus.
This change removes the checks that prevent the message from being sent if it is a data message and if bgMessageHandler isn't set.
Fixes #381.
=> Fix data message not being handled on foreground when backgroundMessageHandler isn't set

packages/firestore/test/util/equality_matcher.ts
BEFORE:
```
AssertionError: expected null to roughly deeply equal undefined
```
AFTER:
```
AssertionError: expected { Object (elements) } to roughly deeply equal { Object (elements) }
+ expected - actual
{
"elements": [
{
-      "internalValue": "foo"
+      "internalValue": "tag"
"typeOrder": 4
}
]
}
```
=> Use correct assert() method so we get good error messages.

packages/firestore/.idea/runConfigurations/All_Tests.xml, packages/firestore/.idea/runConfigurations/All_Tests__w__Mock_Persistence_.xml, packages/firestore/.idea/runConfigurations/Integration_Tests.xml, packages/firestore/.idea/runConfigurations/Integration_Tests__w__Mock_Persistence_.xml, packages/firestore/.idea/runConfigurations/Unit_Tests.xml, packages/firestore/.idea/runConfigurations/Unit_Tests__w__Mock_Persistence_.xml, packages/firestore/.npmignore, packages/firestore/package.json, packages/firestore/src/api/database.ts, packages/firestore/src/core/firestore_client.ts, packages/firestore/src/local/indexeddb_mutation_queue.ts, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/local_serializer.ts, packages/firestore/src/local/memory_persistence.ts, packages/firestore/src/local/persistence.ts, packages/firestore/src/local/simple_db.ts, packages/firestore/test/integration/browser/webchannel.test.ts, packages/firestore/test/integration/util/helpers.ts, packages/firestore/test/unit/local/encoded_resource_path.test.ts, packages/firestore/test/unit/local/indexeddb_schema.test.ts, packages/firestore/test/unit/local/local_store.test.ts, packages/firestore/test/unit/local/mutation_queue.test.ts, packages/firestore/test/unit/local/query_cache.test.ts, packages/firestore/test/unit/local/remote_document_cache.test.ts, packages/firestore/test/unit/local/remote_document_change_buffer.test.ts, packages/firestore/test/unit/local/simple_db.test.ts, packages/firestore/test/unit/specs/spec_test_runner.ts, packages/firestore/test/util/mock_persistence.ts, yarn.lock
This likely falls in the category of "hack" but it is going to make my life much more pleasant.
This PR allows running the Persistence-based tests on Node using https://github.com/axemclion/IndexedDBShim. There are some glitches that I worked around (like lingering files) but overall, I am very pleased to report that I can now debug tests using IntelliJ.
I also included default test configurations for IntelliJ users.
Note that while I am able to run the tests via IntelliJ, `test:node:persistence` still has some occasional failures that I punted on for now (about 3-10 tests fail for with persistence related errors, and 1 fails because XMLHTTPRequest can't be resolved).
=> Using an IndexedDB mock for Node testing

.vscode/launch.json, packages/firestore/.gitignore, packages/firestore/package.json, packages/firestore/test/util/mock_persistence.ts, yarn.lock
* Add SQLite files to .gitignore so they don't pollute 'git status' or
accidentally get committed.
* Use node-cleanup instead of process.on('exit') since it catches ctrl-C.
Unfortunately it can't catch a pure SIGKILL.
=> Add VS Code launcher for persistence tests and minor cleanup.

.vscode/launch.json, packages/firestore/.idea/runConfigurations/All_Tests.xml, packages/firestore/.idea/runConfigurations/All_Tests__w__Mock_Persistence_.xml, packages/firestore/.idea/runConfigurations/Integration_Tests.xml, packages/firestore/.idea/runConfigurations/Integration_Tests__w__Mock_Persistence_.xml, packages/firestore/.idea/runConfigurations/Unit_Tests.xml, packages/firestore/.idea/runConfigurations/Unit_Tests__w__Mock_Persistence_.xml, packages/firestore/src/core/firestore_client.ts, packages/firestore/src/local/indexeddb_mutation_queue.ts, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/shared_client_state.ts, packages/firestore/src/platform_node/node_platform.ts, packages/firestore/src/remote/remote_store.ts, packages/firestore/test/unit/local/local_store.test.ts, packages/firestore/test/unit/local/persistence_test_helpers.ts, packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts, packages/firestore/test/unit/specs/spec_test_runner.ts, packages/firestore/test/util/node_persistence.ts
So I have created two branches 'multitab-dirty-merge' that has the result of the automatic merge with all merge markers.
This PR is set up against this branch to make it easier to show the manual changes.
The merge was kind of complicated since Multi-Tab also introduces LocalStorage. So now there are tests that use IndexedDb that don't have access to Local Storage (I was debating using a Mock for this as well, but decided that we could clean this up later if deemed necessary).
I also renamed the "mock_persistence" file to "node_persistence" so that bootstrap.ts doesn't pick it up.
=> Manual merge of Persistence Mock

packages/firestore/src/core/sync_engine.ts, packages/firestore/src/remote/remote_event.ts, packages/firestore/test/unit/remote/remote_event.test.ts
I got some good feedback on the java port internally, so I am porting that to typescript.
Filtering is moved onto the mapping subtypes, and some tests are split into distinct cases.
=> Port feedback on event filtering

packages/firestore/package.json, packages/firestore/test/integration/util/helpers.ts
1. We weren't actually calling db.INTERNAL.delete(), leading to lingering webchannel connections in tests.
2. Fixed a missed reference to mock_persistence.ts.
=> Post-indexeddbshim test fixes

packages/firebase/index.d.ts, packages/firestore-types/index.d.ts, packages/firestore/CHANGELOG.md, packages/firestore/src/api/database.ts, packages/firestore/src/api/user_data_converter.ts, packages/firestore/src/model/mutation.ts, packages/firestore/src/util/input_validation.ts, packages/firestore/test/integration/api/database.test.ts, packages/firestore/test/integration/api/validation.test.ts
This PR adds field mask support to `.set(, {..})`. It's mostly a port of the missing features from https://critique.corp.google.com/#review/167190604 (internal)
=> Adding mergeFields support to the Web SDK

packages/messaging/src/controllers/sw-controller.ts, packages/messaging/test/sw-controller.test.ts
This operation was safe when we didn't allow users to define "data" on their notification. Not anymore.
=> Don't overwrite user defined data

packages/messaging/src/models/db-interface.ts
According to [the IndexedDB spec](https://www.w3.org/TR/IndexedDB-2/#database-interface), `db.transaction()` method's `mode` parameter is optional, and the default value is `"readonly"`.
However, MS Edge fails a transaction if mode is undefined, so we need to call it explicitly with `"readonly"`.
Fixes #757.
=> Fix Edge not setting default transaction mode

packages/firestore/CHANGELOG.md
A bunch of the "Unreleased" changes have actually been released, so I broke them out
into the appropriate versions. Also added a changelog entry for the 0.4.1 patch release
to fix Node.JS support.
=> Fix up changelog.

packages/firestore/test/integration/api/cursor.test.ts
"micros" could underflow or overflow if the test was run at the wrong time... So I Reworked the test with hardcoded timestamps (based on if micros was "5") as I don't think making it time-dependent gains us interesting additional coverage.
=> b/78539022: Fix test at risk of range violation errors depending on time-of-day.

packages/firestore/test/unit/specs/offline_spec.test.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
The delays in `Removing all listeners delays "Offline" status on next listen` are due to the listen stream backoffs triggered by closing the stream with Code.UNAVAILABLE.
=> Speed up spec tests with connection backoffs

integration/shared/validator.js, packages/functions/test/browser/callable.test.ts, packages/messaging/index.ts, packages/messaging/src/controllers/window-controller.ts, packages/messaging/test/controller-get-token.test.ts, packages/messaging/test/index.test.ts, packages/messaging/test/window-controller.test.ts
Checks browser support before instantiating messaging service controllers and fixes some tests.
I think it's better to let the developer know that Messaging will not work as soon as possible, instead of instantiating a controller without an issue and then throwing an error as soon as they try to use it.
This also prevents issues such as #658 by making sure we don't call any unsupported methods by accident.
This can break users who were not checking browser support before calling `firebase.messaging()`, so it should go to the v5 branch.
=> Check browser support before instantiating controllers

packages/firestore/src/api/database.ts
This is a workaround for the error thrown trying to override the `length` property of a function.
=> IE11 "Can't redefine non-configurable property 'length'" Error

config/karma.saucelabs.js, packages/messaging/index.ts, packages/messaging/package.json, packages/messaging/test/constructor.test.ts, packages/messaging/test/controller-delete-token.test.ts, packages/messaging/test/controller-get-token.test.ts, packages/messaging/test/controller-interface.test.ts, packages/messaging/test/db-interface.test.ts, packages/messaging/test/get-sw-reg.test.ts, packages/messaging/test/helpers.test.ts, packages/messaging/test/iid-model.test.ts, packages/messaging/test/index.test.ts, packages/messaging/test/sw-controller.test.ts, packages/messaging/test/testing-utils/make-fake-subscription.ts, packages/messaging/test/testing-utils/make-fake-sw-reg.ts, packages/messaging/test/testing-utils/messaging-test-runner.ts, packages/messaging/test/token-details-model.test.ts, packages/messaging/test/vapid-details-model.test.ts, packages/messaging/test/window-controller.test.ts, yarn.lock
Enables tests on all desktop browsers that currently support Push API and Notifications API (Chrome, Edge 17 and Firefox). Skips tests on Safari.
Thanks @yifanyang!
=> Enable Messaging tests on Sauce Labs

packages/firebase/index.d.ts, packages/firestore-types/index.d.ts, packages/firestore/src/api/field_value.ts, packages/firestore/src/api/user_data_converter.ts, packages/firestore/src/model/mutation.ts, packages/firestore/src/model/transform_operation.ts, packages/firestore/src/remote/serializer.ts, packages/firestore/src/util/array.ts, packages/firestore/test/integration/api/array_transforms.test.ts, packages/firestore/test/integration/api/server_timestamp.test.ts, packages/firestore/test/integration/api/validation.test.ts, packages/firestore/test/integration/util/events_accumulator.ts, packages/firestore/test/integration/util/helpers.ts, packages/firestore/test/unit/model/mutation.test.ts, packages/firestore/test/unit/remote/node/serializer.test.ts, packages/firestore/test/util/helpers.ts
[This review is not super urgent if you're busy this week]
This is a port of The following iOS commits:
https://github.com/firebase/firebase-ios-sdk/commit/60d43d7b0980719beac21811da712f1cb4881308
https://github.com/firebase/firebase-ios-sdk/commit/360e58901c359d7d21da4fff8043894c843427b7
https://github.com/firebase/firebase-ios-sdk/commit/f2ec9e11fba82d4a76d989293d270a37ad1373a2
https://github.com/firebase/firebase-ios-sdk/commit/e36cc9610b11dfd2581ba5e3fda1917e0d5e697a
https://github.com/firebase/firebase-ios-sdk/commit/7dca635039efb00082624552c223ac7f47ea0cad
While I split this PR into separate commits, they don't match 1:1 with the iOS commits (some of the commits iterated on bits from previous ones) so it may be a little difficult to compare. So I'd probably just compare to iOS HEAD …
=> Add arrayUnion() and arrayRemove() Transforms (not publicly exposed yet)

packages/firebase/externs/firebase-auth-externs.js
Fixed wrong return type of signInAnonymously in auth-externs
=> fixed wrong return type in auth-extern

packages/auth-types/index.d.ts, packages/storage-types/index.d.ts
Generic type 'Observer' requires 1 type argument(s). Fix #787
=> Fixed Generic type Observer

packages/app-types/package.json, packages/app-types/tsconfig.json, packages/auth-types/package.json, packages/auth-types/tsconfig.json, packages/database-types/package.json, packages/database-types/tsconfig.json, packages/firestore-types/package.json, packages/firestore-types/tsconfig.json, packages/functions-types/package.json, packages/functions-types/tsconfig.json, packages/messaging-types/package.json, packages/messaging-types/tsconfig.json, packages/storage-types/package.json, packages/storage-types/tsconfig.json, packages/template-types/package.json, packages/template-types/tsconfig.json
Tests are the same as [Messaging's type-check test](https://github.com/firebase/firebase-js-sdk/blob/9c953fa337f4e6e4cbcdf67e32888bea349be377/packages/messaging/package.json#L18).
This should prevent issues like #787.
=> Add tests for *-types packages

packages/messaging/src/controllers/controller-interface.ts
#482 added VAPID keys, and started storing `vapidKey` as part of `TokenDetails` (code [here](https://github.com/firebase/firebase-js-sdk/blob/7a611b645fbedcd6c732853ed19e3f6a1a2638d5/packages/messaging/src/controllers/controller-interface.ts#L209)).
Since we were storing a stringified `vapidKey` at that point, if there was no `vapidKey` in an older `tokenDetails` object, [this check](https://github.com/firebase/firebase-js-sdk/blob/7a611b645fbedcd6c732853ed19e3f6a1a2638d5/packages/messaging/src/controllers/controller-interface.ts#L131) (comparing a `string` to `undefined`) would simply return `false`, and get a new token.
After #649, we started to store `vapidKey` as `Uint8Array` instead of the stringified version. This also changed the check …
=> Refresh token instead of breaking if VAPID key doesn't exist

packages/messaging/src/controllers/controller-interface.ts, packages/messaging/src/controllers/window-controller.ts, packages/messaging/test/window-controller.test.ts
Simplified the code by replacing some more promises with async/await and removing deprecated callback API of `Notification.requestPermission()`.
Promise based `requestPermission` API is supported by Chrome since version 46 (2015-10-13) and Firefox since version 47 (2016-06-07). [Source](https://developer.mozilla.org/en-US/docs/Web/API/Notification/requestPermission).
=> Refactoring Messaging

packages/messaging/index.ts, packages/messaging/src/controllers/controller-interface.ts, packages/messaging/src/controllers/sw-controller.ts, packages/messaging/src/models/clean-v1-undefined.ts, packages/messaging/src/models/db-interface.ts, packages/messaging/src/models/iid-model.ts, packages/messaging/src/models/token-details-model.ts, packages/messaging/src/models/vapid-details-model.ts, packages/messaging/test/constructor.test.ts, packages/messaging/test/controller-delete-token.test.ts, packages/messaging/test/controller-get-token.test.ts, packages/messaging/test/controller-interface.test.ts, packages/messaging/test/db-interface.test.ts, packages/messaging/test/get-sw-reg.test.ts, packages/messaging/test/iid-model.test.ts, packages/messaging/test/index.test.ts, packages/messaging/test/sw-controller.test.ts, packages/messaging/test/token-details-model.test.ts
Fixes abbreviations in variable and class names to match Google TypeScript style guide, which follows the [Java style guide](https://google.github.io/styleguide/javaguide.html#s5.3-camel-case).
Also changes some variable names in tests.
=>  Fix variable and class names

packages/firestore/package.json, packages/firestore/src/core/firestore_client.ts, packages/firestore/src/local/simple_db.ts, packages/firestore/test/unit/local/simple_db.test.ts, scripts/release/cli.js, yarn.lock
This PR removes our special handling of `onabort` for IndexedDb transactions and treats aborts as an error (as `onabort` is called for quota exceeded). We currently don't abort transactions in our SDK and hence removing this handling seems like the proper thing to do.
I tested this in a test app (not using the Firestore SDK) and saw this error get set during both the initial schema migration as well as during normal operation. The error is a DOMException with `{ code: 22, name: "QuotaExceededError" }`. To get there, I had to write 32 GB of random data to IndexedDb :)
The 'still propagates error if you throw after aborting an exception' test no longer makes sense since the abort already rejects the transaction.
Fixes: https://github.com/firebase/firebase-js-sdk/issues/720
=>  Treating onabort as an error

packages/firestore/src/util/input_validation.ts
Fixes issue #811, where objects created with `Object.create(null)` would fail input validation.
=> allow storing Object.create(null) in documents

packages/firestore/src/api/database.ts, packages/firestore/src/core/query.ts, packages/firestore/test/integration/api/validation.test.ts
Note: The doc comment change I made in Android is missing because array-contains isn't in the .d.ts yet.
=> b/79432277: Limit Queries to only a single array-contains clause.

packages/firestore/src/local/indexeddb_persistence.ts
The error message that the try/catch is printing is getting a little annoying as I am trying to debug test runs. That's why it is now its own PR!
=> Remove test-only error logs

packages/database-types/index.d.ts
Updated some of the type definitions.
Fixes #306, #555.
=> Update rtdb types

README.md, packages/database-types/index.d.ts, packages/firestore/src/core/firestore_client.ts
This allows us to fall back to memory persistence when we get ABORTED_ERR 20.
Reference: https://developer.mozilla.org/en-US/docs/Web/API/DOMException#Error_names
Fixes: https://github.com/firebase/firebase-js-sdk/issues/720
=>  Falling back on ABORTED_ERROR

packages/functions/package.json
`tslib` was missing from the `package.json`, so the helpers ended up being inlined. This PR fixes this. :)
=> Add missing tslib dependency

packages/firestore/src/core/target_id_generator.ts, packages/firestore/src/local/indexeddb_query_cache.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/memory_query_cache.ts, packages/firestore/src/local/query_cache.ts, packages/firestore/src/remote/remote_store.ts, packages/firestore/test/unit/core/target_id_generator.test.ts, packages/firestore/test/unit/local/query_cache.test.ts, packages/firestore/test/unit/local/test_query_cache.ts, packages/firestore/test/unit/specs/spec_builder.ts
This PR removes the in-memory state from the query cache. All tabs will generate target IDs based on the current state in IndexedDb.
I'm still using the TargetIdGenerator, but it now takes the value read from IndexedDb to generate the next Target ID.
=> Generating target IDs from persistence

packages/firestore/src/remote/online_state_tracker.ts, packages/firestore/src/remote/remote_store.ts
Improved message:
> Could not reach Cloud Firestore backend. Connection failed 2 times. Most recent error: FirebaseError: [code=unavailable]: 14 UNAVAILABLE: Connect Failed
> This is purely an informational message and typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
> 
Or:
> Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.
> This is purely an informational message and typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
=> Improves "Could not reach Firestore backend." log message.

packages/firestore/src/api/user_data_converter.ts, packages/firestore/test/integration/api/database.test.ts
The validation for `set(data, mergeFields:...`) rejected field paths that pointed to field deletes/transforms since these are stripped from the update data.  This PR checks the field mask (for field deletes) and the list of field transforms (for server timestamps) to validate mergeFields.
Note that I could re-use the existing FieldMask.covers() function if I turned the array of field paths into a FieldMask.
=> Allow field deletes for SetOptions.mergeFields

.browserslistrc, .travis.yml, config/karma.saucelabs.js
The root cause of recent cannot start browser failure (https://travis-ci.org/firebase/firebase-js-sdk/jobs/386792434) is that Safari 11.0 used for our browser test is no longer supported by SauceLabs. This commit sets browsers to be always the lasted version available on SauceLabs.
=> Update Chrome and Safari version in cross-browser test.

packages/firestore/src/core/sync_engine.ts, packages/firestore/src/local/shared_client_state.ts, packages/firestore/src/local/shared_client_state_syncer.ts, packages/firestore/src/model/collections.ts, packages/firestore/test/unit/local/persistence_test_helpers.ts, packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
This PR adds local storage notifications for query updates.
There are two kinds of updates that we track:
- Query changes from `inactive` to `pending` or `rejected`.
- A `pending` query receives an update (by setting a new lastUpdateTime).
=> Tracking query state in local storage

packages/firestore/test/unit/specs/spec_builder.ts, packages/firestore/test/unit/specs/write_spec.test.ts
I am getting kind of annoyed at writing `drainQueue()` after every client switch in the SpecTests. This should solve that.
=> Draining on client switches

packages/firestore/test/integration/api/database.test.ts, packages/firestore/test/integration/api/query.test.ts, packages/firestore/test/integration/util/events_accumulator.ts
Behaviour was already correct. This PR is effectively just porting the
existing iOS tests to typescript.
http://b/32764756
=> Refine onSnapshot tests to ensure correct number of events emitted

packages/firebase/README.md
When I looked at package documentation for [firebase](https://www.npmjs.com/package/firebase) package, I didn’t see `firebase-functions` listed. I assumed that it came built-in to `firebase-app`, which [turns out to be wrong](https://firebase.google.com/docs/functions/callable#set_up_your_client_development_environment).
This PR adds `firebase-functions` to the list of modules in `firebase` package’s README.
=> Add firebase-functions to README.

packages/firebase/index.d.ts
You can't use firebase in a TypeScript project that loads firebase via a CDN. If you use a CDN then firebase should be available as a global variable because you don't import firebase in your codebase and just use the global variable.
Therefore (because it's a UMD library) I added a `export as namespace`
=> Exporting firebase as namespace

packages/firestore/src/core/sync_engine.ts
This should bring make the multitab branch green again.
The additional asserts of https://github.com/firebase/firebase-js-sdk/pull/903 uncovered a problem in the Multi-Tab branch since the explicit call to `remoteStore.disableNetwork()` raised `isFromCache:true` events.
=> [Multi-Tab] Don't disable network on shutdown

packages/firestore/src/local/indexeddb_mutation_queue.ts, packages/firestore/src/local/indexeddb_query_cache.ts, packages/firestore/src/local/indexeddb_schema.ts, packages/firestore/src/local/local_serializer.ts, packages/firestore/test/unit/local/indexeddb_schema.test.ts
This works around an IndexedDb bug in Chrome and Firefox that omits index entires for auto-generated keys.
https://bugs.chromium.org/p/chromium/issues/detail?id=701972
=> Workaround for IndexedDb bug

packages/database/src/core/util/libs/parser.ts
Make IE great again. Fixes #958 
I tried adding the tslint [rule](https://github.com/Microsoft/tslint-microsoft-contrib) `"no-unsupported-browser-code": [true, ["IE 11"]],` but as it turns out the package `database` doesn't lint the code.
Linting is only enabled in `firestore` and `messaging`
I went a bit deeper trying to copy the config from `firestore` but as it turns out, there are loads of lint errors and I don't feel like touching more code than necessary.
For the moment simply remote the unsupported method in IE11, if anyone cares please add linting and configure it so that these errors won't show up again in the future
=> Remove startsWith because it's not supported in IE11

packages/functions-types/index.d.ts, packages/functions/package.json, packages/functions/src/api/service.ts, packages/functions/test/callable.test.ts, packages/functions/test/service.test.ts
Testing with the functions emulator is manual only for now, because we shouldn't require people to set it up just to run tests. But I ran it to verify that this works.
=> Add a method to allow using Functions with the local emulator.

packages/firestore/src/local/simple_db.ts
We need to add an `onblocked` handler to our schema uprgade code. This handler gets called when another tab already has an open database connection. These connections prevent schema upgrades, but without this PR, we currently don't fail "enablePersistence()" and instead never resolve the Promise.
Let me know if you think we should include the origin/host name in the error message.
FYI: There is no code that tests this codepath as our schema upgrade tests set up their own onsuccess/onfailure handlers.
=> Add onBlocked handler for schema upgrade

packages/auth/test/auth_test.js
fixed updateCurrentUser test failure on IE11/10
Calls updateCurrentUser after authListener being triggered first time to make sure authListener callback is invoked in expected sequence.
=> fixed updateCurrentUser test failure on IE11/10

packages/auth/src/auth.js, packages/auth/src/autheventmanager.js, packages/auth/test/auth_test.js, packages/auth/test/autheventmanager_test.js
Clears getRedirectResult() in AuthEventManager for a specified Auth instance when it is deleted.
```
app.auth().getRedirectResult() => resolves with redirect result provided previous page called a redirect operation.
app.delete(); // deletes auth instance corresponding to app and clears redirect result.
// re-initialize app with same parameters.
app = firebase.initializeApp(config);
app.auth().getRedirectResult() should resolve with null.
```
This is needed for firebaseui-web react wrapper which on component unmount will delete the firebaseui instance (which deletes the internal auth instance). When the component is mounted again, the previously temp auth instance was still caching the redirect result.
https://github.com/firebase/firebaseui-web/issues/440
Cleans up private property access …
=> Clears getRedirectResult() in AuthEventManager for a deleted Auth instance

packages/firestore/src/core/sync_engine.ts, packages/firestore/src/core/view.ts, packages/firestore/src/local/local_store.ts, packages/firestore/test/unit/specs/limbo_spec.test.ts, packages/firestore/test/unit/specs/listen_spec.test.ts, packages/firestore/test/unit/specs/spec_builder.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
This PR adds the functionality to reconcile views with the truth from persistence as tabs gain the primary lease. To do this, it updates state internal to the view, so we might want to wait with merging this until after the View refactor.
This also fixed an issue in the Spec test that cleared the target IDs on client shutdown. They should be cleared on global shutdown (or just re-recreated at test startup like we already do).
=> [Multi-Tab] Recomputing views after failover

packages/firestore/src/remote/remote_store.ts
No functional changes. Just renames, moves, added comments, etc.
* pendingWrites => writePipeline
* canWriteMutations() => canAddToWritePipeline().
* commit() => addToWritePipeline()
* lastBatchSeen removed since we can compute it on demand from
writePipeline.
* Removed cleanUpWriteStreamState() and instead inlined it in
disableNetworkInternal() since I didn't like the non-symmetry with
cleanUpWatchStreamState() which is called every time the stream closes.
* Lots of comment cleanup.
=> Refactor pendingWrites / write pipeline.

packages/firestore/test/unit/specs/spec_test_runner.ts
Making Multi-Tab easier to debug by using predicable client IDs in the multi-tab spec tests.
=> [Multi-Tab] Using fixed client IDs in spec tests

packages/firestore/test/unit/specs/spec_test_runner.ts, packages/firestore/test/util/mock_platform.ts, packages/firestore/test/util/test_platform.ts
In order to raise visibility events in non-spec unit tests, this PR moves the Platform mocks out of the spec tests file and makes them public in `mock_platform.ts`. There is also a name change from `TestPlatform` to `MockPlatform`.
This is the base PR for what I assume will be #994.
=> [Multi-Tab] Making Platform, Window and Document Mock available in all tests

packages/firestore/src/core/event_manager.ts, packages/firestore/src/core/sync_engine.ts, packages/firestore/src/core/view.ts, packages/firestore/src/core/view_snapshot.ts, packages/firestore/test/unit/specs/listen_spec.test.ts
This PR adds support for queries that SyncEngine knows about but EventManager doesn't.
=> [Multi-Tab]  Supporting non-initial initial queries

packages/firebase/index.d.ts
Creating a reference to another DB instance (Database Sharding https://firebase.google.com/docs/database/usage/sharding) throws typing error: `[ts] Expected 0 arguments, but got 1.`
i.e.
```
app.database(`https://xxx.firebaseio.com/`);
```
I was able to find testing for these cases https://github.com/firebase/firebase-js-sdk/blob/81cd260aeb729c5003952988b19d5b32788510d4/packages/database/test/database.test.ts#L73 but the optional type is missing from https://github.com/firebase/firebase-js-sdk/blob/81cd260aeb729c5003952988b19d5b32788510d4/packages/firebase/index.d.ts#L128
=> Added missing types for optional database instance.

packages/firestore/src/core/firestore_client.ts, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/memory_persistence.ts, packages/firestore/src/local/persistence.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
The latest round of CI failures seem to be due to the fact that we don't wait for `applyPrimaryState` to finish before we consider a client healthy. In the spec tests, I already worked around this by using a deferred Promise, but it probably makes sense to just make `setPrimaryStateListener()` a Promise and let it wait on the call to sync engine.
I'm open to renaming the method to something less setter-like - maybe "registerPrimaryStateListener()"?
=> [Multi-Tab] Solving startup race

packages/firestore/test/unit/specs/listen_spec.test.ts
=> [Multi-Tab] Remove `withGcEnabled` for tests that don't call `unlisten`

packages/firestore-types/index.d.ts, packages/firestore/src/api/database.ts, packages/firestore/src/core/firestore_client.ts, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/indexeddb_schema.ts, packages/firestore/src/local/simple_db.ts, packages/firestore/test/unit/local/indexeddb_schema.test.ts, packages/firestore/test/unit/local/persistence_test_helpers.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
This PR adds the yet-to-be approved API to make multi-tab optional.
It also fixes a race during the shutdown: We need to shut down the persistence layer before we shut down the remote store, as the persistence layer could end up calling the remote store even when it is already destroyed.
TODO: Rename `indexeddb_schema.test.ts` to something more applicable once Multi-Tab is merged.
=> [Multi-Tab] Making Multi-Tab optional

packages/firestore/src/api/credentials.ts, packages/testing/index.ts, packages/testing/package.json, packages/testing/src/api/index.ts, packages/testing/test/database.test.ts
This change enables the testing sdk to talk to the firestore emulator. This is based off of https://docs.google.com/document/d/1dWAVm8-jK_JLsCOx4uZBj2MN_6auc7ood-0llWoojs8/edit?ts=5b47bec0#heading=h.sm63cr1eg2l2
=> Enable firestore sdk to talk to emulator

packages/firestore/src/local/local_store.ts
This TODO seems no longer applicable - the current code in master and the new code has essentially the same performance characteristics. It's O(1) in IndexedDb and O(n) in the memory queue (the memory queue scans tombstones).
The code is also not called more often than before (just in `fillWritePipeline`).
=> Removing no longer applicable comment

packages/firestore/test/unit/specs/listen_spec.test.ts
FYI- This demonstrates the modified spec test to verify we don't overwrite a (newer) deletedDoc with an (older) doc, which fails with your current branch.
=> Modify spec test to demonstrate deletedDoc issue.

packages/firestore/src/core/sync_engine.ts, packages/firestore/test/unit/specs/limbo_spec.test.ts
_NOTE: This is a minimal fix for the issue we discussed; I think a cleaner fix is to move View.syncedDocuments out of the view.  I'll poke at this but it'll probably take longer and be a bit more risky_
This fixes an issue occurring when a limbo target receives a documentUpdate,
then a global snapshot, and then a CURRENT. Because there was a global
snapshot before the CURRENT, WatchChangeAggregator has no pending document
updates and calls SyncEngine.targetContainsDocument() to see if we got any
document from the backend for the target. See:
https://github.com/firebase/firebase-js-sdk/blob/6905339235ad801291edc696dd75a08e80647f5b/packages/firestore/src/remote/watch_change.ts#L422
Prior to this change, targetContainsDocument() returned false because
it relies on our Views to track the …
=> b/72533250: Fix issue with limbo resolutions triggering incorrect manufactured deletes.

packages/firestore/src/core/sync_engine.ts
While porting I noticed this was slightly wrong.  targetContainsDocument() is the method in WatchChangeAggregator.  The SyncEngine method I meant to reference is getRemoteKeysForTarget().
=> Fix method name in comment.

packages/firestore/test/unit/specs/describe_spec.ts
I spent the last hour or so trying to make "specTest.only" work (https://gist.github.com/schmidt-sebastian/2259e4a62b3bc96e2d09ac27ba4e14ee), and gave up when the JSON generator tripped over it. This PR is the not-so-nice-version of that change.
=> Making sure we don't export 'experimental'

packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/test/util/test_platform.ts
This uses logic inspired by the current "zombied owner" logic to also zombie client metadata. This should speed up primary tab election, since any zombied tab will no longer be eligible.
=> [Multi-Tab] Zombie all client data

packages/firestore/src/local/indexeddb_schema.ts, packages/firestore/test/unit/local/indexeddb_schema.test.ts
This is a force fix for potential existence filter mismatches caused by
https://github.com/firebase/firebase-ios-sdk/issues/1548
The essential problem is that when resuming a query, the server is
allowed to forget deletes. If the number of incorrectly synthesized
deletes matches the number of server-forgotten deletes then the
existence filter can give a false positive, preventing the cache from
self healing.
Dropping the query cache clears any client-side resume token which
prevents a false positive existence filter mismatch.
Note that the remote document cache and mutation queues are unaffected
so any cached documents that do exist will still work while offline.
=> Add a schema migration that drops the query cache

packages/firestore/src/local/indexeddb_schema.ts, packages/firestore/test/unit/local/indexeddb_schema.test.ts
Ensure the v3 migration unconditionally creates the TargetGlobal row.  Remove the no-longer-necessary v2 schema migration.
=> Ensure that we create an empty TargetGlobal row.

packages/firestore/src/local/local_store.ts, packages/firestore/src/local/query_data.ts, packages/firestore/src/remote/remote_store.ts, packages/firestore/test/unit/remote/remote_event.test.ts
This involves:
1) Making QueryData immutable
2) Renaming QueryData.update to QueryData.copy
=> Unify local.QueryData with the other platforms

packages/firestore/test/unit/local/persistence_test_helpers.ts, packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts, packages/firestore/test/util/node_persistence.ts, packages/firestore/test/util/test_platform.ts
For Mike.
This also makes it possible to run the WebStorageSharedClientTest in Node.
=> [Multi-Tab] Using WebStorage Mock with all IndexedDB tests

packages/firebase/index.d.ts, packages/firestore-types/index.d.ts, packages/firestore/src/api/database.ts
This comments out the multi-tab flag in one `.d.ts` file and adds it to another (where I missed adding it).
=>  Comment out multi-tab flag

packages/firestore/src/core/sync_engine.ts, packages/firestore/src/local/indexeddb_schema.ts, packages/firestore/test/unit/local/indexeddb_schema.test.ts, packages/firestore/test/unit/specs/limbo_spec.test.ts
This PR just contains the manual changes:
Auto-merging packages/firestore/test/util/helpers.ts
Auto-merging packages/firestore/test/unit/specs/listen_spec.test.ts
Auto-merging packages/firestore/test/unit/specs/limbo_spec.test.ts
CONFLICT (content): Merge conflict in packages/firestore/test/unit/specs/limbo_spec.test.ts
Auto-merging packages/firestore/test/unit/specs/describe_spec.ts
Auto-merging packages/firestore/test/unit/local/indexeddb_schema.test.ts
CONFLICT (content): Merge conflict in packages/firestore/test/unit/local/indexeddb_schema.test.ts
Auto-merging packages/firestore/src/remote/remote_store.ts
Auto-merging packages/firestore/src/local/simple_db.ts
Auto-merging packages/firestore/src/local/local_store.ts
Auto-merging packages/firestore/src/local/indexeddb_schema.ts
CONFLICT …
=> Merging Master into Multi-Tab

packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/memory_persistence.ts, packages/firestore/src/local/persistence.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
This mostly fixes up the spec tests so that we can assert that `LocalStore` always gets an already-started `Persistence` instance.
=> Ensure persistence started

packages/firestore/src/core/view_snapshot.ts, packages/firestore/test/unit/specs/orderby_spec.test.ts
The new `fromInitialDocuments` didn't respect the query order as it went through DocumentChangeSet.  I changed this back to what event manager was doing and added a spec test that verified query result order.
=> [Multi-Tab] Sort the initial set of changes

packages/firestore/src/local/indexeddb_remote_document_cache.ts
FriendlyEats writes a bunch of empty change events to the document change log. Let's not do that.
=> [Multi-Tab] Don't add change log entry when there are no changes

packages/firestore/test/integration/api/fields.test.ts, packages/firestore/test/util/api_helpers.ts
This cleans up the few leftover places where the warning was still being outputted in tests. Running locally, I get a clean log.
=> Firestore: in tests, silence the verbose warning about old timestamp behavior

packages/firestore/test/unit/specs/perf_spec.test.ts
When we have n-updates for n targets, we update the DbTargetGlobal store n times. In the multi-tab branch, this even adds n reads. This perf tests will be used in my follow-up PR that gets rid of these extra updates.
This test is so slow at 100 queries per round that I reduced it to 25.
=> Add Watch update perf test

packages/auth/src/error_auth.js, packages/auth/src/rpchandler.js, packages/auth/test/rpchandler_test.js
Added new client error auth/invalid-provider-id and mapped backend error INVALID_PROVIDER_ID to it.
=> Catch invalid provider id error

packages/firestore/src/local/indexeddb_query_cache.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/memory_query_cache.ts, packages/firestore/src/local/query_cache.ts, packages/firestore/test/unit/local/query_cache.test.ts, packages/firestore/test/unit/local/test_query_cache.ts
This PR ports some of what I think I learned by reviewing Greg's latest Android PR to the Web. This save an additional read on every query update in Multi-Tab.
Greg - is this correct?
=> Don't update query target metadata for updates

packages/firestore/src/remote/datastore.ts, packages/firestore/src/remote/persistent_stream.ts, packages/firestore/src/remote/remote_store.ts, packages/firestore/test/integration/remote/stream.test.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
[FYI- I'll probably have @wilhuff take a look at this too since he had opinions about the stream listener stuff, but in the interest of saving him time, can you do the first pass?]
This breaks out a number of changes I made as prep for b/80402781 (Continue
retrying streams for 1 minute (idle delay)).
PersistentStream changes:
* Rather than providing a stream event listener to every call of start(),
the stream listener is now provided once to the constructor and cannot
be changed.
* Streams can now be restarted indefinitely, even after a call to stop().
* PersistentStreamState.Stopped was removed and we just return to
'Initial' after a stop() call.
* Added `currentAuthAttempt` member to PersistentStream in order to avoid
bleedthrough issues if stop() / start() are called while an auth …
=> Refactor PersistentStream.

packages/firestore/src/core/sync_engine.ts, packages/firestore/src/local/indexeddb_query_cache.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/remote/watch_change.ts, packages/firestore/test/unit/specs/listen_spec.test.ts
Watch sends us a periodic heartbeat with an updated resume token that applies to [all active targets](https://github.com/googleapis/googleapis/blob/201d7be7f9da925df93bc52f8108963284f61aed/google/firestore/v1beta1/firestore.proto#L672) by sending us an empty list of target ids.
Our current implementation in the `WatchChangeAggregator` loops over the target ids in the change so in this case we fail to take any action. If a client has been listening to a query that sees no changes for more than thirty minutes we'll fail to persist any resume token updates during that period.
This change:
* Implements special handling in the WatchChangeAggregator for the empty target IDs list
* Adds a filter in the local store to prevent heartbeat resume token updates from being written out more than once …
=> Implement global resume token

packages/firestore/src/remote/persistent_stream.ts
* Addresses https://github.com/firebase/firebase-js-sdk/pull/1041/files#r205862930 as well as a bunch of similar iOS-isms in comments.
* Renames inactivityTimerPromise to idleTimer for readability and consistency with other platforms.
=> Rename idleTimer and fix comments.

packages/firestore/src/local/indexeddb_persistence.ts
The passed transaction function must accept any `PersistenceTransaction`, even though it totally doesn't and we do a cast later under the hood.
=> Fix unsound type signature

packages/firestore/test/unit/specs/spec_builder.ts, packages/firestore/test/unit/specs/spec_test_runner.ts, packages/firestore/test/unit/specs/write_spec.test.ts
The current spec tests in multi-tab don't verify the ackWrite/failWrite callbacks by default. This fixes this regression.
=> Adding back callback assert

packages/firestore/src/local/indexeddb_mutation_queue.ts, packages/firestore/src/local/persistence_promise.ts, packages/firestore/src/local/simple_db.ts, packages/firestore/src/platform_node/grpc_connection.ts, packages/firestore/src/util/async_queue.ts, packages/firestore/src/util/misc.ts, packages/firestore/test/unit/local/indexeddb_schema.test.ts, packages/firestore/test/unit/local/persistence_promise.test.ts, packages/firestore/test/unit/specs/spec_test_runner.ts, packages/firestore/test/util/helpers.ts, packages/firestore/tsconfig.json
After making some errors that would've been caught via more strict type checking, I explored what would be required to enable stricter checking.
Let me know what you think.
=> Enable strict function types

packages/rxfire/package.json
Reverts firebase/firebase-js-sdk#1079
Temporarily reverting this, as this seems to be what's causing CI deploy errors.
=> Revert "Prep rxfire release"

packages/firestore/src/api/database.ts, packages/firestore/src/core/firestore_client.ts, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/remote/persistent_stream.ts, packages/firestore/src/remote/remote_store.ts, packages/firestore/src/util/async_queue.ts, packages/firestore/test/integration/api/array_transforms.test.ts, packages/firestore/test/integration/remote/stream.test.ts, packages/firestore/test/unit/core/event_manager.test.ts, packages/firestore/test/unit/local/mutation_queue.test.ts, packages/firestore/test/unit/local/query_cache.test.ts, packages/firestore/test/unit/specs/spec_test_runner.ts, packages/firestore/test/unit/util/async_queue.test.ts, packages/firestore/tslint.json
I noticed that we were failing to wait for promises in a couple places so I enabled no-floating-promises lint check and cleaned up all the violations.  To make this a bit easier I introduced enqueue() vs enqueueAndWait() on the AsyncQueue, with the former returning void instead of a Promise.
=> Enable no-floating-promises lint check and fix / suppress violations.

packages/firestore/src/core/firestore_client.ts, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/indexeddb_schema.ts, packages/firestore/src/local/local_store.ts, packages/firestore/test/unit/local/indexeddb_persistence.test.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
This PR:
- Renames the DbOwner store to DbPrimaryClient store (without renaming the IndexedDb location).
- Renames `targetIds` to `queryDataByTarget`
- Renames `indexeddb_schema.test.ts` to `indexeddb_persistence.test.ts`
=> Multi-Tab Renames

packages/firestore/src/local/shared_client_state.ts, packages/firestore/src/util/misc.ts, packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
Not sure if this is an actual improvement, but this addressed the following TODO
// TODO(multitab): Return BATCHID_UNKNOWN instead of null
=> Using BATCHID_UNKNOWN instead of null

packages/firestore/src/local/local_documents_view.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/mutation_queue.ts, packages/firestore/src/local/query_cache.ts, packages/firestore/src/local/remote_document_cache.ts, packages/firestore/test/unit/local/test_mutation_queue.ts, packages/firestore/test/unit/local/test_query_cache.ts, packages/firestore/test/unit/local/test_remote_document_cache.ts, packages/firestore/test/unit/local/test_remote_document_change_buffer.ts
This a) removes two TODOs that are no longer applicable/valid and b) addresses one by changing the test files that wrap the cache to use the primaryLease mode that is used in the rest of the client. 
Note that I did the latter from memory, and if we want to make 100% certain that this is correct, I can go back and verify the callers manually.
=> Removing/Addressing TODOs

packages/firestore/CHANGELOG.md, packages/firestore/src/api/database.ts, packages/firestore/src/core/firestore_client.ts, packages/firestore/test/integration/api/get_options.test.ts
Port of https://github.com/firebase/firebase-ios-sdk/pull/1642 (although there was no crash on web; it just unnecessarily returned an error instead of the cached nonexistent document)
=> Fixed `get({source: 'cache'})` to return nonexistent documents from cache.

packages/firestore/src/core/sync_engine.ts, packages/firestore/src/local/shared_client_state.ts, packages/firestore/src/model/collections.ts, packages/firestore/test/integration/api/get_options.test.ts, packages/firestore/test/unit/local/persistence_test_helpers.ts, packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
This PR removes a bunch of code that was only ever used to save us from persisting a mutation state if no client is interested in it anymore.
=> Remove mutation data from client state

packages/firestore/src/platform_node/grpc_connection.ts
* Use Client.waitForReady() to determine when the stream is actually open,
rather than just considering it open right away.
* Don't lowercase RPC names because the gRPC stub supports both now.
* Remove event handlers / asserts that have been proven safe / unnecessary.
=> GRPC Tweaks.

packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/indexeddb_remote_document_cache.ts, packages/firestore/src/local/indexeddb_schema.ts, packages/firestore/test/unit/local/persistence_test_helpers.ts, packages/firestore/test/unit/local/remote_document_cache.test.ts
This PR adds garbage collection of the Remote Document Change Log. Right now, this runs as part of the client metadata refresh, but I added a TODO for Greg to move it to the LRU callsite once it exists.
I only run the GC code every 30 minutes since it requires a read of all client metadata. 
I tried to unify some code which made `canActAsPrimary` slightly less efficient and this can be reverted.
This code is not well tested (and could potentially be better tested if I added a TimerId for it and scheduled it separately), but I did confirm that Chrome runs this code after 30 minutes (and at startup).
=> Garbage Collect the Remote Document Changelog

packages/rxfire/database/list/index.ts, packages/rxfire/database/object/index.ts, packages/rxfire/test/database.test.ts
CC @davideast 
Added two new specs to test API changes below
`listVal(query, keyField?)` Maps a query to an array of objects
`objectVal(query, keyField?)` Maps a query to an object
=> rxfire: added functions to map RTDB changes to values

packages/firestore/test/unit/core/query.test.ts
Ensure b/112521956 cannot happen (makes sure we don't partially match against objects in the array)
=> Tweak array-contains test for partial object matches.

packages/firestore/src/local/indexeddb_persistence.ts
This removes outdated client metadata entries from IndexedDb. It has been tested manually in Chrome.
=> Delete stale client metadata

packages/firestore/src/core/firestore_client.ts, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/indexeddb_remote_document_cache.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/remote_document_cache.ts, packages/firestore/test/unit/local/indexeddb_persistence.test.ts, packages/firestore/test/unit/local/persistence_test_helpers.ts, packages/firestore/test/unit/local/remote_document_cache.test.ts, packages/firestore/test/unit/local/test_remote_document_cache.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
Remove `start()` from the `RemoteDocumentCache` interface. The memory implementation was a no-op, and `IndexedDbPersistence` can guarantee an already-started `IndexedDbRemoteDocumentCache` instance after it has been started itself.
Additionally, move the specification of multi-tab support to the `IndexedDbPersistence` constructor.
=> Stop starting the remote document cache

packages/firestore/src/api/credentials.ts, packages/firestore/src/core/firestore_client.ts, packages/firestore/src/core/sync_engine.ts, packages/firestore/src/remote/remote_store.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
See https://github.com/firebase/firebase-ios-sdk/issues/1499
This reworks our UserListener into a CredentialChangeListener which
fires on any token change, even if the User did not change. This allows
us to restart our streams (but not switch mutation queues, etc.) on token
changes.
=> firebase-ios-sdk/1499: Restart streams on any token change.

packages/firestore/src/local/memory_remote_document_cache.ts
Drop an unused `start()` implementation.
=> Keep stopping starting

packages/firestore/CHANGELOG.md
Hey Josh, can you confirm that this change I checked in earlier today (4ec654d) will _not_ be included in this week's release?  (if it will be I'll move it to the "0.7.0" section)
=> Update Firestore changelog for token change fix (4ec654d).

packages/firestore/src/local/indexeddb_persistence.ts
This is a follow up to https://github.com/firebase/firebase-js-sdk/pull/1123.
The idea is that we only want to delete the zombied entries if we actually deleted the client metadata from IndexedDb. To do this, I moved the transaction boundary inside the `maybeGarbageCollectMultiClientState` function. To keep things simple, I am no longer running this method at startup, but only after the first lease refresh.
=> Only delete zombied entries on commit success

packages/firestore/src/core/sync_engine.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/shared_client_state.ts, packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
This PR removes the query target metadata row from LocalStorage on the last unlisten.
=> Garbage Collect Query State

packages/firestore/src/local/shared_client_state.ts, packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
I never ended up using the `lastUpdateTime` during garbage collection. Removing it, as well the TODO that asked for rate-limiting the updates (entries only get written when query targets become active/inactive).
=> Remove unused lastUpdateTime

packages/firestore/src/local/shared_client_state.ts, packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
We should try to delete the client metadata row from LocalStorage even if `.shutdown()` wasn't called. Because it won't be.
=>  Attempt to delete client metadata row

packages/firestore/CHANGELOG.md, packages/firestore/src/remote/online_state_tracker.ts, packages/firestore/src/remote/remote_store.ts, packages/firestore/test/unit/specs/offline_spec.test.ts, packages/firestore/test/unit/specs/remote_store_spec.test.ts
1. Changed MAX_WATCH_STREAM_FAILURES to 1 per conversation with @wilhuff and
@jdimond.
2. Fixed a "race" where when a get() triggered a watch stream error, we'd
restart the stream, then get() would remove its listener, and so we had no
listener left once the watch stream was "opened". Without a listen to send
we'd be stuck in Offline state (even though we should be Unknown whenever
we have no listens to send), resulting in the next get() returning data
from cache without even attempting to reach the backend.
=> Offline get() improvements.

packages/firestore/test/unit/specs/describe_spec.ts, packages/firestore/test/unit/specs/listen_spec.test.ts, packages/firestore/test/unit/specs/offline_spec.test.ts, packages/firestore/test/unit/specs/persistence_spec.test.ts, packages/firestore/test/unit/specs/remote_store_spec.test.ts, packages/firestore/test/unit/specs/spec_test_runner.ts, packages/firestore/test/unit/specs/write_spec.test.ts
Verified we don't lose any code coverage in tests.
Exempt a few spec tests from running with memory persistence. Restart the persistence layer along with everything else in spec tests.
=> Stop saving persistence layer across spec tests

packages/firestore/src/platform_browser/browser_platform.ts
This expand the checks of #1139 to support platforms where merely accessing "document" or "window" is an error condition (as is the case in Node for example).
Fixes #1138 which uses ReactNative.
=> Support BrowserPlatforms with no window or document

packages/auth/src/exports_lib.js, packages/auth/src/messagechannel/defines.js, packages/auth/src/messagechannel/receiver.js, packages/auth/src/messagechannel/sender.js, packages/auth/src/storage/indexeddb.js, packages/auth/src/utils.js, packages/auth/test/exports_lib_test.js, packages/auth/test/messagechannel/sender_test.js, packages/auth/test/storage/indexeddb_test.js
* Fixes exportPrototypeProperties for multiple properties where the last property overrides the previous properties.
* Fixes fireauth.messagechannel.Sender.
* Fixes service worker indexedDB on some slow browsers, which was detected in Edge.
=> Various auth fixes

packages/firestore/src/local/indexeddb_mutation_queue.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/memory_mutation_queue.ts, packages/firestore/src/local/mutation_queue.ts, packages/firestore/test/unit/local/mutation_queue.test.ts, packages/firestore/test/unit/local/test_mutation_queue.ts
This is meant to make https://github.com/firebase/firebase-js-sdk/pull/1135 smaller and extracts the refactor that changes `removeMutationBatches` to `removeMutationBatch`, which only accepts a single batch at a time.
=> Change removeMutationBatch to remove a single batch

packages/firestore/src/api/database.ts, packages/firestore/src/model/document.ts, packages/firestore/src/remote/watch_change.ts, packages/firestore/test/util/helpers.ts
... with the class comments from Android.
=> Make MaybeDocument an abstract class

packages/firestore/test/integration/api/validation.test.ts
These are two test cases that keep failing for me on CI, and I hope that I can make them pass more often by moving some of the document mutations out of the for-loop and into the initialization.
=>  Speed up FieldPath validation tests

packages/firestore/src/core/sync_engine.ts, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/persistence_promise.ts, packages/firestore/test/unit/local/indexeddb_persistence.test.ts, packages/firestore/test/unit/local/persistence_promise.test.ts
This adds a small PersistencePromise.forEach() helper to make loop processing easier.
=> Adding forEach Helper

packages/firestore/src/core/firestore_client.ts, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/indexeddb_schema.ts, packages/firestore/src/local/simple_db.ts, packages/firestore/test/unit/local/encoded_resource_path.test.ts, packages/firestore/test/unit/local/indexeddb_persistence.test.ts, packages/firestore/test/unit/local/persistence_test_helpers.ts, packages/firestore/test/unit/local/simple_db.test.ts, packages/firestore/test/unit/specs/spec_test_runner.ts, packages/firestore/test/util/helpers.ts
This PR adds the schema migration that drops existing held write acks one last time. This is part of https://github.com/firebase/firebase-js-sdk/pull/1135
The migration itself is not running yet since the SchemaVersion is still set to 4.
As part of this, I have to plumb through DatabaseId to the migration code. I also started using the same Database names in all tests.
=> Schema migration that drops held write acks

packages/firestore/src/core/sync_engine.ts, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/indexeddb_remote_document_cache.ts, packages/firestore/src/local/persistence.ts, packages/firestore/src/local/shared_client_state.ts, packages/firestore/test/unit/specs/describe_spec.ts
This PR removes Multi-Tab TODOs that are no longer applicable. The GC work is mostly done (with the exception of b/112717384), and we don't need to register pending mutations at startup in LocalStorage since we won't raise callbacks for these and will instead keep track of the changes in the remote document change log.
=> Remove Multi-Tab TODOs

packages/firestore/src/core/sync_engine.ts, packages/firestore/src/local/shared_client_state.ts, packages/firestore/src/util/obj.ts, packages/firestore/test/unit/specs/listen_spec.test.ts
This addresses a TODO in SyncEngine to remove query views when the primary transition to secondary. We only need to keep query views for queries that the secondary is interested in.
While doing this I ran into a bug in the current handling of the primary lease loss: We need to prevent that the remote store, the local store and sync engine always agree on whether a query target exist. If the local storage operation to delete a query target fails, then we must ensure that we also don't remove any other state.
=> Keep Query state consistent when primary lease is lost

packages/firestore/src/core/firestore_client.ts, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/memory_persistence.ts, packages/firestore/src/local/persistence.ts, packages/firestore/test/unit/local/indexeddb_persistence.test.ts, packages/firestore/test/unit/local/persistence_test_helpers.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
This PR:
* removes `start()` from the `Persistence` interface. We always immediately called it after instantiating the persistence layer.
* Makes the constructor for `IndexedDbPersistence` private.
* Provides static factory methods on `IndexedDbPersistence`. They return a `Promise` of a fully started instance. The two methods also differentiate between multi-client and not. They can be consolidated when multi-client becomes required for disk persistence.
* Switch instantiations to use static helpers.
The intention is that if you are able to obtain an instance of `Persistence`, then it is useable. Callers should not have access to unstarted instances.
Note that this PR merges into the `sequence_number` branch to resolve some issues that came up in that PR.
=> Remove start() from Persistence interface

packages/firestore/src/api/database.ts, packages/firestore/src/core/transaction.ts, packages/firestore/src/local/local_documents_view.ts, packages/firestore/src/model/mutation.ts
Add handling of UnknownDocument in places where we check for `instanceof NoDocument`.
=> Checking for UnknownDocument

packages/rxfire/firestore/collection/index.ts
Duplicate emissions affect modified and removes as will as insertion. This is a a port of [angularfire#1825](https://github.com/angular/angularfire2/pull/1825).
=> Gracefully handle duplication modified/removed events in rxfire

packages/firestore/src/local/shared_client_state.ts, packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
Addresses TODO(multitab): Rename all usages of LocalStorage to WebStorage to better ...
I left one user facing mention of LocalStorage as LocalStorage (in an error message).
=> Rename LocalStorage to WebStorage

packages/firebase/package.json
The reference to the `index.d.ts` file is incorrect in `firebase`.
=> Package.json has bad types reference

packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/memory_persistence.ts, packages/firestore/src/local/persistence.ts, packages/firestore/test/unit/local/remote_document_cache.test.ts, packages/firestore/test/unit/local/test_garbage_collector.ts, packages/firestore/test/unit/local/test_mutation_queue.ts, packages/firestore/test/unit/local/test_query_cache.ts, packages/firestore/test/unit/local/test_remote_document_cache.ts, packages/firestore/test/unit/local/test_remote_document_change_buffer.ts
This exposes three modes for an IndexedDbTransaction (readonly, readwrite, readwrite-primary) and removes the `requiresPrimaryLease` flag.
=> Adding readwrite-primary mode

packages/firestore/CHANGELOG.md, packages/firestore/src/api/user_data_converter.ts, packages/firestore/src/model/mutation.ts, packages/firestore/test/integration/api/database.test.ts
We currently drop empty objects when during set({merge: true}) since we only add leaf nodes to the field mask. We need to consider an empty object a leaf node.
Fixes: https://github.com/firebase/firebase-js-sdk/issues/1168
=>  Don't drop empty objects during merge

packages/firestore/src/core/view.ts
I wanted to change this while loop into a for-loop and only check `.size` once. It turns out that `.size` is O(1) though as it is set in the constructor.
=> Remove TODO about making SortedSet.size O(1)

packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/shared_client_state_syncer.ts, packages/rxfire/firestore/collection/index.ts
This PR removes two TODOs for things that I'd rather keep as is:
-  Consider removing `requirePrimaryLease` and exposing three different write modes (readonly, readwrite, readwrite_primary).
While that is a good idea per se, we don't expose the write mode in `IndexedDbPersistence.runTransaction`.
- SharedClientStateSyncer method renames.
I can't think of a better name that isn't super awkward. `applyBatchFromPersistence`/`synchronizeBatchWithPersistence` all imply things that are only 90% true, since these methods combine state from WebStorage and Persistence.
=> Remove TODOs

packages/firestore/CHANGELOG.md, packages/firestore/src/api/database.ts, packages/firestore/test/integration/api/validation.test.ts
In particular, we'll throw a decent error if you accidentally pass a callback
function to get().
=> b/112778345: Improve argument validation for get().

packages/firestore/CHANGELOG.md, packages/firestore/src/api/database.ts, packages/firestore/src/util/input_validation.ts, packages/firestore/test/integration/api/validation.test.ts
In particular, doc("") and collection("") give better messages than saying
the path must be even or odd-length.
Also fixed b/62673263 by removing really stale validation code.
=> b/111221684: Improve error message when passing empty strings to API methods.

packages/util/src/jwt.ts
We use unsecured JWTs for authenticate against the database emulator. I do not think this check is necessary, and it breaks the unsecured JWT auth behavior for the database SDK.
=> Consider JWTs with empty signatures to be valid

packages/auth/package.json, packages/webchannel-wrapper/package.json, yarn.lock
Java 10 removed the -d64 flag, which closure-builder was passing. Updating to the latest version resolves the issue.
=> Upgrade closure-builder dependency to 2.3.0.

packages/firestore/src/local/lru_garbage_collector.ts
As discussed, here's the implementation of `RollingSequenceNumberBuffer` with a `SortedSet`.
Note that merge base is the current `lru` PR: https://github.com/firebase/firebase-js-sdk/pull/1224
=> Using SortedSet instead of a PriorityQueue

packages/firestore/src/local/indexeddb_mutation_queue.ts, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/indexeddb_query_cache.ts, packages/firestore/src/local/indexeddb_schema.ts, packages/firestore/src/local/lru_garbage_collector.ts, packages/firestore/src/local/persistence.ts, packages/firestore/src/local/simple_db.ts, packages/firestore/test/unit/local/lru_garbage_collector.test.ts, packages/util/src/jwt.ts
Adds:
* `LruGarbageCollector` which implements the steps for LRU garbage collection
* Includes a selective port of `java.util.PriorityQueue`
* `LruDelegate` interface, which specifies what is needed for a persistence layer for LRU GC
* `ReferenceDelegate` interface, which handles lifecycle hooks for document references and unreferences
* Note that this is not yet wired up in most production code, as there is currently only a single implementation
* `IndexedDbLruDelegate`, implements `ReferenceDelegate` and `LruDelegate` for `IndexedDbPersistence`
* The LRU test suite
* This currently only runs against `IndexedDbPersistence`, and as such contains a few casts that will be removed once the generic interfaces support the needed methods.
Android Port: …
=> Implement IndexedDB LRU Reference Delegate, add LRU tests

packages/firestore/src/local/indexeddb_mutation_queue.ts, packages/firestore/src/local/memory_mutation_queue.ts, packages/firestore/src/local/memory_persistence.ts, packages/firestore/src/local/memory_query_cache.ts, packages/firestore/src/local/memory_remote_document_cache.ts, packages/firestore/src/local/persistence.ts, packages/firestore/src/local/persistence_promise.ts, packages/firestore/src/local/query_cache.ts, packages/firestore/src/util/obj.ts, packages/firestore/test/unit/local/lru_garbage_collector.test.ts, packages/firestore/test/unit/local/persistence_test_helpers.ts
This PR adds only the lru reference delegate for memory. The merge base is into `lru-master`.
Android Port: FirebasePrivate/firebase-android-sdk#190
iOS Port: firebase/firebase-ios-sdk#1600
=> Implement LRU Reference Delegate for Memory Persistence

packages/firestore/test/unit/specs/write_spec.test.ts
1) Remove "held writes" from the spec tests name
2) Update comment for one of the tests to explain why it really needs eager-gc
=> Update test comments

packages/webchannel-wrapper/package.json, packages/webchannel-wrapper/tools/build.js, yarn.lock
Added a build step to produce bundle in es6 module format.
@mikelehen the output file looks fine to me (it has all the expected exports in es6 format) and I tested it against the repo mentioned in https://github.com/firebase/firebase-js-sdk/issues/1031 and it works fine (just did firebase.firestore()). I don't know if the test is sufficient. If not, can you please let me know what else I should do? thanks!
=> support es6 module in webchannel-wrapper

packages/firestore/src/core/sync_engine.ts, packages/firestore/src/core/view.ts, packages/firestore/test/unit/core/event_manager.test.ts
During the Android port I noticed that all the special handling of View.computeInitialDocChanges was also done by View.computeDocChanges.
This code snippet:
```
const newDocHasPendingMutations = newDoc
? newDoc.hasLocalMutations ||
// We only consider committed mutations for documents that were
// mutated during the lifetime of the view.
(this.mutatedKeys.has(newDoc.key) && newDoc.hasCommittedMutations)
: false;
```
simplifies to: `newDoc.hasLocalMutations` since `mutatedKeys` is empty to start with. `newDoc.hasLocalMutations` happens to be the line we rely on in `computeInitialDocChanges`.
=> Remove computeInitialDocChanges

packages/firestore/src/core/sync_engine.ts, packages/firestore/src/local/persistence_promise.ts, packages/firestore/src/util/sorted_map.ts, packages/firestore/src/util/sorted_set.ts
Revived this PR since https://github.com/firebase/firebase-js-sdk/pull/1256 could benefit from it.
This allows us to use SortedSet and SortedMap in the PersistencePromise utilities.
=> Allow iterables in PersistencePromise.map/forEach/waitFor

scripts/release/utils/git.js
I have seen build issues in travis, which I can't reproduce locally. Adding more debug information, so it's easier to figure out why a build failed.
=> print debug info in release cli

packages/firestore/src/local/local_store.ts
`releaseQuery` can end up calling `updateQueryData`, which writes to IndexedDb.
This is a stracktrace from a local test:
index.esm.js:145 Uncaught Error: FIRESTORE (5.5.2) INTERNAL ASSERTION FAILED: AsyncQueue is already failed: Error: Failed to execute 'put' on 'IDBObjectStore': The transaction is read-only.
at e.put (index.esm.js:9779)
at e.saveQueryData (index.esm.js:10034)
at e.updateQueryData (index.esm.js:10014)
at index.esm.js:12150
at index.esm.js:7582
at e.wrapUserFunction (index.esm.js:7568)
at e.wrapSuccess (index.esm.js:7582)
at e.r.nextCallback (index.esm.js:7552)
=> Using readWrite query mode for releaseQuery

packages/firestore/src/local/shared_client_state.ts, packages/firestore/test/unit/local/persistence_test_helpers.ts
I think this is the last regression that prevents multi-tab from working...  Broke with ac7f9ced0fd18088c17ed76470095f0dcde7a15d
When we write to LS, we should use the unescaped key. Only when we use the key in a RegExp does it need to be escaped. To catch this failure, I changed the test persistence key to include brackets.
=> Don't use the escaped persistence keys when we write to Local Storage

packages/firestore/src/local/shared_client_state.ts, packages/firestore/test/unit/local/web_storage_shared_client_state.test.ts
During today's QA run, I wasn't able to reliably get LocalStorage updates when the entry we wrote didn't change. I would like to add back the `updateTimeMs`.
=> Always update LocalStorage state

packages/firestore/src/local/simple_db.ts, packages/firestore/test/unit/local/simple_db.test.ts
Maybe we should stop iterating in SimpleDb after we encountered an error. Maybe.
=> Stop iterating when we encounter an error

packages/auth/gulpfile.js
The old babel preset env doesn't recognize iife invoked by call, and map this to undefined incorrectly. https://github.com/firebase/firebase-js-sdk/issues/1165
Though it is a babel issue, we have a quick easy fix to be tolerant with the issue by using apply instead.
=> use apply instead of call to invoke iife

packages/firestore/src/local/indexeddb_persistence.ts
This addresses https://www.google.com/url?q=https://github.com/firebase/firebase-js-sdk/pull/1108/files/34e6eecf092bf1f684c290c3accec3b9981c2f17..1ab51cbe48f4c5b3a9c1d36d51435f1487bbee7c%23diff-cf8f425b1bd34112162e05d44fc3a464&sa=D&usg=AFQjCNG-YmGkXVPvM2p5ywOjaZ09G6OEnw
- The 5 second threshold is only used during primary tab selection.
- The 30 minute threshold is used everywhere else. This means that the entire system tracks all states for clients that managed to rewrite their state within the last 30 minutes.  This may lead to additional query load for clients that went away without writing their zombied client ID.
I'm also debating if 30 minutes is maybe a bit too long, since the clients are supposed to update their state every 4 seconds.
=> [Multi-Tab] Separate GC threshold from Primary Election threshold

packages/firestore/src/local/memory_persistence.ts, packages/firestore/src/util/obj_map.ts, packages/firestore/test/unit/util/obj_map.test.ts
Iterating orphaned documents was returning all documents, not just orphaned ones. They weren't being incorrectly GC'd, but they were incorrectly counting towards sequence numbers to GC. 
The test that caught this is coming in the port of https://github.com/firebase/firebase-ios-sdk/pull/1905
Additionally, I implemented `Symbol.iterator` for `ObjectMap` so that I could use `PersistencePromise.forEach()`.
=> Fix error in Memory LRU implementation

packages/firestore/src/core/sync_engine.ts, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/memory_persistence.ts, packages/firestore/src/local/memory_query_cache.ts, packages/firestore/src/local/reference_set.ts, packages/firestore/test/unit/local/reference_set.test.ts
`ReferenceSet` used to have an async method for this so it could conform to the `GarbageSource` interface, but that no longer exists. So, we can have a synchronous `containsKey` implementation.
=> Make ReferenceSet.containsKey synchronous

packages/firestore/src/core/sync_engine.ts
I believe that we handle the ReferenceSet correctly when we transition between Primary and Secondary in 99% of all cases. `synchronizeQueryViewsAndRaiseSnapshots` calls `releaseQuery` and `allocateQuery` for every active query, and as such, the reference set in LocalStore gets synced with disk.
We do however not clear the reference set for Limbo Documents. This PR changes this.
=> Clear reference set when we lose our primary lease

packages/firestore/CHANGELOG.md, packages/webchannel-wrapper/tools/build.js
Set goog.json.USE_NATIVE_JSON to true in our webchannel-wrapper build to avoid
fallback to eval() which isn't necessary, since we already rely on JSON.parse()
throughout the codebase.
=> Fix #798: Avoid eval() in webchannel-wrapper.

packages/firebase/README.md, packages/firebase/src/index.ts
```javascript
import firebase from 'firebase'
``` 
doesn't work with the typings we currently have. It works with vanilla javascript though. But to keep it consistently across javascript and typescript, I'm updating it to 
```javascript
import * as firebase from 'firebase'
```
=> update documentation to show the correct import syntax

packages/testing/README.md, packages/testing/index.ts, packages/testing/package.json, packages/testing/src/api/index.ts, packages/testing/src/protos/google/firebase/rules/v1/source.proto, packages/testing/src/protos/google/firestore/emulator/v1/firestore_emulator.proto, packages/testing/src/protos/google/protobuf/empty.proto, packages/testing/test/database.test.ts
This does two things:
In the short-term, this gives us the ability to set Firestore rules from the SDK, mirroring the database functionality
In the long-term, this proto API will give us the ability to expose interesting non-production functionality from the emulators.
=> Introduce protos to communicate with the Firestore Emulator

packages/firestore/src/util/async_queue.ts
This is the only invocation of `findIndex` in a non test-only path. Alternatively, we could also rewrite this functionality.
Fixes https://github.com/firebase/firebase-js-sdk/issues/1319
=> Remove non-test only invocation of findIndex

packages/firestore/src/local/indexeddb_schema.ts, packages/firestore/src/local/memory_persistence.ts, packages/firestore/src/local/memory_remote_document_cache.ts, packages/firestore/src/local/persistence_promise.ts, packages/firestore/src/util/obj_map.ts, packages/firestore/src/util/sorted_map.ts, packages/firestore/src/util/sorted_set.ts, packages/firestore/test/unit/local/persistence_promise.test.ts, packages/firestore/test/unit/local/remote_document_cache.test.ts, packages/firestore/test/unit/local/test_remote_document_cache.ts, packages/firestore/test/unit/util/obj_map.test.ts
This allows use of Firestore in IE11 without Polyfills.
Fixes https://github.com/firebase/firebase-js-sdk/issues/1308
=> Remove Symbol.iterator

packages/testing/package.json, packages/testing/test/database.test.ts
Before:
```
found 6 vulnerabilities (1 low, 5 moderate) in 2069 scanned packages
6 vulnerabilities require semver-major dependency updates.
```
After:
```
found 0 vulnerabilities
in 1083 scanned packages
```
=> Make npm happier about security vulnerabilities

package.json, yarn.lock
deploying to firebase has been disabled for the older versions of firebase-cli. Updating to the latest version, so we can deploy functions and rules required for testing.
=> update the version of firebase-tools

packages/firebase/index.d.ts
According to this [comment](https://github.com/firebase/firebase-js-sdk/issues/941#issuecomment-401432710) this is now supported in the library. 
This tiny PR makes it available for TypeScript users without `d.ts` hacks.
=> TypeScript support for useFunctionsEmulator

.travis.yml
The latest yarn (1.12.1 as of Nov 1st) appears to hang the CI build.
=> Lockdown the version of yarn to 1.10.1 in our Travis environment.

README.md
Several dependencies currently have a `<=9` requirement on the Node.js engine version. The way the README is written, it may give people the impression that any version above 8 is also supported, but that's not the case for Node.js 10 and 11.
=> [README] Supported Node.js versions for SDK development

packages/functions-types/index.d.ts
There is a return type missing for useFunctionsEmulator() and typescript complains about that.  
I added an Issue already here: #1360
=> added return type definition to useFunctionsEmulator

packages/firestore/src/local/memory_mutation_queue.ts, packages/firestore/src/model/mutation_batch.ts, packages/firestore/test/unit/local/mutation_queue.test.ts
If my understanding is correct, we no longer remove mutation batches from any place but the front of the queue. This PR removes the code that handles this removal.
=> Remove Mutation tombstones

packages/firestore/package.json, packages/testing/package.json, yarn.lock
This removes a deprecated call used internally by GRPC, fixing the deprecation warning.
Fixes https://github.com/firebase/firebase-js-sdk/issues/1113
=> Upgrade GRPC to 1.16.0

packages/testing/src/api/index.ts, packages/testing/test/database.test.ts
Right now if you try `firebase.initializeTestApp({ ..., auth: { "email": "ryan@google.com" })` it will be rejected in the emulator because we require a `sub` field. This happens silently and is pretty confusing. I think we should blow up immediately in the client, so developers can figure out what they're doing wrong.
=>  Throw a more helpful error if there isn't a 'sub' field

packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/lru_garbage_collector.ts, packages/firestore/src/local/memory_persistence.ts
Port of https://github.com/firebase/firebase-android-sdk/pull/80
We had originally decided to only look at targets when assessing how much to run GC. However, based on running a write-heavy workload test, we need to include documents that ended up cached without being part of a target.
=> Use orphaned docs as part of GC calculation

packages/database/test/helpers/EventAccumulator.ts
The `waitsForCount(count)` helper function for the tests of the realtime database returns an `EventAccumulator` that is supposed to wait for `count` events to happen before resolving its Promise.
The current implementation, though, always resolves its Promise after the very first event no matter how many were specified. This could lead to tests behaving erroneously.
A quick demo to verify this incorrect behavior:
```ts
const ea = EventAccumulatorFactory.waitsForCount(3);
setTimeout(() => {
console.log('1');
ea.addEvent();
}, 100);
setTimeout(() => {
console.log('2');
ea.addEvent();
}, 200);
setTimeout(() => {
console.log('3');
ea.addEvent();
}, 300);
ea.promise.then(() => console.log('done'));
```
This outputs the following:
```
1
done
2
3
```
When it should output this:
```
1
2
3
done …
```
=> Fix waitsForCount in EventAccumulator (tests)

packages/testing/index.ts
We attempted to expose these in https://github.com/firebase/firebase-js-sdk/pull/1332 but neglected to expose them in the package-level API.
=> Expose database and firestore namespaces in the @firebase/testing module

packages/firestore/src/platform_node/grpc_connection.ts, packages/testing/index.ts
When we upgraded to gRPC 1.16.0 (https://github.com/firebase/firebase-js-sdk/pull/1353) we accidentally introduced a performance issue in the Firestore emulator. Somewhere between 1.13.1 and 1.16.0, gRPC implemented exponential backoff on a per-connection basis.
We already implement "smart" backoffs that have knowledge of which error codes are safe to retry immediately and which are not, and the gRPC backoffs are happening underneath them. In production use-cases we're dodging this behavior because we're hitting multiple machines. For the emulator, this is introducing exponential delay for every failed write.
=>  Limit gRPC's built-in exponential backoff

integration/browserify/package.json, integration/firestore/package.json, integration/messaging/package.json, integration/typescript/package.json, integration/webpack/package.json, packages/app/package.json, packages/database/package.json, packages/firestore/package.json, packages/functions/package.json, packages/logger/package.json, packages/messaging/package.json, packages/rxfire/package.json, packages/template/package.json, packages/testing/package.json, packages/util/package.json, yarn.lock
We are trying to consolidate flags passed to mocha test into [mocha.opts](https://mochajs.org/#mochaopts). In order to support comments in this file, mocha needs to be upgraded to its latest version (5.2.0 as of 11/09/2018).
See discussion in #1373 for more context.
=> Upgrade mocha version to 5.2.0 in all packages.

packages/auth-types/index.d.ts, packages/auth/src/actioncodesettings.js, packages/auth/src/error_auth.js, packages/auth/src/rpchandler.js, packages/auth/test/actioncodesettings_test.js, packages/auth/test/auth_test.js, packages/auth/test/authuser_test.js, packages/auth/test/rpchandler_test.js, packages/firebase/index.d.ts
Added ability to custom FDL domain in ActionCodeSettings
=> Added ability to custom FDL domain

packages/auth/src/storage/indexeddb.js
`event.target.errorCode` is undefined, use event.target.error instead.
=> Fix error catching for IDBRequest.error.

packages/firestore/package.json, packages/testing/package.json, yarn.lock
Need to update grpc dependency to 1.16.1 to support node 11 according to https://github.com/grpc/grpc-node/issues/594#issuecomment-439526215
=> Update grpc to 1.16.1 to support node 11

packages/firestore/src/api/user_data_converter.ts, packages/firestore/src/model/mutation.ts, packages/firestore/src/remote/serializer.ts, packages/firestore/test/unit/remote/node/serializer.test.ts
Rather than an array.
Port of https://github.com/firebase/firebase-android-sdk/pull/137
=> Rework FieldMask to use a SortedSet of FieldPaths

packages/database/test/transaction.test.ts
The test was calling done() while there were still outstanding transactions,
and a subsequent test was calling goOffline(), which then caused the
outstanding transactions to be aborted, leading to the assertion in the
completion callback to fail. This probably only reproduced with the emulator
because it has much less latency than prod.
=> Fix flaky database transaction test.

packages/firestore/src/api/database.ts, packages/firestore/src/core/firestore_client.ts, packages/firestore/test/unit/local/indexeddb_persistence.test.ts
Refactor `PersistenceSettings`. Removes `PersistenceSettings` in favor of more specific classes. Note that merge base is into the lru PR #1392
=> Internal persistence settings

packages/firebase/index.d.ts, packages/firestore-types/index.d.ts, packages/firestore/src/api/database.ts, packages/firestore/src/core/firestore_client.ts, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/lru_garbage_collector.ts, packages/firestore/src/local/memory_persistence.ts, packages/firestore/src/model/collections.ts, packages/firestore/src/platform/config.ts, packages/firestore/src/util/async_queue.ts, packages/firestore/test/integration/api/validation.test.ts, packages/firestore/test/unit/local/indexeddb_persistence.test.ts, packages/firestore/test/unit/local/lru_garbage_collector.test.ts, packages/firestore/test/unit/local/persistence_test_helpers.ts, packages/firestore/test/unit/specs/spec_test_runner.ts, packages/testing/index.ts
Port of https://github.com/firebase/firebase-android-sdk/pull/68
Enables LRU garbage collection, sets the default theshold at 40mb.
=> Wire together LRU garbage collection

packages/firestore/src/local/simple_db.ts, packages/firestore/src/util/misc.ts, packages/firestore/src/util/promise.ts, packages/firestore/test/unit/local/test_mutation_queue.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
Fixes b/66916745
Of note: `sequence()` was barely being used, so rather than port the declared functionality, I removed what wasn't being used.
=> Finish type migration and get rid of AnyDuringMigration

packages/firestore/CHANGELOG.md, packages/firestore/src/core/firestore_client.ts, packages/firestore/src/core/sync_engine.ts, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/lru_garbage_collector.ts, packages/firestore/src/remote/remote_store.ts
Only schedule garbage collections on the primary tab and gracefully ignore
if they fail.
=> Fixes #1436: Ensure only the primary tab tries to garbage collect.

packages/firestore/src/api/user_data_converter.ts, packages/firestore/src/model/mutation.ts
There are a couple of places in UserDataConverter that construct an array of FieldPaths, which is then  immediately converted to a SortedSet. This PR directly constructs the SortedSet.
Note that I did not touch the remaining FieldPath array in ParseContext, as it is modified in place and requires a mutable data structure.
See commit https://github.com/firebase/firebase-js-sdk/pull/1368/commits/e62de99269434c4c55389dbb10b87fd645d02d4c#diff-af007bc1ca0cf1509f29df38bed7d308L609 for the rationale.
=> Remove some Array to SortedSet<FieldPath> conversion

scripts/emulator-testing/emulators/firestore-emulator.ts
v1.2.3 helps resolve several kinds of errors in firestore sdk emulator test. See updates in this [doc](https://docs.google.com/document/d/1NF9DGH1bL9OIxQk207aMkA1MOC_zJWOO7uHcizao41U/edit).
=> Upgrade firestore emulator version to v1.2.3.

packages/firestore/src/remote/remote_store.ts, packages/firestore/src/remote/rpc_error.ts, packages/firestore/test/unit/specs/spec_builder.ts, packages/firestore/test/unit/specs/write_spec.test.ts
This corresponds to a server-side change that will be released for the v1 protocol only.
=> Treat ABORTED writes as retryable

packages/database-types/index.d.ts, packages/firebase/index.d.ts
Since we implement .catch(), we should extend Promise.
=> Fixes #1450: ThenableReference should extend Promise, not PromiseLike.

packages/firebase/auth/package.json, packages/firebase/database/package.json, packages/firebase/empty-import.d.ts, packages/firebase/firestore/package.json, packages/firebase/functions/package.json, packages/firebase/messaging/package.json, packages/rxfire/database/package.json
* Fixes https://github.com/firebase/firebase-js-sdk/issues/1111 
A full reproduction of the error is available below 
https://github.com/davideast/rxfire-samples/blob/f4b0b6b7959b7fb52b04fb7a8041edb17b92a872/src/preact/index.tsx#L20-L23
```typescript
// NOTE: The lazy load for Firestore does not work with TypeScipt
// w/out hacking the node_modules/firebase/firestore/package.json file
// to use "typings": "../index.d.ts".
const firestore$ = from(import('firebase/firestore'));
```
=> Create empty-import.d.ts and reference it in submodule imports

scripts/emulator-testing/emulators/emulator.ts
The firestore emulator binary file cannot be started by 'java -jar' with
permission 'rw-r--r--' on Google corp workstation (Debian). The reason
why we didn't notice this before is that the emulator can run on macbook
(macOS Mojave) and Travis VM (Ubuntu Trusty) perfectly without this
change though.
=> Change downloaded emulator file mode to 'rwxr-xr-x'.

packages/firestore/src/local/lru_garbage_collector.ts
LruParams.COLLECTION_DISABLED <=> CACHE_SIZE_UNLIMITED
This allows `packages/firestore/test/unit/generate_spec_json.sh` to work without failure.
=> Break import cycle

packages/firebase/index.d.ts, packages/firestore-types/index.d.ts, packages/firestore/CHANGELOG.md, packages/firestore/karma.conf.js, packages/firestore/src/api/database.ts, packages/firestore/src/model/field_value.ts, packages/firestore/test/integration/api/fields.test.ts, packages/firestore/test/integration/util/helpers.ts, packages/firestore/test/unit/model/field_value.test.ts, packages/firestore/test/util/api_helpers.ts, packages/rxfire/test/firestore.test.ts, packages/testing/src/api/index.ts
Also update log messages instructing folks what to do if they're using the
soon-to-be-removed timestampsInSnapshots setting.
=> Change timestampsInSnapshots default to true.

packages/firestore/karma.conf.js, packages/firestore/test/integration/util/helpers.ts, packages/testing/src/api/index.ts
prettier runs on the entire codebase (until https://github.com/firebase/firebase-js-sdk/pull/1480 is merged) which can result in spurious diffs (example: https://github.com/firebase/firebase-js-sdk/pull/1479)
this is just bringing the codebase up to spec
=> Run prettier on the whole codebase

packages/testing/index.ts, packages/testing/src/api/index.ts, packages/testing/test/database.test.ts
This PR exposes a new method for the @firebase/testing package to give users the ability to delete their entire database with one call. This is particularly useful in testing frameworks during the before/beforeEach lifecycle phases to isolate each test from one another. This only works with a properly updated Firestore Emulator (>v1.2.4)
=> Added firestoreClearData() testing sdk method

tools/gitHooks/prettier.js
Making some suggested changes to prettier prepush per #531.
- Check that user's version of prettier matches that specified in project package.json and if not, bail out with message to upgrade.
- Run only on changed files using `git diff --name-only origin/master`.
=> Prettier prepush improvements

packages/firebase/package.json
Adds the file `empty-import.d.ts` to the npm installation and fixes missing line from #1347.
=> Include empty import types file for NPM installation

packages/firestore/test/integration/api/batch_writes.test.ts
This is a port of the test from https://github.com/firebase/firebase-android-sdk/pull/215. Thankfully, no special handling is required here.
=> Verify large write batches support

scripts/release/cli.js, scripts/release/utils/inquirer.js
Reason:
Lerna doesn't work well with merge commits and may mark a package as changed even though it's not changed except for the version bump from the last release.
Background:
We introduced a release branch as a staging area for the next release while development continues in the master branch. Eventually we publish the packages from the release branch and make the version bumps in package.json and tags. It creates a merge commit in the master branch when we merge the release branch back.
=> Allow skipping packages in a release

packages/firestore/test/integration/api/batch_writes.test.ts
This reverts commit 20beaef8a74b1d9c379da90218f73a6b55aa4d98.
This test takes ~6s to run causing some timeouts, and it is unlikely to regress
given IndexedDb doesn't have inherent size limitations for us to work around.
=> Remove "can write very large batches" test.

packages/firestore/test/integration/api/server_timestamp.test.ts
The "can return previous value through consecutive updates" test was flaky
because it did two consecutive server timestamp writes to the same field and
expected 2 local events. But if you do both writes within 1ms then the
snapshots will be indistinguishable (the estimated value for the server
timestamps will be the same) and so only 1 event will be raised. I added an
additional change to the second write to guarantee it triggers an event.
While looking at the test, I also noticed it was slightly broken / incomplete.
There was an incorrect line attempting to disable the network and the test was
missing the remaining code to re-enable the network and verify the behavior.  I
fixed that as well.
=> Fix flaky test.

packages/firestore/src/api/database.ts, packages/firestore/test/integration/api/validation.test.ts
Without this, it still fails, but:
a) not until serializing the query, and
b) the error is an internal error, and
c) the error message is quite cryptic and has nothing to do with the problem.
Port of https://github.com/firebase/firebase-android-sdk/pull/138
=> Forbid queries endAt an uncommitted server timestamp.

packages/firestore/CHANGELOG.md, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/simple_db.ts
1. Fixes #1531 (Firestore error uncaught in promise when primary lease check fails).
2. Ensures IndexedDbPersistence doesn't set up its visibility handler, etc. if
it fails to initialize.
The first one was caused by https://github.com/firebase/firebase-js-sdk/commit/f970f9cd51c17897e397d5b0e30dc5abc3c4999d#diff-db492a8b6a1f21cd1cf9bb73da289281R175
=> Fix issues with enablePersistence() in second tab.

packages/testing/src/api/index.ts
Case: User uses loadDatabaseRules method to upload broken rules.
Behavior before: Fail, but present success from SDK method.
Behavior now: Rejected promise from SDK method with compilation error message (i.e. line number)
=> Made rulesets that don't compile throw errors in testing sdk

packages/app/index.ts
Partially addresses issue https://github.com/firebase/firebase-js-sdk/issues/1415.
Open to suggestions on what the message should recommend to the user.
Tried a rollup node test project and browser webpack test project.  Warning is seen in node, not seen in browser.
=> Add a console warning when browser bundle is loaded in node.

packages/firestore/src/platform_browser/webchannel_connection.ts, packages/webchannel-wrapper/src/index.js
It's not necessary for us to reuse xhr objects or set pool-wide headers /
credentials, so we can just instantiate XhrIo objects directly and save 3865
bytes by not pulling in XhrIoPool. We could consider using XmlHttpRequest
directly instead of going through the XhrIo closure wrapper, but WebChannel
uses XhrIo too, so we get it "for free."
=> Drop usage of XhrIoPool to save 3865 bytes.

config/functions/index.js, packages/firebase/index.d.ts, packages/functions-types/index.d.ts, packages/functions/src/api/service.ts, packages/functions/test/callable.test.ts
`fetch` doesn't support timeouts directly, so this uses `Promise.race` instead.
This also fixes a small problem with the functions test runner that would ignore some errors.
=>  Implement timeouts in HttpsCallables.

packages/auth-types/index.d.ts, packages/firebase/index.d.ts
Fix Types
According the Firebase Documentation of updateProfile() method, you won't change the current attribute's value if you're not passing a property.
https://firebase.google.com/docs/reference/js/firebase.User.html#updateProfile
```
// Passing a null value will delete the current attribute's value, but not
// passing a property won't change the current attribute's value:
// Let's say we're using the same user than before, after the update.
user.updateProfile({photoURL: null}).then(function() {
// Profile updated successfully!
// "Jane Q. User", hasn't changed.
var displayName = user.displayName;
// Now, this is null.
var photoURL = user.photoURL;
}, function(error) {
// An error happened.
});
```
=> Values of updateProfile method can be not passed (optional)

packages/rxfire/database/package.json
Realtime database typings exist for rxfire but the package.json file does not reference them and vscode can't find them. This change adds the missing reference, matching auth/, firestore/, and storage/.
us make Firebase …
=> [rxfire] Reference realtime database typings

packages/firestore/CHANGELOG.md, packages/firestore/src/local/indexeddb_remote_document_cache.ts, packages/firestore/test/unit/local/remote_document_cache.test.ts
Ports an optimization from Android where we skip parsing documents that are in
subcollections beneath the collection we're querying over.
=> Improved query performance in the face of subcollections.

packages/firestore/.idea/runConfigurations/All_Tests.xml, packages/firestore/.idea/runConfigurations/All_Tests__w__Mock_Persistence_.xml, packages/firestore/.idea/runConfigurations/Integration_Tests.xml, packages/firestore/.idea/runConfigurations/Integration_Tests__w__Mock_Persistence_.xml, packages/firestore/.idea/runConfigurations/Unit_Tests.xml, packages/firestore/.idea/runConfigurations/Unit_Tests__w__Mock_Persistence_.xml, packages/firestore/package.json
Fix `yarn test:node:persistence` in packages/firestore and also IntelliJ test runner definitions.
#1561 added a requirement that all test runs include an environment variable of `TS_NODE_COMPILER_OPTIONS={"module":"commonjs"}`. This change propagates this into some Firestore-specific locations.
=> Fix test runners based on changes in #1561

packages/firebase/externs/firebase-firestore-externs.js
Upon importing `firebase-firestore-externs.js` for internal use for the first time, some errors came up when a project attempted to build it using closure compiler, mostly regarding unrecognized jsdoc annotations. Fixed errors brought up by the compiler.
=> Update firestore externs file to avoid closure compiler errors

.vscode/launch.json
TS_NODE_COMPILER_OPTIONS={"module":"commonjs"}. This change propagates this
into .vscode/launch.json.
=> Fix vscode test runners based on changes in #1561.

packages/app/rollup.config.js, packages/database/rollup.config.js, packages/firebase/package.json, packages/firebase/rollup.config.js, packages/firestore/rollup.config.js, packages/functions/rollup.config.js, packages/logger/rollup.config.js, packages/messaging/rollup.config.js, packages/polyfill/rollup.config.js, packages/rxfire/rollup.config.js, packages/storage/rollup.config.js, packages/template/rollup.config.js, packages/testing/rollup.config.js, packages/util/rollup.config.js, packages/webchannel-wrapper/package.json, packages/webchannel-wrapper/tools/build.js, yarn.lock
This enables (and improves) sourcemap generation throughout the repo.  My end goal was to be able to use source-map-explorer on any built artifact in order to better understand the bundle size.
NOTES:
1. I reworked the webchannel-wrapper build to actually generate the intermediate output file for our ESM build as it made it more straightforward to generate tho source map.
2. I had to add rollup-plugin-sourcemaps in order to make rollup notice / use existing sourcemaps (when we use compiled code as an input to a second build).
3. I enabled sourcemaps everywhere.  That may not be necessary, but AFAIK it doesn't hurt anything.
=> Enable sourcemap generation throughout repo.

package.json, scripts/docgen/generate-docs.js, scripts/docgen/toc.yaml
From the docs side, it's a lot easier on them if we preserve the same capitalization of files.  Typedoc generates lowercase files and it doesn't seem easy to fix on Typedoc's side so the script will now get the correct casing for a filename from the `toc.yaml` entry that matches the generated filename in a case-insensitive comparison, and rename the file to that.
=> Fix doc generation script to preserve old filename capitalization

packages/rxfire/README.md
Links in the [documentation section](https://www.npmjs.com/package/rxfire#documentation) of the npm package description page don't work correctly. Using the full URL of the docs pages will fix that.
=> Fix links on npm

packages/app-types/package.json, packages/app/package.json, packages/auth-types/package.json, packages/auth/package.json, packages/database-types/package.json, packages/database/package.json, packages/firestore-types/package.json, packages/firestore/package.json, packages/functions-types/package.json, packages/functions/package.json, packages/logger/package.json, packages/messaging-types/package.json, packages/messaging/package.json, packages/polyfill/package.json, packages/storage-types/package.json, packages/storage/package.json, packages/template-types/package.json, packages/template/package.json, packages/testing/package.json, packages/util/package.json, packages/webchannel-wrapper/package.json
npm supports links to `package.json` files that are not in a root of a repostiory by supplying `directory` field in `repository`, see https://docs.npmjs.com/files/package.json.html#repository
=> Add `repository.directory` field to all `package.json` files

packages/messaging/src/controllers/sw-controller.ts, packages/messaging/test/sw-controller.test.ts
Prevents sending messages to Chrome Extension background pages, which are always considered visible in Chrome. That causes our SDK try to send the message to the background page and to not show the notification.
I'll also investigate if background page being considered a visible client is a bug in Chrome itself, and try to get it fixed if I can. But for now this seems like a good workaround.
=> Fix FCM in Chrome Extensions

.travis.yml, package.json, scripts/release/cli.js, scripts/release/utils/yarn.js
`yarn install` takes a long time at the repo level. Part of it is because we automatically trigger a build for all packages after installation. This change uncouples build script from yarn install at repo level.
=>  rename prepare to build, so build is not triggered after yarn install

packages/firestore/CHANGELOG.md, packages/firestore/src/core/sync_engine.ts, packages/firestore/src/model/field_value.ts, packages/firestore/src/model/path.ts, packages/firestore/src/util/sorted_map.ts, packages/firestore/test/integration/api/query.test.ts, packages/firestore/test/unit/core/query.test.ts, packages/firestore/test/unit/model/path.test.ts, packages/firestore/test/util/helpers.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/1524
The DocumentKey serialization to canonical Query IDs is different once a Query is round-tripped through IndexedDb. After the round-trip, we include the project and database ID in the JSON serialized canonical ID. Since we use this ID as a Map key in SyncEngine, we need to ensure that these IDs are consistent.
This is technically a minor breaking change since it means that existing Queries that filter by DocumentReferences will no longer be read back from persistence. Instead, we will treat them as new queries and GC the old query.
=> Ensure consistent JSON Serialization of DocumentKeys

packages/database/index.node.ts, packages/database/index.ts
Fixes: https://github.com/firebase/firebase-js-sdk/issues/1384
We never exported DataSnapshot from the Database SDK, even though it is part of our types. With this PR, users will be able to directly access it (e.g. for instanceof checks).
=> Adding missing export for DataSnapshot

scripts/docgen/theme/partials/member.sources.hbs
Typedoc adds a link to the source code for every symbol documented, and since we are currently using `index.d.ts` as our source, this is not very useful, and the link wrongly points to the local generated files dir anyway.  If we reach our goal of generating docs from source code we can restore this and fix the bad link prefix too.
This file basically overrides the [default Typedoc theme file of the same name](https://github.com/TypeStrong/typedoc-default-themes/blob/f992ea329904db58671a553c30171eb8fdfd3690/src/default/partials/member.sources.hbs) and removes the sources section.
=> Remove source links from generated reference docs

packages/firestore/src/local/indexeddb_schema.ts, packages/firestore/src/local/lru_garbage_collector.ts, packages/firestore/src/local/persistence_promise.ts, packages/firestore/src/remote/serializer.ts, packages/firestore/test/integration/api/validation.test.ts, packages/firestore/test/unit/local/lru_garbage_collector.test.ts, packages/firestore/test/unit/local/simple_db.test.ts, packages/firestore/test/unit/remote/remote_event.test.ts
I noticed that I quite a few changes when I run `yarn pretter` from the firestore root. This is meant to fix this.
I am running prettier 1.16.4.
=> Running yarn:prettier

packages/firestore/CHANGELOG.md, packages/firestore/src/platform_node/grpc_connection.ts
In https://github.com/firebase/firebase-js-sdk/commit/81cd260aeb729c5003952988b19d5b32788510d4 we moved to sending our auth metadata directly in each RPC call, but for RPCs that take a callback (i.e. non-streaming RPCs like we use to commit a transaction), the auth metadata must be passed *before* the callback, but we were unconditionally passing it as the last argument: https://github.com/firebase/firebase-js-sdk/blob/a18b2905a161f302bf0fad7a32dd82507932093e/packages/firestore/src/platform_node/grpc_connection.ts#L145
I've fixed this by removing the getRpcCallable() helper which I felt wasn't being that helpful anymore. I also cleaned up ensureActiveStub() which accepted a token but didn't do anything with it.
=> b/125385470: Fix transactions w/ auth issue on NodeJS.

integration/browserify/.ncurc.json, integration/browserify/package.json, integration/typescript/.ncurc.json, integration/typescript/package.json, integration/webpack/.ncurc.json, integration/webpack/package.json, packages/app/.ncurc.json, packages/app/package.json, packages/database/.ncurc.json, packages/database/package.json, packages/firestore/.ncurc.json, packages/firestore/package.json, packages/functions/.ncurc.json, packages/functions/package.json, packages/logger/.ncurc.json, packages/logger/package.json, packages/messaging/.ncurc.json, packages/messaging/package.json, packages/rxfire/.ncurc.json, packages/rxfire/package.json, packages/storage/.ncurc.json, packages/storage/package.json, packages/template/.ncurc.json, packages/template/package.json, packages/util/.ncurc.json, packages/util/package.json, yarn.lock
The latest karma-sauce-launcher requires node > 8.9.0 which is restricter than the current > 8.0.0 requirement. Instead of further restricting developers with regards to the node version, I'm downgrading it and excluding it from the dependency auto updates.
=> exclude karma-sauce-launcher in dep auto update

scripts/docgen/generate-docs.js
There was an error in the doc generation script where extraneous files generated in the Node doc process weren't getting deleted.  Missing an html extension and not invoking the unlink function.
=> Fix bug causing extra Node doc files to not be deleted

packages/firestore/index.console.ts, packages/firestore/src/local/index_manager.ts, packages/firestore/src/local/indexeddb_index_manager.ts, packages/firestore/src/local/memory_index_manager.ts, packages/firestore/test/integration/api/numeric_transforms.test.ts, packages/firestore/test/unit/local/index_manager.test.ts, packages/firestore/test/unit/local/test_index_manager.ts, packages/firestore/test/unit/specs/query_spec.test.ts, packages/firestore/tools/console.build.js
License tags are required for internal Google usage.
=> Add license tags for new files since last license tag add

packages/messaging/index.ts, packages/messaging/src/controllers/base-controller.ts, packages/messaging/src/controllers/sw-controller.ts, packages/messaging/src/controllers/window-controller.ts, packages/messaging/src/models/errors.ts, packages/messaging/src/models/iid-model.ts, packages/messaging/src/models/token-details-model.ts, packages/messaging/src/models/vapid-details-model.ts, packages/messaging/test/constructor.test.ts, packages/messaging/test/controller-delete-token.test.ts, packages/messaging/test/controller-get-token.test.ts, packages/messaging/test/get-sw-reg.test.ts, packages/messaging/test/iid-model.test.ts, packages/messaging/test/index.test.ts, packages/messaging/test/token-details-model.test.ts, packages/messaging/test/vapid-details-model.test.ts
Following my own advice from #1645 :slightly_smiling_face:
=> Use a const enum for ErrorCode

packages/app/src/firebaseApp.ts
Randomly noticed this while looking into FirebaseError. This way TS will complain if the `errors` object is missing any `AppError` string, or contains a string that is not in `AppError`.
I'd still recommend using a `const enum` instead of a union type as `AppError` though.
=> Improve AppError typings

tools/config.js
This will put projects with "jscore" in the name at the top of the selection list when the release script prompts which project to test with.  All other projects are still included in the same order as before.
=> Make default testing project easier to select

config/tsconfig.base.json, packages/messaging/tsconfig.json
This option is `false` by default, so there is no need to set it to `false` explicitly.
Also because of this, when a package enables the `strict` option, they also need to enable `noImplicitAny` explicitly, even though it is already a part of the `strict` option.
=> Remove "noImplicitAny: false" from the base TSConfig

packages/firestore/src/local/lru_garbage_collector.ts, packages/firestore/src/local/persistence_promise.ts
Due to improved type inference in typescript 3.4, we need to provide explicit type parameters in the following cases, otherwise we will get an error - https://travis-ci.org/firebase/firebase-js-sdk/builds/514917024#L696
Typescript version will be updated in PR https://github.com/firebase/firebase-js-sdk/pull/1654.
=>  Add explicit type parameters for typescript 3.4

packages/firebase/index.d.ts
Lost a previous fix to `index.d.ts` during merging of changes for docs.
=> Fix accidental reversion due to bad merge

packages/firestore/src/api/database.ts, packages/firestore/src/util/input_validation.ts, packages/firestore/test/integration/api/validation.test.ts
=> Validate operator enum in Query.where() calls

packages/firebase/index.d.ts
Docs team made some changes to where a link should go.
=> Change a documentation link to match docs changes

README.md, packages/firestore/CONTRIBUTING.md
* Adding `yarn build` command to main firebase-sdk-js repo
* Updating firestore documentation
=> Update documentation to use yarn build 

package.json
I'm hoping this makes travis more reliable by limiting the amount of concurrency for our tests .
`--concurrency 4` was also slightly faster than `--parallel` on my local machine. Though any value above 1 was actually fairly comparable:
```
--parallel:      342.63s
--concurrency 1: 498.26s
--concurrency 2: 351.23s
--concurrency 3: 342.50s
--concurrency 4: 336.55s
--concurrency 5: 349.82s
--concurrency 6: 348.19s
--concurrency 7: 341.47s
--concurrency 8: 348.52s
```
=> Use `--concurrency 4` instead of `--parallel` for tests.

packages/firestore/package.json
Since our code is TypeScript we use `--require ts-node/register` for mocha to
be able to run our code. We have this require in our global
`../../config/mocha.node.opts` file, but it apparently isn't applied before the
`--require test/util/node_persistence.ts` in our test:node:persistence
command-line. So I've had to add an explicit `--require ts-node/register` to
our command-line.
=> Fix test:node:persistence command and make travis run it.

packages/firestore/src/api/database.ts, packages/firestore/src/core/firestore_client.ts, packages/firestore/test/integration/api/database.test.ts, packages/firestore/test/integration/util/helpers.ts
Context: b/38324305
Please take a look! Couldn't figure out how to cancel existing listeners and pending promises just yet, but will try to figure it out.
For some reason, the test passed the first time, but no longer passes with persistence = false. Gonna close this PR until I figure out what's wrong.
=> Throw error in subsequent function calls after the client is shutdown

packages/auth-types/index.d.ts, packages/auth/src/authcredential.js, packages/auth/src/exports_auth.js, packages/auth/test/authcredential_test.js, packages/auth/test/rpchandler_test.js, packages/firebase/index.d.ts
- Exposed toJSON and fromJSON on AuthCredential.
- Changed AuthCredential from interface to abstract class as fromJSON is a static method.
- Changed the OAuthCredential constructor to take a OAuthProviderOptions object, but not expose the API to public. The constructor change is backward compatible as it still can take idToken and accessToken string.
=> Expose toJSON and fromJSON on AuthCredential

packages/functions/src/api/service.ts
The functions service lacks an `INTERNAL.delete()` method which I think is the cause of https://github.com/firebase/firebase-js-sdk/issues/1683. This adds a delete method which resolves a top-level promise on the service instance which should cancel any ongoing request promises.
=> Add internal delete method to functions

packages/firebase/externs/firebase-auth-externs.js, packages/firebase/index.d.ts
1. Added `toJSON` and `fromJSON` in auth externs
2. Removed redundant type declaration in JSdocs.
=> Updated externs for AuthCredential serialization/deserialzation

.travis.yml
From [yarn documentation](https://yarnpkg.com/lang/en/docs/cli/install/):
> yarn install --frozen-lockfile
> Don’t generate a yarn.lock lockfile and fail if an update is needed.
With this change, our CI build should fail during the install phase if the lock file wasn't updated properly. But it won't, because this [doesn't actually work](https://github.com/yarnpkg/yarn/issues/5840) :neutral_face:. I guess if they ever fix this bug, it will start working. And then we can remove the integrity check from `tools/pretest.js`.
Also changes the fixed yarn version to `latest`, so that we won't have to change it manually after new yarn releases.
=> Use yarn install --frozen-lockfile in CI

packages/firestore/src/local/simple_db.ts, packages/firestore/test/unit/local/simple_db.test.ts
from: b/80403585, #443 
Reference for IndexedDB support: https://caniuse.com/#feat=indexeddb
Old error message [iOS Safari (iOS 9.1)] (error):
```
[2019-04-17T00:04:02.109Z]  @firebase/firestore: – "Firestore (5.9.4): INTERNAL UNHANDLED ERROR: " – "transaction@[native code]↵open@http://localhost:8080/firebase-firestore.js:1:16616…"
```
New error message (warning):
```
Error enabling offline storage. Falling back to storage disabled: FirebaseError: [code=unimplemented]: This platform is either missing IndexedDB or is known to have an incomplete implementation. Offline persistence has been disabled.
```
=> Exclude iOS Safari < 10.0 and Android < 4.4 when checking isAvailable() to enable persistence

packages/auth/src/error_auth.js, packages/auth/src/rpchandler.js, packages/auth/test/rpchandler_test.js
added admin_only_operation error
=> added admin_only_operation error

packages/auth/src/utils.js, packages/auth/test/utils_test.js
Updates isWorker() check to test if importScripts and WorkerGlobalScope are defined. This removes check on window existence. Some developers resort to mocking window to use certain libraries in worker environment. This causes auth worker functionality to fail.
=> Updates isWorker() check 

packages/auth/src/authevent.js, packages/auth/src/autheventmanager.js, packages/auth/test/authevent_test.js, packages/auth/test/autheventmanager_test.js, packages/auth/test/authuser_test.js
Track AuthEvents with event IDs/session IDs in AuthEventManager and ignore duplicate events. This will prevent race conditions when completing sign in with popup.
=> Track AuthEvent with ID to remove duplicate events

packages/firebase/index.d.ts, packages/firestore-types/index.d.ts
=> Adding documentation for WriteBatch size limit

packages/firebase/package.json, packages/firebase/rollup.config.js
Add "app" to list of components in `package.json` and exclude it from the rollup config's component packaging loop because it uses a slightly different config (above that loop).
=> Add app to component list

packages/database-types/index.d.ts, packages/database/CHANGELOG.md, packages/database/src/api/Query.ts, packages/database/src/core/view/Change.ts, packages/firebase/index.d.ts
Looks like this was merged too early.
=> Revert "Fix the type annotations in the RTDB Query.on/off/once API."

packages/app-types/private.d.ts, packages/app/src/errors.ts, packages/messaging/src/models/errors.ts, packages/util/index.ts, packages/util/src/errors.ts, packages/util/test/errors.test.ts
- Fixes and improves types.
- Uses `extends Error` and `super` instead of messing with prototypes for inheritance.
- Fixes inheritance for ES5 using `setPrototypeOf`, [as recommended by TS](https://github.com/Microsoft/TypeScript-wiki/blob/master/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work).
- Displays a console warning if an entry from `error.data` overwrites a `FirebaseError` property.
- Removes the ability to define a custom pattern for template replacement, which should make packages more consistent. Nobody was actually using that feature anyway.
- Removes `patchCapture`. We run our tests in many browsers, including IE11 and Edge, so there is no need to fake remove `captureStackTrace`.
- Renames `ErrorList` to `ErrorMap`.
- Uses the actual …
=> Refactor FirebaseError

packages/firestore/test/util/equality_matcher.ts
While messing with your serializer changes I kept having issues where the test failure wouldn't include a file / line number and so I couldn't tell for sure which expectation had failed.
Through debugging / reverse-engineering, I came up with this change which seems to work, though this doesn't seem to be a very well-documented area of chai.
=> Fix stack traces for custom equality mismatches.

integration/browserify/package.json, integration/firebase-typings/package.json, integration/messaging/package.json, integration/typescript/package.json, integration/webpack/package.json, packages/auth/package.json, packages/firebase/package.json, packages/firebase/rollup.config.js, packages/firestore/package.json, packages/firestore/src/platform_node/load_protos.ts, packages/firestore/src/remote/serializer.ts, packages/firestore/test/unit/remote/node/serializer.test.ts, packages/rxfire/package.json, packages/testing/package.json
Sorry, I decided to review https://github.com/firebase/firebase-js-sdk/pull/1669 in the form of a PR. 😄 Thanks for doing the hard work to get protobufjs upgraded and the tests working again.  This is basically a cleanup pass to convince myself that everything was working right and simplify the tests. In particular:
1. The switch to protobufjs 6.x seems to have removed the need for hasTag() (and actually it had broken our usage of it since the tags ended up changing from snake_case to camelCase so they never matched). So I've removed hasTag() and set `oneofs: false` in protoLoaderOptions so the virtual "fooType" fields are no longer added at all.
2. 'seconds' in timestamps can and should always be serialized as a string, since it's an int64 value but we weren't doing that. I fixed it, …
=> Clean up some serializer stuff.

packages/firebase/index.d.ts, packages/firestore-types/index.d.ts, packages/firestore/CHANGELOG.md, packages/firestore/src/api/database.ts, packages/firestore/test/integration/api/query.test.ts, packages/firestore/test/integration/api/validation.test.ts
@schmidt-sebastian Can you sanity-check this and then I'll assign to @Feiyang1 to merge into the appropriate release?
=> Expose Collection Group queries API.

packages/auth-types/index.d.ts, packages/auth/src/auth.js, packages/auth/src/authuser.js, packages/auth/src/deprecation.js, packages/auth/src/exports_auth.js, packages/auth/test/auth_test.js, packages/auth/test/authuser_test.js, packages/firebase/externs/firebase-auth-externs.js, packages/firebase/index.d.ts
Removed the 5 APIs being deprecated last year:
1. signInAndRetrieveDataWithCustomToken()
2. signInAnonymouslyAndRetrieveData()
3. createUserAndRetrieveDataWithEmailAndPassword()
4. signInAndRetrieveDataWithEmailAndPassword()
5. fetchProvidersForEmail()
Updated 3 APIs to return UserCredential:
1. Updated signInWithCredential to return UserCredential
2. Updated linkWithCredential to return UserCredential
3. Updated reauthenticateWithCredential to return UserCredential
Marked 3 APIs deprecated:
1. Deprecated signInAndRetrieveDataWithCredential
2. Deprecated linkAndRetrieveDataWithCredential
3. Deprecated reauthenticateAndRetrieveDataWithCredential
=> Auth deprecation

packages/messaging/src/controllers/sw-controller.ts, packages/messaging/src/models/errors.ts, packages/messaging/src/models/iid-model.ts
Prevents overwriting the `FirebaseError` field `message`.
=> Rename message to errorInfo in Messaging errors

packages/app/index.ts, packages/app/package.json, packages/util/index.ts, packages/util/src/environment.ts
1. Proper browser env detection. Fixed https://github.com/firebase/firebase-js-sdk/issues/1754
2. Delay Nodejs detection and warning util initializeApp, so people have a chance to suppress it by setting logLevel in @firebase/logger
=> Revamp environment check for firebase app 

packages/auth/demo/public/index.html, packages/auth/demo/public/script.js, packages/auth/demo/public/web-worker.js
Updated demo to remove deprecated APIs for V6
=> updated demo to remove deprecated APIs

packages/testing/src/api/index.ts
A quite reasonable approach suggested in https://github.com/firebase/firebase-js-sdk/issues/1759
=> Fall back to FIRESTORE_EMULATOR_HOST if FIREBASE_FIRESTORE_EMULATOR_ADDRESS is not found

packages/util/src/environment.ts
=> Fix browser detection

packages/installations/package.json
This allows Rollup to detect `tslib` as an external dependency and doesn't bundle it in the package builds. It should prevent `tslib` being bundled twice in the main build.
=> Add tslib to Installations dependencies

packages/firestore/src/core/firestore_client.ts
=> Gracefully fall back to memory persistence for Firefox Private Browsing.

packages/firestore/src/platform_node/grpc_connection.ts
In gRPC 1.17 they released a feature that preferentially chooses to connect over the last channel that successfully connected. This fixes the underlying issue that we were hacking around with these config parameters.
=> Stop hacking around old gRPC misbehavior

packages/firestore/test/unit/specs/describe_spec.ts, packages/firestore/test/unit/specs/perf_spec.test.ts
This PR:
- adds a new spec tests for queries that only return a small subset of documents from a large collection
- increases the test timeout for benchmark spec tests to 10 seconds
- fixes two performance tests failures that likely broke when we removed held write acks
=> Add performance spec tests for queries against large collections

packages/firebase/package.json
`@firebase/{component}` has a peer dependency on `@firebase/app-types` and some has peer dependency on `@firebase/util`. 
Since firebase depends on `@firebase/{component}` directly, it should list all the peer dependencies from `@firebase/{component}` as its dependency, otherwise yarn will complain with unmet peer dependency warning.
The fact that `@firebase/app-types` is a dependency of `@firebase/app` is not enough as explained in https://github.com/yarnpkg/yarn/issues/5347#issuecomment-386288470
This is not a problem with npm because npm doesn't care how the peer dependencies are installed as long as they are there.
=> add packages to dep list for peer dep requirement

packages/firestore/package.json, packages/firestore/src/platform_node/grpc_connection.ts, packages/firestore/src/platform_node/load_protos.ts, yarn.lock
Fixes #1783, reduces package size, and should ease compatibility issues with Electron, etc.
=> Switch from 'grpc' to '@grpc/grpc-js' dependency.

packages/firestore/CHANGELOG.md, packages/firestore/src/core/firestore_client.ts, packages/firestore/src/remote/remote_store.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
reference: b/35928432
[Android PR](https://github.com/firebase/firebase-android-sdk/pull/217/files)
=> Allow firestore to recover quicker when a network change occurs

packages/app/src/errors.ts, packages/app/src/firebaseApp.ts, packages/app/src/firebaseNamespaceCore.ts, packages/app/src/lite/firebaseAppLite.ts, packages/installations/src/util/errors.ts, packages/messaging/src/models/errors.ts, packages/messaging/src/models/iid-model.ts, packages/performance/src/utils/errors.ts, packages/util/src/errors.ts, packages/util/test/errors.test.ts
This makes it possible to have static type checking for error parameters.
Example:
```typescript
const enum ErrorCode {
WITH_PARAMS = 'with-params',
WITHOUT_PARAMS = 'without-params'
}
const ERROR_MAP: ErrorMap<ErrorCode> = {
[ErrorCode.WITH_PARAMS]:
'This message has {$param} and maybe also {$optParam}.',
[ErrorCode.WITHOUT_PARAMS]: "This message doesn't have any parameters."
};
interface ErrorParams {
[ErrorCode.WITH_PARAMS]: { param: string; optParam?: string };
}
const ERROR_FACTORY = new ErrorFactory<ErrorCode, ErrorParams>(
'service',
'serviceName',
ERROR_MAP
);
ERROR_FACTORY.create(ErrorCode.WITH_PARAMS); // error
ERROR_FACTORY.create(ErrorCode.WITH_PARAMS, undefined); // error with strict
ERROR_FACTORY.create(ErrorCode.WITH_PARAMS, null); // error with strict …
```
=> Add types to ErrorFactory message parameters

packages/firestore/package.json, packages/firestore/src/platform_node/grpc_connection.ts, packages/firestore/src/platform_node/load_protos.ts, yarn.lock
This reverts commit 47711840afa61b27b4dfeeac0a6dd292658c140f. Since this
changes our minimum node dependency from v6 to v8, it is a breaking change and
can't be done at this time.
=> Revert "Switch from 'grpc' to '@grpc/grpc-js' dependency. (#1804)"

packages/firebase/index.d.ts, packages/messaging-types/index.d.ts, packages/messaging/src/controllers/base-controller.ts, packages/messaging/src/controllers/window-controller.ts
I'll also update our documentation and guides to use `Notification.requestPermission()` instead of `messaging.requestPermission()`.
=> Deprecate messaging.requestPermission

packages/firestore/src/platform_browser/browser_platform.ts
fixes https://github.com/firebase/firebase-js-sdk/issues/1817
=> fix the condition that checks if window is available

packages/installations/src/api/create-installation.test.ts, packages/installations/src/api/create-installation.ts, packages/installations/src/api/delete-installation.test.ts, packages/installations/src/api/delete-installation.ts, packages/installations/src/api/generate-auth-token.test.ts, packages/installations/src/api/generate-auth-token.ts
`getErrorFromResponse` returns a `Promise` that resolves to an `Error`. I forgot to `await` the promise before throwing it, resulting in the `Promise` object being thrown instead of the `Error`.
=> Fix throwing a Promise object instead of Error

packages/auth/demo/public/sample-config.js, packages/firebase/performance/index.ts, packages/performance-types/index.d.ts, packages/performance/karma.conf.js, packages/performance/rollup.config.js, packages/performance/src/constants.ts, packages/performance/src/controllers/perf.ts, tools/gitHooks/license.js
We have a script that automatically adds the entire license block but it doesn't add `@license` tags (required for internal Google use) if the block exists and is just missing the tag.  Updated the script to add these tags as well, and ran it on existing files.
=> Update license checking script.

packages/firebase/index.d.ts, scripts/docgen/theme/assets/css/firebase.css, scripts/docgen/theme/partials/comment.hbs
Unfortunately Typedoc requires tags to be below the body text of a comment or it will include the body text as part of the tag immediately above it.
However, we want the contents of `@deprecated` tags to appear at the top of the corresponding entry in the documentation, in order to have the most visibility.  So although we still have to put the `@deprecated` tag below the main body text in a comment, this change modifies the Handlebars template so any `@deprecated` tag will be displayed at the top of its entry.
Also added some styling to make the deprecated tag stand out, per request from docs team.
=> Fix display of deprecated tags in generated docs.

config/.eslintrc.json, packages/app/.eslintrc.json, packages/app/package.json, packages/firestore/.eslintrc.json, packages/firestore/package.json, yarn.lock
Create the base eslint rules for firebase projects. We will apply it to all repos eventually.
As the first step, we need to agree on the set of rules, so feedback is welcomed.
I have run this set of rules against all projects, and there are about 4000 issues. Given the large number of issues, we will enable the eslint rules for project one by one in a few followup PRs. 
The set of rules derives from the google tslint rules. I made a [document](https://docs.google.com/document/d/1oIJrTmqUFDVxH15RKaUneJAux-LgitLDojuLChyrBsI/edit#) to show what rules from google tslint rules are included/excluded and what additional rules are included in this PR.
=> eslint rules for firebase projects

packages/storage-types/index.d.ts
I forgot to add `listAll` to storage-types in https://github.com/firebase/firebase-js-sdk/pull/1610
=> Add listAll() to storage-types

packages/firestore/package.json
Without the `module` set to `commonjs`, `yarn test:emulator` fails to `import * as tslib_1 from "tslib";`.
Other PRs will follow to set up travis testing against emulator.
=> Make yarn test:emulator work again

packages/firestore/package.json
Without this, I get:
Error: not supported
at Root.loadSync (/usr/local/google/home/mikelehen/src/firebase-js-sdk/node_modules/@grpc/proto-loader/node_modules/protobufjs/src/root.js:234:15)
So somehow the protobuf code doesn't realize it's running in node or something...
=> Change test:node:persistence to use --require instead of --file so it actually works.

packages/firestore/CHANGELOG.md, packages/firestore/src/local/simple_db.ts, packages/firestore/test/unit/local/simple_db.test.ts
* On iOS 12.2 we proactively warn about the "internal error was encountered in
Indexed Database Server" Bug.
* When the bug is actually encountered on iOS >= 12.2 an < 13 we log a custom
error message.
Both log message and error link to https://stackoverflow.com/q/56496296/110915 which
provides potential error handling / recovery example.
=> Provide warning and potential workaround for iOS Safari bug described by #1670.

packages/firebase/index.d.ts
Not sure how it got entered incorrectly, but fixing to match `storage-types/index.d.ts`
=> Fix storage Reference.put() param type in top-level index.d.ts

packages/performance/src/services/perf_logger.test.ts, packages/performance/src/services/perf_logger.ts
Browser API doesn't support retrieving HTTP method value currently. Firebase Performance SDK hard coded 1 as HTTP method value to bypass validation check. Firebase Performance service now accpets 0 as value, thus updating SDK to apply HTTP method value from networkRequest object.
=> Update HttpMethod from hardcode value '1' to networkRequest object value

packages/firestore/src/local/simple_db.ts
Now it should show up in the error surfaced repeatedly by the AsyncQueue.
See https://github.com/firebase/firebase-js-sdk/issues/1670#issuecomment-503868451 for context.
=> Make IOS_INDEXEDDB_BUG1 error more prominent when it happens.

packages/firestore/src/api/database.ts, packages/firestore/src/core/query.ts, packages/firestore/src/model/field_value.ts, packages/firestore/src/remote/serializer.ts, packages/firestore/test/unit/remote/node/serializer.test.ts, packages/firestore/test/unit/specs/spec_builder.ts, packages/firestore/test/unit/specs/spec_test_runner.ts, packages/firestore/test/util/helpers.ts
This is a bunch of related changes:
* Extract specific filter types for each special kind of operation
* Rename things to match
* Simplify
Each commit describes what it does individually.
cc @thebrianchen
=> Refactor Filters

config/tsconfig.base.json, packages/database/src/api/test_access.ts, packages/database/src/core/CompoundWrite.ts, packages/database/src/core/PersistentConnection.ts, packages/database/src/core/Repo.ts, packages/database/src/core/RepoInfo.ts, packages/database/src/core/SyncPoint.ts, packages/database/src/core/SyncTree.ts, packages/database/src/core/WriteTree.ts, packages/database/src/core/snap/IndexMap.ts, packages/database/src/core/snap/nodeFromJSON.ts, packages/database/src/core/stats/StatsListener.ts, packages/database/src/core/stats/StatsReporter.ts, packages/database/src/core/util/ImmutableTree.ts, packages/database/src/core/util/Tree.ts, packages/database/src/core/util/util.ts, packages/database/src/core/util/validation.ts, packages/database/src/core/view/EventRegistration.ts, packages/database/test/query.test.ts, packages/storage/src/implementation/requestmap.ts, packages/storage/src/implementation/type.ts, packages/storage/test/testshared.ts, packages/storage/test/xhrio.ts, packages/util/src/obj.ts, packages/util/src/query.ts
Replaces some functions from `@firebase/util` with native functions.
=> Remove some object utility functions

packages/app/index.node.ts, packages/app/index.rn.ts
6.2.2 fixed a React Native bug but introduced a Firestore regression.  Rolling back to 6.2.1 and CPing the RN fix.  Also fixing a bug introduced in 6.2.1 causing Auth errors for Node users.
=> Roll back to 6.2.1 and add RN and XMLHttpRequest fixes

packages/app/index.node.ts
Should use destructuring syntax and not top-level export.
=> Fix typo in XMLHttpRequest import causing auth errors in Node

packages/performance/index.ts, packages/performance/src/controllers/perf.test.ts, packages/performance/src/controllers/perf.ts, packages/performance/src/services/api_service.ts, packages/performance/src/services/perf_logger.test.ts, packages/performance/src/services/perf_logger.ts
Context: https://github.com/firebase/firebase-js-sdk/issues/1774
=> Do not initialize performance if required apis are not available

tools/gitHooks/prettier.js
@var-const ran into an issue where he had some stray files in his git repo and our prettier pre-push hook errantly added them to git, committed them, and pushed them to github upon him running `git push`.
This is undesirable and borderline dangerous.  I believe the fix (thanks to the refactoring you did before) is to simply only add `targetFiles` rather than `.`.
Alternatively we could make the `hasDiff` check [here](https://github.com/firebase/firebase-js-sdk/blob/56301fdfe447dfd7b34432b5ba2fba5205b0707d/tools/gitHooks/prepush.js#L42) detect un-added files in your repo.
=> Fix prettier to avoid adding extra files.

packages/firebase/storage/package.json
Similar to #1792 `firebase/storage` was missing a typing reference.
=> Empty import typings for firebase/storage

packages/app/index.ts, packages/app/src/firebaseNamespaceCore.ts, packages/app/tsconfig.json, packages/logger/tsconfig.json, packages/util/src/crypt.ts, packages/util/src/deferred.ts, packages/util/src/obj.ts, packages/util/src/subscribe.ts, packages/util/tsconfig.json
Turned on Typescript `strict` flag for app, logger, and util packages.  This encompasses a number of more specific flags.
=> Enable Typescript strict flag for app, logger, and util packages

packages/firebase/index.d.ts, packages/firestore-types/index.d.ts, packages/firestore/src/api/database.ts, packages/firestore/src/core/query.ts, packages/firestore/test/integration/api/query.test.ts, packages/firestore/test/integration/api/validation.test.ts
Backporting changes from Android IN queries: 
- [#519](https://github.com/firebase/firebase-android-sdk/pull/519#discussion_r294032999): filter for `null` and `NaN` and reorganize tests to match Android SDK
- [#550](https://github.com/firebase/firebase-android-sdk/pull/550): update doc comments for `clearPersistence()` to include Rachel's edits
- [#560](https://github.com/firebase/firebase-android-sdk/pull/560): Allow IN queries with field path and array of documentIds
This change introduces `KeyFieldInFilter`, which stacks on top of @wilhuff's refactor (#1894). This will be ported to Android when he refactors the Android client.
TODO: After this change goes in, I will update the error messages inside `parseDocumentIdValue()` to match the Android SDK, since those error messages are more …
=> Backport updates from Android (multiple changes)

packages/app/src/errors.ts, packages/app/src/firebaseApp.ts, packages/app/src/firebaseNamespaceCore.ts, packages/app/src/lite/firebaseAppLite.ts, packages/util/src/errors.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/1891,
but as a long term solution for avoid overwriting fields in FirebaseError, we should create a separate field to hold the template parameters. Since it's a potential breaking change, we will wait for the next major version to change it.
I'm not sure why we want the template parameters in the FirebaseError, so maybe we don't need it anyway?
=> Fix FirebaseApp overwriting FirebaseError name field

packages/installations/src/helpers/idb-manager.ts
Prevents errors during page load on browsers that don't support IndexedDB.
Fixes #1774.
=> Delay opening a database connection until a request is made

config/tsconfig.base.json, packages/installations/tsconfig.json
It helps us track what es2015+ features are used in firebase.
=> cherry pick es2015+ libs

packages/firestore/src/api/database.ts, packages/firestore/test/integration/api/validation.test.ts
Standardizing error messages across SDKs. The Android SDK's [error messages](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java#L393) apply better to both documentId queries with operators and with `IN`.
=> Port android error messages for documentId validation

packages/firestore/src/api/database.ts, packages/firestore/src/core/query.ts, packages/firestore/src/model/document.ts, packages/firestore/src/model/field_value.ts, packages/firestore/src/model/mutation.ts, packages/firestore/test/unit/model/field_value.test.ts
Small cleanup PR to make us do less of `doc.field(path) || null`.
Note that the Public API still returns `undefined` for missing fields (to differentiate from null), but the private API doesn't need to since it returns a wrapped FieldValue.
=>  Make Document.field() nullable

packages/firebase/package.json, packages/installations/package.json, packages/installations/src/api/create-installation.test.ts, packages/installations/src/api/create-installation.ts, packages/installations/src/helpers/buffer-to-base64-url-safe.test.ts, packages/installations/src/helpers/buffer-to-base64-url-safe.ts, packages/installations/src/helpers/generate-fid.test.ts, packages/installations/src/helpers/generate-fid.ts, packages/installations/src/helpers/get-installation-entry.test.ts, packages/installations/src/helpers/get-installation-entry.ts, packages/installations/src/interfaces/api-response.ts, packages/performance/package.json
Starting from SDK v0.2.0, the server will start returning a valid FID instead of returning an error if the client tries to register an invalid FID, and the SDK will save that FID to the DB, replacing the invalid one. In case of a failure with client side FID generation, `getId` will wait for a valid FID from the server before resolving instead of throwing or returning an invalid FID.
=> Use the FID from the server if client FID generation fails

packages/firebase/tsconfig.json, packages/functions/src/api/service.ts, packages/functions/tsconfig.json, packages/testing/test/database.test.ts, packages/testing/tsconfig.json
Turn on "strict: true" option in Typescript compiler for functions, testing, and main firebase package.
=> Set typescript strict option to true for functions and testing

packages/firestore/CHANGELOG.md, packages/firestore/src/local/local_store.ts, packages/firestore/src/model/field_value.ts, packages/firestore/src/model/mutation.ts, packages/firestore/src/model/transform_operation.ts, packages/firestore/test/integration/api/numeric_transforms.test.ts, packages/firestore/test/integration/api/server_timestamp.test.ts, packages/firestore/test/unit/model/field_value.test.ts, packages/firestore/test/unit/model/mutation.test.ts, packages/firestore/test/util/helpers.ts
Port of https://github.com/firebase/firebase-android-sdk/pull/564
The PR changes what we store in a BaseMutation. With the changes here, every transform operation computes what it needs to store in the BaseMutation. For Numeric increment, this is either an existing numeric value or the IntegerValue.of(0), replacing all invalid base values at time of creation.
=> Store the coerced base value in the BaseMutation

packages/storage/src/implementation/backoff.ts, packages/storage/src/implementation/blob.ts, packages/storage/src/implementation/metadata.ts, packages/storage/src/implementation/string.ts, packages/storage/src/implementation/xhrio.ts, packages/storage/src/implementation/xhrio_network.ts, packages/storage/src/service.ts, packages/storage/src/task.ts, packages/storage/test/reference.test.ts, packages/storage/test/request.test.ts, packages/storage/test/service.test.ts, packages/storage/test/task.test.ts, packages/storage/test/xhrio.ts, packages/storage/tsconfig.json
Enable `"strict": true` Typescript flag for Storage.
=> Enable Typescript strict flag for Storage

packages/firestore/src/core/sync_engine.ts, packages/firestore/src/core/transaction.ts, packages/firestore/test/integration/api/transactions.test.ts
- Standardize errors based on the spreadsheet.
- Remove local validation for document not found in transactions.
=> Standardize Firestore transaction errors

packages/firestore/src/local/local_documents_view.ts, packages/firestore/test/unit/specs/query_spec.test.ts
Fixing https://github.com/firebase/firebase-android-sdk/issues/155
=> Fix missing query results when it is a match after a local patch mutation.

packages/app/index.ts
This rollup plugin has deprecated the boolean "module" and "main" fields in favor of a "mainFields" array.  Updating warning message to match.
=> Update rollup warning message in Node.

packages/firestore/test/unit/specs/limbo_spec.test.ts, packages/firestore/test/unit/specs/limit_spec.test.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
Adding 2 tests for edge cases that require us to parse more documents that contained in the TargetQueryMapping.
=> Adding Limit/Limbo spec tests for go/index-free

packages/firestore/src/core/transaction.ts, packages/firestore/test/integration/api/transactions.test.ts
Context: [b/135709736](http://b/135709736)
Currently,  if you read a non-existent document, then modify the document twice in the same transaction, each Write will include a precondition that the document did not exist. The server will reject this sequence since each precondition is applied on top of preceding writes in the transaction.
Instead, for the first write to a given key, generate a precondition that takes into account the read time and existence of the document, as we do today. For subsequent writes to a given key, generate a general precondition that only preserves the semantics of the operation: `set()` and `delete()` use  `Precondition(none)` and `update()` uses `Precondition(exists)`.
- Update precondition logic to buganizer spec.
- Reorder public and private methods in …
=> Fix preconditions in transactions

packages/firestore/src/local/local_documents_view.ts
`getMissingBaseDocuments` -> `addMissingBaseDocuments`.
Might not make a big difference here, but will make ios/android code more readable.
=> change getMissingBaseDocuments

config/tsconfig.base.json, packages/app/tsconfig.json, packages/database/tsconfig.json, packages/firebase/tsconfig.json, packages/firestore/tsconfig.json, packages/functions/tsconfig.json, packages/installations/tsconfig.json, packages/logger/tsconfig.json, packages/messaging/tsconfig.json, packages/performance/tsconfig.json, packages/rxfire/firestore/collection/index.ts, packages/storage/tsconfig.json, packages/testing/tsconfig.json, packages/util/tsconfig.json
Most packages have already had the flag enabled, this change enables it on the global `tsconfig.base.json` and removes the flags on individual `tsconfig.json` files.  Database is skipped because we have decided not to update it to strict mode, and Firestore will be updated soon.
=> Enable strict mode on all packages except firestore and database

packages/firestore/test/unit/local/lru_garbage_collector.test.ts, scripts/emulator-testing/firestore-test-runner.ts
Currently, node persistence tests aren't being run on CI. This PR adds the node persistence tests to run on CI, but against the emulator as part of the `yarn test:travis` command.
Edited tests in LRU garbage collector to perform fewer writes, since the tests were timing out on CI.
=> Run persistence and node tests in travis

config/functions/package.json
`engines` becomes a mandatory field after firebase-tools 7.0.0 https://github.com/firebase/firebase-tools/releases/tag/v7.0.0
=> add engines field to functions

packages/firestore/test/unit/specs/describe_spec.ts, packages/firestore/test/unit/specs/limbo_spec.test.ts, packages/firestore/test/unit/specs/spec_builder.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
The  'Limbo documents stay consistent' used the multi-client runner instead of the spec-runner. This PR fixes the test and adds an assert to make sure that this doesn't happen again.
=>  Fix Spec tests 'Limbo documents stay consistent'

config/tsconfig.base.json, packages/database/tsconfig.json, packages/util/src/crypt.ts
1. `downlevelIteration` adds support for iteration protocol for es5 target, but it adds extra codes for simple array iteration. 
Since it is only required by database, I am only setting it in database's tsconfig.json instead of in the global tsconfig.json to prevent the bloat.
2. `base64` was defined as an object literal before. When we enabled typescript `strict` flag, it was changed to a class. Class that are compiled down to es5 can't be treeshaked in rollup, so base64 is included in all packages that depend on `@firebase/util` though they don't use base64. This changes base64 back to object literal with type safety.
=> Fix a regression that leads to larger bundle size

scripts/emulator-testing/emulators/firestore-emulator.ts
This just brings us up-to-date without any functional changes as far as
the SDK is concerned.
=> Upgrade to Firestore Emulator 1.6.2

packages/firestore/src/platform_browser/webchannel_connection.ts, packages/firestore/src/remote/rpc_error.ts
Transactions made via http surface all 400 errors as INVALID_ARGUMENT, when they could also be FAILED_PRECONDITION or OUT_OF_RANGE ([code](https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore/src/remote/rpc_error.ts#L247)).
When possible, parse the error message to determine if the server returned a more specific error code.
=> Surface transaction errors in browser

packages/database/src/core/RepoManager.ts, packages/database/src/core/util/libs/parser.ts
https://github.com/firebase/firebase-js-sdk/pull/2005 added support for point the RTDB javascript sdk at the database emulator. This change improves it by inferring the namespace name from the parsed `databaseURL`  app option field.
=> infer namespace from subdomain in database emulator environment variable

packages/app-types/private.d.ts, packages/app/src/firebaseApp.ts, packages/app/test/firebaseApp.test.ts
Usage: `(app as _FirebaseApp)._removeServiceInstance('serviceName')`
=>  Added an internal API to allow removing a service instance

packages/firestore/src/remote/watch_change.ts, packages/firestore/src/util/log.ts, packages/firestore/test/unit/specs/limit_spec.test.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
This PR adds two spec tests that summarize an offline conversation about potential edge cases for index-free queries (good news is that they pass in the branch). I also made some improvements to our logging which hopefully can cut down future spec test debugging time.
=> Add spec tests for limit queries with limbo documents

packages/database/CHANGELOG.md, yarn.lock
@ryanpbrewster reported an issue where `uglify-js` uglify [this function](https://github.com/firebase/firebase-js-sdk/blob/master/packages/util/src/crypt.ts#L18) incorrectly. As a result, the uglified code does wrong thing on multi-byte utf8 characters.
This function is being used in RTDB, so some user data in RTDB might have been corrupted.
As an illustration 
```javascript
arr[idx++] = 0;
arr[idx++] = 1;
```
is turned into:
```
arr[idx++] = (arr[idx++] = 1, 0)
```
The issue doesn't exist in the latest `uglify-js` anymore, so we upgrade `uglify-js` to 3.6.0
Fixes: #2035
=> fix an obnoxious uglify issue

packages/auth/src/auth.js, packages/auth/test/auth_test.js
clear redirect result after signOut or getRedirectResult being called.
=> clear redirect result after signOut or getRedirectResult being called

packages/firestore/test/unit/specs/describe_spec.ts
With this simple change, tests missing the "exclusive" tag will not be translated into JSON. Hence, we can set breakpoints in the spec builder functions. It's really a win win.
I also expect this to speed up our spec tests so much that this changes the way we look at unit testing. I am talking microseconds.
=> Make spec tests easier to debug

packages/database/CHANGELOG.md, packages/database/src/core/Repo.ts, packages/database/test/info.test.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/2043
=> Unbreak .info/serverTimestampOffset

packages/firestore/test/unit/local/lru_garbage_collector.test.ts
This test was probably timing out, because it was running around 2000ms locally. I've cut it down from 250 writes to 100, so hopefully it should be ok now.
=> Fix flaky integration test

packages/firestore/tsconfig.json
tsconfig.base.json enables "strict" now which implicitly enables
"strictFunctionTypes", "strictNullChecks", and "noImplicitAny" (see https://www.typescriptlang.org/docs/handbook/compiler-options.html) so we don't need
to do so explicitly.
We were disabling "alwaysStrict" but that was unnecessary since we have no violations.
=> Remove unnecessary tsconfig.json flags.

packages/database/src/core/RepoManager.ts, packages/database/test/database.test.ts
In https://github.com/firebase/firebase-js-sdk/pull/2016, we added logic for inferring the namespace name to pass to the RTDB emulator from the result of `parseRepoInfo`, but we didn't actually create a repo class to communicate with it.
=> database sdk not correctly inferring emulator namespace name

packages/firestore/test/unit/specs/limit_spec.test.ts
Update the spec test I wrote on Friday to actually use index-free queries. Note that I still have all tests passing even with this change.
=> Make initial view test actually use index-free queries

scripts/emulator-testing/emulators/database-emulator.ts, scripts/emulator-testing/emulators/emulator.ts, scripts/emulator-testing/emulators/firestore-emulator.ts, scripts/emulator-testing/tsconfig.json
I took the emulator-related part out of https://github.com/firebase/firebase-js-sdk/pull/1941/files and reworked it a bit (trying not to use `!` assertions).  I'll work on all the Firestore stuff next (sorry for being so slow).
NOTE: I left out the `stdio: 'inherit'` lines you changed to `stdio: ['inherit', process.stdout, process.stderr]` as I couldn't figure out what that was for.  Let me know if I should pull that in for some reason.
=> Enable strictNullChecks for scripts/emulator-testing/

packages/firestore/src/api/database.ts, packages/firestore/src/core/firestore_client.ts, packages/firestore/src/core/sync_engine.ts, packages/firestore/src/local/indexeddb_mutation_queue.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/memory_mutation_queue.ts, packages/firestore/src/local/mutation_queue.ts, packages/firestore/src/remote/remote_store.ts, packages/firestore/test/integration/api/database.test.ts, packages/firestore/test/integration/util/helpers.ts, packages/firestore/test/unit/local/local_store.test.ts
=> Port waitForPendingWrites from android

packages/messaging/src/controllers/window-controller.ts, packages/messaging/src/models/errors.ts, packages/messaging/test/window-controller.test.ts
It was deprecated three years ago.
https://developers.google.com/web/updates/2016/07/web-push-interop-wins
=> Remove gcm_sender_id / manifest.json related code

packages/app/index.ts, packages/app/src/errors.ts, packages/app/src/firebaseNamespaceCore.ts, packages/app/src/logger.ts, packages/app/test/firebaseApp.test.ts
A change needed for when multiple components each internally depend on another component and may each try to register it.
=> Do not throw error on duplicate service registration.

packages/firestore/test/unit/specs/limbo_spec.test.ts
This is a very important fix to our spec tests. I stumbled over this doing some somewhat unrelated research. Basically, the limbo document version should advance in time as the spec test receives new snapshots.
=> Fix spec test versions

packages/firestore/test/unit/local/persistence_test_helpers.ts, packages/firestore/test/unit/specs/spec_builder.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
I would like to move the `isShutdown` to the Spec test state expectations. That should help me in my futile attempts to auto-generate spec tests.
=> Move isShutdown to state expectations

packages/firestore/src/local/local_store.ts, packages/firestore/test/unit/local/local_store.test.ts, packages/firestore/test/unit/specs/listen_spec.test.ts, packages/firestore/test/util/helpers.ts
This PR changes the handling of remote documents to skip any document updates for document versions that we already have cached. To keep the code readable, I removed the concept of `authoritativeUpdates` (as discussed in the API discussion phase of Sprint planning).
=> Don't persist documents that we already have

scripts/docgen/theme/partials/navigation.hbs
Remove `<wbr>` (word break) tags Typedoc automatically inserts into section headings (like method names).  This is invisible in the content body text but when devsite grabs the headings to create the right-side nav menu, it converts these to spaces, which puts spaces into method names. Any section heading that has a real space in it will have that space preserved.
=> docs: Remove wbr tags inserted by Typedoc

scripts/emulator-testing/emulators/firestore-emulator.ts
This should fix the CI failure in https://github.com/firebase/firebase-js-sdk/pull/2128
1.5.0 returns the following response to a delete of a non-existing doc:
```
Firestore (6.4.0) [Connection]: GRPC stream sending: { streamToken: <Buffer 30>,
writes: 
[ { delete: 'projects/test-emulator/databases/(default)/documents/test-collection/8ZFesMAbTQGIuVox8P17' } ] }
Firestore (6.4.0) [Connection]: GRPC stream received: { writeResults: 
[ { transformResults: [], updateTime: { seconds: '0', nanos: 0 } } ],
streamId: '',
streamToken: <Buffer 31>,
commitTime: { seconds: '0', nanos: 0 } }
```
I believe newer version now return a proper commit and update time.
=> Upgrade Firestore Emulator to 1.8.2

packages/firestore/CHANGELOG.md, packages/firestore/src/api/credentials.ts
https://github.com/firebase/firebase-js-sdk/pull/2078/ altered the
initial state of currentUser from undefined to not undefined, which
caused the if statement to unconditionally evaluate to true. This
results in a race condition that could cause some initial writes to the
database to be dropped.
Fixes https://github.com/firebase/firebase-js-sdk/issues/2135
=> Avoid auth triggers if we haven't yet received the initial user.

packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/indexeddb_remote_document_cache.ts, packages/firestore/src/local/indexeddb_schema.ts, packages/firestore/src/local/local_serializer.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/memory_persistence.ts, packages/firestore/src/local/remote_document_change_buffer.ts, packages/firestore/src/local/simple_db.ts, packages/firestore/test/integration/api/batch_writes.test.ts, packages/firestore/test/integration/api/database.test.ts, packages/firestore/test/unit/local/encoded_resource_path.test.ts, packages/firestore/test/unit/local/indexeddb_persistence.test.ts, packages/firestore/test/unit/local/lru_garbage_collector.test.ts, packages/firestore/test/unit/local/remote_document_cache.test.ts, packages/firestore/test/unit/local/remote_document_change_buffer.test.ts, packages/firestore/test/unit/local/simple_db.test.ts, packages/firestore/test/unit/local/test_remote_document_cache.ts, packages/firestore/test/unit/local/test_remote_document_change_buffer.ts
This a loosely based port of https://github.com/firebase/firebase-android-sdk/pull/615 and https://github.com/firebase/firebase-android-sdk/pull/686
It adds a read time index to the Remote Document Store that can be used for Index-Free queries.   I also wasn't able to find good documentation on what happens if I add an index to an existing ObjectStore, but I wrote a test that verifies that this works. 
A follow up PR uses a similar index for the Multi-Tab changelog.
=> Index-Free: Track readTime in the RemoteDocument store

scripts/docgen/tsconfig.json
non strict mode generates nicer documentation, so we use non strict mode.
In strict mode, optional parameters have `undefined` as part of its type definition in addition to the `Optional` label.
=> use non strict mode when generating doc

packages/firestore/.idea/runConfigurations/All_Tests__Emulator_.xml, packages/firestore/.idea/runConfigurations/All_Tests__Emulator_w__Mock_Persistence_.xml, packages/firestore/.idea/runConfigurations/Integration_Tests__Emulator_.xml, packages/firestore/.idea/runConfigurations/Integration_Tests__Emulator_w__Mock_Persistence_.xml
This matches the AndroidStudio test runners that by default connect to the emulator.
=> Make IntellJ test runners connect to Emulator

packages/firestore/src/local/memory_remote_document_cache.ts
Adds readTime to the MemoryRemoteDocumentCache, which allows us to also filter by read time during query execution.
=> Index-free: Add readTime to the MemoryRemoteDocumentCache

packages/firestore/src/core/view_snapshot.ts, packages/firestore/src/local/indexeddb_schema.ts, packages/firestore/src/local/local_serializer.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/local_view_changes.ts, packages/firestore/src/local/query_data.ts, packages/firestore/test/unit/core/view.test.ts, packages/firestore/test/unit/local/local_store.test.ts, packages/firestore/test/unit/local/query_cache.test.ts, packages/firestore/test/unit/remote/node/serializer.test.ts, packages/firestore/test/unit/specs/spec_test_runner.ts, packages/firestore/test/util/helpers.ts
This PR ports the end state of 
https://github.com/firebase/firebase-android-sdk/pull/771
https://github.com/firebase/firebase-android-sdk/pull/767
https://github.com/firebase/firebase-android-sdk/pull/699
https://github.com/firebase/firebase-android-sdk/pull/616
Since there is a bunch of back and forth in these PRs, I based it on a combined diff: https://gist.github.com/schmidt-sebastian/d6c28b541d48442f19e50f9c78d78d6e
=> Index-Free: Persist the lastLimboFreeSnapshot version

packages/firestore/src/local/indexeddb_remote_document_cache.ts, packages/firestore/src/local/local_documents_view.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/memory_remote_document_cache.ts, packages/firestore/src/local/remote_document_cache.ts, packages/firestore/test/unit/local/local_store.test.ts, packages/firestore/test/unit/local/remote_document_cache.test.ts, packages/firestore/test/unit/local/test_remote_document_cache.ts
This PR adds the ability to getAllDocumentsMatchingQuery() to skip documents older than a given update time. This allows us to only scan for documents that have been modified since the Query's Target Mapping has been persisted.
Port of https://github.com/firebase/firebase-android-sdk/pull/617
=> Index-Free: Filter document queries by read time

packages/firestore/src/core/firestore_client.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/query_engine.ts, packages/firestore/src/local/simple_query_engine.ts, packages/firestore/test/unit/local/local_store.test.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
Adds SimpleQueryEngine and wires it up.
Android: https://github.com/firebase/firebase-android-sdk/blob/715f3f03a96681e8dfd816b2645276b2cd58b8d7/firebase-firestore/src/main/java/com/google/firebase/firestore/local/SimpleQueryEngine.java
https://github.com/firebase/firebase-android-sdk/blob/715f3f03a96681e8dfd816b2645276b2cd58b8d7/firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryEngine.java
=> Add SimpleQueryEngine

packages/firestore/src/core/firestore_client.ts, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/test/unit/local/indexeddb_persistence.test.ts, packages/firestore/test/unit/local/persistence_test_helpers.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
My next PR is going to add one more argument to IndexedDbPersistence, so I thought it was a good idea to clean up the initialization a tiny bit.
=> Clean up IndexedDb initialization

packages/firestore/src/core/query.ts, packages/firestore/test/unit/core/query.test.ts
Ports:
- https://github.com/firebase/firebase-android-sdk/blob/master/firebase-firestore/src/main/java/com/google/firebase/firestore/core/Query.java#L123
- https://github.com/firebase/firebase-android-sdk/blob/master/firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryTest.java#L534
This will be used to opt out Index-Free query processing for queries that match all documents.
=> Port matchesAllDocuments()

packages/firestore/src/local/local_documents_view.ts, packages/firestore/test/unit/local/forwarding_counting_query_engine.ts, packages/firestore/test/unit/local/local_store.test.ts
"Sebastian uses his time wisely."
This is another take on https://github.com/firebase/firebase-js-sdk/pull/2164.
It solves the following issues:
- It doesn't add any stats that are not used/not tested.
- It doesn't add code to the main client.
- It removes the need to plumb a counter through the Persistence layer.
- it reduces the reliance on the exact implementation, but instead focuses more on the result of each operation.
- it gives us a reason to port this back to Android.
=> Expose operation counts from Persistence layer (take 2)

.travis.yml
Google has dropped Ubuntu 14.04 (Trusty) support for Chrome with their latest release today, so we change to use Ubuntu 16.04 (Xenial) image instead.
=> use Ubuntu 16.04 (Xenial) image

packages/firestore/test/unit/specs/spec_builder.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
Consolidating spec expectations to start with a prefixed "expected" after adding "expectedSnapshotsInSyncEvents"
- `SpecExpectation` renamed to `SnapshotEvent`
- `SpecStep.expect` renamed to `SpecStep.expectedSnapshotEvents`
- `SpecStep.stateExpect` renamed to `SpecStep.expectedState`
I was thinking about changing `expectEvents()` to `expectSnapshotEvents()`, as to not confuse SnapshotEvents with SnapshotsInSyncEvents, but that change would affect a bunch of existing spec tests. Thoughts on if that's necessary?
=> Rename spec test functions

packages/firestore/src/local/local_store.ts, packages/firestore/test/unit/local/local_store.test.ts
If there is a chance that a limbo resolution fails for a document that no longer exists, we could get into a state where we write a document into the RemoteDocumentCache with a snapshot version of zero. By re-ordering the statements, we make sure this does not happen
Port of https://github.com/firebase/firebase-android-sdk/pull/802
=> Change the order of checks in applyRemoteEvent()

packages/firestore/src/local/local_store.ts, packages/firestore/test/unit/local/forwarding_counting_query_engine.ts
This PR replaces the O(n) loop in getQueryData() with a key lookup in an ObjectMap. This follows the precedent in SyncEngine (and maybe eventually leads us down the path of merging the different query tracking mechanisms).
=> Add Query to Target ID Map

packages/firestore/test/unit/specs/spec_test_runner.ts
Backporting validation spec test functions from [iOS](https://github.com/firebase/firebase-ios-sdk/pull/3895).
=> Backport spec test function renaming

packages/firestore/test/unit/specs/limbo_spec.test.ts
This PR adds a test for the assert that caused the Index-Free rollback on Android (b/141011925).
The customer got back to me (in person at the Firebase Summit) and their stacktrace is actually from MemoryPersistence. With MemoryPersistence it is actually much more likely to hit the scenario that we discussed as the possible culprit (in LocalStore.applyRemoteEvent):
```
if (existingDoc == null) {
// This is the path that causes the assert. A failed limbo resolution added a 
// NoDocument, but the limbo resolution fails when we have already deleted
// the offending document from cache.
} else if (doc instanceof NoDocument) {
// This is the good path 
}
```
With EagerGC, existingDoc is null if we already unlistened from the query that originally returned it when the Limbo resolution fails …
=> Add test for NoDocument assert

packages/storage/src/implementation/constants.ts
It seems like there was a missing zero for the milliseconds, which resulted in the max time being one minute instead of ten.
=> Fixed default timeout for uploads

packages/database/CHANGELOG.md, packages/database/src/core/util/util.ts, packages/database/test/path.test.ts, packages/firestore/test/unit/specs/limbo_spec.test.ts
Fixes https://buganizer.corp.google.com/issues/141298281
A customer noticed that we don't correctly order their documents. Some of their documents are using keys of the form "00x", where x is a 9 digit number. Our number check only allows for ten digits, and leading zeros can break this limit. This PR relaxes the check and matches the backend semantics.
=> Allow leading zeros in tryParseInt

.github/CODEOWNERS
Add owners for analytics and RC, so relevant PRs can be automatically assigned to the owners.
=> add code owners for analytics and rc

scripts/docgen/content-sources/js/toc.yaml, scripts/docgen/content-sources/node/toc.yaml
The ordering currently doesn't make sense:
https://firebase.google.com/docs/reference/js/firebase.auth
https://firebase.google.com/docs/reference/js/firebase.storage
This fixes b/141303832.
=> Sort classes properly in doc.

packages/firebase/package.json, packages/firebase/src/index.cdn.ts, packages/firebase/src/index.ts
`@firebase/analytics` should be a dependency of `firebase`, so it's not bundled inside `firebase`.
The issue is reported here at https://github.com/firebase/firebase-js-sdk/issues/2213.
=> add @firebase/analytics to firebase deps

README.md, scripts/docgen/content-sources/js/HOME.md, scripts/docgen/content-sources/node/HOME.md
Script tag snippet next to CDN option looks odd and is misleading (points users at use all-in-one package, which is not recommended).  Using a link to direct users to appropriate documentation page instead.
=> Update docs to link to CDN guide

packages/firestore/CHANGELOG.md, packages/firestore/src/model/document.ts, packages/firestore/src/protos/firestore_proto_api.d.ts, packages/firestore/test/integration/api/query.test.ts
Fixes https://github.com/firebase/firebase-js-sdk/issues/2204
This fixes the types for MapValue.fields  so that tslint catches undefined violations and removes the violation in `getProtoField` that caused https://github.com/firebase/firebase-js-sdk/issues/2204
Note that is seems pretty involved to write a test for this since this code is only hit in Query processing and not in DocumentSnapshot.get() (see https://github.com/firebase/firebase-js-sdk/blob/4016987a72fa87eea5171dd718d20f9e5dde8123/packages/firestore/src/api/database.ts#L1346). If requested, I can add this test next week.
=> Treat empty maps correctly in Document.get()

packages/analytics-types/index.d.ts, packages/analytics/src/functions.test.ts, packages/analytics/src/functions.ts, packages/firebase/index.d.ts
It seems like a common enough case to call logEvent with no params.  Making this allowable in the type, and ensuring there is a default in the gtag call.
=> Make event params optional in logEvent

packages/firestore/src/remote/serializer.ts
=> Send raw values when using WebChannel

packages/firestore/src/local/local_store.ts
iOS and Android update the sequence number in LcoalStore.applyRemoteEvent(). This prevents LRU GC for a query that does not explicitly go through releaseQuery.
=> Update SequenceNumber in LocalStore.applyRemoteEvent

.vscode/launch.json
CLI invoked tests already run against the emulator by default, and the .vscode ones should as well.
=> Make vscode tests run against emulator

packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/simple_db.ts, packages/firestore/test/unit/local/encoded_resource_path.test.ts, packages/firestore/test/unit/local/indexeddb_persistence.test.ts, packages/firestore/test/unit/local/simple_db.test.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
This PR marks all straightforward calls of SimpleDb.runTransaction as idempotent. Most of the usage is in test.
This was verified via a manual code audit and via a test hack (not checked in) that fails the first run of idempotent transactions.
=> Marking SimpleDb calls as idempotent

packages/firestore/CHANGELOG.md, packages/firestore/src/remote/serializer.ts, packages/firestore/test/unit/remote/node/serializer.test.ts
This fixes using timestamps with the Firestore Emulator. This is similar to #2228, but for timestamps.
(Internal tracking ID: 37282237)
Tested manually against the Firestore Emulator and production Firestore.
None.
=> Serialize Timestamps as string (per proto3 JSON format).

packages/firestore/test/unit/local/indexeddb_persistence.test.ts
The test 'can use read-time index after schema migration' is not actually idempotent. I don't know why yet, but let's mark it as non-idempotent for now to not block testing.
=> Fix test failure

packages/firestore/test/unit/local/local_store.test.ts
These tests fail when transactions are re-run (as advised during the go/ios-13 migration)
=> Temporarily disable CountingQueryEngine tests

packages/firestore/src/local/simple_db.ts
Improve the idempotent test hack to prevent writes to IndexedDb by failing the transaciton.
=>  Improve test hack

packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/memory_persistence.ts, packages/firestore/src/local/persistence.ts, packages/firestore/test/unit/local/persistence_transaction.test.ts
This should simply some of the idempotent development by allowing any PersistenceTransaction consumer to register onCommitted listeners.
=> Add onCommitted listeners for transactions

packages/firestore/src/local/local_store.ts
I looked through all the code that is called from `collectGarbage()` (and there is a lot), but it seems like there is no in-memory state that is modified during garbage collection. It seems safe to be re-run.
FWIW, we could also blindly swallow all errors that `collectGarbage()` might throw, but then we would likely never receive feedback about any LRU problems.
=> Mark collectGarbage idempotent

packages/firestore/CHANGELOG.md, packages/firestore/src/local/simple_db.ts, packages/firestore/test/unit/local/local_store.test.ts
Address TODOs, add Changelog.
The only outstanding TODO is the clean up of the different modes we pass to runPersistence, but we should discuss offline if we want to clean up the unit tests first.
=> Idempotency: Address TODOs, add Changelog

.opensource/project.json, packages/rxfire/README.md
Adding a better config for the JS SDK on firebaseopensource.com.  I removed the centering on the RxJs page since that doesn't play so nice with the open source site.
N/A
N/A
=> Add open source config and page for RxFire

.vscode/settings.json, packages/rxfire/firestore/collection/index.ts, packages/rxfire/test/firestore.test.ts
* rxfire was comparing documents based off ids, this was fine before collection group queries. Here I've switched to `ref.isEqual` like I have done in AngularFire.
* When a document is modified, we were only replacing the single doc in the array; this would not always trip change detection in frameworks as `===` would still equal true on the top level. Splicing it creates a new array, which will fail `===` and trip change detection.
* Further, this was an issue with the other operations as we were using splice. I'm now slicing to clone the array before modifying.
* NIT: Visual Studio Code's settings, which are committed, were not setup to track the workspace's version of Typescript. This tripped me up a little at first.
=> rxfire: Support collection groups & a minor change detection fix

packages/firestore/src/local/simple_db.ts, packages/firestore/test/unit/local/simple_db.test.ts
Our users are still seeing IndexedDB errors on iOS 13 (using IONIC/Cordova). One of the possible reasons is that some environments might not throw DOMExceptions, which would lead us to not retry. This PR flips our logic around and only skips retries if the underlying exception is a non-Firestore exception.
Fixes https://github.com/firebase/firebase-js-sdk/issues/2232
=> Retry all non-Firestore exceptions

packages/firestore/src/local/indexeddb_mutation_queue.ts, packages/firestore/src/local/local_serializer.ts, packages/firestore/src/local/simple_db.ts
This breaks a compile test I am doing with google-closure-compiler
=> Don't use process when not available

packages/firebase/index.d.ts
Typescript currently throws a fit when trying to log either the `add_payment_info` or `page_view` events with `firebase.analytics.logEvent()`.  The error goes a little something like... 
`Argument of type '"add_payment_info"' is not assignable to parameter of type 'never'.`
These two are the only default events without parameters and also don't have function overloads defined—meaning the following line assigns them to `never`.
https://github.com/firebase/firebase-js-sdk/blob/07cd70d4e694080c0114076fe2be821c951ed75b/packages/firebase/index.d.ts#L4336
I think adding these two definitions patches things right up.
=> Include add_payment_info and page_view events

packages/installations/src/functions/get-id.test.ts, packages/installations/src/functions/get-id.ts, packages/installations/src/functions/get-token.ts, packages/installations/src/helpers/extract-app-config.ts, packages/installations/src/helpers/get-installation-entry.ts, packages/installations/src/helpers/refresh-auth-token.test.ts, packages/installations/src/helpers/refresh-auth-token.ts, packages/installations/src/util/errors.ts
There isn't any useful error information if a request that was started in a different function call fails. Instead of throwing a useless error, try it again in the current function call.
Also makes the "missing app config values" error a little more helpful.
=> Try API requests again if they failed in a different function call

packages/firebase/index.d.ts, packages/firestore-types/index.d.ts, packages/firestore/src/api/database.ts, packages/firestore/src/core/query.ts, packages/firestore/src/core/sync_engine.ts, packages/firestore/src/core/target.ts, packages/firestore/src/core/view.ts, packages/firestore/src/local/index_free_query_engine.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/query_data.ts, packages/firestore/src/local/shared_client_state.ts, packages/firestore/src/remote/remote_store.ts, packages/firestore/src/remote/serializer.ts, packages/firestore/src/util/input_validation.ts, packages/firestore/test/integration/api/query.test.ts, packages/firestore/test/integration/api/validation.test.ts, packages/firestore/test/unit/core/query.test.ts, packages/firestore/test/unit/core/view.test.ts, packages/firestore/test/unit/local/index_free_query_engine.test.ts, packages/firestore/test/unit/local/local_store.test.ts, packages/firestore/test/unit/remote/node/serializer.test.ts, packages/firestore/test/unit/specs/limbo_spec.test.ts, packages/firestore/test/unit/specs/limit_spec.test.ts, packages/firestore/test/unit/specs/listen_spec.test.ts, packages/firestore/test/unit/specs/spec_builder.ts, packages/firestore/test/unit/specs/spec_test_runner.ts
Spec tests are not in this PR, as I need to basically implement the target:query split and mapping in spec tests builder/runner. 
Figured it might be a good idea to have it reviewed without spec tests. Please let me know if you want them to be together.
=> [2.8/3] Add limitToLast implementation and tests.

packages/firestore/CHANGELOG.md, packages/firestore/src/local/indexeddb_persistence.ts, packages/firestore/src/local/simple_db.ts, packages/firestore/test/unit/local/indexeddb_persistence.test.ts
This PR:
- Makes the lease refresh idempotent by moving the `primaryStateListener` callback outside of the transaction function. Note that it call still get called with `primaryStateListener(false)`, as calling that repeatedly should not have any side effects.
- Changes transactions to obtain the IndexedDB lease even if they don't already have it.
Addresses https://github.com/firebase/firebase-js-sdk/issues/2232
=> Don't fail client if lease refresh fails

packages/firestore/src/api/credentials.ts
`this.currentUser = this.getUser();` in the constructor can return a null user even if a user is logged in. It is because the actual auth code that populates uid is asynchronous.
It is a problem because it causes an expensive and unnecessary user switching - we will initially call `this.changeListener` with a null user, then later call it with the actual user when `this.tokenListener` gets called.
https://github.com/firebase/firebase-js-sdk/pull/2137 tried to fix this issue. Its [initial fix](https://github.com/firebase/firebase-js-sdk/pull/2137/commits/bb3723a2c7edf4d895ad56aa021e756232e34407) is correct, but its final version is not. This PR is a copy of 2137's initial fix.
=> Avoid auth trigger if we haven't yet received the initial user

packages/firestore/src/platform_browser/webchannel_connection.ts
From array to string template converted for better readability
=> Use string concatenation instead of array join for making RPC URLs

packages/storage/index.ts, packages/storage/package.json, packages/storage/src/implementation/authwrapper.ts, packages/storage/src/service.ts, packages/storage/test/reference.test.ts, packages/storage/test/requests.test.ts, packages/storage/test/service.test.ts, packages/storage/test/task.test.ts, packages/storage/test/testshared.ts
https://github.com/firebase/firebase-js-sdk/pull/2316 implements the proposal.
This PR changes `@firebase/storage` to use the component platform implemented in https://github.com/firebase/firebase-js-sdk/pull/2316
https://github.com/firebase/firebase-js-sdk/pull/2316
https://github.com/firebase/firebase-js-sdk/pull/2317
=> Migrate storage to component framework

packages/auth/src/exports_auth.js, packages/database/index.node.ts, packages/database/index.ts, packages/database/package.json, packages/database/src/core/AuthTokenProvider.ts, packages/database/src/core/Repo.ts, packages/database/src/core/RepoManager.ts, packages/database/test/browser/crawler_support.test.ts, packages/database/test/helpers/util.ts
https://github.com/firebase/firebase-js-sdk/pull/2316 implements the proposal.
This PR changes `@firebase/database` to use the component platform implemented in https://github.com/firebase/firebase-js-sdk/pull/2316
https://github.com/firebase/firebase-js-sdk/pull/2316
https://github.com/firebase/firebase-js-sdk/pull/2317
=> Migrate Database to component framework

packages/functions/index.node.ts, packages/functions/index.ts, packages/functions/package.json, packages/functions/src/api/service.ts, packages/functions/src/config.ts, packages/functions/src/context.ts, packages/functions/test/browser/callable.test.ts, packages/functions/test/callable.test.ts, packages/functions/test/service.test.ts, packages/functions/test/utils.ts
https://github.com/firebase/firebase-js-sdk/pull/2316 implements the proposal.
This PR changes `@firebase/functions` to use the component platform implemented in https://github.com/firebase/firebase-js-sdk/pull/2316
https://github.com/firebase/firebase-js-sdk/pull/2316
https://github.com/firebase/firebase-js-sdk/pull/2317
https://github.com/firebase/firebase-js-sdk/pull/2323
=> Migrate functions to component framework

packages/app-types/index.d.ts, packages/installations/package.json, packages/installations/src/index.ts
firebase/firebase-js-sdk#2316 implements the proposal.
This PR changes `@firebase/installations` to use the component platform
firebase/firebase-js-sdk#2316
=> Migrate installations to component framework

packages/app-types/index.d.ts, packages/auth-interop-types/README.md, packages/auth-interop-types/index.d.ts, packages/auth-interop-types/package.json, packages/auth-interop-types/tsconfig.json, packages/auth/src/exports_auth.js, packages/firebase/externs/firebase-app-internal-externs.js
firebase/firebase-js-sdk#2316 implements the proposal.
This PR changes `@firebase/auth` to use the component platform implemented in firebase/firebase-js-sdk#2316
=> Migrate auth to component platform

packages/analytics/index.test.ts, packages/analytics/index.ts, packages/analytics/src/constants.ts, packages/analytics/src/factory.ts, packages/analytics/src/helpers.test.ts, packages/analytics/src/helpers.ts, packages/analytics/testing/gtag-script-util.ts
We previously checked for pre-existence of a gtag script by looking for `window.dataLayer`. This is not an accurate check in some cases, such as if the user is using Google Tag Manager on the page, which creates a `window.dataLayer` but does not insert a script tag to download `gtag.js`.
This change directly checks the DOM for existence of such a script tag, and we will insert it if not found.
=> Directly check for existence of gtag script tag

packages/firestore/src/api/database.ts, packages/firestore/src/api/user_data_converter.ts, packages/firestore/test/integration/api/query.test.ts
Also making another IN filters integration test run against prod.
=> Allow nested arrays for IN queries

packages/component/src/provider.ts, packages/testing/src/api/index.ts, packages/testing/test/database.test.ts
https://github.com/firebase/firebase-js-sdk/pull/2316 implements the proposal.
`@firebase/testing` is affected by this change.
This PR updates `@firebase/testing` to use the component platform implemented in https://github.com/firebase/firebase-js-sdk/pull/2316
=> Update @firebase/testing to use component framework

packages/performance/src/utils/attribute_utils.test.ts, packages/performance/src/utils/attributes_utils.ts
`prerender` is deprecated and removed from the spec according to https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilityState
Typescript has removed it from `VisibilityState` type and https://github.com/firebase/firebase-js-sdk/pull/2344 fails because of it.
This PR removes `prerender` from our own code.
=> remove prerender and unloaded from visibilityState

packages/firebase/index.d.ts, scripts/docgen/content-sources/node/toc.yaml
Documentation for functions was incorrectly being excluded from Node docs.
=> Make sure functions documentation is generated for Node

.vscode/launch.json
Forked from #2348, this adds the VSCode launch target I used to test changes inside the IDE.
=> Add RTDB Node debug target

packages/database/src/api/Database.ts, packages/database/src/core/Repo.ts, packages/database/src/core/Repo_transaction.ts, packages/database/src/core/SyncTree.ts, packages/database/src/core/util/ServerValues.ts, packages/database/test/servervalues.test.ts
Per offline discussions, it looks like this is pretty simple to add; we just change resolveDeferredValueSnapshot to also accept a cached value.
Added tests for ServeValues in general.
Forgive my lake of familiarity: do we edit packages/database-types directly? While I understand we don't actually want the feature to be exposed directly yet, it seems weird that extending ServerValues in database.ts didn't change database-types/index.ts
=> Add Database.Servervalue.increment(x)

packages/rxfire/database/object/index.ts
Fixing a bug where RxFire's `objectVal` will return an empty object if the result of `snapshot.val()` is not an object. For example:
database data:
```json
{
"counter": 7
}
```
code:
```js
fromRef(firebase.database().ref('counter')).pipe(value => console.log(value));
```
logs `{}` instead of the expected `7`.
=> rxfire: objectVal bugfix

packages/remote-config/src/remote_config.ts
`await this._storageCache.setLastFetchStatus(lastFetchStatus);` in the catch block can fail (e.g. in envs where indexeddb is not available), but the caller can't catch it because we don't catch it and the program just throws.
Refactored the code to use `async await` directly instead of wrapping fetch inside a Promise callback, so all errors will be caught and rejected properly. 
An alternative considered is to `try catch` in the `catch` block, then `reject`, but it makes the code more complicated and less readable.
It fixes https://github.com/firebase/firebase-js-sdk/issues/2373#issuecomment-558017676.
=> Reject with indexeddb errors in RemoteConfig.fetch()

packages/firestore/src/core/query.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/remote/remote_event.ts, packages/firestore/src/remote/remote_store.ts, packages/firestore/test/integration/api/query.test.ts
* s/memorized/memoized
* Disallow double-unlisten (remote store) and double-releasing (local store)
* Consolidate duplicated integration tests
* Mark synthesizeTargetChange as non-multitab
=> LimitToLast: back port some changes from android

packages/firestore/src/protos/firestore_proto_api.d.ts
"long" is not defined and throws a diagnostic error:
Error: TypeScript Diagnostic Error : ../../firebase/firebase-js-sdk/packages/firestore/src/protos/firestore_proto_api.d.ts(366,42): error TS2304: Cannot find name 'long'.
=> Don't use "long" in Proto types

packages/firebase/empty-import.d.ts
This change attempts to prevent the auto-importing of an exported `undefined` value from `firebase/empty-import`, which predominantly occurs in VS Code.
Fixes #2203
=> Firebase: Adjust undefined import causing IDE annoyances

packages/auth/src/rpchandler.js, packages/auth/test/rpchandler_test.js
Error was already present, but wasn't wired in.
=> Recognize and return TENANT_ID_MISMATCH error code

packages/firestore/src/api/credentials.ts, packages/firestore/src/local/indexeddb_index_manager.ts, packages/firestore/src/model/field_value.ts, packages/firestore/src/platform_browser/webchannel_connection.ts, packages/firestore/src/util/async_queue.ts
I am sure there are more to come... but most of the explicit return type assignments that I had earlier might not be needed anymore (https://github.com/FirebasePrivate/sdk-minifier/pull/2)
=> Small assorted fixes for better property name mangling support

packages/firestore/src/local/simple_db.ts, packages/firestore/test/util/test_platform.ts
Fixes #2404. 
In this particular instance, the user's `process` variable was defined, but `process.env` was not defined, which triggered an error when checking for `process.env.USE_MOCK_PERSISTENCE`.
=> Check for process.env in isMockPersistence

packages/messaging-types/index.d.ts, packages/messaging/src/controllers/base-controller.ts, packages/messaging/src/controllers/window-controller.ts, packages/messaging/test/controller-get-token.test.ts, packages/messaging/test/controller-interface.test.ts
Instead of returning null and expecting the user to request the notification permission, do it automatically.
Also some (not enough) refactoring of tests.
=> Request notification permission in getToken if permission is "default"

packages/performance/src/services/api_service.ts, packages/performance/src/services/remote_config_service.ts, packages/performance/src/utils/attributes_utils.ts
- Remove usage of 'any' for accessing navigator.connection -- prefer a defined interface.
- Make fields in the `ApiService` readonly where possible
- Remove the assertion operator on `ApiService.localStorage` and truly declare it as optional; Update downstream usage to reflect this.
=> Tighten the typing in the Firebase Performance package

packages/app/src/constants.ts
Installations accidentally got left out of the constant list.
=> Add installations to version logging constants

.vscode/launch.json
Due to aeeaa14361d76d3c06fead95a2fd2359b28ad62e we need to look for mocha / karma in the root node_modules folder instead of relative to packages/firestore.
=> Fix VS Code launch.json to look for mocha/karma in right location.

scripts/docgen/content-sources/js/toc.yaml, scripts/docgen/content-sources/node/toc.yaml
Needs to be added to `toc.yaml` files in order to appear in documentation.
=> Add FirestoreDataConverter to toc files

packages/firestore/src/local/shared_client_state.ts, packages/firestore/src/local/shared_client_state_schema.ts
This PR moves all the schema parts of SharedClientState to a new file. We can then use the generated .d.ts file to make sure the schema doesn't get minified.
AFAIK, this is the only file that uses a schema in WebStorage. The Zombie key is assembled as a string, and the value is also only a string.
=> Extract WebStorage schema

packages/database/package.json, packages/database/src/api/Database.ts, packages/database/src/api/Reference.ts, yarn.lock
The typing changes made in https://github.com/firebase/firebase-js-sdk/pull/2378 broke `firebase-admin` compilation which uses strict mode which is not enabled for database.
=> Fix the compiling errors for firebase-admin

packages/firestore/CHANGELOG.md, packages/firestore/src/platform_browser/webchannel_connection.ts, packages/util/src/environment.ts
There is a backend bug (b/145624756) causing our $httpHeaders query param to be ignored if the request doesn't contain an Origin header.  Via https://github.com/firebase/firebase-js-sdk/issues/1491 we've found that several environments can run into this issue so until the backend issue is fixed we are excluding them from using $httpHeaders. This may incur an extra CORS preflight round-trip in some cases, but this is much better than having our Authorization header get ignored.
=> Avoid using $httpHeaders in environments that don't send an Origin header.

packages/database/test/servervalues.test.ts
The introduction of tests that try to send increment operations to the backend has resulted in test flakiness.  Basically the emulator rejects these as invalid operations and closes the connection.  The client automatically reconnects, so _usually_ this doesn't matter.  But the SDK intentionally doesn't tolerate disconnects in the middle of a transaction, so if the disconnect happens to happen during a transaction test, then the test will fail.
I'm avoiding the problem by isolating the increment tests better (use an isolated instance of RTDB and ensures it remains offline so it doesn't even try to send the requests to the emulator).
I've opened b/146657568 to track cleaning this up once the emulator supports increment operations.
=> Fix flaky RTDB tests due to increment operations.

packages/performance/src/services/cc_service.test.ts, packages/performance/src/services/cc_service.ts, packages/performance/src/services/perf_logger.test.ts, packages/performance/src/services/perf_logger.ts
In preparation for some changes to `Logger` that will open up some methods to users, we should remove it from this internal use case that doesn't make use of any of `Logger`'s functionality anyway.
=> Remove Logger from performance backend log use case

packages/functions/src/context.ts, packages/functions/test/browser/callable.test.ts
See [this comment](https://github.com/firebase/firebase-js-sdk/pull/2421#discussion_r363010498) for context.
=> Make sure notification permissions are granted before calling getToken

integration/firestore/gulpfile.js
This change will allow us to replace firestore.js in our Integration Tests with a minified version without having to provide a minified firebase.js
Credit to @hsubox76 for figuring this all out for me.
=> Update integration tests to use firestore.js

packages/performance/CHANGELOG.md
Add changelog about proto2 -> proto3 upgrade on Firebase Performance transport.
Changelog is helpful for Firebase JS team to compose release note of new version. Released changes will be moved to public version in CHANGLOG.md.
Example: https://github.com/firebase/firebase-js-sdk/blob/master/packages/database/CHANGELOG.md
=> Add CHANGELOG for Fireperf transport update from proto2 to proto3

packages/webchannel-wrapper/package.json, packages/webchannel-wrapper/tools/build.js, yarn.lock
Get closure-library from google-closure-library instead of via closure-builder so we can control the version directly.
=> Get closure-library from google-closure-library.

packages/performance/CHANGELOG.md, packages/performance/src/resources/trace.test.ts, packages/performance/src/services/perf_logger.test.ts, packages/performance/src/services/perf_logger.ts, packages/performance/src/services/transport_service.ts
1. Changed transport format from proto2 to proto3 when dispatching performance event to Firebase service.
2. Added unit tests to validate resource (trace and network) can be serialized into new format correctly.
3. Added CHANGELOG for performance monitoring.
=> Performance Monitoring transport format upgrade from proto2 to proto3

packages/firestore/CHANGELOG.md, packages/firestore/src/platform_browser/webchannel_connection.ts, packages/util/src/environment.ts
This is a follow-up to https://github.com/firebase/firebase-js-sdk/pull/2464.
@wu-hui Can you test this with your repro extension?
@wilhuff Can you review?
@hsubox76 Can you review the util changes?
=> Fix for #1491: Disable use of $httpHeaders in browser extensions too.

.github/workflows/deploy-canary.yml
Was unsuccessful trying to set up wombat-dressing-room publish method, likely to take much longer than a few days.  Switching back to previous token so canary releases won't be blocked in the meantime.
=> Switch back to user NPM token

packages/firebase/index.d.ts
The [reference docs for `firebase.firestore.SnapshotMetadata.fromCache`](https://firebase.google.com/docs/reference/js/firebase.firestore.SnapshotMetadata.html#fromcache) are currently incorrect. They say:
> **True if the snapshot includes local writes (set() or update() calls) that haven't been committed to the backend yet.** If your listener has opted into metadata updates (via SnapshotListenOptions) you will receive another snapshot with fromCache equal to false once the client has received up-to-date data from the backend.
This looks like a partial copy-paste from [`hasPendingWrites`](https://firebase.google.com/docs/reference/js/firebase.firestore.SnapshotMetadata.html#has-pending-writes).
In this PR, I've copy pasted the correct description from `firebase-firestore-externs.js`: …
=> Small fix: Firestore's fromCache description

packages/firestore/src/local/indexeddb_remote_document_cache.ts, scripts/run_changed.js
Used a language feature that doesn't exist.  Causes check for modified files to always fail.  Tested this time to make sure it works.
=> [testing] Fix bug in check for modified files

.github/CODEOWNERS
Will assign tech writer as reviewer for changes to `packages/firebase/index.d.ts` (reference doc source) and `scripts/docgen/content-sources/` (TOC and reference doc home page content).
=> Add tech writer as codeowner for files causing doc changes.

packages/firestore/src/local/indexeddb_remote_document_cache.ts, packages/firestore/src/local/local_store.ts, packages/firestore/src/local/memory_remote_document_cache.ts, packages/firestore/src/local/remote_document_cache.ts, packages/firestore/test/integration/api_internal/database.test.ts, packages/firestore/test/unit/local/counting_query_engine.ts, packages/firestore/test/unit/local/remote_document_cache.test.ts
Goal: remove `instanceof IndexedDbRemoteDocumentCache` check in LocalStore to allow me to drop the import.
Realized: We don't even use the document result from getLastDocumentChange. So I changed it to only return the read time.
=> Remove instanceof IndexedDbRemoteDocumentCache check

packages/firestore/src/local/indexeddb_persistence.ts
This ignores the error if the primary lease is somehow lost between updateClientMetadataAndTryBecomePrimary() and maybeGarbageCollectMultiClientState(). There is no special recovery logic needed as the next primary will run the periodic GC.
Fixes https://github.com/firebase/firebase-js-sdk/issues/2555
=> Ignore primary lease loss in maybeGarbageCollectMultiClientState

packages/firestore/test/unit/specs/perf_spec.test.ts
These tests are only run on demand. One of the tests broke when we stopped accepting zero version documents in the RemoteDocumentCache
=> Fix Firestore Performance spec test

scripts/emulator-testing/emulators/firestore-emulator.ts
The emulator now sends resume tokens, which exercises more of the
system. In particular, this means that resuming queries now uses the
index-free query engine.
=> Upgrade Firestore emulator to 1.10.4

scripts/emulator-testing/emulators/firestore-emulator.ts
Rolling back #2602 
Emulator 1.10.4 causes current integration tests to fail. Rolling back to 1.8.2 for now.
=> Rollback: Upgrade Firestore emulator 1.10.4

packages/firestore/CHANGELOG.md, packages/firestore/src/api/database.ts, packages/firestore/test/integration/api/database.test.ts, scripts/emulator-testing/emulators/firestore-emulator.ts
Fixes #2606 
One downside to this approach is if the underlying `DocumentReference.set()` fails, the function name in the error message will not say `CollectionReference.add()` (see `applyFirestoreDataConverter`). I thought about how to refactor `set()` to allow the function name to be passed down, but ultimately decided that this approach is cleaner + the developer can see the stack trace and deduce that for themselves.
=> Allow Collection.add() to use custom objects
